### PR TITLE
PIT markers for Interoperability Testing: CapsuleContent

### PR DESCRIPTION
**Pull request by damoore044**
Proposing PIT markers added to these CapsuleContent tests

### CODE REVIEW

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8036
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_capsulecontent.py -k test_positive_sync_updated_repo or test_positive_capsule_sync and not test_positive_capsule_sync_ or test_positive_sync_container_repo_end_to_end --external-logging
Test Result : ========== 21 deselected, 29 warnings, 3 errors in 194.68s (0:03:14) ===========
```

**Review by vijaysawant — COMMENTED** [review]
Right now we don't mark `pit_server` for the test which uses `*_capsule_configured` fixture, right @ogajduse ?

**Comment by ogajduse** [comment]
> Right now we don't mark `pit_server` for the test which uses `*_capsule_configured` fixture, right @ogajduse ?

That is correct. Good catch.

@damoore044 please see: https://github.com/SatelliteQE/robottelo/pull/15756#pullrequestreview-2199385559

**Review by ColeHiggins2 — APPROVED** [review]
ack pending prt

**Review by vsedmik — CHANGES_REQUESTED** [review]
`@pytest.mark.pit_server` is not applicable as per previous offline communication, please remove.

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_capsulecontent.py -k 'test_positive_sync_updated_repo or test_positive_capsule_sync and not test_positive_capsule_sync_ or test_positive_sync_container_repo_end_to_end'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8099
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_capsulecontent.py -k test_positive_sync_updated_repo or test_positive_capsule_sync and not test_positive_capsule_sync_ or test_positive_sync_container_repo_end_to_end --external-logging
Test Result : ==== 1 failed, 2 passed, 21 deselected, 932 warnings in 9930.60s (2:45:30) =====
```

**Comment by damoore044** [comment]
The one failing test in above PRT is expected for now due to BZ, 
to be resolved in stream soon: [SAT-25813](https://issues.redhat.com/browse/SAT-25813)

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_capsulecontent.py -k 'test_positive_update_counts or test_positive_content_counts_for_mixed_cv'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8108
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_capsulecontent.py -k test_positive_update_counts or test_positive_content_counts_for_mixed_cv --external-logging
Test Result : ========== 2 passed, 25 deselected, 92 warnings in 1705.51s (0:28:25) ==========
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_capsulecontent.py::test_positive_content_counts_for_mixed_cv

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8110
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_capsulecontent.py::test_positive_content_counts_for_mixed_cv --external-logging
Test Result : ================= 1 passed, 14 warnings in 1946.55s (0:32:26) ==================
```

**Review by vsedmik — APPROVED** [review]

**Pull request merged**
