### PR TITLE
Make Rerun RP plugins `fail threshold` configurable

### PR DESCRIPTION
**Pull request by jyejare**
Another RP Rerun Improvement :

- [x] The Fail threshold to skip/abort the Rerun py-tests based on fail percent is not configurable.
- [x] Some nitppicks

Thanks to @mirekdlugosz for the ask !

### CODE REVIEW

**Review by omkarkhatavkar — APPROVED** [review]
ACK, please raise git lab PR for this property, it's non-blocking!

**Comment by jyejare** [comment]
@omkarkhatavkar Yes! The PR for gitlab has already been raised and I have linked this PR there.

**Review by devendra104 — APPROVED** [review]
Looks good.

**Comment by jyejare** [comment]
@SatelliteQE/airgun-tier-2-reviewers Can I get the 2nd ACK here !!

**Review by mirekdlugosz — COMMENTED** [review]
I feel like I'm missing something obvious here, but it seems this new setting never used anywhere? What's the point of adding setting that is not used?

I understand sometimes we introduce changes in phases, but that's rather for big, overarching refactors with considerable risk of introducing regressions. That change doesn't strike me as particularly big or risky. I skimmed over source and seems you only need to replace two references to hardcoded value in `pytest_plugins/rerun_rp/rerun_rp.py`.

**Comment by jyejare** [comment]
@mirekdlugosz The setting will be used when we want to skip the rerun pipeline in CI at specific fail tests percent. For now by default its 20% but this PR allows it to make it configurable.

I was not planning for this Pr as a phased update to rerun plugin. But my approach is to raise the separate PRs for improvements be its small / big. That way the PR doesnt gets hold on for non dependent improvements in same PR. 
And until and unless the PR is well tested by author , there shouldn't be the worry of regression.

**Comment by jyejare** [comment]
@mirekdlugosz Ohh Now I understood what you are talking about ! I am not sure how but the changes to the `rerun_rp.py` are missing in this PR :+1: 

Changing the PR state to Draft, until I add it !

**Comment by jyejare** [comment]
@mirekdlugosz @omkarkhatavkar @devendra104 Here are the logs where I have configured the threshold with `30%` instead of default `20%` and skipped run:
```
ERROR> pytest_plugins.rerun_rp.rerun_rp.LaunchError: The latest launch of Satellite verson 6.8.0 has 75% tests failed. Which is higher than the threshold of 30%. Examine the failures thoroughly and check for any major issue.

========================================================================================== no tests ran in 16.62 seconds =========================================================================================
```

**Comment by mshriver** [comment]
@mirekdlugosz this PR was raised in direct response to your request here:
https://github.com/SatelliteQE/robottelo/pull/7976#discussion_r484362998

@jyejare didn't want to include configurable pass/fail % in 7976, thus opened this smaller scope PR.

As you stated in that comment, our Jenkins pipelines can then adjust what their threshold is for running failed cases.

**Review by mirekdlugosz — APPROVED** [review]
Thanks, Jitendra.
ACK and merge

**Pull request merged**
