### PR TITLE
CherryPick of master PR 'Filtered robotello UI tests for Upgrade #5175'

### PR DESCRIPTION
**Pull request by jyejare**
Cherry picking the master PR 'Filtered robotello UI tests for Upgrade #5175' into 6.2.z

### CODE REVIEW

**Comment by abalakh** [comment]
@jyejare the `test_subnet.py` file contains conflicts which aren't resolved, you need to resolve them first. Basically the process should be smth like this
```
git fetch upstream
git cherry-pick 25d681d6cd8d97a11bc9d4aba7b45151a0d61583
# here cherry-picking stops because of conflicts
# resolve conflicts using any tool or IDE you prefer (i recommend PyCharm)
git cherry-pick --continue
git push origin cherrypick_UI_upgrade_tests
```

**Comment by jyejare** [comment]
@abalakh Yeah that's the correct way which I followed for cherry picking. Thanks for confirming  :)

**Comment by jyejare** [comment]
@abalakh I fixed ```test_subnet.py```, please revisit to ACK

**Comment by jyejare** [comment]
@san7ket @sghai , Need your ACKs

**Pull request merged**
