### PR TITLE
Fixing Satellite subscription name we have in the manifest now

### PR DESCRIPTION
**Pull request by jhutar**
```
pytest tests/foreman/cli/test_host.py::HostSubscriptionTestCase::test_positive_remove --no-print-logs --capture=no --exitfirst 2>&1 | tee /tmp/pytest.log
...
=================== 1 passed, 5 warnings in 1641.36 seconds ====================
```

### CODE REVIEW

**Comment by ntkathole** [comment]
ok to test : tests/test_advanced.py -k "test_positive_beta_repositories, test_positive_repositories_setup"

**Comment by jhutar** [comment]
This also needs to be backported to 6.4 and 6.5 branch. Shall I just create another PRs for that?

**Comment by vijay8451** [comment]
> This also needs to be backported to 6.4 and 6.5 branch. Shall I just create another PRs for that?

Cherry-pick would works fine for 6.4 and 6.5.

**Comment by mirzal** [comment]
> This also needs to be backported to 6.4 and 6.5 branch. Shall I just create another PRs for that?

Yes, after this is merged, cherry-pick commit in these branches and send new PRs. Best to add reference to this PR as well, so we know this is only cherry-pick and not a new thing.

**Pull request merged**
