### PR TITLE
search syntax fixes in host tests

### PR DESCRIPTION
**Pull request by pondrejk**
### Problem Statement
some automation fixes needed

### CODE REVIEW

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_host.py -k test_negative_view_parameter_by_non_admin_user

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8129
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_host.py -k test_negative_view_parameter_by_non_admin_user --external-logging
Test Result : =========== 89 deselected, 95 warnings, 1 error in 260.42s (0:04:20) ===========
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8141
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_host.py -k test_negative_view_parameter_by_non_admin_user --external-logging
Test Result : ========== 1 passed, 89 deselected, 98 warnings in 610.45s (0:10:10) ===========
```

**Review by jameerpathan111 — APPROVED** [review]

**Review by vsedmik — APPROVED** [review]

**Review by omkarkhatavkar — APPROVED** [review]

**Comment by lhellebr** [comment]
This needs to be cherrypicked to 6.16, @pondrejk

**Pull request merged**
