### PR TITLE
[6.14.z] Cherrypick of FixesForEndeavour

### PR DESCRIPTION
**Pull request by LadislavVasina1**
Cherrypick of https://github.com/SatelliteQE/robottelo/pull/14512

### CODE REVIEW

**Comment by LadislavVasina1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_jobinvocation.py -k 'test_rex_through_host_details'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6196
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_jobinvocation.py -k test_rex_through_host_details --external-logging
Test Result : =========== 1 failed, 4 deselected, 3 warnings in 1077.80s (0:17:57) ===========
```

**Comment by LadislavVasina1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_jobinvocation.py -k 'test_rex_through_host_details'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6198
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_jobinvocation.py -k test_rex_through_host_details --external-logging
Test Result : =========== 1 failed, 4 deselected, 3 warnings in 1086.30s (0:18:06) ===========
```

**Comment by LadislavVasina1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_remoteexecution.py -k 'test_positive_run_job_template_multiple_hosts_by_ip'

**Review by lhellebr — APPROVED** [review]

**Comment by LadislavVasina1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_remoteexecution.py -k 'test_positive_run_job_template_multiple_hosts_by_ip'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6201
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_remoteexecution.py -k test_positive_run_job_template_multiple_hosts_by_ip --external-logging
Test Result : ========== 1 passed, 15 deselected, 3 warnings in 1123.47s (0:18:43) ===========
```

**Comment by LadislavVasina1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_jobinvocation.py -k 'test_rex_through_host_details'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6205
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_jobinvocation.py -k test_rex_through_host_details --external-logging
Test Result : =========== 1 failed, 4 deselected, 3 warnings in 1170.89s (0:19:30) ===========
```

**Comment by LadislavVasina1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_jobinvocation.py -k 'test_rex_through_host_details'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6215
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_jobinvocation.py -k test_rex_through_host_details --external-logging
Test Result : =========== 1 failed, 4 deselected, 3 warnings in 1407.83s (0:23:27) ===========
```

**Comment by LadislavVasina1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_jobinvocation.py -k 'test_rex_through_host_details'

**Review by pondrejk — APPROVED** [review]

**Pull request merged**
