### PR TITLE
fix #4728 - add ForemanOpenscap::ArfReport permissions

### LINKED ISSUE #4728: api.test_permission.PermissionTestCase.test_positive_search - needs updating
```
E   AssertionError: {
E    "added_resource_types": [
E     "ForemanOpenscap::ArfReport"
E    ]
E   }
```

### PR DESCRIPTION
**Pull request by rplevka**
fixes: #4728
Just adding the openscap arfreport permissions to the constants.

### CODE REVIEW

**Comment by oshtaier** [comment]
Could you please provide test results?

**Comment by rplevka** [comment]
```
+ /home/jenkins/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/py.test -v --junit-xml=foreman-results.xml -m 'not stubbed' tests/foreman/api/test_permission.py
============================= test session starts ==============================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.34, pluggy-0.4.0 -- /home/jenkins/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/python2.7
cachedir: .cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/jenkins/workspace/satellite6-standalone-automation, inifile:
plugins: xdist-1.16.0, services-1.1.14, cov-2.3.1
collecting ... collected 7 items
2017-06-09 04:32:13 - conftest - DEBUG - Found WONTFIX in decorated tests ['1110476', '1156555', '1269196', '1402826', '1245334', '1221971', '1217635', '1226425', '1199150', '1204686', '1267224', '1103157', '1230902', '1214312', '1079482']
2017-06-09 04:32:13 - conftest - DEBUG - Collected 7 test cases
tests/foreman/api/test_permission.py::PermissionTestCase::test_positive_search <- robottelo/decorators/__init__.py PASSED
tests/foreman/api/test_permission.py::PermissionTestCase::test_positive_search_by_name <- robottelo/decorators/__init__.py PASSED
tests/foreman/api/test_permission.py::PermissionTestCase::test_positive_search_by_resource_type <- robottelo/decorators/__init__.py PASSED
tests/foreman/api/test_permission.py::UserRoleTestCase::test_positive_check_create PASSED
tests/foreman/api/test_permission.py::UserRoleTestCase::test_positive_check_delete PASSED
tests/foreman/api/test_permission.py::UserRoleTestCase::test_positive_check_read PASSED
tests/foreman/api/test_permission.py::UserRoleTestCase::test_positive_check_update PASSED
generated xml file: /home/jenkins/workspace/satellite6-standalone-automation/foreman-results.xml 
============================== 0 tests deselected ==============================
========================== 7 passed in 71.01 seconds ===========================
+ exit 0
```

**Comment by rplevka** [comment]
6.3 fails with some other permissions, however the purpose of this PR is just to add the OpenSCAP::Arf ones:
```
tests/foreman/api/test_permission.py:166: in test_positive_search
    self.fail(json.dumps(diff, indent=True, sort_keys=True))
E   AssertionError: {
E    "added_names": [
E     "ipmi_boot_hosts", 
E     "destroy_ssh_keys", 
E     "view_rh_search", 
E     "edit_tailoring_files", 
E     "create_ssh_keys", 
E     "view_keypairs", 
E     "view_virt_who_config", 
E     "edit_virt_who_config", 
E     "create_virt_who_config", 
E     "view_tailoring_files", 
E     "destroy_tailoring_files", 
E     "destroy_keypairs", 
E     "view_openscap_proxies", 
E     "create_tailoring_files", 
E     "view_ssh_keys", 
E     "destroy_virt_who_config"
E    ], 
E    "added_resource_types": [
E     "SshKey", 
E     "KeyPair", 
E     "ForemanVirtWhoConfigure::Config", 
E     "ForemanOpenscap::TailoringFile", 
E     "ExternalUsergroup", 
E     "Katello::Subscription"
E    ], 
E    "removed_names": [
E     "destroy_ansible_roles", 
E     "access_settings", 
E     "edit_globals", 
E     "create_globals", 
E     "destroy_globals", 
E     "ipmi_boot", 
E     "play_roles", 
E     "view_search", 
E     "import_ansible_roles", 
E     "view_globals", 
E     "view_ansible_roles"
E    ], 
E    "removed_resource_types": [
E     "CommonParameter", 
E     "ExternalUsergroups", 
E     "AnsibleRole"
E    ]
E   }
```

**Comment by sghai** [comment]
ACK

**Pull request merged**
