### PR TITLE
Add stubs for git puppet repositories.

### PR DESCRIPTION
**Pull request by svtkachenko**
Part of issue #400

If I understood correctly these stubs are mostly about `pulp-puppet-module-builder` tool but verification should be performed from Satellite's repository perspective. For now I created separate files in `tests/cli` and `tests/ui` but maybe it would be better to put them in `tests/sys` folder or maybe as separate class in `cli/test_repository.py` and `ui/test_repository.py`?

Ping @kbidarkar @sghai ^^

### CODE REVIEW

**Comment by sghai** [comment]
@svtkachenko : Since all the tests are related to mirroring git puppet repo so best place should be a separate class in `cli/test_repository.py` and `ui/test_repository.py`

@kbidarkar what do you think ?

**Comment by sghai** [comment]
@svtkachenko : Tests looks good to me.

@kbidarkar : can you please review stubs once ?

**Comment by svtkachenko** [comment]
Stubs are moved to corresponding class in repository test-suite instead of separate files.

**Comment by kbidarkar** [comment]
I did work with this tool, ```pulp-puppet-module-builder``` but me unable to recognize any of the tests here, sorry this all sounds new to me. 

Me unable to ACK as I am not aware of the testcases functionally. If any one has worked or spent time on this feature should look into this I feel.

**Comment by sghai** [comment]
@kbidarkar : no worries. Since the stubs were shared by @cswiii so he might have idea about this feature.

@cswiii : could you please review if the tests looks good ?

**Comment by cswiii** [comment]
AFAIK these cases are fine, insofar as testing functionality of importing puppet content from a GIT repo.  They were written quite long ago, but as they are fairly vanilla (base functionality), they should still be good?

I imagine you could reach out to someone like @jlsherrill if a refresher was needed, but the cases themselves seem to make sense.

**Comment by sghai** [comment]
Lets merge the stubs now and if we really need something while automating them or need to check something, we can check with dev anyways. 

Merging now.

**Pull request merged**
