### PR TITLE
Simplify API content view test

### PR DESCRIPTION
**Pull request by Ichimonji10**
Drop all references to NailGun's `client.get` method. Make use of higher level
methods instead. Run as much of test `test_subscribe_system_to_cv` as possible,
on the theory that it is better to run part of a test than no test at all. Test
results:

    $ nosetests tests/foreman/api/test_contentview.py -m test_subscribe_system_to_cv
    .
    ----------------------------------------------------------------------
    Ran 1 test in 38.156s

    OK

### CODE REVIEW

**Comment by Ichimonji10** [comment]
I'm walking through the code base one module at a time and dropping references to `client.get` where reasonable.

**Comment by sthirugn** [comment]
ACK - neat!

**Comment by omaciel** [comment]
APT

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
