### PR TITLE
Issue #4044, use new rhel73 base images

### PR DESCRIPTION
**Pull request by san7ket**
Small Change to update the constant variable to use new , rhel73 baseOS image

### CODE REVIEW

**Comment by kbidarkar** [comment]
Can you please test atleast one testcase which uses rhel73 image as content-host. Just to make sure the image is fine.

**Comment by sghai** [comment]
@san7ket : please share a test result that uses rhel73 distro just to ensure image is working fine.

**Comment by san7ket** [comment]
### >  root   distro ?:1  /robottelo  1  nosetests tests.foreman.cli.test_contenthost:ContentHostTestCase.test_positive_register_with_no_ak
> .
> ----------------------------------------------------------------------
> Ran 1 test in 231.056s
> 
> OK

Test result attached

**Comment by sghai** [comment]
ACK

**Pull request merged**
