### PR TITLE
Add a test that searches for activation keys

### PR DESCRIPTION
**Pull request by Ichimonji10**
Add a test showing that it is possible to search for an activation key belonging
to an organization. Test results:

    $ nosetests tests/foreman/api/test_activationkey.py:SearchTestCase
    .
    ----------------------------------------------------------------------
    Ran 1 test in 4.558s

    OK

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Depends on SatelliteQE/nailgun#216

**Comment by Ichimonji10** [comment]
It's a bit overkill to create a entire `SearchTestCase` class for just one test. I've done this because this PR serves as the base for [this](https://github.com/SatelliteQE/robottelo/compare/master...Ichimonji10:per-page) upcoming PR.

It's true that these sorts of pagination results are a [feature](https://bugzilla.redhat.com/show_bug.cgi?id=1247781#c4), but I plan on filing a bug anyway.

**Comment by JacobCallahan** [comment]
nice job! ACK

**Comment by elyezer** [comment]
ACK, pending dependent NailGun PR.

**Comment by omaciel** [comment]
This can now be merged once it gets rebased.

**Pull request merged**
