### PR TITLE
Adding 8 more test cases to overall docker functionality coverage according to #2642

### PR DESCRIPTION
**Pull request by oshtaier**
Depends on SatelliteQE/nailgun#180
```
nosetests tests/foreman/api/test_docker.py -m test_create_container_local_compute_resource
...
----------------------------------------------------------------------
Ran 3 tests in 42.375s

OK
```
```
nosetests tests/foreman/api/test_docker.py -m test_create_container_external_compute_resource
...
----------------------------------------------------------------------
Ran 3 tests in 41.279s

OK
```
```
nosetests tests/foreman/api/test_docker.py -m test_delete_container
..
----------------------------------------------------------------------
Ran 2 tests in 29.400s

OK
```

### CODE REVIEW

**Comment by Ichimonji10** [comment]
ACK

**Comment by Ichimonji10** [comment]
This PR depends on SatelliteQE/nailgun#180 because that PR provides a default value for the "command" field. However, it's not entirely clear that a default value is appropriate. Not all docker images have the `top` command available, and default values work best when Satellite itself provides a set of choices for a field and we're just picking one of those choices, such as [here](https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entities.py#L2724-L2728).

One way to solve this nut is to refactor the code on this end such that we don't have to pick some arbitrary value. We can do this:

```python
    def setUp(self):
        """Generate default ``DockerHubContainer`` keyword arguments.

        Generate a dict of arguments that can be used when instantiating a
        ``DockerHubContainer`` and save it as ``self.dhc_kwargs``.

        """
        self.dhc_kwargs = {
            'command': 'top',
            'name': gen_string('alphanumeric'),
            'organization': [self.org],
        }
```

We then remove redundant code from tests:

```python
    @run_only_on('sat')
    def test_create_container_local_compute_resource(self):
        """@Test: Create a container in a local compute resource

        @Feature: Docker

        @Assert: The docker container is created in the local compute resource

        """
        container = entities.DockerHubContainer(
            compute_resource=self.cr_internal,
            **self.dhc_kwargs
        ).create()
        self.assertEqual(
            container.compute_resource.read().name,
            self.cr_internal.name,
        )
```

**Comment by oshtaier** [comment]
But if we want to try different commands? That approach will not let us do that

**Comment by Ichimonji10** [comment]
Sure it will. `self.dhc_kwargs` is just a dict.

```python
self.dhc_kwargs['command'] = 'some other command'
container = entities.DockerHubContainer(
    compute_resource=self.cr_internal,
    **self.dhc_kwargs
).create()
```

**Comment by oshtaier** [comment]
Okay, sounds great :) I just wanted to have less code. Will make corresponding changes tomorrow

**Comment by Ichimonji10** [comment]
Sounds good. :smile:

**Comment by oshtaier** [comment]
```
nosetests tests/foreman/api/test_docker.py -m test_create_container_local_compute_resource
...
----------------------------------------------------------------------
Ran 3 tests in 86.916s

OK
```
```
nosetests tests/foreman/api/test_docker.py -m test_create_container_external_compute_resource
...
----------------------------------------------------------------------
Ran 3 tests in 87.995s

OK
```
```
nosetests tests/foreman/api/test_docker.py -m test_delete_container
..
----------------------------------------------------------------------
Ran 2 tests in 64.365s

OK
```

**Comment by oshtaier** [comment]
Fixed code according to @Ichimonji10 comments. Thanks for sharing good ideas and knowledge

**Comment by Ichimonji10** [comment]
ACK

**Comment by elyezer** [comment]
Good job.

ACK

**Pull request merged**
