### PR TITLE
[DONOTMERGE] New search approach implementation in UI

### LINKED ISSUE #2913: Improve handling of entities name that longer than 30 symbols in WebUI
At that moment we have implementation of that functionality on the search level. For example, `environment` entity
```
    def search(self, name):
        """Searches existing env from UI"""
        Navigator(self.browser).go_to_environments()
        if len(name) <= 30:
            element = self.search_entity(name, locators['env.env_name'])
        else:
            element = self.search_entity(
                name, common_locators['select_filtered_entity'])
        return element
```

Such approach applied on next entities:

* [ ] `Config Groups`
* [ ] `Environment`
* [ ] `Hardware Model`
* [ ] `Medium`
* [ ] `Operating System`
* [ ] `Registry`

For other entities, we tried to use short strings (not more than 8 symbols)

We have to think on one solution that should be applied on higher level, so we can remove huge amount of redundant code and add proper support of long string for all entities in WebUI

### LINKED ISSUE #2930: Standardize search functionality
The most essential part of current search approach is navigation to necessary page (which is actually performed to get system to some known state). For example:
```
    def search(self, name):
        """Searches existing Organization from UI."""
        Navigator(self.browser).go_to_org()
        return self.search_entity(name, locators['org.org_name'])
```
or
```
    def search(self, name):
        """Searches existing architecture from UI"""
        Navigator(self.browser).go_to_architectures()
        return self.search_entity(name, locators['arch.arch_name'])
```

In case, we want to get rid of search methods from all modules and move to exclusive `search_entity` usage, we should move mentioned navigation to some other level which is obviously not so easy task.
There are few options:
1) Move to test level
Example:
```
with Session(self.browser) as session:
    make_arch(session, name=test_data['name'], os_names=[test_data['os_name']])
    self.assertIsNotNone(self.architecture.search(test_data['name']))
```
changed on:
```
with Session(self.browser) as session:
    make_arch(session, name=test_data['name'], os_names=[test_data['os_name']])
    session.nav.go_to_architectures()
    self.assertIsNotNone(self.search_entity(test_data['name']), locators['arch.arch_name'])
```
pros:
- That is definitely most friendly approach from architecture point of view as navigation logic is separated from search logic.
- Flexible
- Easy to implement
- Reliable and error-tolerant approach

cons:
- A lot of redundant code will be introduced into the system
- Huge amount of testing and re-testing will be needed as we will touch every piece of code in webui

2) Move to base framework level
a) Some kind of correspondance table
```
'Organization' => go_to_org()
'Architecture' => go_to_architectures()
```
```
def search_entity(...):
    Navigator(self.browser).(check our table for required method)
...
```
```
with Session(self.browser) as session:
    self.assertIsNotNone(self.search_entity('Architecture', test_data['name']), locators['arch.arch_name'])
```
pros:
- One phase of re-test will be enough as we do not change tests logic
- Amount of code will be even decreased, so redundancy will not be introduced

cons:
- Mentioned table will look pretty ugly
- Not so flexible solution and not so easy to understand from user perspective

b) Pass entity class name as a part of navigation method name:
```
architecture => go_to_(class_name)()
org => go_to_(class_name)()
```
pros are the same
cons:
- Even less flexible solution as a) as we have more navigation methods than entities in application

3) Don't remove at all, but get search() to one format/look
Let's say that:
```
    def search(self, name):
        """Searches existing Organization from UI."""
        Navigator(self.browser).go_to_org()
        return self.search_entity(name, locators['org.org_name'])
```
is a standard that we should follow, so things like:
```
    def search(self, element_name):
        """Uses the search box to locate an element from a list of elements"""
        element = None
        strategy, value = locators['contentviews.key_name']
        searchbox = self.wait_until_element(common_locators['kt_search'])
        if searchbox:
            searchbox.clear()
            searchbox.send_keys(escape_search(element_name))
            self.click(common_locators['kt_search_button'])
            element = self.wait_until_element((strategy, value % element_name))
        return element
```
should be re-factored to have similar look
pros:
- Changes impact very small area of the code, so no extra efforts for testing required
- Easy to implement

cons:
- We are only improving things, but not solving initial problem.

### PR DESCRIPTION
**Pull request by oshtaier**
Change search method in base class to re-use in all entities classes
Fixed long string handling for all entities

Closes #2930
Closes #2913

### CODE REVIEW

**Comment by oshtaier** [comment]
Pending test results, so putting DONOTMERGE tag, but PR is ready for review

**Comment by sthirugn** [comment]
I like to see the individual commits here from the other search branch so the work done by individual folks is visible.

**Comment by oshtaier** [comment]
@sthirugn 
I, @abalakh and @kbidarkar decided as a team to squash commits. Please, confirm with @omaciel and @elyezer that we should spend time on that

**Comment by oshtaier** [comment]
@sthirugn You can find list of entities in https://github.com/SatelliteQE/robottelo/issues/2930 to see every person deidcation to that PR

**Comment by elyezer** [comment]
I sent #3017 with the @sthirugn. I prefer following that one since it will show in git history all the evolution that this feature branch had.

We also find the above practice on other projects and I think that we can try to follow that. Which is also how git docs recommends when dealing with feature branches http://www.git-scm.com/book/en/v2/Git-Branching-Branching-Workflows.

**Comment by sthirugn** [comment]
@oshtaier I agree with you that we haven't written clear rules of squashing vs. keeping the commits.  May be its time to create one. Sorry about the re-work, I just saw this PR few minutes back.
@elyezer Thank you for the new PR link and the git info.

**Comment by oshtaier** [comment]
Anyway, if someone has any comments to functionality issues - let me know :) Otherwise, free to put ACK

**Comment by oshtaier** [comment]
Or let's move our conversation to #3017

**Comment by sthirugn** [comment]
+1 to moving converastion to #3017.

This is a complex PR with lot of work - Great job @oshtaier, @abalakh, @kbidarkar, @lpramuk.

**Comment by oshtaier** [comment]
@sthirugn not a problem, we had a discussion about that and did a mistake to not involve more people to it. Anyway, that's great that get to common approach

**Comment by abalakh** [comment]
Closing in favour of #3017

**Pull request closed without merging**
