### PR TITLE
Implement extended ui.locators and changed ui logging to Fix #3606

### LINKED ISSUE #3606: Create specialized type for locators allowing direct interpolation
Currently to define a locator we use a tuple formed by **strategy** and **locator_path**:

```python
"get.element.by.link": (By.XPATH, "//a[contains(@href, '%s')]")
```

The problem is that the code turn verbose when we need to interpolate **%s** in the locator_path we should do.

```python
strategy, value = locators['get.element.by.link']
self.click((strategy, value % 'foo/bar'))
```

We can just create a specialized type from tuple as

```python
class Locator(tuple):
    """A tuple that allows direct interpolation of second element"""
    def __mod__(self, data):
        strategy, value = self
        return strategy, value % data
```

We should use the above type instead of a tuple in locators:

```python
"get.element.by.link": Locator(By.XPATH, "//a[contains(@href, '%s')]")
```
 and then we can do direct interpolation, saving us of defining extra **strategy, value** variables everytime

```python
self.click(locators['get.element.by.link'] % 'foo/bar')
```

### PR DESCRIPTION
**Pull request by rochacbruno**
Closes #3606 

Introduced a new base dataModel for locators It works as a taxonomy-tree with autovivification of nested items (endless tree with auto created nodes)

A Locator is a **Node**, and can have nested nodes infinitely, every time an attribute is accessed if it does not exists a new default empty **Locator node** is created for that attribute and that allows the
`taxonomy-like` definitions.

Examples:

It can be initialized as an empty root node

```python
menu_locators = Locator() # or LocatorDict() shortcut
menu_locators.home = Locator(By.XPATH, "//a[@class='home']")
menu_locators.config = Locator(By.XPATH, "//div[@class='config']")
```

The same can be achieved in a cleaner syntax

```python
menu_locators.config.users = (By.XPATH, "//a[@class='users']")  # old style tuple
menu_locators.home = Locator.XPATH("//a[@class='home']")
menu_locators.home = Locator.ID("name")
menu_locators['users.login'] = Locator.TAG("a")
```

Internally every node will be a **Locator** instance, even if initialized with a 2 elements tuple

Root nodes are created automatically, no need to declare it before

```python
menu_locators.dashboard.tasks.monitor_panel = (By.XPATH, '//div/m/%s')
menu_locators.dashboard.tasks.monitor_panel.button = (By.ID, 'button')
```

**dashboard, tasks, monitor_panel** is created as empty nodes and will not contain a valid locator acting only as a **node** for nested locators. 

```python
print(menu_locators.dashboard)
<contains=['tasks']>
print(menu_locators.dashboard.tasks)
<contains=['monitor_panel']>
```

But **monitor_panel** is a locator and it is also node containing a button

```python
print(menu_locators.dashboard.tasks.monitor_panel)
<|strategy=xpath|value=//div/m/%s|contains=['button']>
```

The **repr** for the object enclosed in `<|...|>` will always show strategy, value and contains (if nested locators): 

Locator **location** attributes are

```python
menu_locators.dashboard.tasks.monitor_panel._strategy
'xpath'
menu_locators.dashboard.tasks.monitor_panel._value
'//div/m/%s'
```

But it still works as a simple tuple (to keep backwards compatibility with tuple style and keep working with selenium accessing it by index[x] or *unpacking)

```python
strategy, value = menu_locators.dashboard.tasks.monitor_panel
print strategy, value
xpath //div/m/%s
```

The %s placeholders can be **direct interpolated** resulting in a new Locator, no more need to define unused **strategy, value** only for interpolation.

```python
panel_a = menu_locators.dashboard.tasks.monitor_panel % 'panel-a'
#or
panel_a = menu_locators["dashboard.tasks.monitor_panel"] % 'panel-a'

print(panel_a)
<|strategy=xpath|value=//div/m/panel-a>
```

Auto completion works in Ipython and other IDES

```python
dir(menu_locators)
['dashboard', '_store', '_strategy', '_value']
dir(menu_locators.dashboard)
['tasks', '_store', '_strategy', '_value']
```

It can still be used also as a dictionary (optionally using LocatorDict (just a shortcut for backwards compatibility)

```python
locator = Locator({'navbar.spinner': (By.XPATH, '//div/spinner')})
locator['navbar']
<contains=['spinner']>
```

All those forms of access returns the same object

```python
locator['navbar.spinner']
locator['navbar']['spinner']
locator['navbar'].spinner
locator.navbar['spinner']
locator.navbar.spinner
<|strategy=xpath|value=//div/spinner>
```

And also can be used to assign new locators

```python
locator['menu.home.button'] = Locator('xpath', '//div/foo/bar')
locator.menu.home.button = ('xpath', '//div/foo/bar')
locator['menu']['home']['button'] = ('xpath', '//div/foo/bar')
```

## Caveats

If a node doesn't exists it is created on the fly

```python
locator.foo.bla.zaz.blaz.catz  # created 5 nodes all empty
```
So there is no `false` node

```python
hasattr(locator.bazinga)  # always True
getattr(locator, 'schubrebers')  # always get a new node Locator
```

But it can be achieved using the contains statement

```python
'bazinga' in locator  # False
locator.bazinga  # created a new node 'bazinga'
'bazinga' in locator  # True
```

## Logging

The location objects has no more logs, for UI the logging was moved to BrowserDriver `execute` method, because it is better to see the logs in the sequence of command execution instead of the sequence of locator access. (see next comments)

# auto complete
Auto complete works in iPython 5.0
robottelo_shell1

auto complete in iPython for nested locators
robottelo_shell2

### CODE REVIEW

**Comment by rochacbruno** [comment]
Tested:

```
ui/test_organization
==================== 9 passed, 1 skipped in 155.95 seconds =====================
```

From S-Auto build 163  (complete UI suite run on build 164)

tests.foreman.ui.test_organization.OrganizationTestCase.test_negative_update 

```
2016-07-28 12:13:17 - DEBUG - Started Test: OrganizationTestCase/test_negative_update
2016-07-28 12:13:18 - DEBUG - Starting container with ID "fcf2a07828aa116a4224f39d366fc16e407d56b6e70a45a5b5b19067fa9a059e"

2016-07-28 12:13:25 - DEBUG - Locator node: login
2016-07-28 12:13:25 - DEBUG - Getting locator: username
2016-07-28 12:13:25 - DEBUG - Accessing locator "login_login" by "id"
2016-07-28 12:13:26 - DEBUG - Updating field:login.username with:lPNXTkiouU

2016-07-28 12:13:26 - DEBUG - Locator node: login
2016-07-28 12:13:26 - DEBUG - Getting locator: password
2016-07-28 12:13:26 - DEBUG - Accessing locator "login_password" by "id"
2016-07-28 12:13:27 - DEBUG - Updating field:login.password with:changeme

2016-07-28 12:13:28 - DEBUG - Getting locator: submit
2016-07-28 12:13:28 - DEBUG - Accessing locator "commit" by "name"

2016-07-28 12:13:33 - DEBUG - Locator node: notif
2016-07-28 12:13:33 - DEBUG - Getting locator: error
2016-07-28 12:13:33 - DEBUG - Accessing locator "//div[contains(@class, 'jnotify-notification-error')]" by "xpath"
2016-07-28 12:13:33 - DEBUG - NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].

2016-07-28 12:13:33 - DEBUG - Locator node: menu
2016-07-28 12:13:33 - DEBUG - Getting locator: any_context
2016-07-28 12:13:33 - DEBUG - Accessing locator "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a" by "xpath"

2016-07-28 12:13:33 - DEBUG - Locator node: org
2016-07-28 12:13:33 - DEBUG - Getting locator: manage_org
2016-07-28 12:13:34 - DEBUG - Accessing locator "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@class='manage-menu' and contains(@href, 'organizations')]" by "xpath"

2016-07-28 12:13:35 - DEBUG - Locator node: navbar
2016-07-28 12:13:35 - DEBUG - Getting locator: spinner
2016-07-28 12:13:35 - DEBUG - Accessing locator "//div[@id='turbolinks-progress']" by "xpath"

2016-07-28 12:13:36 - DEBUG - Locator node: org
2016-07-28 12:13:36 - DEBUG - Getting locator: new
2016-07-28 12:13:36 - DEBUG - Accessing locator "//a[contains(@href, '/organizations/new')]" by "xpath"

2016-07-28 12:13:37 - DEBUG - Locator node: org
2016-07-28 12:13:37 - DEBUG - Getting locator: name
2016-07-28 12:13:37 - DEBUG - Accessing locator "organization_name" by "id"

2016-07-28 12:13:37 - DEBUG - Locator node: org
2016-07-28 12:13:37 - DEBUG - Getting locator: name
2016-07-28 12:13:37 - DEBUG - Accessing locator "organization_name" by "id"
2016-07-28 12:13:38 - DEBUG - Updating field:org.name with:LouhCPSKIC

2016-07-28 12:13:38 - DEBUG - Getting locator: submit
2016-07-28 12:13:38 - DEBUG - Accessing locator "commit" by "name"

2016-07-28 12:13:43 - DEBUG - Locator node: org
2016-07-28 12:13:43 - DEBUG - Getting locator: proceed_to_edit
2016-07-28 12:13:43 - DEBUG - Accessing locator "//a[@class='btn btn-default' and contains(@href, '/edit')]" by "xpath"

2016-07-28 12:13:43 - DEBUG - Getting locator: submit
2016-07-28 12:13:43 - DEBUG - Accessing locator "commit" by "name"

2016-07-28 12:13:51 - DEBUG - Searching for: LouhCPSKIC
2016-07-28 12:13:51 - DEBUG - Locator node: menu
2016-07-28 12:13:51 - DEBUG - Getting locator: any_context
2016-07-28 12:13:51 - DEBUG - Accessing locator "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a" by "xpath"

2016-07-28 12:13:51 - DEBUG - Locator node: org
2016-07-28 12:13:51 - DEBUG - Getting locator: manage_org
2016-07-28 12:13:52 - DEBUG - Accessing locator "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@class='manage-menu' and contains(@href, 'organizations')]" by "xpath"

2016-07-28 12:13:53 - DEBUG - Locator node: navbar
2016-07-28 12:13:53 - DEBUG - Getting locator: spinner
2016-07-28 12:13:53 - DEBUG - Accessing locator "//div[@id='turbolinks-progress']" by "xpath"

2016-07-28 12:13:54 - DEBUG - Locator node: org
2016-07-28 12:13:54 - DEBUG - Getting locator: org_name
2016-07-28 12:13:54 - DEBUG - Getting locator: search
2016-07-28 12:13:54 - DEBUG - Accessing locator "search" by "id"

2016-07-28 12:13:54 - DEBUG - Getting locator: search_button
2016-07-28 12:13:55 - DEBUG - Accessing locator "//button[contains(@type,'submit')]" by "xpath"

2016-07-28 12:13:57 - DEBUG - Getting locator: select_filtered_entity
2016-07-28 12:13:57 - DEBUG - Accessing locator "//td/a[contains(@href,'organizations')]/span[contains(.,'%s')]" by "xpath"
2016-07-28 12:13:57 - DEBUG - Locator value replaced to: //td/a[contains(@href,'organizations')]/span[contains(.,'LouhCPSKIC')]
2016-07-28 12:13:57 - DEBUG - Searching for: LouhCPSKIC

2016-07-28 12:13:57 - DEBUG - Locator node: menu
2016-07-28 12:13:57 - DEBUG - Getting locator: any_context
2016-07-28 12:13:57 - DEBUG - Accessing locator "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a" by "xpath"

2016-07-28 12:13:57 - DEBUG - Locator node: org
2016-07-28 12:13:57 - DEBUG - Getting locator: manage_org
2016-07-28 12:13:58 - DEBUG - Accessing locator "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@class='manage-menu' and contains(@href, 'organizations')]" by "xpath"

2016-07-28 12:13:59 - DEBUG - Locator node: navbar
2016-07-28 12:13:59 - DEBUG - Getting locator: spinner
2016-07-28 12:13:59 - DEBUG - Accessing locator "//div[@id='turbolinks-progress']" by "xpath"

2016-07-28 12:13:59 - DEBUG - Locator node: org
2016-07-28 12:13:59 - DEBUG - Getting locator: org_name
2016-07-28 12:13:59 - DEBUG - Getting locator: search
2016-07-28 12:13:59 - DEBUG - Accessing locator "search" by "id"

2016-07-28 12:14:00 - DEBUG - Getting locator: search_button
2016-07-28 12:14:00 - DEBUG - Accessing locator "//button[contains(@type,'submit')]" by "xpath"

2016-07-28 12:14:02 - DEBUG - Getting locator: select_filtered_entity
2016-07-28 12:14:02 - DEBUG - Accessing locator "//td/a[contains(@href,'organizations')]/span[contains(.,'%s')]" by "xpath"
2016-07-28 12:14:02 - DEBUG - Locator value replaced to: //td/a[contains(@href,'organizations')]/span[contains(.,'LouhCPSKIC')]

2016-07-28 12:14:03 - DEBUG - Locator node: org
2016-07-28 12:14:03 - DEBUG - Getting locator: name
2016-07-28 12:14:03 - DEBUG - Accessing locator "organization_name" by "id"

2016-07-28 12:14:07 - DEBUG - Locator node: org
2016-07-28 12:14:07 - DEBUG - Getting locator: name
2016-07-28 12:14:07 - DEBUG - Accessing locator "organization_name" by "id"
2016-07-28 12:14:07 - DEBUG - Updating field:org.name with:064115927012428415348337566

2016-07-28 12:14:09 - DEBUG - Getting locator: submit
2016-07-28 12:14:09 - DEBUG - Accessing locator "commit" by "name"

2016-07-28 12:14:14 - DEBUG - Getting locator: name_haserror
2016-07-28 12:14:14 - DEBUG - Accessing locator "//label[@for='name']/../../div[contains(@class,'has-error')]" by "xpath"

2016-07-28 12:14:14 - DEBUG - Locator node: login
2016-07-28 12:14:14 - DEBUG - Getting locator: gravatar
2016-07-28 12:14:14 - DEBUG - Accessing locator "//img[contains(@class, 'avatar')]" by "xpath"

2016-07-28 12:14:15 - DEBUG - Locator node: menu
2016-07-28 12:14:15 - DEBUG - Getting locator: account
2016-07-28 12:14:15 - DEBUG - Accessing locator "//a[@id='account_menu']" by "xpath"

2016-07-28 12:14:15 - DEBUG - Locator node: menu
2016-07-28 12:14:15 - DEBUG - Getting locator: sign_out
2016-07-28 12:14:15 - DEBUG - Accessing locator "//a[@id='menu_item_logout']" by "xpath"


2016-07-28 12:14:17 - DEBUG - Locator node: navbar
2016-07-28 12:14:17 - DEBUG - Getting locator: spinner
2016-07-28 12:14:17 - DEBUG - Accessing locator "//div[@id='turbolinks-progress']" by "xpath"

2016-07-28 12:14:18 - DEBUG - Finished Test: OrganizationTestCase/test_negative_update
2016-07-28 12:14:19 - DEBUG - Stopping container with ID "fcf2a07828aa116a4224f39d366fc16e407d56b6e70a45a5b5b19067fa9a059e"
```

**Comment by rochacbruno** [comment]
Waiting other conflicting PRs to be merged in order to rebase this branch and put it to review
(also pending build 164 of S-Auto)

**Comment by rochacbruno** [comment]
# logging

Example: `py.test -s tests/foreman/ui/test_lifecycleenvironment.py -k test_positive_update`

Output on logging:

```console
robottelo            - DEBUG - Started Test: LifeCycleEnvironmentTestCase/test_positive_update
robottelo.ui.browser - DEBUG - Starting container with ID "b33274b4328c6748ce114580d131731cc261406b775cec26a6e4edf989156767"
robottelo.ui.browser - DEBUG - newSession: {'desiredCapabilities': {'platform': 'ANY', 'browserName': 'firefox', 'version': '', 'marionette': False, 'javascriptEnabled': True}}
robottelo.ui.browser - DEBUG - windowMaximize: {'windowHandle': 'current'}
robottelo.ui.browser - DEBUG - get: {'url': 'FQDN.redhat.com:443'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'id', 'value': 'login_login'} id: 0
robottelo.ui.browser - DEBUG - findElement: {'using': 'id', 'value': 'login_login'} id: 0
robottelo.ui.browser - DEBUG - sendKeysToElement: {'id': u'0', 'value': u'WVJbdaHESZ'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'id', 'value': 'login_password'} id: 1
robottelo.ui.browser - DEBUG - sendKeysToElement: {'id': u'1', 'value': 'changeme'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'name', 'value': 'commit'} id: 2
robottelo.ui.browser - DEBUG - clickElement: {'id': u'2'}
robottelo.ui.base    - DEBUG - NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"} id: 3
robottelo.ui.browser - DEBUG - mouseMoveTo: {'element': u'3'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'org-menu')]/a"} id: 4
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'loc-menu')]/a"} id: 5
robottelo.ui.base    - DEBUG - GoToSelectOrg: JQWibgybmd
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"} id: 3
robottelo.ui.browser - DEBUG - mouseMoveTo: {'element': u'3'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "(//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]//li/a[@data-toggle='dropdown'])[1]"} id: 4
robottelo.ui.browser - DEBUG - mouseMoveTo: {'element': u'4'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': u"//div[contains(@style,'static') or contains(@style,'fixed')]//a[@href='/organizations/clear']/../../li/a[contains(.,'JQWibgybmd')]|//div[contains(@style,'static') or contains(@style,'fixed')]//a[@href='/organizations/clear']/../../li/a/span[contains(@data-original-title, 'JQWibgybmd')]"} id: 6
robottelo.decorators - INFO - Bugzilla bug 1328627 not in cache. Fetching.
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[@id='turbolinks-progress']"} id: 7
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[@id='turbolinks-progress']"} id: 8
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"} id: 9
robottelo.ui.browser - DEBUG - mouseMoveTo: {'element': u'9'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'org-menu')]/a"} id: 10
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"} id: 9
robottelo.ui.browser - DEBUG - clickElement: {'id': u'9'}
robottelo.ui.browser - DEBUG - mouseMoveTo: {'xoffset': -150, 'yoffset': -150}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='content_menu']"} id: 11
robottelo.ui.browser - DEBUG - mouseMoveTo: {'element': u'11'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_environments']"} id: 12
robottelo.ui.browser - DEBUG - clickElement: {'id': u'12'}
robottelo.decorators - DEBUG - Bugzilla bug 1328627 found in cache.
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[@id='turbolinks-progress']"} id: 13
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//a[contains(@ui-sref, 'environments.new')]"} id: 14
robottelo.ui.browser - DEBUG - clickElement: {'id': u'14'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'id', 'value': 'name'} id: 15
robottelo.ui.browser - DEBUG - findElement: {'using': 'id', 'value': 'name'} id: 15
robottelo.ui.browser - DEBUG - sendKeysToElement: {'id': u'15', 'value': u'uQFXWcWHFV'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//button[contains(@ng-click,'Save')]"} id: 16
robottelo.ui.browser - DEBUG - clickElement: {'id': u'16'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='content_menu']"} id: 17
robottelo.ui.browser - DEBUG - mouseMoveTo: {'element': u'17'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_environments']"} id: 18
robottelo.ui.browser - DEBUG - clickElement: {'id': u'18'}
robottelo.decorators - DEBUG - Bugzilla bug 1328627 found in cache.
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[@id='turbolinks-progress']"} id: 13
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': u"//a[contains(@ui-sref, 'environment.details') and contains(.,'uQFXWcWHFV')]"} id: 19
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='content_menu']"} id: 17
robottelo.ui.browser - DEBUG - mouseMoveTo: {'element': u'17'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_environments']"} id: 18
robottelo.ui.browser - DEBUG - clickElement: {'id': u'18'}
robottelo.decorators - DEBUG - Bugzilla bug 1328627 found in cache.
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[@id='turbolinks-progress']"} id: 13
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': u"//a[contains(@ui-sref, 'environment.details') and contains(.,'uQFXWcWHFV')]"} id: 19
robottelo.ui.browser - DEBUG - clickElement: {'id': u'19'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//form[@bst-edit-text='environment.name']//i[contains(@class,'fa-edit')]"} id: 20
robottelo.ui.browser - DEBUG - clickElement: {'id': u'20'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//form[@bst-edit-text='environment.name']/div/input"} id: 21
robottelo.ui.browser - DEBUG - sendKeysToElement: {'id': u'21', 'value': u'BTggVFCsXr'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//form[@bst-edit-text='environment.name']//button"} id: 22
robottelo.ui.browser - DEBUG - clickElement: {'id': u'22'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//form[@bst-edit-textarea='environment.description']//i[contains(@class,'fa-edit')]"} id: 23
robottelo.ui.browser - DEBUG - clickElement: {'id': u'23'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//form[@bst-edit-textarea='environment.description']/div/textarea"} id: 24
robottelo.ui.browser - DEBUG - sendKeysToElement: {'id': u'24', 'value': u'tgwsHItlPg'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//form[@bst-edit-textarea='environment.description']//button"} id: 25
robottelo.ui.browser - DEBUG - clickElement: {'id': u'25'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='content_menu']"} id: 17
robottelo.ui.browser - DEBUG - mouseMoveTo: {'element': u'17'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_environments']"} id: 18
robottelo.ui.browser - DEBUG - clickElement: {'id': u'18'}
robottelo.decorators - DEBUG - Bugzilla bug 1328627 found in cache.
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[@id='turbolinks-progress']"} id: 13
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': u"//a[contains(@ui-sref, 'environment.details') and contains(.,'BTggVFCsXr')]"} id: 26
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//img[contains(@class, 'avatar')]"} id: 27
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//a[@id='account_menu']"} id: 28
robottelo.ui.browser - DEBUG - mouseMoveTo: {'element': u'28'}
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//a[@id='menu_item_logout']"} id: 29
robottelo.ui.browser - DEBUG - clickElement: {'id': u'29'}
robottelo.decorators - DEBUG - Bugzilla bug 1328627 found in cache.
robottelo            - DEBUG - Finished Test: LifeCycleEnvironmentTestCase/test_positive_update
robottelo.ui.browser - DEBUG - Stopping container with ID "b33274b4328c6748ce114580d131731cc261406b775cec26a6e4edf989156767"

```

**Comment by rochacbruno** [comment]
@abalakh @oshtaier I want to know what you think about the new logging style above.

**Comment by rochacbruno** [comment]
Test results for UI in `satellite6-standalone-automation/170`

**Comment by oshtaier** [comment]
Really like the format. I little bit afraid that we can have too large amount of data, but in general looks good
nitpicks:
1) `GoToSelectOrg` -> `Selecting Organization`
2) 
```
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_environments']"} id: 18
robottelo.ui.browser - DEBUG - clickElement: {'id': u'18'}
```
Really like to change if we can:
```
robottelo.ui.browser - DEBUG - findElement: id: 18 {'using': 'xpath', 'value': "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_environments']"}
robottelo.ui.browser - DEBUG - clickElement: {'id': u'18'}
```
3) Didn't go through the code, so if we don't have explanation the approach of assigning these ids to elements, will be really nice to have it, because it is not obvious for me why we have order like this:
```
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': "//div[@id='turbolinks-progress']"} id: 13
robottelo.ui.browser - DEBUG - findElement: {'using': 'xpath', 'value': u"//a[contains(@ui-sref, 'environment.details') and contains(.,'BTggVFCsXr')]"} id: 26
```

**Comment by rochacbruno** [comment]
@oshtaier I'll change to **Selecting Organization** and put the element id first.

That **id** is the element **id** given by selenium webdriver, we do not control the ids, each selenium command which selects a new element to the elementTree gives sequential ID to it.

In robottelo.properties there is a list of selenium commands that will be logged, we can add or remove commands from there.

That case from 13 to 26 is because some elements were taken between by commands not being logged. (example: waitForElementand others I choose to suppress)

**Comment by rochacbruno** [comment]
@oshtaier your comments has been addressed

1) changed to **Selecting Organization**

2) **id** is now in the front of log message for better visualization (great idea :+1:  )

3) Some commands are not logged, if elements were assigned in that commands they will not appear in the sequence, in robottelo.properties is possible to choose which **selenium** commands are logged.

`log_driver_commands=newSession,windowMaximize,get,findElement,sendKeysToElement,clickElement,mouseMoveTo`

also it is possible to define formatters for each command log.

**Comment by abalakh** [comment]
mind blown
Awesome change, i really like the new model for locators. :+1: 
What i really like in each of your improvement PRs is how you're covering all the possible use cases and make helpers/models universal and accessible/callable in any way user might like, at the same time backward compatibility is preserved. Although this way it's becoming really hard to suggest any improvement as all the ways i could want to use it are implemented already :smile:

**Comment by rochacbruno** [comment]
@sthirugn maybe it is better to branch for 6.2 before applying this change

**Comment by abalakh** [comment]
Regarding the code - ACK from me. I haven't looked through the new locator model definition very carefully (just briefly), but it seems ok for me, and everything else is ok for sure.

My only suggestion is to add at least 1-line short docstrings for all the overriden methods in `Locator` model (e.g. `__getattr__`,`__mod__`, `__eq__` etc), shortly explaining why we have custom implementation - like you've done with [LocatorValue __mod__](https://github.com/SatelliteQE/robottelo/pull/3635/files#diff-1959e5eefc11a77b171234b3f99c17b5R14), as those methods are not trivial and sometimes they use some tricks so better to have short explanations for them not to be forced to go through the code later to understand what's going on.

**Comment by rochacbruno** [comment]
@abalakh I added comments on every method

**Comment by sghai** [comment]
ACK.. Nice changes. I really like logging but user may need to keep on updating them by adding/removing. Best part  about logging change is that with the execution flow , we can easily debug test failure. Also, good to have separated common, menu and tab locators.

I don't have any comments.  It just looks good.

**Pull request merged**
