### PR TITLE
Fixing permissions for snap14.1

### PR DESCRIPTION
**Pull request by oshtaier**
```
nosetests tests/foreman/api/test_permission.py
.......
----------------------------------------------------------------------
Ran 7 tests in 341.445s

OK
```

### CODE REVIEW

**Comment by abalakh** [comment]
Is that permission removal intended change?

**Comment by oshtaier** [comment]
Dunno. Checking every permission change with development team seems as too consuming operation, and actually we never did that in the past

**Comment by sthirugn** [comment]
ACK

**Comment by elyezer** [comment]
@oshtaier last time hammer_commands.json was massively updated, I checked with a dev to make sure it was at least sane.

The good part about checking if this is a intended change is because they could remove stuff and the build can be missing something. Off course if you don't fell tha it will break something then you can just update and go.

Not suggesting anything, just saying what I used to do.

**Pull request merged**
