### PR TITLE
[6.12.z] Bump pytest from 8.1.0 to 8.1.1

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
### Problem Statement
Need to solve https://github.com/SatelliteQE/robottelo/issues/14329

### Solution
This PR will solve that.  

### Related Issues
https://github.com/SatelliteQE/robottelo/issues/14329

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo\r
pytest: tests/foreman/ -m 'build_sanity'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6229
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ -m build_sanity --external-logging
Test Result : ======== 11 passed, 5817 deselected, 94 warnings in 1864.18s (0:31:04) =========
```

**Review by Gauravtalreja1 — APPROVED** [review]

**Comment by Satellite-QE** [comment]
testing here only

**Comment by Satellite-QE** [comment]
**PRT Result**Build Number:8311Build Status: UNSTABLEPRT Comment: pytest tests/foreman/maintain/test_health.py -k test_positive_health_check_by_tags --external-loggingTest Result: ========== 2 failed, 35 deselected, 90 warnings in 1467.38s (0:24:27) ==========

**Comment by Satellite-QE** [comment]
**PRT Result**
Build Number:8311Build Status: UNSTABLEPRT Comment: pytest tests/foreman/maintain/test_health.py -k test_positive_health_check_by_tags --external-loggingTest Result: ========== 2 failed, 35 deselected, 90 warnings in 1467.38s (0:24:27) ==========

**Pull request merged**
