### PR TITLE
Companion to Broker #170

### PR DESCRIPTION
**Pull request by JacobCallahan**
This PR should be merged after the above Broker PR has been merged.
This update's the version and the name of an attribute we need to keep.

Note: Checks won't pass until the new version of Broker is released.

### CODE REVIEW

**Comment by JacobCallahan** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_rhcloud_inventory.py tests/foreman/cli/test_rhcloud_inventory.py tests/foreman/cli/test_rhcloud_insights.py tests/foreman/ui/test_rhcloud_inventory.py tests/foreman/ui/test_rhcloud_insights.py
broker: 170

**Comment by JacobCallahan** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_rhcloud_inventory.py tests/foreman/cli/test_rhcloud_inventory.py tests/foreman/cli/test_rhcloud_insights.py tests/foreman/ui/test_rhcloud_inventory.py tests/foreman/ui/test_rhcloud_insights.py
broker: 170

**Comment by JacobCallahan** [comment]
PRT failures are unrelated to this change.

**Comment by adarshdubey-star** [comment]
Breaking locally with `E           concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.` 

I tried cleaning all the running containers and still same result!

**Comment by adarshdubey-star** [comment]
@JacobCallahan can this go in now ? , I see the broker PR merged for multiple container checkout!

**Comment by JacobCallahan** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_rhcloud_inventory.py tests/foreman/cli/test_rhcloud_inventory.py tests/foreman/cli/test_rhcloud_insights.py tests/foreman/ui/test_rhcloud_inventory.py tests/foreman/ui/test_rhcloud_insights.py

**Comment by Gauravtalreja1** [comment]
@adarshdubey-star Do you expect PRT failures?

**Comment by adarshdubey-star** [comment]
> @adarshdubey-star Do you expect PRT failures?

I see nothing getting passed here! might be a infra issue

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_rhcloud_inventory.py tests/foreman/cli/test_rhcloud_inventory.py tests/foreman/cli/test_rhcloud_insights.py tests/foreman/ui/test_rhcloud_inventory.py tests/foreman/ui/test_rhcloud_insights.py

**Comment by adarshdubey-star** [comment]
Saw the logs, and the failing cases are not because of the above change we can go ahead and merge this if we see the same result with the above PRT run. @Gauravtalreja1 @JacobCallahan

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
