### PR TITLE
Remove unnecessary coverage

### LINKED ISSUE #2183: Automation failure : test names listed below
TestNames : 
tests.foreman.api.test_multiple_paths.DoubleCheckTestCase.test_post_and_get_11_Host
tests.foreman.api.test_host.HostsTestCase.test_bz_1120800

Error says 
422 Client Error: Unprocessable Entity

please fix it 
thanks

### PR DESCRIPTION
**Pull request by oshtaier**
Closes #2183

### CODE REVIEW

**Comment by oshtaier** [comment]
tests.foreman.api.test_multiple_paths.DoubleCheckTestCase.test_post_and_get_11_Host is not reproducible neither locally nor on Jenkins
image

**Comment by oshtaier** [comment]
Removed ```tests.foreman.api.test_host.HostsTestCase.test_bz_1120800``` as it is invalid per 'https://bugzilla.redhat.com/show_bug.cgi?id=1120800' and can't be reused in any suitable way

**Comment by elyezer** [comment]
I think @Ichimonji10 should take a look on this.

If it is OK, then you got my ACK.

**Comment by Ichimonji10** [comment]
ACK

**Comment by Ichimonji10** [comment]
Please rebase.

**Pull request merged**
