### PR TITLE
remove rhel6 support from scap test and skip test due to bz 2211437

### PR DESCRIPTION
**Pull request by vijaysawant**
- Parameterised OpenSCAP test was failing due to various reasons, as per discussion we decided to remove the support for rhel6 from scap.
- Also due to regression issue/BZ #2211437 test was failing (in Stream/6.14.0) for rhel7 & rhel8 as well, so added skip marker.
- Test would not run in CI.
- In 6.12 test was failing for rhel6 after running the Ansible playbook (python version issue)

### CODE REVIEW

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_openscap.py::test_positive_oscap_run_via_ansible

**Review by shweta83 — APPROVED** [review]
Ack. Thanks for fixing this issue.

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_openscap.py -k test_positive_oscap_run_via_ansible

**Comment by shweta83** [comment]
@vijaysawant Non Blocker comment: As discussed, Let's try to merge these 2 test cases into single but we need to check that the second test case is valid anymore or not. You can take this effort in different PR.

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_openscap.py -k test_positive_oscap_run_via_ansible

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_openscap.py -k "test_positive_oscap_run_via_ansible"

**Review by jyejare — APPROVED** [review]

**Pull request merged**
