### PR TITLE
Remove sleeps and make cron expression more accurate

### PR DESCRIPTION
**Pull request by sambible**
### Problem Statement
The sleeps in these tests result in inconsistent behavior and the cron expression is malformed, leading to 2 seperate faliures. This PR will fix both.

### Solution
Removed the sleep by setting max_tries to 20 on the task poll, reformatted the cron expression to always accurately set the sync time to 5 minutes after the plan is created. 5 minutes is required here due to slow interactions with the UI sometimes resulting in the product not being added until after the sync time had passed.

trigger: test-robottelo
pytest: tests/foreman/ui/test_contenthost.py -k 'test_positive_synchronize_custom_product_custom_cron_real_time'

### CODE REVIEW

**Comment by sambible** [comment]
rigger: test-robottelo
pytest: tests/foreman/ui/test_contenthost.py -k 'test_positive_synchronize_custom_product_custom_cron_real_time'

**Review by dosas — APPROVED** [review]

**Comment by sambible** [comment]
Basically the UI test through navigation, and filling out different pages would take more than 3 minutes to add the product to the syncplan, which would mean the trigger for syncing would have already fired, and the product wouldn't get actually synced. 5 minutes seems to be (10 or 20 runs locally) to be consistent in giving enough time for the UI to process all the stuff, and still not be too long.

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contenthost.py -k 'test_positive_synchronize_custom_product_custom_cron_real_time'

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_syncplan.py -k 'test_positive_synchronize_custom_product_custom_cron_real_time'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7151
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_syncplan.py -k test_positive_synchronize_custom_product_custom_cron_real_time --external-logging
Test Result : =========== 1 passed, 4 deselected, 20 warnings in 854.64s (0:14:14) ===========
```

**Review by shweta83 — APPROVED** [review]

**Comment by dosas** [comment]
> What did you achieve by changing 3 minutes to 5? Otherwise, LGTM.

@sambible That's funny when I run the downstream tests the polling is now failing because the ui is too fast :D
Would you be open to a PR changing the `search rate` to 15:  15 * 20 / 60 = 5 So even for the fastest UI we would be withing the 5 minute mark.

**Pull request merged**
