### PR TITLE
Add a test case for metadata repair on capsule complete sync

### PR DESCRIPTION
**Pull request by vsedmik**
### Problem Statement
We are missing coverage for the customer case listed bellow

### Solution
This PR proposes a test case to ensure that the complete capsule sync repairs the repository metadata.

### Related Issues
https://issues.redhat.com/browse/SAT-28575

### PRT test Cases example
Requires https://github.com/Katello/katello/pull/11168
```
trigger: test-robottelo
pytest: tests/foreman/api/test_capsulecontent.py -k complete_sync_fixes_metadata
Katello:
  katello: 11168
```

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_capsulecontent.py -k complete_sync_fixes_metadata
Katello
  katello: 11168

**Comment by vsedmik** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_capsulecontent.py -k complete_sync_fixes_metadata
Katello
  katello: 11168
```

**Comment by vsedmik** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_capsulecontent.py -k complete_sync_fixes_metadata
Katello:
  katello: 11168
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 9198
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_capsulecontent.py -k complete_sync_fixes_metadata --external-logging
Test Result : ========== 1 passed, 25 deselected, 39 warnings in 2238.96s (0:37:18) ==========
```

**Review by chris1984 — COMMENTED** [review]
@vsedmik would a good 2nd test case after the repair and metadata have been verified to have a client that is connected to the capsule, try a `yum repolist` to verify it can pull down the metadata correctly? Or would that be to hard to mock out?

**Comment by vsedmik** [comment]
> @vsedmik would a good 2nd test case after the repair and metadata have been verified to have a client that is connected to the capsule, try a `yum repolist` to verify it can pull down the metadata correctly? Or would that be to hard to mock out?

@chris1984 Actually we could extend this one to use the `rhel_contenthost`, register it via AK to the capsule and `dnf repolist/update/install/whatever` there. No mocking, just one extra VM used inside this test case. I was thinking if it's worth it and thought the assertion for restored artifacts would be enough. But if you think it's worth it we can do it.

**Review by pondrejk — APPROVED** [review]

**Comment by vsedmik** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_capsulecontent.py -k complete_sync_fixes_metadata
Katello:
  katello: 11168
```

**Review by chris1984 — APPROVED** [review]
Looks great and thanks for updating the test @vsedmik

**Pull request merged**
