### PR TITLE
SAT-23362-update-fixture-as-per-new-feature(6.16)

### PR DESCRIPTION
**Pull request by vijaysawant**
### Problem Statement
[1] Component Audit: SAT-23362
`test_positive_delete_rhel_repo`
`test_positive_sync_repo_null_contents_changed`
`test_positive_sync_kickstart_check_os`
`test_positive_recreate_pulp_repositories`
`test_positive_sync_rh_repos`
6.16 satellite doesn't support sca disable org, because tests were using fixture `*_entitlement_manifest_org`

[2] During TFA, found test `test_positive_delete_rhel_repo` was failing due to airgun issue
Error - `IndexError: list index out of range` This was due to wrong search box and search button

[3] During TFA, found test `test_positive_sync_kickstart_check_os` was failing due to keyError `KeyError: 'rhel8 + "_bos"'`

### Solution
[1] Update fixture, this solution is only applicable to stream version of satellite.

[2] Update airgun view and entities, PR mentioned in Related Issues section and applicable for new UI `6.15.Z` and `Stream` 

[3] Changed robottelo constants key for `REPOSET>kickstart>distro` from 
`rhel8` to `rhel8_bos`
`rhel9` to `rhel9_bos`
Link [robottelo/constants/__init__.py](https://github.com/SatelliteQE/robottelo/pull/14673/files#diff-9a55ae74469aa91ad5efb2b9068f73174467cd0c00d45abf7d35f9f2277a7632)

### Related Issues
Airgun PR: https://github.com/SatelliteQE/airgun/pull/1315 (Merged)

### CODE REVIEW

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_repository.py -k 'test_positive_delete_rhel_repo'

**Comment by vijaysawant** [comment]
**Robottelo-pr-testing**
Error message:
```wait_for.TimedOutError: Could not do 'lambda defined as `lambda: all(node.progress is None for node in repo_nodes),`' at /opt/app-root/lib64/python3.11/site-packages/airgun/entities/sync_status.py:42 in time```

It's not related to current change.

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_repository.py -k 'test_positive_delete_rhel_repo'
airgun: 1315

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_repository.py -k 'test_positive_sync_repo_null_contents_changed'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6355
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_repository.py -k test_positive_sync_repo_null_contents_changed --external-logging
Test Result : ========== 1 passed, 164 deselected, 4 warnings in 695.54s (0:11:35) ===========
```

**Review by damoore044 — APPROVED** [review]

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6353
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_repository.py -k test_positive_delete_rhel_repo --external-logging
Test Result : ========== 1 failed, 32 deselected, 5 warnings in 4391.59s (1:13:11) ===========
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6354
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_repository.py -k test_positive_delete_rhel_repo --external-logging
Test Result : ========== 1 failed, 32 deselected, 5 warnings in 4389.50s (1:13:09) ===========
```

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_repository.py -k 'test_positive_delete_rhel_repo'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6387
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_repository.py -k test_positive_delete_rhel_repo --external-logging
Test Result : ========== 1 failed, 32 deselected, 5 warnings in 4428.77s (1:13:48) ===========
```

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_repository.py -k 'test_positive_sync_kickstart_check_os'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6390
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_repository.py -k test_positive_sync_kickstart_check_os --external-logging
Test Result : ========== 4 passed, 161 deselected, 76 warnings in 923.70s (0:15:23) ==========
```

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_repository.py -k 'test_positive_recreate_pulp_repositories'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6393
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_repository.py -k test_positive_recreate_pulp_repositories --external-logging
Test Result : =========== 164 deselected, 3 warnings, 1 error in 703.31s (0:11:43) ===========
```

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_repository.py -k 'test_positive_recreate_pulp_repositories'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6395
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_repository.py -k test_positive_recreate_pulp_repositories --external-logging
Test Result : ========== 1 passed, 164 deselected, 4 warnings in 749.10s (0:12:29) ===========
```

**Comment by omkarkhatavkar** [comment]
@vijaysawant Did you missed this code to update https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_repositories.py#L119 ?

**Comment by vijaysawant** [comment]
> @vijaysawant Did you missed this code to update https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_repositories.py#L119 ?

Yes, as the constants value updated then corresponding keys need to be updated.
Do you see any other test which need to be updated with this keyname? @omkarkhatavkar

**Comment by omkarkhatavkar** [comment]
@vijaysawant try to run tests that use kickstart from reposet.

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_repositories.py -k 'test_positive_disable_rh_repo_with_basearch'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6411
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_repositories.py -k test_positive_disable_rh_repo_with_basearch --external-logging
Test Result : =========== 4 deselected, 12 warnings, 1 error in 653.26s (0:10:53) ============
```

**Comment by vijaysawant** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_repositories.py -k 'test_positive_disable_rh_repo_with_basearch'
env:
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.15'
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: '13.0'
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6412
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_repositories.py -k test_positive_disable_rh_repo_with_basearch --external-logging
Test Result : =========== 1 passed, 4 deselected, 13 warnings in 755.92s (0:12:35) ===========
```

**Review by omkarkhatavkar — APPROVED** [review]

**Pull request merged**
