### PR TITLE
Remove confusingly named test case in cv

### PR DESCRIPTION
**Pull request by latran**
This test case is confusing, unnecessary, low priority, and plainly makes no sense.  The main goal is to subscribe to a repo, but it seems to be more focused on testing filters.  Both are captured else where already so I'm deleting this test case.

### CODE REVIEW

**Review by mirekdlugosz — APPROVED** [review]
I guess at one point in the past gofer/katello-agent was hard requirement for host subscription? Yeah, we don't do that anymore.

ACK

**Comment by JacobCallahan** [comment]
@mirekdlugosz that is the strange part about this test, katello-agent was never a requirement for registration...

**Review by JacobCallahan — APPROVED** [review]
ACK

**Review by swadeley — COMMENTED** [review]
ACK

**Pull request merged**
