### PR TITLE
ddt removal in ui config groups tests

### PR DESCRIPTION
**Pull request by sthirugn**
Test result:
```
Finding files... done.
Importing test modules ... done.

----------------------------------------------------------------------
Ran 4 tests in 332.130s

OK
```

### CODE REVIEW

**Comment by sthirugn** [comment]
Do not merge this until https://github.com/SatelliteQE/robottelo/pull/2893 is completed as this uses a helper function from the other PR.

**Comment by oshtaier** [comment]
ACK
There are few things that will be nice to check/fix (e.g. removing `generate_strings_list` and use our more usual data function), but it is not in scope of that PR

Feel free to merge after #2893 is merged, second ACK and rebase :)

**Comment by sthirugn** [comment]
yep generate_strings_list() will be addressed in the effort for standardizing test data effort.

**Comment by elyezer** [comment]
ACK

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
