### PR TITLE
CLI Import - prepare_import_data() refactor

### PR DESCRIPTION
**Pull request by lpramuk**
CLI Import - prepare_import_data() refactor
    
    * move prepare_import_data() out of helpers (very specific to be there)
    * move all dataset preparations into prepare_import_data()
    * fix misnomer for custom-channels

### CODE REVIEW

**Comment by lpramuk** [comment]
oops, an irrelevant commit....looks like it's time to learn git rebase backwards ....

**Comment by lpramuk** [comment]
I need to merge #2918 before this one

**Comment by lpramuk** [comment]
```
$ nosetests -vs tests.foreman.cli.test_import:TestImport
...
----------------------------------------------------------------------
Ran 28 tests in 5926.039s

OK (SKIP=1)
```

**Comment by rplevka** [comment]
ACK

**Comment by elyezer** [comment]
ACK

**Pull request merged**
