### PR TITLE
Comp Eval-Combine all possible scenarios from api product and api repository

### PR DESCRIPTION
**Pull request by vijaysawant**
### Problem Statement
1. Component audit - SAT-25973 Merge all possible product related scenarios into on test case
Initially targeted 3 test cases (`test_positive_create_with_name`, `test_positive_create_with_label`, `test_positive_create_with_description`)

Other tests can be merge along with above
`test_positive_update_description`
`test_positive_update_name_to_original`
`test_positive_delete`

`test_positive_update_organization` need to remove as it has skipped during execution due to BZ-1310422 (Current status CLOSE WONTFIX)

2. Component audit - SAT-25974 Merge 2 negative scenarios into on test function
`test_negative_create_url`
`test_negative_create_with_url_with_special_characters`

### Solution
1. commit 1st - New test case name `test_positive_product_end_to_end`
2. commit 2nd - New test case name `test_negative_create_url_with_invalid_and_special_characters`

### PRT test Cases example
```
trigger: test-robottelo
pytest: tests/foreman/api/test_product.py -k 'test_positive_product_end_to_end'
```

```
trigger: test-robottelo
pytest: tests/foreman/api/test_repository.py -k 'test_negative_create_url_with_invalid_and_special_characters'
```

### CODE REVIEW

**Comment by vijaysawant** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_product.py -k 'test_positive_product_end_to_end'
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8010
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_product.py -k test_positive_product_end_to_end --external-logging
Test Result : ========== 1 passed, 27 deselected, 36 warnings in 660.33s (0:11:00) ===========
```

**Review by sambible — APPROVED** [review]

**Comment by vijaysawant** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_repository.py -k 'test_negative_create_url_with_invalid_and_special_characters'
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8023
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_repository.py -k test_negative_create_url_with_invalid_and_special_characters --external-logging
Test Result : ========= 8 passed, 161 deselected, 210 warnings in 576.58s (0:09:36) ==========
```

**Comment by vijaysawant** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_repository.py -k 'test_negative_create_url_with_invalid_and_special_characters'
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8026
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_repository.py -k test_negative_create_url_with_invalid_and_special_characters --external-logging
Test Result : ========= 161 deselected, 174 warnings, 8 errors in 210.74s (0:03:30) ==========
```

**Review by vsedmik — APPROVED** [review]

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8030
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_repository.py -k test_negative_create_url_with_invalid_and_special_characters --external-logging
Test Result : ========= 161 deselected, 174 warnings, 8 errors in 206.00s (0:03:26) ==========
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8034
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_repository.py -k test_negative_create_url_with_invalid_and_special_characters --external-logging
Test Result : ========= 161 deselected, 174 warnings, 8 errors in 204.42s (0:03:24) ==========
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8061
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_repository.py -k test_negative_create_url_with_invalid_and_special_characters --external-logging
Test Result : ========= 8 passed, 161 deselected, 212 warnings in 689.81s (0:11:29) ==========
```

**Review by jyejare — APPROVED** [review]

**Pull request merged**
