### PR TITLE
Modify test_positive_ansible_custom_role to cover non-admin user scenario

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
### Problem Statement
Currently, test_positive_ansible_custom_role covers only admin scenario, and as part of component audit its suggest to modify this test to cover non-admin user scenario

### Solution
Parametrizing the existing test to cover both admin and non-admin user scenarios with few more changes

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleREX::test_positive_ansible_custom_role

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7097
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleREX::test_positive_ansible_custom_role --external-logging
Test Result : ================= 2 passed, 131 warnings in 1575.04s (0:26:15) =================
```

**Review by shubhamsg199 — APPROVED** [review]
LGTM

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleREX::test_positive_ansible_custom_role

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7220
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleREX::test_positive_ansible_custom_role --external-logging
Test Result : ================= 2 passed, 138 warnings in 1701.42s (0:28:21) =================
```

**Review by pnovotny — APPROVED** [review]
LGTM

**Pull request merged**
