### PR TITLE
[6.14.z] fix in test_permission

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13879

### Problem Statement
The result format changed, possibly due to https://github.com/SatelliteQE/robottelo/pull/13737

### Solution
adjusting

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_auth.py -k test_positive_password_reset

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_auth.py -k test_positive_password_reset

**Comment by jameerpathan111** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_auth.py -k test_positive_password_reset

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 30
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_auth.py -k test_positive_password_reset
Test Result : ================= 1 failed, 11 warnings in 1442.30s (0:24:02) ==================
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_auth.py -k test_positive_password_reset

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6095
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_auth.py -k test_positive_password_reset --external-logging
Test Result : ================== 1 failed, 1 warning in 1817.12s (0:30:17) ===================
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_auth.py -k test_positive_password_reset

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6127
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_auth.py -k test_positive_password_reset --external-logging
Test Result : ================== 1 failed, 1 warning in 1580.83s (0:26:20) ===================
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_auth.py -k test_positive_password_reset

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6131
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_auth.py -k test_positive_password_reset --external-logging
Test Result : ================== 1 passed, 1 warning in 1510.38s (0:25:10) ===================
```

**Pull request merged**
