### PR TITLE
Added 'CRUD' tests to Architecture via API.

### PR DESCRIPTION
**Pull request by omaciel**
Added 5 new basic 'CRUD' tests for Architecture via the API.

### CODE REVIEW

**Comment by omaciel** [comment]
```bash
(robottelo)┌[omaciel☮Ogs-MacBook-Pro.local]-(~/hacking/robottelo)-[git://master ✗]-
└> nosetests -v tests/foreman/api/test_architecture.py
@Test: Create an architecture and associate it with an OS. ... ok
@Test: Create architecture providing an invalid initial name. ... ok
@Test: Create architecture then update its name to an invalid name. ... ok
@Test: Create an architecture providing the initial name. ... ok
@Test: Create architecture and then delete it. ... ok
@Test: Create architecture then update its name to another ... ok
@Test: Do not wrap API calls in an extra hash. ... SKIP: Skipping test due to open Bugzilla bug #1151220.

----------------------------------------------------------------------
Ran 7 tests in 24.546s

OK (SKIP=1)
```

**Comment by omaciel** [comment]
@sthirugn as promised, here's the new PR.

**Comment by elyezer** [comment]
ACK

**Comment by sthirugn** [comment]
ACK

**Comment by omaciel** [comment]
Thanks @sthirugn and @elyezer

**Pull request merged**
