### PR TITLE
minor fixes for status code, vm.hostname

### PR DESCRIPTION
**Pull request by anarang**

### CODE REVIEW

**Comment by oshtaier** [comment]
Could you please put here few details regarding these fixes? Like why we need them

**Comment by elyezer** [comment]
ACK, pending @oshtaier comment.

**Comment by elyezer** [comment]
@anarang ping.

**Comment by anarang** [comment]
@oshtaier these were the minor fixes which were missed from the previous pull request. As I moved the entire method for configuring the rhai client to vm.py so rhai.vm.hostname won't work but vm.hostname would. Regarding the status code, as per the requirement I changed it to 0.

**Comment by anarang** [comment]
@elyezer  pong, I am on PTO and thus delay in response.

**Comment by oshtaier** [comment]
ACK pending rebase

**Pull request merged**
