### PR TITLE
Now puppet classes can only be created by API's.

### PR DESCRIPTION
**Pull request by kbidarkar**
* Confirmed from sat6 and foreman-dev channel
* Removed the Puppet Class creation tests.
* Update and deletion may be possible but need to be tested via
  API's.

Doing it via the API's needs to be looked into. Will raise a separate issue for this task.

### CODE REVIEW

**Comment by kbidarkar** [comment]
This task will be handled in issue https://github.com/SatelliteQE/robottelo/issues/1814

**Comment by Ichimonji10** [comment]
Is the intent here to drop UI-based puppet class creation, then add back in API-based puppet class creation?

**Comment by kbidarkar** [comment]
yes, Add API-based puppet class creation and check if updating and deleting of puppet-class works via the UI.

**Comment by Ichimonji10** [comment]
ACK

**Comment by sghai** [comment]
ACK

**Pull request merged**
