### PR TITLE
New Hosts UI - Manage columns test

### PR DESCRIPTION
**Pull request by pnovotny**
Test case for new feature Hosts / All Hosts -> Manage columns.

This adds test case for the new feature 'Manage columns'
in new web UI Hosts / All Hosts.

It sets different custom columns to be displyed or hidden
and checks if the changes are applied to the hosts table.

Related airgun PR: https://github.com/SatelliteQE/airgun/pull/820

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
Can one of the admins verify this patch?

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: -k test_positive_manage_table_columns tests/foreman/ui/test_host.py
airgun: 820

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: -k test_positive_manage_table_columns tests/foreman/ui/test_host.py
airgun: 820

**Review by lhellebr — APPROVED** [review]

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_manage_table_columns 
airgun: 820

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_manage_table_columns
airgun: 820

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_manage_table_columns
airgun: 820

**Comment by pnovotny** [comment]
Done, thanks!

**Comment by Gauravtalreja1** [comment]
@pnovotny Great, could you fix pre-commit checks and try running PRT now?

**Comment by pnovotny** [comment]
@Gauravtalreja1 pre-commit errors fixed. Let's see if the PRT will run now...

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_manage_table_columns
airgun: 820

**Review by pondrejk — APPROVED** [review]

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_manage_table_columns
airgun: 820

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_manage_table_columns
airgun: 820

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_manage_table_columns
airgun: 820

**Pull request merged**
