### PR TITLE
[6.14.z] HTTP Proxy UI fixes

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14646

### Proposed changes
Just two fixes and one extension to address the component eval goals.

### PRT test Cases example
trigger: test-robottelo
pytest: tests/foreman/ui/test_http_proxy.py
airgun: 1311

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_http_proxy.py
airgun: 1311

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6344
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_http_proxy.py --external-logging
Test Result : ================= 8 failed, 98 warnings in 1127.31s (0:18:47) ==================
```

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_http_proxy.py
airgun: 1318

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6386
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_http_proxy.py --external-logging
Test Result : ================= 8 passed, 190 warnings in 2107.63s (0:35:07) =================
```

**Pull request merged**
