### PR TITLE
Test: Delete published content-view version from UI

### PR DESCRIPTION
**Pull request by sghai**
Implemented test to remove CV version from UI.

### CODE REVIEW

**Comment by sghai** [comment]
Referencing issue #1905

**Comment by sghai** [comment]
```
@Test: Delete a content-view version associated to 'Library' ... ok

----------------------------------------------------------------------
Ran 1 test in 218.243s

OK
```

**Comment by elyezer** [comment]
ACK

**Comment by Ichimonji10** [comment]
ACK

**Pull request merged**
