### PR TITLE
[6.4] FIX UI test_smartclassparameter

### PR DESCRIPTION
**Pull request by ldjebran**
tests made from the beginning to work in one thread, tried many things to make them work in multi process (locking ...) nothing helped and they will never work in multi process env (perhaps only a full redesign will help).
```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v tests/foreman/ui_airgun/test_smartclassparameter.py
============================================ test session starts ============================================
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /home/dlezz/.pyenv/versions/3.6.6/envs/robottelo/bin/python
cachedir: .pytest_cache
shared_function enabled - ON - scope: ffff - storage: file
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: wait-for-1.0.9, xdist-1.22.5, services-1.2.1, mock-1.10.0, forked-0.2, cov-2.5.1
collecting 9 items                                                                                          2018-09-28 14:06:39 - conftest - DEBUG - BZ deselect is disabled in settings

collected 9 items                                                                                           

tests/foreman/ui_airgun/test_smartclassparameter.py::test_positive_create_matcher_attribute_priority PASSED [ 11%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_positive_create_matcher_merge_override PASSED [ 22%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_negative_create_matcher_merge_override PASSED [ 33%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_positive_create_matcher_merge_default PASSED [ 44%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_negative_create_matcher_merge_default PASSED [ 55%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_positive_create_matcher_avoid_duplicate PASSED [ 66%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_negative_create_matcher_avoid_duplicate PASSED [ 77%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_positive_view_yaml_output_after_resubmit_array_type PASSED [ 88%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_positive_view_yaml_output_after_resubmit_yaml_type PASSED [100%]

======================================== 9 passed in 709.36 seconds =========================================
```

### CODE REVIEW

**Comment by ldjebran** [comment]
@oshtaier I found a way to mark the whole module will refactor this.

**Comment by oshtaier** [comment]
thank you!

**Comment by ldjebran** [comment]
```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v -m 'run_in_one_thread and tier2 and not stubbed'  tests/foreman/ui_airgun/test_smartclassparameter.py
============================================ test session starts ============================================
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /home/dlezz/.pyenv/versions/3.6.6/envs/robottelo/bin/python
cachedir: .pytest_cache
shared_function enabled - ON - scope: ffff - storage: file
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: wait-for-1.0.9, xdist-1.22.5, services-1.2.1, mock-1.10.0, forked-0.2, cov-2.5.1
collecting 9 items                                                                                          2018-09-28 15:30:14 - conftest - DEBUG - BZ deselect is disabled in settings

collected 9 items                                                                                           

tests/foreman/ui_airgun/test_smartclassparameter.py::test_positive_create_matcher_attribute_priority PASSED [ 11%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_positive_create_matcher_merge_override PASSED [ 22%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_negative_create_matcher_merge_override PASSED [ 33%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_positive_create_matcher_merge_default PASSED [ 44%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_negative_create_matcher_merge_default PASSED [ 55%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_positive_create_matcher_avoid_duplicate PASSED [ 66%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_negative_create_matcher_avoid_duplicate PASSED [ 77%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_positive_view_yaml_output_after_resubmit_array_type PASSED [ 88%]
tests/foreman/ui_airgun/test_smartclassparameter.py::test_positive_view_yaml_output_after_resubmit_yaml_type PASSED [100%]

======================================== 9 passed in 764.64 seconds =========================================
```

**Comment by ldjebran** [comment]
with not run_in_one_thread
```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v -m 'not run_in_one_thread and tier2 and not stubbed'  tests/foreman/ui_airgun/test_smartclassparameter.py
============================================ test session starts ============================================
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /home/dlezz/.pyenv/versions/3.6.6/envs/robottelo/bin/python
cachedir: .pytest_cache
shared_function enabled - ON - scope: ffff - storage: file
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: wait-for-1.0.9, xdist-1.22.5, services-1.2.1, mock-1.10.0, forked-0.2, cov-2.5.1
collecting 9 items                                                                                          2018-09-28 15:52:09 - conftest - DEBUG - BZ deselect is disabled in settings

collected 9 items / 9 deselected                                                                            

======================================= 9 deselected in 0.05 seconds ========================================
```

**Comment by ldjebran** [comment]
@oshtaier yes

**Pull request merged**
