### PR TITLE
Add coverage checking

### PR DESCRIPTION
**Pull request by elyezer**
Add target to make file to locally check coverage and enable coverage
checking to Travis.

### CODE REVIEW

**Comment by oshtaier** [comment]
Could you please show test run results on your local environment?
I mean running `make test-robottelo-coverage` to see that is actually passing and generate necessary report

**Comment by elyezer** [comment]
@oshtaier it runs py.test to check robottelo tests and create a coverage report.

```
$ make test-robottelo-coverage
py.test --cov --cov-config=.coveragerc tests/robottelo
================================ test session starts ================================
platform linux -- Python 3.4.2, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/elyezer/code/robottelo, inifile: 
plugins: cov-2.2.0
collected 49 items 

tests/robottelo/test_api_utils.py ..
tests/robottelo/test_cli.py .....
tests/robottelo/test_datafactory.py ....
tests/robottelo/test_decorators.py .............
tests/robottelo/test_hammer.py .......
tests/robottelo/test_helpers.py ...........
tests/robottelo/test_ssh.py .
tests/robottelo/test_vm.py ......
------------------ coverage: platform linux, python 3.4.2-final-0 -------------------
Name                           Stmts   Miss  Cover
--------------------------------------------------
robottelo/__init__.py              0      0   100%
robottelo/api/__init__.py          0      0   100%
robottelo/api/utils.py            31     19    39%
robottelo/cli/__init__.py          0      0   100%
robottelo/cli/base.py            168     89    47%
robottelo/cli/hammer.py           89      5    94%
robottelo/config/__init__.py       2      0   100%
robottelo/config/casts.py         25     13    48%
robottelo/config/settings.py     354    203    43%
robottelo/constants.py            77      0   100%
robottelo/datafactory.py          47      1    98%
robottelo/decorators.py          129     64    50%
robottelo/helpers.py              64     28    56%
robottelo/ssh.py                  78     41    47%
robottelo/vm.py                  157     83    47%
--------------------------------------------------
TOTAL                           1221    546    55%

============================= 49 passed in 1.32 seconds =============================
```

**Comment by omaciel** [comment]
ACK

**Comment by oshtaier** [comment]
So, should we make sure that we do not decrease coverage before each commit?

**Comment by omaciel** [comment]
It would be a good thing to make sure we keep a certain coverage level and perhaps have Travis fail if a commit decreases coverage...

**Comment by oshtaier** [comment]
Ok, I see
ACK

**Comment by oshtaier** [comment]
Please rebase

**Comment by elyezer** [comment]
Rebased

**Pull request merged**
