### PR TITLE
changed string type to utf8

### PR DESCRIPTION
**Pull request by vijaysawant**
- test `test_positive_list_tailoring_file` was failing due to the error `Skipping data chunk due to 'utf-8' codec can't decode byte`
- by changing string_type of tailing file, it is expected to read strings

### CODE REVIEW

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap_tailoringfiles.py -k test_positive_list_tailoring_file

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap_tailoringfiles.py test_positive_list_tailoring_file

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap_tailoringfiles.py -k test_positive_list_tailoring_file

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap_tailoringfiles.py -k test_positive_list_tailoring_file

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap_tailoringfiles.py -k test_positive_list_tailoring_file

**Comment by devendra104** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap_tailoringfiles.py -k test_positive_list_tailoring_file
pod_resources_size: extra_large

**Comment by devendra104** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap_tailoringfiles.py -k test_positive_list_tailoring_file -n 2
pod_resources_size: extra_large

**Review by adarshdubey-star — APPROVED** [review]
Ack

**Review by Griffin-Sullivan — APPROVED** [review]

**Pull request merged**
