### PR TITLE
Fixing menu navigation procedure

### PR DESCRIPTION
**Pull request by oshtaier**
Just very plausible idea on fixing our 'Docker browser' issue for user and probably some other functionality areas.
@abalakh performed all the testings on the local Docker containers interfaces. Seems that current fix helped to resolve our problem
Let's try to submit current PR and trigger the job on CI as we do not have consistent failures locally even without the fix

### CODE REVIEW

**Comment by oshtaier** [comment]
Small sanity check
```
nosetests tests/foreman/ui/test_user.py -m test_positive_update_username 
.
----------------------------------------------------------------------
Ran 1 test in 365.349s

OK
```

**Comment by abalakh** [comment]
Results without the fix:
```python
============================= test session starts ==============================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile:
plugins: xdist-1.13.1, repeat-0.2
gw0 I / gw1 I
gw0 [57] / gw1 [57]
 
scheduling tests via LoadScheduling
..ss..sF...s...Fsss..ss.F..........ssssss.F...s..........
============== 4 failed, 37 passed, 16 skipped in 3147.88 seconds ==============
```
(Same picture like we have on jenkins)

Test results after the fix:
```python
============================= test session starts ==============================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
gw0 I / gw1 I
gw0 [57] / gw1 [57]

scheduling tests via LoadScheduling
..ss.s.....s.....sss.ss...........ssssss......s..........
=================== 41 passed, 16 skipped in 2909.50 seconds ===================
```
Second attempt:
```python
============================= test session starts ==============================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
gw0 I / gw1 I
gw0 [57] / gw1 [57]

scheduling tests via LoadScheduling
..ss.s......s....sss.ss...........ssssss......s..........
=================== 41 passed, 16 skipped in 2882.26 seconds ===================
```

The issue is not 100% reproducible locally, so there's a chance it wasn't actually fixed and we're just lucky and receiving good results, but the only way to reproduce it is to run whole module, and it takes around 1 hour locally, so it's pretty hard to validate the fix, let's just merge this and check if that helps.

**Comment by abalakh** [comment]
ACK

**Comment by sghai** [comment]
ACK

**Comment by rplevka** [comment]
@oshtaier, @abalakh, Just a friendly tip for experimental changes - better than pushing such changes into master straight away, we should use Standalone automation job in jenkins - this job now supports custom robottelo repos, so you simply point the build to your fork/branch and test it.

**Pull request merged**
