### PR TITLE
[6.14.z] - remove the all nailgun imports from UI folder

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
#### Problem Statement

We are using the direct imports from the nailgun rather than directly using from target_sat

#### Solution

Direct Imports Removed: We've cleaned up our codebase by eliminating direct imports from the Nailgun package.

Using target_sat, module_target_sat, class_target_sat: Modified the API calls and using the target_sat.api. pattern for all API calls.

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/ -m e2e

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6101
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/ -m e2e --external-logging
Test Result : = 2 failed, 24 passed, 786 deselected, 1076 warnings, 14 errors in 8124.14s (2:15:24) =
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/

**Comment by Gauravtalreja1** [comment]
@omkarkhatavkar Could you rebase and update this PR?

**Comment by omkarkhatavkar** [comment]
@Gauravtalreja1 @jyejare Rebase Done !

**Review by pondrejk — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
@omkarkhatavkar Could you rebase this PR again ?

**Comment by omkarkhatavkar** [comment]
@pnovotny @Gauravtalreja1 @pondrejk  Can we merge this ?

**Comment by pnovotny** [comment]
ACK

**Review by JacobCallahan — APPROVED** [review]

**Pull request merged**
