### PR TITLE
Convert tests/upgrades/test_yum_plugins.py to pytest

### PR DESCRIPTION
**Pull request by tpapaioa**
Pre-upgrade test, on a 6.8.5 Satellite w/ rhel7 server and satellite tools repos enabled and synced:

```
# rm -f /var/tmp/robottelo_pre_upgrade_failed_tests.json
# rm -f ~/.config/nailgun/*.json
# source ../jenkins-configs/compute_resources.conf
# source ../jenkins-configs/sat6_upgrade.conf
# export SATELLITE_HOSTNAME=XXX
# export RHEV_SAT_HOST=$SATELLITE_HOSTNAME
# FROM_VERSION=6.8 TO_VERSION=6.9 pytest -m pre_upgrade -s tests/upgrades/test_yum_plugins.py
[...]
collected 2 items / 1 deselected / 1 selected

tests/upgrades/test_yum_plugins.py .
[...]
=== 1 passed, 1 deselected, 61 warnings in 479.07s (0:07:59) ===
```

Post-upgrade (6.9) test:
```
# FROM_VERSION=6.8 TO_VERSION=6.9 pytest -m post_upgrade -s tests/upgrades/test_yum_plugins.py 
[...]
collected 2 items / 1 deselected / 1 selected
[...]
tests/upgrades/test_yum_plugins.py .
[...]
=== 1 passed, 1 deselected, 57 warnings in 439.75s (0:07:19) ===
```

### CODE REVIEW

**Review by JacobCallahan — APPROVED** [review]

**Comment by JacobCallahan** [comment]
trigger: test-robottelo
pytest: tests/upgrades/test_yum_plugins.py -n 3

**Review by pondrejk — APPROVED** [review]
ack pending test result

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -s -m "pre_upgrade" tests/upgrades/test_yum_plugins.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -s -m 'pre_upgrade' tests/upgrades/test_yum_plugins.py

**Pull request merged**
