### PR TITLE
Add build_sanity to syncplan and gpg test

### PR DESCRIPTION
**Pull request by swadeley**
Hello

robottelo]$ pytest tests/foreman/api/test_syncplan.py -m build_sanity
============================ test session starts ===============================================
platform linux -- Python 3.8.6, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo_1/robottelo, inifile: pytest.ini
plugins: ibutsu-1.12, mock-3.3.1, forked-1.3.0, services-2.2.1, cov-2.10.1, xdist-1.34.0
collecting ... 2020-11-20 09:55:03 - conftest - DEBUG - Collected 114 test cases
collected 114 items / 112 deselected / 2 selected                                                                

tests/foreman/api/test_syncplan.py ..                                                                      [100%]

============== 2 passed, 112 deselected, 2 warnings in 11.16s ==============

robottelo]$ pytest tests/foreman/cli/test_content_credentials.py -m build_sanity
============================= test session starts ==========================================
platform linux -- Python 3.8.6, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo_1/robottelo, inifile: pytest.ini
plugins: ibutsu-1.12, mock-3.3.1, forked-1.3.0, services-2.2.1, cov-2.10.1, xdist-1.34.0
collecting ... 2020-11-20 09:56:39 - conftest - DEBUG - Collected 88 test cases
collected 88 items / 87 deselected / 1 selected                                                                  

tests/foreman/cli/test_content_credentials.py .                                                            [100%]

============ 1 passed, 87 deselected, 2 warnings in 16.59s ============

### CODE REVIEW

**Review by pondrejk — COMMENTED** [review]
ACK about the decorators but there seem to be an unintended .bak file pushed

**Comment by swadeley** [comment]
> ACK about the decorators but there seem to be an unintended .bak file pushed

sorry about that, now fixed, thanks for the review

**Review by lhellebr — APPROVED** [review]
Makes sense

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
