### PR TITLE
Just a debug PR

### PR DESCRIPTION
**Pull request by vsedmik**

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentcredentials.py::test_positive_search_scoped
env: ROBOTTELO_ui__RECORD_VIDEO: true

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentcredentials.py::test_positive_search_scoped
env: ROBOTTELO_ui__record_video: true

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentcredentials.py::test_positive_search_scoped
env:
ROBOTTELO_ui__record_video: true

**Comment by omkarkhatavkar** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentcredentials.py::test_positive_search_scoped
env:
  ROBOTTELO_ui__record_video: true
```

**Comment by omkarkhatavkar** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentcredentials.py::test_positive_search_scoped
env:
  ROBOTTELO_ui__record_video: true
```

**Pull request closed without merging**
