### PR TITLE
Remove sauceclient requirement

### PR DESCRIPTION
**Pull request by pgagne**
See https://github.com/SatelliteQE/airgun/issues/418

Test results:
```
(venv) redacted$ pip uninstall sauceclient 
Uninstalling sauceclient-1.0.0:
  Would remove:
    /redacted/robottelo/venv/lib/python3.6/site-packages/sauceclient-1.0.0-py3.6.egg-info
    /redacted/robottelo/venv/lib/python3.6/site-packages/sauceclient.py
Proceed (y/n)? y
  Successfully uninstalled sauceclient-1.0.0
(venv) redacted$  PYTHONPATH="../airgun/:$PYTHONPATH" pytest tests/foreman/ui/test_debug.py 
========================================================================================================================================== test session starts ===========================================================================================================================================
platform darwin -- Python 3.6.5, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /redacted/robottelo
plugins: services-1.3.1, xdist-1.30.0, forked-1.0.2, mock-1.10.4, cov-2.8.1
collecting ... 2019-11-07 21:39:06 - conftest - DEBUG - Collected 1 test cases

2019-11-07 16:39:06 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x112ea1e80
2019-11-07 16:39:06 - robottelo.ssh - INFO - Connected to [redacted]
2019-11-07 16:39:06 - robottelo.ssh - INFO - >>> rpm -q satellite
2019-11-07 16:39:07 - robottelo.ssh - INFO - <<< stdout
satellite-6.6.0-7.el7sat.noarch

2019-11-07 16:39:07 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x112ea1e80
2019-11-07 16:39:07 - robottelo.host_info - DEBUG - Host Satellite version: 6.6
2019-11-07 16:39:07 - robottelo.helpers - DEBUG - Generated file bz_cache.json with BZ collect data
collected 1 item                                                                                                                                                                                                                                                                                         

tests/foreman/ui/test_debug.py .                                                                                                                                                                                                                                                                   [100%]

======================================================================================================================================= 1 passed in 158.71 seconds =======================================================================================================================================

```
`test_debug.py`
```python3
import pytest

def test_debug(session):
    with session:
        session.lifecycleenvironment.read_all()

```

### CODE REVIEW

**Comment by JacobCallahan** [comment]
@SatelliteQE/quality-engineers does anyone want to take this up? If not, this is a candidate for closure.

**Comment by jyejare** [comment]
@JacobCallahan I think we should be able to ACK and Merge this ! I dont see there is a much of a work remained here.

**Review by mshriver — APPROVED** [review]

**Review by jyejare — APPROVED** [review]

**Comment by jyejare** [comment]
But not sure why @pgagne wants to keep it as DO_NOT_MERGE.

**Comment by pgagne** [comment]
I dont, @ntkathole  added that when we originally decided not to merge it. I cant remove the label.

**Review by JacobCallahan — APPROVED** [review]

**Pull request merged**
