### PR TITLE
Moved package/errata sub-commands from content-host to host

### LINKED ISSUE #3326: All package/package-group/errata sub-commands moved to host entity from content-hosts
As per of 6.2 host unification changes, all commands related to errata/package and package group are now moved from content-hosts to hosts entity. 
So all existing tests that points to content-host object should point to hosts object now.

```
 ~]# hammer -u admin -p changeme host | grep -ie errata -ie package -ie package-group
 errata                        Manage errata on your hosts
 package                       Manage packages on your hosts
 package-group                 Manage package-groups on your hosts
```

### PR DESCRIPTION
**Pull request by abalakh**
As per sat6.2, `package`/`package-group`/`errata` sub-commands moved from `content-host` to `host` command. Updating robottelo accordingly.
Closes #3326

### CODE REVIEW

**Comment by abalakh** [comment]
For the record: 
fixes applied to validate the changes:
1) Added support of `prior-id` field to `make_lifecycle_environment`
2) Updated `make_activation_key` to force exclude `unlimited-content-hosts` parameter
3) Used custom sat-tools repo instead of rh one
Gist with diff available [here](https://gist.github.com/abalakh/6ea83c906551b8113d50)

**Comment by abalakh** [comment]
Sorry for another [WIP] pull request, but it's _much_ easier for me to put all thoughts, fixes, code snippets and other-things-not-to-forget into a single PR (even if it's not 100% ready) rather than try to keep everything in mind.

**Comment by abalakh** [comment]
Rebased and removed the `[WIP]` tag. As part of blocking bugs were fixed, i was able to successfully run few of tests:
```python
py.test -v tests/foreman/cli/test_host.py -k 'KatelloAgentTestCase'
============================= test session starts ==============================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1 -- /home/andrii/env/bin/python
cachedir: .cache
rootdir: /home/andrii/workspace/robottelo, inifile:
plugins: xdist-1.13.1, repeat-0.2
collecting ... collected 39 items

tests/foreman/cli/test_host.py::KatelloAgentTestCase::test_negative_unregister_and_pull_content PASSED
tests/foreman/cli/test_host.py::KatelloAgentTestCase::test_positive_apply_errata <- robottelo/decorators.py PASSED
tests/foreman/cli/test_host.py::KatelloAgentTestCase::test_positive_get_errata_info <- robottelo/decorators.py PASSED
```
The rest of them (package installation related) are still failing due to some bugs, but they shouldn't block this PR - few passed tests are proving sub-commands were moved correctly.

**Comment by elyezer** [comment]
ACK

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
