### PR TITLE
Updated installer flags for 6.10

### PR DESCRIPTION
**Pull request by devendra104**
A lot of the changes observed in the 6.10 installer flag. All the removed and added flags are mentioned below.

**Removed Flags**
```
--[no-]enable-foreman-proxy-plugin-pulp
--certs-log-dir
--clear-pulp-content
--foreman-dynflow-pool-size
--foreman-jobs-manage-service
--foreman-jobs-service-enable
--foreman-jobs-service-ensure
--foreman-jobs-sidekiq-redis-url
--foreman-passenger
--foreman-passenger-min-instances
--foreman-passenger-prestart
--foreman-passenger-ruby
--foreman-passenger-ruby-package
--foreman-passenger-start-timeout
--foreman-proxy-content-enable-ostree
--foreman-proxy-content-enable-puppet
--foreman-proxy-content-manage-broker
--foreman-proxy-content-parent-fqdn
--foreman-proxy-content-proxy-pulp-isos-to-pulpcore
--foreman-proxy-content-proxy-pulp-yum-to-pulpcore
--foreman-proxy-content-pulp-admin-password
--foreman-proxy-content-pulp-ca-cert
--foreman-proxy-content-pulp-max-speed
--foreman-proxy-content-pulp-num-workers
--foreman-proxy-content-pulp-proxy-password
--foreman-proxy-content-pulp-proxy-port
--foreman-proxy-content-pulp-proxy-url
--foreman-proxy-content-pulp-proxy-username
--foreman-proxy-content-pulp-puppet-wsgi-processes
--foreman-proxy-content-pulp-worker-timeout
--foreman-proxy-content-qpid-router
--foreman-proxy-content-qpid-router-sasl-mech
--foreman-proxy-content-qpid-router-sasl-password
--foreman-proxy-content-qpid-router-sasl-username
--foreman-proxy-content-ssl-protocol
--foreman-proxy-plugin-pulp-enabled
--foreman-proxy-plugin-pulp-listen-on
--foreman-proxy-plugin-pulp-mongodb-dir
--foreman-proxy-plugin-pulp-pulp-content-dir
--foreman-proxy-plugin-pulp-pulp-dir
--foreman-proxy-plugin-pulp-pulp-url
--foreman-proxy-plugin-pulp-pulpcore-api-url
--foreman-proxy-plugin-pulp-pulpcore-content-url
--foreman-proxy-plugin-pulp-pulpcore-enabled
--foreman-proxy-plugin-pulp-pulpcore-mirror
--foreman-proxy-plugin-pulp-pulpnode-enabled
--foreman-proxy-plugin-pulp-puppet-content-dir
--foreman-proxy-plugin-pulp-version
--katello-enable-deb
--katello-enable-docker
--katello-enable-file
--katello-enable-ostree
--katello-enable-puppet
--katello-enable-yum
--katello-num-pulp-workers
--katello-pulp-db-ca-path
--katello-pulp-db-name
--katello-pulp-db-password
--katello-pulp-db-replica-set
--katello-pulp-db-seeds
--katello-pulp-db-ssl
--katello-pulp-db-ssl-certfile
--katello-pulp-db-ssl-keyfile
--katello-pulp-db-unsafe-autoretry
--katello-pulp-db-username
--katello-pulp-db-verify-ssl
--katello-pulp-db-write-concern
--katello-pulp-manage-db
--katello-pulp-max-speed
--katello-pulp-worker-timeout
--katello-repo-export-dir
--katello-use-pulp-2-for-docker
--katello-use-pulp-2-for-file
--katello-use-pulp-2-for-yum
--reset-certs-log-dir
--reset-foreman-dynflow-pool-size
--reset-foreman-jobs-manage-service
--reset-foreman-jobs-service-enable
--reset-foreman-jobs-service-ensure
--reset-foreman-jobs-sidekiq-redis-url
--reset-foreman-passenger
--reset-foreman-passenger-min-instances
--reset-foreman-passenger-prestart
--reset-foreman-passenger-ruby
--reset-foreman-passenger-ruby-package
--reset-foreman-passenger-start-timeout
--reset-foreman-proxy-content-enable-ostree
--reset-foreman-proxy-content-enable-puppet
--reset-foreman-proxy-content-manage-broker
--reset-foreman-proxy-content-parent-fqdn
--reset-foreman-proxy-content-proxy-pulp-isos-to-pulpcore
--reset-foreman-proxy-content-proxy-pulp-yum-to-pulpcore
--reset-foreman-proxy-content-pulp-admin-password
--reset-foreman-proxy-content-pulp-ca-cert
--reset-foreman-proxy-content-pulp-max-speed
--reset-foreman-proxy-content-pulp-num-workers
--reset-foreman-proxy-content-pulp-proxy-password
--reset-foreman-proxy-content-pulp-proxy-port
--reset-foreman-proxy-content-pulp-proxy-url
--reset-foreman-proxy-content-pulp-proxy-username
--reset-foreman-proxy-content-pulp-puppet-wsgi-processes
--reset-foreman-proxy-content-pulp-worker-timeout
--reset-foreman-proxy-content-qpid-router
--reset-foreman-proxy-content-qpid-router-sasl-mech
--reset-foreman-proxy-content-qpid-router-sasl-password
--reset-foreman-proxy-content-qpid-router-sasl-username
--reset-foreman-proxy-content-ssl-protocol
--reset-foreman-proxy-plugin-pulp-enabled
--reset-foreman-proxy-plugin-pulp-listen-on
--reset-foreman-proxy-plugin-pulp-mongodb-dir
--reset-foreman-proxy-plugin-pulp-pulp-content-dir
--reset-foreman-proxy-plugin-pulp-pulp-dir
--reset-foreman-proxy-plugin-pulp-pulp-url
--reset-foreman-proxy-plugin-pulp-pulpcore-api-url
--reset-foreman-proxy-plugin-pulp-pulpcore-content-url
--reset-foreman-proxy-plugin-pulp-pulpcore-enabled
--reset-foreman-proxy-plugin-pulp-pulpcore-mirror
--reset-foreman-proxy-plugin-pulp-pulpnode-enabled
--reset-foreman-proxy-plugin-pulp-puppet-content-dir
--reset-foreman-proxy-plugin-pulp-version
--reset-katello-enable-deb
--reset-katello-enable-docker
--reset-katello-enable-file
--reset-katello-enable-ostree
--reset-katello-enable-puppet
--reset-katello-enable-yum
--reset-katello-num-pulp-workers
--reset-katello-pulp-db-ca-path
--reset-katello-pulp-db-name
--reset-katello-pulp-db-password
--reset-katello-pulp-db-replica-set
--reset-katello-pulp-db-seeds
--reset-katello-pulp-db-ssl
--reset-katello-pulp-db-ssl-certfile
--reset-katello-pulp-db-ssl-keyfile
--reset-katello-pulp-db-unsafe-autoretry
--reset-katello-pulp-db-username
--reset-katello-pulp-db-verify-ssl
--reset-katello-pulp-db-write-concern
--reset-katello-pulp-manage-db
--reset-katello-pulp-max-speed
--reset-katello-pulp-worker-timeout
--reset-katello-repo-export-dir
--reset-katello-use-pulp-2-for-docker
--reset-katello-use-pulp-2-for-file
--reset-katello-use-pulp-2-for-yum
```

**Added Flags:**
```
-
--[no-]enable-foreman-cli-remote-execution
--[no-]enable-foreman-plugin-webhooks
--[no-]enable-foreman-proxy-plugin-shellhooks
--foreman-cli-use-sessions
--foreman-dynflow-manage-services
--foreman-dynflow-orchestrator-ensure
--foreman-dynflow-redis-url
--foreman-dynflow-worker-concurrency
--foreman-dynflow-worker-instances
--foreman-plugin-tasks-backup
--foreman-proxy-content-enable-ansible
--foreman-proxy-content-enable-katello-agent
--foreman-proxy-content-pulpcore-allowed-content-checksums
--foreman-proxy-content-pulpcore-api-service-worker-timeout
--foreman-proxy-content-pulpcore-content-service-worker-timeout
--foreman-proxy-content-pulpcore-django-secret-key
--foreman-proxy-content-pulpcore-mirror
--foreman-proxy-dhcp-ping-free-ip
--foreman-proxy-plugin-ansible-callback
--foreman-proxy-plugin-ansible-runner-package-name
--foreman-proxy-plugin-shellhooks-directory
--foreman-proxy-plugin-shellhooks-enabled
--foreman-proxy-plugin-shellhooks-listen-on
--foreman-proxy-plugin-shellhooks-version
--katello-hosts-queue-workers
--puppet-package-install-options
--puppet-server-puppetserver-profiler
--reset-foreman-cli-use-sessions
--reset-foreman-dynflow-manage-services
--reset-foreman-dynflow-orchestrator-ensure
--reset-foreman-dynflow-redis-url
--reset-foreman-dynflow-worker-concurrency
--reset-foreman-dynflow-worker-instances
--reset-foreman-plugin-tasks-backup
--reset-foreman-proxy-content-enable-ansible
--reset-foreman-proxy-content-enable-katello-agent
--reset-foreman-proxy-content-pulpcore-allowed-content-checksums
--reset-foreman-proxy-content-pulpcore-api-service-worker-timeout
--reset-foreman-proxy-content-pulpcore-content-service-worker-timeout
--reset-foreman-proxy-content-pulpcore-django-secret-key
--reset-foreman-proxy-content-pulpcore-mirror
--reset-foreman-proxy-dhcp-ping-free-ip
--reset-foreman-proxy-plugin-ansible-callback
--reset-foreman-proxy-plugin-ansible-runner-package-name
--reset-foreman-proxy-plugin-shellhooks-directory
--reset-foreman-proxy-plugin-shellhooks-enabled
--reset-foreman-proxy-plugin-shellhooks-listen-on
--reset-foreman-proxy-plugin-shellhooks-version
--reset-katello-hosts-queue-workers
--reset-puppet-package-install-options
--reset-puppet-server-puppetserver-profiler
```

**Removed Section:**
`'= Module foreman_proxy_plugin_pulp:'`

**Added Sectio**n:
`''= Module foreman_proxy_plugin_shellhooks:'`

### CODE REVIEW

**Review by latran — COMMENTED** [review]
Where did you find this list of flags?  I'm just curious because I may need to use it.

**Comment by devendra104** [comment]
> Where did you find this list of flags? I'm just curious because I may need to use it.

we found it in satellite-installer helper.

```
# satellite-installer --help
Usage:
    satellite-installer [OPTIONS]

Options:

= Generic:
    --[no-]lock-package-versions  Let installer lock versions of the installed packages to prevent
                                  unexpected breakages during system updates. The choice is remembered
                                  and used in next installer runs. (default: nil)
    --tuning INSTALLATION_SIZE    Tune for an installation size. Choices: default, medium, large, extra-large, extra-extra-large (default: "default")
    --certs-update-server         This option will enforce an update of the HTTPS certificates (default: false)
    --certs-update-server-ca      This option will enforce an update of the CA used for HTTPS certificates. (default: false)
    --certs-update-all            This option will enforce an update of all the certificates for given host (default: false)
    --certs-reset                 This option will reset any custom certificates and use the self-signed CA instead. Note that any clients will need to be updated with the latest katello-ca-consumer RPM, and any external proxies will need to have the certs updated by generating a new certs tarball. (default: false)
    --certs-skip-check            This option will cause skipping the certificates sanity check. Use with caution (default: false)
    --register-with-insights      This option will register the system with Red Hat Insights. (default: false)

```

**Comment by devendra104** [comment]
All the changes are expected and approved by the developer.

**Review by latran — APPROVED** [review]
I've checked the list of removed and list of added and compared to your changes.  All looks good.  ACK.

**Review by jameerpathan111 — APPROVED** [review]
LGTM

**Pull request merged**
