### PR TITLE
[WIP] Adding support for SauceLabs execution.

### PR DESCRIPTION
**Pull request by omaciel**
A while back we removed support for running UI tests via SauceLabs.

This Pull Request adds that support back.

### CODE REVIEW

**Comment by omaciel** [comment]
@elyezer can you continue this work for me? Basically:
* Need to add a level of verification/validation is `webdriver == remote` and `sauce_user` and `sauce_key` are not set;
* Add `sauceclient` back as a dependency (optional) and add support to report test results back to `SauceLabs` (please refer to #6755fe7d)

**Comment by elyezer** [comment]
I'm going to continue this.

**Comment by omaciel** [comment]
I have gone ahead and added code that allows us to 'inform' **SauceLabs** about the results of a test, but I added it to the `tearDown` method of the `UITestCase` class. Existing [documentation](https://docs.python.org/2/library/unittest.html#unittest.TestCase.run) tells us that in order to examine the test result for a test run, one should override the `run` method and that there is an implicit call to [defaultTestResult](https://docs.python.org/2/library/unittest.html#unittest.TestCase.defaultTestResult) which should return us a `TestResult` instance.

When I implemented my `run()` method, interestingly enough, I did not have a `TestResult` but a `TestCaseFunction` instance, which is **not** what I expected, and the statement `if result.failures or result.errors` failed:

```python
    def run(self, result=None):
        super(UITestCase, self).run(result)
        # create a sauceclient object to report pass/fail results
        sc = sauceclient.SauceClient(
            settings.sauce_user,
            settings.sauce_key)

        if result.failures or result.errors:
            if isinstance(
                    self.browser,
                    selenium.webdriver.remote.webdriver.WebDriver):
                sc.jobs.update_job(self.browser.session_id,name=str(self),passed=False)
        else:
            if isinstance(
                    self.browser,
                    selenium.webdriver.remote.webdriver.WebDriver):
                sc.jobs.update_job(self.browser.session_id,name=str(self),passed=True)

        return result
```

I have tested my changes so far, with success:

```shell
(robottelo) ┌[omaciel☮Ogs-MacBook-Pro.local]-(~/hacking/robottelo)-[git://add-saucelabs-back ✗]-
└> py.test -v -n 4 --boxed tests/foreman/ui/test_architecture.py
========================================================== test session starts ===========================================================
platform darwin -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1 -- /Users/omaciel/.virtualenvs/robottelo/bin/python
cachedir: .cache
rootdir: /Users/omaciel/hacking/robottelo, inifile:
plugins: cov-2.2.1, xdist-1.14
[gw0] darwin Python 2.7.10 cwd: /Users/omaciel/hacking/robottelo
[gw1] darwin Python 2.7.10 cwd: /Users/omaciel/hacking/robottelo
[gw2] darwin Python 2.7.10 cwd: /Users/omaciel/hacking/robottelo
[gw3] darwin Python 2.7.10 cwd: /Users/omaciel/hacking/robottelo
[gw0] Python 2.7.10 (default, Oct 23 2015, 18:05:06)  -- [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
[gw1] Python 2.7.10 (default, Oct 23 2015, 18:05:06)  -- [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
[gw2] Python 2.7.10 (default, Oct 23 2015, 18:05:06)  -- [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
[gw3] Python 2.7.10 (default, Oct 23 2015, 18:05:06)  -- [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
gw0 [6] / gw1 [6] / gw2 [6] / gw3 [6]
scheduling tests via LoadScheduling
[gw1] PASSED tests/foreman/ui/test_architecture.py::ArchitectureTestCase::test_negative_create_with_invalid_name <- robottelo/decorators.py
[gw3] PASSED tests/foreman/ui/test_architecture.py::ArchitectureTestCase::test_positive_create_with_name <- robottelo/decorators.py
[gw0] PASSED tests/foreman/ui/test_architecture.py::ArchitectureTestCase::test_negative_create_with_same_name <- robottelo/decorators.py
[gw1] PASSED tests/foreman/ui/test_architecture.py::ArchitectureTestCase::test_positive_delete <- robottelo/decorators.py
[gw2] PASSED tests/foreman/ui/test_architecture.py::ArchitectureTestCase::test_positive_create_with_os <- robottelo/decorators.py
[gw0] PASSED tests/foreman/ui/test_architecture.py::ArchitectureTestCase::test_positive_update_name_and_os <- robottelo/decorators.py

======================================================= 6 passed in 247.11 seconds =======================================================
```

**SauceLabs** dashboard shows that all tests have the correct name and status:

screenshot 2016-02-18 15 57 01

One thing though. Tests run on **SauceLabs** reported a running time much higher per individual tests than running them 'locally' using our Docker-based Selenium system, as shown below:

screenshot 2016-02-18 15 58 05

**Comment by JacobCallahan** [comment]
ACK, pending conflict resolution.

**Comment by elyezer** [comment]
@JacobCallahan #3313 overrides this PR, we are safe to close this.

**Pull request closed without merging**
