### PR TITLE
Quick fix for Location entity possible name length boundaries

### LINKED ISSUE #2525: Fix possible boundaries for location test cases
Maximum is 246 characters for location entity

### PR DESCRIPTION
**Pull request by oshtaier**
Closes #2525

```
nosetests tests/foreman/cli/test_location.py -m test_create_location_with_different_names_positive
.......
----------------------------------------------------------------------
Ran 7 tests in 59.121s

OK
```

### CODE REVIEW

**Comment by abalakh** [comment]
ACK

**Comment by rplevka** [comment]
ACK

**Comment by elyezer** [comment]
I think we should check with devs to make sure this is a intended change or not.

**Comment by oshtaier** [comment]
@elyezer Could you please help with that when you have a spare moment? Just with some kind of confirmation and I can proceed with BZ if needed

**Comment by elyezer** [comment]
@oshtaier ping me tomorrow and we can talk more about this.

**Comment by oshtaier** [comment]
<mmccune> oshtaier: if the CLI and the UI limit it to 246 and they are consistent, then that is not a defect, the limit is 246

**Comment by elyezer** [comment]
@oshtaier thanks for the update.

**Pull request merged**
