### PR TITLE
Updated activation key field in UI for global registration page

### PR DESCRIPTION
**Pull request by shweta83**
Changes caused by [BZ 2059829](https://bugzilla.redhat.com/show_bug.cgi?id=2059829)

Depends on: Airgun PR https://github.com/SatelliteQE/airgun/pull/802

### CODE REVIEW

**Comment by Griffin-Sullivan** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k global_registration
airgun: 802

**Comment by Griffin-Sullivan** [comment]
A couple failure types to look into from PRT most of them are from using SCA mode but trying to attach subscriptions. If we updated manifest type these should all fix. There's a couple that are failing like `test_global_registration_form_populate` for example that you should look more into since it is a separate issue I think.

**Comment by Gauravtalreja1** [comment]
@shweta83 Failures in PRT seem to be due to `module_org_with_manifest`, where org has SCA enabled, which needs to be disabled for cloned manifest or `module_ak` fixture can be updated to use manifester org fixtures

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k global_registration
airgun: 802

**Comment by shweta83** [comment]
> A couple failure types to look into from PRT most of them are from using SCA mode but trying to attach subscriptions. If we updated manifest type these should all fix. There's a couple that are failing like `test_global_registration_form_populate` for example that you should look more into since it is a separate issue I think.
I updated the manifest fixture but PRT is failing because of known logging issue. I will re-run PRT once this issue gets fixed.

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k global_registration
airgun: 802

**Comment by shweta83** [comment]
The failed test cases are unrelated to the changes.

**Review by Griffin-Sullivan — APPROVED** [review]
Looks good. Since the airgun PR is also changing the helper could you update this line so the test will pass?https://github.com/SatelliteQE/robottelo/blob/0b42049cbe130c1422d11c18952e6454b72ce391/tests/foreman/ui/test_host.py#L1407

It failed in PRT.

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k global_registration
airgun: 802

**Comment by shweta83** [comment]
> Looks good. Since the airgun PR is also changing the helper could you update this line so the test will pass?
> 
> https://github.com/SatelliteQE/robottelo/blob/0b42049cbe130c1422d11c18952e6454b72ce391/tests/foreman/ui/test_host.py#L1407
> 
> It failed in PRT.

@Griffin-Sullivan Fixed the failure. I tried to fix other failures but since those failures are not related to change so review is not blocked now.

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_global_registration_upgrade_subscription_manager
airgun: 802

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
