### PR TITLE
Add test update checkin time

### PR DESCRIPTION
**Pull request by swadeley**
Closed loop: 1860928

### CODE REVIEW

**Comment by swadeley** [comment]
Hello @mshriver 

I see you added/ [1] pytestmark = pytest.mark.libvirt_discovery to this test. So I wonder is it OK for m to add a simple extra test at the end?

Thank you

commit 5bd6d20b2ff84c5035c09286b4c8d2e8933f9587

**Comment by mshriver** [comment]
@swadeley Maybe I'm missing something, but that mark was not added to the test module that you're modifying here, it was added to a few other test modules modified by that commit. 

Regardless, I don't see any problem with you adding additional test steps here. There are no module level marks applied in `tests/foreman/ui/test_contenthost.py`

**Review by jaryn — APPROVED** [review]

**Comment by swadeley** [comment]
> @swadeley Maybe I'm missing something, but that mark was not added to the test module that you're modifying here, it was added to a few other test modules modified by that commit.
> 


Test level, not module level:


    # The content host has been moved to broker, but the test still depends on libvirt compute resource
    @pytest.mark.libvirt_discovery
    @pytest.mark.tier3
    @pytest.mark.upgrade
    def test_positive_virt_who_hypervisor_subscription_status(session, rhel7_contenthost):
        """Check that virt-who hypervisor shows the right subscription status
       without and with attached subscription.

        :id: 8b2cc5d6-ac85-463f-a973-f4818c55fb37


> Regardless, I don't see any problem with you adding additional test steps here. There are no module level marks applied in `tests/foreman/ui/test_contenthost.py`

Great, thank you

**Review by mshriver — APPROVED** [review]

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
