### PR TITLE
[6.11.z] Fix 4-digit logic in download_repofile and ohsnap_repo_url

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12057

`ohsnap_repo_url()` and `download_repofile()` needlessly shortens 4 digit satellite version to 3 digits

Found when PR testing https://github.com/SatelliteQE/robottelo/pull/12049#issuecomment-1656731416

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_clone.py
env:
    ROBOTTELO_server__version__release: '6.13.3'
    ROBOTTELO_server__version__snap: '2.0'

**Comment by Gauravtalreja1** [comment]
@lpramuk satellite-clone step seem to be failing in PRT, suspecting it could be a bug, so can you please check and update the PR?

**Comment by ogajduse** [comment]
PRT cherry-picked wrong commit, there is nothing to investigate in this PR. We have to wait till monday for @omkarkhatavkar or @jyejare to fix our GHA or @lpramuk has to cherry-pick the PR manually.

**Comment by jyejare** [comment]
@ogajduse Let's close this PR and go for manual one! Even though we fix the issue this might take time to get merge and bring it here to fix this issue. Also even if we fix it it will open a new PR.

So go for a fresh manual cherrypick !

**Comment by lpramuk** [comment]
We have a flaw in cherrypicking - this completely different commit

**Pull request closed without merging**
