### PR TITLE
[6.14.z] CP of API-Errata modifications

### PR DESCRIPTION
**Pull request by damoore044**
Failed cherry-pick into 6.14.z of #13515 from master.
Failed auto-CP merge request: #13828

### Specific 6.14.z differences from 6.15 and master PRs:
The new case `test_positive_incremental_update_apply_to_envs_cvs[rhel8_contenthost0]`, 
was only planned and merged for 6.15.z+, is not included in these changes.

To fix `test_errata_installation_with_swidtags`:
Setup now with global registration host, using custom ak cv and repos (including `settings.repos.swid_tag`)
Now, we have the repositories with swid tags properly synced to the contenthost.
I will open a follow-up pr to extend these swidtag test fixes into master/6.15 (failing for same reason).

### PRT case:
```
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py
```

### CODE REVIEW

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

**Review by lhellebr — COMMENTED** [review]
Well this is just a cherrypick so not much to review, but PRT failed, please investigate.

**Review by rplevka — APPROVED** [review]

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

**Comment by ogajduse** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5875
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_errata.py --external-logging
Test Result : ======= 6 failed, 7 passed, 750 warnings, 2 errors in 3317.65s (0:55:17) =======
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6138
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_errata.py --external-logging
Test Result : =========== 1 failed, 11 passed, 2400 warnings in 5102.74s (1:25:02) ===========
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6156
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_errata.py --external-logging
Test Result : ======================== 12 errors in 243.96s (0:04:03) ========================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6157
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_errata.py --external-logging
Test Result : ================ 12 passed, 2402 warnings in 5103.10s (1:25:03) ================
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6168
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_errata.py --external-logging
Test Result : ================ 12 passed, 2376 warnings in 5117.80s (1:25:17) ================
```

**Review by vsedmik — APPROVED** [review]

**Pull request merged**
