### PR TITLE
Fix UI DiscoveryRule tests

### LINKED ISSUE #2710: Automation failure :  tests.foreman.ui.test_discoveryrule.DiscoveryRules
TestNames:
tests.foreman.ui.test_discoveryrule.DiscoveryRules.test_disable_discovery_rule_1
tests.foreman.ui.test_discoveryrule.DiscoveryRules.test_negative_create_discovery_rule_4
tests.foreman.ui.test_discoveryrule.DiscoveryRules.test_positive_create_discovery_rule_1_1_83877860
tests.foreman.ui.test_discoveryrule.DiscoveryRules.test_positive_create_discovery_rule_2
tests.foreman.ui.test_discoveryrule.DiscoveryRules.test_update_discovery_rule_1_1_rYURafgQ
tests.foreman.ui.test_discoveryrule.DiscoveryRules.test_delete_discovery_rule_1_1_GGpEBCUF

Error Message
unexpectedly None

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-ui/tests/foreman/ui/test_discoveryrule.py", line 171, in test_delete_discovery_rule_1
    self.assertIsNotNone(self.discoveryrules.search(name))
  File "/usr/lib64/python2.7/unittest/case.py", line 1000, in assertIsNotNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
'unexpectedly None\n--------------------

### PR DESCRIPTION
**Pull request by abalakh**
Some time ago we had only few DiscoveryRule tests and they were passing successfully. Lately new DiscoveryRule tests were introduced (#2701). Tests started failing because pagination appeared and some of the DiscoveryRules appeared on the second page.
Some bad news there:
1) All the Discovery Rules are shown on UI regardless of organization/location selected, making it impossible to fix by selecting different organization
2) There's no searchbar on DiscoveryRule page, so searching for specific discovery rule is not an option either

The only option left is to set `entries_per_page` setting to some huge value while DiscoveryRule tests are running and return it to the previous value after the tests finished execution.

UI was not an option here - setting should be changed in `setUpClass` and `tearDownClass`, and browser is started/closed in `setUp` and `tearDown` accordingly, so we can't access browser from `setUpClass`/`tearDownClass`. In addition, UI is slower then API.

That's why SatelliteQE/nailgun#205 was introduced, and solution with changing `entries_per_page` through API is applied here.

Closes #2710
```
nosetests tests/foreman/ui/test_discoveryrule.py
..............................
----------------------------------------------------------------------
Ran 30 tests in 882.763s

OK
```

### CODE REVIEW

**Comment by sghai** [comment]
Thank you @abalakh for the fix.  Looks great.
We already have a bz `1233135` for missing search bar on Discovery Rules page.

**Comment by abalakh** [comment]
Oh, btw:
Depends on SatelliteQE/nailgun#205

**Comment by sthirugn** [comment]
ACK

**Comment by oshtaier** [comment]
To be honest, I am not so happy with a constants like ''100000'', but understand necessity of it here.
ACK

**Comment by abalakh** [comment]
@oshtaier me either. But as we already have a defect for missing searchbar, I hope it will be fixed soon and whole DiscoveryRule module will be refactored. Consider this as a temporary workaround.

**Pull request merged**
