### PR TITLE
Fixing 6 entities according to new search approach

### PR DESCRIPTION
**Pull request by oshtaier**
**Activation key:**
```
nosetests tests/foreman/ui/test_activationkey.py
E....SE.S...S............E.......E
----------------------------------------------------------------------
Ran 34 tests in 5919.913s

FAILED (SKIP=3, errors=4)
```
Four failures happened due VirtualMachineError and don't have references to my changes

```
nosetests tests/foreman/ui/test_docker.py -m test_add_docker_repo_to_activation_key
.
----------------------------------------------------------------------
Ran 1 test in 106.718s

OK
```
```
nosetests tests/foreman/ui/test_docker.py -m test_add_docker_repo_composite_view_to_activation_key
.
----------------------------------------------------------------------
Ran 1 test in 188.408s

OK
```

**Compute Profile:**
```
nosetests tests/foreman/ui/test_computeresource.py -m test_access_docker_resource_via_compute_profile
.
----------------------------------------------------------------------
Ran 1 test in 30.953s

OK
```

**Compute Resource (test results are given with fix for 'superclass' issue):**
```
nosetests tests/foreman/ui/test_computeresource.py
..........
----------------------------------------------------------------------
Ran 10 tests in 623.508s

OK
```

**Config Groups:**
```
nosetests tests/foreman/ui/test_config_groups.py
.F..
----------------------------------------------------------------------
Ran 4 tests in 415.912s

FAILED (failures=1)
```
One failure happened due issue with string length (>30 symbols)

**Partition Table:**
```
nosetests tests/foreman/ui/test_partitiontable.py
....SS
----------------------------------------------------------------------
Ran 6 tests in 247.068s

OK (SKIP=2)
```

**Products:**
```
nosetests tests/foreman/ui/test_products.py
........
----------------------------------------------------------------------
Ran 8 tests in 1237.240s

OK
```

### CODE REVIEW

**Comment by abalakh** [comment]
ACK

**Comment by oshtaier** [comment]
Will rebase

**Comment by oshtaier** [comment]
rebased

**Comment by kbidarkar** [comment]
ACK

**Pull request merged**
