### PR TITLE
[6.15.z] Add test for VMware image based provisioning

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15733

Component Audit: Adding a test for VMware image based provisioning

Dependent Nailgun PR: https://github.com/SatelliteQE/nailgun/pull/1204

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_vmware.py -k test_positive_image_provision_end_to_end
provisioning: true
pod_resources_size: extra_extra_large

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_vmware.py -k test_positive_image_provision_end_to_end
provisioning: true
pod_resources_size: extra_extra_large
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8007
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_computeresource_vmware.py -k test_positive_image_provision_end_to_end --external-logging --include-onprem-provisioning
Test Result : ========== 26 deselected, 46 warnings, 2 errors in 285.77s (0:04:45) ===========
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_vmware.py -k test_positive_image_provision_end_to_end
provisioning: true
pod_resources_size: extra_extra_large
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8053
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_computeresource_vmware.py -k test_positive_image_provision_end_to_end --external-logging --include-onprem-provisioning
Test Result : ========== 2 failed, 26 deselected, 61 warnings in 1884.80s (0:31:24) ==========
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_vmware.py -k test_positive_image_provision_end_to_end
provisioning: true
pod_resources_size: extra_extra_large
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8573
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_computeresource_vmware.py -k test_positive_image_provision_end_to_end --external-logging --include-onprem-provisioning
Test Result : ========== 2 failed, 26 deselected, 69 warnings in 2025.54s (0:33:45) ==========
```

**Comment by Gauravtalreja1** [comment]
@shubhamsg199 Could you update this PR?

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_vmware.py -k test_positive_image_provision_end_to_end
provisioning: true
pod_resources_size: extra_extra_large
env:
     BROKER_SSH_BACKEND: hussh

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 9088
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_computeresource_vmware.py -k test_positive_image_provision_end_to_end --external-logging --include-onprem-provisioning
Test Result : ========== 2 failed, 26 deselected, 80 warnings in 1971.28s (0:32:51) ==========
```

**Pull request closed without merging**
