### PR TITLE
Added boundary tests for org cli max length 242

### LINKED ISSUE #2881: Add cli boundary tests for org length of 242
Currently no such tests are available in cli

### PR DESCRIPTION
**Pull request by sthirugn**
Closed #2881 

Test result:
```sh
Finding files... done.
Importing test modules ... done.

----------------------------------------------------------------------
Ran 117 tests in 951.526s

OK (skipped=71)

```

Also note that this PR is specifically to update org name boundary tests and not other attributes like label, desc, etc.

### CODE REVIEW

**Comment by oshtaier** [comment]
If you like to improve alpha, alphanumeric and numeric test sets of data for `Organization` entity, so please do the same for all other inputs (with value of 84 or 83, not sure what is right one).
NACK

**Comment by sthirugn** [comment]
For other data values, it needs more effort to investigate and find the right value and not just a wild guess of 84 or 83 which had caused troubled in the past for me in API tests.  If this is a blocker for this PR, let it be.  I will work on this after my ddt removal task is completed.

**Comment by elyezer** [comment]
@oshtaier and @sthirugn we can open an issue to track the multi byte charset values and merge this PR. The issue will make sure that we don't forget to improve for other data types later.

ACK, pending issue for multi byte.

**Comment by oshtaier** [comment]
We have a meeting to discuss that tomorrow
My point - it is a blocker as it is in scope of that PR

**Comment by abalakh** [comment]
ACK
I would say this PR is harmless, as it introduces some boundaries for at least few of string types. PR is not closing #2881, but is a part of it. imo we can merge it, better to have some of boundary tests rather then no tests at all (especially when we don't break anything).
@oshtaier , still NACK?

**Comment by oshtaier** [comment]
@abalakh Agree with you. Feel free to merge that PR in case corresponding issue will exist in the system (new or existing one)

**Comment by abalakh** [comment]
@sthirugn please, do a rebase

**Comment by oshtaier** [comment]
@abalakh Anyway, I think we should follow @elyezer advice here and, probably, close #2881 and open a new issue. Please, merge only corresponding issue exists

**Comment by abalakh** [comment]
@oshtaier there's already #2890 existing for other string types.

**Comment by oshtaier** [comment]
@abalakh Thank you
@sthirugn :+1:

**Comment by sthirugn** [comment]
@abalakh @oshtaier ty, rebased.

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
