### PR TITLE
Fix UI SyncPlan

### PR DESCRIPTION
**Pull request by vsedmik**
Products added to a SyncPlan must contain a repo in 6.14.

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_syncplan.py -k test_positive_end_to_end

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentcredentials.py
env:
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.14.0'
ROBOTTELO_server__deploy_arguments__deploy_snap_version: '14.0'
ROBOTTELO_ui__RECORD_VIDEO: true

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_syncplan.py -k test_positive_end_to_end

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_syncplan.py -k test_positive_end_to_end

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_syncplan.py -k test_positive_end_to_end

**Review by sambible — APPROVED** [review]
lgtm

**Review by damoore044 — APPROVED** [review]
looks good- lets merge

**Pull request merged**
