### PR TITLE
Automation for bz-2040870

### PR DESCRIPTION
**Pull request by latran**
We already have an existing test case that has all the necessary steps for [bz-2040870](https://bugzilla.redhat.com/show_bug.cgi?id=2040870) except it uses rh vitualization repo because the syncing is faster.  I'm changing this to fit the bz need with few changes involved.

### CODE REVIEW

**Comment by latran** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k test_positive_export_import_redhat_cv

**Comment by latran** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k test_positive_export_import_redhat_cv

**Review by rmynar — APPROVED** [review]
two birds one stone. :+1:

**Comment by mshriver** [comment]
@latran your changes look sane, but its failing in PRT - want to re-run? what's failing?

**Review by ColeHiggins2 — APPROVED** [review]
ACK pending Rerun

**Comment by ColeHiggins2** [comment]
Looks like two tests got run, both seem to fail on line 978 on the make_org() call

**Comment by latran** [comment]
@mshriver @ColeHiggins2 I'm running it locally to see what's going on.

**Comment by latran** [comment]
I'm not what sure why the test is failing in PRT, but running it locally takes about 23 minutes due to the size of the repo and the time it takes to import/export the content.

test result:
```
pytest tests/foreman/cli/test_satellitesync.py::TestContentViewSync::test_positive_export_import_redhat_cv
============ 1 passed, 2 warnings in 1422.48s (0:23:42) ===========
``

I'm gonna run the PRT again and see as well.

**Comment by latran** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py::TestContentViewSync::test_positive_export_import_redhat_cv

**Review by JacobCallahan — APPROVED** [review]

**Pull request merged**
