### PR TITLE
Fixed bug where SharedFunctionSettings validation is comparing None …

### LINKED ISSUE #5854: Missing share_timeout breaking pipeline on Python 3

### PR DESCRIPTION
**Pull request by renzon**
…with int

close #5854

This bug is holding the adoption of Python 3

### CODE REVIEW

**Comment by renzon** [comment]
Error on Python 3:

```console
pytest tests/robottelo/test_settings.py 
=============================================== test session starts ===============================================
platform linux -- Python 3.6.4, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/renzo/PycharmProjects/robottelo, inifile:
plugins: xdist-1.22.2, services-1.2.1, mock-1.6.3, forked-0.2, cov-2.5.1
collected 1 item                                                                                                  

tests/robottelo/test_settings.py F                                                                          [100%]

==================================================== FAILURES =====================================================
_________________________________________ test_share_timetout_validation __________________________________________

    def test_share_timetout_validation():
        """Assert validation can run even with undefined (None) share_timeout"""
        shared_function_settings = SharedFunctionSettings()
        shared_function_settings.storage = 'file'
        shared_function_settings.storage = 'file'
>       assert [] == shared_function_settings.validate()

tests/robottelo/test_settings.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <robottelo.config.base.SharedFunctionSettings object at 0x7f401c4d06a0>

    def validate(self):
        """Validate the shared settings"""
        validation_errors = []
        supported_storage_handlers = ['file', 'redis']
        if self.storage not in supported_storage_handlers:
            validation_errors.append(
                '[shared] storage must be one of {}'
                .format(supported_storage_handlers)
            )
        if self.storage == 'redis':
            try:
                importlib.import_module('redis')
            except ImportError:
                validation_errors.append(
                    '[shared] python redis package not installed')
    
>       if self.share_timeout > self.MAX_SHARE_TIMEOUT:
E       TypeError: '>' not supported between instances of 'NoneType' and 'int'

robottelo/config/base.py:982: TypeError
============================================ 1 failed in 1.49 seconds =========================================
```

**Comment by rochacbruno** [comment]
@renzon I think you meant to send this against `py3` branch not master?

**Comment by renzon** [comment]
@rochacbruno: in fact fixing this on master and intending on cherry picking to py3 branch. Can you think opn any caveat?

**Comment by renzon** [comment]
Test passing on Python 3:

```console
(.venv3) [renzo@note robottelo]$ pytest tests/robottelo/test_settings.py 
=============================================== test session starts ===============================================
platform linux -- Python 3.6.4, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/renzo/PycharmProjects/robottelo, inifile:
plugins: xdist-1.22.2, services-1.2.1, mock-1.6.3, forked-0.2, cov-2.5.1
collected 1 item                                                                                                  

tests/robottelo/test_settings.py .                                                                          [100%]

============================================ 1 passed in 0.62 seconds =============================================
```

**Comment by renzon** [comment]
@kbidarkar: I would cherry pick this change to py3 branch but there is no SharedFunctionSettings on it. Are you sure our pipeline is using py3 branch?

**Comment by rochacbruno** [comment]
@renzon anyway we can merge this against master and then merge py3 on master after this as that branch has only a `unicode` check.

**Comment by kbidarkar** [comment]
I cherry-picked the `py3` commit to my own branch as py3 was not rebased.

1) robottelo branch : https://github.com/kbidarkar/robottelo/tree/6.3.z

**Comment by kbidarkar** [comment]
I will proceed by cherry-picking this commit and not wait for this to get merged.

**Comment by kbidarkar** [comment]
@renzon : thanks a lot for this fix, robottelo automation of Tier1 seems to start now.

**Pull request merged**
