### PR TITLE
[6.15.z] CapsuleContent [CompEval] Destructive tests SCA fixes

### PR DESCRIPTION
**Pull request by damoore044**
Failed auto-cherrypick of #15619 
for 6.15.z use rhel8 repos, roughly double the content counts
```
trigger: test-robottelo
pytest: tests/foreman/destructive/test_capsulecontent.py
```

### CODE REVIEW

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_capsulecontent.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7933
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_capsulecontent.py --external-logging
Test Result : =========== 1 failed, 1 passed, 2132 warnings in 14114.02s (3:55:14) ===========
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_capsulecontent.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7937
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_capsulecontent.py --external-logging
Test Result : =========== 1 passed, 2123 warnings, 1 error in 14054.87s (3:54:14) ============
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_capsulecontent.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7993
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_capsulecontent.py --external-logging
Test Result : =========== 1 failed, 1 passed, 2071 warnings in 15532.26s (4:18:52) ===========
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_capsulecontent.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8400
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_capsulecontent.py --external-logging
Test Result : =========== 1 failed, 1 passed, 2200 warnings in 17306.76s (4:48:26) ===========
```

**Pull request closed without merging**
