### PR TITLE
Introducing rhci test folder

### PR DESCRIPTION
**Pull request by sthirugn**
- to avoid rhci test failures while running against sat installation

Currently test_rhci.py fails in sat6 installation.  This PR introduces a new test folder for rhci specific tests to prevent any unnecessary failures in sat runs.

### CODE REVIEW

**Comment by JacobCallahan** [comment]
ACK good idea!

**Comment by abalakh** [comment]
I think in case of new folder file `__init__.py` should be created there too, shouldn't it?

**Comment by sthirugn** [comment]
@abalakh you are right.  I added now.

**Comment by Ichimonji10** [comment]
@anarang FYI ↑

**Comment by Ichimonji10** [comment]
ACK

**Pull request merged**
