### PR TITLE
[6.13.z] Nutanix:virt-who config API cases support for SCA enabled

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10895

Cases : PASS
```
(robottelo_vv) [root@dell-per740-68-vm-04 robottelo]# pytest ./tests/foreman/virtwho/api/test_nutanix_sca.py --disable-pytest-warnings -q
......                                                                                                                                                                                                      [100%]
6 passed, 6 deselected, 30 warnings in 509.62s (0:08:29)

```

### CODE REVIEW

**Comment by JacobCallahan** [comment]
@yanpliu can you check the PRT test failure?

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/virtwho/api/test_nutanix_sca.py

**Comment by yanpliu** [comment]
> @yanpliu can you check the PRT test failure?

@JacobCallahan I have compared the difference between https://github.com/SatelliteQE/robottelo/pull/10895 and #11111 . there are same. and I have pull the branch [cherry-pick-6.13.z-102223657e6b93ea37523755c87544e46182a5bb](https://github.com/SatelliteQE/robottelo/tree/cherry-pick-6.13.z-102223657e6b93ea37523755c87544e46182a5bb)  local and run the cases, they passed.
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ git branch
  6.13.z
* cherry-pick-6.13.z-102223657e6b93ea37523755c87544e46182a5bb
  master
  virt-who-cherrypick-fail
  virt-who-upgrade-all-tiers
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/api/test_nutanix_sca.py  --disable-pytest-warnings -q
......                                                                                                                                                                                                      [100%]
6 passed, 6 deselected, 30 warnings in 511.86s (0:08:31)

```
How to rerun the checks?

**Comment by Gauravtalreja1** [comment]
> > @yanpliu can you check the PRT test failure?
> 
> @JacobCallahan I have compared the difference between #10895 and #11111 . there are same. and I have pull the branch [cherry-pick-6.13.z-102223657e6b93ea37523755c87544e46182a5bb](https://github.com/SatelliteQE/robottelo/tree/cherry-pick-6.13.z-102223657e6b93ea37523755c87544e46182a5bb) local and run the cases, they passed.
> 
> ```
> (robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ git branch
>   6.13.z
> * cherry-pick-6.13.z-102223657e6b93ea37523755c87544e46182a5bb
>   master
>   virt-who-cherrypick-fail
>   virt-who-upgrade-all-tiers
> (robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/api/test_nutanix_sca.py  --disable-pytest-warnings -q
> ......                                                                                                                                                                                                      [100%]
> 6 passed, 6 deselected, 30 warnings in 511.86s (0:08:31)
> ```
> 
> How to rerun the checks?

@yanpliu Thanks for testing this cherry pick PR locally and putting up the results for 6.13.z
I ran the PRT but later realized we don't support running PRT for virtwho tests in CI, so we can skip this check(can add that support later cc @omkarkhatavkar ) and merge

**Comment by yanpliu** [comment]
> > > @yanpliu can you check the PRT test failure?
> > 
> > 
> > @JacobCallahan I have compared the difference between #10895 and #11111 . there are same. and I have pull the branch [cherry-pick-6.13.z-102223657e6b93ea37523755c87544e46182a5bb](https://github.com/SatelliteQE/robottelo/tree/cherry-pick-6.13.z-102223657e6b93ea37523755c87544e46182a5bb) local and run the cases, they passed.
> > ```
> > (robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ git branch
> >   6.13.z
> > * cherry-pick-6.13.z-102223657e6b93ea37523755c87544e46182a5bb
> >   master
> >   virt-who-cherrypick-fail
> >   virt-who-upgrade-all-tiers
> > (robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/api/test_nutanix_sca.py  --disable-pytest-warnings -q
> > ......                                                                                                                                                                                                      [100%]
> > 6 passed, 6 deselected, 30 warnings in 511.86s (0:08:31)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How to rerun the checks?
> 
> @yanpliu Thanks for testing this cherry pick PR locally and putting up the results for 6.13.z I ran the PRT but later realized we don't support running PRT for virtwho tests in CI, so we can skip this check(can add that support later cc @omkarkhatavkar ) and merge

@Gauravtalreja1 Thank you very much

**Pull request merged**
