### PR TITLE
[6.14.z] added scap constant

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14921

### Problem Statement
with recent changes in oscap related fixtures, the lack of the rhel9 variant in constants causes key error

### Solution
added an item into constants

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap.py -k  test_postive_create_scap_policy_with_valid_name[cjk]

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6748
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_oscap.py -k  test_postive_create_scap_policy_with_valid_name[cjk] --external-logging
Test Result : =========== 70 deselected, 78 warnings, 1 error in 659.90s (0:10:59) ===========
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap.py -k test_postive_create_scap_policy_with_valid_name[cjk]

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6818
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_oscap.py -k test_postive_create_scap_policy_with_valid_name[cjk] --external-logging
Test Result : =========== 70 deselected, 78 warnings, 1 error in 715.16s (0:11:55) ===========
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap.py -k test_postive_create_scap_policy_with_valid_name[cjk]

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6822
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_oscap.py -k test_postive_create_scap_policy_with_valid_name[cjk] --external-logging
Test Result : ========== 1 passed, 70 deselected, 79 warnings in 662.25s (0:11:02) ===========
```

**Pull request merged**
