### PR TITLE
Add location to sessions in test_hostcollection.py

### PR DESCRIPTION
**Pull request by swadeley**
Hi

Adding location at the start of sessions in ui/test_hostcollection.py

  issue #9040 refers

### CODE REVIEW

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_hostcollection.py

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_hostcollection.py

**Comment by swadeley** [comment]
Only tests/foreman/ui/test_hostcollection.py::test_positive_install_module_stream failed due to a time out
`11:12:50  ../../lib64/python3.8/site-packages/airgun/views/job_invocation.py:213: TimedOutError`

will try again

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_hostcollection.py

**Review by devendra104 — APPROVED** [review]

**Review by JacobCallahan — APPROVED** [review]

**Comment by swadeley** [comment]
Thank you.

**Pull request merged**
