### PR TITLE
ddt removal in ui content views tests

### PR DESCRIPTION
**Pull request by sthirugn**
Test results:
```sh
# nosetests tests/foreman/ui/test_contentviews.py:TestContentViewsUI.test_cv_create
.
----------------------------------------------------------------------
Ran 1 test in 49.488s

OK

# nosetests tests/foreman/ui/test_contentviews.py:TestContentViewsUI.test_cv_create_negative
.
----------------------------------------------------------------------
Ran 1 test in 147.374s

OK

# nosetests tests/foreman/ui/test_contentviews.py:TestContentViewsUI.test_positive_cv_update_name
.
----------------------------------------------------------------------
Ran 1 test in 51.800s

OK

# nosetests tests/foreman/ui/test_contentviews.py:TestContentViewsUI.test_negative_cv_update_name
.
----------------------------------------------------------------------
Ran 1 test in 142.940s

OK


# nosetests tests/foreman/ui/test_contentviews.py:TestContentViewsUI.test_positive_cv_update_description
.
----------------------------------------------------------------------
Ran 1 test in 41.104s

OK

# nosetests tests/foreman/ui/test_contentviews.py:TestContentViewsUI.test_cv_delete
.
----------------------------------------------------------------------
Ran 1 test in 173.289s

OK
```

### CODE REVIEW

**Comment by sthirugn** [comment]
rebased

**Comment by oshtaier** [comment]
ACK

**Comment by abalakh** [comment]
ACK

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
