### PR TITLE
Skipping UI tests due to BZ 1333805

### PR DESCRIPTION
**Pull request by sthirugn**
Skipping all Docker Registry UI tests due to BZ 1338071

### CODE REVIEW

**Comment by sthirugn** [comment]
This fixes 6 failures (skips) in recent tier1 run.

**Comment by omaciel** [comment]
@sthirugn as we skip tests due to BZs, are we reporting them as blockers for the release?

**Comment by sthirugn** [comment]
yep, regression + blocker

**Comment by lpramuk** [comment]
*** This bug has been marked as a duplicate of bug 1333805 ***

#1333805 is in POST state, thus closing #1338071 as DUPL

Before merging lets update Bugzilla number.

**Comment by sthirugn** [comment]
@lpramuk thank you, PR updated

**Comment by oshtaier** [comment]
Please, also correct initial message in PR

**Comment by oshtaier** [comment]
ACK

**Comment by oshtaier** [comment]
@omaciel Definitely blocker for release

**Pull request merged**
