### PR TITLE
[6.15.z] improve installer tests compatibility with pit (#15308)

### LINKED ISSUE #16200: [Failed-AutoCherryPick] - improve installer tests compatibility with pit
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.15.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/10684230409)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/15308)

### PR DESCRIPTION
**Pull request by rmynar**
cherrypick of #15308 
closes #16200

### CODE REVIEW

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8768
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/installer/test_installer.py::test_satellite_installation tests/foreman/installer/test_installer.py::test_capsule_installation --external-logging
Test Result : ============ 1 failed, 1 passed, 260 warnings in 3108.06s (0:51:48) ============
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/installer/test_installer.py::test_satellite_installation tests/foreman/installer/test_installer.py::test_capsule_installation

**Comment by lhellebr** [comment]
PRT both times:
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='<FQDN>', port=443): Max retries exceeded with url: /katello/api/organizations (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2fce62aff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/installer/test_installer.py::test_satellite_installation tests/foreman/installer/test_installer.py::test_capsule_installation

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8870
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/installer/test_installer.py::test_satellite_installation tests/foreman/installer/test_installer.py::test_capsule_installation --external-logging
Test Result : ============ 1 failed, 1 passed, 329 warnings in 3193.02s (0:53:13) ============
```

**Comment by rmynar** [comment]
Previous PRTs have failed on a known bug (SAT-28665). It is not yet fixed, but there's already a known workaround, so I updated the test to apply the workaround if bug is still open.

**Comment by rmynar** [comment]
trigger: test-robottelo
pytest: tests/foreman/installer/test_installer.py::test_satellite_installation tests/foreman/installer/test_installer.py::test_capsule_installation

**Comment by rmynar** [comment]
trigger: test-robottelo
pytest: tests/foreman/installer/test_installer.py::test_satellite_installation tests/foreman/installer/test_installer.py::test_capsule_installation
deploy_rhel_version: 8

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8903
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/installer/test_installer.py::test_satellite_installation tests/foreman/installer/test_installer.py::test_capsule_installation --external-logging
Test Result : ================= 2 passed, 463 warnings in 4644.96s (1:17:24) =================
```

**Review by ogajduse — APPROVED** [review]

**Pull request merged**
