### PR TITLE
Fix CLI SyncPlan tests

### PR DESCRIPTION
**Pull request by vsedmik**
Introduced changes:
1. Fix for several occurrences missed during helpers refactor.
2. Force explicit time format. Earlier no offset was was provided and UTC was considered, now it seems the local system time is considered instead.

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py -k 'test_positive_synchronize_custom_product_daily_recurrence or test_positive_synchronize_custom_product_future_sync_date or test_positive_synchronize_custom_product_past_sync_date or test_positive_synchronize_custom_products_future_sync_date or test_positive_synchronize_rh_product_past_sync_date or test_positive_synchronize_rh_product_future_sync_date or test_positive_synchronize_custom_product_weekly_recurrence'

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py -k 'test_positive_synchronize_custom_product_daily_recurrence or test_positive_synchronize_custom_product_future_sync_date or test_positive_synchronize_custom_product_past_sync_date or test_positive_synchronize_custom_products_future_sync_date or test_positive_synchronize_rh_product_past_sync_date or test_positive_synchronize_custom_product_weekly_recurrence'

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py -k 'test_positive_synchronize_custom_product_daily_recurrence or test_positive_synchronize_custom_product_future_sync_date or test_positive_synchronize_custom_product_past_sync_date or test_positive_synchronize_custom_products_future_sync_date or test_positive_synchronize_rh_product_past_sync_date or test_positive_synchronize_rh_product_future_sync_date or test_positive_synchronize_custom_product_weekly_recurrence'

**Comment by vsedmik** [comment]
PRT#3791 result: `tests/foreman/cli/test_syncplan.py .F.....                               [100%]`

The last failure does not relate to this PR and shall be addressed later, since we need to push as much fixes as possible now. Locally it passed however.
```
tests/foreman/api/test_syncplan.py ....... 
==== 7 passed, 107 deselected, 133 warnings in 1673.23s (0:27:53) =====
```

**Review by jyejare — APPROVED** [review]

**Comment by jyejare** [comment]
Merging as all checks are passing except one for which @vsedmik has provided the reason.

**Pull request merged**
