### PR TITLE
Add workaround for cpu_mode for EL9 Libvirt tests

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
Add workaround for cpu_mode when BZ:2236693 is open for EL9 Libvirt tests

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_libvirt.py::test_positive_provision_end_to_end[rhel9-destroy_vm_on_host_delete=True]
provisioning: true

**Comment by adarshdubey-star** [comment]
Can you have a look at the PRT failure or is it not related to the changes @Gauravtalreja1 ?

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_libvirt.py::test_positive_provision_end_to_end[rhel9-destroy_vm_on_host_delete=True]
provisioning: true

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_libvirt.py::test_positive_provision_end_to_end[rhel9-destroy_vm_on_host_delete=True]
provisioning: true

**Review by adarshdubey-star — APPROVED** [review]

**Pull request merged**
