### PR TITLE
Add test for redis type foreman-rails-cache-store

### PR DESCRIPTION
**Pull request by jameerpathan111**
Add `foreman-rails-cache-store type:redis` to satellite-installer test.

### CODE REVIEW

**Comment by jameerpathan111** [comment]
trigger: test-robottelo
pytest: tests/foreman/installer/test_installer.py -k test_satellite_and_capsule_installation

**Review by pondrejk — APPROVED** [review]

**Comment by lpramuk** [comment]
But you are changing generic installer test for testing of enablement redis cache (not really just turning on and then no test)
Wouldn't be better to have separate test instead ?

**Comment by jameerpathan111** [comment]
trigger: test-robottelo
pytest: tests/foreman/installer/test_installer.py -k test_satellite_installation_with_options

**Comment by jameerpathan111** [comment]
> But you are changing generic installer test for testing of enablement redis cache (not really just turning on and then no check that the cache gets really activated) Wouldn't be better to have separate test instead ?

Created separate test :)

**Comment by jameerpathan111** [comment]
trigger: test-robottelo
pytest: tests/foreman/installer/test_installer.py -k test_satellite_installation_with_options

**Review by Gauravtalreja1 — APPROVED** [review]

**Comment by jameerpathan111** [comment]
Merged PR as it has 2 tier-2 acks.

**Pull request merged**
