### PR TITLE
Fix original manifest generation

### PR DESCRIPTION
**Pull request by elyezer**
Make sure to download the template when using the original manifest.

Also fix a missing refactor line where is using the original manifest.

### CODE REVIEW

**Comment by elyezer** [comment]
Run the fixed test and got

```
===================== 1 failed, 32 deselected in 72.35 seconds ======================
```

It have failed on line which is not related to the manifest generation: 

```
>                   session.nav.go_to_select_org(org.name)
```

Checked the logs and the manifest upload worked fine.

**Comment by elyezer** [comment]
Run refresh_manifest from CLI to make sure:

```
$ py.test tests/foreman/cli/test_subscription.py -k'test_positive_manifest_refresh'
================================ test session starts ================================
platform linux -- Python 3.4.2, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/elyezer/code/robottelo, inifile: 
plugins: xdist-1.13.1, cov-2.2.0
collected 6 items 

tests/foreman/cli/test_subscription.py .

============= 5 tests deselected by '-ktest_positive_manifest_refresh' ==============
====================== 1 passed, 5 deselected in 39.92 seconds ======================
```

**Comment by oshtaier** [comment]
ACK

**Comment by abalakh** [comment]
ACK

**Comment by oshtaier** [comment]
Should fix 'ui.test_organization.OrganizationTestCase.test_verify_bugzilla_1259248' test on CI

**Pull request merged**
