### PR TITLE
Fixed test_positive_end_to_end

### LINKED ISSUE #7129: tests/foreman/ui/test_syncplan.py:121: AssertionError
Error Message

AssertionError: assert '' == '2019/07/08 05:07'   + 2019/07/08 05:07

Stacktrace

session = <airgun.session.Session object at 0x7f31a4b9b048>

    @tier2
    def test_positive_end_to_end(session):
        """Perform end to end scenario for sync plan component
    
        :id: 39c140a6-ca65-4b6a-a640-4a023a2f0f12
    
        :expectedresults: All CRUD actions for component finished successfully
    
        :CaseLevel: Integration
        """
        plan_name = gen_string('alpha')
        description = gen_string('alpha')
        new_description = gen_string('alpha')
        with session:
            startdate = (
                    session.browser.get_client_datetime() + timedelta(minutes=10))
            # Create new sync plan and check all values in entity that was created
            session.syncplan.create({
                'name': plan_name,
                'interval': SYNC_INTERVAL['day'],
                'description': description,
                'date_time.start_date': startdate.strftime("%Y-%m-%d"),
                'date_time.hours': startdate.strftime('%H'),
                'date_time.minutes': startdate.strftime('%M'),
            })
            assert session.syncplan.search(plan_name)[0]['Name'] == plan_name
            syncplan_values = session.syncplan.read(plan_name)
            assert syncplan_values['details']['name'] == plan_name
            assert syncplan_values['details']['description'] == description
            assert syncplan_values['details']['enabled'] == 'Yes'
            assert syncplan_values['details']['interval'] == SYNC_INTERVAL['day']
            time = syncplan_values['details']['date_time'].rpartition(':')[0]
>           assert time == startdate.strftime("%Y/%m/%d %H:%M")
E           AssertionError: assert '' == '2019/07/08 05:07'
E             + 2019/07/08 05:07

tests/foreman/ui/test_syncplan.py:121: AssertionError

### PR DESCRIPTION
**Pull request by vijay8451**
- Fixed #7129 
- Test result:
```
$ pytest -vs tests/foreman/ui/test_syncplan.py::test_positive_end_to_end 
2019-07-09 12:35:45 - conftest - DEBUG - Registering custom pytest_configure

========================================================================= test session starts ==========================================================================
platform linux -- Python 3.6.8, pytest-4.0.2, py-1.8.0, pluggy-0.11.0 -- /home/vijsingh/my_projects/env66/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/vijsingh/my_projects/PR_Proj/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.4, forked-1.0.2
collecting ... 2019-07-09 12:35:45 - conftest - DEBUG - BZ deselect is disabled in settings

collected 1 item                                                                                                                                                       

tests/foreman/ui/test_syncplan.py::test_positive_end_to_end 2019-07-09 12:35:45

PASSED2019-07-09 12:46:45 - robottelo - DEBUG - Finished Test: test_syncplan.py/test_positive_end_to_end
```

### CODE REVIEW

**Comment by vijay8451** [comment]
> was that product change? I see `time = syncplan_values['details']['date_time'].rpartition(':')[0]` returned empty value in failure.

Does not looks a product change to me ... and error is below:

> assert time == startdate.strftime("%Y/%m/%d %H:%M")
```
E AssertionError: assert 'Jul 9, 2019 8:54' == '2019/07/09 08:54'
E - Jul 9, 2019 8:54
E + 2019/07/09 08:54
```

**Comment by vijay8451** [comment]
> Given that this is a change from Sat6.5 I would like to confirm with engineering that the change is intentional before we proceed. As I am the component owner I will do that.

Thanks @swadeley I just saw below format change with 6.6:

6.6 => July 09, 2019, 10:30 AM
6.5 =>  2019/07/09 16:00:00

**Comment by latran** [comment]
I must say that the 6.6 date is much clearer than the 6.5

**Comment by swadeley** [comment]
> I must say that the 6.6 date is much clearer than the 6.5

no to me, but that's probably because you live in USA and I am used to ISO dates.

**Comment by swadeley** [comment]
[Bug 1729189 - Date format changed from ISO 8601 to USA format](https://bugzilla.redhat.com/show_bug.cgi?id=1729189)

**Comment by mirzal** [comment]
I don't think we should merge PRs that are NACKed by any reviewer. Even more so when reviewer is component owner, who by definition is supposed to own all tests.

I know we historically had problem with PRs not being merged for a long time, and I know this PR is part of UI failures fixing initiative (thanks, @vijay8451 !), but really - if there is disagreement, we can afford to spend a day or two to talk and reach consensus. Going over each others head is not going to lead us anywhere.

Also, automation is to support us and to notify us of problems in product. It's not our goal to make automation "green" by all means necessary. If this turns out to be genuine bug in the product, I believe this PR should have never entered Robottelo - these tests **should** fail, as long as bug is not fixed.

**Comment by ntkathole** [comment]
@mirzal agree with you. But this issue has been noticed previously as well and this happens due to different timezone on Jenkins and test server.

- current_time is being fetched from the machine which runs the test

- This is being set to the web-UI date and time fields.

-  The issue could be when the test machine is in 1 timezone and the web-UI in another or if both the machine are not in sync via ntp, then the test breaks.

 But I just want Stephen to look into it so that we don't miss it if change is in product, so merged and asked him to follow-up.
Thanks for checking it out.

**Pull request merged**
