### PR TITLE
Add missing super() calls to setUp to #fix 3534

### LINKED ISSUE #3534: Always call superclass's setUp() and tearDown()
With https://github.com/SatelliteQE/robottelo/pull/3533, now setUp() and tearDown() does test case logging.  Any test which overrides these should call superclass's methods to get the loggings.

### PR DESCRIPTION
**Pull request by rochacbruno**
Add missing super().setUp() calls to fix #3534

### CODE REVIEW

**Comment by rochacbruno** [comment]
```python
$ py.test -s tests/robottelo/
====================================================================== test session starts =======================================================================
platform linux2 -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/brocha/Projects/robottelo, inifile: 
plugins: ipdb-0.1.dev2, cov-2.2.1, xdist-1.14
collected 105 items 

tests/robottelo/test_api_utils.py ..
tests/robottelo/test_cli.py .....
tests/robottelo/test_config_casts.py ..............
tests/robottelo/test_config_settings.py .....
tests/robottelo/test_datafactory.py .....
tests/robottelo/test_decorators.py ...........................................
tests/robottelo/test_hammer.py .......
tests/robottelo/test_helpers.py ...........
tests/robottelo/test_ssh.py ..
tests/robottelo/test_ui.py .....
tests/robottelo/test_vm.py ......
==== 105 passed in 1.03 seconds ====
```

**Comment by oshtaier** [comment]
ACK
Do not close the issue as there still teardowns() which are not covered

**Comment by rochacbruno** [comment]
thanks @oshtaier I'll add the teardowns in the same PR. (I forgot about this)

**Comment by oshtaier** [comment]
please also check setupclass and teardownclass

**Comment by rochacbruno** [comment]
@oshtaier done, checked all setUp*, tearDown*

**Comment by oshtaier** [comment]
ACK

**Comment by abalakh** [comment]
ACK

**Pull request merged**
