### PR TITLE
Change local file and folder to allowed import path

### PR DESCRIPTION
**Pull request by sambible**
This moves CUSTOM_LOCAL_FOLDER and CUSTOM_LOCAL_FILE to an allowed import path, fixing a few tests.

### CODE REVIEW

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_repository.py::TestFileRepository

**Review by JacobCallahan — APPROVED** [review]
ACK, merge pending PRT results

**Review by swadeley — APPROVED** [review]
ACK

**Review by synkd — APPROVED** [review]
ACK

**Pull request merged**
