### PR TITLE
Mirroring policy for 7.0

### PR DESCRIPTION
**Pull request by latran**
Fix the mirroring policy test cases for 7.0

### CODE REVIEW

**Comment by latran** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_contentmanagement.py

**Comment by jyejare** [comment]
@latran Tests are failing not sure if it's related to your PR!

**Comment by latran** [comment]
@jyejare , there seems to be something wrong in general with `test_contentmanagement.py`.  I will investigate or get someone to investigate.  I half expected this and hence put it in draft.

**Comment by latran** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_contentmanagement.py

**Review by ColeHiggins2 — COMMENTED** [review]
any updates on this?

**Comment by latran** [comment]
@ColeHiggins2 it seems that capsule setup is still having the same issue when running locally.  @Griffin-Sullivan has pointed out that it's due to repos from dogfood being missing during setup.  Not sure if that's fixed yet.

**Comment by latran** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_contentmanagement.py

**Comment by jyejare** [comment]
@latran Just FYI , tests are failing yet !

**Comment by latran** [comment]
@jyejare Looking into it still.

**Review by mshriver — APPROVED** [review]

**Pull request merged**
