### PR TITLE
Update hammer_commands and test_hammer_options

### PR DESCRIPTION
**Pull request by elyezer**
Update the information being tested to match the latest compose.

### CODE REVIEW

**Comment by sthirugn** [comment]
ACK

**Comment by elyezer** [comment]
```
py.test tests/foreman/cli/test_hammer.py
================================== test session starts ===================================
platform darwin -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collected 1 items

tests/foreman/cli/test_hammer.py .

============================== 1 passed in 2020.24 seconds ===============================
```

**Comment by elyezer** [comment]
Rebased

**Comment by Ichimonji10** [comment]
ACK

**Pull request merged**
