### PR TITLE
ddt removal in ui partitiontable tests

### PR DESCRIPTION
**Pull request by sthirugn**
```sh
# nosetests tests/foreman/ui/test_partitiontable.py

----------------------------------------------------------------------
Ran 6 tests in 158.268s

OK (skipped=2)
```

### CODE REVIEW

**Comment by oshtaier** [comment]
Pending same question as in `https://github.com/SatelliteQE/robottelo/pull/2939`

**Comment by sthirugn** [comment]
@oshtaier question is addressed in #2939

**Comment by abalakh** [comment]
ACK

**Comment by sthirugn** [comment]
Rebased

**Comment by sthirugn** [comment]
all comments addressed here

**Comment by oshtaier** [comment]
ACK

**Comment by oshtaier** [comment]
rebase

**Comment by sthirugn** [comment]
Rebased.

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
