### PR TITLE
Fix reporttemplates CLI tests for output being one string, not a list of lines as it used to

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by lhellebr** [comment]
`test_positive_generate_hostpkgcompare` fails due to #9215 , others pass.

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_reporttemplates.py -k test_positive_generate_ansible_template

**Review by pondrejk — APPROVED** [review]
ack, but please squash the commits

**Comment by lhellebr** [comment]
Why not squash it during merge? There's a button for that.

**Comment by tstrych** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_reporttemplates.py::test_positive_generate_with_name_and_org tests/foreman/cli/test_reporttemplates.py::test_positive_generate_ansible_template tests/foreman/cli/test_reporttemplates.py::test_positive_generate_entitlements_report_multiple_formats tests/foreman/cli/test_reporttemplates.py::test_positive_schedule_entitlements_report

**Review by tstrych — APPROVED** [review]
ACK

**Comment by swadeley** [comment]
> Why not squash it during merge? There's a button for that.

what would the commit message be then? I don t see a useful commit message if all the commits are squashed.

**Comment by lhellebr** [comment]
For example `Fix reporttemplates CLI tests for one-string out`, really anything along the lines of PR name

**Review by jyejare — APPROVED** [review]

**Comment by jyejare** [comment]
@swadeley With squash and merge, it combines all commit messages into one commit like:

Screenshot 2021-12-09 at 12 56 36 PM


And I modified that like this before merging:

```
* Fix ReportTemplate Tests for single-string output, Styleguide fix and Remove 'import sleep'
```

**Pull request merged**
