### PR TITLE
Remove old skip_if for closed BZs

### PR DESCRIPTION
**Pull request by vsedmik**
### Problem Statement
These BZs were already closed so we don't need to skip `if open` them anymore:
https://bugzilla.redhat.com/show_bug.cgi?id=1802395
https://bugzilla.redhat.com/show_bug.cgi?id=1789028
https://bugzilla.redhat.com/show_bug.cgi?id=2112320
https://bugzilla.redhat.com/show_bug.cgi?id=1680458
https://bugzilla.redhat.com/show_bug.cgi?id=2148813

### Solution
Remove the `skip_if` conditioning.

### PRT
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py::test_positive_lock_clone_nodelete_unlock_report tests/foreman/cli/test_activationkey.py::test_create_ak_with_syspurpose_set tests/foreman/ui/test_containerimagetag.py::test_positive_search

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py::test_positive_lock_clone_nodelete_unlock_report tests/foreman/cli/test_activationkey.py::test_create_ak_with_syspurpose_set tests/foreman/ui/test_containerimagetag.py::test_positive_search

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7318
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_reporttemplates.py::test_positive_lock_clone_nodelete_unlock_report tests/foreman/cli/test_activationkey.py::test_create_ak_with_syspurpose_set tests/foreman/ui/test_containerimagetag.py::test_positive_search --external-logging
Test Result : ============= 2 passed, 68 warnings, 1 error in 917.13s (0:15:17) ==============
```

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py::test_positive_lock_clone_nodelete_unlock_report tests/foreman/cli/ tests/foreman/ui/test_containerimagetag.py::test_positive_search

**Review by vijaysawant — APPROVED** [review]
Changes are strainght forward.

**Review by ColeHiggins2 — APPROVED** [review]

**Pull request merged**
