### PR TITLE
Updated properties file for discovery_iso setting

### PR DESCRIPTION
**Pull request by sghai**

### CODE REVIEW

**Comment by sghai** [comment]
We are using modified ISO for PXE_Less discovery as mentioned in PR #3204. ISOs are already re-built and placed on external_libvirt server. However user needs to set the ISO name in properties file.
Please note that ISO's are vlan's specific that means each ISO is rebuilt based on the GW and Server_name corresponding to specific vlan. So follow the convention like:

If you'r running test against `down_el6` vlan or `qe-sat6-rhel6` server then ISO name should be like `foreman-discovery-image-3.0.5-3_unattended_down_el6.iso`

**Comment by sthirugn** [comment]
ACK

**Comment by kbidarkar** [comment]
ACK

**Comment by kbidarkar** [comment]
ACK the needed settings part exists in PR #3204.

**Pull request merged**
