### PR TITLE
Add remaining DockerContentViewTests for Docker CLI

### PR DESCRIPTION
**Pull request by abalakh**
Add remaining Docker CLI tests for adding docker repos to content views and publishing/promoting those CVs.
Slightly updated corresponding API tests as well.
Part of #2705
Depends on SatelliteQE/nailgun#195

### CODE REVIEW

**Comment by abalakh** [comment]
Will add tests results shortly.

**Comment by abalakh** [comment]
CLI tests:
```
nosetests tests/foreman/cli/test_docker.py:DockerContentViewTestCase
.............
----------------------------------------------------------------------
Ran 13 tests in 1755.582s

OK
```
API tests:
```
nosetests tests/foreman/api/test_docker.py:DockerContentViewTestCase
...........S.
----------------------------------------------------------------------
Ran 13 tests in 961.760s

OK (SKIP=1)
```

**Comment by Ichimonji10** [comment]
The API tests look great.

There's an enormous amount of duplication in the new CLI tests. At least the following code is copied and pasted in to each of the new tests:

```python
        repo = _make_docker_repo(
            make_product({'organization-id': self.org_id})['id'])
        content_view = make_content_view({
            'composite': False,
            'organization-id': self.org_id,
        })
        result = ContentView.add_repository({
            'id': content_view['id'],
            'repository-id': repo['id'],
        })
        self.assertEqual(result.return_code, 0)
        content_view = ContentView.info({'id': content_view['id']}).stdout
        self.assertIn(
            repo['id'],
            [repo_['id'] for repo_ in content_view['docker-repositories']],
        )
```

At the very least, can you put that code in to a private function? Even better, can you make a new test case?

**Comment by Ichimonji10** [comment]
ACK pending de-duplication.

**Comment by elyezer** [comment]
ACK pending comment.

**Comment by abalakh** [comment]
@Ichimonji10 it's a little bit trickier than it sounds. Off the top of my head there're 3 ways to do this:
1) Private func outside the class (like already existing `_make_docker_repo()`). With this approach we won't be able to use `self.assert***()` to verify results.
2) Private func inside the class. Main concern here is that we'll have private functions inside and outside class, which will increase overall code complexity. In addition, about 30% tests start differently and won't use this func.
3) setUp section. IMO, would be the best solution, if we didn't have those 30% tests which are different. 
We'll do some redundant stuff for them which is not OK and will affect performance. As an option here we could divide tests to 2 separate classes and use setUp section for one of them, but i'm not sure it's a good idea to split the class which contains logically and functionally connected tests.

Am I missing something? Maybe you have better ideas? Oh, and what do you mean by "make a new test case" here?

**Comment by Ichimonji10** [comment]
> 1) Private func outside the class (like already existing _make_docker_repo()). With this approach we won't be able to use self.assert***() to verify results.

It actually is possible to define a private function outside the class and make use of assertions. Define a function whose first argument is `self`, and pass in the `self` argument when calling that function from within an object.

That said, it's more straightforward to just define a method.

> Oh, and what do you mean by "make a new test case" here?

I mean "make a new class." See the definition of "test case" and other terms [here](https://docs.python.org/3.4/library/unittest.html).

> but i'm not sure it's a good idea to split the class which contains logically and functionally connected tests.

You're not sure? OK. Short of actually doing this refactor myself, I'm **very** sure it's a good idea to split up these test cases. We have hundreds of lines of copied and pasted code. That's a maintenance nightmare a strong indicator of bad code.

> Am I missing something?

Yes. Test cases are designed to reduce redundancy. From the docs:

> Tests can be numerous, and their set-up can be repetitive. Luckily, we can factor out set-up code by implementing a method called setUp(), which the testing framework will automatically call for every single test we run:

If we're stuffing all CLI docker tests into a single class, then we're completely ignoring the tools unittest gives to us.

> As an option here we could divide tests to 2 separate classes and use setUp section for one of them, but i'm not sure it's a good idea to split the class which contains logically and functionally connected tests.

Why is splitting tests in to two classes a bad idea? Because someone might get confused as to the purpose of the tests? The tests are all in a module called `tests.foreman.cli.test_docker`. That's a pretty good indication of what these tests are doing.

**Comment by abalakh** [comment]
OK, i've updated the PR, added private `_create_and_associate_repo_with_cv()` func. I guess PR is ready for the next iteration of review :smile:

**Comment by oshtaier** [comment]
Much better :smiley_cat: 
Let's wait for @Ichimonji10 feedback

**Comment by Ichimonji10** [comment]
ACK

**Comment by abalakh** [comment]
Forgot to include tests results for update:
```
nosetests tests/foreman/cli/test_docker.py:DockerContentViewTestCase
.............
----------------------------------------------------------------------
Ran 13 tests in 1741.053s

OK
```

**Pull request merged**
