### PR TITLE
reuse code - DRY principle

### PR DESCRIPTION
**Pull request by lpramuk**
let's use a function. that's what is it for.

### CODE REVIEW

**Comment by lpramuk** [comment]
DONT MERGE YET

**Comment by rplevka** [comment]
:+1: 
how on Earth i might have missed that?
could you run the appropriate tests to verify there are no issues using this approach?

**Comment by Ichimonji10** [comment]
ACK pending some form of verification.

**Comment by lpramuk** [comment]
$ nosetests tests.foreman.cli.test_import
F..................
======================================================================
FAIL: @test: Check whether all supported Sat5 macros are being
...
Ran 19 tests in 1624.827s

FAILED (failures=1)
----------------------------------------------------------------------

failure is not related to changes I've done, it's about puppet and Roman is working on fix

**Comment by Ichimonji10** [comment]
ACK

[FYI](https://guides.github.com/features/mastering-markdown/)

**Comment by rplevka** [comment]
> failure is not related to changes I've done, it's about puppet and Roman is working on fix

there it goes: #2721

ACK

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
