### PR TITLE
KatelloAgent: Use internal/CDN Tools appropriately

### PR DESCRIPTION
**Pull request by lpramuk**
- add new settings: cdn, capsule_repo, sattools_repo
- use internal/CDN Tools according to `cdn` setting

(addresses #4429 for master)

### CODE REVIEW

**Comment by rplevka** [comment]
APT - we might want to test this first

**Comment by lpramuk** [comment]
I ran one test successfully and it used new 2.9.0 katello-agent as I had set ```cdn=false```

```
$ nosetests -s tests/foreman/cli/test_host.py:KatelloAgentTestCase.test_positive_install_package
...
Installing:
 katello-agent
      noarch 2.9.0-1.el7sat   LRig0q_lJlzJrkCDmMumSybzSQk_UXMTIFXeorExjQd  26 k
Installing for dependencies:
 gofer
      noarch 2.7.6-1.el7sat   LRig0q_lJlzJrkCDmMumSybzSQk_UXMTIFXeorExjQd  84 k
 katello-agent-fact-plugin
      noarch 2.9.0-1.el7sat   LRig0q_lJlzJrkCDmMumSybzSQk_UXMTIFXeorExjQd 9.5 k
...

----------------------------------------------------------------------
Ran 1 test in 343.436s

OK
```

**Comment by lpramuk** [comment]
Guys I prefer not to squash 2 commits

**Comment by kbidarkar** [comment]
ACK

**Comment by kbidarkar** [comment]
There are testcases which need to be fixed, they will be handled separately.
We will be tracking it in here, https://github.com/SatelliteQE/robottelo/issues/4429#issuecomment-287071112

**Pull request merged**
