### PR TITLE
[6.15.z] Errata WIP for remaining UI Failures

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15085

### Problem Statement
Fix remaining UI errata failures (8-10 in recent CI 6.15.0/stream)
- Fixture improvements
- Remove some remaining outdated setup/ unusable fixtures
- Fix intermittent failures of `test_end_to_end` and `_pagination`
- Makes use of `api_factory` method proposed (_closed_)
#14974 

### Ongoing Failures
- `test_positive_content_host_previous_env`: Skipped for now, until [BZ #2280882](https://bugzilla.redhat.com/show_bug.cgi?id=2280882) is resolved.
- `test_positive_apply_for_all_hosts`: ~Testing locally~ Fixed- Airgun [PR #1387](https://github.com/SatelliteQE/airgun/pull/1387). Added End2End flag for this case, as it is now very thorough and makes use of multiple install methods.

### PRT Case
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py
airgun: 1428
```

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py
airgun: 1428

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7478
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_errata.py --external-logging
Test Result : ===== 2 failed, 15 passed, 1 skipped, 1940 warnings in 5834.74s (1:37:14) ======
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py
airgun: 1428

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7495
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_errata.py --external-logging
Test Result : ========== 17 passed, 1 skipped, 2026 warnings in 6384.63s (1:46:24) ===========
```

**Review by JacobCallahan — APPROVED** [review]

**Pull request merged**
