### PR TITLE
Fixed test_repository tests to use make_product_wait

### PR DESCRIPTION
**Pull request by sthirugn**
- to account for racing condition during product creation
- remove cacheable and isolating the product creation for each test

### CODE REVIEW

**Comment by sthirugn** [comment]
This fixes 1 failure in latest tier1 run.

**Comment by sthirugn** [comment]
```
$ py.test tests/foreman/cli/test_repository.py -k test_positive_create_with_name
======================================================================== test session starts ========================================================================
platform linux2 -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/suresh/hacking/robottelo, inifile: 
plugins: cov-2.2.1, xdist-1.14
collected 30 items 

tests/foreman/cli/test_repository.py ..

===================================================== 28 tests deselected by '-ktest_positive_create_with_name' =====================================================
============================================================= 2 passed, 28 deselected in 26.80 seconds ==============================================================
$ py.test tests/foreman/cli/test_repository.py -k test_positive_create_with_name_label
======================================================================== test session starts ========================================================================
platform linux2 -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
plugins: cov-2.2.1, xdist-1.14
collected 30 items 

tests/foreman/cli/test_repository.py .

================================================== 29 tests deselected by '-ktest_positive_create_with_name_label' ==================================================
============================================================= 1 passed, 29 deselected in 20.57 seconds ==============================================================
```

**Comment by sthirugn** [comment]
```
$ py.test tests/foreman/cli/test_repository.py -k test_positive_update_url
======================================================================== test session starts ========================================================================
platform linux2 -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
plugins: cov-2.2.1, xdist-1.14
collected 30 items 

tests/foreman/cli/test_repository.py .

======================================================== 29 tests deselected by '-ktest_positive_update_url' ========================================================
============================================================= 1 passed, 29 deselected in 216.07 seconds =============================================================
```

**Comment by oshtaier** [comment]
Sounds good. ACK

**Comment by sthirugn** [comment]
Rebased.

**Comment by elyezer** [comment]
ACK

**Pull request merged**
