### PR TITLE
[6.13.z] Updated activation key field in UI for global registration page

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10606

Changes caused by [BZ 2059829](https://bugzilla.redhat.com/show_bug.cgi?id=2059829)

Depends on: Airgun PR https://github.com/SatelliteQE/airgun/pull/802

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k global_registration
airgun: 802

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k global_registration

**Comment by JacobCallahan** [comment]
@shweta83 can you look into the PRT failure and determine if this can be merged?

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k global_registration

**Comment by shweta83** [comment]
> @shweta83 can you look into the PRT failure and determine if this can be merged?

Sure.

**Comment by devendra104** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k global_registration

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k global_registration

**Pull request merged**
