### PR TITLE
[6.12.z] Add workaround for cpu_mode for EL9 Libvirt tests

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12973

Add workaround for cpu_mode when BZ:2236693 is open for EL9 Libvirt tests

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_libvirt.py::test_positive_provision_end_to_end[rhel9-destroy_vm_on_host_delete=True]
provisioning: true

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_libvirt.py::test_positive_provision_end_to_end[rhel9-destroy_vm_on_host_delete=True]
provisioning: true

**Comment by Gauravtalreja1** [comment]
PRT failure is unrelated and looks common in component pipeline for other EL versions, and will require some investigation, so will request to merge this as is.

**Review by Griffin-Sullivan — APPROVED** [review]

**Review by shubhamsg199 — APPROVED** [review]

**Comment by shubhamsg199** [comment]
Merging considering the https://github.com/SatelliteQE/robottelo/pull/12987#issuecomment-1782504987

**Pull request merged**
