### PR TITLE
Fixed test_positive_assign_http_proxy_to_products_repositories failure

### PR DESCRIPTION
**Pull request by ColeHiggins2**
This test was failing in stream due to not having an org and location selected.

### CODE REVIEW

**Comment by ColeHiggins2** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_http_proxy.py::test_positive_assign_http_proxy_to_products_repositories

**Review by Gauravtalreja1 — APPROVED** [review]

**Review by vsedmik — APPROVED** [review]
PRT pending

**Comment by Gauravtalreja1** [comment]
@ColeHiggins2 We should cherrypick this to older versions since this failure may also occur there?

**Review by sambible — APPROVED** [review]
ack pending PRT and comment

**Review by damoore044 — APPROVED** [review]
ack- prt pending

**Comment by ColeHiggins2** [comment]
@Gauravtalreja1 this was originally just for stream... but now that you mention it, this test is failing in previous versions too. Lets cherrypick into older versions and i can see if they pass

**Comment by Gauravtalreja1** [comment]
@ColeHiggins2 Thanks for confirming, I've seen this failure in your tests for http proxy earlier, that's why I remember it :)

**Pull request merged**
