### PR TITLE
[6.13] webhook bz coverage added

### PR DESCRIPTION
**Pull request by pondrejk**
manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/11399 somehow the autocherrypick process didn't trigger

### CODE REVIEW

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_webhook.py::test_positive_end_to_end

**Comment by Griffin-Sullivan** [comment]
Any idea what happened during the read after updating?

**Review by JacobCallahan — APPROVED** [review]

**Comment by JacobCallahan** [comment]
@pondrejk PRT failed, is the change related?

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_webhook.py::test_positive_end_to_end

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
