### PR TITLE
Fix katello-certs-check valid output (#6691)

### PR DESCRIPTION
**Pull request by swadeley**
Update list of output options for katello-certs-check #6691 

======================= 1 passed in 2.10 seconds =======================
(robottelo-master) [sjw@localhost robottelo]$ pytest tests/foreman/sys/test_katello_certs_check.py::KatelloCertsCheckTestCase::test_positive_validate_katello_certs_check_output
====================== test session starts ===========================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.6.0, pluggy-0.8.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: Downloads/robottelo, inifile:
plugins: xdist-1.23.2, services-1.3.1, mock-1.10.0, forked-0.2, cov-2.6.0
collecting ... 2019-01-29 21:16:15 - conftest - DEBUG - BZ deselect is disabled in settings

collected 1 item                                                                                                             

tests/foreman/sys/test_katello_certs_check.py .                                                              [100%]

====================== 1 passed in 2.08 seconds ===============================

### CODE REVIEW

**Comment by ntkathole** [comment]
@swadeley This tests is made for asserting the options in output of katello-certs-check. In automation we are using dummy certs i.e. hostname is not equal to common name so it gives output for capsule not satellite. Currently test pass for last two snaps.

**Comment by oshtaier** [comment]
@ntkathole does it mean that we should close that PR?

**Comment by ntkathole** [comment]
@oshtaier yea, I am just waiting for @swadeley  to agree :)

**Comment by oshtaier** [comment]
got you =)

**Comment by swadeley** [comment]
@ntkathole I got message from report portal that the test failed on 2019-01-28.  It did pass twice after you fixed the permission error.

Looking in report portal more closely I now see the error was "The certificate "/tmp/server.valid.crt" has already expired on: Oct 17 10:25:11 2018".  

Anyway, I will close this now based on your explanation of the unique way this test is done.

**Pull request closed without merging**
