### PR TITLE
Pulp test fix

### PR DESCRIPTION
**Pull request by shweta83**
Fixed Pulp test case

### CODE REVIEW

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_repositories.py -k test_positive_sync_kickstart_repo

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_repositories.py -k test_positive_sync_kickstart_repo

**Review by ogajduse — APPROVED** [review]

**Comment by ogajduse** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_repositories.py::test_positive_sync_kickstart_repo

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_repositories.py -k test_positive_sync_kickstart_repo

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_repositories.py -k test_positive_sync_kickstart_repo

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
