### PR TITLE
Fix hammer commands as per recent snap

### PR DESCRIPTION
**Pull request by sthirugn**
The changes are tested in $jenkins/job/satellite6-standalone-automation/120.

The failures in this job are valid bugs and are being tracked in:
https://bugzilla.redhat.com/show_bug.cgi?id=1343551
https://bugzilla.redhat.com/show_bug.cgi?id=1344095
https://bugzilla.redhat.com/show_bug.cgi?id=1344096

### CODE REVIEW

**Comment by oshtaier** [comment]
Commit is a huge one that I even can't see the diffs =). Could you please provide any test results for that module? Or it will fail anyway because of BZs?

**Comment by sthirugn** [comment]
@oshtaier did you see my comment in https://github.com/SatelliteQE/robottelo/pull/3527#issue-159252325 ?

**Comment by oshtaier** [comment]
Not sure whether you meant your first comment or something else, but just want to know what result we will get for that test case. Will it fail till defects will be fixed?

**Comment by oshtaier** [comment]
See the result on our standalone automation job. Only regression with organization-id is present here.
Probably good to go
ACK

**Comment by rochacbruno** [comment]
ACK

**Pull request merged**
