### PR TITLE
Move all entity fields to NailGun

### PR DESCRIPTION
**Pull request by Ichimonji10**
Move the various `*Field` classes from Robottelo's `robottelo.orm` module to
NailGun's `nailgun.entity_fields` module. Move all tests for those fields to
NailGun. Fix all references to the fields, both in code and documentation, so
that Robottelo works with NailGun version 0.3.0.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
I've executed `make test-foreman-api`, and the test results were completely sane. I got a few test failures, but they were due to the Satellite itself having issues and returning HTTP 500 responses, not due to any issues with the code itself.

I've recently released NailGun version 0.3.0. See the release notes [here](https://github.com/SatelliteQE/nailgun/releases/tag/0.3.0). If this is merged, then all Robottelo users *must* make sure to execute `pip upgrade nailgun`. In fact, people can safely do that right now. NailGun 0.3.0 should be perfectly backward-compatible.

**Comment by JacobCallahan** [comment]
ACK. Are you going to port over the tests to nailgun eventually?

**Comment by Ichimonji10** [comment]
@JacobCallahan Yes, I am porting over tests as I go. I've ported over tests for the `*Field` classes already.

**Comment by Ichimonji10** [comment]
See tests [here](https://github.com/SatelliteQE/nailgun/blob/master/tests/test_entity_fields.py).

**Comment by JacobCallahan** [comment]
Good stuff!

**Comment by elyezer** [comment]
ACK, what @JacobCallahan said.

**Comment by elyezer** [comment]
Karma given

**Pull request merged**
