### PR TITLE
fix template sync asserts

### LINKED ISSUE #8586: Fix failing test api test_templatesync test_positive_import_community_templates_from_repo
This test is historically failing and the assertion needs to be revisted.
tests.foreman.api.test_templatesync.TestTemplateSyncTestCase.test_positive_import_community_templates_from_repo

`assert 132 > 150` is also ambiguous, please consider a more appropriate assertion and possibly an explanation for why the assertion could fail.

### PR DESCRIPTION
**Pull request by peterdragun**
depends on: https://github.com/SatelliteQE/foreman_templates/pull/4

resolves #8586

Foreman community template repo is archived and we never really had control about templates. There are many tests that are using our repo, so this test does not change coverage. 

Test results:
```
pytest -v tests/foreman/*/test_templatesync.py
================================================================================= test session starts =================================================================================
platform linux -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-0.13.1 -- /home/pdragun/.virtualenvs/robottelo/bin/python
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/pdragun/Documents/robottelo, configfile: pyproject.toml
plugins: cov-2.12.1, forked-1.3.0, xdist-2.3.0, services-2.2.1, reportportal-5.0.8, mock-3.6.1, ibutsu-1.16
collected 27 items / 1 deselected / 26 selected                                                                                                                                       

tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_filtered_templates_from_git PASSED                                                       [  3%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_import_filtered_templates_from_git_with_negate PASSED                                                    [  7%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_and_associate PASSED                                                                     [ 11%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_to_subdirectory PASSED                                                                   [ 15%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_export_filtered_templates_to_localdir PASSED                                                    [ 19%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_export_filtered_templates_negate PASSED                                                         [ 23%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_export_and_import_with_metadata PASSED                                                          [ 26%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_json_output_verbose_true PASSED                                                          [ 30%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_json_output_verbose_false PASSED                                                         [ 34%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_json_output_changed_key_true PASSED                                                      [ 38%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_json_output_changed_key_false PASSED                                                     [ 42%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_json_output_name_key PASSED                                                              [ 46%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_json_output_imported_key PASSED                                                          [ 50%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_json_output_file_key PASSED                                                              [ 53%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_json_output_corrupted_metadata PASSED                                                    [ 57%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_json_output_filtered_skip_message PASSED                                                 [ 61%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_json_output_no_name_error PASSED                                                         [ 65%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_json_output_no_model_error PASSED                                                        [ 69%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_json_output_blank_model_error PASSED                                                     [ 73%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_export_json_output PASSED                                                                       [ 76%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_log_to_production PASSED                                                                 [ 80%]
tests/foreman/api/test_templatesync.py::TestTemplateSyncTestCase::test_positive_export_log_to_production PASSED                                                                 [ 84%]
tests/foreman/cli/test_templatesync.py::TestTemplateSyncTestCase::test_positive_import_force_locked_template PASSED                                                             [ 88%]
tests/foreman/cli/test_templatesync.py::TestTemplateSyncTestCase::test_positive_export_filtered_templates_to_temp_dir PASSED                                                    [ 92%]
tests/foreman/ui/test_templatesync.py::test_positive_import_templates PASSED                                                                                                    [ 96%]
tests/foreman/ui/test_templatesync.py::test_positive_export_templates PASSED                                                                                                    [100%]

============================================================== 26 passed, 1 deselected, 64 warnings in 442.76s (0:07:22) ==============================================================
```

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
Can one of the admins verify this patch?

**Review by ogajduse — APPROVED** [review]
All changes reviewed. And discussed with @peterdragun.
Those deleted tests depend on the *community-templates* repository that is now in a deprecated state as its content was merged to Foreman core. Thus testing the content of the deprecated repository does not make sense to me. We should use our repository from our SatelliteQE organization instead. The biggest advantage of using it is that we have full control over the content in the repository.
Deleted tests cover the same as the other existing tests do with a difference in the repository that they use.

Our template with template mockups: https://github.com/SatelliteQE/foreman_templates

**Comment by ogajduse** [comment]
@jyejare Can you, as a former owner of the component, please do a review?

**Comment by jyejare** [comment]
@ogajduse Thanks for adding me here. I ll review this today and soon.

Just a thought, are we cleaning up the exported templates from 'SatelliteQE/foreman_templates' repository ? Either manually / automatically ?

If not, we should improve on that area, but obviously not in this PR. Can be a separate RFE.

**Comment by peterdragun** [comment]
There aren't any tests for exporting to git repository, just to local dir.  Test for exporting to git will be done as separate PR, I will make sure that those test will create new and after test delete branch in repo.

**Pull request merged**
