### PR TITLE
Fix location max length as 246

### PR DESCRIPTION
**Pull request by sthirugn**
Test results:
```
Finding files... done.
Importing test modules ... done.

----------------------------------------------------------------------
Ran 33 tests in 360.011s

OK (skipped=2)
```

### CODE REVIEW

**Comment by abalakh** [comment]
ACK. Thanks for the fix :+1:

**Comment by abalakh** [comment]
Closes #2868

**Comment by sthirugn** [comment]
@abalakh I already added `Closed` text in the commit message to automatically close the issue after merge :)

**Comment by oshtaier** [comment]
it doesn't close that issue

**Comment by oshtaier** [comment]
deleting `Closes` statement

**Comment by sthirugn** [comment]
@oshtaier not sure what you mean, https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues

**Comment by oshtaier** [comment]
I mean `Organization` part

**Comment by oshtaier** [comment]
Provided comment for initial issue #2868

**Comment by oshtaier** [comment]
One more thing. As we really like to introduce a fix and not a 'monkey' patch, please take a look on Jenkins issue more accurately. You can see that failure happened for `utf8` case, so `85` symbols are too many for Location/Organization entities. Please, calculate right value (that corresponds 246 symbols for let's say `alpha` case) and use it here

NACK till mentioned fix

**Comment by sthirugn** [comment]
@oshtaier disagree. this PR is for fixing the issue introduced by my earlier PR https://github.com/SatelliteQE/robottelo/pull/2860.  If you feel the jenkins failure is related to utf8, please create a separate github issue to work.

**Comment by oshtaier** [comment]
Me and Andrii looked more accurately and it seems that was problem with `latin1`. ACK.

**Comment by oshtaier** [comment]
Anyway, we have completely different approaches for our SDLC and it doesn't make sense to have discussion there (and meetings too) as it seems as a waste of time. I think that we need to ask someone else (who can be a decision maker). I will try to ping @omaciel tomorrow

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
