### PR TITLE
templatesync test fixes

### PR DESCRIPTION
**Pull request by pondrejk**
### Problem Statement
paths seem to have changed, made some amendments

### CODE REVIEW

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_templatesync.py::TestTemplateSyncTestCase::test_positive_export_filtered_templates_to_git

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6648
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_templatesync.py::TestTemplateSyncTestCase::test_positive_export_filtered_templates_to_git --external-logging
Test Result : ============= 2 failed, 2 passed, 40 warnings in 731.58s (0:12:11) =============
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_templatesync.py::TestTemplateSyncTestCase::test_positive_export_filtered_templates_to_git

**Comment by shweta83** [comment]
@pondrejk Can you please check the test failures?

**Comment by pondrejk** [comment]
turns out there is an another issue to investigate that affects only empty-repo exports, this pr however does reduce the failures and is a prerequisite to fixing the mentioned problem, so re-running prt with a different collection

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_templatesync.py -k test_positive_export_filtered_templates_to_git[non_empty_repo-ssh]

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6820
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_templatesync.py -k test_positive_export_filtered_templates_to_git[non_empty_repo-ssh] --external-logging
Test Result : =========== 1 passed, 7 deselected, 16 warnings in 639.42s (0:10:39) ===========
```

**Review by vsedmik — APPROVED** [review]
LGTM, PRT passed too

**Pull request merged**
