### PR TITLE
[6.12.z] Add coverage for BZ#2112098

### PR DESCRIPTION
**Pull request by vsedmik**
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13506

Closes https://github.com/SatelliteQE/robottelo/issues/13640

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k test_positive_custom_cdn_with_credential

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k test_positive_custom_cdn_with_credential

**Comment by jyejare** [comment]
@vsedmik The PRT is still failing, please look into it!

**Comment by vsedmik** [comment]
@jyejare I'm on it already - wanted to see the PRT pass on 6.13.z first and then push it here + rerun.

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k test_positive_custom_cdn_with_credential

**Comment by vsedmik** [comment]
PRT # 5353 passed.

**Pull request merged**
