### PR TITLE
Update API Host Collection tests according to sat6.2 changes

### PR DESCRIPTION
**Pull request by abalakh**
```python
py.test -v tests/foreman/api/test_hostcollection.py
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1 -- /home/andrii/env/bin/python
cachedir: .cache
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 17 items 

tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_negative_create_with_invalid_name PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_add_host <- robottelo/decorators.py SKIPPED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_add_hosts <- robottelo/decorators.py SKIPPED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_create_with_description PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_create_with_host <- robottelo/decorators.py SKIPPED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_create_with_hosts <- robottelo/decorators.py SKIPPED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_create_with_limit PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_create_with_name PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_create_with_unlimited_hosts PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_delete PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_read_host_ids <- robottelo/decorators.py SKIPPED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_update_chost <- robottelo/decorators.py SKIPPED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_update_description PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_update_hosts <- robottelo/decorators.py SKIPPED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_update_limit PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_update_name PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_update_unlimited_hosts PASSED

======================= 10 passed, 7 skipped in 47.84 seconds ========================
```

### CODE REVIEW

**Comment by abalakh** [comment]
Depends on SatelliteQE/nailgun#276

**Comment by elyezer** [comment]
ACK, pending Nailgun PR.

**Comment by oshtaier** [comment]
ACK

**Comment by abalakh** [comment]
Linking this PR with SatelliteQE/nailgun#270

**Pull request merged**
