### PR TITLE
Fixed satellite installer services check test case

### PR DESCRIPTION
**Pull request by devendra104**
Removed "foreman" from the services list in the test_positive_check_installer_services test case.

### CODE REVIEW

**Review by mirekdlugosz — APPROVED** [review]
Expected results in line 1385 still refer `foreman-tasks` service. Could you remove that reference as well?

LGTM otherwise

**Comment by devendra104** [comment]
> Expected results in line 1385 still refer `foreman-tasks` service. Could you remove that reference as well?
> 
> LGTM otherwise

Fixed.

**Review by omkarkhatavkar — APPROVED** [review]
ACK

**Comment by omkarkhatavkar** [comment]
@devendra104 travis is not happy, can you make it happy?

**Pull request merged**
