### PR TITLE
hosts cockpit tests fix

### PR DESCRIPTION
**Pull request by pnovotny**
Use global registration for Cockipt host.

It shoud fix problem with repo setup & Cockpit installation.

### CODE REVIEW

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_host.py -k test_positive_cockpit

**Review by lhellebr — COMMENTED** [review]
Looking at the changes, they look sane, but in PRT:

```
    def test_positive_cockpit(self, cockpit_host, class_cockpit_sat, class_org):
        [...]
        with class_cockpit_sat.ui_session() as session:
            session.organization.select(org_name=class_org.name)
            session.location.select(loc_name=ANY_CONTEXT['location'])
            kill_process = class_cockpit_sat.execute('pkill -f cockpit-ws')
>           assert kill_process.status == 0
E           AssertionError: assert 1 == 0
E            +  where 1 = stdout:\n\nstderr:\n(0, b'')\nstatus: 1.status
```

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_host.py -k test_positive_cockpit

**Comment by pnovotny** [comment]
Rebasing & re-running PRT. I see in ReportPortal that on with the latest 6.14. only rhel_7 host failed, the rest (rhel 8 & 9) is passing.

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_host.py -k test_positive_cockpit

**Pull request closed without merging**
