### PR TITLE
ddt removal in ui domain tests

### PR DESCRIPTION
**Pull request by sthirugn**
test results:
```sh
# nosetests tests/foreman/ui/test_domain.py:Domain.test_create_domain_1
.
----------------------------------------------------------------------
Ran 1 test in 32.009s

OK
# nosetests tests/foreman/ui/test_domain.py:Domain.test_create_domain_2
.
----------------------------------------------------------------------
Ran 1 test in 32.329s

OK
# nosetests tests/foreman/ui/test_domain.py:Domain.test_update_domain
S
----------------------------------------------------------------------
Ran 1 test in 33.316s

OK (SKIP=1)
# nosetests tests/foreman/ui/test_domain.py:Domain.test_negative_create_domain
.
----------------------------------------------------------------------
Ran 1 test in 36.820s

OK
# nosetests tests/foreman/ui/test_domain.py:Domain.test_positive_set_domain_parameter_1
.
----------------------------------------------------------------------
Ran 1 test in 61.225s

OK
# nosetests tests/foreman/ui/test_domain.py:Domain.test_remove_domain_parameter
.
----------------------------------------------------------------------
Ran 1 test in 82.572s

OK
```

### CODE REVIEW

**Comment by oshtaier** [comment]
Do we have any difference in any QA terms between `test_create_domain_1` and `test_create_domain_2` methods? I propose to leave only second case as it covers all possible scenarios described in first one.

**Comment by sthirugn** [comment]
@oshtaier you are right.  But this is not the only ui module which does these tests separately.  There are other ui modules which do this.  So I kept it as it is.  I can probably create an issue to follow up on this for this module and for other modules in UI.

**Comment by oshtaier** [comment]
@sthirugn Got it. You are right. Let's finish with ddt removal and address all these concerns separately

**Comment by oshtaier** [comment]
ACK

**Comment by omaciel** [comment]
ACK

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
