### PR TITLE
Remove Puppet and add exception for OSTree for repository testing

### PR DESCRIPTION
**Pull request by sambible**
Puppet and OSTree are no longer supported content-types, and file is. Removed/Added where appropriate

### CODE REVIEW

**Comment by mshriver** [comment]
@sambible there are uses of these keys in the repo, they need to be handled if you're going to remove those repo types from constants.  This search is even limited because of the quote usage

```
❯ grep -r "REPO_TYPE\['ostree" ./*
./robottelo/products.py:REPO_TYPE_OSTREE = constants.REPO_TYPE['ostree']
./tests/foreman/ui/test_contentview.py:        repo_type=REPO_TYPE['ostree'],
./tests/foreman/ui/test_contentview.py:        content_type=REPO_TYPE['ostree'],
./tests/foreman/ui/test_repository.py:#                 'repo_type': REPO_TYPE['ostree'],
❯ grep -r "REPO_TYPE\['puppet" ./*
./robottelo/products.py:REPO_TYPE_PUPPET = constants.REPO_TYPE['puppet']
```

**Comment by sambible** [comment]
Refactored this a bit, only removed puppet, didn't add another type, and disabled ostree in the failing test, since the Ostree test in UI indicates this is going to be readded in Satellite 7.

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_repository.py::test_negative_update_to_invalid_download_policy

**Comment by sambible** [comment]
@mshriver can I get a re-review on this?

**Comment by swadeley** [comment]
Hi @sambible 

I am a bit confused:

`TODO: Remove ostree from exceptions when ostree is added back in Satellite 7` is in test `test_negative_update_to_invalid_download_policy` 
but 
`if content_type != 'ostree'` is for `test_negative_create_non_yum_with_download_policy` 

Is that the exception you mean?

Thank you

**Comment by sambible** [comment]
Oh, good catch - I placed it in the wrong test. As you said, it should be put in the description of test_negative_create_non_yum_with_download_policy. Still getting used to the placement of parameterize fixture options.

**Review by JacobCallahan — APPROVED** [review]

**Pull request merged**
