### PR TITLE
cherry pick test fix test_negative_without_attach_with_lce

### PR DESCRIPTION
**Pull request by tstrych**
ChP of #8023

### CODE REVIEW

**Comment by tstrych** [comment]
For more info and test results pls go to #8062, 

Travis fail not connected. I paste it here for you.
```
tests/foreman/ui/test_rhcloud_inventory.py
==========================================
test_rhcloud_inventory_e2e:142
------------------------------
* Tokens with invalid values:
  Casecomponent: RHCloud-Inventory (type: 'choice')
Total number of tests: 461
Total number of invalid docstrings: 1 (00.22%)
Test cases with no docstrings: 0 (0.00%)
Test cases missing minimal docstrings: 0 (0.00%)
Test cases with unexpected tags: 0 (0.00%)
Test cases with unexpected token values in docstrings: 1 (0.22%)
Test cases with unparseable docstrings: 0 (0.00%)
Makefile:67: recipe for target 'test-docstrings' failed
make: *** [test-docstrings] Error 255
```

**Comment by tstrych** [comment]
wrong cherry-picked file and mess in git afterwards, will do that again in different branch :)

**Comment by tstrych** [comment]
I learned hard way, why I should squash my comments before merge :)

**Review by mirekdlugosz — APPROVED** [review]
ACK

**Review by rplevka — COMMENTED** [review]
ACK

**Pull request merged**
