### PR TITLE
[6.15.z] Integrate FAM pipeline into robottelo

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14028

### Problem Statement
Current FAM misc pipeline has been broken for a couple releases. This is due to some version changes, but also we were not testing things as accurately as possible. For instance, we were cloning upstream and running the develop branch.

### Solution
Integrate the FAM pipeline into robottelo. This now runs everything on the satellite against itself, so we know that the collection being packaged in Satellite is working correctly.

### Note
The expectation is not that this will pass 100%. Getting all of the modules and roles to pass will take individual setup that needs to be done in robottelo, AAP, or upstream in the test playbook itself. For now I would like to see that the tests are executing as expected and the results show helpful output on failure (ie: the actual ansible tasking logs). After merging, we will need to evaluate as teams how to remediate the issues based on component and team.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: -vv tests/foreman/sys/test_fam.py::test_positive_run_modules_and_roles

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5813
Build Status: UNSTABLE
PRT Comment: pytest -vv tests/foreman/sys/test_fam.py::test_positive_run_modules_and_roles
Test Result : ================ 35 warnings, 110 errors in 1564.41s (0:26:04) =================
```

**Comment by jameerpathan111** [comment]
All tests failed with `failed on setup with "broker.exceptions.ProviderError"`, re-triggering the job.

**Comment by jameerpathan111** [comment]
trigger: test-robottelo
pytest: -vv tests/foreman/sys/test_fam.py::test_positive_run_modules_and_roles

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5817
Build Status: UNSTABLE
PRT Comment: pytest -vv tests/foreman/sys/test_fam.py::test_positive_run_modules_and_roles
Test Result : ================ 29 warnings, 110 errors in 1522.71s (0:25:22) =================
```

**Comment by Griffin-Sullivan** [comment]
This and the other branches will need https://github.com/SatelliteQE/robottelo/pull/14238

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6083
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/sys/test_fam.py::test_positive_run_modules_and_roles[activation_key] --external-logging
Test Result : ================== 1 failed, 1 warning in 1487.97s (0:24:47) ===================
```

**Pull request merged**
