### PR TITLE
Pulling in capsule changes from master to 6.3.z branch

### LINKED ISSUE #6431: backport capsule tests redesign to 6.3.z
https://github.com/SatelliteQE/robottelo/pull/6130

- this might be wasted energy as it is possible that we decide not to run these test on 6.3 any longer

### PR DESCRIPTION
**Pull request by latran**
Fixes #6431

refactor capsule tests

### CODE REVIEW

**Comment by latran** [comment]
There's a conflict about using the capsule_id and capsule_hostname.  What should we use going forward?

**Comment by rplevka** [comment]
@latran hey. thanks for picking this up.
what conflict are you referring to? You lost me :)

**Comment by rplevka** [comment]
@latran hey. are yo ustill working on this?

**Comment by latran** [comment]
@rplevka I have not had a chance to continue work on this.  Will reach out to @JacobCallahan for assistance.

**Comment by latran** [comment]
I decided to use capsule_id since it's more consistent with the previous uses of the ssh command.

**Comment by latran** [comment]
@oshtaier 

Hey found this issue related to your pull request.  Is this something that also needs to be fixed in the 6.3.z branch?

```
$ flake8 .
./tests/foreman/api/test_contentmanagement.py:1113:31: W605 invalid escape sequence '\;'
```

**Comment by oshtaier** [comment]
if `flake8 .` returns no issues for you, so you don't need it. I am not sure as development went far away in `master` and I am not looking in `6.3` for a long time

**Comment by latran** [comment]
This is consistent with master branch despite code coverage drop.

Code coverage drop: 0.16%

**Comment by san7ket** [comment]
Can we please test it once, do get it merged

**Comment by rplevka** [comment]
Is this ready to be merged? @latran have you got a chance to test it?
Anyway, this branch will be abandoned soon, as with release of 6.5.0, the 6.3 reaches end of life.

**Comment by latran** [comment]
@rplevka @san7ket 

I'll try to get testing done today and tomorrow.

**Comment by latran** [comment]
This is taking a bit more time than I anticipated, but I'll get it done as soon as I can within next week.

**Comment by rplevka** [comment]
@latran, maybe it's no longer worth the effort, I appreciate it tho

**Comment by latran** [comment]
@rplevka , Maybe so because I have to test the capsule test cases in regards to this cherry pick.  That means getting 2 machines from beaker, manually install satellite 6.3 GA to it, make sure it work, then setup a capsule, then finally test.  A lot of things there to do there and hitting walls at each encounter.

**Comment by latran** [comment]
@rplevka 
Testing is not worth the effort anymore.  It's either way more difficult than anticipated or too much configuration that I can't figure out.  So let's just merge the code.

**Comment by oshtaier** [comment]
`Testing is not worth the effort anymore.`
Sounds like we should close the PR, not merge it

**Comment by san7ket** [comment]
Closing it, as per comments

**Pull request closed without merging**
