### PR TITLE
Update Satellite 7.0 references to 6.11

### PR DESCRIPTION
**Pull request by JacobCallahan**
... it never happened.

### CODE REVIEW

**Comment by JacobCallahan** [comment]
This is likely not all the references that need to be updated, but the most obvious.

**Review by mshriver — APPROVED** [review]
image

**Review by jyejare — APPROVED** [review]
We need to make sure that we have open a parallel PR in CI !

**Review by latran — APPROVED** [review]

**Comment by akhil-jha** [comment]
https://github.com/SatelliteQE/robottelo/blob/master/tests/upgrades/test_satellite_maintain.py#L76

https://github.com/SatelliteQE/robottelo/blob/master/tests/robottelo/test_issue_handlers.py#L119 
https://github.com/SatelliteQE/robottelo/blob/master/tests/robottelo/test_issue_handlers.py#L85

**Comment by JacobCallahan** [comment]
@akhil-jha thanks. I'll include the satellite maintain lines you linked, but I'll leave robottelo tests alone.

**Review by ColeHiggins2 — APPROVED** [review]
ACK

**Pull request merged**
