### PR TITLE
Add assertIn statement for debugging (#6801)

### PR DESCRIPTION
**Pull request by swadeley**
Hello @JacobCallahan 

Please review location of `self.assertIn(interval, valid_intervals)`

Thank you

### CODE REVIEW

**Comment by swadeley** [comment]
robottelo]$ pytest -v tests/foreman/api/test_syncplan.py::SyncPlanUpdateTestCase::test_positive_update_interval
=========================== test session starts =================================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.6.0, pluggy-0.8.1 -- /.virtualenvs/robottelo-master/bin/python3
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo, inifile:
plugins: xdist-1.23.2, services-1.3.1, repeat-0.8.0, mock-1.10.0, forked-0.2, cov-2.6.0
collecting ... 2019-03-12 10:17:31 - conftest - DEBUG - BZ deselect is disabled in settings

collected 1 item                                                                                                                                             

tests/foreman/api/test_syncplan.py::SyncPlanUpdateTestCase::test_positive_update_interval PASSED                                                       [100%]

============================ 1 passed in 10.32 seconds ===========================

**Comment by oshtaier** [comment]
First I tried go that way:
```
list = valid_sync_interval()
cron_expression = gen_choice(valid_cron_expressions())
interval = list.pop()
while list:
    sync_plan = entities.SyncPlan(
	description=gen_string('alpha'),
	organization=self.org,
	interval=interval
	cron_expression = cron_expression if interval == SYNC_INTERVAL['custom'] else None
    ).create()
    new_interval = list.pop()
...
```

but then I understand that initial idea is wrong from the start and we need to create two separate test cases as we doing two different process in one:
```
sync_plan = entities.SyncPlan(
    description=gen_string('alpha'),
    organization=self.org,
    interval=SYNC_INTERVAL['hour']
).create()
sync_plan.interval = SYNC_INTERVAL['week']
sync_plan = sync_plan.update(['interval'])
self.assertEqual(sync_plan.interval, new_interval)
```
and
```
cron_expression = gen_choice(valid_cron_expressions())
sync_plan = entities.SyncPlan(
    description=gen_string('alpha'),
    organization=self.org,
    interval=SYNC_INTERVAL['day']
).create()
sync_plan.interval = SYNC_INTERVAL['custom']
sync_plan.cron_expression = cron_expression 
sync_plan = sync_plan.update(['interval', 'cron_expression'])
self.assertEqual(sync_plan.interval, new_interval)
self.assertEqual(sync_plan.cron_expression, cron_expression)
```

Yes, we can randomize the process more, but value of that is near zero

**Comment by swadeley** [comment]
Hello

Looking at latest failure for that test, I see it fails in a different place:

        # We don't want a single dictionary value.
        if not isinstance(choices, Iterable) or isinstance(choices, dict):
            raise ValueError('Choices argument is not iterable.')
        if not choices:
> raise ValueError('Choices argument cannot be empty.')
E ValueError: Choices argument cannot be empty.

site-packages/fauxfactory/factories/choices.py:27: ValueError

**Comment by omaciel** [comment]
@JacobCallahan @oshtaier what's blocking this from being merged?

**Comment by oshtaier** [comment]
@omaciel I do not see that my comment was addressed. The whole test case is wrong as we mixed two different things inside one. I like to see it rewritten rather than improving debug procedure for invalid functionality

**Comment by oshtaier** [comment]
And so sorry for delay, I thought that it was obvious that review cannot be moved forward till person replied to the blocking comment

**Comment by swadeley** [comment]
> master is not place to put debug statement. Give me a moment to rewrite test

@oshtaier  I do not regard that assert statement as a temporary debug statement and see no harm in it.

**Comment by oshtaier** [comment]
Yes, there is no harm in it, but I thought that we can improve our code in other way. That's all

**Comment by omaciel** [comment]
@swadeley @oshtaier I'll be honest that without much context, I'm still baffled as to why this **one line** change is taking so long. Is the assertion incorrect or is the entire test incorrect?

**Comment by oshtaier** [comment]
@omaciel 
I replied to that PR right away, after two days:
image

and spend 2+ hours to that comment, so yeah, I pretty much don't care on that one line and requested redesign for the test case entirely

In general, I see people is too lazy to even discuss completed solution, so from my side I do the same and start ignoring PRs from them.

**Comment by omaciel** [comment]
@oshtaier I feel that this language and attitude is uncalled for and not what I expect from a professional such as yourself. I kindly ask that you reconsider your poor choice of words and make amends with the parties involved. You and I can talk when I'm back from PTO next week.

**Comment by oshtaier** [comment]
@omaciel sure, any time you like, but I can assure you, that situation happened only because we have too few reviewers on the project. I would add more, but it is out of scope for public github. You are right, let's not create bad experience from nothing. I will continue to do my best to improve quality on the project

**Pull request closed without merging**
