### PR TITLE
[6.13.z][Cherrypick] Merge and refactor leapp tests

### PR DESCRIPTION
**Pull request by shweta83**
### Problem Statement
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/15571 on 6.13.z

### Solution
Resolves https://github.com/SatelliteQE/robottelo/issues/16367

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
@shweta83 Could you incorporate this change in this PR https://github.com/SatelliteQE/robottelo/pull/16433 ?

**Comment by shweta83** [comment]
> @shweta83 Could you incorporate this change in this PR #16433 ?

Added the changes.

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8798
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py --external-logging
Test Result : ================= 2 failed, 161 warnings in 2690.12s (0:44:50) =================
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py
deploy_rhel_version: 8

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8953
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py --external-logging
Test Result : ================= 2 failed, 167 warnings in 3091.85s (0:51:31) =================
```

**Comment by Gauravtalreja1** [comment]
@shweta83 Could you update this PR?

**Pull request closed without merging**
