### PR TITLE
Support WebElement as alternative to locators in basic UI helpers

### PR DESCRIPTION
**Pull request by abalakh**
`Base.click` is already supporting both locators and WebElement, updating following methods accordingly:
* text_field_update
* element_type
* select
* assign_value

This change is required for upcoming PR covering #778 as i play with WebElements directly there.

Some test results for existing tests using these helpers (just to prove no regressions were added):
* Ace editor:
```python
py.test tests/foreman/ui/test_remoteexecution.py -k test_positive_view_diff
============================= test session starts ==============================
platform linux2 -- Python 2.7.10, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 17 items 

tests/foreman/ui/test_remoteexecution.py .

============================= 16 tests deselected ==============================
=================== 1 passed, 16 deselected in 78.80 seconds ===================
```
* Select:
```python
py.test tests/foreman/ui/test_activationkey.py -k test_positive_create_with_envs
========================= test session starts ==========================
platform linux2 -- Python 2.7.10, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 33 items 

tests/foreman/ui/test_activationkey.py .

========================= 32 tests deselected ==========================
============== 1 passed, 32 deselected in 131.24 seconds ===============
```
* Checkbox:
```python
py.test tests/foreman/ui/test_sync.py -k test_positive_sync_custom_repo
========================= test session starts ==========================
platform linux2 -- Python 2.7.10, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 5 items 

tests/foreman/ui/test_sync.py .

========================== 4 tests deselected ==========================
=============== 1 passed, 4 deselected in 74.61 seconds ================
```

### CODE REVIEW

**Comment by abalakh** [comment]
`[DONOTMERGE]` prefix as there are no results for using these helpers with WebElements so far, i'll add them as soon as PR for #778 is ready.

**Comment by abalakh** [comment]
Test results for WebElements provided in #4059 (https://github.com/SatelliteQE/robottelo/pull/4059#issuecomment-264171073)

**Comment by sghai** [comment]
@rochacbruno @renzon : hey.. Could you guys please review this PR ?

**Comment by abalakh** [comment]
Hm... It appears we do not support updating radio buttons in `Base.assign_value()`. Lemme quickly fix that too is scope of this PR (i don't want to rise the third dependent PR, it's a nightmare to cherry-pick changes between branches to test things out and then revert everything back for updating PR)

**Comment by abalakh** [comment]
Done. Test results for radio button are provided in https://github.com/SatelliteQE/robottelo/pull/4059#issuecomment-264202524

**Pull request merged**
