### PR TITLE
Remove the sub-man status (#14783)

### PR DESCRIPTION
**Pull request by shweta83**
### Problem Statement
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/14783

### CODE REVIEW

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_registration.py -k 'test_positive_force_register_twice'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6541
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_registration.py -k test_positive_force_register_twice --external-logging
Test Result : ========== 12 deselected, 20 warnings, 3 errors in 290.42s (0:04:50) ===========
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6543
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_registration.py -k test_positive_force_register_twice --external-logging
Test Result : ========== 3 passed, 12 deselected, 50 warnings in 1043.45s (0:17:23) ==========
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_registration.py -k 'test_positive_force_register_twice'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6558
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_registration.py -k test_positive_force_register_twice --external-logging
Test Result : ========== 3 passed, 12 deselected, 47 warnings in 765.95s (0:12:45) ===========
```

**Review by shubhamsg199 — APPROVED** [review]

**Pull request merged**
