### PR TITLE
API stubs for Smart Variables feature

### PR DESCRIPTION
**Pull request by jyejare**
41 API stubs for Smart Variables feature.

### CODE REVIEW

**Comment by oshtaier** [comment]
API returned only JSON output. I don't think that we should YAML word here at all

**Comment by jyejare** [comment]
@oshtaier Actually the RFE raised to show YAML output of host in API and CLI as well.

**Comment by sghai** [comment]
I think here we should decide on whether we should add test stubs which are dependent on some RFE (which is still in new state)?  I mean If we leave those stubs unimplemented how a person would know later,  if those are ready for automation or blocked. May be we should add @BZ tag with `RFE ID` in relevant stubs?

thoughts ?

**Comment by oshtaier** [comment]
In that particular situation, I think that verification steps are wrong and we should be able to verify that functionality works in another way

But in general, yes, if we add stubs that should 'probably work' in future, we have to add better description and BZ ID

**Comment by oshtaier** [comment]
1) YAML output button is specific only to UI and should not be mentioned in CLI or API tests. For CLI, we can specify '--output=yaml', but it doesn't contain any information about smart variables, so far. API using JSON as a standard for all interactions. We have to re-implement stubs to represent correct validation and flow which is specific for API and CLI only
2) We have to provide more details for complex cases (like merge overrides and etc), because at that moment they are good only for UI and were not tested on CLI or API

NACK for that PR till bunch of cases containing word YAML will be clarified or at least tested for specific interface (API in that case)

**Comment by jyejare** [comment]
@oshtaier : Absolutely, currently there is no way to check YAML output from API and CLI for smart variables. But as I said earlier the RFE is logged for getting YAML output of host from API and CLI. And so updated YAML affected stubs with that RFE bz id.
The main intention to put those YAML stubs is we can check/test behavior of merge_overrides, merge_default and avoid_duplicates only via YAML output. Also I dont want to take them out now and wait/track the RFE to get merged. So I can skip them if bug open with RFE bz id.

**Comment by oshtaier** [comment]
Still, I don't think that for API/CLI it will be called as 'YAML output'. Probably, for API it will be just few more new parameters in returned dictionary when we call GET to the server. Same for CLI, it will be just new parameters when we call `info`. Thing that we should verify should not have any connection to word `YAML` or phrase `YAML output` as we need just more information about Smat Variables and Smart Class Parameters for Host entity

**Comment by oshtaier** [comment]
Thanks @jyejare for explanation. I think we can go with ENC output name + RFE Bugzilla ID for every test that cannot be implemented at that moment

**Comment by jyejare** [comment]
@oshtaier , I updated PR with term ENC instead of YAML. Please continue to review my PR.

**Comment by sghai** [comment]
ACK

**Pull request merged**
