### PR TITLE
Create Satellite object based on the Capsule answer file

### PR DESCRIPTION
**Pull request by ogajduse**
The current implementation of `satellite` property - inherited from `ContentHost` class:
```python
@property
    def satellite(self):
        if not self._satellite:
            self._satellite = Satellite()
        return self._satellite
```

Patch in this PR ensures that `Capsule` always gets the correct Satellite instance assigned in its `satellite` property.
The assumption is that `satellite-installer --scenario capsule` was run on the capsule host, therefore the answer file should contain the hostname/URL of the Satellite host it is connected to. After the hostname is obtained from the answer file, it tries to find the host in the inventory. If it is not found there, it tries to create `Satellite` with that hostname anyway, if that fails, it falls back to the Satellite assigned to the xdist worker.

Requires SatelliteQE/broker#182

### CODE REVIEW

**Comment by ogajduse** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_async_ssh_provider

**Review by pondrejk — APPROVED** [review]

**Review by Griffin-Sullivan — APPROVED** [review]
Nice addition! Can we rebase and make sure checks are passing?

**Review by jyejare — APPROVED** [review]

**Comment by ogajduse** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_async_ssh_provider

**Comment by ogajduse** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_async_ssh_provider -k

**Comment by ogajduse** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_async_ssh_provider[rhel9]

**Review by vsedmik — APPROVED** [review]

**Review by JacobCallahan — APPROVED** [review]

**Pull request merged**
