### PR TITLE
Do not merge, just a packit test

### PR DESCRIPTION
**Pull request by vsedmik**
Just a packit test PR for https://github.com/Katello/katello/pull/11092

### CODE REVIEW

**Comment by vsedmik** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_end_to_end
Katello:
    katello: 11092
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7900
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_end_to_end --external-logging
Test Result : ========== 2 failed, 5 deselected, 139 warnings in 2329.35s (0:38:49) ==========
```

**Comment by vsedmik** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_end_to_end
Katello:
    katello: 11092
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7927
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_end_to_end --external-logging
Test Result : ========== 2 passed, 5 deselected, 136 warnings in 2504.42s (0:41:44) ==========
```

**Review by ColeHiggins2 — APPROVED** [review]

**Comment by vsedmik** [comment]
Upstream fix PR has been merged, closing.

**Pull request closed without merging**
