### PR TITLE
Fix: CLI test_host/test_positive_create_using_libvirt_without_mac

### PR DESCRIPTION
**Pull request by lpramuk**
Fix: CLI test_host/test_positive_create_using_libvirt_without_mac

+ use setup external libvirt instead of blindly expecting libvirt of SAT6 machine
+ added creation assert
+ added cleanup (Host.delete)

(Part of #2931.)

### CODE REVIEW

**Comment by lpramuk** [comment]
External libvirt access is setup in automation-tools by postinstall task ```setup_libvirt_key``` called within ```product_install```

**Comment by lpramuk** [comment]
$ nosetests test_host
..............................
----------------------------------------------------------------------
Ran 30 tests in 2213.021s

OK

**Comment by lpramuk** [comment]
This test has been failing since ever (before October it had been skipped)
Fix has been waiting for infrastructure (external libvirt machine access)

**Comment by abalakh** [comment]
Cool :+1: 
Now the test is dependent on config's `compute_resources` section. Mind decorating the test with `skip_if_not_set` decorator?

**Comment by lpramuk** [comment]
+1 Good point. Decorator added.

**Comment by abalakh** [comment]
Thanks.
One more thing - local test results unfortunately proves nothing. Locally this test was passing even before the fix, it's failing only on jenkins machines.
Could you please double check by running this test against sat6 machines, used by jenkins? I tried running the test with your changes against rhel6 machine and the test failed with the same error as before - `undefined method 'name' for nil:NilClass`. Of course, i could miss to configure something.

**Comment by sghai** [comment]
Guys: I guess this test creates a dummy host not a real host.

**Comment by sghai** [comment]
More info is here https://github.com/SatelliteQE/robottelo/issues/2865

**Comment by lpramuk** [comment]
@abalakh  jenkins machines are now setup - see SatelliteQE/automation-tools PR #278

**Comment by lpramuk** [comment]
@sghai 
Yes, this PR actually fixes #2865

**Comment by lpramuk** [comment]
if connection to compute resource is succesful then error ```undefined method 'name' for nil:NilClass``` is gone.

To avoid the error, you need to use sane connection string for compute resource not just blindly expect that libvirt is running @localhost.

One way was to setup and run libvirt on localhost (SAT6),  another way was to use configured external libvirt, (the one I chose )

**Comment by lpramuk** [comment]
@sghai 
Looking at libvirt1, I think a cleanup (host deletion) will be necesary.

**Comment by lpramuk** [comment]
Now I'm more happy about PR:
+ added creation assert
+ added cleanup (Host.delete)

**Comment by lpramuk** [comment]
```
$ nosetests -s tests.foreman.cli.test_host:HostCreateTestCase.test_positive_create_using_libvirt_without_mac
...
Host deleted

.
----------------------------------------------------------------------
Ran 1 test in 45.544s

OK
```

**Comment by sghai** [comment]
ACK.. LGTM

**Comment by abalakh** [comment]
Probably jenkins machines fix is applied now - i've run the test there and it's passing.
Thank you @lpramuk for fixing this.
ACK

**Pull request merged**
