### PR TITLE
Fix metadata CaseComponent ContentManagement

### PR DESCRIPTION
**Pull request by swadeley**
One CaseComponent fix and fix format of bugzilla reference.

### CODE REVIEW

**Comment by JacobCallahan** [comment]
Candlepin likely would be the most accurate component. A bit of a weird test, but it's tied to a bug so I'm good with it.

**Comment by swadeley** [comment]
Hello

The bug its tied to has "Content Management" as the component:

[Bug 1112802 - Subscription manager routes should be anchored at their own API](https://bugzilla.redhat.com/show_bug.cgi?id=1112802)

its really a test for RHSM routes, which I realise now lead to Candlepin.

I will change it as requested.

Thanks

**Comment by swadeley** [comment]
Hello @pgagne, please approve and merge.

Thank oyu

**Comment by pgagne** [comment]
ACK

**Comment by swadeley** [comment]
Thank you all

**Pull request merged**
