### PR TITLE
[6.14.z] Bump el9 kickstart version to 9.4

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15007

### Problem Statement
New el9.4 is GA'ed, and kickstart constants requires an update.

### Solution
we need to manually bump this kickstart constants for provisioning tests

PRT is expected to fail due to known broker issue, so manually tested the el9.4 provisioning.
```
# cat /etc/redhat-release
Red Hat Enterprise Linux release 9.4 (Plow)
```

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6863
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel --external-logging
Test Result : ============ 1 failed, 118 warnings, 1 error in 2666.80s (0:44:26) =============
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6873
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel --external-logging
Test Result : ============ 1 failed, 127 warnings, 1 error in 2882.14s (0:48:02) =============
```

**Review by shweta83 — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
PRT failures are unrelated to this changes and are related to Leapp upgrade

**Review by shubhamsg199 — APPROVED** [review]

**Pull request merged**
