### PR TITLE
[6.3] FIX  CLI capsule timeout issue

### PR DESCRIPTION
**Pull request by ldjebran**
```
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test -v tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_positive_remove_cv_version_from_multi_env_capsule_scenario
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.2, cov-2.4.0
collected 1 item 
2017-08-16 17:52:45 - conftest - DEBUG - Found WONTFIX in decorated tests ['1147100', '1269208', '1269196', '1378009', '1245334', '1217635', '1226425', '1156555', '1311113', '1199150', '1238247', '1204686', '1267224', '1221971', '1103157', '1230902', '1230865', '1214312', '1079482']

2017-08-16 17:52:45 - conftest - DEBUG - Collected 1 test cases


tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_positive_remove_cv_version_from_multi_env_capsule_scenario <- robottelo/decorators/__init__.py PASSED

================================================== 0 tests deselected ==================================================
============================================= 1 passed in 2288.04 seconds ==============================================
```

### CODE REVIEW

**Comment by oshtaier** [comment]
Is it valid that it can sync for 1 hour? Do you think any real user wait for such period?

**Comment by ldjebran** [comment]
@oshtaier any way we have no SLA regarding the numbers, on my instance the rhel7 sync took 1 hour 5 min. on @abalakh instance it took 15-16 min. 
Think the values does not matter, and are here to prevent hanging commands. 
If a test is an SLA one, it have to supply the needed timeout values.

**Comment by abalakh** [comment]
@oshtaier for RHEL repo - yep, unfortunately that's possible. I'm not sure whether it's worth it to introduce 1h timeout for all the syncs, maybe it's better to pass desired timeout for large repos only

**Comment by ldjebran** [comment]
The timeout was set by observation to make that tests working, I really do not want a tests to fail because it rest 2 seconds to resume the command.

**Pull request merged**
