### PR TITLE
Automated Tests regarding user roles

### LINKED ISSUE #3733: Automate CLI test_user.py stubs regarding roles

### PR DESCRIPTION
**Pull request by renzon**
close #3733

Missing only default roles which need more info
Refactored test which depends on only one user to
UserTestWithCleaningUp so user got deleted on tearDown
 Refactored also Roles so they are created and destroyed
 on once for all tests

### CODE REVIEW

**Comment by renzon** [comment]
Test Results:

```console
/home/renzo/PycharmProjects/venvs/robottelo/bin/python /home/renzo/bin/pycharm-2016.2/helpers/pycharm/pytestrunner.py -p pytest_teamcity /home/renzo/PycharmProjects/robottelo/tests/foreman/cli/test_user.py
Testing started at 3:20 PM ...
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/renzo/PycharmProjects/robottelo, inifile: 
plugins: cov-2.3.0, xdist-1.14
collected 49 items

=================== 43 passed, 6 skipped in 1487.40 seconds ====================

Process finished with exit code 0
```

**Comment by sghai** [comment]
ACK..

**Comment by jyejare** [comment]
@renzon : Please post the local test results for all these tests.

**Comment by renzon** [comment]
@jyejare in fact the results were already posted: https://github.com/SatelliteQE/robottelo/pull/3738#issuecomment-241826515

**Comment by rochacbruno** [comment]
ACK

**Pull request merged**
