### PR TITLE
vm.py - goferd start now optional in install_katello_agent

### PR DESCRIPTION
**Pull request by rplevka**
This should cover the `goferless` clients as well as maintain a backwards compatibility

```
In [78]: my_vm.install_katello_agent()
2017-06-27 16:59:41 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f151acd2090
2017-06-27 16:59:41 - robottelo.ssh - INFO - Connected to [10.8.29.245]
2017-06-27 16:59:41 - robottelo.ssh - INFO - >>> yum install -y katello-agent
2017-06-27 17:00:13 - robottelo.ssh - INFO - <<< stdout
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-
              : manager
Resolving Dependencies
[...]
Dependencies Resolved
[...]
Downloading packages:
[...]
Installed:
  katello-agent.noarch 0:3.0.0-2.el7sat                                         
[...]
2017-06-27 17:00:13 - robottelo.ssh - INFO - <<< stderr
Warning: RPMDB altered outside of yum.

2017-06-27 17:00:13 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f151acd2090
2017-06-27 17:00:14 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f151acf6290
2017-06-27 17:00:14 - robottelo.ssh - INFO - Connected to [10.8.29.245]
2017-06-27 17:00:14 - robottelo.ssh - INFO - >>> rpm -q katello-agent
2017-06-27 17:00:14 - robottelo.ssh - INFO - <<< stdout
katello-agent-3.0.0-2.el7sat.noarch

2017-06-27 17:00:14 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f151acf6290
2017-06-27 17:00:15 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f151ad1c0d0
2017-06-27 17:00:15 - robottelo.ssh - INFO - Connected to [10.8.29.245]
2017-06-27 17:00:15 - robottelo.ssh - INFO - >>> service goferd start
2017-06-27 17:00:16 - robottelo.ssh - INFO - <<< stderr
Redirecting to /bin/systemctl start  goferd.service

2017-06-27 17:00:16 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f151ad1c0d0
2017-06-27 17:00:17 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f1521f45b50
2017-06-27 17:00:17 - robottelo.ssh - INFO - Connected to [10.8.29.245]
2017-06-27 17:00:17 - robottelo.ssh - INFO - >>> service goferd status
2017-06-27 17:00:17 - robottelo.ssh - INFO - <<< stdout
● goferd.service - Gofer Agent
   Loaded: loaded (/usr/lib/systemd/system/goferd.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-06-27 11:00:16 EDT; 1s ago
 Main PID: 10636 (python)
   CGroup: /system.slice/goferd.service
           └─10636 python /usr/bin/goferd --foreground

Jun 27 11:00:16 139728619934800.foo.bar.com goferd[10636]: [INFO][MainThread] gofer.agent.plugin:682 - plugin:katelloplugin loaded using: /usr/lib/gofer/plugins/katelloplugin.py
Jun 27 11:00:16 139728619934800.foo.bar.com goferd[10636]: [INFO][MainThread] rhsm.connection:830 - Connection built: host=hp-dl80gen9-01.foo.bar.com port=443 handler=/rhsm auth=identity_cert ca_dir=/etc/rhsm/ca/ verify=False
Jun 27 11:00:17 139728619934800.foo.bar.com goferd[10636]: [INFO][MainThread] katelloplugin:164 - Using /etc/rhsm/ca/katello-default-ca.pem as the ca cert for qpid connection
Jun 27 11:00:17 139728619934800.foo.bar.com goferd[10636]: [INFO][worker-0] gofer.messaging.adapter.connect:28 - connecting: proton+amqps://hp-dl80gen9-01.foo.bar.com:5647
Jun 27 11:00:17 139728619934800.foo.bar.com goferd[10636]: [INFO][worker-0] gofer.messaging.adapter.proton.connection:87 - open: URL: amqps://hp-dl80gen9-01.foo.bar.com:5647|SSL: ca: /etc/rhsm/ca/katello-default-ca.pem|key: None|certificate: /etc/pki/consumer/bundle.pem|host-validation: None
Jun 27 11:00:17 139728619934800.foo.bar.com goferd[10636]: [INFO][MainThread] gofer.agent.main:87 - agent started.
Jun 27 11:00:17 139728619934800.foo.bar.com goferd[10636]: [INFO][worker-0] root:490 - connecting to hp-dl80gen9-01.foo.bar.com:5647...
Jun 27 11:00:17 139728619934800.foo.bar.com goferd[10636]: [INFO][worker-0] root:532 - Disconnected
Jun 27 11:00:17 139728619934800.foo.bar.com goferd[10636]: [ERROR][worker-0] gofer.messaging.adapter.connect:33 - connect: proton+amqps://hp-dl80gen9-01.foo.bar.com:5647, failed: Connection amqps://hp-dl80gen9-01.foo.bar.com:5647 disconnected
Jun 27 11:00:17 139728619934800.foo.bar.com goferd[10636]: [INFO][worker-0] gofer.messaging.adapter.connect:35 - retry in 10 seconds

2017-06-27 17:00:17 - robottelo.ssh - INFO - <<< stderr
Redirecting to /bin/systemctl status  goferd.service

2017-06-27 17:00:17 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f1521f45b50
```

```
In [85]: my_vm.install_katello_agent(start_gofer=False)
2017-06-27 17:18:33 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f151abd8f90
2017-06-27 17:18:33 - robottelo.ssh - INFO - Connected to [10.8.29.245]
2017-06-27 17:18:33 - robottelo.ssh - INFO - >>> yum install -y katello-agent
2017-06-27 17:18:39 - robottelo.ssh - INFO - <<< stdout
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-
              : manager
Resolving Dependencies
[...]
Dependencies Resolved
[...]
Installed:
  katello-agent.noarch 0:3.0.0-2.el7sat                                         

Dependency Installed:
  gofer.noarch 0:2.7.7-2.el7sat                                                 

Complete!

2017-06-27 17:18:39 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f151abd8f90
2017-06-27 17:18:40 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f151ac7e5d0
2017-06-27 17:18:40 - robottelo.ssh - INFO - Connected to [10.8.29.245]

2017-06-27 17:18:40 - robottelo.ssh - INFO - >>> rpm -q katello-agent
2017-06-27 17:18:41 - robottelo.ssh - INFO - <<< stdout
katello-agent-3.0.0-2.el7sat.noarch

2017-06-27 17:18:41 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f151ac7e5d0

In [86]: my_vm.run('service goferd status')
2017-06-27 17:19:00 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f151abdc450
2017-06-27 17:19:00 - robottelo.ssh - INFO - Connected to [10.8.29.245]
2017-06-27 17:19:00 - robottelo.ssh - INFO - >>> service goferd status
2017-06-27 17:19:01 - robottelo.ssh - INFO - <<< stdout
● goferd.service - Gofer Agent
   Loaded: loaded (/usr/lib/systemd/system/goferd.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

2017-06-27 17:19:01 - robottelo.ssh - INFO - <<< stderr
Redirecting to /bin/systemctl status  goferd.service
[...]
```

### CODE REVIEW

**Comment by sghai** [comment]
ACK.. changes looks good to me w/ good chunk of assertions :)

**Comment by rplevka** [comment]
Fixed the flake error and rebased.
I'm not quite sure we still want this in, since it looks like the `goferless` mode is not going to happen soon.

**Comment by ldjebran** [comment]
I have closed the same PR https://github.com/SatelliteQE/robottelo/pull/4853 after many discussions in mail list

**Comment by abalakh** [comment]
@ldjebran the difference is at that point it was a defect which we didn't won't to work around, but now it's expected behavior.
@rplevka so what's the status, can we merge it or `goferless` won't be included in 6.3?

**Comment by rplevka** [comment]
@abalakh i believe this is already in 6.3

**Comment by ldjebran** [comment]
@abalakh it is not an expected behavior,  there is no goferless feature for 6.3 at the moment

**Comment by ldjebran** [comment]
@abalakh only if you have some information that I did not know

**Comment by abalakh** [comment]
>i believe this is already in 6.3

> there is no goferless feature for 6.3 at the moment

guys, i don't get you :)

**Comment by rplevka** [comment]
apologies,
the goferless clients are not meant to get katello-agent installed, but `katello-host-client-tools`. Thus, this change is not needed.

**Pull request closed without merging**
