### PR TITLE
Added new hammer options

### PR DESCRIPTION
**Pull request by ntkathole**
issue #5224 

Test Results:

```
pytest tests/foreman/cli/test_hammer.py::HammerCommandsTestCase::test_positive_all_options
========================================================== test session starts ==========================================================

collected 2 items


tests/foreman/cli/test_hammer.py .

====================================================== 1 passed in 2973.82 seconds ======================================================
```

### CODE REVIEW

**Comment by ldjebran** [comment]
as I know @svtkachenko is working on this looking that each option change is legitimate and has code behind it.

**Comment by ldjebran** [comment]
@ntkathole have you investigated on all options or simply generated the file?

**Comment by ntkathole** [comment]
@ldjebran I simply generated the file and found it works.

**Comment by ldjebran** [comment]
@ntkathole of course if you generate the file it will work :), but the problem is not here, 
The problem is are that changes valid or not

**Comment by ntkathole** [comment]
@ldjebran feel free to close the PR and  @svtkachenko can continue work on issue.

**Comment by ntkathole** [comment]
Closing this PR as  PR #5257  merged

**Pull request closed without merging**
