### PR TITLE
[6.11.z] Add Closed loop BZ#2148433 for Provisioning Templates

### PR DESCRIPTION
**Pull request by shubhamsg199**
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/10993
Closes: https://github.com/SatelliteQE/robottelo/issues/11031

### CODE REVIEW

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioningtemplate.py -k test_positive_provision_template_check_net_interface

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioningtemplate.py -k test_positive_provision_template_check_net_interface

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioningtemplate.py -k test_positive_provision_template_check_net_interface

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioningtemplate.py -k test_positive_provision_template_check_net_interface

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioningtemplate.py -k test_positive_provision_template_check_net_interface

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioningtemplate.py -k test_positive_provision_template_check_net_interface

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
