### PR TITLE
Restructuring rh_cloud test cases based on cert auth

### PR DESCRIPTION
**Pull request by adarshdubey-star**
`Removing token-based fixtures for rh_cloud_inventory/insights for test fixes`

### CODE REVIEW

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_rhcloud_inventory.py

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_rhcloud_insights.py

**Comment by adarshdubey-star** [comment]
2 test cases are failing with different errors not related to the changes done above rest are good!

**Review by jyejare — COMMENTED** [review]
ACK. Looks good, but I wonder how cert auth is being feeded for the RHCloud integration ?especially since you are removing the token based integration. Also the docstrings/test_steps of test cases are not updated to inform how cert auth based integration is being used here directly or indirectly.

Isnt it at all required.

**Comment by adarshdubey-star** [comment]
> ACK. Looks good, but I wonder how cert auth is being feeded for the RHCloud integration ?especially since you are removing the token based integration. Also the docstrings/test_steps of test cases are not updated to inform how cert auth based integration is being used here directly or indirectly.
> 
> Isnt it at all required.

The certificate-based authentication is directly related to the presence of certificates at the organizational level now.
The token-based architecture is completely eradicated, following that implementation I have removed the statement within the test cases which intends to have the `satellite api key `termed as a `token`. There is no explicit parameter to toggle.

`Adding upstream PR for more reference ` - https://github.com/theforeman/foreman_rh_cloud/commit/5838733800f9fa56adfeb47e00cf87932d165675

**Comment by adarshdubey-star** [comment]
> @adarshdubey-star Agree that you removed the `token` mention from docstrings but you are not updating the docstrings thats saying `presence of certificates at the organizational level`. That docstring mention is very important for newbies / external nonQE teams to understand how the test steps are using Authentication mechanism.

@jyejare I thought to keep it the same way, as there is no step going on in the test cases that can or will justify the presence of the authentication, as it's happening implicitly. Also about the understanding part, the same way it's going to remove from the documentation itself and that might create confusion with it.

**Review by jyejare — APPROVED** [review]

**Comment by jameerpathan111** [comment]
@adarshdubey-star I forgot about [rh_cloud.yaml.template](https://github.com/SatelliteQE/robottelo/blob/master/conf/rh_cloud.yaml.template) can you update that as well and also the one present in our ci repo.

**Pull request merged**
