### PR TITLE
Remove cpu_mode option from Libvirt provisioning tests

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
### Problem Statement
cpu_mode option is removed in SAT-22491 and upstream PR https://github.com/theforeman/foreman/pull/9963, causing Libvirt provisioning tests to fail

### Solution
Remove cpu_mode option from Libvirt provisioning tests

### Dependant PRs:
https://github.com/SatelliteQE/airgun/pull/1486

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/{cli,ui}/test_computeresource_libvirt.py -k test_positive_provision_end_to_end
airgun: 1486
provisioning: true
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8013
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/{cli,ui}/test_computeresource_libvirt.py -k test_positive_provision_end_to_end --external-logging --include-onprem-provisioning
Test Result : ========== 29 deselected, 66 warnings, 6 errors in 798.57s (0:13:18) ===========
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/{cli,ui}/test_computeresource_libvirt.py -k test_positive_provision_end_to_end
airgun: 1486
provisioning: true
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8052
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/{cli,ui}/test_computeresource_libvirt.py -k test_positive_provision_end_to_end --external-logging --include-onprem-provisioning
Test Result : ==== 2 failed, 4 passed, 29 deselected, 966 warnings in 10867.32s (3:01:07) ====
```

**Comment by Gauravtalreja1** [comment]
PRT is expected to fail here for EL9 host due to known issue with SAT-22491

**Review by shubhamsg199 — APPROVED** [review]

**Pull request merged**
