### PR TITLE
Remove puppet modules tests.

### PR DESCRIPTION
**Pull request by jaryn**

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
Can one of the admins verify this patch?

**Comment by mshriver** [comment]
@jaryn Thanks for cleaning up some of this content from robottelo - this removal is included with #8927, which @tstrych is using to do the final clean up and has some dependent PRs before we get it merged. 

Is this impacting a test that you're trying to fix @jaryn? @tstrych thoughts about this line being removed before #8927?

**Comment by tstrych** [comment]
We can merge this. 
I am definitely interested I could miss something.

**Review by omkarkhatavkar — APPROVED** [review]
ACK

**Pull request merged**
