### PR TITLE
[6.12.z] Convert2Rhel test fixes

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10840

Fixed Convert2RHEL test failures.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_convert2rhel.py -k test_convert2rhel_centos[centos7]

**Comment by Gauravtalreja1** [comment]
@shweta83 Could you check the failing PRT?

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_convert2rhel.py -k test_convert2rhel_centos[centos7]

**Review by Gauravtalreja1 — APPROVED** [review]
PRT failure looks unrelated atm, and looking at the changes it is solving the issue of checkout with s/vm.release/vm.deploy_rhel_version which works, so will merge this as is and PRT failures can be considered during TFA by @shweta83

**Pull request merged**
