### PR TITLE
[6.13.z] - removing the import entities from nailgun and moving target_sat

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
### Problem Statement
Needs to be a cherrypick of https://github.com/SatelliteQE/robottelo/pull/12989 to 6.13.z

### Solution
This PR helps to do the cherrypick https://github.com/SatelliteQE/robottelo/pull/12989

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pod_resource_size: large

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pod_resource_size: large

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pod_resource_size: extra_large

**Review by pondrejk — APPROVED** [review]

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
