### PR TITLE
fix settings for virtual_display evaluation

### LINKED ISSUE #2904: fix new settings module - virtual_display evaluation
robottelo.properties:
```
[robottelo]
virtual_display=false
# window_manager_command=
```
nosetests:
```
ImproperlyConfigured: Failed to validate the configuration, check the message(s):
[robottelo] virtual_display is enabled, window_manager_command must be provided.
```

### PR DESCRIPTION
**Pull request by lpramuk**
Fixes #2904

### CODE REVIEW

**Comment by elyezer** [comment]
The correct fix for the issue is:

```diff
diff --git a/robottelo/config/settings.py b/robottelo/config/settings.py
index 3fd313c..297b489 100644
--- a/robottelo/config/settings.py
+++ b/robottelo/config/settings.py
@@ -534,7 +534,7 @@ class Settings(object):
             INIReader.cast_logging_level
         )
         self.virtual_display = self.reader.get(
-            'robottelo', 'virtual_display', False)
+            'robottelo', 'virtual_display', False, bool)
         self.webdriver = self.reader.get(
             'robottelo', 'webdriver', 'firefox')
         self.window_manager_command = self.reader.get(
```

**Comment by elyezer** [comment]
missed casting the value

**Comment by elyezer** [comment]
I have found another issue, can you please incorporate it too?

```diff
diff --git a/robottelo/config/settings.py b/robottelo/config/settings.py
index 3fd313c..608c75e 100644
--- a/robottelo/config/settings.py
+++ b/robottelo/config/settings.py
@@ -530,11 +530,11 @@ class Settings(object):
         self.verbosity = self.reader.get(
             'robottelo',
             'verbosity',
-            'debug',
+            INIReader.cast_logging_level('debug'),
             INIReader.cast_logging_level
         )
         self.virtual_display = self.reader.get(
-            'robottelo', 'virtual_display', False)
+            'robottelo', 'virtual_display', False, bool)
         self.webdriver = self.reader.get(
             'robottelo', 'webdriver', 'firefox')
         self.window_manager_command = self.reader.get(
```

**Comment by lpramuk** [comment]
Ok. I'm going to add your comments into PR

**Comment by elyezer** [comment]
ACK

**Comment by rplevka** [comment]
ACK

**Pull request merged**
