### PR TITLE
Parametrize Satellite and Capsule deployments

### PR DESCRIPTION
**Pull request by ogajduse**
### Problem Statement
Some of our deployments have hardcoded deploy arguments. These should come from the config.

### Solution
Take the deployment arguments from the config.

### CODE REVIEW

**Review by lpramuk — APPROVED** [review]

**Comment by ogajduse** [comment]
trigger: test-robottelo

**Review by JacobCallahan — APPROVED** [review]
ACK on contents, but can you look into the PRT failure?

**Comment by ogajduse** [comment]
PRT got OOM killed. I will retrigger and try to feed the pod with more RAM.

**Comment by ogajduse** [comment]
trigger: test-robottelo
pod_resources_size: extra_extra_large

**Pull request merged**
