### PR TITLE
[6.15.z][Cherrypick] Merge and refactor leapp tests

### PR DESCRIPTION
**Pull request by shweta83**
### Problem Statement
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/15571 on 6.15.z

### Solution
Resolves: https://github.com/SatelliteQE/robottelo/issues/16365

### CODE REVIEW

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8666
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel --external-logging
Test Result : ================== 32 warnings, 2 errors in 717.75s (0:11:57) ==================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8668
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel --external-logging
Test Result : ================= 2 failed, 165 warnings in 3090.99s (0:51:30) =================
```

**Comment by Gauravtalreja1** [comment]
@shweta83 Could you incorporate this change in this PR https://github.com/SatelliteQE/robottelo/pull/16433 ?

**Comment by shweta83** [comment]
> @shweta83 Could you incorporate this change in this PR #16433 ?
@Gauravtalreja1 Added the changes.

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py -k test_positive_leapp_upgrade_rhel

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8796
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_positive_leapp_upgrade_rhel --external-logging
Test Result : ================= 2 failed, 162 warnings in 3058.11s (0:50:58) =================
```

**Comment by Gauravtalreja1** [comment]
@shweta83 Could you update this PR?

**Pull request closed without merging**
