### PR TITLE
[6.3] fix ui test_remoteexecution

### PR DESCRIPTION
**Pull request by ldjebran**
original error:
```console
>       raise exception_class(message, screen, stacktrace)
E       WebDriverException: Message: Editor is not defined
```
it seems the Editor var for ace editor  no longer used and all ace editor tests failed with the above error.
```console
(sat-6.3) dl@DL:~/projects/redhat/robottelo$ pytest -v tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase

================================================= test session starts ==================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.34, pluggy-0.4.0 -- /home/dl/.pyenv/versions/2.7.13/envs/sat-6.3/bin/python2.7
cachedir: .cache
rootdir: /home/dl/projects/redhat/robottelo, inifile:
plugins: xdist-1.16.0, services-1.2.1, mock-1.6.0, cov-2.3.1
collected 10 items 
2017-06-14 13:59:26 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings


tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_negative_create_job_template PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_negative_create_job_template_with_same_name PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_negative_preview_verify PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_clone_job_template PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_create_job_template_input PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_create_simple_job_template PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_delete_job_template PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_preview_verify PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_template_upload PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_view_diff PASSED

============================================= 10 passed in 591.11 seconds ==============================================
```

### CODE REVIEW

**Comment by ldjebran** [comment]
```console
(sat-6.3) dl@DL:~/projects/redhat/robottelo$ pytest -v tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.34, pluggy-0.4.0 -- /home/dl/.pyenv/versions/2.7.13/envs/sat-6.3/bin/python2.7
cachedir: .cache
rootdir: /home/dl/projects/redhat/robottelo, inifile:
plugins: xdist-1.16.0, services-1.2.1, mock-1.6.0, cov-2.3.1
collected 10 items 
2017-06-14 14:47:39 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings


tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_negative_create_job_template PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_negative_create_job_template_with_same_name PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_negative_preview_verify PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_clone_job_template PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_create_job_template_input PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_create_simple_job_template PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_delete_job_template PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_preview_verify PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_template_upload PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_view_diff PASSED

============================================= 10 passed in 602.88 seconds ==============================================

```

**Comment by oshtaier** [comment]
Is it expected that var removed from page javascript?

**Comment by ldjebran** [comment]
@oshtaier I have not this information, perhaps it was renamed to some thing other, and we have to debug to find it, I made some research to find it but in vain.  
and why we do have to expect any var existence (is that var existence a requirement, or it was agreed with QE)?

**Comment by abalakh** [comment]
@oshtaier any objections against merging it? I don't think it worth bothering devs just to confirm javascript var rename/removal especially when we have more flexible approach to handle that.

**Comment by oshtaier** [comment]
So you propose to make our code more complex instead? Yes, please bother yourself with one line email or  run search in foreman/katello PRs github

**Comment by ldjebran** [comment]
put this to do not merge for the moment

**Comment by oshtaier** [comment]
That solution is not more flexible as new locator can be also removed or modified

**Comment by ldjebran** [comment]
closing PR as other solution needed

**Comment by ldjebran** [comment]
opened an issue instead 
https://github.com/SatelliteQE/robottelo/issues/4844

**Comment by ldjebran** [comment]
reopen PR as cannot find a more simpler approach, and as we need this tests to stop failing

**Comment by oshtaier** [comment]
ACK pending test results for job_templates and provisioning_templates tests for latest 6.3 application version

**Comment by ldjebran** [comment]
```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ pytest -v tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.0, cov-2.4.0
collected 10 items 
2017-06-20 11:01:20 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings


tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_negative_create_job_template PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_negative_create_job_template_with_same_name PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_negative_preview_verify PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_clone_job_template PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_create_job_template_input PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_create_simple_job_template PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_delete_job_template PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_preview_verify PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_template_upload PASSED
tests/foreman/ui/test_remoteexecution.py::JobsTemplateTestCase::test_positive_view_diff PASSED

============================================= 10 passed in 661.62 seconds ==============================================
```

```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ pytest -v tests/foreman/ui/test_template.py
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.0, cov-2.4.0
collected 13 items 
2017-06-20 11:15:20 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings


tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_with_invalid_name <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_with_same_name <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_with_too_long_audit <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_without_type <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_without_upload <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_advanced_search <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_clone <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_create_with_name <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_create_with_snippet_type <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_delete <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_update_name_and_type <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_update_os <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_update_with_manager_role PASSED

============================================= 13 passed in 790.35 seconds ==============================================
```

**Pull request merged**
