### PR TITLE
[6.16.z] Add tests for multiCV assignment with Hammer

### PR DESCRIPTION
**Pull request by vsedmik**
Manual cherry-pick of @jeremylenz's #15880 

We got that merged after branching so we need to CP it back to 6.16.z.

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_host.py -k 'test_positive_multi_cv_assignment'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8551
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_host.py -k test_positive_multi_cv_assignment --external-logging
Test Result : ==== 2 failed, 94 deselected, 162 warnings, 2 errors in 1363.14s (0:22:43) =====
```

**Comment by vsedmik** [comment]
PRT failures are related to the container state improper issue, unrelated to this PR.

**Review by jeremylenz — APPROVED** [review]

**Comment by vsedmik** [comment]
rebased

**Pull request merged**
