### PR TITLE
Remove XenServer from virt-who config plugin

### PR DESCRIPTION
**Pull request by hkx303**
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1719661 has been fixed, since XenServer is not one of the supported hypervisors as per the Virtual Instances Guide. Ideally in the downstream, we should remove this from the drop down menu list under Satellite Web UI -> Infrastructure -> Virt-who configs -> New Virt-who Config -> Hypervisor Type drop down menu. And not support by hammer cli and API, need to remove XenServer test from virt-who config plugin.

### CODE REVIEW

**Comment by mshriver** [comment]
Thanks for the update @hkx303, going to hold merging of this until we branch for 6.10

**Review by JacobCallahan — CHANGES_REQUESTED** [review]
The new virtwho.yaml.template introduced in #8662 will need to be updated as part of this pr post-branch as well.

**Comment by hkx303** [comment]
> The new virtwho.yaml.template introduced in #8662 will need to be updated as part of this pr post-branch as well.

Thank you & Done!

**Comment by JacobCallahan** [comment]
it looks like you merged instead of rebased to upstream/master, adding more changes to this PR than you intended.

**Review by JacobCallahan — APPROVED** [review]
Nice!

**Comment by mshriver** [comment]
@hkx303 merge commits are not allowed in the repo, please remove the merge commit and instead rebase your commits onto the latest `master` branch commit. If you'd like some git guidance don't hesitate to reach out!

**Comment by hkx303** [comment]
> @hkx303 merge commits are not allowed in the repo, please remove the merge commit and instead rebase your commits onto the latest `master` branch commit. If you'd like some git guidance don't hesitate to reach out!

Sorry, remove the merge master commit and instead rebase the master branch :)

**Review by mshriver — APPROVED** [review]

**Comment by mshriver** [comment]
@hkx303 no need to apologize! Thanks for cleaning up the commits :)

**Pull request merged**
