### PR TITLE
[6.15.z] Enabling Robottelo for IPv6 Testing (#14160)

### PR DESCRIPTION
**Pull request by jyejare**
### Problem Statement
* Enabling Robottelo for IPv6 Testing

Failed Automatic cherry-pick of https://github.com/SatelliteQE/robottelo/pull/14160 

### Solution
Manual cherrypick of PR after conflicts were resolved.

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
Why selecting all labels when its just failed cherrypick for 6.15.z?

**Comment by jyejare** [comment]
@Gauravtalreja1 Even I dont think that the Ipv6 testing will go beyond 6.15

**Comment by jyejare** [comment]
trigger: test-robottelo
pytest: tests/foreman -m build_sanity

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7393
Build Status: SUCCESS
PRT Comment: pytest tests/foreman -m build_sanity --external-logging
Test Result : ======= 11 passed, 5448 deselected, 5552 warnings in 1566.82s (0:26:06) ========
```

**Pull request merged**
