### PR TITLE
Deploy katello-remove sideways as it's no longer part of product

### PR DESCRIPTION
**Pull request by lpramuk**
Requires: 
- MR !308

Fixes:
- tests/foreman/cli/test_capsule_installer.py::CapsuleInstallerTestCase::test_positive_reinstall_on_same_node_after_remove

### CODE REVIEW

**Comment by lhellebr** [comment]
While grammatically, "artefact" means the same as "artifact", in this context only "artifact" is used and "artefact" looks rather weird.

**Comment by lhellebr** [comment]
This adds dependency on another server and a new setting. Would it make sense to make it optional (in that case, the test would be skipped or gracefully fail if server is not specified)?

**Comment by mirekdlugosz** [comment]
I agree with @lhellebr , skip the test if setting is not specified. Especially since this new setting is not mandatory (which is right call!). I don't believe in failed tests in case where optional value was not provided.

**Comment by lhellebr** [comment]
LGTM after fix, I'll ACK once you provide the test results.

**Comment by lpramuk** [comment]
`
(r) [lpramuk@X1C6:fix_missing_katello-remove:~]$ pytest tests/foreman/cli/test_capsule_installer.py::CapsuleInstallerTestCase::test_positive_reinstall_on_same_node_after_remove
================================================= test session starts ==================================================
platform linux -- Python 3.7.6, pytest-4.6.3, py-1.8.0, pluggy-0.13.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/lpramuk/git/SatelliteQE/robottelo, inifile: pytest.ini
plugins: mock-1.10.4, services-1.3.1
collecting ... 2020-02-11 13:05:47 - conftest - DEBUG - Collected 1 test cases
2020-02-11 14:05:47 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f7832cc3a10
2020-02-11 14:05:47 - robottelo.ssh - INFO - Connected to [smqa-r210-06.lab.eng.brq.redhat.com]
2020-02-11 14:05:47 - robottelo.ssh - INFO - >>> rpm -q satellite
2020-02-11 14:05:48 - robottelo.ssh - INFO - <<< stdout
satellite-6.7.0-5.beta.el7sat.noarch

2020-02-11 14:05:48 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f7832cc3a10
2020-02-11 14:05:48 - robottelo.host_info - DEBUG - Host Satellite version: 6.7
2020-02-11 14:05:48 - robottelo.helpers - DEBUG - Generated file bz_cache.json with BZ collect data
collected 1 item                                                                                                       

tests/foreman/cli/test_capsule_installer.py .                                                                    [100%]

============================================= 1 passed in 1677.46 seconds ==============================================
`

**Comment by lpramuk** [comment]
Rafactor inludes:
- rename ```s/artefact/artifact/```
- conditional test skip 
Provided test result (see above)

**Pull request merged**
