### PR TITLE
[6.15.z] non-admin user acess with usergroup

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15489

### Problem Statement
With user which is non-admin but it is in usergroup which should give him administrator role is possible to access lot of pages, but giving Permission denied

### Solution
It verifies if a non-admin user in the user group can access the WebUI.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_non_admin_user_access_with_usergroup
airgun: 1461

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7750
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_non_admin_user_access_with_usergroup --external-logging
Test Result : ====== 1 passed, 16 deselected, 27 warnings, 1 error in 735.05s (0:12:15) ======
```

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_non_admin_user_access_with_usergroup
airgun: 1453

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7756
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_non_admin_user_access_with_usergroup --external-logging
Test Result : ========== 1 failed, 16 deselected, 26 warnings in 657.39s (0:10:57) ===========
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_non_admin_user_access_with_usergroup

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7762
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_non_admin_user_access_with_usergroup --external-logging
Test Result : ====== 1 passed, 16 deselected, 27 warnings, 1 error in 750.55s (0:12:30) ======
```

**Comment by amolpati30** [comment]
"trigger": "test-robottelo"
"pytest": "-k 'test_positive_non_admin_user_access_with_usergroup' tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt"

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7772
Build Status: SUCCESS
PRT Comment: pytest /opt/app-root/src/robottelo/tests/foreman -v -m build_sanity --external-logging
Test Result : ======= 11 passed, 5460 deselected, 5572 warnings in 1937.46s (0:32:17) ========
```

**Pull request merged**
