### PR TITLE
Fixes for test failures

### PR DESCRIPTION
**Pull request by shweta83**
Test Failure fixes: 
1. ui.test_settings.py:test_positive_update_email_delivery_method_sendmail
2. api.test_location.py --> Removed Environment while creating entity

### CODE REVIEW

**Comment by akhil-jha** [comment]
I know the PR is in draft so that's why I am asking.....did the fix you made worked for rhel8 locally? Because sendmail doesn't come in rhel8 by default now. So even if you get a `"Email was sent successfully"` on UI, I don't expect it to see in /var/mail/root. You'd have to configure sendmail. Right? 
**Please correct me if I am wrong.**

**Comment by jyejare** [comment]
@shweta83 Is this suppose to be in draft state ?

**Comment by shweta83** [comment]
> @shweta83 Is this suppose to be in draft state ?

This was in draft state because of rhel8 sendmail issue but this test should be skipped now until the BZ is fixed. I updated the PR.

**Review by latran — COMMENTED** [review]
I'd rather you put this back in draft and wait until the bz is fixed instead of putting the skip marker on the same bz that you're writing automation for.  It can be confusing.  And you can also add the `blocker` label until then as well.

One question though.  Is this fix also slated for 6.11?  I don't see a flag for it in the bz so the `cherrypick` label may not be applicable in this case.

**Comment by shweta83** [comment]
> I'd rather you put this back in draft and wait until the bz is fixed instead of putting the skip marker on the same bz that you're writing automation for. It can be confusing. And you can also add the `blocker` label until then as well.
> 
> One question though. Is this fix also slated for 6.11? I don't see a flag for it in the bz so the `cherrypick` label may not be applicable in this case.

@latran I started this PR with fixing the failure in 6.11 due to changes in UI but it had issue with RHEL8(which impacts 6.11 as well) so I added skip marker here.

**Comment by mshriver** [comment]
@latran @shweta83 I think its fine to add test cases skipped by BZs - it provides 'instant' validation of the BZ in the automation results when we get a snap containing the fix. The BZ should change states and stop blocking test case execution, and then @shweta83 can validate the bug based off of the test automation results.

This type of pattern is exactly what we need to get 'ahead' of dev in automation coverage, and push towards automated build sign-off.

**Comment by latran** [comment]
Alright, I understand now.

**Comment by mshriver** [comment]
@shweta83 above being said - why is the assert removed?  The assert is valid once the BZ is resolved, so it shouldn't be removed.

**Comment by shweta83** [comment]
> @shweta83 above being said - why is the assert removed? The assert is valid once the BZ is resolved, so it shouldn't be removed.

@mshriver You are right. It was done by mistake. I updated the PR

**Review by ogajduse — APPROVED** [review]

**Review by mshriver — APPROVED** [review]

**Pull request merged**
