### PR TITLE
[6.3] FIX UI contentview template partition_table

### PR DESCRIPTION
**Pull request by ldjebran**
The changes introduled here are the following
*  Many tests suffer from errors like:  TimeoutException: Message: "Timeout waiting for page to load", and "StaleElementReferenceException: Message: Element is no longer attached to the DOM" 

     increase the timeout for wait_for_ajax, 
    This allowed the tests to pass three time without these failures, 
    The template and partitiontable tests where run in multi thread 
    We are waiting for ajax on every step , this should be changed, and wait for ajax only when needed, wait for ajax between finding an element and clicking is not a good idea
        The scenario should be find an element click on it and then wait for ajax 

* for some functions that contain wait_for_ajax in kwargs, will wait for ajax only once and when requested to do so using the wkargs
* Tests that use two or more sessions where using the session object of the already closed session object
* Some content view tests where creating the repositories just after opening the session that randomly leaded to errors like: StaleElementReferenceException
* The success message was removed when adding a repo as it's shown for a very short time, and randomly the tests failed (and any way we asserting that the repo is in the list of available repos)

```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test tests/foreman/ui/test_contentview.py::ContentViewTestCase -v -k "test_positive_add_puppet_module or test_positive_add_package_filter or test_positive_add_package_inclusion_filter_and_publish or test_positive_add_package_exclusion_filter_and_publish or test_positive_remove_package_from_exclusion_filter or test_positive_update_inclusive_filter_package_version or test_positive_update_exclusive_filter_package_version or test_positive_update_filter_affected_repos or test_positive_edit_rh_custom_spin or test_positive_create_composite or test_positive_add_rh_custom_spin or test_positive_add_custom_content or test_positive_publish_with_rh_content or test_positive_clone_within_same_env or test_positive_clone_within_diff_env or test_positive_admin_user_actions or test_positive_readonly_user_actions or test_positive_remove_cv_version_from_default_env or test_positive_remove_renamed_cv_version_from_default_env"
=============================================================== test session starts ===============================================================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.20.0, services-1.2.1, mock-1.6.2, forked-0.2, cov-2.5.1
collected 93 items 
2017-08-31 15:49:19 - conftest - DEBUG - Found WONTFIX in decorated tests ['1156555', '1269196', '1378009', '1245334', '1217635', '1226425', '1147100', '1311113', '1199150', '1204686', '1221971', '1103157', '1230902', '1230865', '1214312', '1079482']

2017-08-31 15:49:19 - conftest - DEBUG - Collected 93 test cases


tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_add_custom_content <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_add_package_exclusion_filter_and_publish <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_add_package_filter <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_add_package_inclusion_filter_and_publish <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_add_puppet_module <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_add_rh_custom_spin <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_admin_user_actions <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_clone_within_diff_env <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_clone_within_same_env <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_create_composite <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_edit_rh_custom_spin <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_publish_with_rh_content <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_readonly_user_actions <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_remove_cv_version_from_default_env <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_remove_package_from_exclusion_filter <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_remove_renamed_cv_version_from_default_env <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_update_exclusive_filter_package_version <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_update_filter_affected_repos <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_update_inclusive_filter_package_version <- robottelo/decorators/__init__.py PASSED

========================================================================= 74 tests deselected ==========================================================================
============================================================= 19 passed, 74 deselected in 11409.66 seconds =============================================================

```

```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test -v -n 4 tests/foreman/ui/test_template.py tests/foreman/ui/test_partitiontable.py
==================================================================== test session starts =====================================================================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.20.0, services-1.2.1, mock-1.6.2, forked-0.2, cov-2.5.1
[gw0] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw1] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw2] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw3] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw0] Python 2.7.13 (default, Feb  1 2017, 15:29:46)  -- [GCC 4.8.4]
[gw2] Python 2.7.13 (default, Feb  1 2017, 15:29:46)  -- [GCC 4.8.4]
[gw3] Python 2.7.13 (default, Feb  1 2017, 15:29:46)  -- [GCC 4.8.4]
[gw1] Python 2.7.13 (default, Feb  1 2017, 15:29:46)  -- [GCC 4.8.4]
gw0 [33] / gw1 [33] / gw2 [33] / gw3 [33]
scheduling tests via LoadScheduling

tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_with_same_name <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_without_type <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_with_too_long_audit <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_with_invalid_name <- robottelo/decorators/__init__.py 
[gw2] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_without_type <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_create_with_name <- robottelo/decorators/__init__.py 
[gw0] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_with_too_long_audit <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_clone <- robottelo/decorators/__init__.py 
[gw3] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_with_same_name <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_advanced_search <- robottelo/decorators/__init__.py 
[gw0] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_clone <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_display_cloned_help <- robottelo/decorators/__init__.py 
[gw0] SKIPPED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_display_cloned_help <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_export_cloned_and_edited <- robottelo/decorators/__init__.py 
[gw0] SKIPPED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_export_cloned_and_edited <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_export_locked <- robottelo/decorators/__init__.py 
[gw0] SKIPPED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_export_locked <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_export_template_disable_safe_render <- robottelo/decorators/__init__.py 
[gw0] SKIPPED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_export_template_disable_safe_render <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_export_unlocked <- robottelo/decorators/__init__.py 
[gw0] SKIPPED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_export_unlocked <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_update_name_and_type <- robottelo/decorators/__init__.py 
[gw3] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_advanced_search <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_display_help <- robottelo/decorators/__init__.py 
[gw3] SKIPPED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_display_help <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_update_with_manager_role 
[gw3] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_update_with_manager_role 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_negative_create_with_empty_layout <- robottelo/decorators/__init__.py 
[gw0] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_update_name_and_type <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_update_os <- robottelo/decorators/__init__.py 
[gw1] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_with_invalid_name <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_without_upload <- robottelo/decorators/__init__.py 
[gw1] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_negative_create_without_upload <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_negative_update_name <- robottelo/decorators/__init__.py 
[gw3] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_negative_create_with_empty_layout <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_negative_create_with_invalid_name <- robottelo/decorators/__init__.py 
[gw2] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_create_with_name <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_create_with_snippet_type <- robottelo/decorators/__init__.py 
[gw0] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_update_os <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_negative_create_with_same_name <- robottelo/decorators/__init__.py 
[gw0] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_negative_create_with_same_name <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_non_default_for_location <- robottelo/decorators/__init__.py 
[gw0] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_non_default_for_location <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_non_default_for_organization <- robottelo/decorators/__init__.py 
[gw2] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_create_with_snippet_type <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_delete <- robottelo/decorators/__init__.py 
[gw3] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_negative_create_with_invalid_name <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_default_for_organization <- robottelo/decorators/__init__.py 
[gw0] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_non_default_for_organization <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_with_audit_comment <- robottelo/decorators/__init__.py 
[gw3] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_default_for_organization <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_with_one_character_name <- robottelo/decorators/__init__.py 
[gw1] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_negative_update_name <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_default_for_location <- robottelo/decorators/__init__.py 
[gw1] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_default_for_location <- robottelo/decorators/__init__.py 
[gw0] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_with_audit_comment <- robottelo/decorators/__init__.py 
[gw2] PASSED tests/foreman/ui/test_template.py::TemplateTestCase::test_positive_delete <- robottelo/decorators/__init__.py 
[gw3] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_with_one_character_name <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_delete <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_update <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_with_snippet <- robottelo/decorators/__init__.py 
tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_with_name <- robottelo/decorators/__init__.py 
[gw0] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_with_snippet <- robottelo/decorators/__init__.py 
[gw2] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_create_with_name <- robottelo/decorators/__init__.py 
[gw1] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_update <- robottelo/decorators/__init__.py 
[gw3] PASSED tests/foreman/ui/test_partitiontable.py::PartitionTableTestCase::test_positive_delete <- robottelo/decorators/__init__.py 

========================================================== 27 passed, 6 skipped in 3007.15 seconds ===========================================================
```
Please note that the two pytest run was running always at the same time

### CODE REVIEW

**Comment by ldjebran** [comment]
@oshtaier many thnaks for your review

1- timeout: I was not informed (any where in the code ) that 30 second timeout is a SLA
any way to prepare a bug like that one, I will need a week to test/debug/analyse/document, 
and have to argue that the usability of the application is affected what is not evident, and that work will go to the trash. 

**Please take into consideration that foreman is an AJAX application any call to the server may lead to DOM changes**

2- StaleElementException: I had never said that this error is due to timeout, but I explained above that this is about the creation of repository just after the opening of the session. and that is due to the fact of wait of ajax between finding the element and apply it's actions


3- I had no intention to remove the wait for ajax between actions, and that was not done, I have simply removed the wait for ajax between finding the element and applying the element action.

This is a list of function in base that was affected by this PR and steps performed:
______________________________________________________________________________
| Actions Now | Actions proposed in this PR
|----   |-----|
|**Click** |
| get element (with selenium waiter) | get element (with selenium waiter) |
| wait for ajax | click|
| click | wait for ajax|
|wait for ajax| 
|**Assign value: Input scenario**|
| get element (with selenium waiter) | get element (with selenium waiter) |
| get type| get type
| wait for ajax | get element (with selenium waiter)|
|get element (with selenium waiter)|wait for ajax
| wait for ajax | 
| set value | 
|wait for ajax| 
| **Assign value: Select scenario** |
| get element (with selenium waiter) | get element (with selenium waiter) |
| get type| get type
| wait for ajax | get element (with selenium waiter) 
|get element (with selenium waiter) | select|
| wait for ajax | wait for ajax | 
|select |
| wait for ajax | 

Every action at it's end is doing a wait for ajax
Taking for example the click function, finding the element and click function must be atomic we have not to wait the ajax (that can change the DOM) between finding the element and clicking on it. 

If we have to do an extra wait for ajax to refresh the state of the element we have to do it before finding the element (but that is mostly done by the ulterior action), any way this extra call before getting the element will not break the functionality (and we have to do it in click function it self, to have more control over that).
eg:
|**Click** |
| wait for ajax |
| get element (with selenium waiter) |
| click | 
|wait for ajax|

**Comment by oshtaier** [comment]
Thanks for the details

If you have StaleElementException for ` this is about the creation of repository just after the opening of the session. and that is due to the fact of wait of ajax between finding the element and apply it's actions`
Wait for ajax cannot produce exception as it doesn't have interactions with elements, but if next action produced it, that is very good output as that means that page was not loaded which means that we have bad test design. I agree that probably we have to change ordering and call wait for ajax before waiter for element, not after, but it has to be there. Of course, we have to have wait for ajax after action executed, but also before waiter as I wrote above. Anyway, we cannot change the whole architecture paradigm, just because you have failures for 10-30 test cases, but if you want to do that, so you need to make 2-3 rounds of full WebUI retest for both local/docker containers and saucelabs and for multi threading.

**Comment by ldjebran** [comment]
removed the content view tests from this PR to not be blocked as the changes made have to be merged as soon as possible

**Comment by oshtaier** [comment]
Probably, you removed wrong part. I am fine the changes to all other files, not to the base class

**Comment by ldjebran** [comment]
@oshtaier will create a new PR for that changes, and let this base changes in this PR. as we need more time for testing.

**Comment by ldjebran** [comment]
All the changes has been done, going to look for more testing , put do not merge

**Comment by ldjebran** [comment]
Close this PR as need many testing to be done, it does not worth , will submit this idea in an other PR with full review of all the base functions

**Pull request closed without merging**
