### PR TITLE
CLI Import test added - test_merge_orgs

### PR DESCRIPTION
**Pull request by rplevka**
Added a test to excercise `--into-org-id` option of `hammer import organization`
To verify mapping is being performed correctly, the test attempts to import some users originally belonging to different organizations in `Satellite 5` and verifying they all appear under a single organization in `Satellite 6`

```bash
$ nosetests -m test_merge_orgs test_import.py
.
----------------------------------------------------------------------
Ran 1 test in 43.342s

OK
```

### CODE REVIEW

**Comment by Ichimonji10** [comment]
This can be made more concise:

```diff
diff --git a/tests/foreman/cli/test_import.py b/tests/foreman/cli/test_import.py
index a4ae0d6..43d2f5c 100644
--- a/tests/foreman/cli/test_import.py
+++ b/tests/foreman/cli/test_import.py
@@ -265,31 +265,23 @@ class TestImport(CLITestCase):
         )
         ssh.upload_file(new_dataset, new_dataset)
         files['users'] = new_dataset
-
-        ssh_map = Import.organization(
-            {
-                'csv-file': files['users'],
-                'into-org-id': new_org['id'],
-                'verbose': True
-            }
-        )
-        self.assertIn(
-            u'Mapped 3 organizations.',
-            ''.join(ssh_map.stdout)
-        )
-        Import.user({
+        ssh_map = Import.organization({
             'csv-file': files['users'],
-            'new-passwords': pwdfile
+            'into-org-id': new_org['id'],
+            'verbose': True,
         })
-        # list users by org-id
+        self.assertIn(u'Mapped 3 organizations.', ''.join(ssh_map.stdout))
+        Import.user({'csv-file': files['users'], 'new-passwords': pwdfile})
+
+        # list users by org-id and check whether users from csv are in listing
         users = User().list({u'organization-id': new_org['id']})
-        # now check whether users from csv appeared in the listing
         logins = set(user['login'] for user in users.stdout)
         imp_users = set(
-            user['username'] for
-            user in csv_to_dataset(files['users'])
+            user['username']
+            for user in csv_to_dataset(files['users'])
         )
         self.assertTrue(all((user in logins for user in imp_users)))
+
         # do the cleanup
         os.remove(new_dataset)
         ssh.command(
```

**Comment by Ichimonji10** [comment]
ACK pending comment. FYI, you can apply the diff above with `git apply`.

**Comment by rplevka** [comment]
@Ichimonji10 :+1: 
very cool, this will definitely come handy in the future, thanks

**Comment by Ichimonji10** [comment]
Glad to hear it. :smile:

ACK

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
