### PR TITLE
[6.13.z] Add support to run VMware tests on VMware8

### PR DESCRIPTION
**Pull request by shubhamsg199**
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13877

### CODE REVIEW

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_vmware.py::test_positive_vmware_cr_end_to_end tests/foreman/ui/test_computeresource_vmware.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5754
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_computeresource_vmware.py::test_positive_vmware_cr_end_to_end tests/foreman/ui/test_computeresource_vmware.py
Test Result : =========== 2 failed, 14 passed, 153 warnings in 6342.52s (1:45:42) ============
```

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_vmware.py::test_positive_vmware_cr_end_to_end tests/foreman/ui/test_computeresource_vmware.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5759
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_computeresource_vmware.py::test_positive_vmware_cr_end_to_end tests/foreman/ui/test_computeresource_vmware.py
Test Result : ================ 14 passed, 102 warnings in 6189.76s (1:43:09) =================
```

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
