### PR TITLE
6.10.z cherry pick for updating repo auth

### PR DESCRIPTION
**Pull request by ColeHiggins2**
Cherry-pick https://github.com/SatelliteQE/robottelo/pull/9274/commits into 6.10.z

### CODE REVIEW

**Comment by Griffin-Sullivan** [comment]
Are the tests passing now or are there new issues?

**Review by Griffin-Sullivan — APPROVED** [review]
Looks good to me. If there are more errors that were caused by these changes in 6.10 or 7.0 I can help fix them.

**Comment by lhellebr** [comment]
LGTM, I don't see any obvious difference for a 6.10 cherrypick

**Review by lhellebr — APPROVED** [review]

**Comment by lhellebr** [comment]
Please check at least some tests results

**Comment by ColeHiggins2** [comment]
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-6.2.5, py-1.9.0, pluggy-0.13.1 -- /home/colehiggins/projects/robo38/bin/python3.8
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/colehiggins/projects/robottelo, configfile: pyproject.toml
plugins: reportportal-5.0.12, xdist-2.5.0, mock-3.7.0, forked-1.3.0, ibutsu-2.0.2, services-2.2.1
collecting ... collected 9 items

tests/foreman/api/test_repository.py::TestRepository::test_positive_synchronize_auth_yum_repo[0] 
tests/foreman/api/test_repository.py::TestRepository::test_positive_synchronize_auth_yum_repo[1] 
tests/foreman/api/test_repository.py::TestRepository::test_positive_synchronize_auth_yum_repo[2] 
tests/foreman/api/test_repository.py::TestRepository::test_positive_synchronize_auth_yum_repo[3] 
tests/foreman/api/test_repository.py::TestRepository::test_positive_synchronize_auth_yum_repo[4] 
tests/foreman/api/test_repository.py::TestRepository::test_positive_synchronize_auth_yum_repo[5] 
tests/foreman/api/test_repository.py::TestRepository::test_positive_synchronize_auth_yum_repo[6] 
tests/foreman/api/test_repository.py::TestRepository::test_positive_synchronize_auth_yum_repo[7] 
tests/foreman/api/test_repository.py::TestRepository::test_positive_synchronize_auth_yum_repo[8] 

=============================== warnings summary ===============================
tests/foreman/api/test_repository.py: 52 warnings
  /home/colehiggins/projects/robo38/lib64/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host. Adding certificate verification is strongly advised. 

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================== 9 passed, 52 warnings in 122.52s (0:02:02) ==================

**Review by mshriver — APPROVED** [review]

**Pull request merged**
