### PR TITLE
[6.15.z] Vertical menu search test

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13421

New module and test case for vertical menu search functionality.

TC: `test_positive_vertical_navigation_search_end_to_end`

Requires: https://github.com/SatelliteQE/airgun/pull/1076

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_search.py -k test_positive_vertical_navigation_search_end_to_end
airgun: 1233
env:
ROBOTTELO_ui__record_video: true

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5720
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_search.py -k test_positive_vertical_navigation_search_end_to_end
Test Result : ============= 1 failed, 1 passed, 32 warnings in 898.16s (0:14:58) =============
```

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_search.py -k test_positive_vertical_navigation_search_end_to_end
airgun: 1234
env:
ROBOTTELO_ui__record_video: true

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5762
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_search.py -k test_positive_vertical_navigation_search_end_to_end
Test Result : ============= 1 failed, 1 passed, 35 warnings in 917.62s (0:15:17) =============
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_search.py -k test_positive_vertical_navigation_search_end_to_end
airgun: 1234

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5771
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_search.py -k test_positive_vertical_navigation_search_end_to_end
Test Result : ============ 1 failed, 1 passed, 36 warnings in 1130.49s (0:18:50) =============
```

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_search.py -k test_positive_vertical_navigation_search_end_to_end
airgun: 1234

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5800
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_search.py -k test_positive_vertical_navigation_search_end_to_end
Test Result : ================= 2 passed, 33 warnings in 1142.71s (0:19:02) ==================
```

**Pull request merged**
