### PR TITLE
[6.14.z] non-admin user acess with usergroup

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15489

### Problem Statement
With user which is non-admin but it is in usergroup which should give him administrator role is possible to access lot of pages, but giving Permission denied

### Solution
It verifies if a non-admin user in the user group can access the WebUI.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_non_admin_user_access_with_usergroup
airgun: 1461

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7749
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_non_admin_user_access_with_usergroup --external-logging
Test Result : ====== 1 passed, 16 deselected, 27 warnings, 1 error in 712.96s (0:11:52) ======
```

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_non_admin_user_access_with_usergroup

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7755
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_non_admin_user_access_with_usergroup --external-logging
Test Result : ====== 1 passed, 16 deselected, 27 warnings, 1 error in 659.26s (0:10:59) ======
```

**Comment by amolpati30** [comment]
"trigger": "test-robottelo"
"pytest": "-k 'test_positive_non_admin_user_access_with_usergroup' tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt"

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7757
Build Status: SUCCESS
PRT Comment: pytest /opt/app-root/src/robottelo/tests/foreman -v -m build_sanity --external-logging
Test Result : ======= 11 passed, 5378 deselected, 5486 warnings in 1391.12s (0:23:11) ========
```

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
