### PR TITLE
katello host tools unittest2pytest

### PR DESCRIPTION
**Pull request by tstrych**
forgotten tests, 
More info is written in #8339.

### CODE REVIEW

**Comment by tstrych** [comment]
trigger: test-robottelo
pytest: -m katello_host_tools tests/foreman/cli/test_host.py

**Comment by tstrych** [comment]
Robottelo runner passed ;) 
also test passed locally 
`===== 3 passed, 1 skipped, 50 deselected, 6 warnings in 657.90s (0:10:57) ======`

Warning summary 
```
 InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised
 ```

**Review by pondrejk — APPROVED** [review]

**Comment by pondrejk** [comment]
@tstrych can you repush to retrigger the hung quality checks?

**Comment by tstrych** [comment]
thanks, sure :+1:

**Review by mshriver — APPROVED** [review]

**Pull request merged**
