### PR TITLE
Tests to upload SRPM - BZ#1378442

### PR DESCRIPTION
**Pull request by rplevka**
backporting https://github.com/SatelliteQE/robottelo/pull/3849

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK

**Comment by oshtaier** [comment]
pending test results. I know that is just cherry-pick, but anyway

**Comment by omaciel** [comment]
@rplevka waiting on test results to merge it please :)

**Comment by rplevka** [comment]
the test are going to be skipped

**Comment by omaciel** [comment]
OK, going to merge this as the test will be skipped until the BZ associated with it is fixed.

**Pull request merged**
