### PR TITLE
Fix CLI host tests according to 6.2

### PR DESCRIPTION
**Pull request by oshtaier**
```
nosetests tests/foreman/cli/test_host.py:HostUpdateTestCase
..................
----------------------------------------------------------------------
Ran 18 tests in 830.487s

OK
```

### CODE REVIEW

**Comment by abalakh** [comment]
Is that expected change? I mean, it's pretty suspicious a lot of host fields migrated to os fields, although both os and host should have these. And structures like `self.host['operating-system']['operating-system']` are especially weird. Have you checked that with devs? It might be just a small bug, smth was accidentally touched.

**Comment by oshtaier** [comment]
@abalakh yeap, I am sure. These all things related to interface introduction (or I would call separation). Same procedure was applied on operating system sub-entity.
Check the UI for Hosts sub tabs for better understanding.

**Comment by oshtaier** [comment]
image

**Comment by oshtaier** [comment]
That is probably host unification procedure for all CLI, API and UI interfaces

**Comment by abalakh** [comment]
ACK

**Pull request merged**
