### PR TITLE
Fix stubbed decorator call

### PR DESCRIPTION
**Pull request by elyezer**
Stubbed expect a string parameter or None. By just calling `@stubbed`
the argument will be the decorated method and not a string. Because this
nosetests will not count those skips and py.test will fail all of them.

### CODE REVIEW

**Comment by elyezer** [comment]
Before
=====

Nose

```
$ nosetests tests/foreman/api/test_errata.py

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

py.test

```
$ py.test tests/foreman/api/test_errata.py
=============================== test session starts ===============================
platform darwin -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collected 13 items

tests/foreman/api/test_errata.py FFFFFFFFFFFFF

==================================== FAILURES =====================================
____________________ ErrataTestCase.test_errata_content_host_1 ____________________

wrapper = <function skip_wrapper at 0x103824140>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_errata_content_host_1>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
____________________ ErrataTestCase.test_errata_content_host_2 ____________________

wrapper = <function skip_wrapper at 0x103824de8>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_errata_content_host_2>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
____________________ ErrataTestCase.test_errata_content_view_1 ____________________

wrapper = <function skip_wrapper at 0x1038248c0>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_errata_content_view_1>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
________________________ ErrataTestCase.test_errata_list_1 ________________________

wrapper = <function skip_wrapper at 0x103824758>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_errata_list_1>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
________________________ ErrataTestCase.test_errata_list_2 ________________________

wrapper = <function skip_wrapper at 0x103824500>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_errata_list_2>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
________________________ ErrataTestCase.test_errata_list_3 ________________________

wrapper = <function skip_wrapper at 0x10382f050>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_errata_list_3>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
________________________ ErrataTestCase.test_errata_sort_1 ________________________

wrapper = <function skip_wrapper at 0x103824668>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_errata_sort_1>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
____________________ ErrataTestCase.test_errata_systems_list_1 ____________________

wrapper = <function skip_wrapper at 0x1038248c0>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_errata_systems_list_1>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
____________________ ErrataTestCase.test_errata_systems_list_2 ____________________

wrapper = <function skip_wrapper at 0x10382f320>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_errata_systems_list_2>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
_____________________ ErrataTestCase.test_hc_errata_install_1 _____________________

wrapper = <function skip_wrapper at 0x10382f140>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_hc_errata_install_1>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
____________________ ErrataTestCase.test_incremental_update_1 _____________________

wrapper = <function skip_wrapper at 0x10382f410>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_incremental_update_1>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
____________________ ErrataTestCase.test_incremental_update_2 _____________________

wrapper = <function skip_wrapper at 0x10382f668>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_incremental_update_2>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
____________________ ErrataTestCase.test_incremental_update_3 _____________________

wrapper = <function skip_wrapper at 0x10382f8c0>
wrapped = <tests.foreman.api.test_errata.ErrataTestCase testMethod=test_incremental_update_3>
assigned = ('__module__', '__name__', '__doc__'), updated = ('__dict__',)

    def update_wrapper(wrapper,
                       wrapped,
                       assigned = WRAPPER_ASSIGNMENTS,
                       updated = WRAPPER_UPDATES):
        """Update a wrapper function to look like the wrapped function

           wrapper is the function to be updated
           wrapped is the original function
           assigned is a tuple naming the attributes assigned directly
           from the wrapped function to the wrapper function (defaults to
           functools.WRAPPER_ASSIGNMENTS)
           updated is a tuple naming the attributes of the wrapper that
           are updated with the corresponding attribute from the wrapped
           function (defaults to functools.WRAPPER_UPDATES)
        """
        for attr in assigned:
>           setattr(wrapper, attr, getattr(wrapped, attr))
E           AttributeError: 'ErrataTestCase' object has no attribute '__name__'

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py:33: AttributeError
============================ 13 failed in 2.30 seconds ============================
```

After
====

Nose

```
$ nosetests tests/foreman/api/test_errata.py
SSSSSSSSSSSSS
----------------------------------------------------------------------
Ran 13 tests in 0.002s

OK (SKIP=13)
```

py.test

```
$ py.test tests/foreman/api/test_errata.py
=============================== test session starts ===============================
platform darwin -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collected 13 items

tests/foreman/api/test_errata.py sssssssssssss

=========================== 13 skipped in 0.28 seconds ============================
```

**Comment by JacobCallahan** [comment]
ACK

**Comment by Ichimonji10** [comment]
Do nose and the standard unittest harnesses work with the updated decorator too?

**Comment by Ichimonji10** [comment]
ACK pending comment

**Comment by elyezer** [comment]
@Ichimonji10 I have already provided the before and after for py.test and nose. Here follows the before and after for standard unittest:

Before

```
$ python -m unittest tests.foreman.api.test_errata.ErrataTestCase
EEEEEEEEEEEEE
======================================================================
ERROR: test_errata_content_host_1 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

======================================================================
ERROR: test_errata_content_host_2 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

======================================================================
ERROR: test_errata_content_view_1 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

======================================================================
ERROR: test_errata_list_1 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

======================================================================
ERROR: test_errata_list_2 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

======================================================================
ERROR: test_errata_list_3 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

======================================================================
ERROR: test_errata_sort_1 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

======================================================================
ERROR: test_errata_systems_list_1 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

======================================================================
ERROR: test_errata_systems_list_2 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

======================================================================
ERROR: test_hc_errata_install_1 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

======================================================================
ERROR: test_incremental_update_1 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

======================================================================
ERROR: test_incremental_update_2 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

======================================================================
ERROR: test_incremental_update_3 (tests.foreman.api.test_errata.ErrataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'ErrataTestCase' object has no attribute '__name__'

----------------------------------------------------------------------
Ran 13 tests in 0.002s

FAILED (errors=13)
```

After

```
python -m unittest tests.foreman.api.test_errata.ErrataTestCase
sssssssssssss
----------------------------------------------------------------------
Ran 13 tests in 0.001s

OK (skipped=13)
```

**Comment by elyezer** [comment]
Be aware that nose behave a little different for this error, it does not count any test and does not fail, but py.test and standard unittest does.

This will increase the number of tests because they will be when running with nose:

```
# Before
Ran 3652 tests in 0.247s

# After
Ran 4145 tests in 0.272s
```

**Comment by omaciel** [comment]
Very cool!!!

**Comment by omaciel** [comment]
Looks like the comment has been addressed. ACK

**Pull request merged**
