### PR TITLE
Implemented update function for discovery rule along with a test

### PR DESCRIPTION
**Pull request by sghai**

### CODE REVIEW

**Comment by sghai** [comment]
```
@Test: Update discovery rule name ... ok

----------------------------------------------------------------------
Ran 1 test in 72.791s

OK
```

**Comment by Ichimonji10** [comment]
ACK

**Comment by oshtaier** [comment]
I can see that there is not only 'name' parameter that can be updated for discovery rules (e.g. 'hostgroup'). Do you plan to cover them in scope of another tasks? If yes, could you please create new github issue before closing this one?

**Comment by sghai** [comment]
Yes, There are other bunch of parameters that can be covered as part of update tests. Idea behind raising this PR is to just add the update function and a tests to see if that works correctly.

I'll create new github issue for rest of parameters.

**Comment by oshtaier** [comment]
ACK

**Pull request merged**
