### PR TITLE
[6.15.z] Close-loop BZ2217079

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14276

null

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py::TestPullProviderRex::test_positive_run_job_in_chosen_directory

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6680
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py::TestPullProviderRex::test_positive_run_job_in_chosen_directory --external-logging
Test Result : ================= 6 failed, 567 warnings in 4306.81s (1:11:46) =================
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py::TestPullProviderRex::test_positive_run_job_in_chosen_directory

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6715
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py::TestPullProviderRex::test_positive_run_job_in_chosen_directory --external-logging
Test Result : ================= 6 failed, 540 warnings in 4218.18s (1:10:18) =================
```

**Comment by Gauravtalreja1** [comment]
@lhellebr Could you revist this PR and investigate the PRT failures?

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py::TestPullProviderRex::test_positive_run_job_in_chosen_directory

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7695
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py::TestPullProviderRex::test_positive_run_job_in_chosen_directory --external-logging
Test Result : ================= 6 failed, 539 warnings in 3901.31s (1:05:01) =================
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py::TestPullProviderRex::test_positive_run_job_in_chosen_directory

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7698
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py::TestPullProviderRex::test_positive_run_job_in_chosen_directory --external-logging
Test Result : ================= 6 passed, 561 warnings in 4071.85s (1:07:51) =================
```

**Pull request merged**
