### PR TITLE
Improve CLI and API sync tests

### PR DESCRIPTION
**Pull request by swadeley**
Reduce search rate to every 10s (reduce intermittent fails)
  Fix logger commands to not use .format

### CODE REVIEW

**Comment by swadeley** [comment]
trigger: robottelo
pytest:  tests/foreman/api/test_syncplan.py tests/foreman/cli/test_syncplan.py

**Review by mshriver — APPROVED** [review]

**Comment by swadeley** [comment]
Forgot to add the `search_rate=10` line in UI test. Now done, need to run tests again.

**Comment by swadeley** [comment]
trigger: robottelo
pytest: tests/foreman/api/test_syncplan.py tests/foreman/cli/test_syncplan.py tests/foreman/ui/test_syncplan.py

**Review by pondrejk — APPROVED** [review]

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
