### PR TITLE
VM to Broker conversion for Oscap test

### PR DESCRIPTION
**Pull request by jameerpathan111**
VM to Broker conversion for test_positive_upload_to_satellite test. Refs: https://github.com/SatelliteQE/robottelo/pull/8522#discussion_r615769266
This PR also tries to address issue related to long test name because parameterization.

### CODE REVIEW

**Comment by jameerpathan111** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_oscap.py

**Comment by jameerpathan111** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_oscap.py

**Review by JacobCallahan — APPROVED** [review]

**Comment by jameerpathan111** [comment]
The PRT run fails because of puppet related issue of 6.10(Ref. #8635)

**Comment by JacobCallahan** [comment]
@pondrejk can you check this out, please?

**Review by swadeley — APPROVED** [review]
ACK

**Comment by jameerpathan111** [comment]
Thank you :)

**Pull request merged**
