### PR TITLE
UI: OperatingSys search refactor

### PR DESCRIPTION
**Pull request by lpramuk**
UI: OperatingSys search refactor

(Part of #2930)

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK pending test results

**Comment by kbidarkar** [comment]
ACK.

Merge it once the tests PASS.

**Comment by lpramuk** [comment]
```
$ nosetest -vs tests.foreman.ui.test_operatingsys
Ran 18 tests in 624.434s

FAILED (errors=5, failures=8)
```

**Comment by sthirugn** [comment]
ACK but I have a question on test results.  This shows 5 errors and 8 failures because?

**Comment by elyezer** [comment]
@lpramuk ping

**Comment by lpramuk** [comment]
I submitted that results to say that "I'm in progress..."

**Comment by lpramuk** [comment]
```
$ nosetests tests.foreman.ui.test_operatingsys
....F.............
======================================================================
FAIL: @Test: OS - Create a new OS with same name and version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lpramuk/git/SatelliteQE/robottelo/robottelo/decorators.py", line 136, in wrapper
    return func(*args, **kwargs)
  File "/home/lpramuk/git/SatelliteQE/robottelo/tests/foreman/ui/test_operatingsys.py", line 232, in test_negative_create_os_with_same_name_and_version
    (common_locators['haserror']))
AssertionError: unexpectedly None
```

**Comment by oshtaier** [comment]
ACK. Merge as we will re-run tests anyway in a bunch after. + mentioned error doesn't have references to our changes

**Comment by lpramuk** [comment]
that failure is due to bug? if you create OS with same name and version there is no error msg for that. (6.1.4)

**Pull request merged**
