### PR TITLE
Fix returned data because format changed (gpgkeys)

### PR DESCRIPTION
**Pull request by swadeley**
Due to changes in PR#7824

This is for gpgkeys

Due to changes in filtered_datapoint, [Fix filtered_datapoint() and improve parametrized()](https://github.com/SatelliteQE/robottelo/pull/7824), multiple tests are failing.

### CODE REVIEW

**Comment by swadeley** [comment]
robottelo]$ pytest --show-capture=no tests/foreman/cli/test_gpgkey.py -k test_positive_create_with
=============================== test session starts ===============================================
platform linux -- Python 3.7.7, pytest-4.6.3, py-1.8.1, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo
plugins: cov-2.8.1, services-1.3.1, mock-1.10.4, forked-1.1.3, xdist-1.31.0
collecting ... 2020-07-24 10:33:17 - conftest - DEBUG - Collected 37 test cases
collected 37 items / 35 deselected / 2 selected                                                                  

tests/foreman/cli/test_gpgkey.py ..                                                                        [100%]

============================ 2 passed, 35 deselected in 264.84 seconds ===================================

**Comment by swadeley** [comment]
Hello

Travis's flake8 is failing on 'pytest' on this line:

`tests/foreman/api/test_setting.py:102:6: F821 undefined name 'pytest'`

Flake8 passes locally

**Comment by swadeley** [comment]
robottelo]$ pytest --show-capture=no tests/foreman/cli/test_gpgkey.py -k test_positive_update_key tests/foreman/cli/test_gpgkey.py -k test_positive_search
=============================== test session starts ===============================================
platform linux -- Python 3.7.7, pytest-4.6.3, py-1.8.1, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo
plugins: cov-2.8.1, services-1.3.1, mock-1.10.4, forked-1.1.3, xdist-1.31.0
collecting ... 2020-07-24 10:45:20 - conftest - DEBUG - Collected 74 test cases
collected 74 items / 72 deselected / 2 selected                                                                  

tests/foreman/cli/test_gpgkey.py ..

============================= 2 passed, 72 deselected in 261.12 seconds ============================

**Comment by mshriver** [comment]
@swadeley #7902 should fix that.

**Comment by swadeley** [comment]
Hello

Rebase coming to pick up https://github.com/SatelliteQE/robottelo/pull/7902

**Comment by swadeley** [comment]
robottelo]$ pytest --show-capture=no tests/foreman/cli/test_gpgkey.py -k test_positive_create_with
========================== test session starts ==================================
platform linux -- Python 3.7.7, pytest-4.6.3, py-1.8.1, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo
plugins: cov-2.8.1, services-1.3.1, mock-1.10.4, forked-1.1.3, ipdb-0.1, xdist-1.31.0
collecting ... 2020-07-27 11:00:01 - conftest - DEBUG - Collected 37 test cases
collected 37 items / 35 deselected / 2 selected                                                                  

tests/foreman/cli/test_gpgkey.py ..                                                                        [100%]

===================== 2 passed, 35 deselected in 297.63 seconds =====================

**Comment by swadeley** [comment]
Thank you all.

**Pull request merged**
