### PR TITLE
issues/5882 : Fix AttributeError: 'str' object has no attribute 'decode'

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by ldjebran** [comment]
seems this is resolved in this PR https://github.com/SatelliteQE/robottelo/pull/5898

**Comment by jhutar** [comment]
Please can this be reviewed and merged? Or please suggest somebody else for a review.

**Comment by rochacbruno** [comment]
@jhutar there is no change to merge, all have been already added in other PR. This PR can be closed.

**Comment by jhutar** [comment]
Awesome, thank you @rochacbruno !

**Pull request closed without merging**
