### PR TITLE
[6.12.z] Add Closed loop BZ#2173199

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11608

Adding closed loop for https://bugzilla.redhat.com/show_bug.cgi?id=2173199

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_bootdisk.py -k test_positive_bootdisk_download_https

**Review by pondrejk — APPROVED** [review]
ack pending passing test

**Comment by Gauravtalreja1** [comment]
@shubhamsg199 Could you investigate the failing PRT checks?

**Comment by shubhamsg199** [comment]
This test will fail for 6.12 as the BZ is not fixed for 6.12 -> https://bugzilla.redhat.com/show_bug.cgi?id=2216211

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_bootdisk.py -k test_positive_bootdisk_download_https

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_bootdisk.py -k test_positive_bootdisk_download_https

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
