### PR TITLE
Added new cli options to hammer_commands.json

### LINKED ISSUE #3633: Fix tests.foreman.cli.test_hammer.HammerCommandsTestCase.test_positive_all_options
```
E           AssertionError: 
E           hammer activation-key subscriptions
E             Added options:
E               * search
E               * full-results
E               * order
E               * by
E               * host
E               * activation-key
E               * activation-key-id
E               * page
E               * per-page
E           
E           hammer hostgroup create
E             Added options:
E               * organization
E               * organization-id
E           
E           hammer hostgroup update
E             Added options:
E               * organization
E               * organization-id
```

### PR DESCRIPTION
**Pull request by svtkachenko**
Fixes #3633 

2016-07-21 18:46:58 - robottelo - DEBUG - Finished Test: HammerCommandsTestCase/test_positive_all_options

========================= 1 passed in 4004.04 seconds ==========================

### CODE REVIEW

**Comment by omaciel** [comment]
@svtkachenko awesome!!! Can you confirm that this was tested against SNAP 21.0? @sghai any comments from you?

**Comment by sghai** [comment]
@omaciel @svtkachenko : Changes looks good. Nice to see first PR from @svtkachenko 

As per jenkins job, following new options have been added to `hammer activation-key subscriptions`:
- host
- search
- full-results
- order
- by
- activation-key
-activation-key-id
- page
- per-page

Hammer hostgroup create/update updated with : `organization and organization-id` options

Though they forgot to remove `organizations and organization-ids` from hostgroup create/update. Will file bz..

**Comment by sghai** [comment]
ACK

**Comment by omaciel** [comment]
ACK

**Pull request merged**
