### PR TITLE
make broker logger to use same format as robottelo one

### PR DESCRIPTION
**Pull request by rplevka**
to do:
- [x] robottelo logger code changes
- [x] https://github.com/SatelliteQE/broker/pull/205
- [x] wait for the changes to land in broker release
- [x] https://github.com/SatelliteQE/robottelo/pull/11210

Streamline the robottelo and broker log formats.
This initializes broker logger with the robottelo formatter.

before the change:
```
2023-04-04 01:16:40 - gw1 - robottelo - INFO - Finished Test: tests/foreman/api/test_ping.py::test_positive_ping[2-2]
2023-04-04 01:17:15 - gw1 - robottelo - DEBUG - Original deploy arguments for sat: {'deploy_snap_version': 'this.server.version.snap', 'deploy_sat_version': 'this.server.version.release', 'deploy_rhel_version': 'this.server.version.rhel_version'}
2023-04-04 01:17:15 - gw1 - robottelo - DEBUG - Resolved deploy arguments for sat: {'deploy_snap_version': 16.0, 'deploy_sat_version': 6.13, 'deploy_rhel_version': 8}
[D 230404 01:17:15 broker:84] Broker instantiated with kwargs={'host_class': <class 'robottelo.hosts.Satellite'>}
[D 230404 01:17:15 broker:319] reconstructing host with export: {'_broker_args': ... }
```

after the change:
```
2023-04-04 01:00:59 - gw1 - robottelo - DEBUG - Original deploy arguments for sat: {'deploy_snap_version': 'this.server.version.snap', 'deploy_sat_version': 'this.server.version.release', 'deploy_rhel_version': 'this.server.version.rhel_version'}
2023-04-04 01:00:59 - gw1 - robottelo - DEBUG - Resolved deploy arguments for sat: {'deploy_snap_version': 16.0, 'deploy_sat_version': 6.13, 'deploy_rhel_version': 8}
2023-04-04 01:00:59 - gw1 - broker - DEBUG - Broker instantiated with kwargs={'host_class': <class 'robottelo.hosts.Satellite'>}
2023-04-04 01:00:59 - gw1 - broker - DEBUG - reconstructing host with export: {'_broker_args': {'deploy_rhel_version': '8.7', 'deploy_sat_version': '6.13.0', 'deploy_snap_version': '16.0', 'host_type': 'satellite', ''os_distribution': 'RedHat', 'os_distribution_version': '8.7', 'reported_devices': {'nics': ['lo', 'eth0']}, 'template': 'tpl-sat-jenkins-6.13.0-16.0-rhel-8.7',  'host_type': 'satellite', 'os_distribution': 'RedHat', 'os_distribution_version': '8.7', 'reported_devices': {'nics': ['lo', 'eth0']}, 'template': 'tpl-sat-jenkins-6.13.0-16.0-rhel-8.7', 'type': 'host'}
```

### CODE REVIEW

**Review by JacobCallahan — APPROVED** [review]

**Review by ogajduse — APPROVED** [review]

**Comment by rplevka** [comment]
ready for merging after https://github.com/SatelliteQE/robottelo/pull/11210 gets in

**Comment by ogajduse** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_ping.py[root]

**Comment by ogajduse** [comment]
Let's wait for #11367 to be merged and then re-run CI/CQ here.

@rplevka  the patch did not modify the format of the broker logs.
```
2023-04-27 13:50:33 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
    capsule.instance_name is required in env main
2023-04-27 13:50:37 - spnego._gss - DEBUG - Python gssapi not available, cannot use any GSSAPIProxy protocols: No module named 'gssapi'
2023-04-27 13:50:37 - spnego._gss - DEBUG - Python gssapi IOV extension not available: No module named 'gssapi'
2023-04-27 13:50:37 - spnego._sspi - DEBUG - SSPI bindings not available, cannot use any SSPIProxy protocols: No module named 'spnego._sspi_raw.sspi'
2023-04-27 13:50:41 - robottelo.collection - INFO - Processing test items to add testimony token markers
2023-04-27 13:50:41 - robottelo - INFO - Started Test: tests/foreman/cli/test_ping.py::test_positive_ping[root]
2023-04-27 13:50:41 - robottelo - DEBUG - Original deploy arguments for sat: {'promtail_enable': True, 'deploy_sat_version': 'stream', 'deploy_snap_version': 11.0, 'deploy_rhel_version': 8.7}
2023-04-27 13:50:41 - robottelo - DEBUG - Resolved deploy arguments for sat: {'promtail_enable': True, 'deploy_sat_version': 'stream', 'deploy_snap_version': 11.0, 'deploy_rhel_version': 8.7}
[D 230427 13:50:41 broker:68] Broker instantiated with kwargs={'host_class': <class 'robottelo.hosts.Satellite'>}
2023-04-27 13:50:41 - robottelo - DEBUG - Updated broker args for sat: {'promtail_enable': True, 'deploy_sat_version': 'stream', 'deploy_snap_version': 11.0, 'deploy_rhel_version': 8.7}
[D 230427 13:50:41 broker:68] Broker instantiated with kwargs={'host_class': <class 'robottelo.hosts.Satellite'>, 'workflow': 'deploy-satellite', 'promtail_enable': True, 'deploy_sat_version': 'stream', 'deploy_snap_version': 11.0, 'deploy_rhel_version': 8.7}
[D 230427 13:50:41 broker:123] Doing _checkout(): self._provider_actions={'workflow': (<class 'broker.providers.ansible_tower.AnsibleTower'>, 'execute')}
[I 230427 13:50:41 broker:128] Using provider AnsibleTower to checkout
[D 230427 13:50:41 broker:88] Resolving action execute on provider <class 'broker.providers.ansible_tower.AnsibleTower'>.
[D 230427 13:50:41 __init__:55] AnsibleTower provider instantiated with kwargs={'workflow': 'deploy-satellite', 'promtail_enable': True, 'deploy_sat_version': 'stream', 'deploy_snap_version': 11.0, 'deploy_rhel_version': 8.7}
```

**Comment by rplevka** [comment]
that is because the logs are originating from broker's own logger initialization, not from the function I updated.

**Pull request merged**
