### PR TITLE
changed registered host to rhel7 only

### PR DESCRIPTION
**Pull request by ColeHiggins2**
Fixed tests failure, Removed parametrized testing for rhel6, rhel7, and rhel8. 

Open for discussion on whether we need to write 2 more tests for rhel6 and rhel8

### CODE REVIEW

**Review by JacobCallahan — APPROVED** [review]
ACK. Merge pending test results. You can hold on the other rhel versions for now, but keep this test in mind when we get around to the major parameterization push.

**Review by synkd — APPROVED** [review]
ACK.

I do think it would be a good idea to write tests for RHEL 6 and 8. RHEL 6 currently requires an Extended Lifecyle Support (ELS) subscription to access content; we could potentially catch any issues arising from SCA and ELS subscriptions with that test. And RHEL 8 uses (and, I assume, RHEL 9 will use) a different product certificate from earlier RHEL versions; we may be able to catch version-specific SCA issues there as well.

**Comment by JacobCallahan** [comment]
@ColeHiggins2 can you rebase this pr, should help you checks pass.

**Review by swadeley — APPROVED** [review]
ACK

**Pull request merged**
