### PR TITLE
Improve logging for the decorators module

### PR DESCRIPTION
**Pull request by elyezer**
Create an specific logger for the module and log when skipping bugs.
Logging when a test is skipped will allow generate a report showing all
skipped tests due to bugs.

### CODE REVIEW

**Comment by omaciel** [comment]
Should probably add an example of what you want to capture here :)

APT

**Comment by elyezer** [comment]
The generated logging will be something like:

```
2015-05-29 17:10:57 - robottelo.common.decorators - INFO - Bugzilla bug 1226425 not in cache. Fetching.
2015-05-29 17:10:58 - robottelo.common.decorators - DEBUG - Skipping test test_1 in module tests.foreman.test due to Bugzilla bug #1226425
2015-05-29 17:10:58 - robottelo.common.decorators - INFO - Redmine bug 10653 not in cache. Fetching.
2015-05-29 17:10:59 - robottelo.common.decorators - DEBUG - Skipping test test_2 in module tests.foreman.test due to Redmine bug #10653
```

The idea is to create a job that will grab all logging and check for skip entries in order to generate a report show the number of skipped tests due to bugs.

**Comment by sthirugn** [comment]
APT

**Comment by elyezer** [comment]
The reason to create a new logger is because

    A good convention to use when naming loggers is to use a module-level logger, in each module which uses logging, named as follows:

    logger = logging.getLogger(__name__)

From https://docs.python.org/2/howto/logging.html#advanced-logging-tutorial

**Comment by Ichimonji10** [comment]
:+1:

**Pull request merged**
