### PR TITLE
Code Coverage 1: low impact test case

### PR DESCRIPTION
**Pull request by latran**
IMO, this is a low impact test case that should be removed.  Let me know if you think otherwise.

### CODE REVIEW

**Comment by latran** [comment]
Added a couple more removals.  Removed stubbed test cases as it's better covered in CLI or UI than API.

**Comment by jameerpathan111** [comment]
> Added a couple more removals. Removed stubbed test cases as it's better covered in CLI or UI than API.

@latran @mirekdlugosz To which interface we give more priority/importance while adding test coverage for a feature?

**Comment by latran** [comment]
@jameerpathan111 

That's a good question.  I think it's a case by case basis and what limitations does each test case have.  I try to do all 3, but typically CLI and UI are top priorities for me.

**Comment by latran** [comment]
Can someone merge this please?

**Pull request merged**
