### PR TITLE
Debug PRT

### PR DESCRIPTION
**Pull request by tpapaioa**

### CODE REVIEW

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py::test_positive_install_content_with_http_proxy
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8555
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_http_proxy.py::test_positive_install_content_with_http_proxy --external-logging
Test Result : ================== 1 passed, 9 warnings in 634.25s (0:10:34) ===================
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8557
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : =========== 3 passed, 4 deselected, 58 warnings in 617.99s (0:10:17) ===========
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8558
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ===== 2 failed, 4 deselected, 65 warnings, 4 errors in 1324.97s (0:22:04) ======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8559
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 3 failed, 4 deselected, 68 warnings, 3 errors in 870.35s (0:14:30) ======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k 'test_positive_install_content_with_http_proxy and auth_http_proxy'
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8560
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy and auth_http_proxy --external-logging
Test Result : ====== 2 failed, 5 deselected, 52 warnings, 2 errors in 765.83s (0:12:45) ======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k 'test_positive_install_content_with_http_proxy and auth_http_proxy'
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8562
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy and auth_http_proxy --external-logging
Test Result : ========== 5 deselected, 52 warnings, 4 errors in 1359.85s (0:22:39) ===========
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py::test_positive_install_content_with_http_proxy[rhel8-ipv4-auth_http_proxy] tests/foreman/api/test_http_proxy.py::test_positive_install_content_with_http_proxy[rhel8-ipv4-unauth_http_proxy
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8590
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py::test_positive_install_content_with_http_proxy[rhel8-ipv4-auth_http_proxy] tests/foreman/api/test_http_proxy.py::test_positive_install_content_with_http_proxy[rhel8-ipv4-unauth_http_proxy] --external-logging
Test Result : ============= 2 failed, 44 warnings, 2 errors in 737.60s (0:12:17) =============
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py::test_positive_install_content_with_http_proxy[rhel8-ipv4-auth_http_proxy] tests/foreman/api/test_http_proxy.py::test_positive_install_content_with_http_proxy[rhel8-ipv4-unauth_http_proxy
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py::test_positive_install_content_with_http_proxy[rhel8-ipv4-auth_http_proxy] tests/foreman/api/test_http_proxy.py::test_positive_install_content_with_http_proxy[rhel8-ipv4-unauth_http_proxy]
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8595
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 2 failed, 4 deselected, 35 warnings, 2 errors in 749.13s (0:12:29) ======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8597
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 2 failed, 4 deselected, 34 warnings, 2 errors in 699.31s (0:11:39) ======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8598
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 2 failed, 4 deselected, 34 warnings, 2 errors in 707.49s (0:11:47) ======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8599
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 2 failed, 4 deselected, 33 warnings, 2 errors in 696.32s (0:11:36) ======
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8600
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 2 failed, 4 deselected, 34 warnings, 2 errors in 653.35s (0:10:53) ======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
broker: 315
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8601
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 2 failed, 4 deselected, 34 warnings, 2 errors in 671.45s (0:11:11) ======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
broker: 315
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8602
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 2 failed, 4 deselected, 34 warnings, 2 errors in 698.78s (0:11:38) ======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
broker: 315
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8603
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 1 failed, 4 deselected, 13 warnings, 1 error in 812.12s (0:13:32) =======
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8604
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 1 failed, 4 deselected, 13 warnings, 1 error in 672.13s (0:11:12) =======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
broker: 315
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8605
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 1 failed, 4 deselected, 13 warnings, 1 error in 663.43s (0:11:03) =======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
broker: 315
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8614
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 1 failed, 4 deselected, 13 warnings, 1 error in 673.86s (0:11:13) =======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8615
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 1 failed, 4 deselected, 13 warnings, 1 error in 610.72s (0:10:10) =======
```

**Comment by tpapaioa** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8624
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py -k test_positive_install_content_with_http_proxy --external-logging
Test Result : ====== 1 failed, 4 deselected, 13 warnings, 1 error in 625.22s (0:10:25) =======
```

**Pull request closed without merging**
