### PR TITLE
Automate tests for new UI content tab

### PR DESCRIPTION
**Pull request by peterdragun**
~~Depends on: SatelliteQE/airgun/pull/720~~

### CODE REVIEW

**Comment by peterdragun** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_positive_apply_erratum or test_positive_update_delete_package or test_positive_crud_module_streams'
airgun: 720

**Comment by peterdragun** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_positive_apply_erratum or test_positive_update_delete_package or test_positive_crud_module_streams'
airgun: 720

**Comment by peterdragun** [comment]
PRT is running on 6.11, fails are because of the tested part of UI is new in 6.12. PRT should be retriggered after branching and updating the config for PRT.
Tests are passing locally.

**Comment by peterdragun** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_positive_apply_erratum or test_positive_update_delete_package or test_positive_crud_module_streams'
airgun: 720

**Comment by peterdragun** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_positive_apply_erratum or test_positive_update_delete_package or test_positive_crud_module_streams'
airgun: 720

**Comment by peterdragun** [comment]
trigger: test-robottelo
pytest: -v tests/foreman/ui/test_host.py -k 'test_positive_apply_erratum or test_positive_update_delete_package or test_positive_crud_module_streams'
airgun: 720

**Comment by peterdragun** [comment]
trigger: test-robottelo
pytest: -v tests/foreman/ui/test_host.py -k 'test_positive_apply_erratum or test_positive_update_delete_package or test_positive_crud_module_streams'
airgun: 720

**Comment by jameerpathan111** [comment]
trigger: test-robottelo
airgun: 736
pytest: tests/foreman/ui/test_settings.py

**Comment by jameerpathan111** [comment]
Testing https://github.com/SatelliteQE/airgun/pull/736 here(with peter's permission)

**Comment by peterdragun** [comment]
trigger: test-robottelo
pytest: -v tests/foreman/ui/test_host.py -k 'test_positive_apply_erratum or test_positive_update_delete_package or test_positive_crud_module_streams'
airgun: 720

**Review by swadeley — APPROVED** [review]
ACK

**Review by latran — APPROVED** [review]

**Review by pondrejk — APPROVED** [review]

**Pull request merged**
