### PR TITLE
Fix host-collections max-content-host attribute name

### PR DESCRIPTION
**Pull request by sthirugn**
```
$nosetests tests/foreman/cli/test_host_collection.py:TestHostCollection.test_positive_create_3
.
----------------------------------------------------------------------
Ran 1 test in 37.948s

OK
```
This fixes two cli failures in the recent automation run.

### CODE REVIEW

**Comment by sthirugn** [comment]
This is ready for review

**Comment by elyezer** [comment]
ACK

**Comment by oshtaier** [comment]
Is it fine that we have different parameters for create procedure:
input - ```max-content-hosts```:
```
self._new_host_collection({
             'max-content-hosts': test_data,
})
```
and output - ```limit```:
```
self.assertEqual(new_host_col['limit'], str(test_data))
```

**Comment by sthirugn** [comment]
@oshtaier Good question.  I haven't reviewed many cli commands to see if we are following any pattern for implementation.  But if you feel this is a bug, please create a bugzilla.

**Comment by Ichimonji10** [comment]
@oshtaier I've written up bugs for similar issues, and would go ahead and write a bug in this case too. For inspiration, see https://bugzilla.redhat.com/show_bug.cgi?id=1235019

**Comment by Ichimonji10** [comment]
ACK

**Pull request merged**
