### PR TITLE
ddt removal in ui content env tests

### PR DESCRIPTION
**Pull request by sthirugn**

### CODE REVIEW

**Comment by kbidarkar** [comment]
ACK

**Comment by oshtaier** [comment]
ACK pending test results

**Comment by sthirugn** [comment]
```sh
# nosetests tests/foreman/ui/test_contentenv.py:ContentEnvironment.test_positive_create_content_environment_basic
.
----------------------------------------------------------------------
Ran 1 test in 57.935s

OK
```

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
