### PR TITLE
Fixed UI tests

### PR DESCRIPTION
**Pull request by sghai**
Fixed  test_clone_template by adding wait_for_ajax statement
Fixed test_create_cv by updating its data-set

### CODE REVIEW

**Comment by elyezer** [comment]
APT

**Comment by oshtaier** [comment]
APT

**Comment by sthirugn** [comment]
@sghai please update test results as per @oshtaier.  I am going to merge it though.

**Comment by sghai** [comment]
Sure..

```
@Test: Assure ability to clone a provisioning template ... ok

----------------------------------------------------------------------
Ran 1 test in 85.147s

OK
```

**Comment by sghai** [comment]
```
@test: create content views (positive) ... ok
@test: create content views (positive) ... ok
@test: create content views (positive) ... ok
@test: create content views (positive) ... ok
@test: create content views (positive) ... ok
@test: create content views (positive) ... ok

----------------------------------------------------------------------
Ran 6 tests in 305.662s

OK
```

**Pull request merged**
