### PR TITLE
Fixes for ansible

### PR DESCRIPTION
**Pull request by adarshdubey-star**
Some refactoring and fixes

### CODE REVIEW

**Comment by Griffin-Sullivan** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_ansible.py::test_fetch_and_sync_ansible_playbooks tests/foreman/api/test_ansible.py::test_positive_ansible_job_on_host tests/foreman/ui/test_ansible.py::test_positive_ansible_custom_role

**Review by lhellebr — APPROVED** [review]
Simple enough and necessary refactor, LGTM

**Review by synkd — APPROVED** [review]

**Review by shubhamsg199 — APPROVED** [review]
Ack

**Comment by Griffin-Sullivan** [comment]
UI failure seems unrelated

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
