### PR TITLE
Replace import_string with import_module

### PR DESCRIPTION
**Pull request by nixocio**
Replace the use of `import_string` with `import_module` from the
standard library.

See: https://docs.python.org/3/library/importlib.html#importlib.import_module

### CODE REVIEW

**Comment by rochacbruno** [comment]
+1 to remove the whole `func_shared`

**Comment by kersommoura** [comment]
@mirekdlugosz, I ran the unittests tests. And I noticed the same about @shared decorator not being used. If we are not using and do not have need to use them, IMO we should remove them, simplify the code basis and let version control take of it.

snippet: 
```shell
make test-robottelo

tests/robottelo/test_api_utils.py ..
tests/robottelo/test_assertions.py ..........................................
tests/robottelo/test_cli.py ......................................
tests/robottelo/test_cli_method_calls.py ................................
tests/robottelo/test_config_casts.py ..............
tests/robottelo/test_config_settings.py ......
tests/robottelo/test_datafactory.py .....
tests/robottelo/test_decorators.py ................
tests/robottelo/test_func_locker.py ............
tests/robottelo/test_func_shared.py ............  File "/home/kmo/work/sat_automation/robottelo/robottelo/decorators/func_shared/shared.py", line 282, in _call_function
...
tests/robottelo/test_hammer.py ..........
tests/robottelo/test_helpers.py ..................................
tests/robottelo/test_host_info.py ................
tests/robottelo/test_settings.py .
tests/robottelo/test_ssh.py ..............
tests/robottelo/test_vm.py ........
tests/robottelo/api/test_assertions.py ..................................
tests/robottelo/cli/test_assertions.py ........
tests/robottelo/decorators/test_host.py .........

======================================================================================================== 316 passed in 18.92 seconds =========================================================================================================


```

**Comment by mirekdlugosz** [comment]
@kersommoura I'll leave it up to you to decide which one you want to pursue. Removing `@shared` is obviously more work, so I understand if you don't want to spend too much time on that. I'll ACK both.

If you decide to remove `@shared`, we should advertise that on satqe list before merge to get more people involved. Just in case this is critical for someone's workflow.

**Comment by kersommoura** [comment]
@mirekdlugosz, for the time being I will stick with removing the `import_string`, but I will file an issue to remove the `@shared` code, and give others a chance to chime in. Thanks.

**Comment by mirekdlugosz** [comment]
@SatelliteQE/quality-engineers can we have tier2 ACK and merge here? It's been opened for over two weeks.

**Comment by rochacbruno** [comment]
@mirekdlugosz are we merging it or removing all the shared_function code?

**Comment by mirekdlugosz** [comment]
Judging from last comment by @nixocio , he isn't that interested in expanding scope of his PR to remove whole thing, and nobody chimed in to take it over. So our options really are "merge" and "stall it indefinitely".

I vote for merge.

**Pull request merged**
