### PR TITLE
Remove tests with API and CLI equivalent (#7154)

### PR DESCRIPTION
**Pull request by swadeley**
* These tests all have a CLI and API equivalent which duplicates the test
logic.

1] Remove test_negative_synchronize_custom_product_past_sync_date

Links to API and CLI version of this test as proof that code logic is covered elsewhere:

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/api/test_syncplan.py#L678

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/cli/test_syncplan.py#L417

------------------------------------------------------------------------------------------------------

2] Remove test_positive_synchronize_custom_product_past_sync_date

Links to API and CLI version of this test as proof that code logic is covered elsewhere

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/api/test_syncplan.py#L711

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/cli/test_syncplan.py#L459

----------------------------------------------------------------------------------------------------------------

3] Remove test_positive_synchronize_custom_product_future_sync_date

Links to API and CLI version of this test as proof that code logic is covered elsewhere

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/api/test_syncplan.py#L758

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/cli/test_syncplan.py#L516

---------------------------------------------------------------------------------------------------------------

4]  Remove test_positive_synchronize_custom_products_future_sync_date

Links to API and CLI version of this test as proof that code logic is covered elsewhere

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/api/test_syncplan.py#L811

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/cli/test_syncplan.py#L570

---------------------------------------------------------------------------------------------------------------

5] Remove test_positive_synchronize_rh_product_future_sync_date

Links to API and CLI version of this test as proof that code logic is covered elsewhere

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/api/test_syncplan.py#L936

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/cli/test_syncplan.py#L711

---------------------------------------------------------------------------------------------------------------

6] Remove test_positive_synchronize_custom_product_daily_recurrence

Links to API and CLI version of this test as proof that code logic is covered elsewhere

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/cli/test_syncplan.py#L786

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/api/test_syncplan.py#L1005

----------------------------------------------------------------------------------------------------------------

7] Remove test_positive_synchronize_custom_product_weekly_recurrence

Links to API and CLI version of this test as proof that code logic is covered elsewhere

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/api/test_syncplan.py#L1051

https://github.com/SatelliteQE/robottelo/blob/f376d01e22d71ba1b1613d1adc2569cc8a91f67a/tests/foreman/cli/test_syncplan.py#L838

--------------------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by swadeley** [comment]
Thanks @vijay8451, 

I fixed that, flake8 passes locally now.

**Comment by latran** [comment]
@swadeley  I don't know if it's appropriate to remove this since the UI portion simulates customer interaction and failures may show up via navigation/interaction of the web pages.  I see a few test cases in my component area as well that is also covered in all 3 areas (API, CLI, UI) and serves to extend testing.  My opinion is to keep it so it can track UI failures unless other test already covers it.  Other opinions are welcome.

**Comment by swadeley** [comment]
@latran thanks for the feedback, good point, I should have added more info to the opening statement. We intend to keep the end-to-end tests, and possibly merge the two end-to-end tests into one, as a check that all web UI elements related to Sync Plans function.

End-to-end tests are expected to take a long time, so there is no pressure on component owners to reduce their run time. So they are the best place to exercise all web UI actions required to test a component.

Thank you

**Comment by latran** [comment]
@swadeley Ok.  I'll leave the sound judgment in your hands then :)

**Comment by JacobCallahan** [comment]
@swadeley can you verify that each of these forms/inputs is touched in the end-to-end test(s)?

**Comment by san7ket** [comment]
@swadeley @JacobCallahan This is pending since long, So, in the removed tests , there are 3 operations done related to Syncplan
1. Create Syncplan
2. Search Syncplan
3. Add repo to syncplan

@swadeley Can you verify that the e2e tests touches the above forms. I bet they would but would be great if you confirm

**Comment by swadeley** [comment]
Hello @san7ket 

I was not sure what level of proof @JacobCallahan wanted to see. I imagined I would have to make a table with all the API end points and check they all get tested, but I have been busy with ON_QA work.

A Sync Plan page has these items:
Name             <--test assigns 
Description      <--test assigns
Start Date        <--test assigns
Next Sync          <--gets calculated based on start time and interval
Recurring Logic  <-- This gets assigned by foreman tasks, not the test.
Sync Enabled      <--test assigns
Interval                <--test assigns
Products  <-- Gets updated to show how many product you have associated

If you look at the sync plan create page its just:
Name
Description
Interval
Start Date
Start Time  [optional]

The first of the end to end test is test_positive_end_to_end [1]

It creates a daily sync plan, asserts all the expected values exist, and updates the description.

Looking at the code its plain to see these values are assigned when the sync plan is created:
name
interval
description
date_time.start_date
date_time.hours
date_time.minutes


The next test (test_positive_end_to_end_custom_cron)[2] is very similar except it uses custom cron instead of daily.

I think only the addition and removal of a product should be added. This can be done when I combine the two end to end tests into one to save on setup time.[3]


[1]  https://github.com/SatelliteQE/robottelo/blob/c4ff7741fd1a3a549bf3f553089fd7062bde6bb4/tests/foreman/ui/test_syncplan.py#L90

[2] https://github.com/SatelliteQE/robottelo/blob/c4ff7741fd1a3a549bf3f553089fd7062bde6bb4/tests/foreman/ui/test_syncplan.py#L135

[3] Consolidate Sync Plan end to end UI tests #7253 https://github.com/SatelliteQE/robottelo/issues/7253

**Comment by JacobCallahan** [comment]
ACK, thanks for the follow-up.

**Comment by swadeley** [comment]
Thank you all

**Pull request merged**
