### PR TITLE
Tfa fix compute resources azure

### PR DESCRIPTION
**Pull request by amolpati30**
### Problem Statement
Encountering an assertion error that is causing three test cases to fail.

### Solution
Fixed the error, update the assertion

### CODE REVIEW

**Comment by amolpati30** [comment]
"trigger": "test-robottelo"
"pytest": "tests/foreman/cli/test_computeresource_azurerm.py -k 'test_positive_azurerm_host_provisioned'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7837
Build Status: SUCCESS
PRT Comment: pytest /opt/app-root/src/robottelo/tests/foreman -v -m build_sanity --external-logging
Test Result : ======= 12 passed, 5531 deselected, 5639 warnings in 1946.30s (0:32:26) ========
```

**Review by ColeHiggins2 — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_azurerm.py::{TestAzureRMFinishTemplateProvisioning,TestAzureRMUserDataProvisioning}

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7846
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_computeresource_azurerm.py::{TestAzureRMFinishTemplateProvisioning,TestAzureRMUserDataProvisioning} --external-logging
Test Result : ================= 3 passed, 102 warnings in 2583.61s (0:43:03) =================
```

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
