### PR TITLE
[6.13.z] test settings change from non-default to default

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11437

Extending the existing test to cover for 2157869, also removed some old skips from the test_settings file

Local result:

```
 pytest tests/foreman/ui/test_settings.py -k test_positive_update_login_page_footer_text
================================================ test session starts =================================================
collected 16 items / 15 deselected / 1 selected                                                                      

tests/foreman/ui/test_settings.py .                                                                            [100%]


============================== 1 passed, 15 deselected, 2 warnings in 126.77s (0:02:06) ==============================
```

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_settings.py -k test_positive_update_login_page_footer_text

**Comment by Gauravtalreja1** [comment]
@pondrejk can you look into the PRT result?

**Comment by devendra104** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_settings.py -k test_positive_update_login_page_footer_text

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_settings.py -k test_positive_update_login_page_footer_text

**Comment by pondrejk** [comment]
locally the test passes:
```

pytest tests/foreman/ui/test_settings.py -k test_positive_update_login_page_footer_text
================================================ test session starts =================================================

plugins: services-2.2.1, mock-3.10.0, cov-3.0.0, ibutsu-2.2.4, xdist-3.2.1, reportportal-5.1.7
collected 16 items / 15 deselected / 1 selected                                                                      

tests/foreman/ui/test_settings.py .                                                                            [100%]

```

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
