### PR TITLE
[6.11.z] Add f-m upgrade tests to robottelo with capsule parametrization

### LINKED ISSUE #10300: [Failed-AutoCherryPick] -  Add f-m upgrade tests to robottelo with capsule parametrization
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3472430441)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10227)

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
CherryPick of https://github.com/SatelliteQE/robottelo/pull/10227
Fixes #10300

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/maintain/test_upgrade.py

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/maintain/test_upgrade.py

**Comment by jyejare** [comment]
@Gauravtalreja1 You have some fails in PRT, is that expected ?

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/maintain/test_upgrade.py

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/maintain/test_upgrade.py

**Comment by Gauravtalreja1** [comment]
@jyejare PRT passed!

**Review by jyejare — APPROVED** [review]

**Review by jyejare — APPROVED** [review]

**Pull request merged**
