### PR TITLE
Fix UI issue for create new user functionality

### LINKED ISSUE #2223: Automation failure : tests.foreman.ui.test_user.User.test_update_password
Error Message
```403 Client Error: Forbidden```

Stacktrace
```
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "robottelo/common/decorators.py", line 362, in wrapper_func
    return func(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-ui/tests/foreman/ui/test_user.py", line 87, in test_update_password
    self.assertTrue(self.login.is_logged())
  File "robottelo/ui/login.py", line 56, in is_logged
    response.raise_for_status()
  File "/home/jenkins/shiningpanda/jobs/ca586003/virtualenvs/d41d8cd9/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
```

### PR DESCRIPTION
**Pull request by oshtaier**
It seems that 'is_logged' functionality was improved. Fixed UI test, so it passes
Closes #2223

### CODE REVIEW

**Comment by oshtaier** [comment]
```
nosetests tests/foreman/ui/test_user.py -m test_update_password
.
----------------------------------------------------------------------
Ran 1 test in 78.383s

OK
```

**Comment by oshtaier** [comment]
Refer to https://github.com/SatelliteQE/robottelo/pull/2203 to find solution for that issue

**Comment by elyezer** [comment]
ACK

**Comment by jyejare** [comment]
ACK

**Pull request merged**
