### PR TITLE
Use module_extra_rhel_entitlement_manifest for cloud connector test

### PR DESCRIPTION
**Pull request by jameerpathan111**
### Problem Statement
There have been new IQE tests added that requires manifest with more entitlements.  

### Solution
Use `module_extra_rhel_entitlement_manifest` for `test_positive_configure_cloud_connector`.

### CODE REVIEW

**Review by pondrejk — APPROVED** [review]

**Review by synkd — APPROVED** [review]

**Review by Gauravtalreja1 — APPROVED** [review]
Ack, pending test results

**Comment by jameerpathan111** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_rhc.py

**Comment by jameerpathan111** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_rhc.py
env:
  ROBOTTELO_ui__record_video: true
```

**Comment by jameerpathan111** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_rhc.py
env:
  ROBOTTELO_ui__record_video: true
```

**Pull request merged**
