### PR TITLE
fixes #4006 - permission constants need to be updated

### LINKED ISSUE #4006: API - permission constants need to be updated
from __tests.foreman.api.test_permission.PermissionTestCase.test_positive_search__
```json
{"added_names": [
    "edit_external_parameters",  
     "view_params",  
     "destroy_external_parameters", 
     "create_external_parameters",
     "view_external_parameters"
  ],
  "added_resource_types": [
     "PuppetclassLookupKey",
     "VariableLookupKey"
  ],
  "removed_names": [
     "destroy_content_hosts",
     "create_content_hosts",
     "edit_content_hosts",
     "view_content_hosts"
  ],
 "removed_resource_types": [
     "Katello::System",
     "LookupKey"
  ]
}
```

### PR DESCRIPTION
**Pull request by rplevka**
```bash
$ nosetests -m test_positive_search test_permission.py 
...
----------------------------------------------------------------------
Ran 3 tests in 256.669s

OK
```

### CODE REVIEW

**Comment by oshtaier** [comment]
NACK according to travis. Interesting fact that test has been passed for duplicated lists

**Comment by rplevka** [comment]
i can't figure out what  is wrong with it.

**Comment by oshtaier** [comment]
ACK

**Comment by omaciel** [comment]
@oshtaier glad to see you commenting on PRs :)

**Comment by oshtaier** [comment]
@omaciel sure, gonna drop you a message in nearest days

**Pull request merged**
