### PR TITLE
part of a fix of #3291 - removing tier decorators for Import tests

### PR DESCRIPTION
**Pull request by rplevka**

### CODE REVIEW

**Comment by rplevka** [comment]
addresses https://github.com/SatelliteQE/robottelo/issues/3291

**Comment by elyezer** [comment]
APT

**Comment by omaciel** [comment]
@rplevka can we get a better commit message? I'm not sure why we're removing the decorator :/

**Comment by omaciel** [comment]
@rplevka will merge this now as we need it for our next compose build.

**Pull request merged**
