### PR TITLE
Reporting test fixes for stream

### PR DESCRIPTION
**Pull request by LadislavVasina1**
### Problem Statement
There were multiple outdated Reporting UI tests that did not work correctly with stream.

### Solution
This PR fixes these issues.

### PRT test Cases example
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_reporttemplates.py -k "test_positive_schedule_generation_and_get_mail or test_positive_installable_errata_with_user or test_positive_generate_subscriptions_report_json or test_positive_generate_all_installed_packages_report"
```

### CODE REVIEW

**Comment by LadislavVasina1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_reporttemplates.py -k "test_positive_schedule_generation_and_get_mail or test_positive_installable_errata_with_user or test_positive_generate_subscriptions_report_json or test_positive_generate_all_installed_packages_report"
```

**Comment by LadislavVasina1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_reporttemplates.py -k "test_positive_schedule_generation_and_get_mail or test_positive_installable_errata_with_user or test_positive_generate_subscriptions_report_json or test_positive_generate_all_installed_packages_report"
```

**Comment by LadislavVasina1** [comment]
I think that the addition of the force flag will pass (or fail on something else:D) all the 60 tests that failed in snap81 because of this error 
```robottelo.exceptions.CLIReturnCodeError: CLIReturnCodeError(status=64, stderr="Could not update content override:\n  You must use --force to set a value other than 'enabled'```

**Comment by LadislavVasina1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_reporttemplates.py -k "test_positive_schedule_generation_and_get_mail or test_positive_installable_errata_with_user or test_positive_generate_subscriptions_report_json or test_positive_generate_all_installed_packages_report"
```

**Review by vsedmik — APPROVED** [review]
Looks good to me. The PRT is failing because of https://issues.redhat.com/browse/SAT-30043

No need to hook it `:BlockedBy: SAT-30043` since many other cases are affected too and I expect a quick fix for that.

**Pull request merged**
