### PR TITLE
[6.12.z] - remove the all nailgun imports from UI folder

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
#### Problem Statement

We are using the direct imports from the nailgun rather than directly using from target_sat

#### Solution

Direct Imports Removed: We've cleaned up our codebase by eliminating direct imports from the Nailgun package.

Using target_sat, module_target_sat, class_target_sat: Modified the API calls and using the target_sat.api. pattern for all API calls.

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/ -m e2e

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6103
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/ -m e2e --external-logging
Test Result : = 5 failed, 5 passed, 787 deselected, 843 warnings, 3 errors in 5789.77s (1:36:29) =
```

**Comment by Gauravtalreja1** [comment]
@omkarkhatavkar Could you rebase and update this PR?

**Comment by omkarkhatavkar** [comment]
@Gauravtalreja1 @jyejare Rebase Done !

**Review by pondrejk — APPROVED** [review]

**Comment by omkarkhatavkar** [comment]
6.12.z is now absolute hence closing this

**Pull request closed without merging**
