### PR TITLE
Update settings default values and cast

### PR DESCRIPTION
**Pull request by elyezer**
Add missing default value for the screenshots path and cast to boolean
upstream option.

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK pending run for **any** test that has `skip_if_bug_open` decorator and defect for that ID is not `CLOSED`

**Comment by elyezer** [comment]
```
$ nosetests tests/foreman/cli/test_docker.py -m test_create_registry
S
----------------------------------------------------------------------
Ran 1 test in 3.027s

OK (SKIP=1)
```

**Comment by elyezer** [comment]
```
$ nosetests tests/foreman/ui/test_org.py -m test_positive_create_with_auto_gen_label
SSSSSSS
----------------------------------------------------------------------
Ran 7 tests in 104.255s

OK (SKIP=7)
```

**Comment by abalakh** [comment]
ACK

**Comment by elyezer** [comment]
@oshtaier run two tests, one for UI and other for CLI. Seems that it is now working.

**Comment by oshtaier** [comment]
Closes #2936

**Comment by sthirugn** [comment]
:+1:

**Pull request merged**
