### PR TITLE
[6.14.z] Add customer test case for BZ#2212523

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12687

Basically coverage for [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2212523) but generalized to check all content referenced in `repomd.xml` in both exports.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k test_positive_export_incremental_syncable_check_content

**Comment by vsedmik** [comment]
PRT failed coz https://github.com/SatelliteQE/robottelo/pull/12666 had merge conflict and hasn't been merged yet.

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k test_positive_export_incremental_syncable_check_content

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k test_positive_export_incremental_syncable_check_content

**Comment by vsedmik** [comment]
PRT passed (4108) after #12666 was merged.

**Review by vsedmik — APPROVED** [review]

**Review by Griffin-Sullivan — APPROVED** [review]

**Pull request merged**
