### PR TITLE
added the test coverage for bugzilla_1857176

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
This is the PR for adding the QE test coverage for cname scenarios in a capsule cerificate.

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -k 'test_positive_generate_capsule_certs_using_absolute_path' tests/foreman/

**Comment by omkarkhatavkar** [comment]
```
(env) /home/okhatavk/Satellite/robottelo (bz_1857176) $ py.test -k test_positive_generate_capsule_certs_using_absolute_path tests/foreman/ --junit-xml=sat-results.xml -o junit_suite_name=sat-result
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.6, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/okhatavk/Satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, ibutsu-1.13, cov-2.10.1, xdist-2.2.0, mock-3.5.1, reportportal-5.0.7, forked-1.3.0, picked-0.4.6
collected 5277 items / 5276 deselected / 1 skipped                                                                                                                                           

tests/foreman/sys/test_katello_certs_check.py .                                                                                                                                        [100%]

====================================================================================== warnings summary ======================================================================================
tests/foreman/sys/test_katello_certs_check.py::TestKatelloCertsCheck::test_positive_generate_capsule_certs_using_absolute_path
  tests/foreman/sys/test_katello_certs_check.py:324: PytestWarning: record_property is incompatible with junit_family 'xunit2' (use 'legacy' or 'xunit1')
    @pytest.mark.destructive

-- Docs: https://docs.pytest.org/en/stable/warnings.html
----------------------------------------------------------- generated xml file: /home/okhatavk/Satellite/robottelo/sat-results.xml -----------------------------------------------------------
============================================================ 1 passed, 1 skipped, 5276 deselected, 1 warning in 128.81s (0:02:08) ============================================================

```

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -k 'test_positive_generate_capsule_certs_using_absolute_path' tests/foreman/

**Review by devendra104 — APPROVED** [review]
ACK

**Comment by omkarkhatavkar** [comment]
Build 20 has Failed! is because of the dynaconf failure nothing related to test

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -k 'test_positive_generate_capsule_certs_using_absolute_path' tests/foreman/

**Review by mshriver — APPROVED** [review]

**Pull request merged**
