### PR TITLE
Put proper if conditions leveling for user entity in UI

### PR DESCRIPTION
**Pull request by oshtaier**

### CODE REVIEW

**Comment by rplevka** [comment]
ACK

**Comment by oshtaier** [comment]
Pick up random case to double check as full set was already tested few times:
```
nosetests tests/foreman/ui/test_user.py -m test_positive_update_firstname
.
----------------------------------------------------------------------
Ran 1 test in 54.192s

OK
```

**Comment by abalakh** [comment]
ACK

**Comment by sthirugn** [comment]
:+1:

**Pull request merged**
