### PR TITLE
Move TestAnsibleREX UI tests to Ansible module

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
### Problem Statement
Ansible-RemoteExecution tests present in REX module under TestAnsibleREX class in UI

### Solution
- Move Ansible-RemoteExecution tests present in REX module to Ansible Module in TestAnsibleREX class, to track this tests in correct component module
- Move Ansible-ConfigurationManagement tests present in Ansible to module to new TestAnsibleCfgMgmt class for consistency in CLI test module.
- And few other minor fixes.

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6284
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py --external-logging
Test Result : ==== 5 failed, 2 passed, 14 deselected, 393 warnings in 2301.16s (0:38:21) =====
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6289
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_ansible.py --external-logging
Test Result : ========= 7 passed, 14 deselected, 411 warnings in 2626.12s (0:43:46) ==========
```

**Review by shweta83 — APPROVED** [review]
LGTM

**Review by pondrejk — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6347
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py --external-logging
Test Result : = 1 failed, 7 passed, 14 deselected, 442 warnings, 1 error in 2691.49s (0:44:51) =
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6376
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py --external-logging
Test Result : ==== 1 failed, 7 passed, 14 deselected, 434 warnings in 2696.51s (0:44:56) =====
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6377
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py --external-logging
Test Result : ==== 1 failed, 7 passed, 14 deselected, 441 warnings in 2710.98s (0:45:10) =====
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6439
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_ansible.py --external-logging
Test Result : ========= 8 passed, 14 deselected, 472 warnings in 2735.18s (0:45:35) ==========
```

**Review by shubhamsg199 — APPROVED** [review]

**Pull request merged**
