### PR TITLE
Optimize API tests for sync plans (#6812)

### PR DESCRIPTION
**Pull request by swadeley**
Changes to other sync plan tests to match change made in #6823

Will take time to test one by one.

### CODE REVIEW

**Comment by swadeley** [comment]
Hello,

All tests with future_sync are failing, but I do not think its the tests that are at fault, they failed before. Waiting for feedback from s.jha.

From the git commits:

    Optimize custom_product_daily_recurrence (#6812)
  this is:  test_positive_synchronize_custom_product_daily_recurrence
 PASS

    Optimize rh_product_future_sync_date (#6812)
 this is: test_positive_synchronize_rh_product_future_sync_date
 FAIL

           Optimize custom_products_future_sync_date (#6812)       products with s,
 this is: test_positive_synchronize_custom_products_future_sync_date
 FAIL

    Optimize custom_product_future_sync_date (#6812)     product, singular, this is: test_positive_synchronize_custom_product_future_sync_date
FAIL

**Comment by swadeley** [comment]
Hello
Samir Jha suggested adding `replace(second=0, microsecond=0)` [1]. This makes the tests pass. Without that it was creating sync dates one interval further ahead than expected. Maybe that is why someone added the extra sync update step which I have now removed.

@oshtaier , is there a way I can print the API call that gets made? The API request are over SSH so I cannot use wireshark to capture them. I would like to see the API request to see if it reflects what customers would do or are told to do in docs.

Thank you

[1] https://github.com/SatelliteQE/robottelo/pull/6825/commits/61757cd93a6224084b10e5b6554e5567813c3faf

**Comment by swadeley** [comment]
I tested each test individually then ran this test on the whole test case.

robottelo]$ pytest --capture=no tests/foreman/api/test_syncplan.py::SyncPlanSynchronizeTestCase
2019-03-22 19:26:28 - conftest - DEBUG - Registering custom pytest_namespace

======================== test session starts ====================================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.6.0, pluggy-0.8.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo, inifile:
plugins: xdist-1.23.2, services-1.3.1, repeat-0.8.0, mock-1.10.0, forked-0.2, cov-2.6.0
collecting ... 2019-03-22 19:26:28 - conftest - DEBUG - BZ deselect is disabled in settings

collected 8 items

====================== 8 passed, 4 warnings in 2835.28 seconds =====================

**Comment by swadeley** [comment]
I am testing `test_positive_synchronize_custom_product_future_sync_date` some more. It seems to pass when randomly selected interval is daily or weekly, but fail when interval is hourly.

**Comment by swadeley** [comment]
Hello, sorry, ignore previous comment, that fail was a test I was running locally without the `replace(second=0, microsecond=0)` update. I have been running tests locally from one directory and against a remote server form another directory. I wanted to capture the difference in the logs.

Here is the bit from a test which does not have `replace(second=0, microsecond=0)`:

`2019-03-28 09:48:53 - nailgun.client - DEBUG - Making HTTP POST request to https://sat-6-5-qa-rhel7.localhost.example.com/katello/api/v2/organizations/9/sync_plans with options {'auth': ('admin', 'changeme'), 'verify': False, 'headers': {'content-type': 'application/json'}}, no params and data {"enabled": true, "sync_date": "2019-03-28 09:52:53", "interval": "daily", "name": "ufSlBGTTt", "organization_id": 9}.
2019-03-28 09:48:53 - nailgun.client - DEBUG - Received HTTP 200 response:   {"id":8,"organization_id":9,"name":"ufSlBGTTt","description":null,"interval":"daily","next_sync":"2019/03/29 09:52:00 +0000","created_at":"2019-03-28 09:48:53 UTC","updated_at":"2019-03-28 09:48:53 UTC","enabled":true,"foreman_tasks_recurring_logic_id":20,"cron_expression":null,"products":[],"permissions":{"view_sync_plans":true,"edit_sync_plans":true,"destroy_sync_plans":true},"sync_date":"2019/03/28 09:52:53 +0000"}`

and here with the fix:

`2019-03-28 11:07:03 - nailgun.client - DEBUG - Making HTTP POST request to https://10.37.193.7/katello/api/v2/organizations/47/sync_plans with options {'auth': ('admin', 'changeme'), 'verify': False, 'headers': {'content-type': 'application/json'}}, no params and data {"enabled": true, "sync_date": "2019-03-28 11:11:00", "interval": "daily", "name": "GZIfkiUBCUqy", "organization_id": 47}.
2019-03-28 11:07:04 - nailgun.client - DEBUG - Received HTTP 200 response:   {"id":34,"organization_id":47,"name":"GZIfkiUBCUqy","description":null,"interval":"daily","next_sync":"2019/03/28 11:11:00 +0000","created_at":"2019-03-28 11:07:04 UTC","updated_at":"2019-03-28 11:07:04 UTC","enabled":true,"foreman_tasks_recurring_logic_id":48,"cron_expression":null,"products":[],"permissions":{"view_sync_plans":true,"edit_sync_plans":true,"destroy_sync_plans":true},"sync_date":"2019/03/28 11:11:00 +0000"}`


Notice in the first the date is "29" for next sync date:
`"next_sync":"2019/03/29 09:52:00 +0000","created_at":"2019-03-28 09:48:53 UTC"`

versus in the second it is "28" as expected:

`"next_sync":"2019/03/28 11:11:00 +0000","created_at":"2019-03-28 11:07:04 UTC"`

Thank you

**Comment by JacobCallahan** [comment]
@swadeley It looks like the difference in dates is a bug. Maybe during the seconds stripping or some other conversion process, foreman thinks that the submitted time has already passed, so it is moving it along an additional 24 hours. I'd check with the dev on this one. In the meantime, squash your commits and I'm good with the merge!

**Comment by swadeley** [comment]
@JacobCallahan the change, the unwanted date, is in the HTTP response; strangely, the request looks the same looking at the logs. I lack evidence to show the developer if I cannot show the real request sent to the API, which is why I asked @oshtaier if he has any idea how to get the code to printout the call before its gets encrypted. Otherwise I have to try again with wireshark.

Thank you

**Comment by swadeley** [comment]
Hello, I now have Wireshark setup to capture the API calls. I will post the relevant POST and associated HTTP 200 responses.

**Comment by swadeley** [comment]
From Wireshark
(time is BST on my system, but test host is UTC so one hour behind)

Line 171	06:45:33.043430236	192.168.121.1	sat-6-5-qa-rhel7.localhost.example.com	HTTP	215	POST /katello/api/v2/organizations/10/sync_plans HTTP/1.1  (application/json)
`{"enabled": true, "sync_date": "2019-04-03 05:49:00", "interval": "hourly", "name": "WpDTxQQuQb", "organization_id": 10}`

Line 180 HTTP 200 OK
 `{"id":8,"organization_id":10,"name":"WpDTxQQuQb","description":null,"interval":"hourly","next_sync":"2019/04/03 05:49:00 +0000","created_at":"2019-04-03 05:45:33 UTC","updated_at":"2019-04-03 05:45:33 UTC","enabled":true,"foreman_tasks_recurring_logic_id":12,"cron_expression":null,"products":[],"permissions":{"view_sync_plans":true,"edit_sync_plans":true,"destroy_sync_plans":true},"sync_date":"2019/04/03 05:49:00 +0000"}`

In the above response I see "next_sync":"2019/04/03 05:49:00 +0000", which is the same as in the POST, as expected. Its the time plus the 4 mins delay.

Test again with this change

"+++ b/tests/foreman/api/test_syncplan.py
@@ -799,7 +799,7 @@ class SyncPlanSynchronizeTestCase(APITestCase):
         sync_plan = entities.SyncPlan(
             organization=self.org,
             enabled=True,
\-            sync_date=datetime.utcnow().replace(second=0, microsecond=0)
\+            sync_date=datetime.utcnow()
             + timedelta(seconds=delay),"

159	10:31:42.028624523	192.168.121.1	sat-6-5-qa-rhel7.localhost.example.com	HTTP	213	POST /katello/api/v2/organizations/11/sync_plans HTTP/1.1  (application/json)

`{"enabled": true, "sync_date": "2019-04-03 09:35:42", "interval": "hourly", "name": "hRcayiwQ", "organization_id": 11}`

the sync_date time is one hour in the past, but that is because is UTC, plus the 4 mins delay.

HTTP 200
  `{"id":9,"organization_id":11,"name":"hRcayiwQ","description":null,"interval":"hourly","next_sync":"2019/04/03 10:35:00 +0000","created_at":"2019-04-03 09:31:42 UTC","updated_at":"2019-04-03 09:31:42 UTC","enabled":true,"foreman_tasks_recurring_logic_id":13,"cron_expression":null,"products":[],"permissions":{"view_sync_plans":true,"edit_sync_plans":true,"destroy_sync_plans":true},"sync_date":"2019/04/03 09:35:42 +0000"}`

Why is next_sync time one hour ahead of sync_date?

**Comment by swadeley** [comment]
Hello

I spoke to the developer, he explained:
If seconds are not 00 then it skips one "interval". Foreman tasks checks at the start of every minute what tasks are *past* due to be run and then runs any tasks. But if the task has seconds, then it skips a complete interval, not one minute. This does not occur if you enter the Sync Plan in the web UI.

I raised a new bug to get this improved: 
Bug 1695733 - Future dated Sync Plans with non-zero seconds value skip the first interval

Based on the testing I have done it is now clear we do not need to reset microseconds. I can remove that.

**Comment by swadeley** [comment]
robottelo]$ pytest --capture=no tests/foreman/api/test_syncplan.py::SyncPlanSynchronizeTestCase
2019-04-03 21:48:16 - conftest - DEBUG - Registering custom pytest_namespace

======================== test session starts ===================================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.6.0, pluggy-0.8.1
shared_function enabled - OFF - scope: - storage: file
rootdir: /Downloads/robottelo, inifile:
plugins: xdist-1.23.2, services-1.3.1, repeat-0.8.0, mock-1.10.0, forked-0.2, cov-2.6.0
collecting ... 2019-04-03 21:48:17 - conftest - DEBUG - BZ deselect is disabled in settings

collected 8 items

===================== 8 passed, 4 warnings in 1924.71 seconds ========================

**Comment by swadeley** [comment]
Hello

I added an "if bz_bug_is_open(1695733)" step to the future sync tests. That we will have coverage both before and after BZ#1695733 is resolved. I can then remove all the "(second=0)" additions when time allows.
I will run the SyncPlanSynchronizeTestCase again.

**Comment by swadeley** [comment]
Hello
I tested the changes against the latest snap.
 robottelo]$ git status
On branch issue#6812-2
Your branch is up-to-date with 'origin/issue#6812-2'.

================== test session starts ============================================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.6.0, pluggy-0.8.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo, inifile:
plugins: xdist-1.23.2, services-1.3.1, repeat-0.8.0, mock-1.10.0, forked-0.2, cov-2.6.0
collecting ... 2019-04-07 08:36:17 - conftest - DEBUG - BZ deselect is disabled in settings

collected 8 items                                                                                                                                            

tests/foreman/api/test_syncplan.py ........                                                                                                            [100%]

================ 8 passed, 6 warnings in 2836.27 seconds ===========================

**Comment by swadeley** [comment]
Hello @oshtaier 

I have increased the delay to 8 minute, which is how long it was when it had the extra 4 minute update step after 4 about minutes (depending on the load).

robottelo]$ pytest --show-capture=no tests/foreman/api/test_syncplan.py::SyncPlanSynchronizeTestCase
====================== test session starts ======================================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.6.0, pluggy-0.8.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo, inifile:
plugins: xdist-1.23.2, services-1.3.1, repeat-0.8.0, mock-1.10.0, forked-0.2, cov-2.6.0
collecting ... 2019-04-10 10:23:19 - conftest - DEBUG - BZ deselect is disabled in settings

collected 8 items                                                                                       

tests/foreman/api/test_syncplan.py ........                                                       [100%]

=================== 8 passed, 6 warnings in 4214.58 seconds ======================

**Comment by swadeley** [comment]
Hello

> Hello @oshtaier
> 
> I have increased the delay to 8 minute, which is how long it was when it had the extra 4 minute update step after 4 about minutes (depending on the load).
> 
I decided to revert that, the API and CLI tests are not failing due to a slow test setup speed, its only the ui_airgun tests that fail due to being too slow to setup that they miss the sync event.

**Comment by swadeley** [comment]
robottelo]$ pytest --show-capture=no tests/foreman/api/test_syncplan.py::SyncPlanSynchronizeTestCase
============================ test session starts ====================================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.6.0, pluggy-0.8.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /Downloads/robottelo, inifile:
plugins: xdist-1.23.2, services-1.3.1, repeat-0.8.0, mock-1.10.0, forked-0.2, cov-2.6.0
collecting ... 2019-04-18 17:17:35 - conftest - DEBUG - BZ deselect is disabled in settings

collected 8 items                                                                                                                                            

tests/foreman/api/test_syncplan.py ........                                                                                                            [100%]

================== 8 passed, 6 warnings in 1964.87 seconds ==========================

**Comment by swadeley** [comment]
thank you @pondrejk

**Pull request merged**
