### PR TITLE
Update travis.yml config

### PR DESCRIPTION
**Pull request by elyezer**
Migrate from legacy to container-based Travis infrastructure.

More info: http://docs.travis-ci.com/user/migrating-from-legacy/

### CODE REVIEW

**Comment by Ichimonji10** [comment]
ACK

Awesome!

**Comment by sthirugn** [comment]
ACK

**Comment by sghai** [comment]
:+1:

**Comment by oshtaier** [comment]
I can see 'This job is running on container-based infrastructure' in Travis logs :). :+1:

**Pull request merged**
