### PR TITLE
Fix constant for cloudinit image in Azure

### PR DESCRIPTION
**Pull request by shubhamsg199**
### Problem Statement
The existing cloudinit image which we were using in Azure has been changed by Azure , hence the tests were failing because of it.

### Solution
Replace the constant with the correct image name.

### CODE REVIEW

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_computeresource_azurerm.py tests/foreman/cli/test_computeresource_azurerm.py

**Review by jameerpathan111 — APPROVED** [review]

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7062
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_computeresource_azurerm.py tests/foreman/cli/test_computeresource_azurerm.py --external-logging
Test Result : = 1 failed, 19 passed, 1 deselected, 244 warnings, 6 errors in 3086.99s (0:51:26) =
```

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_computeresource_azurerm.py tests/foreman/cli/test_computeresource_azurerm.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7068
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_computeresource_azurerm.py tests/foreman/cli/test_computeresource_azurerm.py --external-logging
Test Result : ==== 3 failed, 23 passed, 1 deselected, 295 warnings in 4225.47s (1:10:25) =====
```

**Pull request merged**
