### PR TITLE
Update customer scenarios script to new BZ auth

### PR DESCRIPTION
**Pull request by JacobCallahan**
This change brings the script up-to-date with the latest authorization method accepted by the Bugzilla api.

### CODE REVIEW

**Review by mshriver — APPROVED** [review]

**Review by Griffin-Sullivan — APPROVED** [review]

**Review by swadeley — APPROVED** [review]
ACK

**Review by ColeHiggins2 — APPROVED** [review]
ACK

**Comment by bherrin3** [comment]
ACK!

**Review by bherrin3 — APPROVED** [review]

**Review by pondrejk — APPROVED** [review]

**Comment by mshriver** [comment]
@pondrejk ends the chain! We were wondering how many approvals it would get before merge.

**Pull request merged**
