### PR TITLE
[DONOTMERGE] Renamed tests for cli/test_system_registration.py.

### PR DESCRIPTION
**Pull request by omaciel**
Test case naming follows #3038 conventions.

### CODE REVIEW

**Comment by omaciel** [comment]
```shell
(robottelo)┌[omaciel☮Ogs-MacBook-Pro.local]-(~/hacking/robottelo)-[git://rename-tests-cli-system-registration ✔]-
└> py.test -v tests/foreman/cli/test_system_registration.py --collect-only
================================================================= test session starts ==================================================================
platform darwin -- Python 2.7.10, pytest-2.8.3, py-1.4.31, pluggy-0.3.1 -- /Users/omaciel/.virtualenvs/robottelo/bin/python
cachedir: .cache
rootdir: /Users/omaciel/hacking/robottelo, inifile:
collected 8 items
<Module 'tests/foreman/cli/test_system_registration.py'>
  <UnitTestCase 'SystemRegistrationTestCase'>
    <TestCaseFunction 'test_negative_pull_content'>
    <TestCaseFunction 'test_negative_register'>
    <TestCaseFunction 'test_positive_deregister'>
    <TestCaseFunction 'test_positive_list'>
    <TestCaseFunction 'test_positive_pull_content'>
    <TestCaseFunction 'test_positive_register_no_ak'>
    <TestCaseFunction 'test_positive_register_with_ak'>
    <TestCaseFunction 'test_positive_rpm_install'>

===================================================================  in 0.30 seconds ===================================================================
```

**Comment by sghai** [comment]
I think we should remove this test module as `system_registration` is already merged/renamed with `content-host`. If test are valid, we just need to rename the `system` keyword to `content-host` and move it to `test_contenthost.py` module.

**Comment by oshtaier** [comment]
+100 for @sghai comment. However it can be a little bit out of scope for current task

**Comment by omaciel** [comment]
@sthirugn please use these changes and merge them into `cli/test_contenthost.py`? Then `git rm` this module (and update docs)

**Comment by sthirugn** [comment]
:+1:

**Comment by sthirugn** [comment]
this PR will be closed once https://github.com/SatelliteQE/robottelo/pull/3173 is merge and test_system_registration.py is removed.

**Comment by sthirugn** [comment]
This is taken care in https://github.com/SatelliteQE/robottelo/pull/3174

**Pull request closed without merging**
