### PR TITLE
Added support to provision using separate target_image and hostname

### PR DESCRIPTION
**Pull request by kbidarkar**
a) This is required to provision a capsule for testcases which
   requires DNS resolution both via sat6 and the provisioned vm's.
b) With this change we would need to provide both hostname and
   domain, while creating the vm instance.
c) Then we can use DDNS so that sat6 too can resolve the VM's
   on the ginger host.

### CODE REVIEW

**Comment by ldjebran** [comment]
@kbidarkar, as understood for capsule host we have to supply hostname, domain, and target_image?

**Comment by rochacbruno** [comment]
@kbidarkar this one is only pending @abalakh comments

**Comment by kbidarkar** [comment]
Sorry guys, will work on this ASAP and provide some test results.

**Comment by kbidarkar** [comment]
This took some time today for me at my end as was running `robottelo` tests after a long time and also for the first time after a fresh OS install. For now tested the `Backward Compatibiltiy` and it works fine for the testcase `test_positive_install_package`.  The one failure seen below looks to be something other issue and is related to `No Group named birds exists' as seen from the below pic.

no_group_birds_exist


1) Backward compatibility: `Test results for any existing VM test, just to make sure nothing was accidentally broken`

```
(robottelo) [kbidarka@dhcp223-55 robottelo]$ git branch 
  62z
  master
* update-vm_create
(robottelo) [kbidarka@dhcp223-55 robottelo]$ nosetests -m test_positive_install_package tests.foreman.ui.test_contenthost
.F
======================================================================
FAIL: Install a package group to a host remotely
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kbidarka/git_world/robottelo/tests/foreman/ui/test_contenthost.py", line 181, in test_positive_install_package_group
    self.assertEqual(result, 'success')
AssertionError: u'warning' != 'success'

```

Will look into 2) and 3) soon and update it here.

**Comment by kbidarkar** [comment]
Regarding 2) ,  `Console output for creating the VM with new attributes.`
As this has a lot of internal stuff, here is the link to pastebin, http://pastebin.test.redhat.com/452045

**Comment by kbidarkar** [comment]
3) For this I really need to dig into, writing the unit-test for this, can we please plan this for some later time, need to look at other stuff on priority.

**Comment by kbidarkar** [comment]
Regarding the package-group failure, we already have an issue for it and more details can be found from this issue/discussion here, https://github.com/SatelliteQE/robottelo/issues/3642#issuecomment-273393816

Currently this PR is ready for a final review and merge, I just found a small typo, which I am fixing now.

```
diff --git a/robottelo/vm.py b/robottelo/vm.py
index ad094b2..14e159c 100644
--- a/robottelo/vm.py
+++ b/robottelo/vm.py
@@ -125,7 +125,7 @@ class VirtualMachine(object):
         else:
             command_args.append('-d {domain}')
 
-        if self.hostname and self.domain:
+        if self.hostname and self._domain:
             target_image = u'{0}'.format(self._target_image)
         else:
             target_image = u'{0}.{1}'.format(self._target_image, self._domain)
```

**Comment by abalakh** [comment]
@kbidarkar thank you! That's why i asked for results - to uncover such typos if any :)

**Comment by abalakh** [comment]
@kbidarkar mind rebasing before merging?

**Comment by kbidarkar** [comment]
@abalakh, yeah sure , will rebase

**Pull request merged**
