### PR TITLE
Fixed BZ workflow

### PR DESCRIPTION
**Pull request by renzon**
Check discussion #4263 

Using bellow code to test:
```python
if __name__ == '__main__':
    settings.configure()
    for bug in [1351040, 1416690]:
        print(bug, bz_bug_is_open(bug))
```

By the time of this run 1351040 BZ has status VERIFIED and "sat-6.3.0" flag set to "+". On the other hand 1416690 BZ, clone of previous one, has status POST and "sat-6.2.z" flag set to "+". 

So testing with a bz and its clone on sat 6.2: should return True (bz is open) for both BZs:

```console
/home/renzo/PycharmProjects/venvs/robottelo/bin/python /home/renzo/PycharmProjects/robottelo/robottelo/decorators/__init__.py
2017-04-24 10:00:19 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f66745acb10
2017-04-24 10:00:19 - robottelo.ssh - INFO - >>> rpm -q satellite
2017-04-24 10:00:20 - robottelo.ssh - INFO - <<< stdout
satellite-6.2.9-2.0.el7sat.noarch

2017-04-24 10:00:20 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f66745acb10
2017-04-24 10:00:20 - robottelo.host_info - DEBUG - Host Satellite version: 6.2
(1351040, True)
(1416690, True)

Process finished with exit code 0
```

For 6.3 both should return False:

```console
/home/renzo/PycharmProjects/venvs/robottelo/bin/python /home/renzo/PycharmProjects/robottelo/robottelo/decorators/__init__.py
2017-04-24 10:06:13 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7fbda4024b10
2017-04-24 10:06:13 - robottelo.ssh - INFO - >>> rpm -q satellite
2017-04-24 10:06:14 - robottelo.ssh - INFO - <<< stdout
satellite-6.3.0-11.1.beta.el7sat.noarch

2017-04-24 10:06:14 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7fbda4024b10
2017-04-24 10:06:14 - robottelo.host_info - DEBUG - Host Satellite version: 6.3
(1351040, False)
(1416690, False)

Process finished with exit code 0
```

### CODE REVIEW

**Comment by rochacbruno** [comment]
@renzon I included comments in #4263 https://github.com/SatelliteQE/robottelo/issues/4263#issuecomment-296907692

**Comment by ldjebran** [comment]
@renzon as understand, this is a work in progress, perhaps must tag it as DO NOT MERGE.

**Comment by renzon** [comment]
@rochacbruno addressed your comment.

@lpramuk @rochacbruno can you guys review this PR?

**Comment by rochacbruno** [comment]
Considering this on review:

bz workflow - page 1

**Comment by JacobCallahan** [comment]
The process outlined above looks good to me.

**Comment by rochacbruno** [comment]
@lpramuk @rplevka @sghai we are in need of one more ACK to merge this.

**Comment by lpramuk** [comment]
I got 6.3.0+ regression filed in NEW state and running automation for 6.2 
What happens?
In accordance with diagram it would wrongly skip a test

**Comment by renzon** [comment]
If it is a regression pointed by an already existing test and you want let it failing you could not decorate it. I made the diagram thinking of new bugs possibly not having coverage to start with. Lets chat on irc about it ;)

**Pull request merged**
