### PR TITLE
Update Repos and Reposets for lastest sat6.1 GA manifest.

### PR DESCRIPTION
**Pull request by kbidarkar**
We need the latest manifest for our automation, once we have that in place this PR can be merged.

### CODE REVIEW

**Comment by kbidarkar** [comment]
[Do Not Merge], but this PR is ready for review and we need to wait till the latest manifests are in place.

**Comment by oshtaier** [comment]
Please, re-run few tests that using mentioned manifests and put results here before merge

**Comment by Ichimonji10** [comment]
The changes look sane. Go ahead and drop the "[DO NOT MERGE]" prefix whenever the latest manifest is available.

**Comment by kbidarkar** [comment]
Frankly speaking it's not required, it's just a minor change. 
Still as you have asked, let me run just 1 single test which uses it and update it here. If there are any other failures, let automation catch it later as there are many testcases I believe.

The change is because, we moved from "sat6 beta" to "sat6.1" so this is expected change. :)

**Comment by oshtaier** [comment]
That is minor change that can have major impact, so thanks for understanding

**Comment by kbidarkar** [comment]
@elyezer , I have updated the manifest on sesame, which was created on 20150813 and has the necessary sat6.1 GA changes. Now I will test it and update the results.

**Comment by kbidarkar** [comment]
The results for API tests are below:
```
(robottelo)[kbidarka@dhcp201-208 robottelo]$ nosetests -m test_cv_associate_rh tests.foreman.api.test_contentview
..
----------------------------------------------------------------------
Ran 2 tests in 303.809s

OK
```

**Comment by kbidarkar** [comment]
The manifest_latest.zip file now points to manifest-20150813.zip which was created post sat6.1 GA

**Comment by Ichimonji10** [comment]
ACK

**Comment by oshtaier** [comment]
ACK. Please, check next run on Jenkins when it will be triggered

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
