### PR TITLE
RHAIManage model page

### PR DESCRIPTION
**Pull request by quarckster**
A model page for Red Hat Insights Manage.

### CODE REVIEW

**Comment by quarckster** [comment]
@oshtaier please review

**Comment by omaciel** [comment]
@oshtaier @abalakh could you review/merge this for us?

**Comment by oshtaier** [comment]
@omaciel I saw that PR, but not sure whether it make any sense to submit old UI code to master as we do not support and will never support it in future

**Comment by omaciel** [comment]
@oshtaier perhaps a good opportunity to let people know about AirGun and encourage these changes to go there? Hint, hint :)

**Comment by quarckster** [comment]
@omaciel @oshtaier @abalakh  I would like to use Airgun as well, but the problem is insights tests need to cover some matrix of Sat versions and 6.3 is one of them

**Comment by oshtaier** [comment]
ACK pending
- test results
- travis passing

**Comment by quarckster** [comment]
Tests results:
```
==================================test session starts=====================================
platform linux -- Python 3.6.5, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /home/dmisharo/insights_env/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.6.5', 'Platform': 'Linux-4.12.14-lp150.12.4-default-x86_64-with-glibc2.3.4', 'Packages': {'pytest': '3.6.1', 'py': '1.5.4', 'pluggy': '0.6.0'}, 'Plugins': {'wait-for': '1.0.9', 'xdist': '1.22.2', 'services': '1.2.1', 'pudb': '0.6', 'mock': '1.6.3', 'metadata': '1.7.0', 'html': '1.19.0', 'forked': '0.2', 'cov': '2.5.1'}, 'JAVA_HOME': '/usr/lib64/jvm/jre'}
rootdir: /home/dmisharo/insights_env/src/robottelo, inifile:
plugins: wait-for-1.0.9, xdist-1.22.2, services-1.2.1, pudb-0.6, mock-1.6.3, metadata-1.7.0, html-1.19.0, forked-0.2, cov-2.5.1
collected 3 items                                                                                                                                                                                                                           

tests/robottelo/ui/test_rhai.py::RHAITestCase::test_rhai_manage_insights_connection PASSED                                                                                                                                            [ 33%]
tests/robottelo/ui/test_rhai.py::RHAITestCase::test_rhai_manage_service PASSED                                                                                                                                                        [ 66%]
tests/robottelo/ui/test_rhai.py::RHAITestCase::test_rhai_navigation PASSED                                                                                                                                                            [100%]

========================= 3 passed in 86.31 seconds ================================
```

**Pull request merged**
