### PR TITLE
recording ui-session-id for report portal logging

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
### Problem Statement

Currently, We are unable to retrieve the Selenium UI session ID from the Airgun GitHub repository and integrate it into our automation testing tool, Robottelo. This session ID is crucial because during the test recording process, videos are generated by the Selenium Airgun repository, and these videos are associated with specific UI session IDs. To improve our testing workflow and enhance the usability of our test results, we need to establish a mechanism that allows us to access this session ID within Robottelo and incorporate it into the JUnit XML results. By doing so, we can leverage the power of the Report Portal logging system, enabling other team members to easily locate and access the video links associated with each test result for comprehensive test result review.

### Solution

- The ui_session_record_property fixture is now function-scoped to ensure it is created once per test function.
- The fixture uses record_property to load properties like video_link and session_id.
- The ui_session_record_property fixture returns a Satellite instance with an associated AirgunSession instance, including the updated ui_session_id attribute.

#### Airgun PR
https://github.com/SatelliteQE/airgun/pull/1038

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -n 2 tests/foreman/ui/test_settings.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -n 2 tests/foreman/ui/test_settings.py
pod_resources_size: large

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -n 2 tests/foreman/ui/test_settings.py
pod_resources_size: large

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -n 2 tests/foreman/ui/test_settings.py
pod_resources_size: large

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -n 2 tests/foreman/ui/test_settings.py
pod_resources_size: large
airgun: 1038

**Comment by omkarkhatavkar** [comment]
Although PRT failed for UI tests that are unrelated, we are able to get the video urls properties and session-id's 

image

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -n 2 tests/foreman/ui/test_acs.py
pod_resources_size: extra_large
airgun: 1038

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_host.py
pod_resources_size: extra_large
airgun: 1038

**Comment by omkarkhatavkar** [comment]
Although PRT failed for UI tests that are unrelated, we are able to get the video urls properties and session-id's 

image

**Review by JacobCallahan — APPROVED** [review]

**Comment by omkarkhatavkar** [comment]
> Looks Great!
> 
> BTW I would incline towards creating pytest plugin out of it rather than having conftest file with same contents at each sub-directory (like ui, destructor you are doing). In plugin you can choose to filter the path for the tests and then record the property for ui session.
> 
> With this pytest plugin, we can open it in future for everyone.

For now, I'm moving this to the `tests/foreman/` level. I'm currently trying to avoid a plugin as it can not be run as a hook because it requires a `record_property` function scope fixture.

**Review by JacobCallahan — APPROVED** [review]

**Review by jyejare — APPROVED** [review]

**Pull request merged**
