### PR TITLE
Fixed Satellite Installer Options

### LINKED ISSUE #5745: Change on installer options - tests.foreman.installer.test_installer.InstallerParamsTestCase.test_installer_options_and_flags
Error Message
AssertionError: Items in the first set but not the second: u'--certs-server-ca-name' u'--certs-org-unit' u'--foreman-loggers' u'-d' u'--katello-num-pulp-workers' u'--certs-org' u'--katello-user-groups' u'--foreman-version' u'--foreman-ipa-manage-sssd' u'--foreman-server-ssl-cert' u'--foreman-repo' u'--foreman-ssl' u'--foreman-db-sslmode' u'--certs-ca-common-name' u'--foreman-db-password' u'--foreman-passenger-interface' u'--capsule-parent-fqdn' u'--katello-oauth-secret' u'--foreman-vhost-priority' u'--foreman-oauth-map-users' u'--certs-ssl-build-dir' u'--foreman-oauth-consumer-secret' u'--foreman-http-keytab' u'--foreman-server-ssl-port' u'--foreman-db-host' u'--certs-user' u'--foreman-websockets-ssl-key' u'--foreman-unattended' u'--foreman-server-port' u'--foreman-db-username' u'--foreman-db-port' u'--foreman-authentication' u'--certs-generate' u'--foreman-db-adapter' u'--foreman-websockets-ssl-cert' u'--foreman-configure-epel-repo' u'--foreman-manage-user' u'--foreman-keepalive-timeout' u'--certs-default-ca-name' u'--foreman-websockets-encrypt' u'--certs-deploy' u'--foreman-passenger-min-instances' u'--foreman-selinux' u'--foreman-plugin-version' u'--foreman-passenger-prestart' u'--foreman-server-ssl-key' u'--katello-cdn-ssl-version' u'--foreman-puppet-home' u'--katello-log-dir' u'--foreman-passenger-start-timeout' u'--capsule-enable-ostree' u'--certs-city' u'--foreman-puppet-ssldir' u'--katello-package-names' u'--foreman-group' u'--foreman-db-pool' u'--certs-state' u'--foreman-passenger' u'--foreman-db-database' u'--foreman-keepalive' u'--foreman-server-ssl-certs-dir' u'--foreman-serveraliases' u'--foreman-pam-service' u'--foreman-passenger-ruby-package' u'--foreman-servername' u'--certs-pki-dir' u'--katello-group' u'--foreman-client-ssl-ca' u'--foreman-server-ssl-chain' u'--foreman-user-groups' u'--foreman-configure-scl-repo' u'--foreman-max-keepalive-requests' u'--foreman-rails-env' u'--certs-ca-expiration' u'--foreman-logging-level' u'--katello-user' u'--foreman-oauth-consumer-key' u'--foreman-client-ssl-key' u'--foreman-email-conf' u'--certs-regenerate-ca' u'--foreman-foreman-url' u'--capsule-certs-tar' u'--foreman-use-vhost' u'--foreman-email-source' u'--foreman-custom-repo' u'--katello-config-dir' u'--[no-]enable-capsule' u'--certs-expiration' u'--foreman-passenger-ruby' u'--certs-country' u'--certs-group' u'--foreman-server-ssl-ca' u'--foreman-app-root' u'--capsule-puppet-ca-proxy' u'--capsule-puppet-server-implementation' u'--katello-max-keep-alive' u'--katello-oauth-key' u'--katello-post-sync-token' u'--foreman-oauth-active' u'--foreman-client-ssl-cert' u'--foreman-gpgcheck' u'--certs-regenerate' u'--foreman-plugin-prefix' u'--foreman-user' u'--foreman-server-ssl-crl' u'--capsule-puppet' u'--certs-log-dir' Items in the second set but not the first: u'--puppet-syslogfacility' u'--puppet-ca-server' u'--puppet-hiera-config' u'--puppet-autosign' u'--puppet-manage-packages' u'--puppet-cron-cmd' u'--foreman-proxy-use-sudoers' u'--foreman-proxy-realm-split-config-files' u'--certs-reset' u'--puppet-ca-crl-filepath' u'--foreman-compute-libvirt-version' u'--foreman-compute-gce-version' u'--puppet-use-srv-records' u'--foreman-compute-rackspace-version' u'--foreman-compute-vmware-version' u'--puppet-module-repository' u'--puppet-splay' u'--puppet-runmode' u'--puppet-logdir' u'--puppet-unavailable-runmodes' u'--[no-]enable-foreman-compute-vmware' u'--[no-]enable-foreman-plugin-docker' u'--[no-]enable-foreman-compute-openstack' u'--[no-]enable-foreman-plugin-templates' u'--foreman-cli-foreman-url' u'--puppet-rundir' u'--[no-]enable-foreman-plugin-hooks' u'--foreman-proxy-puppet-api-timeout' u'--puppet-srv-domain' u'--[no-]enable-foreman-compute-libvirt' u'--puppet-configtimeout' u'--[no-]parser-cache' u'--foreman-proxy-content-certs-tar' u'--puppet-systemd-cmd' u'--puppet-runinterval' u'--puppet-dir' u'--foreman-proxy-dhcp-pxeserver' u'--puppet-autosign-content' u'--foreman-proxy-plugin-remote-execution-ssh-install-key' u'--puppet-group' u'--disable-resolve-mismatches' u'--puppet-classfile' u'--foreman-cli-username' u'--puppet-dns-alt-names' u'--foreman-proxy-content-enable-ostree' u'--foreman-compute-ovirt-version' u'--puppet-ssldir' u'--puppet-listen-to' u'--foreman-proxy-freeipa-config' u'--[no-]enable-foreman-compute-ec2' u'--foreman-proxy-content-parent-fqdn' u'--puppet-show-diff' u'--foreman-plugin-tasks-cron-line' u'--puppet-pluginfactsource' u'--puppet-auth-template' u'--[no-]enable-foreman-compute-gce' u'--[no-]enable-foreman-compute-ovirt' u'--katello-pulp-max-speed' u'--puppet-listen' u'--puppet-vardir' u'--puppet-additional-settings' u'--[no-]enable-foreman-cli' u'--foreman-compute-ec2-version' u'--puppet-pluginsource' u'--puppet-user' u'--puppet-autosign-mode' u'--puppet-port' u'--[no-]enable-foreman-compute-rackspace' u'--puppet-version' u'--foreman-plugin-tasks-automatic-cleanup' u'--puppet-main-template' u'--puppet-package-provider' u'--[no-]enable-puppet' u'--puppet-autosign-entries' u'--puppet-splaylimit' u'--foreman-proxy-groups' u'--foreman-compute-openstack-version' u'--[no-]enable-foreman-proxy-content' u'--puppet-ca-port' u'--puppet-sharedir' u'--puppet-codedir' u'--foreman-cli-password' u'--foreman-proxy-plugin-remote-execution-ssh-ssh-kerberos-auth' u'--puppet-package-source' u'--certs-cname' u'--puppet-pluginsync' u'--puppet-usecacheonfailure' u'--foreman-proxy-dhcp-manage-acls'

### PR DESCRIPTION
**Pull request by renzon**
close #5745

Test Result:

```console

(robottelo) [renzo@note robottelo]$ pytest tests/foreman/installer/test_installer.py -k "test_installer_options_and_flags"
=============================================== test session starts ===============================================
platform linux2 -- Python 2.7.14, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/renzo/PycharmProjects/robottelo, inifile:
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.3, cov-2.4.0
collected 4 items                                                                                                 
2018-01-03 16:40:33 - conftest - DEBUG - BZ deselect is disabled in settings


tests/foreman/installer/test_installer.py .                                                                 [100%]

=============================================== 3 tests deselected ================================================
===================================== 1 passed, 3 deselected in 11.97 seconds ====================================
```

### CODE REVIEW

**Comment by renzon** [comment]
@abalakh 

1. Before only install help was used. So the diff we could able to check is related to this command. I am going to create a branch if this diff and discuss if dev. I am going to mark this PR with DO NOT MERGE until I get answers. In fact I have refactored the test case to identify what have been removed/added now so it will not be a big deal.

2. It was generated automatically and that is the reason I haven't taken a look on it. But nothing prevent us from sorting and proper formatting it. So I have done that, ty for the very good observation ;)

**Comment by renzon** [comment]
BTW 1070 option seems a overloaded cli to me. Probably it should be refactored on different commands. Most of times there is a certain action with some related options. Ex: capsule cert generation. You use the installer but with a small sub set of options. What you guys think? Maybe it is already addressed and I am not aware of it @cswiii @omaciel @rochacbruno @ldjebran @abalakh ?

**Comment by oshtaier** [comment]
@renzon Anything planned to be fixed here?

**Comment by renzon** [comment]
@oshtaier There is still an ongoing conversation with devs to check the option since the amount is huge. I am going to nag them on mail list again ;)

**Comment by ldjebran** [comment]
@abalakh have you any comment?

**Pull request merged**
