### PR TITLE
Update case as Last Checkin Time is no longer UTC time

### PR DESCRIPTION
**Pull request by hkx303**
**Description**
Update case as Last Checkin Time is no longer UTC time

**Test Result**
```
(venv) [hkx303@kuhuang virtwho]$ pytest test_ui_virtwho.py::test_positive_last_checkin_status
===================================== test session starts ======================================
platform linux -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/hkx303/Documents/CI/robottelo/robottelo
plugins: services-1.3.1, forked-1.0.2, mock-1.10.4, cov-2.7.1, xdist-1.29.0
collecting ... 2019-11-19 07:26:28 - conftest - DEBUG - Collected 1 test cases

test_ui_virtwho.py 

============================ 1 failed, 3 warnings in 256.88 seconds ============================
```

All steps pass except the last step(Known bug):
```
            session.virtwho_configure.delete(name)
>           assert not session.virtwho_configure.search(name)

test_ui_virtwho.py:731: 
```

### CODE REVIEW

**Comment by hkx303** [comment]
Raised a Bugzilla to track this
[Bug 1774881](https://bugzilla.redhat.com/show_bug.cgi?id=1774881) - Last Checkin Time from Content Hosts Page is no longer UTC time

**Comment by hkx303** [comment]
This bug is Devel ACK, but I will ask them as I think it is more reasonable now

**Comment by hkx303** [comment]
As https://bugzilla.redhat.com/show_bug.cgi?id=1774881#c5 described:
The time should've either followed the user's set time zone or the browser's "timezone" session cookie, which it does now.

Recently, I found that the result we got through [1] is UTC time, but it still appears as the user's time zone on the UI

[1]
https://github.com/SatelliteQE/robottelo/blob/49abcf07c142de477dde01345baa662b2424a8c4/tests/foreman/virtwho/test_ui_virtwho.py#L726

**Comment by hkx303** [comment]
As https://github.com/SatelliteQE/robottelo/pull/7495#issuecomment-562421093 mentioned, regarding the checkin_time, what we get is different from its displayed in UI, any ideas? Thanks @mirekdlugosz

**Comment by mirekdlugosz** [comment]
@hkx303 sorry, I'm not sure if I understand what you mean.

From what I understand, all times should follow local browser time zone. This is what your PR in current form checks.

Is there some other time in the workflow that displays UTC instead of local?
Or do you mean we should remove "DO NOT MERGE" label and get it merged?

**Comment by hkx303** [comment]
Sorry to make you confused.
You are right, all times should follow local browser time zone now.
Our CI can pass this case because the browser time zone for our remote browser is UTC time now.
And, I also would like to request to remove the "DO NOT MERGE" label and get it merged.
Thanks.

**Comment by hkx303** [comment]
**New Test Result**
(venv) [hkx303@kuhuang virtwho]$ pytest test_ui_virtwho.py::test_positive_last_checkin_status
============================== test session starts ===============================
platform linux -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/hkx303/Documents/CI/robottelo/robottelo
plugins: services-1.3.1, forked-1.0.2, mock-1.10.4, cov-2.7.1, xdist-1.29.0
collecting ... 2019-12-09 08:13:08 - conftest - DEBUG - Collected 1 test cases

collected 1 item                                                                 

test_ui_virtwho.py .                                                       [100%]

===================== 1 passed, 3 warnings in 278.25 seconds =====================

**Comment by mirekdlugosz** [comment]
@hkx303 label removed, for merge we need Tier2 ack.
Thanks for your work

**Comment by hkx303** [comment]
Thank you guys

**Pull request merged**
