### PR TITLE
[6.15.z] Move ansible API tests to Ansible-Cfgmgmt and REX classes

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14626

### Problem Statement
Ansible tests are mixed in API ansible module, which need to be consistent as CLI/UI module

### Solution
Move Ansible API tests to Ansible-ConfigurationManagement and Ansible-RemoteExecution classes, And few other minor fixes.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_ansible.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6321
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_ansible.py --external-logging
Test Result : =========== 12 passed, 1330 warnings, 1 error in 5883.20s (1:38:03) ============
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6325
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_ansible.py --external-logging
Test Result : =========== 12 passed, 1228 warnings, 1 error in 5335.51s (1:28:55) ============
```

**Comment by Gauravtalreja1** [comment]
PRT looks due to an intermittent issue, so I think this PR is ready for review/merge

**Comment by omkarkhatavkar** [comment]
both the time the single test `tests.foreman.api.test_ansible.TestAnsibleCfgMgmt.test_positive_read_facts_with_filter[rhel8]` is getting failed same reason 
``` {
  "error": {"message":"PG::ForeignKeyViolation: ERROR:  update or delete on table \"hosts\" violates foreign key constraint \"fact_values_host_id_fk\" on table \"fact_values\"\nDETAIL:  Key (id)=(6) is still referenced from table \"fact_values\".\n"}
}
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_ansible.py::TestAnsibleCfgMgmt

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6444
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_ansible.py::TestAnsibleCfgMgmt --external-logging
Test Result : ================= 5 passed, 301 warnings in 1508.93s (0:25:08) =================
```

**Pull request merged**
