### PR TITLE
[Cherry-pick 6.4.z ] updated env id as per ak env

### LINKED ISSUE #6639: Updated env_id as per ak_env
Error Message

AssertionError: 1 != 3

Stacktrace

self = <tests.upgrades.test_capsule.Scenario_capsule_sync testMethod=test_pre_user_scenario_capsule_sync>

    @pre_upgrade
    def test_pre_user_scenario_capsule_sync(self):
        """Pre-upgrade scenario that creates and sync repository with
        rpm in satellite which will be synced in post upgrade scenario.
    
    
        :id: preupgrade-eb8970fa-98cc-4a99-99fb-1c12c4e319c9
    
        :steps:
            1. Before Satellite upgrade, Sync a repo/rpm in satellite
    
        :expectedresults: The repo/rpm should be synced to satellite
    
         """
        ak = entities.ActivationKey(organization=self.org_id).search(
            query={'search': 'name={}'.format(self.activation_key)})[0]
        ak_env = ak.environment.read()
        product = entities.Product(
            name=self.prod_name, organization=self.org_id).create()
        self.create_repo()
        repo = entities.Repository(
            product=product.id, name=self.repo_name,
            url=self.repo_url).create()
        repo.sync()
        content_view = entities.ContentView(
            name=self.cv_name, organization=self.org_id).create()
        content_view.repository = [repo]
        content_view = content_view.update(['repository'])
        content_view.publish()
        promote(content_view.read().version[0], ak_env.id)
>       self.assertEqual(content_view.read().environment[0].id, ak_env.id)
E       AssertionError: 1 != 3

tests/upgrades/test_capsule.py:101: AssertionError

### PR DESCRIPTION
**Pull request by vijay8451**
- Cherry-pick of #6640
- Fixed #6639

### CODE REVIEW

**Comment by oshtaier** [comment]
Does that code work on 6.4?

**Comment by oshtaier** [comment]
I will definitely not ask to run it on 6.3, but is there any chance to run it on 6.4?

**Comment by jyejare** [comment]
ACK pending @oshtaier comment

**Comment by vijay8451** [comment]
@oshtaier Thanks for the highlight this one, Yes same code should work during upgrade.
The new change is cherry-pick due to a known issue found on recently upgrade i.e. #6639 
and in order to avoid the same for 6.4/3 cherry-picked for it.

Also whenever a new release/snap push for 6.4.x then same test would run as a part of upgrade too.

Please let me know you view.

**Comment by oshtaier** [comment]
Yes, I understand your point, but it is really nice to run code before merge, even if we can catch any issue later during runs

**Pull request merged**
