### PR TITLE
CLI/Import - tests for importing AKs

### PR DESCRIPTION
**Pull request by lpramuk**
CLI/Import - AKs import

+ added default positive test exersizing import of activation keys

### CODE REVIEW

**Comment by rplevka** [comment]
the code looks good.
Could you paste the nosetests output for the unit?

**Comment by sthirugn** [comment]
ACK pending test results.

**Comment by lpramuk** [comment]
```
$ nosetests tests.foreman.cli.test_import:TestImport.test_import_ak_default
.
----------------------------------------------------------------------
Ran 1 test in 337.745s

OK
```

**Comment by lpramuk** [comment]
I pasted the nosetests output to resolve pending comments
So we have too ACKs here (roman, suresh)

**Comment by rplevka** [comment]
postACK :)

**Pull request merged**
