### PR TITLE
Do not delete as part of teardown

### PR DESCRIPTION
**Pull request by swadeley**
Unecessary deletions create load on Satellite
    Deleting org can cause race conditions

### CODE REVIEW

**Review by devendra104 — COMMENTED** [review]
@swadeley One fixture is used by the customer upgrade scenarios and another is used by the "run_in_one_thread" marker test case, I don't think it will create any load or race condition.

**Comment by swadeley** [comment]
> @swadeley One fixture is used by the customer upgrade scenarios and another is used by the "run_in_one_thread" marker test case, I don't think it will create any load or race condition.

@devendra104 If the teardown is essential to your test then it should be part of your test. Any fixture in this `pytest_fixtures/api_fixtures.py file could be used by anyone in their test in the future, and they have a right to expect it is safe to use.

**Comment by devendra104** [comment]
> > @swadeley One fixture is used by the customer upgrade scenarios and another is used by the "run_in_one_thread" marker test case, I don't think it will create any load or race condition.
> 
> @devendra104 If the teardown is essential to your test then it should be part of your test. Any fixture in this `pytest_fixtures/api_fixtures.py file could be used by anyone in their test in the future, and they have a right to expect it is safe to use.

I think it can be used by anyone and it will not create any load or race condition, If it is mandatory to use teardown type of fixtures in the test file then I will definitely move this inside the test file or create separate fixtures file.

**Review by mshriver — APPROVED** [review]

**Review by devendra104 — APPROVED** [review]
ACK

**Comment by mshriver** [comment]
CI pipeline failing due to ubuntu requirement not available, unrelated to change here.

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
