### PR TITLE
[cherry-pick] Fix valid_sync_interval, no underscore required

### PR DESCRIPTION
**Pull request by swadeley**
Hello

a cherry-pick from https://github.com/SatelliteQE/robottelo/pull/8751

### CODE REVIEW

**Comment by swadeley** [comment]
robottelo]$ pytest tests/foreman/api/test_syncplan.py -k test_positive_update_interval
========================= test session starts =====================================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo, configfile: pyproject.toml
plugins: xdist-2.3.0, mock-3.6.1, ibutsu-1.16, forked-1.3.0, services-2.2.1, cov-2.12.1, reportportal-5.0.8
collected 114 items / 106 deselected / 8 selected                                                                                                                                                 

tests/foreman/api/test_syncplan.py ........                                                                                                                                                 [100%]
=========================== 8 passed, 106 deselected, 21 warnings in 22.18s ============================

**Review by devendra104 — APPROVED** [review]
ACK

**Comment by mshriver** [comment]
I would hold on merging this cherry-pick. The commit (same goes for #8751) doesn't really fix why the test failed, just regresses the parametrization. The test itself can be fixed with a 1-line change, maintaining the parametrization that includes arg ID's.

**Comment by swadeley** [comment]
lets close in favour of https://github.com/SatelliteQE/robottelo/pull/8761#pullrequestreview-703339187

**Pull request closed without merging**
