### PR TITLE
[E2E] Recalculate applicability before UI session, fix navigation failure

### PR DESCRIPTION
**Pull request by damoore044**
### Problem Statement
- Occasional e2e failure in one or two parameters for `UI::Errata::test_end_to_end[rhel7, 8, 9]`.
- Upon asserting one applicable errata, after installing an outdated applicable package.
```
tests/foreman/ui/test_errata.py:396: in test_end_to_end
    assert (applicable_errata == 1)
E   AssertionError: Expected 1 applicable errata: RHSA-2012:0055, after setup. Got 0
E   assert 0 == 1
```

- Follow-up after resolving `AssertionError`, now failing to navigate to `[Details]` 
at [Ln405](https://github.com/SatelliteQE/robottelo/pull/14095/files#:~:text=assert%20session.errata.search_content_hosts): `assert session.contenthost.search_content_hosts(...)`
```
navmazing._errors.NavigationTriesExceeded: Navigation failed to reach [Details] in the specified tries
>           raise NoSuchElementException(f"Could not find an element {repr(locator)}") from None
E           selenium.common.exceptions.NoSuchElementException: Message: Could not find an element ".//input[@ng-model='showInstallable']"; For documentation on this error, please visit: ...
../../lib64/python3.11/site-packages/widgetastic/browser.py:467: NoSuchElementException
```
  The page is blank when the test fails, `assert` does not give the method enough time for a loaded page.
  Also put up a very small change for the `search_content_hosts()` method- [Airgun#1240](https://github.com/SatelliteQE/airgun/pull/1240).

### Solution
- _To resolve applicability_, after installing the outdated pkg, we need to manually recalculate errata to show up-to-date applicability in time.
- _To resolve navigation_, instead of asserting directly on `session.contenthost .errata ` methods, store the method result as a variable, giving time in case the page is slow, UI elements are not loaded yet. 
Then assert upon the variable (typically some sort of response) or expected outcome (generated task(s) etc).
### PRT Case
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py::test_end_to_end
airgun: 1240
```

### CODE REVIEW

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py::test_end_to_end

**Review by ColeHiggins2 — APPROVED** [review]

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5756
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_errata.py::test_end_to_end
Test Result : ================= 3 failed, 290 warnings in 2338.25s (0:38:58) =================
```

**Comment by damoore044** [comment]
UI Failure navigating to `[Details]` in all parameters, this fixed the prior `AssertionError` before UI session, 
locally testing the new failure.

**Review by vsedmik — APPROVED** [review]

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5761
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_errata.py::test_end_to_end
Test Result : ================= 3 failed, 294 warnings in 2357.91s (0:39:17) =================
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py::test_end_to_end
airgun: 1240

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5763
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_errata.py::test_end_to_end
Test Result : ================= 3 failed, 277 warnings in 2163.51s (0:36:03) =================
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py::test_end_to_end
airgun: 1240

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5772
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_errata.py::test_end_to_end
Test Result : ================= 3 passed, 332 warnings in 2845.71s (0:47:25) =================
```

**Review by synkd — APPROVED** [review]

**Review by sambible — APPROVED** [review]

**Review by Griffin-Sullivan — APPROVED** [review]

**Pull request merged**
