### PR TITLE
[6.12.z] test_host - disable SCA on the module_org

### PR DESCRIPTION
**Pull request by rplevka**
backport of
https://github.com/SatelliteQE/robottelo/pull/10460

### CODE REVIEW

**Comment by rplevka** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_host.py -k test_positive_erratum_applicability

**Review by pondrejk — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
Until #10460 PR is merged, will move this PR to draft

**Comment by devendra104** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_host.py -k test_positive_erratum_applicability

**Comment by Gauravtalreja1** [comment]
@rplevka Can you please update this PR?

**Pull request closed without merging**
