### PR TITLE
Cherrypick of 6.15 tests to 6.15.z

### PR DESCRIPTION
**Pull request by sambible**
Cherrypick of tests that missed the cutover from stream. 
Requires: https://github.com/SatelliteQE/airgun/pull/1121

Original PR: https://github.com/SatelliteQE/robottelo/pull/13120

### CODE REVIEW

**Review by vsedmik — CHANGES_REQUESTED** [review]
Don't we miss the `new_host_ui` fixture here?

**Comment by ColeHiggins2** [comment]
trigger: test-robottelo
airgun: 1121
pytest: tests/foreman/ui/test_host.py -k test_all_hosts_delete or test_all_hosts_bulk_delete

**Review by vsedmik — APPROVED** [review]
Looks good now, PRT pending.

**Comment by vsedmik** [comment]
PRT failure seems unrelated AND happened in teardown, which means the tests actually passed
```
22:26:21  >               ':4444', f'/videos/{ui_session.ui_session_id}.mp4'
22:26:21              )
22:26:21  E           AttributeError: 'Session' object has no attribute 'ui_session_id'
```

**Pull request merged**
