### PR TITLE
[6.16.z] [RFE] Updating Subscription Management to be SCA Only

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15637

### Problem Statement

Updating Subscription Management Component to be SCA only

SAT-24357

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_subscription.py::test_positive_candlepin_events_processed_by_stomp

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8411
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_subscription.py::test_positive_candlepin_events_processed_by_stomp --external-logging
Test Result : ================== 1 passed, 9 warnings in 668.90s (0:11:08) ===================
```

**Comment by jyejare** [comment]
@omkarkhatavkar Interesting that the test did not fail but the return code is non-zero and its failing the PRT check.

**Comment by devendra104** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_subscription.py::test_positive_candlepin_events_processed_by_stomp

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8426
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_subscription.py::test_positive_candlepin_events_processed_by_stomp --external-logging
Test Result : ================== 1 passed, 9 warnings in 683.01s (0:11:23) ===================
```

**Review by vsedmik — APPROVED** [review]
Changes look good, properly cherry-picked

**Pull request merged**
