### PR TITLE
Renamed tests for cli/test_roles.py.

### PR DESCRIPTION
**Pull request by omaciel**
Test case naming follows #3038 conventions.

### CODE REVIEW

**Comment by omaciel** [comment]
```shell
(robottelo)┌[omaciel☮Ogs-MacBook-Pro.local]-(~/hacking/robottelo)-[git://rename-tests-cli-roles ✔]-
└> py.test -v tests/foreman/cli/test_roles.py --collect-only
================================================================= test session starts ==================================================================
platform darwin -- Python 2.7.10, pytest-2.8.3, py-1.4.31, pluggy-0.3.1 -- /Users/omaciel/.virtualenvs/robottelo/bin/python
cachedir: .cache
rootdir: /Users/omaciel/hacking/robottelo, inifile:
collected 4 items
<Module 'tests/foreman/cli/test_roles.py'>
  <UnitTestCase 'RoleTestCase'>
    <TestCaseFunction 'test_positive_create_with_name'>
    <TestCaseFunction 'test_positive_create_with_permission'>
    <TestCaseFunction 'test_positive_delete_by_id'>
    <TestCaseFunction 'test_positive_update_name'>

===================================================================  in 0.29 seconds ===================================================================
```

**Comment by sghai** [comment]
ACK.. Looks good

**Comment by oshtaier** [comment]
`test_roles.py` -> `test_role.py`

**Comment by oshtaier** [comment]
ACK pending 1 comment

**Comment by omaciel** [comment]
@oshtaier done

**Comment by oshtaier** [comment]
APT

**Pull request merged**
