### PR TITLE
Add Capsule Provisioning test

### PR DESCRIPTION
**Pull request by shubhamsg199**
Adding a test for provisioning using an external capsule.

### CODE REVIEW

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_capsule_pxe_provisioning
provisioning: true
pod_resources_size: extra_extra_large

**Review by Gauravtalreja1 — APPROVED** [review]
ACK, PRT passed before rebase

**Pull request merged**
