### PR TITLE
Let's fix the length of the strings to improve reliable results.

### PR DESCRIPTION
**Pull request by kbidarkar**
* Updated data as per tests.
* Drop length arguments to `gen_*` methods. They produce 10 chars
  long strings by default

### CODE REVIEW

**Comment by elyezer** [comment]
I know that having long organization or location names could break the org/loc selection in UI tests even though the UI still usable by the user. But I did not get why the presence of varying-length strings is not appropriated for other entities like subnet.

**Comment by kbidarkar** [comment]
We are inducing too much of randomness in the UI Tests, which will result in unreliable results. Almost everything is random. I think reducing this could help us with stable results.
This will be a problem when selecting too long names from the selection list.
org_subnet_selection

**Comment by kbidarkar** [comment]
I think we need to discuss this issue and come up with suggestions to overcome these issues.

**Comment by JacobCallahan** [comment]
@kbidarkar Can you explain why we are unable to correctly select an element, if the names are too long? I don't have enough practice with the UI tests to understand the problem right now. Thanks!

**Comment by kbidarkar** [comment]
@JacobCallahan: I wish I could have some concrete or direct answer here. 
a) For UI related tests, we see failures and issues failing while triggering the automation with jenkins. Many a times the tests simply just PASS locally, but fail while running the automation with jenkins.
b) But there could be other reasons too. Like when the length of the entity chars is too long, weird things happen with the UI. The UI will try to display the entire length of that particular entity and it might so happen that,
i) we may not find the locator at the desired location, as the UI will shift trying to display the lengthy chars. 
ii) instead of the entire length of the locator of say 30 chars , the UI would display "abcdefghij....".
iii) also with lot of randomness at every level I cannot imagine what all issues we could encounter.
c) Also troubleshooting would be a problem with random length, as once the entity char length might be 5 chars and it passes for me when actually writing the test, but fail when tried with 30chars.
d) Now some might suggest, why not while writing test itself we test with 30chars.
i) we can do that but then, we encounter the weird issue of timing as mentioned in a)
ii) It PASSES locally but, fails only when running the automation with jenkins.

Things are not that predictable when running automation for UI. 

Also the important questions which I was asking myself. 

a) Will the customer really use such long chars more than 10 to 15 chars.
b) I was thinking we could use only long chars for boundary testing with 255 chars, this will help us to test issues which we might encounter related to DB stuff. I feel the major reason for using long chars should be to make sure we don't encounter DB related issues. Whether the UI and DB accepts upto 255chars. So for functional test cases is it really required?

May be it is time for us to discuss upon and decide on this, so as to unnecessarily avoid such complex issues.

**Comment by elyezer** [comment]
I agree with having long string for boundary tests, but if we write them down how we will handle the long string? And when we are able to handle them, then the length of the string will be irrelevant once we are able to select long ones.

Anyway the point is, we aways faced the works locally problem and this is really hard to debug. I think maybe this is time to us improve even more robottelo by adding screenshot support and take it when the test fail. But we can go even further by adding recording support too, we will be building something like a local Sauce Labs. If we are able to create a separated package to handle screen shot and recording then I'm sure we can help others too.

A good start point could be https://github.com/RedHatQE/python-selenium-wrapper.

**Comment by kbidarkar** [comment]
I still think functional tests could avoid long chars for various entities, as testing them once for 255 chars should be enough.  Simple tests with 255 chars would not be a problem at all and I believe can be handled. 

a) The idea is to focus more on functional tests with short length chars.
b) Using lengthy 255 chars can be tried for specific tests like boundary tests.
c) The length of the strings will **NOT** be irrelevant, but will definitely help us when dealing with functional test cases, where the focus will be more on the functionality rather than handling the lengthy once with alternate locators or other magic which might be required. 
d) Most of the UI tests are failing after the move to the API, because API uses random length entity CHARS. All these tests where passing earlier , or I am sure will pass if we stop using such random length chars.

I seriously feel starting with a limited length chars will help stabilise the automation results.
For example: 
a) There are many tests in the automation run for the UI for which the FAILURE AGE is just 1 day.
b) I feel there are many more other tests which need or have to be automated.
c) I would suggest working with fixed length chars should be fine.
d) Rather than putting efforts in investigating for long length chars ( apart from boundary 255 chars) test case failures, we could work on other tests. As these mostly end up in timing issues or other weird issues.

Also I tried looking at the below link:
https://github.com/SatelliteQE/robottelo/issues/1822

But as per my current understanding, looks like we would need to tweak our existing automation heavily at the webdriver level.
I think we need to look into robottelo/test.py module. 
Please do comment and suggest about it's approach , if anyone has some better ideas.

**Comment by kbidarkar** [comment]
I say all this as, instead of finding "Genuine build issues, we are seeing a lot of automation isssues."

**Comment by kbidarkar** [comment]
I think this approach looks a bit promising as suggested by @sghai.

https://github.com/SatelliteQE/robottelo/pull/1818#issuecomment-69159225

Will try updating some of the tests as per the suggestions above.

**Comment by JacobCallahan** [comment]
@kbidarkar thanks for the explanation.

**Pull request closed without merging**
