### PR TITLE
Making the attach_nic work on a running domain

### LINKED ISSUE #4155: attach_nic() does not apply the changes to a running domain
this option: https://github.com/SatelliteQE/robottelo/blob/master/robottelo/libvirt_discovery.py#L180
seems to only update the config file of the domain, however it doesn't apply this unless the running domain is being reloaded.
This causes failure of the related tests (since the new NIC does not appear in refreshed facts).

removing the `--config` option seem to work just fine and a running domain reflects the changes

### PR DESCRIPTION
**Pull request by rplevka**
Closes #4155

a simple command modification allows us to attach the NIC to the domain without a need of restarting it.

### CODE REVIEW

**Comment by abalakh** [comment]
Any test result, please? Otherwise ACK

**Comment by abalakh** [comment]
And now it requires rebase, sorry for that :) but it's easier to rebase 1-line PR rather than @sghai 's 1k lines PR 😄

**Comment by sghai** [comment]
@rplevka : I ran all tests against 6.3 and found that issue and fixed the issue with '--live' option. Tests are working fine. with '--live' all changes applied immediately.

**Comment by abalakh** [comment]
@rplevka @sghai guys, so what's about this PR, is this change still needed?

**Comment by sghai** [comment]
@rplevka @abalakh : I'm not 100% sure about this change. If @rplevka has tested the fix then I'm fine with he change.

**Comment by rplevka** [comment]
@abalakh @sghai i've tested it. It seems to apply a default behavior which is equivalent to `--live`.

**Comment by rplevka** [comment]
```bash
$ py.test -k test_positive_refresh_facts_pxe test_discoveredhost.py
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/rplevka/work/rplevka/robottelo, inifile: 
plugins: cov-2.3.1, xdist-1.14
collected 42 items 

test_discoveredhost.py .s

============================================= 40 tests deselected by '-ktest_positive_refresh_facts_pxe' =============================================
================================================ 1 passed, 1 skipped, 40 deselected in 189.97 seconds ================================================
```

**Pull request merged**
