### PR TITLE
[6.13.z] using installer to set mqtt resend interval

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10797

Installer now exposes this setting, no need to edit the config directly anymore.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_negative_time_to_pickup[rhel9]

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_negative_time_to_pickup[rhel9]

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_negative_time_to_pickup[rhel9]

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k test_negative_time_to_pickup[rhel9]

**Pull request merged**
