### PR TITLE
Remove the sub-man status (#14783)

### PR DESCRIPTION
**Pull request by shweta83**
### Problem Statement
Manual Cherrypick of https://github.com/SatelliteQE/robottelo/pull/14783

### CODE REVIEW

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_registration.py -k 'test_positive_force_register_twice'

**Comment by shubhamsg199** [comment]
pre-commit.ci autofix

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_registration.py -k 'test_positive_force_register_twice'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6556
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_registration.py -k test_positive_force_register_twice --external-logging
Test Result : ========== 3 passed, 12 deselected, 47 warnings in 1267.48s (0:21:07) ==========
```

**Pull request merged**
