### PR TITLE
[6.14.z] Update HTTP Proxy e2e test cases

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14215

### Problem Statement
During the HTTP proxy component evaluation PX/SD/QE agreed to make several changes. This PR addresses those related to the E2E tests, in particular:
- extends `test_positive_end_to_end` to sync other content type repos via HTTP proxy
- decreases CaseImportance of some 

Some other changes improve docstings - remove redundant fields and adds more information.

### Related Issues
SAT-23276

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5934
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py --external-logging
Test Result : ===== 8 passed, 2 deselected, 308 warnings, 2 errors in 1699.33s (0:28:19) =====
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5942
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py --external-logging
Test Result : ===== 8 passed, 2 deselected, 329 warnings, 2 errors in 1731.01s (0:28:51) =====
```

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5946
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py --external-logging
Test Result : ===== 1 failed, 9 passed, 2 deselected, 503 warnings in 3451.19s (0:57:31) =====
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5950
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py --external-logging
Test Result : ===== 1 failed, 9 passed, 2 deselected, 492 warnings in 3404.24s (0:56:44) =====
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5954
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py --external-logging
Test Result : = 1 failed, 7 passed, 2 deselected, 346 warnings, 2 errors in 2209.12s (0:36:49) =
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5955
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py 
Test Result : ========= 10 passed, 2 deselected, 491 warnings in 3361.68s (0:56:01) ==========
```

**Comment by vsedmik** [comment]
There is some flakiness in the last cli test not reproducible locally.
Since it is not caused by this PR and this PR is just a cherry-pick, we should merge and address the flakiness separately.

**Review by vsedmik — APPROVED** [review]

**Pull request merged**
