### PR TITLE
[6.13.z] Add automation for BZ 2168494

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15811

### Problem Statement
Automated BZ 2168494

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8000
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 2218.45s (0:36:58) ==================
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8185
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 3557.87s (0:59:17) ==================
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8196
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 2514.95s (0:41:54) ==================
```

**Comment by shweta83** [comment]
The test is failing on selennium grid with some unrelated javascript error failing for all tests for jobinvocation. We need to fix that before merging this. So moving this back to draft.

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8675
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 2307.57s (0:38:27) ==================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8680
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 2321.96s (0:38:41) ==================
```

**Comment by devendra104** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8933
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 16 warnings in 2218.39s (0:36:58) ==================
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report
deploy_rhel_version: 8

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8936
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 16 warnings in 3144.52s (0:52:24) ==================
```

**Comment by shweta83** [comment]
The failure is unrelated to the change in the PR.

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
