### PR TITLE
[6.13.z] [6.15.z]Leapp client upgrade from non-admin user

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14671

### Problem Statement
Missing scenario of Leapp client upgrade from non-admin user
We need sca enabled manifest because test is failing with VDC subscription we use from manifest.yaml.

### Solution
Added test scenario to test BZ#2257302

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel_non_admin

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6738
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel_non_admin --external-logging
Test Result : ========== 1 failed, 1 deselected, 14 warnings in 2170.90s (0:36:10) ===========
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel_non_admin

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6921
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel_non_admin --external-logging
Test Result : ========== 1 failed, 1 deselected, 14 warnings in 2704.06s (0:45:04) ===========
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel_non_admin

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7166
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel_non_admin --external-logging
Test Result : ========== 1 failed, 1 deselected, 14 warnings in 2241.66s (0:37:21) ===========
```

**Comment by Gauravtalreja1** [comment]
@shweta83 Could you please update this PR since it has been more than 3 months?

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel_non_admin

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8186
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel_non_admin --external-logging
Test Result : ========== 1 failed, 1 deselected, 14 warnings in 3618.48s (1:00:18) ===========
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel_non_admin

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8207
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel_non_admin --external-logging
Test Result : ========== 1 failed, 1 deselected, 14 warnings in 2632.03s (0:43:52) ===========
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel_non_admin

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8223
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel_non_admin --external-logging
Test Result : ========== 1 failed, 1 deselected, 14 warnings in 3246.14s (0:54:06) ===========
```

**Comment by shweta83** [comment]
Closing this as we are merging the 2 tests in PR https://github.com/SatelliteQE/robottelo/pull/15571 and it will be cherrypicked in 6.13.z

**Pull request closed without merging**
