### PR TITLE
[6.13.z] Move ansible API tests to Ansible-Cfgmgmt and REX classes

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/14626

### CODE REVIEW

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6323
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_ansible.py --external-logging
Test Result : =========== 10 passed, 1165 warnings, 1 error in 5994.76s (1:39:54) ============
```

**Comment by Gauravtalreja1** [comment]
PRT looks due to an intermittent issue, so I think this PR is ready for review/merge

**Comment by omkarkhatavkar** [comment]
we are seeing same error as here as well ```WARNING  nailgun.client:client.py:126 Received HTTP 500 response: {
  "error": {"message":"PG::ForeignKeyViolation: ERROR:  update or delete on table \"hosts\" violates foreign key constraint \"fact_values_host_id_fk\" on table \"fact_values\"\nDETAIL:  Key (id)=(5) is still referenced from table \"fact_values\".\n"}
}```  like this PR https://github.com/SatelliteQE/robottelo/pull/14635#issuecomment-2044434370

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_ansible.py::TestAnsibleCfgMgmt

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6443
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_ansible.py::TestAnsibleCfgMgmt --external-logging
Test Result : ================= 3 passed, 221 warnings in 1868.15s (0:31:08) =================
```

**Comment by Gauravtalreja1** [comment]
Just rebased, PRT is passed

**Comment by omkarkhatavkar** [comment]
I don't see this intermittent issue as this produced multiple times with the same error with different cherry pick branch versions as well.

Just looking at how you have run this test, earlier you tried running tests as a whole test module it failed every time. Where as later you run this as test class it starts passing. Which signifies that this could be due to the previous test causing the issue or something that modifies the setup. I will not hold your PR if you wanted to fix this later.

**Pull request merged**
