### PR TITLE
UI: OperatingSys search refactor #2

### PR DESCRIPTION
**Pull request by lpramuk**
UI: OperatingSys search refactor #2

fix: only one test_method searches by description
(Part of #2930)

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK

**Comment by lpramuk** [comment]
This should have been part of PR #2994. 
I've just forgot repush changes after successful run

**Comment by lpramuk** [comment]
For results see PR #2994

**Comment by abalakh** [comment]
ACK

**Pull request merged**
