### PR TITLE
[6.14.Z] - Support the --local-files oscap argument

### PR DESCRIPTION
**Pull request by adarshdubey-star**
Manual cherry-pick for - https://github.com/SatelliteQE/robottelo/pull/11813
Automation coverage for :
https://bugzilla.redhat.com/show_bug.cgi?id=2081777
https://bugzilla.redhat.com/show_bug.cgi?id=2211952

### CODE REVIEW

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_oscap.py -k test_positive_oscap_run_via_local_files

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_oscap.py -k test_positive_oscap_run_via_local_files

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_oscap.py -k test_positive_oscap_run_via_local_files

**Review by shubhamsg199 — APPROVED** [review]
ACK

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
