### PR TITLE
Skipped Tests for OS associated with HostGroup bug #1658659

### PR DESCRIPTION
**Pull request by jyejare**
Skipped Discovery Tests with bug 1658659.

### CODE REVIEW

**Comment by oshtaier** [comment]
sorry for stupid questions, but are tests skipped in result? so if test signature has fixture that is skipped, then test is also skipped?

**Comment by jyejare** [comment]
@oshtaier , 

Yes, It does skip the test.

```
import pytest
from pytest import fixture

@fixture(scope='module')
def skip_me():
    a = 5
    if a:
        pytest.skip('Skipping, coz a is not None')
    pytest.fail('Test Failed')

def test_test1(skip_me):
    assert 1 == 1
```

# py.test -s tests/foreman/test/test_fixtureskips.py -k test_test1
========================================== test session starts ==========================================
platform linux -- Python 3.6.5, pytest-4.0.2, py-1.7.0, pluggy-0.8.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/jitendrayejare/Desktop/RedHat/RoboTelloNew/robottelo, inifile:
plugins: xdist-1.26.0, services-1.3.1, mock-1.10.0, forked-1.0.1, cov-2.6.1
collecting ... 2019-02-04 12:17:12 - conftest - DEBUG - Collected 1 test cases

collected 1 item                                                                                        

tests/foreman/test/test_fixtureskips.py 2019-02-04 12:17:12 - robottelo - INFO - Entities cleaner disabled
s

======================================= 1 skipped in 0.01 seconds =======================================

**Comment by jyejare** [comment]
@oshtaier , By the way, this PR is no longer required as the bug [1] is now ON_QA and the issue is fixed.

I am closing this PR.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1658659

**Comment by oshtaier** [comment]
=) Thanks

**Pull request closed without merging**
