### PR TITLE
CapsuleContent [CompEval] - Cx Case

### PR DESCRIPTION
**Pull request by damoore044**
### Purpose
Cover customer scenario in CapsuleContent:
- Add repo w/ synced content to CV in Library, export-complete Library content,
- import the exported Library content, promote/add to Capsule's LCE, sync the Capsule

BZ: 2043726, 2059385

### CODE REVIEW

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_capsulecontent.py::test_positive_exported_imported_content_sync

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7699
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_capsulecontent.py::test_positive_exported_imported_content_sync --external-logging
Test Result : ================= 1 failed, 13 warnings in 1507.78s (0:25:07) ==================
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_capsulecontent.py::test_positive_exported_imported_content_sync

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7825
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_capsulecontent.py::test_positive_exported_imported_content_sync --external-logging
Test Result : ================= 1 failed, 13 warnings in 1479.54s (0:24:39) ==================
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_capsulecontent.py::test_positive_exported_imported_content_sync

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7905
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_capsulecontent.py::test_positive_exported_imported_content_sync --external-logging
Test Result : ================= 1 passed, 14 warnings in 1614.98s (0:26:54) ==================
```

**Review by pondrejk — APPROVED** [review]

**Review by sambible — APPROVED** [review]

**Pull request merged**
