### PR TITLE
DO-NOT-MERGE: Testing EXPORT ENV VARS PR

### PR DESCRIPTION
**Pull request by omkarkhatavkar**

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
```yaml
trigger: test-robottelo
pytest: tests/foreman/ui/test_bookmarks.py
env:
  ROBOTTELO_ui__record_video: true
```

**Comment by omkarkhatavkar** [comment]
```yaml
trigger: test-robottelo
pytest: tests/foreman/ui/test_sync.py -k 'test_positive_sync_custom_repo'
env:
  ROBOTTELO_ui__record_video: true
```

**Comment by Gauravtalreja1** [comment]
@omkarkhatavkar As this feature is already merged in PRT, can we close this test PR?

**Comment by omkarkhatavkar** [comment]
closing this as this was for testing

**Pull request closed without merging**
