### PR TITLE
updated location issue in test setup

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
### PR Issue
https://github.com/SatelliteQE/robottelo/issues/7210

### Test Result 
```
Testing started at 2:26 PM ...
/home/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_smartvariable.py::test_positive_override_from_attribute
Launching py.test with arguments test_smartvariable.py::test_positive_override_from_attribute in /home/okhatavk/Satellite/robottelo/tests/foreman/ui

2019-07-22 14:26:53 - conftest - DEBUG - Registering custom pytest_configure

2019-07-22 14:26:53 - conftest - DEBUG - Fetching BZs to deselect...

2019-07-22 14:27:18 - conftest - DEBUG - Deselected tests reason: BZ resolution ['1226425', '1147100', '1311113', '1487317', '1204686', '1347658', '1310422', '1156555', '1475443', '1479291', '1199150', '1278917', '1217635', '1414821', '1214312', '1230902']

2019-07-22 14:27:18 - conftest - DEBUG - Deselected tests reason: missing version flag ['1226425', '1147100', '1311113', '1487317', '1610309', '1204686', '1701118', '1489322', '1194476', '1347658', '1436209', '1310422', '1581628', '1378442', '1156555', '1475443', '1682940', '1479291', '1199150', '1278917', '1701132', '1625783', '1217635', '1214312', '1230902']

2019-07-22 14:27:18 - conftest - DEBUG - Deselected tests reason: sat-backlog ['1226425', '1147100', '1311113', '1487317', '1610309', '1204686', '1701118', '1489322', '1194476', '1347658', '1436209', '1310422', '1581628', '1378442', '1156555', '1475443', '1682940', '1479291', '1199150', '1278917', '1701132', '1625783', '1217635', '1214312', '1230902']

============================= test session starts ==============================
platform linux -- Python 3.4.8, pytest-4.0.2, py-1.7.0, pluggy-0.9.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/okhatavk/Satellite/robottelo, inifile:
plugins: xdist-1.26.1, services-1.3.1, mock-1.10.0, forked-1.0.2, cov-2.6.12019-07-22 14:27:18 - conftest - DEBUG - Collected 1 test cases

collected 1 item

test_smartvariable.py                                                   [100%]

========================== 1 passed in 495.59 seconds 
```

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
> test_positive_create_matcher_attribute_priority

Let me check that.

**Comment by omkarkhatavkar** [comment]
@ntkathole just reverted code base with default location and setting.

**Comment by ntkathole** [comment]
Thanks @omkarkhatavkar , already acked!

**Comment by omkarkhatavkar** [comment]
> I'm not sure if I follow... Basically, Puppet environment should be in the same location as other entities we change here, right? In the past we didn't make sure this requirement is met, now we always assign location to puppet env before actually using it. Is that correct?

These were the changes causing this behaviour : 

https://bugzilla.redhat.com/show_bug.cgi?id=1709695
https://bugzilla.redhat.com/show_bug.cgi?id=1725250
https://github.com/theforeman/foreman/pull/6883

**Comment by mirzal** [comment]
Both these issues are now fixed and verified, which I read as "new hosts are assigned to default organization / location automatically". If that's the case, why do we need to set location manually?

Probably it's just my lack of knowledge about Puppet speaking.

**Comment by mirzal** [comment]
For the record, these are not blocking comments. First, I wasn't sure if I understood the change correctly. Now, I think I did, but after reading bugzilla comments, I don't understand why we need this change.

**Comment by omkarkhatavkar** [comment]
After having a discussion with @vijay8451 looks like https://github.com/SatelliteQE/robottelo/issues/7215 particular issue is the culprit for location issue. We are running parallel tests where the locations are getting override instead of append. Hence closing this PR as this will be automatically get fixed once the dependent issue gets fixed

**Pull request closed without merging**
