### PR TITLE
[6.13.z] Add automation for BZ 2106475 and BZ 2174734

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
Manual Cherrypick of https://github.com/SatelliteQE/robottelo/pull/10913

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning_puppet.py -k test_host_provisioning_with_external_puppetserver
provisioning: true
pod_resources_size: extra_extra_large

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning_puppet.py -k test_host_provisioning_with_external_puppetserver
provisioning: true
pod_resources_size: extra_extra_large

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning_puppet.py -k test_host_provisioning_with_external_puppetserver
provisioning: true
pod_resources_size: extra_extra_large

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning_puppet.py -k test_host_provisioning_with_external_puppetserver
provisioning: true
pod_resources_size: extra_extra_large

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning_puppet.py -k test_host_provisioning_with_external_puppetserver
provisioning: true
pod_resources_size: extra_extra_large

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning_puppet.py -k test_host_provisioning_with_external_puppetserver
provisioning: true
pod_resources_size: extra_extra_large

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning_puppet.py -k test_host_provisioning_with_external_puppetserver
provisioning: true
pod_resources_size: extra_extra_large

**Review by shubhamsg199 — APPROVED** [review]
Ack, The RHEL9 test failure in PRT will be fixed by https://github.com/SatelliteQE/robottelo/pull/11052
Good work @Gauravtalreja1

**Review by JacobCallahan — APPROVED** [review]

**Pull request merged**
