### PR TITLE
Clean only orgs with no hosts, using Host.search()

### PR DESCRIPTION
**Pull request by rochacbruno**
It depends on nailgun PR https://github.com/SatelliteQE/nailgun/pull/298  to use Host search to get organization assigned hosts

```bash
py.test -s tests/foreman/api/test_host.py -k with_name
....
2016-06-03 13:43:59 - robottelo - DEBUG - Org 1073 can't be deleted as it has 1 hosts
2016-06-03 13:43:59 - robottelo - DEBUG - Cleanup deleted 1 entities
=== 1 passed, 44 deselected in 24.36 seconds ===
```

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK
@abalakh @elyezer @sthirugn Please, check that PR. The more ACK the better.
Same here. Please, submit after next successful test run only

**Comment by sthirugn** [comment]
ACK - not merging as per @oshtaier comment above.

**Comment by sthirugn** [comment]
@rochacbruno can you please rebase and remove conflicts?

**Comment by rochacbruno** [comment]
@sthirugn rebased

**Pull request merged**
