### PR TITLE
ddt removal in api organization and partition table tests

### PR DESCRIPTION
**Pull request by sthirugn**
This PR also removed redundata test data and reused helper functions.

test_organization.py:

```sh
Finding files... done.
Importing test modules ... done.

----------------------------------------------------------------------
Ran 17 tests in 64.928s

OK (skipped=2)
```

test_partitiontable.py:

```sh
Finding files... done.
Importing test modules ... done.

----------------------------------------------------------------------
Ran 12 tests in 14.704s

OK (skipped=1)

```

### CODE REVIEW

**Comment by sthirugn** [comment]
*This completed the ddt removal in api tests - cli and ui are pending.*

**Comment by JacobCallahan** [comment]
ACK. Great work during these conversions!

**Comment by sthirugn** [comment]
Thank you :)

**Comment by elyezer** [comment]
ACK

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
