### PR TITLE
Fixed UI tests

### PR DESCRIPTION
**Pull request by sghai**
- Fixed test_positive_copy_activation_key test by updating data set
- Fixed test_update_os_template test by adding wait_for_ajax

### CODE REVIEW

**Comment by sghai** [comment]
```
@Test: Update provisioning template ... ok

----------------------------------------------------------------------
Ran 1 test in 62.898s

OK
```

**Comment by sghai** [comment]
```
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok

----------------------------------------------------------------------
Ran 6 tests in 544.094s

OK
```

**Comment by sghai** [comment]
```
@Test: Create new puppet-class ... ok
@Test: Create new puppet-class ... ok
@Test: Create new puppet-class ... ok
@Test: Create new puppet-class ... ok
@Test: Create new puppet-class ... ok

----------------------------------------------------------------------
Ran 5 tests in 455.544s

OK
```

**Comment by oshtaier** [comment]
Don't like the idea of populating ```self.wait_for_ajax()``` so frequently, but it is not critical concern
ACK

**Comment by sghai** [comment]
Yes..agreed. For almost all UI modules, we are using this extensively and I really don't know any better way to deal with this.

**Comment by sthirugn** [comment]
ACK

**Comment by elyezer** [comment]
@sghai @oshtaier we can create selenium soft wrappers that will call wait for ajax when clicking on things.

**Comment by elyezer** [comment]
ACK

**Comment by sghai** [comment]
Yeah.. good suggestion. I'll try that. thanks

**Pull request merged**
