### PR TITLE
[6.12.z] removing the import entities from nailgun and moving target_sat

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
### Problem Statement
Needs to be a cherrypick of https://github.com/SatelliteQE/robottelo/pull/12989 to 6.12.z

### Solution
This PR helps to do the cherrypick https://github.com/SatelliteQE/robottelo/pull/12989

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pod_resource_size: extra_large

**Review by pondrejk — APPROVED** [review]

**Review by Gauravtalreja1 — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
@ogajduse We had a discussion on the original PR about this and @omkarkhatavkar confirmed that he's only targetting tests/foreman/api in this PR and he will continue on other modules in separate PRs
https://github.com/SatelliteQE/robottelo/pull/12989#issuecomment-1786927532

**Review by ogajduse — APPROVED** [review]

**Comment by ogajduse** [comment]
@omkarkhatavkar black seems to be not happy about the formatting, can you please fix it?

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pod_resource_size: extra_large

**Comment by ogajduse** [comment]
trigger: test-robottelo
pod_resource_size: extra_extra_large

**Comment by ogajduse** [comment]
trigger: test-robottelo
pod_resources_size: extra_extra_large

**Comment by ogajduse** [comment]
PRT passed, merging

**Pull request merged**
