### PR TITLE
Update Hammer options for new additions

### LINKED ISSUE #4164: Update HammerCommandsTestCase.test_positive_all_options
- [x] tests.foreman.cli.test_hammer.HammerCommandsTestCase.test_positive_all_options

following options seems to be added for 6.2.7:
```
E           AssertionError: 
E           hammer auth-source ldap create
E             Added options:
E               * organization-ids
E               * organizations
E               * location-ids
E               * locations
E           
E           hammer auth-source ldap list
E             Added options:
E               * organization
E               * location-id
E               * location
E               * organization-id
E           
E           hammer auth-source ldap update
E             Added options:
E               * organization-ids
E               * organizations
E               * location-ids
E               * locations
E           
E           hammer csv activation-keys
E             Added options:
E               * search
E           
E           hammer csv content-hosts
E             Added options:
E               * search
E               * columns
E           
E           hammer csv settings
E             Added options:
E               * search
E           
E           hammer csv subscriptions
E             Added options:
E               * search
```

### PR DESCRIPTION
**Pull request by lpramuk**
Fixes #4164

### CODE REVIEW

**Comment by lpramuk** [comment]
Once 6.3 will be rebased of 1.15 we can merge

**Comment by lpramuk** [comment]
I checked upstream and it contains these new subcommands/options.
Lets merge to be on par with upcoming 6.3 candidate (aka Downstream Nightly) in advance

**Comment by rplevka** [comment]
ACK

**Comment by rplevka** [comment]
I believe we want this in `6.2.z` too.

**Comment by lpramuk** [comment]
it's there already (was merged before this)

**Pull request merged**
