### PR TITLE
DO NOT REVIEW - testing provisioning

### PR DESCRIPTION
**Pull request by shubhamsg199**
testing rhel9 provisioning

### CODE REVIEW

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_puppetenvironment.py -k test_positive_end_to_end
env:
    ROBOTTELO_server__deploy_workflow: 'deploy-satellite-upgrade'
    ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.14'
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: 'ystream'
    BROKER_AnsibleTower__inventory: 'osp-rhos01-satellite-upgrade'
    ROBOTTELO_ui__record_video: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_puppetenvironment.py -k test_positive_end_to_end
env:
  ROBOTTELO_server__deploy_workflow: 'deploy-satellite-upgrade'
  ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
  ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.14'
  ROBOTTELO_server__deploy_arguments__deploy_snap_version: 'ystream'
  BROKER_AnsibleTower__inventory: 'osp-rhos01-satellite-upgrade'
  ROBOTTELO_ui__record_video: true

**Comment by shubhamsg199** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_puppetenvironment.py -k test_positive_end_to_end
env:
  ROBOTTELO_server__deploy_workflow: 'deploy-satellite-upgrade'
  ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
  ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.14'
  ROBOTTELO_server__deploy_arguments__deploy_snap_version: 'ystream'
  BROKER_AnsibleTower__inventory: 'osp-rhos01-satellite-upgrade'
  ROBOTTELO_ui__record_video: true
```

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_puppetenvironment.py -k test_positive_end_to_end
env:
  ROBOTTELO_server__deploy_workflow: 'deploy-satellite-upgrade'
  ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
  ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.14'
  ROBOTTELO_server__deploy_arguments__deploy_snap_version: 'ystream'
  BROKER_AnsibleTower__inventory: 'osp-rhos01-satellite-upgrade'
  ROBOTTELO_ui__record_video: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
Closing as I've finished the testing

**Pull request closed without merging**
