### PR TITLE
[qe_test-coverage] - added qe coverage for bugzilla 1767040

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
### PR Description 
Added qe test coverage for Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1767040

### More Details on the assertion, see upstream PR 
https://github.com/theforeman/foreman/pull/7220

### CODE REVIEW

**Review by mirekdlugosz — APPROVED** [review]
In hindsight, maybe there should be a way to instantiate browser on context manager entry, without ever requesting any entity. There are couple of tests that would be cleaner if Airgun could do that, and this is another on that list.

ACK

**Review by pondrejk — APPROVED** [review]
ack pending test result

**Comment by omkarkhatavkar** [comment]
> ack pending test result

Just waiting for the build here to get in downstream, Once I have it I can test it.

**Comment by mshriver** [comment]
I pushed a commit rebasing to resolve merge conflicts. Not sure why this wasn't merged when it was approved.

**Comment by mshriver** [comment]
@omkarkhatavkar can you please review this test case, as the BZ has been updated to indicate it is available in the latest builds. Running the case locally, I'm not seeing the error text that you're looking for, and I'm not sure what made you expect that specific error text.  The page still appears to show access to a full trace when the URL used in the test is accessed directly.

**Comment by omkarkhatavkar** [comment]
> is accessed directly.

Looking at the upstream code It seems feels like they have remove the `Full trace` but I'm wrong. I will have discussion with Dev around this. See the link here (https://github.com/theforeman/foreman/pull/7220/files#diff-2b432eaf48e42a883b1a7983c54347d0e54e9af184404c5283ceb6a8dcf7c7c4L13)

**Comment by omkarkhatavkar** [comment]
The Bugzilla is not fixed fully, I will update the PR once get more details

**Comment by omkarkhatavkar** [comment]
closing this as the fork was deleted and raising the same pr here https://github.com/SatelliteQE/robottelo/pull/8260

**Comment by mshriver** [comment]
For future reference, I'm pretty sure you could have checked out this PR to re-create the branch locally.

**Pull request closed without merging**
