### PR TITLE
Some capsule tests

### PR DESCRIPTION
**Pull request by cswiii**

### CODE REVIEW

**Comment by cswiii** [comment]
I have run flake8 against these btw :P

**Comment by JacobCallahan** [comment]
ACK. Excited to see these fleshed out!

**Comment by elyezer** [comment]
I will create a follow up PR which will properly format the docstrings as used in other robottelo parts. This could be also a reference for future PRs.

Thanks for the addition.

**Comment by elyezer** [comment]
ACK

**Pull request merged**
