### PR TITLE
testing foreman_ygg_worker, etc.

### PR DESCRIPTION
**Pull request by pondrejk**
### Problem Statement
to test 

https://github.com/theforeman/foreman-packaging/pull/11317
https://github.com/theforeman/foreman-packaging/pull/11296
https://github.com/theforeman/foreman/pull/10340

### CODE REVIEW

**Comment by pondrejk** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_pull_provider
theforeman:
    foreman: 10340
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8982
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_pull_provider --external-logging
Test Result : ========= 6 passed, 58 deselected, 555 warnings in 4488.69s (1:14:48) ==========
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_pull_provider
theforeman:
    foreman: 10340

**Comment by pondrejk** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_pull_provider
theforeman:
    foreman: 10340
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 9162
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_pull_provider --external-logging
Test Result : = 2 failed, 4 passed, 58 deselected, 628 warnings, 1 error in 5451.23s (1:30:51) =
```

**Comment by pondrejk** [comment]
all related prs are now merged, closing

**Pull request closed without merging**
