### PR TITLE
Added test stubs for oscap hardening, disconnected to connected

### PR DESCRIPTION
**Pull request by kbidarkar**
features

This covers the following areas:

a) oscap hardening
b) disconnected to connected RedHat Repo syncs
c) oscap email reporting

### CODE REVIEW

**Comment by kbidarkar** [comment]
For oscap testcases why those are added as tier4, below is the explanation.

```
Issues here for the record:
a) OSCAP tests are lengthy and fall under teir4 category.
b) OSCAP changes for Sat6.2 are less visible and more back-end changes or how it's handled internally.
c) Visible changes are more like new buttons, new page, new select box and so on. [ hence more assert statements only was the plan]
d) So my idea is to add those new test-cases to github as tier4
e) The idea was to run the 1) create oscap-reports testcase  2) then run the delete test which would just delete the oscap report created in 1).
f) The plan is to do the same as mentioned in e) for the Sat6.2 tests.
g) But then the issue could be is, if we run tests in parallel would this work or not. Probably not.
h) So wondering and we need investigate whether depending upon modules can we force a particular module to be run in a serial fashion, to save time.
```

**Comment by oshtaier** [comment]
ACK

**Comment by sthirugn** [comment]
I agree with @kbidarkar.  Here all the oscap tests need oscap setup which is a long running process.  So it is okay to mark all the oscap tests as tier 4 now.  Once we start implementing the tests, we can change tiers if need be.

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
