### PR TITLE
Port entity mixins to NailGun, fix documentation

### PR DESCRIPTION
**Pull request by Ichimonji10**
Changes in this PR:

* Port module `robottelo.orm` to NailGun. Make related changes, such dropping module `tests.robottelo.test_orm`.
* Fix the documentation. Drop the number of errors down from 30 to 5. The remaining five cannot trivially be fixed.
* Fix the `make graph-entities` command.

Tested against a downstream RHEL 7.1 system. The two failures that show up are due to differences between downstream and upstream. Upstream provides some extra functionality that downstream doesn't, and NailGun targets upstream by default.

```
$ nosetests tests/foreman/api/test_multiple_paths.py
...S...S.....S.............................................................S...S.......................................................................EE...........................................................SSSS.SSSSSS..S.SSSSSSS...SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
======================================================================
ERROR: @Test: Create an entity and get it using
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_multiple_paths.py", line 700, in test_entity_read
    self.assertIsInstance(entity_cls(id=entity_id).read(), entity_cls)
  File "/home/ichimonji10/code/robottelo/robottelo/entities.py", line 1974, in read
    return super(Product, self).read(entity, attrs, ignore)
  File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 481, in read
    if attrs[field_name] is None:
KeyError: 'sync_plan'
-------------------- >> begin captured logging << --------------------
tests.foreman.api.test_multiple_paths: DEBUG: test_entity_read arg: <class 'robottelo.entities.Product'>
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: @Test: Create an entity and get it using
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_multiple_paths.py", line 700, in test_entity_read
    self.assertIsInstance(entity_cls(id=entity_id).read(), entity_cls)
  File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 481, in read
    if attrs[field_name] is None:
KeyError: 'gpg_key'
-------------------- >> begin captured logging << --------------------
tests.foreman.api.test_multiple_paths: DEBUG: test_entity_read arg: <class 'robottelo.entities.Repository'>
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 267 tests in 449.718s

FAILED (SKIP=53, errors=2)
```

### CODE REVIEW

**Comment by Ichimonji10** [comment]
I've rebased this PR and added a third commit which fixes `make graph-entities`. The only remaining references to `robottelo.orm` are in `scripts/generate_entities.py`.

```
$ git grep 'orm\.'
LICENSE:implementation is available to the public in source code form.  A
scripts/generate_entities.py:        hostgroup = orm.OneToOneField(required=False, null=True)
scripts/generate_entities.py:        output.write('class {0}(orm.Entity):\n'.format(self.name))
scripts/generate_entities.py:        type_ = 'orm.OneToOneField'
scripts/generate_entities.py:        type_ = 'orm.OneToManyField'
scripts/generate_entities.py:        type_ = 'orm.ListField'
scripts/generate_entities.py:        type_ = 'orm.IntegerField'
scripts/generate_entities.py:        type_ = 'orm.StringField'
```

**Comment by elyezer** [comment]
ACK

Can I expect an email to be sent to notify folks that they will need to update nailgun once this gets merged?

**Comment by Ichimonji10** [comment]
@elyezer, yes. I will send an email out before I leave today.

**Comment by omaciel** [comment]
ACK

**Pull request merged**
