### PR TITLE
Bump el8 and el9 kickstart versions

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
SSIA

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py::test_rhel_pxe_provisioning
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_rhel_pxe_provisioning
provisioning: true
pod_resources_size: extra_extra_large

**Review by ogajduse — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
PRT failures look intermittent for EL content repo sync and are unrelated to these changes.

**Review by shubhamsg199 — APPROVED** [review]
Ack

**Review by jyejare — APPROVED** [review]
ACK. Should we automate this in the future? To open a PR for contants to be automatically keeping them up to date ?

We have an RHEL update job in CI which can trigger the request to update the versions in robottelo . Update could be done via Git Workflow/Action.

@devendra104 @ogajduse @Gauravtalreja1 ^

**Comment by jyejare** [comment]
@Gauravtalreja1 Removed AutoMerge  cherrypicked as PRT is failing for this job.

**Pull request merged**
