### PR TITLE
Renamed tests for cli/test_subscription.py.

### PR DESCRIPTION
**Pull request by omaciel**
Test case naming follows #3038 conventions.

### CODE REVIEW

**Comment by omaciel** [comment]
```shell
(robottelo)┌[omaciel☮Ogs-MacBook-Pro.local]-(~/hacking/robottelo)-[git://rename-tests-cli-subscription ✔]-
└> py.test -v tests/foreman/cli/test_subscription.py --collect-only
================================================================= test session starts ==================================================================
platform darwin -- Python 2.7.10, pytest-2.8.3, py-1.4.31, pluggy-0.3.1 -- /Users/omaciel/.virtualenvs/robottelo/bin/python
cachedir: .cache
rootdir: /Users/omaciel/hacking/robottelo, inifile:
collected 6 items
<Module 'tests/foreman/cli/test_subscription.py'>
  <UnitTestCase 'SubscriptionTestCase'>
    <TestCaseFunction 'test_negative_manifest_refresh'>
    <TestCaseFunction 'test_positive_enable_manifest_reposet'>
    <TestCaseFunction 'test_positive_manifest_delete'>
    <TestCaseFunction 'test_positive_manifest_history'>
    <TestCaseFunction 'test_positive_manifest_refresh'>
    <TestCaseFunction 'test_positive_manifest_upload'>

===================================================================  in 0.32 seconds ===================================================================
```

**Comment by sghai** [comment]
ACK

**Comment by oshtaier** [comment]
`(positive)` word is redundant in docstrings since our renaming procedure

**Comment by oshtaier** [comment]
ACK pending non-blocking comments

**Comment by omaciel** [comment]
@oshtaier agreed. Updated.

**Comment by oshtaier** [comment]
ACK

**Pull request merged**
