### PR TITLE
Fix Puppet tests

### PR DESCRIPTION
**Pull request by shubhamsg199**
Fix failing Puppet tests

### CODE REVIEW

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_classparameters.py -k test_positive_impact_parameter_delete_attribute

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_classparameters.py -k test_positive_impact_parameter_delete_attribute

**Review by adarshdubey-star — APPROVED** [review]
Ack

**Review by jyejare — APPROVED** [review]

**Comment by jyejare** [comment]
Interesting to see we can search items by name that too from Component object itself. Never seen like this before!

**Pull request merged**
