### PR TITLE
updated the failing gr tests with new ui

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
#### Test Result 
```
Testing started at 7:12 PM ...
/home/okhatavk/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --path /home/okhatavk/okhatavk/Satellite/robottelo/tests/foreman/ui/test_host.py -- -k test_positive_global_registration_form
Launching py.test with arguments -k test_positive_global_registration_form /home/okhatavk/okhatavk/Satellite/robottelo/tests/foreman/ui/test_host.py in /home/okhatavk/Satellite/robottelo

============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/okhatavk/okhatavk/Satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, cov-2.10.1, xdist-2.2.1, reportportal-5.0.8, mock-3.5.1, forked-1.3.0, ibutsu-1.14.1, picked-0.4.6collected 37 items / 36 deselected / 1 selected

../../okhatavk/Satellite/robottelo/tests/foreman/ui/test_host.py 2021-07-16 19:12:48 - robottelo.collection - INFO - Processing test items to add testimony token markers
[INFO 210716 19:12:48] Using username and password authentication
[INFO 210716 19:12:58] Using username and password authentication
.       [100%]

=============================== warnings summary ===============================
```

#### Airgun PR 
https://github.com/SatelliteQE/airgun/pull/587/files

### CODE REVIEW

**Review by jyejare — APPROVED** [review]
ACK with non-blocking comments/questions/suggestions on dependent AIrgun PR.

**Review by jaryn — COMMENTED** [review]
Is it worthy to add a test for whether quoting of the parameters is done well?

**Review by rplevka — APPROVED** [review]

**Comment by omkarkhatavkar** [comment]
> Is it worthy to add a test for whether quoting of the parameters is done well?

I will add the test for the same

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -k 'global_registration' tests/foreman
airgun: 587

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -k 'global_registration' tests/foreman/ui/test_host.py
airgun: 587

**Comment by omkarkhatavkar** [comment]
PR Tester is failing because of not having latest updated WT.Pf4 version.

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -k 'global_registration' tests/foreman/ui/test_host.py
airgun: 587

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -k 'global_registration' tests/foreman/ui/test_host.py
airgun: 587

**Comment by omkarkhatavkar** [comment]
Okay, I looked at the test result on the PR Tester, we are passing 1 test and failing 1 test that is because of underlining issue https://bugzilla.redhat.com/show_bug.cgi?id=1983043. I think test result-wise we are good

**Review by mshriver — APPROVED** [review]

**Pull request merged**
