### PR TITLE
Remove compute_resource_docker

### PR DESCRIPTION
**Pull request by adarshdubey-star**
The module is removed as satellite no longer supports the docker computer resource as a functionality for the end users.

### CODE REVIEW

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_docker.py

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_docker.py

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_docker.py

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_docker.py

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_docker.py

**Comment by adarshdubey-star** [comment]
Opened - https://github.com/SatelliteQE/robottelo/pull/12259 as there is some issue with the stream needs to investigate further.

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_docker.py

**Review by shubhamsg199 — APPROVED** [review]
Ack, can you update the description so others can know why this tets was removed?

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
