### PR TITLE
fixes for [RFE] test_positive_installable_errata

### PR DESCRIPTION
**Pull request by damoore044**
PRT build results: 
 - Just the 3 parameters of `test_positive_installable_errata`: **[3737] 3/3 Pass**
 - All of `API/test_reporttemplates.py`: **[3738] In Progress**
 
`> assert rhel_contenthost.execute(f'yum install -y {FAKE_1_CUSTOM_PACKAGE}').status == 0 
E        +  where 1 = stdout:\nLoaded plugins: product-id, search-disabled-repos, subscription-manager\n\nstderr:\n(256, b'There are no enabled ...n-manager repos --enable <repo>
\n To enable custom repositories:\n     yum-config-manager --enable <repo>\n')\nstatus: 1.status`

Prior CI Failure: **[3729] 3/3 Fail**, `b'There are no enabled ...n-manager repos --enable <repo>`
 
Report template should find the applicable errata of package 'walrus', which was downgraded/out of date.
Assertions test the package version of 'walrus' to make sure it was updated by applying the erratum.

### CODE REVIEW

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py

**Review by JacobCallahan — CHANGES_REQUESTED** [review]

**Review by JacobCallahan — APPROVED** [review]
ACK, nice work!

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py -k test_positive_installable_errata

**Review by sambible — APPROVED** [review]
lgtm baby

**Comment by sambible** [comment]
well, pending PRT of course :)

**Review by ColeHiggins2 — APPROVED** [review]
Ack

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py -k test_positive_installable_errata

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py

**Pull request merged**
