### PR TITLE
[6.13.z] Convert CLI tests to manifester

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10209

This PR will convert all CLI tests that use manifests to obtain those manifests via manifester. Like https://github.com/SatelliteQE/robottelo/pull/10162, my plan is to push one commit for each module that I'm converting. The PR will remain in draft state until I have converted all affected modules. The list of CLI modules that I will be converting is as follows:
```
test_activationkey.py
test_contentaccess.py
test_contentview.py
test_errata.py
test_logging.py
test_remoteexecution.py
test_reporttemplate.py
test_repository_set.py
test_rhcloud_insights.py
test_rhcloud_inventory.py
test_satellitesync.py
test_subscription.py
test_syncplan.py
test_vm_install_products_package.py
```

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_activationkey.py -k "test_positive_create_with_name or test_positive_add_redhat_product or test_positive_add_redhat_and_custom_products or test_positive_delete_manifest or test_positive_delete_subscription or test_create_ak_with_syspurpose_set or test_update_ak_with_syspurpose_values or test_positive_add_subscription_by_id or test_positive_copy_subscription or test_positive_view_subscriptions_by_non_admin_user"

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_activationkey.py -k 'test_positive_create_with_name or test_positive_add_redhat_product or test_positive_add_redhat_and_custom_products or test_positive_delete_manifest or test_positive_delete_subscription or test_create_ak_with_syspurpose_set or test_update_ak_with_syspurpose_values or test_positive_add_subscription_by_id or test_positive_copy_subscription or test_positive_view_subscriptions_by_non_admin_user'

**Comment by synkd** [comment]
Quite a few failures in PRT, all on the `make_activation_key` method from the CLI factory:
```
12:34:45  FAILED tests/foreman/cli/test_activationkey.py::test_positive_create_with_name[alpha] - AttributeError: type object 'cli' has no attribute 'make_activation_key'
12:34:45  FAILED tests/foreman/cli/test_activationkey.py::test_positive_create_with_name[numeric] - AttributeError: type object 'cli' has no attribute 'make_activation_key'
12:34:45  FAILED tests/foreman/cli/test_activationkey.py::test_positive_create_with_name[alphanumeric] - AttributeError: type object 'cli' has no attribute 'make_activation_key'
12:34:45  FAILED tests/foreman/cli/test_activationkey.py::test_positive_create_with_name[latin1] - AttributeError: type object 'cli' has no attribute 'make_activation_key'
12:34:45  FAILED tests/foreman/cli/test_activationkey.py::test_positive_create_with_name[utf8] - AttributeError: type object 'cli' has no attribute 'make_activation_key'
12:34:45  FAILED tests/foreman/cli/test_activationkey.py::test_positive_create_with_name[cjk] - AttributeError: type object 'cli' has no attribute 'make_activation_key'
12:34:45  FAILED tests/foreman/cli/test_activationkey.py::test_positive_create_with_name[html] - AttributeError: type object 'cli' has no attribute 'make_activation_key'
12:34:45  ==== 7 failed, 9 passed, 129 deselected, 60 warnings in 1395.42s (0:23:15) =====
```
I'm not sure yet why this error is occurring, but that method is definitely present in the module on the 6.13.z branch:
 https://github.com/SatelliteQE/robottelo/blob/79fd1e847236c7e13ef5fb1ee1aa18631c45e98e/robottelo/cli/factory.py#L139

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_activationkey.py -k 'test_positive_create_with_name or test_positive_add_redhat_product or test_positive_add_redhat_and_custom_products or test_positive_delete_manifest or test_positive_delete_subscription or test_create_ak_with_syspurpose_set or test_update_ak_with_syspurpose_values or test_positive_add_subscription_by_id or test_positive_copy_subscription or test_positive_view_subscriptions_by_non_admin_user'

**Comment by Gauravtalreja1** [comment]
@synkd Are these PRT failures expected?

**Comment by jyejare** [comment]
@vsedmik The failures related to Activation Key here mentioned in above @synkd comment are seen in master/CI too? If yes, we can merge this ASAP.

**Comment by synkd** [comment]
@Gauravtalreja1 @jyejare I just took a closer look at this, and these failures do appear expected, because the `make_activation_key` method is actually not available in under `target_sat.cli`. Previously, it was imported from `robottelo.cli.factory` and called directly. However, I got a suggestion during review on https://github.com/SatelliteQE/robottelo/pull/10209 to change it to the form it's in here, which I apparently implemented without properly testing. I will open a PR against master to revert that change and then cherry-pick back to this PR and https://github.com/SatelliteQE/robottelo/pull/10639.

**Comment by synkd** [comment]
@Gauravtalreja1 @jyejare I just opened https://github.com/SatelliteQE/robottelo/pull/10654 to address these failures. Once that is merged, I'll cherry-pick back to this PR and to https://github.com/SatelliteQE/robottelo/pull/10639.

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_activationkey.py -k 'test_positive_create_with_name or test_positive_add_redhat_product or test_positive_add_redhat_and_custom_products or test_positive_delete_manifest or test_positive_delete_subscription or test_create_ak_with_syspurpose_set or test_update_ak_with_syspurpose_values or test_positive_add_subscription_by_id or test_positive_copy_subscription or test_positive_view_subscriptions_by_non_admin_user'

**Review by Gauravtalreja1 — APPROVED** [review]
Ack, thanks for quickly fixing this!
Do you mind cherrypicking @jameerpathan111 's https://github.com/SatelliteQE/robottelo/pull/10646 PR as well? which seems to fail for auto cherrypick in 6.13 due to this PR, non-blocking!

**Review by vsedmik — APPROVED** [review]
No, not failing in master @jyejare .
Thank you for the fast fix @synkd !

**Pull request merged**
