### PR TITLE
api endpoints updated

### PR DESCRIPTION
**Pull request by pondrejk**
### Problem Statement

Updating the list of endpoints to 6.15, the changes were verified before via sat-eng list

### CODE REVIEW

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_api_endtoend.py -k get_links

**Comment by pondrejk** [comment]
well, stream is yet different, these changes are targeting 6.15, therefore the prt failure

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_api_endtoend.py -k get_links
env:
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.15'

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_api_endtoend.py -k get_links
env:
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.15'
```

**Comment by pondrejk** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_api_endtoend.py -k get_links
env:
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.15'

**Comment by pondrejk** [comment]
I keep getting broker error from prt, supplying local results instead:

```
 pytest tests/foreman/endtoend/test_api_endtoend.py -k get_links
=============================================== test session starts ===============================================

collected 6 items / 5 deselected / 1 selected                                                                     

tests/foreman/endtoend/test_api_endtoend.py .                                                               [100%]
```

**Review by Gauravtalreja1 — APPROVED** [review]

**Comment by pondrejk** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_api_endtoend.py -k get_links
env:
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.15'
```

**Pull request merged**
