### PR TITLE
[6.16.z] [6.16]Add test for podman push on capsule

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15884

Last test for Podman push feature for 6.16, requires a new version of `smart_proxy_container_gateway` to be released.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_capsulecontent.py -k 'test_negative_podman_capsule_push'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8247
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_capsulecontent.py -k test_negative_podman_capsule_push --external-logging
Test Result : ========== 24 deselected, 36 warnings, 1 error in 2149.91s (0:35:49) ===========
```

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_capsulecontent.py -k 'test_negative_podman_capsule_push'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8361
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_capsulecontent.py -k test_negative_podman_capsule_push --external-logging
Test Result : ========== 24 deselected, 32 warnings, 2 errors in 2304.58s (0:38:24) ==========
```

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_capsulecontent.py -k 'test_negative_podman_capsule_push'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8453
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_capsulecontent.py -k test_negative_podman_capsule_push --external-logging
Test Result : ========== 1 passed, 24 deselected, 37 warnings in 1415.28s (0:23:35) ==========
```

**Pull request merged**
