### PR TITLE
Add coverage for BZ#2112098

### PR DESCRIPTION
**Pull request by vsedmik**
### Problem Statement
1. Custom CDN with custom ContentCredential scenario is still missing.
2. Misleading name of one fixture.

### Solution
1. Add new test case to cover Custom CDN with CC.
2. Rename the fixture.

### Related Issues
https://bugzilla.redhat.com/show_bug.cgi?id=2112098

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k test_positive_custom_cdn_with_credential

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k test_positive_custom_cdn_with_credential

**Review by damoore044 — APPROVED** [review]
ack 👍

**Review by lhellebr — APPROVED** [review]

**Comment by vsedmik** [comment]
Updated fixture name for recently merged case (#13543), rebased.

**Review by pondrejk — APPROVED** [review]

**Pull request merged**
