### PR TITLE
Add org ID to api repo sync search

### PR DESCRIPTION
**Pull request by swadeley**
and use org_id in UI test for consistency

brings API test into line with changes in cli and UI

https://github.com/SatelliteQE/robottelo/pull/8754/commits

### CODE REVIEW

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_syncplan.py tests/foreman/ui/test_syncplan.py

**Comment by swadeley** [comment]
UI is OK, but I have three failed in the API test

robottelo]$ pytest tests/foreman/ui/test_syncplan.py
=============================== test session starts =============================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/sjw/sat6/robottelo_1/robottelo, configfile: pyproject.toml
plugins: xdist-2.3.0, mock-3.6.1, ibutsu-1.16, forked-1.3.0, services-2.2.1, cov-2.12.1, reportportal-5.0.8
collected 5 items                                                                                                                                                                                 

tests/foreman/ui/test_syncplan.py .....                                                                                                                                                     [100%]

============================ 5 passed, 23 warnings in 1217.86s (0:20:17) ============================

**Comment by swadeley** [comment]
rh_product tests use their own org, not module org, now fixed

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_syncplan.py tests/foreman/ui/test_syncplan.py

**Comment by swadeley** [comment]
robottelo]$ pytest tests/foreman/api/test_syncplan.py
================================== test session starts ==============================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo_1/robottelo, configfile: pyproject.toml
plugins: xdist-2.3.0, mock-3.6.1, ibutsu-1.16, forked-1.3.0, services-2.2.1, cov-2.12.1, reportportal-5.0.8
collected 114 items                                                                                                                                                                               

tests/foreman/api/test_syncplan.py ..................................................................................................................                                       [100%]
============================= 114 passed, 446 warnings in 1492.40s (0:24:52) ============================

**Review by jameerpathan111 — APPROVED** [review]
ack

**Review by pondrejk — APPROVED** [review]

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
