### PR TITLE
Updated test case docstring for UI tests

### PR DESCRIPTION
**Pull request by sthirugn**
Others tests will be updated in upcoming PRs

### CODE REVIEW

**Comment by sthirugn** [comment]
This needs testimony update

**Comment by sthirugn** [comment]
There is no testimony update needed.  Testimony currently does not accept `:` in test case name so I fixed very few test cases which had that issue. All is well.

**Comment by sthirugn** [comment]
Updated and rebased.

**Comment by oshtaier** [comment]
ACK

**Comment by elyezer** [comment]
ACK

**Pull request merged**
