### PR TITLE
Only the second call should raise an exception

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_login_failure_rhsso_user_if_internal_user_exist

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 9588
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py::test_login_failure_rhsso_user_if_internal_user_exist --external-logging
Test Result : ================= 1 passed, 17 warnings in 2167.81s (0:36:07) ==================
```

**Review by lpramuk — APPROVED** [review]

**Comment by lpramuk** [comment]
@lhellebr Why cherrypicking only to 6.16.z and 6.15.z ?

**Comment by lhellebr** [comment]
@lpramuk 6.14 added

**Review by pondrejk — APPROVED** [review]

**Pull request merged**
