### PR TITLE
[6.13.z] Add automation for BZ 2026239

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
Manual Cherrypick of #11013

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_report.py

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_report.py

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_report.py

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_report.py

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_report.py

**Review by Griffin-Sullivan — APPROVED** [review]
I don't think the one failure is related to this PR

**Comment by Gauravtalreja1** [comment]
Yes, that one failure is not related to the changes, and seems intermittent checkout error

**Pull request merged**
