### PR TITLE
Updated verification code for UI test_remove_os

### PR DESCRIPTION
**Pull request by jyejare**
Updated code for verification of test test_remove_os

### CODE REVIEW

**Comment by omaciel** [comment]
@jyejare could you add an explanation why we no longer have to wait for the ``notif``?

**Comment by sghai** [comment]
ACK.. 

We removed the success notification statement because we are verifying the deleted entity via search and moreover, the success notification doesn't stay for long on UI.. so sometimes selenium doesn't handle it properly.

**Comment by omaciel** [comment]
ACK

**Comment by elyezer** [comment]
Looks good, but will let @omaciel merge if his question was answered.

**Pull request merged**
