### PR TITLE
[6.3] FIX UI content view add unpublished to composite

### PR DESCRIPTION
**Pull request by ldjebran**
removed test covering not a bug https://bugzilla.redhat.com/show_bug.cgi?id=1367123
(new feature introduced and this bug and test are not needed any more)

### CODE REVIEW

**Comment by ldjebran** [comment]
@oshtaier good idea, should we keep the bug number in doc for history what do you think?

**Comment by oshtaier** [comment]
yeah, why not =)

**Comment by ldjebran** [comment]
put do not merge for changes

**Comment by ldjebran** [comment]
```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test tests/foreman/ui/test_contentview.py::ContentViewTestCase -v -k "test_positive_add_non_composite_cv_to_composite or test_positive_add_unpublished_cv_to_composite"
========================================== test session starts ==========================================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.20.0, services-1.2.1, mock-1.6.2, forked-0.2, cov-2.5.1
collected 93 items 
2017-09-08 15:40:10 - conftest - DEBUG - Found WONTFIX in decorated tests ['1156555', '1269196', '1378009', '1245334', '1217635', '1226425', '1147100', '1311113', '1199150', '1204686', '1221971', '1103157', '1230902', '1230865', '1214312', '1079482']

2017-09-08 15:40:10 - conftest - DEBUG - Collected 93 test cases


tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_add_non_composite_cv_to_composite <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_add_unpublished_cv_to_composite <- robottelo/decorators/__init__.py PASSED

========================================== 91 tests deselected ==========================================
=============================== 2 passed, 91 deselected in 194.03 seconds ===============================
```

@oshtaier done please review

**Comment by ldjebran** [comment]
instead of deleting the tests affected by that bug, they have been refactored to positive one

**Comment by oshtaier** [comment]
Is it possible to verify the fact about 'latest'? Do we see that word somewhere for unpublished version from composite content view stand point?

Other than that, PR is good

**Comment by ldjebran** [comment]
Yes we can see that in the place of version

**Comment by oshtaier** [comment]
@ldjebran Really appreciate if you add verification for that in any modified test case. Just that text is present here

**Comment by ldjebran** [comment]
@oshtaier comment addressed
```
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$  py.test tests/foreman/ui/test_contentview.py::ContentViewTestCase -v -k "test_positive_add_non_composite_cv_to_composite or test_positive_add_unpublished_cv_to_composite"
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.20.0, services-1.2.1, mock-1.6.2, forked-0.2, cov-2.5.1
collected 93 items 
2017-09-11 15:16:26 - conftest - DEBUG - Found WONTFIX in decorated tests ['1156555', '1269196', '1378009', '1245334', '1217635', '1226425', '1147100', '1311113', '1199150', '1204686', '1221971', '1103157', '1230902', '1230865', '1214312', '1079482']

2017-09-11 15:16:26 - conftest - DEBUG - Collected 93 test cases


tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_add_non_composite_cv_to_composite <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_add_unpublished_cv_to_composite <- robottelo/decorators/__init__.py PASSED

================================================= 91 tests deselected ==================================================
====================================== 2 passed, 91 deselected in 198.87 seconds =======================================
```

**Pull request merged**
