### PR TITLE
Pytest conversion for /api/test_computeprofile.py

### PR DESCRIPTION
**Pull request by akhil-jha**
Test result:
```
$ pytest tests/foreman/api/test_computeprofile.py 

=========================================== test session starts ===================================================================================
platform linux -- Python 3.8.6, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/akjha/satelliteqe/robottelo, inifile: pytest.ini
plugins: forked-1.3.0, ibutsu-1.12, xdist-1.34.0, mock-3.3.1, cov-2.10.1, services-2.2.1
collecting ... 2020-11-24 09:23:34 - conftest - DEBUG - Collected 5 test cases
collected 5 items                                                                                                                                                                                                                        

tests/foreman/api/test_computeprofile.py .....                                                          [100%]

===================================== 5 passed, 2 warnings in 15.22s ============================================================================
```

### CODE REVIEW

**Review by jameerpathan111 — APPROVED** [review]
ACK

**Comment by jameerpathan111** [comment]
PR looks good to me. 
Those tests can be parameterized, though it's not required I guess.

**Comment by lhellebr** [comment]
Changes look sane but I also think it would be more pytest-ish to @parametrize the tests instead of looping though inputs.

**Review by lhellebr — CHANGES_REQUESTED** [review]
I think you should use @parametrize

**Review by latran — APPROVED** [review]
LGTM

**Comment by omkarkhatavkar** [comment]
Can one of the admins verify this patch?

**Comment by akhil-jha** [comment]
Screenshot from 2021-02-04 14-49-22

**Comment by akhil-jha** [comment]
Screenshot from 2021-02-04 15-27-27

**Review by jyejare — APPROVED** [review]

**Pull request merged**
