### PR TITLE
[6.11.z] assertion fix in capsule upgrade test

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of commit: f679049a7cb9da7e60434d1230f70badbbea53db

pr fixes an assertion in test_positive_run_capsule_upgrade_playbook

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k capsule

**Comment by Gauravtalreja1** [comment]
@pondrejk Could you check PRT failure and add cherrypick/no-cherrypick labels?

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k capsule

**Comment by pondrejk** [comment]
hm, prt times out on the capsule upgrade task, though I get successful runs locally

**Review by Gauravtalreja1 — APPROVED** [review]

**Review by adarshdubey-star — APPROVED** [review]

**Pull request merged**
