### PR TITLE
Skip invalid_name test because of BZ 1401519

### LINKED ISSUE #4005: invalid_names_list should no longer return long strings
since `6.3` the most (if not all) string-length restrictions have been removed.
It means the negative tests expecting error to be raised on using such string no longer pass.

There is however a restriction in data payload which is sent to the server, so we can perhaps try to update the `gen_string(300)` by something much bigger, that would trigger this restriction.

https://github.com/SatelliteQE/robottelo/blob/master/robottelo/datafactory.py#L100

### PR DESCRIPTION
**Pull request by svtkachenko**
Closes #4005

### CODE REVIEW

**Comment by oshtaier** [comment]
That PR doesn't close the issue, so please remove that statement
ACK

**Comment by svtkachenko** [comment]
@oshtaier After discussing with @rplevka we've found that disappeared length limit is not intentional change but rather a bug. Changes described in issue not needed, leaving close statement as is.

**Comment by oshtaier** [comment]
in that case provide changes to all modules
NACK

**Comment by oshtaier** [comment]
or remove all modules from the list or mark whole list

**Comment by oshtaier** [comment]
just to avoid confusion in future

**Comment by svtkachenko** [comment]
@oshtaier Only 'Architecture` entity in `tests/foreman/api/test_architecture.py` is affected, other entities have name length limit, other mentioned tests are passing.

**Comment by oshtaier** [comment]
Okay, I will do corresponding change

**Pull request merged**
