### PR TITLE
Fixed OpenScapTestCase to handle UTF-8

### PR DESCRIPTION
**Pull request by ntkathole**
Issue #5613 

Test results

```
2017-12-03 16:57:23 - robottelo.ssh - INFO - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv scap-content list --per-pa
ge="10000"
2017-12-03 16:57:26 - robottelo.ssh - INFO - <<< stdout
Id,Title
6,1234
1,Red Hat firefox default content
2,Red Hat jre default content
3,Red Hat rhel6 default content
4,Red Hat rhel7 default content
5,壥壈勊澆裩專訢芽狷珘娊睿褓讈瑆發嗥苋鉝翧银墼陲蔛嬽刺鄹聂资欠患兾凗旯袪塼鴙尴盾銤簄豝构俧掼囉悂緞髡枳详岒頿擯

2017-12-03 16:57:26 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x2ef7410
2017-12-03 16:57:26 - robottelo - DEBUG - Finished Test: OpenScapTestCase/test_positive_list_default_content_with_admin
PASSED2017-12-03 16:57:26 - robottelo - INFO - Started tearDownClass: tests.foreman.cli.test_oscap/OpenScapTestCase


======================================================= 1 passed in 41.11 seconds ================================================
```

### CODE REVIEW

**Comment by oshtaier** [comment]
does it change something? as you just check that some element is present in the list

**Comment by san7ket** [comment]
@oshtaier yea , it checks the required value from a list.

**Comment by oshtaier** [comment]
why do we care at all about utf-8?
we have list
```
6,1234
1,Red Hat firefox default content
2,Red Hat jre default content
3,Red Hat rhel6 default content
4,Red Hat rhel7 default content
5,壥壈勊澆裩專訢芽狷珘娊睿褓讈瑆發嗥苋
```
and check whether `Red Hat rhel7 default content` present in the list, so probably we don't even get to that line. Or I miss something?

**Comment by ntkathole** [comment]
@oshtaier early the problem is only due to str() function during  as  'ascii' codec can't encode characters  else everything is good.

```
>>> str(u'壥壈勊澆裩專訢芽狷珘娊睿褓讈瑆發嗥苋鉝翧银墼陲蔛嬽刺鄹聂
患兾凗旯袪塼鴙尴盾銤簄豝构俧掼囉悂緞髡枳详岒頿擯')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-52: ordinal not in range(128)

```

**Comment by oshtaier** [comment]
I see

**Pull request merged**
