### PR TITLE
Convert cli test_http_proxy to pytest

### PR DESCRIPTION
**Pull request by tpapaioa**
This PR converts the small cli test_http_proxy to pytest.

### CODE REVIEW

**Review by jameerpathan111 — APPROVED** [review]
ACK

**Review by JacobCallahan — APPROVED** [review]
ACK. Merge pending test results

**Comment by JacobCallahan** [comment]
trigger: test-robottelo
pytest: -n 3 tests/foreman/cli/test_http_proxy.py

**Comment by JacobCallahan** [comment]
i'm seeing the following error from the port
```
==================================== ERRORS ====================================
_____________ ERROR at setup of test_positive_create_update_delete _____________
[gw0] linux -- Python 3.8.3 /opt/app-root/bin/python3.8
file /opt/app-root/src/robottelo/tests/foreman/cli/test_http_proxy.py, line 28
    @pytest.mark.tier1
    @pytest.mark.upgrade
    def test_positive_create_update_delete(module_org, module_loc):
fixture 'module_loc' not found
```

**Comment by tpapaioa** [comment]
Fixed.

```
# pytest tests/foreman/cli/test_http_proxy.py 
[...]
collected 1 item

tests/foreman/cli/test_http_proxy.py . [100%]
[...]
=== 1 passed, 4 warnings in 35.04s ===
```

**Review by JacobCallahan — APPROVED** [review]

**Pull request merged**
