### PR TITLE
Added return validation_errors on FakeCapsuleSettings

### LINKED ISSUE #3761: robottelo.config.base.FakeCapsuleSettings.validate() doesnt return anything
Need to fix it to return validation_errors

### PR DESCRIPTION
**Pull request by pgagne**
closes #3761

### CODE REVIEW

**Comment by pgagne** [comment]
Related to  #3611

**Comment by pgagne** [comment]
coveralls failing due to https://github.com/SatelliteQE/robottelo/pull/3428#issuecomment-242810050

**Comment by rochacbruno** [comment]
#3765 opened to track the coverage issue

**Comment by rochacbruno** [comment]
ACK

**Comment by oshtaier** [comment]
ACK

**Pull request merged**
