### PR TITLE
Make CaseImportance case-sensitive in testimony.yaml

### PR DESCRIPTION
**Pull request by mshriver**
If this is not accepted, I'll have to update #8163 to cover all capitalizations of the marks values.

Blocker:

- [x] https://github.com/SatelliteQE/testimony/issues/148

### CODE REVIEW

**Review by omkarkhatavkar — COMMENTED** [review]
```
(env) /home/okhatavk/Satellite/robottelo (update-testimony-importance) $ grep -r ":CaseComponent:.[a-z].*" tests | grep '.py' | grep -v 'Binary'
tests/foreman/sys/test_rename.py::CaseComponent: satellite-change-hostname
(env) /home/okhatavk/Satellite/robottelo (update-testimony-importance) $ grep -r ":CaseImportance:.[a-z].*" tests | grep '.py' | grep -v 'Binary'
tests/foreman/ui/test_contentview.py:    :CaseImportance:High
tests/foreman/cli/test_contentaccess.py::CaseImportance: high
(env) /home/okhatavk/Satellite/robottelo (update-testimony-importance) $ grep -r ":CaseLevel: [a-z].*" tests | grep '.py' | grep -v 'Binary'
(env) /home/okhatavk/Satellite/robottelo (update-testimony-importance) $ grep -r ":CaseAutomation:.[a-z].*" tests | grep '.py' | grep -v 'Binary'
```

**Comment by omkarkhatavkar** [comment]
@mshriver  let me know is that me only seeing that

**Comment by mshriver** [comment]
@omkarkhatavkar Check the components listing in testimony.yaml, `satellite-change-hostname` is lowercase, along with one or two other components with this syntax.

If you're suggesting I make every component name consistent, this will require some further changes. Most of them are CamelCase, but several have `-` separating words, and I didn't want to completely change these.

I'll look at the occurrence of `CaseImportance: high`, as testimony should have caught this.

I do not believe testimony enforces the whitespace between the token name and value, so `CaseImportance:High` is technically valid.

**Comment by mshriver** [comment]
@omkarkhatavkar `tests/foreman/cli/test_contentaccess.py` had an invalid CaseImportance as you highlighted, at the module level.

Each test case function within the module specifically defined CaseImportance in its local docblock, so the resulting testimony validation of the squashed token values did not catch this instance.  I've removed the line from that test module.

Thanks for being so thorough in your review here!

**Review by pondrejk — APPROVED** [review]

**Review by omkarkhatavkar — APPROVED** [review]
ACK

**Pull request merged**
