### PR TITLE
Transitions (hammer import) removal

### LINKED ISSUE #5061: Transition tooling removal
Remove hammer import automation as it will be removed in 6.3 and also check that hammer import subcommand is not present

- [x] test_import.py removal - PR https://github.com/SatelliteQE/robottelo/pull/5145
- [x] test_hammer::HammerCommandsTestCase.test_positive_all_options() - modify hammer_commands.json
- [x] settings cleanup PR #6464 , #6465, #6466

### PR DESCRIPTION
**Pull request by lpramuk**
See https://bugzilla.redhat.com/show_bug.cgi?id=1477992

Fixes #5061

### CODE REVIEW

**Comment by ldjebran** [comment]
@rplevka this PR also close issue https://github.com/SatelliteQE/robottelo/issues/4620

**Comment by oshtaier** [comment]
Is that functionality going to be removed completely? Because from BZ description or PR itself, it is not clear for me what kind of transition we plan

**Comment by lpramuk** [comment]
Yeah, completely.
It was decided by pm.

**Comment by rplevka** [comment]
so long `hammer import`, say hi to `elastic search` and `gutterball` if you meet them!

**Pull request merged**
