### PR TITLE
Cherrypick for Scap RFE

### PR DESCRIPTION
**Pull request by adarshdubey-star**
Parent PR - https://github.com/SatelliteQE/robottelo/pull/11836

### CODE REVIEW

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_oscap.py -k test_positive_oscap_run_via_local_files

**Comment by ogajduse** [comment]
@adarshdubey-star Do not forget to link the related issues to your PRs.

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_oscap.py -k test_positive_oscap_run_via_local_files

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_oscap.py -k test_positive_oscap_run_via_local_files

**Pull request closed without merging**
