### PR TITLE
Rebased and bumped PyYaml dependency

### PR DESCRIPTION
**Pull request by san7ket**

### CODE REVIEW

**Comment by vijay8451** [comment]
Could you please share some tests result around if any ..

**Comment by san7ket** [comment]
In-progress

**Comment by JacobCallahan** [comment]
Watching

**Comment by san7ket** [comment]
There is no test that passes, the failures are not related to version bump. I am trying to fix some test to get the results. 
This change implacts , test_variable, smartclass variable and parameters test cases

**Comment by san7ket** [comment]
/satellite6-standalone-automation/1563/testReport/tests.foreman.cli.test_host/HostParameterTestCase/
/satellite6-standalone-automation/1563/testReport/tests.foreman.cli.test_host/HostParameterTestCase/test_positive_set_multi_line_and_with_spaces_parameter_value/

All tests passed.

**Comment by san7ket** [comment]
The Job has unrelated automation failures

**Pull request merged**
