### PR TITLE
Fix valid_sync_interval, no underscore required

### PR DESCRIPTION
**Pull request by swadeley**
Hello

A recent change[1] introduced an underscore into 'custom cron'

[1] https://github.com/SatelliteQE/robottelo/pull/8706

### CODE REVIEW

**Comment by swadeley** [comment]
robottelo]$ pytest tests/foreman/api/test_syncplan.py -k test_positive_update_interval
=================================== test session starts ==============================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/sjw/sat6/robottelo, configfile: pyproject.toml
plugins: xdist-2.3.0, mock-3.6.1, ibutsu-1.16, forked-1.3.0, services-2.2.1, cov-2.12.1, reportportal-5.0.8
collected 114 items / 106 deselected / 8 selected                                                                                                                                                 

tests/foreman/api/test_syncplan.py ........                                                                                                                                                 [100%]

========================= 8 passed, 106 deselected, 21 warnings in 35.59s ==========================

**Comment by swadeley** [comment]
robottelo]$ pytest tests/foreman/api/test_syncplan.py -k test_positive_create_with_interval
=============================== test session starts ===========================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo, configfile: pyproject.toml
plugins: xdist-2.3.0, mock-3.6.1, ibutsu-1.16, forked-1.3.0, services-2.2.1, cov-2.12.1, reportportal-5.0.8
collected 114 items / 110 deselected / 4 selected                                                                                                                                                 

tests/foreman/api/test_syncplan.py ....                                                                                                                                                     [100%]

tests/foreman/api/test_syncplan.py::test_positive_create_with_interval[1]
tests/foreman/api/test_syncplan.py::test_positive_create_with_interval[1]
tests/foreman/api/test_syncplan.py::test_positive_create_with_interval[2]
tests/foreman/api/test_syncplan.py::test_positive_create_with_interval[2]
tests/foreman/api/test_syncplan.py::test_positive_create_with_interval[3]
tests/foreman/api/test_syncplan.py::test_positive_create_with_interval[3]
=========================== 4 passed, 110 deselected, 9 warnings in 23.88s =============================

**Review by devendra104 — APPROVED** [review]
ACK

**Review by ColeHiggins2 — APPROVED** [review]
ACK

**Review by omkarkhatavkar — APPROVED** [review]
ACK, tier1 and tier2 ack, hence merging

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
