### PR TITLE
Add new manual BZ tests for repositories and products

### PR DESCRIPTION
**Pull request by tpapaioa**
This PR adds new stubbed/manual tests to provide coverage for several BZs.

```
<Package cli>
  <Module test_product.py>
    <Function test_positive_product_sync_state>
  <Module test_repository.py>
    <Class TestRepository>
        <Function test_negative_update_red_hat_repo>
<Package ui>
  <Module test_product.py>
    <Function test_positive_bulk_action_advanced_sync>
  <Module test_repository.py>
    <Function test_positive_repo_discovery_change_ssl>
    <Function test_positive_remove_credentials>
    <Function test_positive_sync_status_repo_display>
    <Function test_positive_search_enabled_kickstart_repos>
    <Function test_positive_rpm_metadata_display>
```

### CODE REVIEW

**Review by latran — CHANGES_REQUESTED** [review]
Might be worthwhile to add tier markers to the test cases as well.

**Comment by mshriver** [comment]
@tpapaioa is this test content for 6.10?

**Comment by tpapaioa** [comment]
> @tpapaioa is this test content for 6.10?
No.

> Might be worthwhile to add tier markers to the test cases as well.
Done.

**Review by latran — APPROVED** [review]
ACK

**Review by mshriver — APPROVED** [review]

**Pull request merged**
