### PR TITLE
Fix expected user name

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ldap_authentication.py::test_positive_add_katello_role

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5984
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ldap_authentication.py::test_positive_add_katello_role --external-logging
Test Result : ============= 1 failed, 1 passed, 34 warnings in 970.38s (0:16:10) =============
```

**Review by pondrejk — APPROVED** [review]
ack, pending prt success

**Review by jameerpathan111 — APPROVED** [review]

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ldap_authentication.py::test_positive_add_katello_role

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6659
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ldap_authentication.py::test_positive_add_katello_role --external-logging
Test Result : ============= 1 failed, 1 passed, 44 warnings in 899.52s (0:14:59) =============
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ldap_authentication.py::test_positive_add_katello_role

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6670
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_ldap_authentication.py::test_positive_add_katello_role --external-logging
Test Result : ================== 2 passed, 44 warnings in 959.70s (0:15:59) ==================
```

**Comment by lhellebr** [comment]
merge

**Comment by jameerpathan111** [comment]
@lhellebr need rebase😅

**Pull request merged**
