### PR TITLE
Assert no version available on satellite-maintain upgrade list-versions for stream

### PR DESCRIPTION
**Pull request by Griffin-Sullivan**
On stream we do not have a version to upgrade to, so this test is failing. Adding a conditional to check on stream that there are no numbers in the output.

### CODE REVIEW

**Comment by Griffin-Sullivan** [comment]
trigger: test-robottelo
pytest: tests/foreman/maintain/test_upgrade.py::test_positive_satellite_maintain_upgrade_list

**Comment by Griffin-Sullivan** [comment]
Ok the initial approach didn't work because capsule showed kernel updates in the output of the command which contained numbers... Gonna need to rethink how to do this.

**Review by synkd — COMMENTED** [review]
Those kernel versions are showing because somewhere along the line `dnf` installed a new kernel version, but the system was not rebooted, so the system is still running an older kernel version. I wouldn't think this behavior would be exclusive to stream, but I admittedly do not have a sophisticated understanding of the upgrade test workflow, so I'm not sure when `dnf upgrade` gets run in which scenarios.

A couple of ways to work around this issue come to mind. You could reboot the system before running the `list-versions` command, or you could run `grep -v "Security:"` against the output of `list-versions` and then parse the result of that for your assertion. Do you anticipate issues with either of those approaches?

**Comment by Griffin-Sullivan** [comment]
@synkd SUCCESS!

**Review by synkd — APPROVED** [review]

**Pull request merged**
