### PR TITLE
Fixing locator for CV publish

### PR DESCRIPTION
**Pull request by oshtaier**
Tested both on downstream and upstream builds:
```
nosetests tests/foreman/ui/test_contentview.py -m test_positive_promote_with_custom_content
.
----------------------------------------------------------------------
Ran 1 test in 144.838s

OK
```

Needs also be merged into 6.2.z

### CODE REVIEW

**Comment by abalakh** [comment]
APT

**Comment by sghai** [comment]
ACK.. thank you @oshtaier for fix. 

However, let's hold this PR to merge until we get some confirmation from dev as why this locator is changed in 6.2.2. I think it was working earlier in 6.2.1

**Comment by oshtaier** [comment]
it seems as it was picked from upstream, but yeah, not a problem

**Comment by sghai** [comment]
Got reply from dev, the change is part of this 6.2.z bz: 1117753

**Comment by sghai** [comment]
We need to cherry-pick this commit for 6.2.z.

**Pull request merged**
