### PR TITLE
[6.15.z] Fix bind name

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16170

null

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_positive_create_with_https

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8418
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py::test_positive_create_with_https --external-logging
Test Result : ================= 2 passed, 202 warnings in 2720.57s (0:45:20) =================
```

**Comment by devendra104** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_positive_create_with_https

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8421
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py::test_positive_create_with_https --external-logging
Test Result : ================= 2 passed, 207 warnings in 2696.50s (0:44:56) =================
```

**Review by pondrejk — APPROVED** [review]

**Pull request merged**
