### PR TITLE
Remove old ui robottelo framework

### PR DESCRIPTION
**Pull request by oshtaier**
```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui/test_architecture.py 
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.6.5, pytest-4.0.2, py-1.5.3, pluggy-0.11.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/ashtayer/Desktop/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-06-07 16:49:08 - conftest - DEBUG - BZ deselect is disabled in settings

collected 1 item                                                                                                                                                                             

tests/foreman/ui/test_architecture.py .                                                                                                                                                [100%]

====================================================================================== 1 passed, 2 warnings in 121.67 seconds =========================================================================
```

### CODE REVIEW

**Comment by oshtaier** [comment]
1) Removed all old framework UI modules (`robottelo\ui\*` except `robottelo\ui\utils.py which consists from only one method that we are using for new framework)
2) Removed most of the test modules. Left ones that have chance ever be implemented/ported. Still need to review stubs, but it is out of scope of current PR
3) Renamed `tests\ui`-> `tests\ui_deprecated`, `tests\ui_airgun` -> `tests\ui`
4) Removed all not actual unit tests
5) Fixed a little docs

**Comment by ntkathole** [comment]
Adding just to remember, we need to raise PR in robottelo-ci as well to make changes accordingly in automation, upgrade and polarion jobs https://github.com/SatelliteQE/robottelo-ci/blob/master/scripts/satellite6-automation.sh#L98

**Comment by oshtaier** [comment]
thanks @ntkathole

**Comment by ntkathole** [comment]
@oshtaier few questions : 

- tests/foreman/ui/test_sso.py,test_statistic.py , test_system_registration.py and other many files is removed completely. I could not find them in any directory now. Am I missing something? 

- why tests/foreman/rhai/conftest.py is removed? I am not sure if we are using it for rhai tests.

**Comment by oshtaier** [comment]
> why tests/foreman/rhai/conftest.py is removed? I am not sure if we are using it for rhai tests.

It is not removed, but modified to use new ui folder

**Comment by oshtaier** [comment]
> tests/foreman/ui/test_sso.py,test_statistic.py , test_system_registration.py and other many files is removed completely. I could not find them in any directory now. Am I missing something?

1) Most of these files were present from the start of the project, so if no one implement them for last 5 years, so no one will ever implement them. And management guys mentioned many times to remove that old trash.
2) Some of functionality has nothing to do with UI and basically with test automation. It is just impossible to automate.
3) All of these files will still present in other branches for next many years (don't think that 6.5 branch will be removed in nearest two years), so if you need that functionality ever - you can go there.

**Comment by ntkathole** [comment]
Thanks @oshtaier . 
One last question, I see some test files (test_virt_who_config.py, test_task.py, test_myaccount.py, test_statistic.py, test_navigation.py, test_puppetmodule.py) which has tests automated in older UI but not in new and still we are removing them. Might be these tests are already on your radar to move to new UI. Can we just keep them rather than deleting so that we don't miss them.

`Sorry if we already automated them and I couldn't find in ui_airgun directory.`

**Comment by vijay8451** [comment]
@oshtaier If I understood correct ,  removed `UI` tests are either already covered in `ui_airgun` or not needed to cover(if pending) in future ?  
And the tests which do have a chance ever be implemented/ported in future under `ui_airgun` moved under `tests\ui_deprecated` ?

**Comment by oshtaier** [comment]
@vijay8451 you are right, that was an initial idea

**Comment by oshtaier** [comment]
@ntkathole 
With new approach, we decide to move out from tier1/component testing completely. And additionally to that we want to decrease amount of existing test cases in other areas significantly, to have more end to end cases than ones for boundary analysis, negative scenario and etc. Mentioned modules do not meet described expectations.
Anyway, I removed them for a different reasons. For example:

`test_navigation.py` - here we have only tests which are actually tier0 unit tests and they responsible for validating navigation across all the pages of application. In new framework that fact is already proved by ideology from navmazing and `breadcrumb` elements. We always validate that we moving into right direction when wanted perform any operation in web UI. After we merge https://github.com/SatelliteQE/airgun/pull/329, we finish the cycle and have near perfect navigation validation

`test_puppetmodule.py` - we have enough test coverage in that direction in `test_repository.py` (create, sync, resync)

`test_task.py` - contains zero of valid test coverage. Anyway, we have much better test coverage in `test_positive_task_status` test in https://github.com/SatelliteQE/robottelo/blob/76ead823ba10654dddc0783f935dde2c0bf573c1/tests/foreman/ui_airgun/test_dashboard.py#L188

`test_virt_who_config.py` - was moved to deprecated folder, not deleted

`test_statistic.py` - tier1 tests that refer to charts. It is really time consuming to provide test coverage for charts in automation. That just doesn't worth the effort

`test_hostunification.py` - refer to procedure of host/content host unification that we had in 6.2 or 6.3. That is not actual to validate anymore. Coverage that we have here, we basically implement in `test_host.py` and `test_contenthost.py` modules.

and etc.

**Pull request merged**
