### PR TITLE
Fix capsule KS sync test

### PR DESCRIPTION
**Pull request by vsedmik**

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_contentmanagement.py::TestCapsuleContentManagement::test_positive_sync_kickstart_repo

**Comment by vsedmik** [comment]
SatLab is quite busy with the new snap so PRT failed with timeout on checkout. Let's rerun later.

**Comment by ogajduse** [comment]
@omkarkhatavkar PRT apparently sets `settings.server.version.rhel_version` to `7` instead of `8`. Is it something that you can quickly fix?

**Comment by omkarkhatavkar** [comment]
@ogajduse you can pass `deploy_rhel_version: 8` in PRT comment

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_contentmanagement.py::TestCapsuleContentManagement::test_positive_sync_kickstart_repo
deploy_rhel_version: 8

**Comment by latran** [comment]
@vsedmik Run failed.  Please check.

**Comment by ogajduse** [comment]
@latran There is nothing to check from @vsedmik's side. PRT did not change `deploy_rhel_version` even if he forced it in the PRT trigger comment.
What might went wrong now, @omkarkhatavkar?

**Comment by omkarkhatavkar** [comment]
Ohh It was capsule deploy arguments, we are overriding the satellite server properties but missed the capsule. Let me get that PR in CI

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_contentmanagement.py::TestCapsuleContentManagement::test_positive_sync_kickstart_repo
deploy_rhel_version: 8

**Review by latran — APPROVED** [review]

**Review by JacobCallahan — APPROVED** [review]

**Pull request merged**
