### PR TITLE
Removed test_host_system_unification.py from cli tests

### PR DESCRIPTION
**Pull request by sthirugn**
The tests for content hosts and hosts are already covered in
* test_contenthost.py
* test_host.py

### CODE REVIEW

**Comment by sghai** [comment]
Thanks for making this change.. :+1: 

ACK

**Comment by abalakh** [comment]
ACK

**Comment by sthirugn** [comment]
@abalakh :+1:

**Comment by sthirugn** [comment]
Comments updated and rebased

**Comment by abalakh** [comment]
ACK

**Pull request merged**
