### PR TITLE
Nilclass publish test

### PR DESCRIPTION
**Pull request by sambible**
BZ automation work here, will look weird since it's based on a PR that hasnt' been merged, so it will show a large amount of changes, given that it's tracking the move from contentview to contentview_old. 

Test will be in the test_contentview.py file.

### CODE REVIEW

**Comment by JacobCallahan** [comment]
Converted to draft because, until that other PR is merged, it's very hard to determine what the changes are here. Can you link the PR this depends on? It also looks like you'll need to rebase and resolve a merge conflict.

**Comment by sambible** [comment]
moving this back to review, as the base PR got merged, and this is easy to review now!

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k 'test_different_org_publish'
airgun: 948

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k 'test_different_org_publish'
airgun: 948

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k 'test_different_org_publish'
airgun: 948

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k 'test_different_org_publish'
airgun: 948

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k 'test_different_org_publish'
airgun: 948

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k 'test_different_org_publish'
airgun: 948

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k 'test_different_org_publish'

**Comment by jyejare** [comment]
@sambible Pre-commit checks are failing, please look into them !

**Comment by jyejare** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k test_different_org_publish

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 38
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_contentview.py -k test_different_org_publish
Test Result : =========== 2 deselected, 10 warnings, 1 error in 735.60s (0:12:15) ============
```

**Comment by ogajduse** [comment]
Switching this PR to Draft since there was no action taken on it for months.

**Comment by lhellebr** [comment]
@sambible please let us know if we should keep this as draft or just close it

**Pull request closed without merging**
