### PR TITLE
Memory optimization for GCE tests

### PR DESCRIPTION
**Pull request by ogajduse**
## Problem statement
* Memory consumption of the container that runs the GCE tests spikes up to **7.3 GB**
* We need more HW resources to run the tests

## Root cause
* `gce_latest_rhel_uuid` fixture lists all images across all public projects which results in 2 GB of data being stored in the memory
* This variable is defined in a session-scoped fixture, therefore the data are cleaned up by GC at the very end of the test session

## Solution
* Request only a limited subset of images from the specific projects that store RHEL images that we request
  * let the _Google Compute API_ filter the templates for us

## Results
From my observation, the implementation I propose consumes only 16% of what the original code stores.

## Notes
I want to thank @rplevka and @lpramuk for their help in finding the root cause.

Requires a new wrapanapi release containing the patch from RedHatQE/wrapanapi#466.

### CODE REVIEW

**Comment by JacobCallahan** [comment]
@ogajduse wrapanapi PR has been merged. please give PRT a try

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_computeresource_gce.py

**Comment by adarshdubey-star** [comment]
I think we need this in for PRT to pass https://github.com/SatelliteQE/robottelo/pull/11916

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_computeresource_gce.py

**Comment by jyejare** [comment]
@adarshdubey-star I merged that dependency PR as we half changes in this PR. Lets retrigger PRT here once we have image refreshed and all cherrypicks merged!

**Review by jyejare — APPROVED** [review]
Only one test failed with `HTTP Error` for Power test case , does not relates to the changes in the PR I think. @adarshdubey-star Can you confirm to merge this PR ?

**Comment by adarshdubey-star** [comment]
> Only one test failed with `HTTP Error` for Power test case , does not relates to the changes in the PR I think. @adarshdubey-star Can you confirm to merge this PR ?

Yeah, I looked into the failure a timeout caused the issue, good to merge.

**Review by adarshdubey-star — APPROVED** [review]
Great work , @ogajduse

**Comment by ogajduse** [comment]
All tests passed except one which failed with
```
{"message":"ERF42-7634 [Foreman::Exception]: Timeout has occurred while communicating with 4iXNtqntSE (us-east1-b-Google)"}
```

In `robottelo.log` I see that we query only
```
2023-07-18 09:43:25 - googleapiclient.discovery - DEBUG - URL being requested: GET https://compute.googleapis.com/compute/v1/projects/rhel-cloud/global/images?filter=name%3Arhel-7%2A&alt=json
2023-07-18 09:43:28 - googleapiclient.discovery - DEBUG - URL being requested: GET https://compute.googleapis.com/compute/v1/projects/rhel-sap-cloud/global/images?filter=name%3Arhel-7%2A&alt=json
```

I will post the RAM usage of the pytest session once I have the data available.

**Review by Gauravtalreja1 — APPROVED** [review]

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_computeresource_gce.py
pod_resources_size: medium

**Comment by ogajduse** [comment]
@omkarkhatavkar OCP pod resources telemetry is not running due to some issues at the moment. I will re-run the tests once again anyway.

**Comment by omkarkhatavkar** [comment]
> od resources telemetry is not running due to some issues at the moment. I will re-run the tests once again anyway.

@ogajduse earlier test failed that would have run on small, it still fails on small which is fine, let's try and see if it works on medium pod size.

**Comment by omkarkhatavkar** [comment]
my bad looking at the test results more closely it was not failed because of the ram, it works fine it could be some other test issue.

**Comment by ogajduse** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_computeresource_gce.py
pod_resources_size: medium

**Comment by ogajduse** [comment]
Memory usage of the builder container from the last PRT run
image

**Comment by rplevka** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_computeresource_gce.py
pod_resources_size: medium

**Pull request merged**
