### PR TITLE
Use py.test decorators for CLI tests.

### PR DESCRIPTION
**Pull request by omaciel**
This pull request adds `py.test` markers for all existing automated tests. It also
removes blank lines from docstrings (for some modules) and removes the `pass`
argument from many `stubbed` tests.

### CODE REVIEW

**Comment by omaciel** [comment]
Please only merge if #3078 gets merged.

**Comment by sthirugn** [comment]
ACK

**Comment by elyezer** [comment]
ACK, pending rebase.

**Comment by omaciel** [comment]
Rebased

**Pull request merged**
