### PR TITLE
Update UI smoke tests

### PR DESCRIPTION
**Pull request by elyezer**
Use the VirtualMachine methods to install katello cert RPM and register
the vm as a content host.

Improve formatting and drop single use variables. Also use constants
whenever possible.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
This all looks great to me. ACK.

**Comment by elyezer** [comment]
Missing test result, will paste here asap.

**Comment by sthirugn** [comment]
ACK

**Comment by elyezer** [comment]
Rebased

**Comment by sthirugn** [comment]
@elyezer as a second thought, lets wait on this.  We already have a ton of nailgun changes going in which may need some fixes.  Lets get this PR in on Monday.

**Comment by elyezer** [comment]
@sthirugn :+1:

**Comment by oshtaier** [comment]
ACK
Please, rebase once more

**Comment by elyezer** [comment]
@oshtaier rebased.

**Comment by sthirugn** [comment]
release is signed off today.  safe to merge this pr now.

**Comment by sthirugn** [comment]
I will rerun automation later today and will investigate the results tomorrow.

**Pull request merged**
