### PR TITLE
Move ansible API tests to Ansible-Cfgmgmt and REX classes

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
### Problem Statement
Ansible tests are mixed in API ansible module, which need to be consistent as CLI/UI module

### Solution
Move Ansible API tests to Ansible-ConfigurationManagement and Ansible-RemoteExecution classes, And few other minor fixes.

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_ansible.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6315
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_ansible.py --external-logging
Test Result : ================ 12 passed, 1140 warnings in 4724.02s (1:18:44) ================
```

**Review by Griffin-Sullivan — APPROVED** [review]
This diff is hard to read so as long as your team is happy with the change I'm good to merge.

**Comment by Griffin-Sullivan** [comment]
I guess it's easier to read https://github.com/SatelliteQE/robottelo/blob/0db0c68ff1b0dc7eb0a86cdde516cd37d978caf9/tests/foreman/api/test_ansible.py here

**Review by synkd — APPROVED** [review]

**Review by shubhamsg199 — APPROVED** [review]
ACK

**Pull request merged**
