### PR TITLE
Add fixture to cut Satellite off nameservers

### PR DESCRIPTION
**Pull request by vsedmik**

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_http_proxy.py -k test_positive_assign_http_proxy_to_products

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6473
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_http_proxy.py -k test_positive_assign_http_proxy_to_products --external-logging
Test Result : =========== 1 passed, 4 deselected, 13 warnings in 719.45s (0:11:59) ===========
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6474
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_http_proxy.py -k test_positive_assign_http_proxy_to_products --external-logging
Test Result : =========== 1 passed, 4 deselected, 13 warnings in 844.08s (0:14:04) ===========
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6477
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_http_proxy.py -k test_positive_assign_http_proxy_to_products --external-logging
Test Result : =========== 1 passed, 4 deselected, 13 warnings in 853.87s (0:14:13) ===========
```

**Pull request closed without merging**
