### PR TITLE
adding try finally block to vm.get() in order to fetch the log files …

### PR DESCRIPTION
**Pull request by anarang**
…form VM;

minor changes in Makefile.
 Did cherry-pick <commit-id> from the master branch.
The PR has been merged in master before.

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK

**Comment by rplevka** [comment]
just a thought - if you do this just to collect some artifacts - wouldn't it be better to put the collecting into tearDown method of the test?

**Comment by anarang** [comment]
@rplevka that is inside the vm context manager as the file is to be fetched from that, so tear down isn't an option as of now. For that it shall require a lot of code refactoring involving creating a vm in setup and collecting artifacts,destroying vm in tear down. I shall do that later, so for now, we can let that be I guess.

**Comment by rplevka** [comment]
ACK

**Pull request merged**
