### PR TITLE
[6.1.z] Cherry-pick changed @skip_if_bz to consider sat version and f…

### LINKED ISSUE #3868: @skip_if_bz_bug_open logic should involve version check
since we support multiple versions of katello (satellite), and not all bug fixes are being backported to all versions, the following scenario might (and most probably **will**) occur:

1.) A nasty bug is discovered and reported on `sat-6.2.2`
2.) An appropriate test with `@skip_if_bz_bug_open('123456')` is being created and pushed to `master`, and `6.2.z` branches.
3.) Devels mark the target version as `sat-6.3`, deliver a fix and close the BZ.
4.) `@skip_if_bz_bug_open` no longer skips the bug.
5.) test passes on `6.3.*` but starts to fail on `6.2.z` as the fix hasn't been (and is never going to be) backported.

Shall we start deleteing such test cases from version branches which are not supported, or at least start marking them as `@stubbed` or shall we implement some version check mechanism (check the BZ flags, etc.) to the BZ decorators?

discuss ;)

### PR DESCRIPTION
**Pull request by renzon**
…lags

close #3868

### CODE REVIEW

**Comment by renzon** [comment]
@lpramuk @sghai: test decreased because of file duplication, base was renamed to settings. I keep both to avoid a big refactoring on entire code base.

**Comment by oshtaier** [comment]
Can you run few tests please?

**Comment by renzon** [comment]
Test on Sat 6.3:

```console
 32 tests deselected by '-k LocationTestCase and test_positive_create_with_description' 
=================== 1 passed, 32 deselected in 19.93 seconds ===================
```

**Comment by renzon** [comment]
Test skipped on Sat 6.2:

```console

 32 tests deselected by '-k LocationTestCase and test_positive_create_with_description' 
=================== 1 skipped, 32 deselected in 8.46 seconds ===================
```

**Comment by renzon** [comment]
@oshtaier I run tests for a BZ which has only sat-6.3 flag:

https://bugzilla.redhat.com/show_bug.cgi?id=1233612

So it must run only on sat version >= 6.3.

**Comment by rochacbruno** [comment]
As @sghai is on training this week I changed the requested reviewer to @oshtaier

**Comment by renzon** [comment]
@rochacbruno You can review it as well ;)

**Comment by oshtaier** [comment]
As it goes into 6.1 - I am not going into deep details. Basically, looks good

**Pull request merged**
