### PR TITLE
Drop assertion messages for CLI smoke tests

### PR DESCRIPTION
**Pull request by elyezer**
Robottelo provides information about the command and the return code
when it finds a failure, there is no need to recreate these messages.

This will also make smoke stop failing due to ascii codec errors.

### CODE REVIEW

**Comment by omaciel** [comment]
APT

**Comment by sthirugn** [comment]
APT

**Comment by JacobCallahan** [comment]
third APT :)

**Comment by Ichimonji10** [comment]
`+48 -214`

:+1:

**Pull request merged**
