### PR TITLE
[6.14.z] Content View Audit Tests

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11433

Leaving this in draft for now, but this will contain a few of the initial tests for the publish audit feature. 

Needs this nailgun PR: https://github.com/SatelliteQE/nailgun/pull/922

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_ccv_audit_scenarios tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_check_needs_publish_flag tests/foreman/api/test_contentview.py::TestContentViewRedHatContent::test_cv_audit_scenarios
nailgun: 922

**Comment by Gauravtalreja1** [comment]
@sambible Could you please investigate the PRT failure?

**Comment by ogajduse** [comment]
I believe that we should merge SatelliteQE/nailgun#922 first and then re-run PRT using 6.14.z cherry-pick PR of SatelliteQE/nailgun#922.
But SatelliteQE/nailgun#922 explicitly states `NoCherryPick`, which confuses me. Can you look into it @sambible?

**Comment by sambible** [comment]
@ogajduse is correct - the sister Nailgun cherrypick needs to be merged before this will pass. Those labels have been updated, it is now properly set to cherrypick to 6.14

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_ccv_audit_scenarios tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_check_needs_publish_flag tests/foreman/api/test_contentview.py::TestContentViewRedHatContent::test_cv_audit_scenarios
nailgun: 922

**Review by vsedmik — APPROVED** [review]

**Pull request merged**
