### PR TITLE
e2e cli minor fix

### PR DESCRIPTION
**Pull request by pondrejk**

### CODE REVIEW

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_cli_endtoend.py -k test_positive_cli_end_to_end

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_cli_endtoend.py -k test_positive_cli_end_to_end

**Review by omkarkhatavkar — APPROVED** [review]

**Comment by omkarkhatavkar** [comment]
@pondrejk PRT failing

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_cli_endtoend.py -k test_positive_cli_end_to_end

**Review by lhellebr — CHANGES_REQUESTED** [review]
This seems related and incorrect:
```
assert content_host['content-information'][0]['content-view'] == content_view['name']
E       AssertionError: assert '' == 'YwlTlMsnMe'
E         - YwlTlMsnMe
```

**Comment by jyejare** [comment]
@pondrejk Is this still valid? it has a stale label marked now, please resume on this else this will be auto closed.

**Pull request closed without merging**
