### PR TITLE
fix in alternate directory rex test

### PR DESCRIPTION
**Pull request by pondrejk**
making sure host is registered to the destructive satellite

### CODE REVIEW

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_remoteexecution.py -k use_alternate_directory

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_remoteexecution.py -k use_alternate_directory

**Comment by adarshdubey-star** [comment]
Can you visit the PRT failure?

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_remoteexecution.py -k use_alternate_directory

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_remoteexecution.py -k use_alternate_directory

**Comment by pondrejk** [comment]
Passing locally with latest changes against 6.12:
```
pytest tests/foreman/destructive/test_remoteexecution.py -k use_alternate_directory
================================================ test session starts ================================================
platform linux -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/pondrejk/Documents/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, reportportal-5.1.2, ibutsu-2.2.4, forked-1.4.0, cov-3.0.0, mock-3.10.0, xdist-3.0.2
collected 2 items / 1 deselected / 1 selected      

tests/foreman/destructive/test_remoteexecution.py  .
```

Though in prt I'm getting template not found for some reason

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_remoteexecution.py -k use_alternate_directory

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_remoteexecution.py -k use_alternate_directory
inventory: rhv-rhvm02

**Comment by Gauravtalreja1** [comment]
PRT checkouts 6.11 instances in above runs, where `Run Command - Script Default` job-template doesn't exist, but it exists as `Run Command - SSH Default`. This seems to be a PRT failure, so wouldn't block this PR.

**Review by Gauravtalreja1 — APPROVED** [review]

**Review by adarshdubey-star — APPROVED** [review]

**Pull request merged**
