### PR TITLE
[6.15.z] Test CV incremental update & publish time

### PR DESCRIPTION
**Pull request by damoore044**
### Problem Statement
Failed auto-CP to 6.15.z
Original Pull Request #14749 

```
trigger: test-robottelo
pytest: tests/foreman/longrun/test_inc_updates.py::test_positive_incremental_update_time
```

### CODE REVIEW

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_inc_updates.py::test_positive_incremental_update_time

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6572
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/longrun/test_inc_updates.py::test_positive_incremental_update_time --external-logging
Test Result : ================== 1 passed, 14 warnings in 971.72s (0:16:11) ==================
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_inc_updates.py::test_positive_incremental_update_time

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6578
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/longrun/test_inc_updates.py::test_positive_incremental_update_time --external-logging
Test Result : ================== 1 passed, 14 warnings in 938.51s (0:15:38) ==================
```

**Review by lpramuk — APPROVED** [review]

**Comment by damoore044** [comment]
@lpramuk had changed as this was identified as a CustomerCase so put that in title, just a tiny addition

**Pull request merged**
