### PR TITLE
test_positive_end_to_end_bulk_update (#6956)

### PR DESCRIPTION
**Pull request by swadeley**
* Test the Update All Packages button on Update Packages dialogue
 * Use the Host Collection view to get to it.

### CODE REVIEW

**Comment by swadeley** [comment]
This is already in master branch.

 This change depends on https://github.com/SatelliteQE/airgun/pull/345 (now merged)

**Comment by swadeley** [comment]
@mirzal sory about that, it was due to my misunderstanding. When I was told 6.5.z branch still uses /ui_airgun directory I applied the change to the file in that directory and then removed the file in /ui when I should have just done a checkout of the file to revert my changes in that /ui directory.

I have now done that and forced pushed.

Thank you

**Comment by mirzal** [comment]
@swadeley no need to apologize. I'm pretty sure we could remove that file and nothing would happen, as it isn't used in 6.5.z branch anyway. It's just a little unexpected thing to do, that's all.

Anyway, we're all set now. I mean, once we have Tier2 reviewer ACK.

**Comment by swadeley** [comment]
Thank you all

**Pull request merged**
