### PR TITLE
[6.14.z] - removing the import entities from nailgun and moving target_sat

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
### Problem Statement
Needs to be a cherrypick of https://github.com/SatelliteQE/robottelo/pull/12989 to 6.14.z

### Solution
This PR helps to do the cherrypick https://github.com/SatelliteQE/robottelo/pull/12989

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pod_resources_size: large

**Comment by pondrejk** [comment]
Hi @omkarkhatavkar, I pulled in the changes to my existing PR https://github.com/SatelliteQE/robottelo/pull/13048, but I start getting `TypeError: Webhooks.__init__() got multiple values for argument 'server_config'` after the move from  entities.Webhook to target_sat.api.Webhook. Any idea what might to be the problem?

**Comment by omkarkhatavkar** [comment]
> Hi @omkarkhatavkar, I pulled in the changes to my existing PR #13048, but I start getting `TypeError: Webhooks.__init__() got multiple values for argument 'server_config'` after the move from entities.Webhook to target_sat.api.Webhook. Any idea what might to be the problem?

This is resolved using Nailgun PR here https://github.com/SatelliteQE/nailgun/pull/1029, Thanks @pondrejk raising it up

**Review by JacobCallahan — APPROVED** [review]

**Review by pondrejk — APPROVED** [review]

**Pull request merged**
