### PR TITLE
Fix guardtime, improve sync tests

### PR DESCRIPTION
**Pull request by swadeley**
Hello

When I added "guardtime" to cron sync plan UI test I forgot it was in seconds. Fixing that now for the UI test.

Also adding similar guardtime code to the CLI tests.

Thank you

### CODE REVIEW

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest:  tests/foreman/cli/test_syncplan.py -k future_sync_date

**Review by omkarkhatavkar — APPROVED** [review]

**Review by ColeHiggins2 — APPROVED** [review]
ack

**Review by pondrejk — APPROVED** [review]
is the rpr failure significant? apart form that, it looks ready to merge

**Comment by swadeley** [comment]
> is the rpr failure significant? apart form that, it looks ready to merge

I will do some local testing, lets hold off the merge.

**Comment by swadeley** [comment]
Hi

checking test build 558, it was only this test that failed: 
test_positive_synchronize_custom_products_future_sync_date

It failed on checking the second product was not synced:
"search": "Actions::Katello::Repository::Sync and organization_id = 3 and resource_id = 3",

so I am increasing the cron multiple to 5 and the guardtime to 3 mins (180 secs)  for that test as it needs more time to make checks between the steps (its the only once with multiple products).

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_product_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_products_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_rh_product_future_sync_date tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_past_sync_date

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_product_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_products_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_rh_product_future_sync_date tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_past_sync_date

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_product_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_products_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_rh_product_future_sync_date tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_past_sync_date

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_product_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_products_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_rh_product_future_sync_date tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_past_sync_date

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_product_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_products_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_rh_product_future_sync_date tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_past_sync_date

**Comment by JacobCallahan** [comment]
@swadeley you have a number of ACKs already, so when you are finished, feel free to merge

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_product_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_products_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_rh_product_future_sync_date tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_past_sync_date

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: test_positive_synchronize_custom_products_future_sync_date

**Comment by swadeley** [comment]
HI, I added an extra 30 sec guard time to the test with multiple products as it failed once but then passed the next time.

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_product_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_products_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_rh_product_future_sync_date tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_past_sync_date

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_product_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_products_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_rh_product_future_sync_date tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_past_sync_date

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_product_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_custom_products_future_sync_date tests/foreman/cli/test_syncplan.py::test_positive_synchronize_rh_product_future_sync_date tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_past_sync_date

**Pull request merged**
