### PR TITLE
[6.15.z] CP of API-Errata modifications

### PR DESCRIPTION
**Pull request by damoore044**
Failed cherry-pick into 6.15.z of #13515 from master.
Failed auto-CP merge request: #13830

### PRT case:
```
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py
```

### CODE REVIEW

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

**Comment by ogajduse** [comment]
@damoore044 This PR seems to duplicate the patch from #13829 that was created automatically. Can you please check?

**Review by ogajduse — APPROVED** [review]

**Comment by ogajduse** [comment]
@omkarkhatavkar FYSA: GHA successfully created backport PR for 6.15.z branch #13829, however, it also created issue #13830 which states that the automatic backport failed. I believe that it confused David; therefore, he spent extra time manually cherry-picking the patch to 6.15.z - this PR.
Can you please look into what happened? This is not the first time I have seen such a thing.

**Comment by damoore044** [comment]
@pondrejk Yes that right, I had thought the CP-action into 6.15.z had failed, so opened this manual CP

**Comment by omkarkhatavkar** [comment]
Okay @damoore044 @ogajduse Thanks for raising it. I will try to come up with a way to handle this.

**Pull request merged**
