### PR TITLE
Adding documentation for valid_data_list() helper function

### PR DESCRIPTION
**Pull request by sthirugn**
valid_data_list() helper function is widely used to create valid data set for different attributes.  Although this works great in most entities, there are few entities which don't honor these standards and they should not use this helper function.  This docstring text will help future coders to be aware of this issue.

### CODE REVIEW

**Comment by sthirugn** [comment]
Rebased

**Comment by oshtaier** [comment]
ACK

**Comment by elyezer** [comment]
Do `make docs-clean docs` shows any warning about this docstring?

**Comment by sthirugn** [comment]
@elyezer nope
```sh
# make docs-clean docs
rm -rf _build/*
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3b1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 20 source files that are out of date
updating environment: 20 added, 0 changed, 0 removed
reading sources... [100%] reviewing_PRs                                         
/home/suresh/hacking/framework/robottelo/tests/foreman/cli/test_import.py:docstring of tests.foreman.cli.test_import.get_sat6_id:4: ERROR: Unexpected indentation.
/home/suresh/hacking/framework/robottelo/tests/foreman/cli/test_import.py:docstring of tests.foreman.cli.test_import.get_sat6_id:5: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/suresh/hacking/framework/robottelo/docs/api/tests.foreman.ui.rst:54: WARNING: autodoc: failed to import module u'tests.foreman.ui.test_discovery'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 378, in import_object
    __import__(self.modname)
ImportError: No module named test_discovery
/home/suresh/hacking/framework/robottelo/tests/foreman/ui/test_host.py:docstring of tests.foreman.ui.test_host.Host.setUpClass:11: WARNING: Enumerated list ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] reviewing_PRs                                          
<autodoc>:None: WARNING: py:data reference target not found: robottelo.config.conf
/home/suresh/hacking/framework/robottelo/docs/api/tests.foreman.cli.rst:30: WARNING: py:class reference target not found: Architecture
/home/suresh/hacking/framework/robottelo/docs/api/tests.foreman.cli.rst:37: WARNING: py:class reference target not found: Domain
/home/suresh/hacking/framework/robottelo/docs/api/tests.foreman.cli.rst:55: WARNING: py:class reference target not found: Environment
/home/suresh/hacking/framework/robottelo/docs/api/tests.foreman.cli.rst:67: WARNING: py:class reference target not found: HostGroup
/home/suresh/hacking/framework/robottelo/docs/api/tests.foreman.cli.rst:31: WARNING: py:class reference target not found: Model
/home/suresh/hacking/framework/robottelo/docs/api/tests.foreman.ui.rst:51: WARNING: py:mod reference target not found: tests.foreman.ui.test_discovery
generating indices... genindex py-modindex
highlighting module code... [  2%] tests.foreman.cli.test_host_system_unificatiohighlighting module code... [  7%] tests.foreman.performance.test_candlepin_conchighlighting module code... [ 32%] tests.foreman.performance.test_candlepin_conchighlighting module code... [ 75%] tests.foreman.performance.test_candlepin_conchighlighting module code... [100%] robottelo.ui.hostgroup                       
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 11 warnings.

Build finished. The HTML pages are in _build/html.
```

**Comment by sthirugn** [comment]
screenshot

**Comment by abalakh** [comment]
Rebase, please?

**Comment by sthirugn** [comment]
@abalakh rebased

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
