### PR TITLE
exception.message was deprecated in Python 2.6, removed in 3. str in …

### LINKED ISSUE #5886: [py3.6] object has no attribute 'message'
This is a issue to track all tests failing with the [subject]

there are errors on multiple objects:
- AttributeError: 'CLIFactoryError' object has no attribute 'message'
- AttributeError: 'UINoSuchElementError' object has no attribute 'message'
- AttributeError: 'UIError' object has no attribute 'message'
- AttributeError: 'HTTPError' object has no attribute 'message'
- AttributeError: 'CLIFactoryError' object has no attribute 'message'
- AttributeError: 'ValueError' object has no attribute 'message'

### PR DESCRIPTION
**Pull request by jhutar**
…3 is kinda unicode in 2.

Fixes  #5886 - well, maybe not completely. I was unable to test UI tests in my setup. Some Docker issues - probably just some config issue.

### CODE REVIEW

**Comment by jhutar** [comment]
```
(venv3) [pok@localhost robottelo]$ py.test tests/foreman/cli/test_activationkey.py::ActivationKeyTestCase::test_negative_create_with_invalid_name tests/foreman/cli/test_activationkey.py::ActivationKeyTestCase::test_negative_create_with_usage_limit_with_invalid_integers tests/foreman/cli/test_activationkey.py::ActivationKeyTestCase::test_negative_create_with_usage_limit_with_not_integers tests/foreman/api/test_classparameters.py::SmartClassParametersTestCase::test_positive_list_with_non_admin_user
============================= test session starts ==============================
platform linux -- Python 3.6.4, pytest-3.4.0, py-1.5.3, pluggy-0.6.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/pok/Checkouts/robottelo, inifile:
plugins: services-1.2.1, mock-1.6.3
collected 4 items
2018-03-28 22:42:20 - conftest - DEBUG - Collected 4 test cases


tests/foreman/cli/test_activationkey.py ...                              [ 75%]
tests/foreman/api/test_classparameters.py .                              [100%]

============================== 0 tests deselected ==============================
========================== 4 passed in 65.06 seconds ===========================
```

**Comment by jhutar** [comment]
In last commit are some more fixes which just looks like it should happen, but I was able to test only a small subset. Here is one example:
```
(venv3) [pok@localhost robottelo]$ py.test tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_negative_add_non_composite_cv_to_composite
============================= test session starts ==============================
platform linux -- Python 3.6.4, pytest-3.4.0, py-1.5.3, pluggy-0.6.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/pok/Checkouts/robottelo, inifile:
plugins: services-1.2.1, mock-1.6.3
collected 1 item
2018-03-28 23:02:25 - conftest - DEBUG - Collected 1 test cases


tests/foreman/cli/test_contentview.py .                                  [100%]

============================== 0 tests deselected ==============================
========================== 1 passed in 36.61 seconds ===========================
```

**Comment by jhutar** [comment]
@sghai , when this was approved by Bruno (thanks!), can I just merge it, or is somebody else supposed to do so?

**Comment by sghai** [comment]
@jhutar : the usual process is two have two 'Acks'  on PR and then we are good with merge.

**Comment by ldjebran** [comment]
@jhutar please provide tests results for all the modified tests in py2 and py3 if you have configuration problems please let me know, will help you with.

**Comment by jhutar** [comment]
Hello @ldjebran . IIRC it was decided fixes should be P3 only. For test results: I believe that would require full test-suite to run. I'm sure you are more experienced with Jenkins jobs. Could you please prepare me a Satellite I can run against and suggest robottelo.properties I need for that Satellite?

**Comment by ldjebran** [comment]
@jhutar many thanks

**Pull request merged**
