### PR TITLE
eol banner

### PR DESCRIPTION
**Pull request by pondrejk**
### Problem Statement
testing end of life banner 

### Solution
requires https://github.com/SatelliteQE/airgun/pull/1049

### CODE REVIEW

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_eol_banner.py -k test_positive_eol_banner_e2e
airgun: 1049

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_eol_banner.py -k test_positive_eol_banner_e2e
airgun: 1049

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_eol_banner.py -k test_positive_eol_banner_e2e
airgun: 1049

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_eol_banner.py -k test_positive_eol_banner_e2e
airgun: 1049

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_eol_banner.py -k test_positive_eol_banner_e2e
airgun: 1049

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_eol_banner.py -k test_positive_eol_banner_e2e

**Comment by lhellebr** [comment]
Why no-cheryrpick?

**Comment by pondrejk** [comment]
Hello, please dont't stale it :) This has been merged separately for 6.15 therefore no cherry pick. Atm the version definition on stream builds prevents the banner from working there, so the tests won't pass in this branch. I'll check back with the resolution

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_eol_banner.py -k test_positive_eol_banner_e2e

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_eol_banner.py -k test_positive_eol_banner_e2e

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5846
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_eol_banner.py -k test_positive_eol_banner_e2e
Test Result : ================= 1 passed, 11 warnings in 1019.86s (0:16:59) ==================
```

**Comment by pondrejk** [comment]
This was reviewed and merged as a 6.15 feature in https://github.com/SatelliteQE/robottelo/pull/13463, master was waiting on a code change in stream that is now in, prt passes

**Pull request merged**
