### PR TITLE
UI: Org search refactor

### PR DESCRIPTION
**Pull request by lpramuk**
UI: Org search refactor

(Part of #2930)

### CODE REVIEW

**Comment by oshtaier** [comment]
```
def remove(self, org_name, really=True):
         """Remove Organization in UI."""
         Navigator(self.browser).go_to_org()
         self.delete_entity(
             org_name,
             really,
             locators['org.org_name'],
             locators['org.delete'],
             drop_locator=locators['org.dropdown'],
         )
```
will fail.
You need:
```
def remove(self, org_name, really=True):
         """Remove Organization in UI."""
         Navigator(self.browser).go_to_org()
         self.delete_entity(
             org_name,
             really,
             locators['org.delete'],
             drop_locator=locators['org.dropdown'],
         )
```

**Comment by lpramuk** [comment]
yes, I missed to remove it, fixed

**Comment by oshtaier** [comment]
ACK pending test results

**Comment by elyezer** [comment]
ACK, pending results.

**Comment by oshtaier** [comment]
It seems that @lpramuk environment is not configured to test UI functionality properly, so let's merge that code and re-test it before merging into `master` branch.

We have to run all tests anyway

**Comment by lpramuk** [comment]
No the robottelo tests suite is not robust enough to be exersized  in variuos setups 
I run test on my own machine (virtaul X desktop), others do it in VMs (slow enough)

I may create an issue for it

**Comment by oshtaier** [comment]
I doubt that reason in that as you didn't make any experiments to prove that. You just need to make sure that your environment has appropriate version for all libs and etc. Just have same environment as on Jenkins
Any Test Automation System in the world, especially UI based ones, cannot support all environments, so please follow envs that are used on the project by most people

**Comment by lpramuk** [comment]
I DO follow.

sleep(1) would'nt have helped me if it has been firefox/libs/packages related. Period.

**Comment by oshtaier** [comment]
Ok. That code works fine on another machines, so problem in yours. Period

**Pull request merged**
