### PR TITLE
host edit: test correct page redirection

### PR DESCRIPTION
**Pull request by pnovotny**
### Problem Statement

New test for correct page redirection after editing a host.

Component evaluation - SAT-21625
https://bugzilla.redhat.com/2166303

### Related Issues

Requires https://github.com/SatelliteQE/airgun/pull/1362

### CODE REVIEW

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_page_redirect_after_update
airgun: 1362

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6630
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_page_redirect_after_update --external-logging
Test Result : ========== 1 failed, 41 deselected, 50 warnings in 738.07s (0:12:18) ===========
```

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_page_redirect_after_update
airgun: 1362

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6631
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_page_redirect_after_update --external-logging
Test Result : ========== 1 failed, 41 deselected, 50 warnings in 677.10s (0:11:17) ===========
```

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_page_redirect_after_update
airgun: 1362

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6632
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_page_redirect_after_update --external-logging
Test Result : ========== 1 failed, 41 deselected, 54 warnings in 979.94s (0:16:19) ===========
```

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_page_redirect_after_update
airgun: 1362

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6633
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_page_redirect_after_update --external-logging
Test Result : ========== 1 failed, 41 deselected, 56 warnings in 1046.80s (0:17:26) ==========
```

**Comment by shweta83** [comment]
It is not recommended to add redhat internal links on the PR. Please remove the bugzilla link and just use the bug id.

**Comment by pnovotny** [comment]
I agree about the internal links.
But unlike RH Jira, Jenkins and similar internal systems, RH Bugzilla is public instance accessible to everyone (with some few exceptions like security bugs).

**Comment by pnovotny** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_page_redirect_after_update

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6703
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_page_redirect_after_update --external-logging
Test Result : ========== 1 passed, 41 deselected, 52 warnings in 740.34s (0:12:20) ===========
```

**Review by jameerpathan111 — APPROVED** [review]

**Review by pondrejk — APPROVED** [review]

**Pull request merged**
