### PR TITLE
Cv UI Publish 

### PR DESCRIPTION
**Pull request by sambible**
Few tests for Publish and Promote - Publish is working, but Promote is still WIP - leaving in Draft state.

### CODE REVIEW

**Comment by sambible** [comment]
Gonna yank out promote, and move this out of draft

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview_new.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview_new.py
airgun: 948

**Pull request closed without merging**
