### PR TITLE
Fix logging statements in API sync plan tests

### PR DESCRIPTION
**Pull request by swadeley**
Hello

When I copied new logging statements from CLI to API  [1], I fixed the ones for tests with plural `products`, but then failed to fix the others to the format required.

[1]: https://github.com/SatelliteQE/robottelo/pull/8953

### CODE REVIEW

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_syncplan.py

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_syncplan.py tests/foreman/cli/test_syncplan.py

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_syncplan.py tests/foreman/cli/test_syncplan.py

**Review by mshriver — APPROVED** [review]
The joy of API entities having attributized access and CLI entities not.  Something @JacobCallahan and I are looking to standardize in robottelo. I've worked around it in some CLI tests by wrapping CLI entities (which are really just a dictionary) in AttrDict.

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
