### PR TITLE
discovery test stubs for hammer-cli

### PR DESCRIPTION
**Pull request by sghai**
Test stubs for hammer-cli-discovery-plugin

### CODE REVIEW

**Comment by elyezer** [comment]
Missing `@stubbed()` decorator to skip the tests. This way all tests will be considered as passed.

**Comment by sghai** [comment]
ah.. Updating now. thanks for pointing..

**Comment by elyezer** [comment]
@sghai thank for fixing other module.

**Comment by JacobCallahan** [comment]
ACK

**Pull request merged**
