### PR TITLE
API: Move repository set tests to a separate module

### LINKED ISSUE #3148: Move API repository set tests to separate module
`class RepositorySetTestCase` is stored inside `test_product.py` right now. For UI/CLI we have separate module `test_repository_set.py` for that purpose. Need to make API consistent with other interfaces.

### PR DESCRIPTION
**Pull request by abalakh**
For UI/CLI we have separate module `test_repository_set.py` for repository set tests.
Making API consistent with other interfaces.
Closes #3148

### CODE REVIEW

**Comment by oshtaier** [comment]
APT

**Comment by abalakh** [comment]
```python
py.test tests/foreman/api/test_repository_set.py
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 2 items 

tests/foreman/api/test_repository_set.py ..

============================= 2 passed in 63.36 seconds ==============================

py.test tests/foreman/api/test_product.py
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 4 items 

tests/foreman/api/test_product.py ....

============================= 4 passed in 120.16 seconds =============================
```

**Comment by rplevka** [comment]
ACK
Thank you for the 'cleanup' :)

**Comment by oshtaier** [comment]
ACK

**Pull request merged**
