### PR TITLE
[6.1.z] fix nonexistent rhel65 image

### LINKED ISSUE #3899: [6.2.z][6.1.z] fix nonexisting rhel65 image
We have a lot of ```robottelo/vm.py:147: VirtualMachineError```s in 6.2 automation caused by  attempts to provision VM based on nonexisting ```rhel65``` image:
```
 VirtualMachineError: Failed to fetch virtual machine IP address information
```

### PR DESCRIPTION
**Pull request by lpramuk**
- fix nonexisting rhel65 image
- update rhel6{6,7} to rhel68 image where applicable

(Fixes #3899)

### CODE REVIEW

**Comment by rplevka** [comment]
ACK,
thanks for a prompt patch

**Comment by lpramuk** [comment]
I didnt update tests for applicable errata where having older rhel67 is preferred to rhel68

**Comment by lpramuk** [comment]
Also I didnt backport what we have in master - ```robottelo/constants.py```:
``` RHEL6_DISTRO="rhel68" ```

....in favor of quick fix in 6.1.z branch

**Comment by lpramuk** [comment]
cherrypicked & conflicts resolved.

**Comment by lpramuk** [comment]
fixed one more conflict I happen to miss

**Pull request merged**
