### PR TITLE
[6.13.z] Add coverage for ansible config report

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10465

Test results:

```
pytest tests/foreman/ui/test_ansible.py -k test_positive_config_report_ansible
======================================================================================= test session starts =======================================================================================
platform linux -- Python 3.8.6, pytest-7.1.3, pluggy-1.0.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/addubey/work/robottelo, configfile: pyproject.toml
plugins: forked-1.4.0, services-2.2.1, cov-3.0.0, xdist-3.1.0, ibutsu-2.2.4, reportportal-5.1.3, mock-3.10.0
collected 5 items / 3 deselected / 2 selected                                                                                                                                                     

tests/foreman/ui/test_ansible.py ..                                                                                                                                                         [100%]
==================================================================== 2 passed, 3 deselected, 3 warnings in 1363.22s (0:22:43) =====================================================================

```
Airgun PR for the endpoints utilized : https://github.com/SatelliteQE/airgun/pull/791

**Note**: `The results are from 6.12 we have a issue in 6.13 hence going for the skip marker`
BZ : https://bugzilla.redhat.com/show_bug.cgi?id=2155814

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_config_report_ansible

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_config_report_ansible

**Review by pondrejk — COMMENTED** [review]
A couple of instances of the following error in the prt run:
```
12:42:10  >       id = target_sat.nailgun_smart_proxy.id
12:42:10  E       AttributeError: 'Satellite' object has no attribute 'nailgun_smart_proxy'
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_config_report_ansible

**Comment by adarshdubey-star** [comment]
The PRT will fail because of a known BZ filed for Job invocation as mentioned in the parent PR.

**Pull request merged**
