### PR TITLE
[6.3] port shared function + change temp folder as per settings

### PR DESCRIPTION
**Pull request by ldjebran**
This is a port of shared function from 6.2.z branch

Shared function is a decorator, that enable a function once called to store
the results to storage, any ulterior call from the same or other processes will
return the stored results, which make the shared function results persistent.

Note: Shared function store it's data as json. The results of the decorated
    function must be json compatible.

Usage::

```python
    from robottelo.decorators.func_shared.shared import shared

    @shared
    def module_level_shared(*args, **kwargs):
        # do some
        # the result of a shared function must be json compatible
        return any_data

    class SomeTestCase1(TestCase):

        @shared
        def _shared_function(cls):

            org = make_org()
            # upload manifest
            repo = make_repository()
            return {'org_id': org['id'], 'repo_id': repo['id']}

        @classmethod
        @shared
        def setUpClass(cls):

            data = cls._shared_function()
            other_data = module_level_shared()

            cls.org = Org.info({'id': data['org_id']})
            cls.repo = Repository.info({'id': data['repo_id']})
            return

    # the shared function can be called an other time to be able to initiate
    # specific data

    class SomeTestCase2(TestCase):

        @classmethod
        @shared(inject=True, injected_kw='_injected')
        def setUpClass(cls, org_id=None, repo_id=None, _injected=False):

            if _injected:
                cls.org = Org.info({'id': org_id})
                cls.repo = Repository.info({'id': repo_id})
            else:
                # create the org
                cls.org = make_org()
                # upload manifest
                cls.repo = make_repository()

            # create a virtual machine

            # shared function with injected=True, must return a dict
            # the resulting dictionary will be injected in other calls as
            # kwargs, an added bool kw argument by default named _injected
            # should be added to the function kwargs, to be able to be notified
            # that the kwargs are injected from already stored result
            return {'org_id': cls.org['id'], 'repo_id': cls.repo['id']}

        # in case we do not want the injected key word in kwargs
        # simply , declare injected_kw=None
        @classmethod
        @shared(inject=True, injected_kw=None)
        def shared_class_method(cls, org_id=None, repo_id=None):
             if org_id is not None:
                cls.org = Org.info({'id': org_id})
             else:
                # create the org
                cls.org = make_org()
                # upload manifest
             if repo_id is not None:
                cls.repo = Repository.info({'id': repo_id})
             else:
                cls.repo = make_repository()

            # create a virtual machine

            return {'org_id': cls.org['id'], 'repo_id': cls.repo['id']}
```
unittest covered

### CODE REVIEW

**Comment by ldjebran** [comment]
put "DO NOT MERGE" need some investigations

**Comment by ldjebran** [comment]
@elyezer @omaciel  @oshtaier @renzon @rochacbruno
Perhaps we should move this PR (with locked function, that is already in robottelo) to a separate project what do you think?

**Comment by renzon** [comment]
@ldjebran such decorator should be part of xdist itself ;)

**Comment by ldjebran** [comment]
@renzon added new functionality, please revisit  
add a new keyword to shared function function_kw
This functionality allow  the kw of a function to participate in the scope creation eg: in the storage of persistent data

suppose you have a function that has a DISTRO passed as kw arg and that function should prepare content based on that distro, we could pass that distro kw to shared function and for each distro a new shared storage will be created

```python
@shared(function_kw=['distro']
def simple_distro_contro(distro=RHEL7, org=None):
    # create a content
```
for each distro value RHEL6 and RHEL7 a new data will be created and saved in it's own storage

usage:  for creating shared org for distro based content for virt-who and capsule vm setup

**Comment by ldjebran** [comment]
updated the examples in doc string to a more simpler form as cli objects are dicts and can be saved as json.

For nailgun entities shared function will check if the object is a nailgun Entity if so, it will use its' to_json_dict() to save the data, so the returned object for a nailgun object is a dict.  

to restore a nailgun objects from storage data (if entities where returned by the shared function of course)
```python 
from robottelo.decorators.func_shared.shared import shared
from nailgun import entities


@shared
def shared_org_loc():
    # a function that create an org and location shared with other processes
    org = entities.Organization().create()
    loc = entities.Location(organization=[org]).create()
    return dict(org=org, loc=loc)

def test_shared_entities():
    org_loc = shared_org_loc()
    org = entities.Organization().read(attrs=org_loc['org'])
    loc = entities.Location().read(attrs=org_loc['loc'])
    # we can refresh the entities if we want
    org = org.read()
    loc = loc.read()
```
we had also the possibility to use only the ids
```python 
from robottelo.decorators.func_shared.shared import shared
from nailgun import entities


@shared
def shared_org_loc():
    # a function that create an org and location shared with other processes
    org = entities.Organization().create()
    loc = entities.Location(organization=[org]).create()
    return dict(org_id=org.id, loc_id=loc.id)

def test_shared_entities():
    org_loc = shared_org_loc()
    org = entities.Organization(id=org_log['org_id')
    loc = entities.Location(id=org_log['loc_id')
    # we can refresh the entities if we want
    org = org.read()
    loc = loc.read()
```
if requested I will write an adapter for restoring nailgun entities automatically

**Pull request merged**
