### PR TITLE
[6.15.z] Add automation for BZ 2168494

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15811

### Problem Statement
Automated BZ 2168494

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by ogajduse** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7957
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 2320.88s (0:38:40) ==================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7958
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 2386.78s (0:39:46) ==================
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8001
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 2223.17s (0:37:03) ==================
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8230
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 2720.53s (0:45:20) ==================
```

**Comment by shweta83** [comment]
The test is failing on selennium grid with some unrelated javascript error failing for all tests for jobinvocation. We need to fix that before merging this. So moving this back to draft.

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8263
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 2195.52s (0:36:35) ==================
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8279
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 16 warnings in 2362.22s (0:39:22) ==================
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8282
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 16 warnings in 2218.74s (0:36:58) ==================
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8681
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 2223.01s (0:37:03) ==================
```

**Comment by shweta83** [comment]
The failure is unrelated to the change in the PR.

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
