### PR TITLE
[6.12.z] component name changes

### PR DESCRIPTION
**Pull request by pondrejk**
### Problem Statement
manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/14380
closes https://github.com/SatelliteQE/robottelo/issues/14390

### CODE REVIEW

**Review by Gauravtalreja1 — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
@pondrejk `:CaseLevel:` is still required for 6.12.z as removal PR of caselevel or other tokens wasn't cherrypicked to 6.12.z (CC @omkarkhatavkar @jyejare ), but meanwhile could you add that back so we can get this PR merged? 
```
testimony --config testimony.yaml validate tests/foreman/api
tests/foreman/api/test_ldapauthsource.py
========================================

test_positive_endtoend:27
-------------------------

* Docstring should have at least caseautomation, casecomponent, caseimportance, caselevel, id, requirement, team, testtype, upstream token(s)
```

**Comment by omkarkhatavkar** [comment]
> Good find @Gauravtalreja1 through checks ! @omkarkhatavkar could we cherrypick this now even before we merge this PR ?

@jyejare @Gauravtalreja1 I just added that back to 6.12.z. Some how I missed that, now you can see that https://github.com/SatelliteQE/robottelo/pull/14414

**Comment by Gauravtalreja1** [comment]
@omkarkhatavkar @jyejare Thank you for taking the prompt action by cherrypicking the huge and long pending PR. 
@pondrejk will now need to resolve the conflicts in his branch, I wish we would've merged this PR as is first :)

**Comment by omkarkhatavkar** [comment]
It was painful for me, it took 2 hours

**Comment by jyejare** [comment]
@pondrejk please resolve the conflicts !

**Pull request merged**
