### PR TITLE
[6.15.z] Fix TOTP generation. Fix what commit a5a5cd9e5e broke.

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14645

null

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6832
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 28 deselected, 40 warnings, 1 error in 1435.40s (0:23:55) ===========
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login

**Comment by devendra104** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7561
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 1 failed, 28 deselected, 45 warnings in 2284.12s (0:38:04) ==========
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7700
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 1 failed, 28 deselected, 45 warnings in 2323.87s (0:38:43) ==========
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login
env:
    ROBOTTELO_rhsso__rhsso__totp_secret: 'MF2HS5DCIY3XKZLJJNRTQ4TVOB4EINCQ'

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login
env:
    ROBOTTELO_rhsso__rhsso__totp_secret: 'MF2HS5DCIY3XKZLJJNRTQ4TVOB4EINCQ'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7701
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 1 failed, 28 deselected, 45 warnings in 2437.23s (0:40:37) ==========
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login
env:
ROBOTTELO_rhsso__rhsso__totp_secret: 'MF2HS5DCIY3XKZLJJNRTQ4TVOB4EINCQ'

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login
env:
    ROBOTTELO_rhsso__rhsso__totp_secret: 'MF2HS5DCIY3XKZLJJNRTQ4TVOB4EINCQ'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7713
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 1 failed, 28 deselected, 45 warnings in 2155.06s (0:35:55) ==========
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7726
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 1 passed, 28 deselected, 45 warnings in 2648.66s (0:44:08) ==========
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7730
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 1 passed, 28 deselected, 45 warnings in 2368.45s (0:39:28) ==========
```

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
