### PR TITLE
logging - added py.test worker information to the log

### PR DESCRIPTION
**Pull request by rplevka**
cherry-picking: https://github.com/SatelliteQE/robottelo/pull/3884

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK

**Comment by omaciel** [comment]
Travis was very unhappy with new `cachetools` so I had to send in https://github.com/SatelliteQE/robottelo/pull/3889 (I could not cherry-pick https://github.com/SatelliteQE/robottelo/pull/3883 because one of the files modified by it does not exist on 6.2.z branch)

**Comment by omaciel** [comment]
Re-triggering Travis

**Comment by omaciel** [comment]
@rplevka please rebase so that new requirements can be used by Travis?

**Comment by rplevka** [comment]
rebased

**Pull request merged**
