### PR TITLE
ddt removal in ui settings tests

### PR DESCRIPTION
**Pull request by sthirugn**
```sh
# nosetests tests/foreman/ui/test_settings.py

----------------------------------------------------------------------
Ran 29 tests in 296.042s

OK (skipped=9)
```

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK

**Comment by abalakh** [comment]
ACK. Rebase, please?

**Comment by sthirugn** [comment]
Rebased

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
