### PR TITLE
[6.3 Feature] Automated Subnet Parameters CRUD Tests

### PR DESCRIPTION
**Pull request by jyejare**
Automated CRUD API tests of 6.3 Feature Parameterized Subnets.

### CODE REVIEW

**Comment by jyejare** [comment]
DO NOT MERGE this until https://github.com/SatelliteQE/nailgun/pull/437 gets merged

**Comment by jyejare** [comment]
@svtkachenko and @abalakh , Please review my PR.

**Comment by svtkachenko** [comment]
@jyejare Can you please rebase your branch with SatelliteQE:master? It is 137 commits behind master and cause unneeded changes, like
```diff
- @stubbed()
+ @stubbed
```

**Comment by jyejare** [comment]
@svtkachenko , Some issues with my local branch and all mess. Hence I am closing this PR and have raised fresh one here: https://github.com/SatelliteQE/robottelo/pull/5426
Please review that one.

**Pull request closed without merging**
