### PR TITLE
Fix tests.foreman.api.test_permission.PermissionsTestCase.test_search_by_resource_type_13_Host method

### LINKED ISSUE #2172: Automation failure : test_search_by_resource_type_13_Host
Testnames:
tests.foreman.api.test_permission.PermissionsTestCase.test_search_by_resource_type_13_Host

The test says : 
Element counts were not equal:
First has 0, Second has 1:  u'view_discovered_hosts'
First has 0, Second has 1:  u'provision_discovered_hosts'
First has 0, Second has 1:  u'edit_discovered_hosts'
First has 0, Second has 1:  u'destroy_discovered_hosts'
more details: 
- https://jenkins.example.com/view/Nightly/job/satellite6-automation-upstream-rhel71-api/56/testReport/junit/tests.foreman.api.test_permission/PermissionsTestCase/test_search_by_resource_type_13_Host/

please fix it 
thanks

### PR DESCRIPTION
**Pull request by oshtaier**
Fix tests corresponding to new parameters in payload
Closes #2172

### CODE REVIEW

**Comment by oshtaier** [comment]
Before fix:
```
nosetests tests/foreman/api/test_permission.py -m test_search_by_resource_type
...F.................................S........
======================================================================
FAIL: @test: Search for permissions by resource type.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/oshtaier/Desktop/robottelo/tests/foreman/api/test_permission.py", line 70, in test_search_by_resource_type
    [perm['name'] for perm in perm_group],
AssertionError: Element counts were not equal:
First has 0, Second has 1:  u'view_discovered_hosts'
First has 0, Second has 1:  u'provision_discovered_hosts'
First has 0, Second has 1:  u'edit_discovered_hosts'
First has 0, Second has 1:  u'destroy_discovered_hosts'
-------------------- >> begin captured logging << --------------------
py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 46 tests in 52.712s

FAILED (SKIP=1, failures=1)
```

After fix:
```
nosetests tests/foreman/api/test_permission.py -m test_search_by_resource_type
.....................................S........
----------------------------------------------------------------------
Ran 46 tests in 53.102s

OK (SKIP=1)
```

**Comment by elyezer** [comment]
I would like to see these permissions names tuples sorted alphabetically. Feel free to sort the Host section or leave as is because others does not follow this.

ACK

**Comment by sthirugn** [comment]
ACK

**Comment by Ichimonji10** [comment]
@oshtaier Was this fix tested against an upstream or downstream system?

**Comment by oshtaier** [comment]
@Ichimonji10 Against downstream. Sorry for late response.

**Pull request merged**
