### PR TITLE
API: Added coverage for ptable create, delete, update

### LINKED ISSUE #2501: Automate :  Create a partition table in Api
please automate:

POST /api/ptables
Create a partition table
Params
Param name 	Description
ptable
required 	
Value: Hash
ptable[name]
required 	
Value: String
ptable[layout]
required 	
Value: String
ptable[os_family]
optional , nil allowed 	
Value: String

### LINKED ISSUE #2502: Automate :  Update a partition table in api
please automate:

PUT /api/ptables/:id
Update a partition table
Params
Param name 	Description
id
required 	
Value: String
ptable
required 	
Value: Hash
ptable[name]
optional 	
Value: String
ptable[layout]
optional 	
Value: String
ptable[os_family]
optional , nil allowed 	
Value: String

### LINKED ISSUE #2503: Automate :  Delete a partition table
please automate:

DELETE /api/ptables/:id
Delete a partition table
Params
Param name 	Description
id
required 	
Value: String

### PR DESCRIPTION
**Pull request by abalakh**
Added coverage for ```POST /api/ptables```, ```PUT /api/ptables/:id``` and ```DELETE /api/ptables/:id```.
Closes #2501
Closes #2502
Closes #2503
Putting everything in one PR as it will take longer to create separate PRs, rebase and resolve conflicts after each one gets merged, than it took to write these simple tests :smile:  (can split to separate PRs if that's really necessary).
Tests results:
```
nosetests tests/foreman/api/test_partitiontable.py 
...................................................
----------------------------------------------------------------------
Ran 51 tests in 122.097s

OK
```
```[DO NOT MERGE]``` tag until SatelliteQE/nailgun#132 gets merged and released.

### CODE REVIEW

**Comment by oshtaier** [comment]
Really appreciate if you can validate https://bugzilla.redhat.com/show_bug.cgi?id=1229384 in separate test case in scope of this PR

**Comment by abalakh** [comment]
@oshtaier done. please, take a look at ```test_bugzilla_1229384()```.
Also I've created #2520, to cover this BZ for API and CLI as well.

**Comment by oshtaier** [comment]
ACK. Provide test run results

**Comment by abalakh** [comment]
Here they are:
```
nosetests tests/foreman/api/test_partitiontable.py
SSSSSS...................................................
----------------------------------------------------------------------
Ran 57 tests in 102.031s

OK (SKIP=6)
```

**Comment by Ichimonji10** [comment]
ACK

**Comment by Ichimonji10** [comment]
Bonus karma for rebasing this.

**Comment by abalakh** [comment]
Done :)

**Pull request merged**
