### PR TITLE
Add test coverage for SAT-26014

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
### Problem Statement
Missing test coverage for SAT-26014

### Solution
Adding a destructive test to cover SAT-26014

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_installer.py -k test_negative_installer_invalid_dns_forwarder

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8823
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_installer.py -k test_negative_installer_invalid_dns_forwarder --external-logging
Test Result : ========== 1 passed, 5 deselected, 18 warnings in 1252.58s (0:20:52) ===========
```

**Review by rmynar — APPROVED** [review]
Looks good to me.

Just non-blocking comments:
Would you consider adding a positive scenario? It may be easily added into non-default installation: https://github.com/SatelliteQE/robottelo/blob/8109a0f8f86fabebd989b6bc033a8f5a8742df1d/tests/foreman/installer/test_installer.py#L296

What about cherry picking into older versions? 6.15, maybe 6.14...?

**Comment by Gauravtalreja1** [comment]
@rmynar Thanks for your comments. 
If you see the related issue, then its about a negative scenario only which breaks the answer file, and for positive scenario its already been tested in our misc-provisioning Jenkins jobs, so I don't think if we should cover in new test separately, and about cherrypicking it to 6.15 or 6.14, so its only fixed for stream and 6.16 for now.

**Review by shubhamsg199 — APPROVED** [review]
Ack, looks good.

**Pull request merged**
