### PR TITLE
pass bridge to snap-guest vm

### PR DESCRIPTION
**Pull request by pondrejk**
Required in  #4578, pending tests

### CODE REVIEW

**Comment by kbidarkar** [comment]
ACK

**Comment by pondrejk** [comment]
see the standalone automation job number 542 to see the test results, basically the bridge is now correctly propagated from robottelo.settings and set to default value if unset. The snap-guest now fails on:

```
ERROR    Cannot get interface MTU on 'sfeature_el6': No such device
Domain installation does not appear to have been successful.
```

This is given by infrastructure as the hypervisor for generated host doesnt have the same interfaces enables as the Sat server does

**Comment by pondrejk** [comment]
Putting back do not merge as this probably doesn't fix the original isssue, see the discussion in #4578 Will keep this open until we come to a decision on how to tackle the problem

**Comment by rochacbruno** [comment]
@pondrejk pending CP to 6.2?

**Pull request merged**
