### PR TITLE
Enable IPv6 proxy when settings.server.is_ipv6=True in IPv6 runs

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
### Problem Statement
IPv6 proxy isn't configured for subscription manager and DNF, causing tests to fail where we register or with installer when run for IPv6

### Solution
Enable IPv6 proxy when settings.server.is_ipv6=True in IPv6 runs

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/  --component "Puppet"

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ --component "Puppet"
network_type: ipv6

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ --component "Puppet"
network_type: ipv6

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ --component "Puppet"
network_type: ipv6

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ --component "Puppet"
network_type: ipv6

**Comment by Gauravtalreja1** [comment]
Remaining PRT failures are related to Puppet component, I'll investigate and fix those in separate PR later

**Comment by jameerpathan111** [comment]
trigger: test-robottelo
pytest: tests/foreman/installer/test_installer.py
network_type: ipv6

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/installer/test_installer.py
network_type: ipv6

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 9298
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/installer/test_installer.py --external-logging
Test Result : ========= 21 passed, 3 deselected, 392 warnings in 7907.94s (2:11:47) ==========
```

**Review by jyejare — APPROVED** [review]

**Pull request merged**
