### PR TITLE
Drop DDT from CLI Import tests

### PR DESCRIPTION
**Pull request by lpramuk**
No herbicides. (Part of #2769.)

### CODE REVIEW

**Comment by sthirugn** [comment]
@lpramuk can you please rebase and resolve conflicts? the changes are not shown now.

**Comment by lpramuk** [comment]
multiple conflicts resolved.

**Comment by sthirugn** [comment]
ACK

**Comment by lpramuk** [comment]
fixing: during merge I dropped the fix for:
                Import.content_view_with_tr_data({
                    'csv-file': files['repositories'],

it should be: files['content-views']

**Comment by rplevka** [comment]
ACK
- hopefully, the lack of herbicides won't lead to growing population of the bugs

**Pull request merged**
