### PR TITLE
Debug failover to cloned manifests

### PR DESCRIPTION
**Pull request by synkd**
This PR, in combination with https://github.com/SatelliteQE/manifester/pull/21, addresses some of the errors that have been occurring in CI in cases where Manifester times out when exporting a manifest due to an upstream RHSM issue. These changes should enable Robottelo to successfully fail over to using cloned manifests in those cases.

### CODE REVIEW

**Comment by synkd** [comment]
Setting the `in progress` label until https://github.com/SatelliteQE/manifester/pull/21 is merged.

**Review by jyejare — APPROVED** [review]

**Review by JacobCallahan — APPROVED** [review]

**Comment by JacobCallahan** [comment]
@synkd if this is ready, can you add a PRT run?

**Comment by synkd** [comment]
@JacobCallahan since the timeout that would trigger the failover does not happen in upstream RHSM with any discernible pattern, PRT won't reliably tell us whether the change worked. It's more likely to tell us that the change didn't break anything. This is probably worth demonstrating, so I will trigger a run.

I can artificially trigger the failover to cloned manifests on the manifester side by setting the timeout to 0. I'd prefer do this locally and provide some PDB output demonstrating that the control flow is working as expected. Would that work for you?

**Comment by JacobCallahan** [comment]
Well we can test no-break by running a simple test that touches the closest part of manifester

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_contentaccess.py::test_negative_rct_not_shows_golden_ticket_enabled

**Comment by synkd** [comment]
@JacobCallahan any test that uses one of the manifester fixtures from taxonomy.py will adequately test no-break, so we're good on that front with the PRT run above.

**Pull request merged**
