### PR TITLE
cherry-pick: Bump repo versions to 6.8 (#8172)

### PR DESCRIPTION
**Pull request by swadeley**
* Bump repo versions to 6.8

This will help with upgraded tests.

### CODE REVIEW

**Review by tstrych — COMMENTED** [review]
One thing to keep in mind, there will be soon 6.9, action needed for master branch. 

I think it is necessary to provide some kind of results/proof, that new `REPOSETS`, `REPOS`, `RHVA_TREE` and `SAT_6_TREE` are really in place and are not failing our tests results.

**Review by JacobCallahan — APPROVED** [review]
ACK. @tstrych a good potential future enhancement could be to programmatically inject version values and generate these data structures

**Review by devendra104 — APPROVED** [review]
ACK

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
