### PR TITLE
Flip entitlement to SCA in destructive caps content

### PR DESCRIPTION
**Pull request by vsedmik**
### Problem Statement
Entitlement mode got deprecated and removed from 6.16

### Solution
Flip to SCA.

### PRT test Cases example
trigger: test-robottelo
pytest: tests/foreman/destructive/test_capsulecontent.py

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_capsulecontent.py

**Review by Griffin-Sullivan — APPROVED** [review]
Code looks fine. Waiting for PRT.

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6481
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_capsulecontent.py --external-logging
Test Result : =========== 1 failed, 1 passed, 2055 warnings in 14944.09s (4:09:04) ===========
```

**Comment by vsedmik** [comment]
In PRT one test passed, second failed. The failure looks like a product bug or something to be further investigated, unrelated to this PR.

**Review by vijaysawant — APPROVED** [review]

**Pull request merged**
