### PR TITLE
[6.2.z] qe_test_coverage 1333219

### PR DESCRIPTION
**Pull request by ldjebran**
+ cover bug: https://bugzilla.redhat.com/show_bug.cgi?id=1333219
+ remove bug skip as bug resolved and test functional

```
(sat-6.2.z) dlezz@elysion:~/projects/robottelo-fork$ pytest tests/foreman/ui/test_subscription.py -v -k "test_positive_access"
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.2.z/bin/python
cachedir: .cache
shared_function enabled - ON - scope:  - storage: file
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.15.0, services-1.1.14, cov-2.3.1
collected 3 items 
2017-05-31 12:54:58 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings


tests/foreman/ui/test_subscription.py::SubscriptionTestCase::test_positive_access_with_non_admin_user PASSED
tests/foreman/ui/test_subscription.py::SubscriptionTestCase::test_positive_access_with_restricted_user PASSED

================================================== 1 tests deselected ==================================================
======================================= 2 passed, 1 deselected in 69.56 seconds ========================================
```

### CODE REVIEW

**Comment by ldjebran** [comment]
put it do not merge add 2 more tests for this

**Comment by ldjebran** [comment]
```console
(sat-6.2.z) dlezz@elysion:~/projects/robottelo-fork$ pytest tests/foreman/ui/test_subscription.py -v -k "test_positive_access"
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.2.z/bin/python
cachedir: .cache
shared_function enabled - ON - scope:  - storage: file
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.15.0, services-1.1.14, cov-2.3.1
collected 4 items 
2017-05-31 15:56:08 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings


tests/foreman/ui/test_subscription.py::SubscriptionTestCase::test_positive_access_with_non_admin_user PASSED
tests/foreman/ui/test_subscription.py::SubscriptionTestCase::test_positive_access_with_non_admin_user_with_manifest PASSED
tests/foreman/ui/test_subscription.py::SubscriptionTestCase::test_positive_access_with_non_admin_user_without_manifest PASSED

================================================== 1 tests deselected ==================================================
======================================= 3 passed, 1 deselected in 551.50 seconds =======================================
(sat-6.2.z) dlezz@elysion:~/projects/robottelo-fork$ 
```

**Comment by oshtaier** [comment]
and rebase of course

**Comment by ldjebran** [comment]
branch rebase done
```console
(sat-6.2.z) dlezz@elysion:~/projects/robottelo-fork$ pytest tests/foreman/ui/test_subscription.py -v -k "test_positive_access"
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.2.z/bin/python
cachedir: .cache
shared_function enabled - ON - scope:  - storage: file
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.15.0, services-1.1.14, cov-2.3.1
collected 5 items 
2017-06-07 17:38:20 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings


tests/foreman/ui/test_subscription.py::SubscriptionTestCase::test_positive_access_with_non_admin_user PASSED
tests/foreman/ui/test_subscription.py::SubscriptionTestCase::test_positive_access_with_non_admin_user_with_manifest PASSED
tests/foreman/ui/test_subscription.py::SubscriptionTestCase::test_positive_access_with_non_admin_user_without_manifest PASSED

================================================== 2 tests deselected ==================================================
======================================= 3 passed, 2 deselected in 226.01 seconds =======================================
(sat-6.2.z) dlezz@elysion:~/projects/robottelo-fork$
```

**Pull request merged**
