### PR TITLE
{Rebase Pending}{Testing Pending} Discovery Improvements wrt efficiency and count

### PR DESCRIPTION
**Pull request by jyejare**
TO BE ADDED ...

### CODE REVIEW

**Comment by mirekdlugosz** [comment]
@jyejare Given multiple conflicts and lack of test results, I assume this is not a 6.7.z branching blocker. Is that correct?

**Comment by jyejare** [comment]
@mirekdlugosz Yeah I am not looking at it for now. Go ahead and consider it as a non-blocker for branching.

**Comment by mshriver** [comment]
@jyejare I've moved this to draft state as it appears to be forgotten/stale. Please rebase and update if its still something you would like to see merged.  Thanks!

**Comment by jyejare** [comment]
@mirekdlugosz , @rplevka has raised PR to convert the Discovery tests to Pytest and since this PR duplicates it! I am closing this PR.

**Pull request closed without merging**
