### PR TITLE
Fix max name length for CLI hostgroup tests

### LINKED ISSUE #3163: Fix max name length in cli/test_hostgroup tests
Following tests from cli/test_hostgroup may fail due to invalid boundary value for name:
* test_positive_create
* test_positive_update_name
* test_positive_delete

`test_positive_create` is failing right now on Jenkins with `Name is too long (maximum is 245 characters)` error. Need to update the tests accordingly.

### PR DESCRIPTION
**Pull request by abalakh**
Closes #3163

### CODE REVIEW

**Comment by abalakh** [comment]
Executed 10 times in a row:
```python
for i in {1..10}; do py.test tests/foreman/cli/test_hostgroup.py -k 'test_positive_create or test_positive_update_name or test_positive_delete'; done
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1
collected 12 items 

tests/foreman/cli/test_hostgroup.py ...

 9 tests deselected by '-ktest_positive_create or test_positive_update_name or test_positive_delete' 
====================== 3 passed, 9 deselected in 193.88 seconds ======================
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1
collected 12 items 

tests/foreman/cli/test_hostgroup.py ...

 9 tests deselected by '-ktest_positive_create or test_positive_update_name or test_positive_delete' 
====================== 3 passed, 9 deselected in 194.86 seconds ======================
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1
collected 12 items 

tests/foreman/cli/test_hostgroup.py ...

 9 tests deselected by '-ktest_positive_create or test_positive_update_name or test_positive_delete' 
====================== 3 passed, 9 deselected in 194.26 seconds ======================
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1
collected 12 items 

tests/foreman/cli/test_hostgroup.py ...

 9 tests deselected by '-ktest_positive_create or test_positive_update_name or test_positive_delete' 
====================== 3 passed, 9 deselected in 192.89 seconds ======================
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1
collected 12 items 

tests/foreman/cli/test_hostgroup.py ..F

====================================== FAILURES ======================================
2015-12-16 13:32:50 - robottelo.ssh - DEBUG - <<< stderr
[ERROR 2015-12-16 06:32:50 Exception] Name has already been taken
Could not update the hostgroup:
  Name has already been taken

 9 tests deselected by '-ktest_positive_create or test_positive_update_name or test_positive_delete' 
================= 1 failed, 2 passed, 9 deselected in 163.55 seconds =================
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1
collected 12 items 

tests/foreman/cli/test_hostgroup.py ...

 9 tests deselected by '-ktest_positive_create or test_positive_update_name or test_positive_delete' 
====================== 3 passed, 9 deselected in 193.67 seconds ======================
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1
collected 12 items 

tests/foreman/cli/test_hostgroup.py ...

 9 tests deselected by '-ktest_positive_create or test_positive_update_name or test_positive_delete' 
====================== 3 passed, 9 deselected in 193.45 seconds ======================
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1
collected 12 items 

tests/foreman/cli/test_hostgroup.py ...

 9 tests deselected by '-ktest_positive_create or test_positive_update_name or test_positive_delete' 
====================== 3 passed, 9 deselected in 194.16 seconds ======================
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1
collected 12 items 

tests/foreman/cli/test_hostgroup.py ...

 9 tests deselected by '-ktest_positive_create or test_positive_update_name or test_positive_delete' 
====================== 3 passed, 9 deselected in 193.86 seconds ======================
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1
collected 12 items 

tests/foreman/cli/test_hostgroup.py ...

 9 tests deselected by '-ktest_positive_create or test_positive_update_name or test_positive_delete' 
====================== 3 passed, 9 deselected in 192.12 seconds ======================
```
1 failure as it generated already existing name (today's my lucky day :smile: )
Also tested with hardcoded boundary values of 1 and 245 chars (220 for html) 10 times - no failures either.

**Comment by oshtaier** [comment]
ACK

**Comment by elyezer** [comment]
ACK, I will let @sthirugn take a look on this before merging.

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
