### PR TITLE
Updated factory method for `make_syncplan`.

### PR DESCRIPTION
**Pull request by omaciel**
Current automation results show several issues with Sync Plan tests for the UI. The
Pull Request #3223 updated the `create` method for the `SyncPlan` class and removed
the `submit_validate` but the factory method was not updated.

### CODE REVIEW

**Comment by omaciel** [comment]
This should fix the following issue with UI Sync Plan tests:

```python
Syncplan(session.browser).create(**create_args) E       TypeError: create() got an unexpected keyword argument 'submit_validate'  robottelo/ui/factory.py:614: TypeError
```

**Comment by sthirugn** [comment]
good catch APT

**Comment by elyezer** [comment]
APT

**Comment by omaciel** [comment]
```python
(robottelo)┌[omaciel☮Ogs-MacBook-Pro.local]-(~/hacking/robottelo)-[git://fix-syncplan ✔]-
└> py.test -v tests/foreman/ui/test_syncplan.py -k 'test_positive_create_with_name'
============================================================= test session starts =============================================================
platform darwin -- Python 2.7.10, pytest-2.8.5, py-1.4.31, pluggy-0.3.1 -- /Users/omaciel/.virtualenvs/robottelo/bin/python
cachedir: .cache
rootdir: /Users/omaciel/hacking/robottelo, inifile:
plugins: cov-2.2.0, xdist-1.13.1
collected 12 items

tests/foreman/ui/test_syncplan.py::SyncPlanTestCase::test_positive_create_with_name PASSED

========================================== 11 tests deselected by '-ktest_positive_create_with_name' ==========================================
================================================== 1 passed, 11 deselected in 102.54 seconds ==================================================
```

**Comment by sghai** [comment]
:+1:  thank you for fixing this.

**Comment by oshtaier** [comment]
My bad. Thanks for fixing that

**Comment by elyezer** [comment]
@oshtaier no worries, rafactoring code is not an easy task.

**Pull request merged**
