### PR TITLE
Improving logging for tests

### PR DESCRIPTION
**Pull request by sthirugn**
With multithreading it is becoming very difficult to identify the tests looking
a the robottelo logs.  This improves the logging by adding more useful logs.

CLI test:

```
Finding files... done.
Importing test modules ... done.

2016-06-09 15:47:31 - robottelo - DEBUG - Started setUpClass: ActivationKeyTestCase
...
...
2016-06-09 15:47:37 - robottelo - DEBUG - Started Test: ActivationKeyTestCase/test_positive_create_with_name
...
2016-06-09 15:47:43 - robottelo - DEBUG - Finished Test: ActivationKeyTestCase/test_positive_create_with_name
...
2016-06-09 15:47:43 - robottelo - DEBUG - Started tearDownClass: ActivationKeyTestCase
2016-06-09 15:47:43 - robottelo - DEBUG - Cleanup got 0 entities to update
2016-06-09 15:47:43 - robottelo - DEBUG - Cleanup got 0 entities to update
2016-06-09 15:47:43 - robottelo - DEBUG - Cleanup got 0 entities to delete
2016-06-09 15:47:43 - robottelo - DEBUG - Cleanup deleted 0 entities
----------------------------------------------------------------------
Ran 1 test in 11.809s

OK
```

UI test:

```
Finding files... done.
Importing test modules ... done.

2016-06-09 15:50:36 - robottelo - DEBUG - Started setUpClass: ArchitectureTestCase
...
2016-06-09 15:50:36 - robottelo - INFO - Session set with:
	User: 5:SagrhqSeSO
	Organization: 1:Default Organization
	Web Driver: firefox
	Binary: /usr/bin/firefox
	Locale: en_US.UTF-8
	Server Name: ***
2016-06-09 15:50:36 - robottelo - DEBUG - Started Test: ArchitectureTestCase/test_positive_create_with_name
...
2016-06-09 15:50:45 - robottelo - DEBUG - Finished Test: ArchitectureTestCase/test_positive_create_with_name
...
2016-06-09 15:50:46 - robottelo - DEBUG - Started tearDownClass: ArchitectureTestCase
...

OK
```

API test:
```
Finding files... done.
Importing test modules ... done.

2016-06-09 15:53:39 - robottelo - DEBUG - Started setUpClass: ActivationKeyTestCase
2016-06-09 15:53:39 - robottelo - DEBUG - Started Test: ActivationKeyTestCase/test_positive_create_with_name
...
2016-06-09 15:53:43 - robottelo - DEBUG - Finished Test: ActivationKeyTestCase/test_positive_create_with_name
2016-06-09 15:53:43 - robottelo - DEBUG - Started tearDownClass: ActivationKeyTestCase
2016-06-09 15:53:43 - robottelo - DEBUG - Cleanup got 0 entities to update
2016-06-09 15:53:43 - robottelo - DEBUG - Cleanup got 0 entities to update
2016-06-09 15:53:43 - robottelo - DEBUG - Cleanup got 1 entities to delete
...
2016-06-09 15:53:45 - robottelo - DEBUG - Cleanup deleted 1 entities
----------------------------------------------------------------------
Ran 1 test in 5.444s

OK
```

### CODE REVIEW

**Comment by sthirugn** [comment]
Updated code with module name for setUpClass/tearDownClass loggings:
```
Finding files... done.
Importing test modules ... done.

2016-06-09 16:06:18 - robottelo - DEBUG - Started setUpClass: tests.foreman.cli.test_capsule2/ActivationKeyTestCase
2016-06-09 16:06:18 - robottelo - DEBUG - Started Test: ActivationKeyTestCase/test_positive_create_with_name
...
2016-06-09 16:06:22 - robottelo - DEBUG - Finished Test: ActivationKeyTestCase/test_positive_create_with_name
2016-06-09 16:06:22 - robottelo - DEBUG - Started tearDownClass: tests.foreman.cli.test_capsule2/ActivationKeyTestCase
2016-06-09 16:06:22 - robottelo - DEBUG - Cleanup got 0 entities to update
2016-06-09 16:06:22 - robottelo - DEBUG - Cleanup got 0 entities to update
2016-06-09 16:06:22 - robottelo - DEBUG - Cleanup got 1 entities to delete
...
2016-06-09 16:06:24 - robottelo - DEBUG - Cleanup deleted 1 entities
----------------------------------------------------------------------
Ran 1 test in 5.456s

OK
```

**Comment by sthirugn** [comment]
It may be possible that many tests have setup() or teardown() which may not get these loggings but they need to be fixed later.

**Comment by rochacbruno** [comment]
> There are many tests have their own setup() or teardown() which may not get these loggings but they need to be fixed later
@sthirugn So a new issue should be created to remind us of this :)

ACK (pending issue creation ^)

**Comment by rochacbruno** [comment]
Merging with one ACK because we need to retrigger

**Pull request merged**
