### PR TITLE
[6.14.z] Add preconversion check for convert2rhel

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15044

### Problem Statement
We have pre-conversion check for convert2rhel but missing automation for it.

### Solution
Added pre-convesion check.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6918
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_convert2rhel.py -k test_convert2rhel_oracle_with_pre_conversion_template_check[oracle8] --external-logging
Test Result : =========== 3 deselected, 18 warnings, 1 error in 2013.16s (0:33:33) ===========
```

**Comment by Gauravtalreja1** [comment]
@shweta83 Could you investigate the PRT failure and update the PR?

**Comment by shweta83** [comment]
Yes. Already working on fixing it.

**Comment by ogajduse** [comment]
It has been over 70 days since the last update on this PR. Converting the PR to draft.

**Comment by Gauravtalreja1** [comment]
@shweta83 Could you please update this PR since it has been more than 3 months?

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_convert2rhel.py -k test_convert2rhel_centos_with_pre_conversion_template_check[centos8]

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8216
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_convert2rhel.py -k test_convert2rhel_centos_with_pre_conversion_template_check[centos8] --external-logging
Test Result : =========== 3 deselected, 16 warnings, 1 error in 2283.02s (0:38:03) ===========
```

**Pull request closed without merging**
