### PR TITLE
[6.16.z] Fix action order so the user is not missing when adding a role to them

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16353

null

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_positive_negotiate_CRUD

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8762
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py::test_positive_negotiate_CRUD --external-logging
Test Result : ============ 1 passed, 160 warnings, 1 error in 3189.55s (0:53:09) =============
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_positive_negotiate_CRUD

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8782
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py::test_positive_negotiate_CRUD --external-logging
Test Result : ================= 2 passed, 320 warnings in 4618.91s (1:16:58) =================
```

**Pull request merged**
