### PR TITLE
 Add un_auth_proxy_url to robottelo/config/facade.py

### PR DESCRIPTION
**Pull request by jameerpathan111**
Test results:
```
$ pytest tests/foreman/ui/test_http_proxy.py -k test_positive_assign_http_proxy_to_products_repositories | tee http_proxy.log 
============================= test session starts ==============================
collected 3 items / 2 deselected / 1 selected

tests/foreman/ui/test_http_proxy.py .                                    [100%]

================= 1 passed, 2 deselected in 411.24s (0:06:51) ==================
```
```
$ pytest tests/foreman/cli/test_product.py -k test_positive_assign_http_proxy_to_products | tee http_proxy.log 
============================= test session starts ==============================
collected 7 items / 6 deselected / 1 selected

tests/foreman/cli/test_product.py .                                      [100%]

================= 1 passed, 6 deselected in 221.50s (0:03:41) ==================
```
```
$ pytest tests/foreman/api/test_repository.py -k test_positive_assign_http_proxy_to_repository
============================= test session starts ==============================
collected 172 items / 171 deselected / 1 selected

tests/foreman/api/test_repository.py .                                   [100%]

================ 1 passed, 171 deselected in 110.78s (0:01:50) =================
```

Test `test_positive_assign_http_proxy_to_products_repositories` depends on https://github.com/SatelliteQE/airgun/pull/549

```
$ pytest tests/foreman/ui/test_http_proxy.py -k test_positive_assign_http_proxy_to_products_repositories
============================= test session starts ==============================
collected 3 items / 2 deselected / 1 selected

tests/foreman/ui/test_http_proxy.py .                                    [100%]

================= 1 passed, 2 deselected in 411.24s (0:06:51) ==================
```

### CODE REVIEW

**Review by swadeley — APPROVED** [review]
ACK

**Review by pondrejk — COMMENTED** [review]
@jameerpathan111 changes look good, but do we know why the change in settings type occured? I wonder if the root cause might affect some other settings somewhere else

**Comment by jameerpathan111** [comment]
@pondrejk I don't have much clue around why the change occurred. @omkarkhatavkar @jyejare might know about this.

**Comment by mirekdlugosz** [comment]
@pondrejk the surprising part is that `http_proxy.auth_proxy_url` is already on the list of wrapper exceptions in [robottelo/config/facade.py](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/config/facade.py). I will try to take a look at that tomorrow.

**Review by mirekdlugosz — APPROVED** [review]
We discussed that with Jameer off Github, and he confirmed that wrapping `http_proxy.auth_proxy_url` in `str()` call was not strictly necessary, he only did it to be on the safe side. Adding `http_proxy.un_auth_proxy_url` to list of exceptions in facade is enough to let UI test progress further in execution.

ACK

**Pull request merged**
