### PR TITLE
Fix a syntax error in the test suite

### PR DESCRIPTION
**Pull request by Ichimonji10**
New test results:

    $ nosetests tests/foreman/api/test_syncplan.py:SyncPlanProductTestCase
    SSSS
    ----------------------------------------------------------------------
    Ran 4 tests in 2.494s

    OK (SKIP=4)

### CODE REVIEW

**Comment by Ichimonji10** [comment]
This should fix a jenkins error.

**Comment by omaciel** [comment]
ACK

i_will_be_good

**Comment by Ichimonji10** [comment]
:wink:

**Comment by JacobCallahan** [comment]
Ahhh ok. ACK

**Pull request merged**
