### PR TITLE
Update hammer command options data

### PR DESCRIPTION
**Pull request by elyezer**
Update the data in order to match the current hammer commands and
options.

```
$ py.test tests/foreman/cli/test_hammer.py 
================================ test session starts ================================
platform linux2 -- Python 2.7.5 -- py-1.4.30 -- pytest-2.7.2
rootdir: /home/elyezer/robottelo, inifile: 
collected 1 items 

tests/foreman/cli/test_hammer.py .

============================ 1 passed in 634.49 seconds =============================
```

### CODE REVIEW

**Comment by sthirugn** [comment]
wait, so these changes are being introduced in z-stream build?

**Comment by elyezer** [comment]
@sthirugn I have tested against qe machines. And this seems to be a fix for a broken docker cli though

**Comment by oshtaier** [comment]
@sthirugn That should be related to recent fix for very important defect:
https://bugzilla.redhat.com/show_bug.cgi?id=1206679

**Comment by sthirugn** [comment]
@oshtaier excellent this is the info I am looking for

**Comment by sthirugn** [comment]
ACK

**Comment by oshtaier** [comment]
ACK

**Pull request merged**
