### PR TITLE
Use DOCKER_UPSTREAM_NAME in repo test

### PR DESCRIPTION
**Pull request by swadeley**
rather than hardcoded repo name
  Change to mirror.gcr.io

see also https://github.com/SatelliteQE/robottelo/pull/8310#issuecomment-770266796

### CODE REVIEW

**Comment by swadeley** [comment]
robottelo]$ pytest tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo
================================ test session starts ================================================
platform linux -- Python 3.9.1, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /robot-test/robottelo, configfile: pyproject.toml
plugins: xdist-2.1.0, mock-3.3.1, forked-1.3.0, services-2.2.1, cov-2.11.1, ibutsu-1.13
collected 1 item                                                                                                                                                                                  

tests/foreman/cli/test_repository.py .                                                                                                                                                      [100%]

================================ 1 passed, 5 warnings in 33.32s =======================================

**Comment by swadeley** [comment]
robottelo]$ pytest tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_with_tags_whitelist
============================== test session starts ============================================
platform linux -- Python 3.9.1, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/sjw/robot-test/robottelo, configfile: pyproject.toml
plugins: xdist-2.1.0, mock-3.3.1, forked-1.3.0, services-2.2.1, cov-2.11.1, ibutsu-1.13
collected 1 item                                                                                                                                                                                  

tests/foreman/cli/test_repository.py .  

=========================== 1 passed, 5 warnings in 45.40s =================================

**Comment by swadeley** [comment]
obottelo]$ pytest tests/foreman/cli/test_repository.py::TestRepository::test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags
====================== test session starts ============================================================
platform linux -- Python 3.9.1, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /robot-test/robottelo, configfile: pyproject.toml
plugins: xdist-2.1.0, mock-3.3.1, forked-1.3.0, services-2.2.1, cov-2.11.1, ibutsu-1.13
collected 1 item                                                                                                                                                                                  

tests/foreman/cli/test_repository.py .                                                                                                                                                      [100%]
============================= 1 passed, 5 warnings in 45.75s =======================================

**Comment by swadeley** [comment]
There is one test that fails:

`FAILED tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later[0] - wait_for.TimedOutError: Could not do 'lambda defined as `lambda: int(_get...`

**Comment by swadeley** [comment]
Hello, this result shows above fail is now fixed, but I will run test against whole file as well.

robottelo]$ pytest tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later
======================== test session starts ====================================================
platform linux -- Python 3.9.1, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /robot-test/robottelo, configfile: pyproject.toml
plugins: xdist-2.1.0, mock-3.3.1, forked-1.3.0, services-2.2.1, cov-2.11.1, ibutsu-1.13
collected 1 item                                                                                                                                                                                  

tests/foreman/cli/test_repository.py .                                                                                                                                                      [100%]
============================ 1 passed, 5 warnings in 109.08s (0:01:49) =========================

**Comment by jyejare** [comment]
@swadeley If this is fixed in last comment, why this is still in Draft state ?

**Review by jyejare — APPROVED** [review]

**Comment by swadeley** [comment]
> @swadeley If this is fixed in last comment, why this is still in Draft state ?

because I said I would run test on whole file and because a certain someone might come along and set it back to draft

**Comment by swadeley** [comment]
All the changes I have made pass, but these test have failed:

================================ short test summary info ==============================================
FAILED tests/foreman/cli/test_repository.py::TestRepository::test_negative_restricted_user_cv_add_repository[0] - AssertionError: assert 172 == 1
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_with_special_characters[1-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with...
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_with_special_characters[2-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with...
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_with_special_characters[3-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with...
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_with_special_characters[4-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with...
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_with_special_characters[5-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with...
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_with_special_characters[6-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with...
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_with_special_characters[7-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with...
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_with_special_characters[8-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with...
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_with_special_characters[9-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with...
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_too_long[1-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with data:
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_too_long[2-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with data:
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_too_long[3-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with data:
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_too_long[4-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with data:
ERROR tests/foreman/cli/test_repository.py::TestRepository::test_negative_update_auth_url_too_long[5-0] - robottelo.cli.factory.CLIFactoryError: Failed to create Repository with data:
=============== 1 failed, 241 passed, 20 skipped, 6 warnings, 14 errors in 5045.68s (1:24:05) ======================

This seems to be a side affect of pytest conversion: https://github.com/SatelliteQE/robottelo/pull/8100

**Review by pondrejk — APPROVED** [review]

**Comment by swadeley** [comment]
Hello

Re comment https://github.com/SatelliteQE/robottelo/pull/8318#issuecomment-770667185

`test_negative_restricted_user_cv_add_repository` passed on retesting. For the others, this PR fixes them:

https://github.com/SatelliteQE/robottelo/pull/8323

Thank you

**Pull request merged**
