### PR TITLE
[6.15.z] Check that host statuses honor taxonomy permissions

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14986

null

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py::test_host_status_honors_taxonomies
airgun: 1384

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7006
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py::test_host_status_honors_taxonomies --external-logging
Test Result : ================= 1 failed, 13 warnings in 1009.31s (0:16:49) ==================
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py::test_host_status_honors_taxonomies
airgun: 1388

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7061
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py::test_host_status_honors_taxonomies --external-logging
Test Result : ================== 1 failed, 13 warnings in 992.96s (0:16:32) ==================
```

**Comment by lhellebr** [comment]
This shouldn't have been marked for cherrypick in the first place, the fix is only present in stream. Closing this PR and keeping the airgun one because the UI hasn't changed.

**Pull request closed without merging**
