### PR TITLE
Fix UI test names according to new naming conventions (part 1)

### PR DESCRIPTION
**Pull request by oshtaier**
Tests for module that has more than cosmetic changes (don't know why I did that, but just wanted to improve it :smile: )
```
nosetests tests/foreman/ui/test_discoveryrule.py
........
----------------------------------------------------------------------
Ran 8 tests in 501.615s

OK
```

### CODE REVIEW

**Comment by abalakh** [comment]
Please fix docs warnings:
```
/home/travis/build/SatelliteQE/robottelo/docs/api/tests.foreman.ui.rst:49: WARNING: autodoc: failed to import module u'tests.foreman.ui.test_contentviews'; the following exception was raised:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named test_contentviews
/home/travis/build/SatelliteQE/robottelo/docs/api/tests.foreman.ui.rst:54: WARNING: autodoc: failed to import module u'tests.foreman.ui.test_discoveredhosts'; the following exception was raised:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named test_discoveredhosts                             
/home/travis/build/SatelliteQE/robottelo/docs/api/tests.foreman.ui.rst:46: WARNING: py:mod reference target not found: tests.foreman.ui.test_contentviews
/home/travis/build/SatelliteQE/robottelo/docs/api/tests.foreman.ui.rst:51: WARNING: py:mod reference target not found: tests.foreman.ui.test_discoveredhosts
```

**Comment by abalakh** [comment]
ACK pending mentioned fix

**Comment by oshtaier** [comment]
Done. Please, scroll my code once more before merge :)

**Comment by elyezer** [comment]
APT

**Pull request merged**
