### PR TITLE
Drop module `robottelo.entities`

### PR DESCRIPTION
**Pull request by Ichimonji10**
NailGun version 0.8.0 includes all of the entity classes. Drop module
`robottelo.entities` in favor of `nailgun.entities`.

Lock Robottelo to NailGun version 0.8.x. More breaking changes will be
introduced in to NailGun before version 1.0 is released, and locking to a
specific version will prevent those changes from unduly affecting Robottelo.

Example test results:

    $ nosetests tests/foreman/api/test_multiple_paths.py
    ...S...S.....S.............................................................S...S.......................................................................EE...........................................................SSSS.SSSSSS..S.SSSSSSS...SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
    Ran 267 tests in 408.456s

    FAILED (SKIP=53, errors=2)
    $ nosetests tests/foreman/smoke/test_api_smoke.py -m test_smoke
    .
    ----------------------------------------------------------------------
    Ran 1 test in 78.671s

    OK

The two errors are due to a known versioning issue.

### CODE REVIEW

**Comment by omaciel** [comment]
ACK

**Comment by omaciel** [comment]
@elyezer bump? :)

**Comment by elyezer** [comment]
ACK

**Comment by Ichimonji10** [comment]
:tada:

**Pull request merged**
