### PR TITLE
[6.15.z] - remove the unused testimony tokens & none used for reporting (#13479)

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
### Problem Statement

cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13479

Remove 3 tokens from Robottelo which are not useful or not being used anywhere in reporting:

TestType
Upstream
CaseLevel

### Solution
removed these three tokens from the test docstring, This will need some testing against the Polarian staging host.

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo

**Review by shweta83 — APPROVED** [review]
Ack

**Comment by jyejare** [comment]
@omkarkhatavkar Please resolve conflicts to merge !

**Comment by omkarkhatavkar** [comment]
> @omkarkhatavkar Please resolve conflicts to merge !

@jyejare Done !

**Pull request merged**
