### PR TITLE
Implement some Docker UI stubs

### PR DESCRIPTION
**Pull request by abalakh**
Depends on #3568 
```
py.test tests/foreman/ui/test_docker.py -k 'test_positive_search_docker_image or test_positive_list_containers or test_positive_create_with_external_registry' -v
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /home/andrii/env/bin/python
cachedir: .cache
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 44 items 

tests/foreman/ui/test_docker.py::DockerTagTestCase::test_positive_search_docker_image <- robottelo/decorators.py PASSED
tests/foreman/ui/test_docker.py::DockerComputeResourceTestCase::test_positive_list_containers PASSED
tests/foreman/ui/test_docker.py::DockerContainerTestCase::test_positive_create_with_external_registry <- robottelo/decorators.py PASSED

 41 tests deselected by '-ktest_positive_search_docker_image or test_positive_list_containers or test_positive_create_with_external_registry' 
===================== 3 passed, 41 deselected in 297.05 seconds ======================
```

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK

**Comment by rochacbruno** [comment]
#3568 merged can we merge this? @abalakh ?

**Comment by abalakh** [comment]
@rochacbruno yes, sure

**Comment by rochacbruno** [comment]
ACK

**Pull request merged**
