### PR TITLE
Improve CLI factory error exception message

### PR DESCRIPTION
**Pull request by elyezer**
Improve the CLIFactoryError message on the exception raised on
create_object method. This will format the option in a more readable
way, making it easy to identity the passed options.

### CODE REVIEW

**Comment by JacobCallahan** [comment]
nice change. ACK

**Comment by elyezer** [comment]
Forgot to paste the new output

```python
CLIFactoryError: Failed to create Org with data:
{
  "compute-resource-ids": null,
  "config-template-ids": null,
  "description": null,
  "domain-ids": null,
  "environment-ids": null,
  "hostgroup-ids": null,
  "label": null,
  "media-ids": null,
  "name": "",
  "realm-ids": null,
  "smart-proxy-ids": null,
  "subnet-ids": null,
  "user-ids": null
}
```

**Comment by elyezer** [comment]
Rebased.

**Comment by Ichimonji10** [comment]
ACK

**Comment by omaciel** [comment]
Only managed to see this now, but thank you for the improvement!

**Pull request merged**
