### PR TITLE
Remove system_facts

### PR DESCRIPTION
**Pull request by sambible**
Part of the helpers refactor.

This file isn't currently referenced anywhere in Robottelo, and looks to be a pretty old relic. Unless there is value in keeping the constants around, I don't really see any reason to not simply delete this file.

Thoughts?

### CODE REVIEW

**Comment by JacobCallahan** [comment]
See if anything needs to be added to the SystemFacts class defined here: https://github.com/SatelliteQE/robottelo/blob/master/robottelo/host_helpers/contenthost_mixins.py#L93

**Review by shweta83 — APPROVED** [review]
I think we are good to remove this @sambible @JacobCallahan

**Review by Gauravtalreja1 — APPROVED** [review]

**Comment by jyejare** [comment]
@sambible Check the suggestion from @JacobCallahan. Tts very valuable suggestion if the deletions from this PR can fit into what he said. If it doesn't let's continue.

Waiting for your ACK/NACK.

**Comment by sambible** [comment]
The file being proposed for deletion is effectively a custom facts dictionary, with specifics set already. As it says
"""JSON representation for a RHEL server."""

Personally, I don't see any reason to maintain this specific collection of facts. It's not being used by any tests currently, and the code in there doesn't do anything we can't do with the mixin already (i.e. generate a facts file from a RHEL server)

**Review by jyejare — APPROVED** [review]

**Comment by jyejare** [comment]
@JacobCallahan Are you good with @sambible comment, then please merge !

**Pull request merged**
