### PR TITLE
Fix test_hammer.py::HammerCommandsTestCase::test_positive_all_options

### PR DESCRIPTION
**Pull request by mirekdlugosz**
Fix `tests/foreman/cli/test_hammer.py::HammerCommandsTestCase::test_positive_all_options`.

This PR consists of 2 main changes:
* change in hammer help parsing function
* update of `tests/foreman/data/hammer_commands.json`, used by test above.

### hammer help parsing

There are two changes in hammer help output introduced in Satellite 6.8.

First, some options are grouped. Where hammer used to write `--location-id`, `--location-title` (as two separate options), now it writes `--location[-id|-title]`.

Second, internal hammer command synonyms are exposed in `full-help`. So where `list` was only acceptable subcommand in the past, now you can use `list` or `index`. This is written as `list, index` in full-help output.

Robottelo unit test suite was extended to cover these changes.

### `hammer_commands.json` changes

`hammer_commands.json` is reference that we compare `hammer full-help` against in test. It's generated by `./scripts/hammer_command_tree.py`, which basically goes through all hammer subcommands and calls `--help` on them.

Summary of changes in file:
* new commands: `bookmark`, `content-credentials`, `http-proxy`,  `mail-notification`, `prebuild-bash-completion`, `scap-content-profile`, `status`, `trend`
* removed commands: `smart-variables` 
* new subcommands: `login > basic`, `login > oauth`, `auth-source > external`, `compute-resource > virtual-machine`, `compute-resource > virtual-machines`, `content-view > add-repository`,  `content-view > add-version`, `host > policies-enc`, `host > traces`, `ping > foreman`, `ping > katello`, `policy > hosts`, `product > update-proxy`, `report-template > import`, `user > mail-notification`
* majority of `list` and `info` subcommands got new `--fields` flag
* huge number of wording changes in help messages

Overall, nothing particularly surprising or unexpected. Mainly a fair share of new features.

I had to modify this file manually to account for mismatches between `full-help` and `--help` outputs, reported as [bz#1872783](https://bugzilla.redhat.com/show_bug.cgi?id=1872783).

### Test result

```
$ pytest -v tests/foreman/cli/test_hammer.py::HammerCommandsTestCase::test_positive_all_options
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.5, pytest-4.6.3, py-1.8.1, pluggy-0.13.1 -- /home/mzalewsk/.virtualenvs/robottelo/bin/python3
collecting ... 2020-08-27 11:23:41 - conftest - DEBUG - Collected 1 test cases
collected 1 item                                                                                                                                                                              

tests/foreman/cli/test_hammer.py::HammerCommandsTestCase::test_positive_all_options PASSED                                                                                              [100%]
============================================================================ 1 passed, 2 warnings in 13.37 seconds ============================================================================
```

### CODE REVIEW

**Comment by JacobCallahan** [comment]
Let's hold on this for now, as now is a good time to have a larger discussion around the necessity of this test.

**Comment by mirekdlugosz** [comment]
@JacobCallahan As component owner, I think this test is necessary. You are free to start discussion with management about taking over ownership of "Hammer" component and maintaining it as you see fit.

Until then, do you have any comments regarding code itself?

**Comment by JacobCallahan** [comment]
After talking with Mirek, I'm not going to hold on the wider discussion. We can get the test passing and then have that discussion later.

**Review by omkarkhatavkar — APPROVED** [review]
ACK

**Comment by omkarkhatavkar** [comment]
Merging as tier1 and tier2 ACK are already present

**Pull request merged**
