### PR TITLE
[6.16.z] Change from module to function fixtures

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16345

### Problem Statement
I was seeing issues sharing module level fixtures with other tests in the class

### Solution
Change the module fixture to function level fixtures, to better work in CI.

### PRT test Cases example
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_all_hosts_manage_errata'

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_all_hosts_manage_errata'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8630
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_all_hosts_manage_errata --external-logging
Test Result : ========= 4 failed, 73 deselected, 650 warnings in 2508.66s (0:41:48) ==========
```

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_all_hosts_manage_errata'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8635
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_all_hosts_manage_errata --external-logging
Test Result : ========= 4 failed, 73 deselected, 2240 warnings in 9340.45s (2:35:40) =========
```

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_all_hosts_manage_errata'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8636
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_all_hosts_manage_errata --external-logging
Test Result : ========= 4 failed, 73 deselected, 1722 warnings in 8813.94s (2:26:53) =========
```

**Comment by sambible** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_all_hosts_manage_errata'
airgun: 1562

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8637
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_all_hosts_manage_errata --external-logging
Test Result : ========= 4 passed, 73 deselected, 833 warnings in 3507.38s (0:58:27) ==========
```

**Pull request merged**
