### PR TITLE
test: Unable to select organization for Sync management

### PR DESCRIPTION
**Pull request by sambible**
Creating a manual test case for https://bugzilla.redhat.com/show_bug.cgi?id=1860957

There has been discussion around automating this, and it was determined to be more work than value. Not sure if this is the correct place to stick this, would like feedback.

### CODE REVIEW

**Review by akhil-jha — APPROVED** [review]
Not a blocker, but you could add caseimportance as well. I test_repository.py has a caseimportance of high, but the test doesn't seem high to me. More like medium.

**Review by jyejare — APPROVED** [review]
ACK, this is the most common workflow customers might access the sync status page, I mean the chances are high that customers will route to the sync status page this way. 

So let's keep it as high importance only.

**Review by ColeHiggins2 — APPROVED** [review]
ACK

**Comment by sambible** [comment]
Added case importance, will merge after all checks run

**Pull request merged**
