### PR TITLE
Bz1669241 cli api

### PR DESCRIPTION
**Pull request by lhellebr**
As promised in https://github.com/SatelliteQE/robottelo/pull/7452#pullrequestreview-311632309

### CODE REVIEW

**Comment by JacobCallahan** [comment]
@lhellebr can you paste in the test results?

**Comment by lhellebr** [comment]
```
$ pytest tests/foreman/api/test_subscription.py::SubscriptionsTestCase::test_positive_delete_manifest_as_another_user
=================================================== test session starts ====================================================
platform linux -- Python 3.6.6, pytest-4.6.3, py-1.7.0, pluggy-0.12.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/lhellebr/git/robottelo, inifile: pytest.ini
plugins: mock-1.10.4, services-1.3.1
collecting ... 2019-11-25 15:33:47 - conftest - DEBUG - Collected 1 test cases

2019-11-25 16:33:49 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7fb229e029e8
2019-11-25 16:33:49 - robottelo.ssh - INFO - Connected to [...]
2019-11-25 16:33:49 - robottelo.ssh - INFO - >>> rpm -q satellite
2019-11-25 16:33:50 - robottelo.ssh - INFO - <<< stdout
satellite-6.7.0-2.beta.el7sat.noarch

2019-11-25 16:33:50 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7fb229e029e8
2019-11-25 16:33:50 - robottelo.host_info - DEBUG - Host Satellite version: 6.7
2019-11-25 16:33:50 - robottelo.helpers - DEBUG - Generated file bz_cache.json with BZ collect data
collected 1 item                                                                                                           

tests/foreman/api/test_subscription.py .                                                                             [100%]

===================================================== warnings summary =====================================================
tests/foreman/api/test_subscription.py::SubscriptionsTestCase::test_positive_delete_manifest_as_another_user
  /home/lhellebr/git/robottelo/tests/foreman/api/test_subscription.py:193: PendingDeprecationWarning: Please use assertEqual instead.
    self.assertEquals(0, len(Subscription.list({'organization-id': org.id})))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================== 1 passed, 1 warnings in 120.09 seconds ==========================================
```

**Comment by lhellebr** [comment]
Can we merge this?

**Comment by mirekdlugosz** [comment]
I don't see anything blocking this. merging

**Pull request merged**
