### PR TITLE
[6.15.z] Check that concurrency level is honored

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13198

### Problem Statement
Concurrency has been reworked in dynflow

### Solution
Add a test for concurrency level being honored

trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py::TestAnsibleREX::test_positive_run_serial

### CODE REVIEW

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py::TestAnsibleREX::test_positive_run_serial

**Review by Gauravtalreja1 — APPROVED** [review]
ACK, PRT is expected to fail as there's no 6.15.z

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py::TestAnsibleREX::test_positive_run_serial

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py::TestAnsibleREX::test_positive_run_serial

**Pull request merged**
