### PR TITLE
[6.2.z] [Cherry-pick] Added tests for scparams/variables list / BZ 1303653, 1219934

### PR DESCRIPTION
**Pull request by svtkachenko**
https://bugzilla.redhat.com/show_bug.cgi?id=1303653
https://bugzilla.redhat.com/show_bug.cgi?id=1219934

Basically cherry-picked from #4327 but with portion of changes for 6.2:
* All affected setUpClass'es were decorated with `lock_function` as in #4409
* `test_positive_import_twice_list_by_puppetclass_id` and specific asserts for duplicates in results were removed from classparameters as corresponding BZ was fixed for 6.3 only
* Host's 'list_by' tests are using nailgun for creating hosts for several reasons:
  * There is no helper that would allow easily create host, like the one in 6.3. And using `make_host` directly is too complicated.
  * After all host creating is not a purpose of these tests.
*  Also these nailgun calls are using some hacks because of, err, nailgun design. `entities.Host().create(create_missing=True)` fails to lookup location in environment when passing only environment id (and not full nailgun's `Environment` object obtained after `read()`). Workaround within CLI tests is 
`environment=entities.Environment(id=self.puppet_env['id']).read(),`

```python
]% py.test -n 4 tests/foreman/cli/test_{environment,host,hostgroup,variables}.py -k 'sc_params or puppet or list_s or list_by' 
========================================== test session starts ===========================================
platform linux2 -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/qui/code/robottelo, inifile: 
plugins: xdist-1.14, services-1.1.14, cov-2.3.1
gw0 [21] / gw1 [21] / gw2 [21] / gw3 [21]
scheduling tests via LoadScheduling
.....................
====================================== 21 passed in 554.85 seconds =======================================
```

```python
% py.test tests/foreman/cli/test_classparameters.py -k 'list_by'
========================================== test session starts ===========================================
platform linux2 -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/qui/code/robottelo, inifile: 
plugins: xdist-1.14, services-1.1.14, cov-2.3.1
collected 45 items 
2017-03-16 08:44:30 - conftest - DEBUG - Found WONTFIX in decorated tests ['1156555', '1269196', '1245334', '1217635', '1226425', '1204686', '1267224', '1103157', '1230902', '1214312', '1079482']

2017-03-16 08:44:30 - conftest - DEBUG - Collected 45 test cases


tests/foreman/cli/test_classparameters.py ........

=================================== 37 tests deselected by '-klist_by' ===================================
=============================== 8 passed, 37 deselected in 198.08 seconds ================================
```

### CODE REVIEW

**Comment by ldjebran** [comment]
@

**Comment by ldjebran** [comment]
@svtkachenko why you removed the checks that only unique results are returned, as understand this not a restriction of the test it self (but you are cherry picking) is there a problem with that (perhaps this a bug).

**Comment by ldjebran** [comment]
@svtkachenko, why you are locking the setup classes, have you done some tests (with pytest -n 8) that reproduce the problem that we tried to resolve in the PR you are referring. 

If yes please update the description with the log tests as we have not closed the issue https://github.com/SatelliteQE/robottelo/issues/4310 and please also refer to that issue, so we can track this tests in the next build too.

**Comment by svtkachenko** [comment]
Checks "that only unique results are returned" were added as sanity checks and also to extend coverage for BZ 1385351 (Test `test_positive_import_twice_list_by_puppetclass_id` covers exact steps from BZ). And since 385351 was fixed only in 6.3 and wouldn't be fixed in 6.2, tests are failing though list in general works.

**Comment by ldjebran** [comment]
from where you got info that bug 1385351 wouldn't be fixed in 6.2, perhaps you have to create a clone with sat-6.2.z? flag

**Comment by svtkachenko** [comment]
@ldjebran I've cloned BZ and added those test and checks back.

**Comment by abalakh** [comment]
> Also these nailgun calls are using some hacks because of, err, nailgun design. entities.Host().create(create_missing=True) fails to lookup location in environment when passing only environment id (and not full nailgun's Environment object obtained after read()). Workaround within CLI tests is
environment=entities.Environment(id=self.puppet_env['id']).read(),

I wouldn't call that a 'hack' as both ways of passing arguments are supported and documented (either as an Entity object or by entity's id), but if there's an issue with entities.Host().create_missing(), why not fixing it but introducing workarounds instead?

**Pull request merged**
