### PR TITLE
Bump broker to 0.5

### PR DESCRIPTION
**Pull request by JacobCallahan**
This requirement update also adds in the podman and hussh dependency groups.

trigger: test-robottelo
pytest: tests/foreman/ -k 'test_host_registration_end_to_end or test_positive_erratum_applicability or test_positive_upload_content'

### CODE REVIEW

**Comment by JacobCallahan** [comment]
trigger: test-robottelo
pytest: tests/foreman/ -k 'test_host_registration_end_to_end or test_positive_erratum_applicability or test_positive_upload_content'
env:
    BROKER_SSH_BACKEND: hussh

**Comment by JacobCallahan** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ -k 'test_host_registration_end_to_end or test_positive_erratum_applicability or test_positive_upload_content'
env:
    BROKER_SSH_BACKEND: hussh
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7184
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ -k test_host_registration_end_to_end or test_positive_erratum_applicability or test_positive_upload_content --external-logging
Test Result : == 6 failed, 11 passed, 5478 deselected, 6734 warnings in 8007.45s (2:13:27) ===
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7186
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ -k test_host_registration_end_to_end or test_positive_erratum_applicability or test_positive_upload_content --external-logging
Test Result : == 6 failed, 11 passed, 5478 deselected, 6727 warnings in 7915.49s (2:11:55) ===
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ -k 'test_host_registration_end_to_end or test_positive_erratum_applicability or test_positive_upload_content'
env:
  BROKER_SSH_BACKEND: hussh
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7248
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ -k test_host_registration_end_to_end or test_positive_erratum_applicability or test_positive_upload_content --external-logging
Test Result : == 6 failed, 11 passed, 5501 deselected, 6746 warnings in 7864.05s (2:11:04) ===
```

**Comment by Gauravtalreja1** [comment]
@JacobCallahan Did you get an chance to look at the PRT failures? Does this seem related?

**Comment by JacobCallahan** [comment]
@Gauravtalreja1 those failures so not seem to be related. However, I would like @shubhamsg199 to run the tests he wanted Hussh for via PRT as well

**Comment by Gauravtalreja1** [comment]
````
trigger: test-rotottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-rotottelo
pytest: tests/foreman/api/test_provisioning.py -k test_rhel_pxe_provisioning
provisioning: true
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-rotottelo
pytest: tests/foreman/api/test_provisioning.py -k test_rhel_pxe_provisioning
provisioning: true
env:
  BROKER_SSH_BACKEND: hussh
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-rotottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_rhel_pxe_provisioning
provisioning: true
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7321
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_provisioning.py -k test_rhel_pxe_provisioning --external-logging --include-onprem-provisioning
Test Result : === 4 failed, 8 passed, 13 deselected, 2627 warnings in 19093.37s (5:18:13) ====
```

**Review by Gauravtalreja1 — APPROVED** [review]
LGTM, PRT failures for above provisioning tests are related to known bug for EL8 provisioning.

**Review by shubhamsg199 — APPROVED** [review]
LGTM, Thanks @Gauravtalreja1 for testing provisioning. The failures are expected due to the RHEL8 provisioning bug.

**Pull request merged**
