### PR TITLE
[DO NOT MERGE] Implement host-collection erratum

### PR DESCRIPTION
**Pull request by ldjebran**
Because of the bug it was not possible to test it

### CODE REVIEW

**Comment by oshtaier** [comment]
So, this code was not tested?

**Comment by ldjebran** [comment]
@oshtaier  , this code was tested to work on the latest 6.2.6, but unfortunately a bug has been discovered when running the command hammer erratum install https://bugzilla.redhat.com/show_bug.cgi?id=1405428,
negative tests working as except one where the errata is mentioned, and seems affected by the bug.
on 6.3 latest versions 7 and 8 compose the tests even does pass the setUp because of diff bug

**Comment by oshtaier** [comment]
Hmm, so maybe we can merge it in another branch. I mean to 6.2.z and then in future just cherry-pick into master?

**Comment by ldjebran** [comment]
it should be a good solution, but I think before we should cherry-pick the base errata tests

**Comment by oshtaier** [comment]
Yeah, follow any procedure that you like, but at least we can have code submitted in 6.2

**Comment by ldjebran** [comment]
@rochacbruno i'am waiting the refactoring of ERRATA CLI to be merged and than cherry-pick the base errata tests, and than make a PR for this 6.2

**Comment by ldjebran** [comment]
This PR will replaced by a new one in 6.2.z branch

**Pull request closed without merging**
