### PR TITLE
Check that host statuses honor taxonomy permissions

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py::test_host_status_honors_taxonomies

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6825
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py::test_host_status_honors_taxonomies --external-logging
Test Result : ================= 1 failed, 13 warnings in 1046.49s (0:17:26) ==================
```

**Comment by lhellebr** [comment]
Depends on https://github.com/SatelliteQE/airgun/pull/1384

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py::test_host_status_honors_taxonomies

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6826
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py::test_host_status_honors_taxonomies --external-logging
Test Result : ================= 1 failed, 13 warnings in 1088.95s (0:18:08) ==================
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py::test_host_status_honors_taxonomies
airgun: 1384

**Review by pondrejk — APPROVED** [review]

**Review by rplevka — APPROVED** [review]

**Pull request merged**
