### PR TITLE
[6.3]  change selenium 2.53.1

### PR DESCRIPTION
**Pull request by ldjebran**
Tests run on saucelabs
```
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test tests/foreman/ui -v -m 'tier1 and run_in_one_thread and not stubbed'
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.0, cov-2.4.0
collected 1275 items 
2017-08-01 15:07:47 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings


tests/foreman/ui/test_adusergroup.py::ActiveDirectoryUserGroupTestCase::test_negative_create_external_with_invalid_name PASSED
tests/foreman/ui/test_adusergroup.py::ActiveDirectoryUserGroupTestCase::test_negative_create_external_with_same_name PASSED
tests/foreman/ui/test_adusergroup.py::ActiveDirectoryUserGroupTestCase::test_positive_add_admin_role PASSED
tests/foreman/ui/test_adusergroup.py::ActiveDirectoryUserGroupTestCase::test_positive_create_external PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_negative_edit_parameter_dialog <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_negative_enable_merge_overrides_default_checkboxes <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_negative_update_parameter_type <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_negative_validate_default_value_with_list <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_negative_validate_default_value_with_regex <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_negative_validate_matcher_and_default_value <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_negative_validate_matcher_non_existing_attribute <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_negative_validate_matcher_value_with_default_type <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_negative_validate_matcher_value_with_list <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_negative_validate_matcher_value_with_regex <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_positive_create_matcher_puppet_default_value <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_positive_edit_parameter_dialog <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_positive_enable_merge_overrides_default_checkboxes <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_classparameters.py::SmartClassParametersTestCase::test_positive_hide_empty_default_value <- robottelo/decorators/__init__.py PASSED
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
to show a full traceback on KeyboardInterrupt use --fulltrace
/home/dlezz/.pyenv/versions/2.7.13/lib/python2.7/socket.py:480: KeyboardInterrupt
================================================ 1226 tests deselected =================================================
==================================== 18 passed, 1226 deselected in 6881.55 seconds =====================================
```

### CODE REVIEW

**Comment by ldjebran** [comment]
put do not merge as some CI infra updates must be done

**Comment by oshtaier** [comment]
anyway we will need full tests results. Of course, only for UI

**Comment by kbidarkar** [comment]
@ldjebran @oshtaier @rochacbruno , will work towards raising the necessary CI infra PR, once raised we can merge both the PR together.

**Comment by kbidarkar** [comment]
Will be updating the CI infra to as per below statement from @ldjebran mail.
`Found working and supported on Saucelabs the combination of selenium 2.53.1 with Firefox 47.0 (this is the maximum working scenario without gecko driver).`

**Comment by ldjebran** [comment]
The standalone automation is started ...  waiting results (this can take 2 days to finish) 
Note:
The analysis will be very hard and time consuming process, as the standalone automation is not prepared for this type of tasks.
Think the right path for this is to make the changes , run the full automation and analyse, if something wrong and a blocker found revert back.

**Comment by oshtaier** [comment]
let's wait for at least one round, we can afford to wait for 2-3 days for changes like this

**Comment by kbidarkar** [comment]
Had discussion with  @ldjebran @oshtaier and @sghai , we decided to merge this and test it on automation pipeline. so will be merging this, if things don't work , we will revert it.

**Comment by kbidarkar** [comment]
ACK

**Pull request merged**
