### PR TITLE
[6.15.z] test timeout_to_kill

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15162

### Problem Statement
timeout to kill setting should cancel the rex job if it takes too long

### Solution
adding test

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7938
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 945.86s (0:15:45) ===========
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7939
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 909.28s (0:15:09) ===========
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8002
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 906.48s (0:15:06) ===========
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8275
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 955.76s (0:15:55) ===========
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8763
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 852.33s (0:14:12) ===========
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8869
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 1205.23s (0:20:05) ==========
```

**Pull request closed without merging**
