### PR TITLE
Revert "Added one test for compliance policies"

### PR DESCRIPTION
**Pull request by oshtaier**
Reverts SatelliteQE/robottelo#6264

Initial PR had DO NOT MERGE label and not resolved comment

@alda519 any reason you do that?

### CODE REVIEW

**Comment by oshtaier** [comment]
Nope, it was not removed. It was removed once you merged the PR, so it was not removed
And comment was addressed, but not in the way we wanted, actually it resolve nothing, anyway PR doesn't have 'approve' from person who spent most time on that review

**Comment by oshtaier** [comment]
@alda519 ^

**Comment by alda519** [comment]
If I knew that I would have removed that label before.
This change
https://github.com/SatelliteQE/robottelo/pull/6264/files#diff-73a3e1a7a2352bcb26d5c8b6d86d47f9R1172
is exactly the same as what is in the comment.

**Comment by oshtaier** [comment]
@ldjebran was it resolved in a way you asked?

**Comment by ldjebran** [comment]
plus I do not see that the changes was tested or any comment that say tested.

**Pull request merged**
