### PR TITLE
[6.14.z][Cherrypick] Merge and refactor leapp tests

### PR DESCRIPTION
**Pull request by shweta83**
### Problem Statement
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/15571 on 6.15.z

### Solution
Resolves https://github.com/SatelliteQE/robottelo/issues/16366

### CODE REVIEW

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8670
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_leapp_upgrade_rhel --external-logging
Test Result : ================= 2 failed, 166 warnings in 3215.15s (0:53:35) =================
```

**Comment by Gauravtalreja1** [comment]
@shweta83 Could you incorporate this change in this PR https://github.com/SatelliteQE/robottelo/pull/16433 ?

**Comment by shweta83** [comment]
> @shweta83 Could you incorporate this change in this PR #16433 ?

Added the changes.

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_leapp_client.py -k test_positive_leapp_upgrade_rhel

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8797
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_leapp_client.py -k test_positive_leapp_upgrade_rhel --external-logging
Test Result : ================= 2 failed, 162 warnings in 3232.40s (0:53:52) =================
```

**Comment by Gauravtalreja1** [comment]
@shweta83 Could you update this PR?

**Pull request closed without merging**
