### PR TITLE
CLI: Move SSHCommandResult processing to Base class

### LINKED ISSUE #2776: CLI: Move SSHCommandResult processing from tests to Base class
Currently after executing CLI commands, we're sending `SSHCommandResult` directly to tests without any changes or processing. This makes tests responsible for validating the command execution result. As a result, after each executed command, we're "manually" checking `return_code`, `stderr` and processing `stdout` every single time inside the test instead of doing this automatically inside the framework. 
So the simplified flow is following:
* Test asks framework to execute some CLI command
* Framework executes command and sends `SSHCommandResult` to the test
* Test checks if `return_code` is `0`
* Test checks if `stderr` is empty
*  If everything is ok, test starts working with `stdout`.

Just compare this example of API vs CLI command:
```python
# API
content_view = entities.ContentView(id=123).read()

# CLI
result = ContentView.info({'id': 123})
self.assertEqual(result.return_code, 0, "Failed to fetch object")
self.assertEqual(len(result.stderr), 0,
    "There should not be an exception here")
content_view = result.stdout
```
So, for each executed command we have about 2-4 lines of redundant code. And tests usually have not just 1 command executed, but probably 3-5 of them in average, increasing the number of redundant lines of code to 6-20 per "average" test.

The solution here is to stop sending `SSHCommandResult` directly to the tests and make framework to be responsible for `SSHCommandResult` processing. Simplified flow is following:
* Test asks framework to execute some CLI command
* Framework executes command and receives `SSHCommandResult`
* Framework checks if `return_code` is `0`
* Framework checks if `stderr` is empty
* If everything is ok, framework sends `stdout` to test, if not - raises an exception.
* Test recieves `stdout` and starts working with it

This will greatly reduce amount of code per each executed command:
```python
# Before
result = ContentView.info({'id': 123})
self.assertEqual(result.return_code, 0, "Failed to fetch object")
self.assertEqual(len(result.stderr), 0,
    "There should not be an exception here")
content_view = result.stdout

# After
content_view = ContentView.info({'id': 123})
```

That will work for about 95% cases, as we usually don't need `return_code` or `stderr`, we just need to be sure command was executed ok. 
In case we expect and error (for negative tests), we can catch an exception like this:
```python
# Before
result = ContentView.info({'id': 123})
self.assertNotEqual(result.return_code, 0, "Expected an error here")

# After
with self.assertRaises(CLICommandExecutionError):
    result = ContentView.info({'id': 123})
```
And even if we need the `return_code` (pretty rare case), we can still fetch it from the exception:
```python
# Before
result = ContentView.info({'id': 123})
self.assertEqual(result.return_code, 1, "Expected return_code 1 here")

# After
with self.assertRaises(CLICommandExecutionError) as e:
    ContentView.info({'id': 123})
self.assertEqual(e.exception.return_code, 1)
```
IMO, this change will reduce amount of code in CLI tests for ~30-50%

### PR DESCRIPTION
**Pull request by abalakh**
Closes #2776
Please, check #2776 for more details.

Commit summary:
* Added new exception - `CLIReturnCodeError` which contains return_code, stderr and msg (message).
* Created `Base._handle_response()` func which checks `return_code` and raises `CLIReturnCodeError` if needed. Returns `stdout`.
* Injected `Base._handle_response()` in `Base.execute()` (that's the easiest place to inject, no existing commands won't be affected and nothing should be rewritten)
* By default, all CLI commands running with `Base.execute()` will be wrapped by `Base._handle_response()`, if raw response is needed, `Base.execute()` now accepts optional parameter `return_raw_response`.
* Removed `Base._remove_task_status()` in favour of `Base._handle_response()` `ignore_stderr` argument.
* Updated all the CLI tests, removed `return_code` and `stderr` verification
* Some minor tests updates like update of indentation, variable names, typos, removing of single-use variables, sorting argument alphabetically etc.

Starting from now, there's no need to check for `return_code`, `stderr` and grab `stdout` when executing CLI commands, robottelo will do that for you:
```python
# Before
result = ContentView.info({'id': 123})
self.assertEqual(result.return_code, 0, "Failed to fetch object")
self.assertEqual(len(result.stderr), 0,
    "There should not be an exception here")
content_view = result.stdout

# Now
content_view = ContentView.info({'id': 123})
```
For negative tests, when non-zero `return_code` is expected, catch `CLICommandExecutionError` exception:
```python
# Before
result = ContentView.info({'id': 123})
self.assertNotEqual(result.return_code, 0, "Expected an error here")

# Now
with self.assertRaises(CLICommandExecutionError):
    result = ContentView.info({'id': 123})
```
If `return_code` or contains of `stderr` is needed, both are included in `CLICommandExecutionError`:
```python
# Before
result = ContentView.info({'id': 123})
self.assertEqual(result.return_code, 1, "Expected return_code 1 here")
self.assertGreater(len(result.sdterr), 0, "Expected errors in stderr")

# Now
with self.assertRaises(CLICommandExecutionError) as e:
    ContentView.info({'id': 123})
self.assertEqual(e.exception.return_code, 1)
self.assertGreater(len(e.exception.stderr), 0)
```

### CODE REVIEW

**Comment by abalakh** [comment]
This PR is a combination of #2778, #2779, #2801, #2806, #2814 and #2817, squashed together and rebased to the current state of master branch (with conflicts resolution).
Unfortunately, github refuses to show full diff :disappointed:
According to local git:
``` 54 files changed, 3541 insertions(+), 6367 deletions(-)```

And tests results:
```
nosetests tests/foreman/cli                       
......SSSS......SSSSSS.SSSSSS..........SSSS.S.SS.......S...........................S....................S...............................................S.....S.......................S..SS................SS.S.....S...S..S......SS...S.........SSSSSSSS....SS.....SSSSSSSSS..............SSSSSS.........................................SS...............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS....SSSSS...SSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.............SSSSSSSSSSSSSSSSSSSSSS.S.....SSSSSS.........................................SSSSSSS.S...................................SSSSSSSSSS.........................................S......................S............................................................SSSSSSSSSSS...SSSS.SSSS..S.SSSS.SSSS.SSSSSSSSS..SSS.SSS...........SS........S.S.......SSSSS.S.SSSS.SSSS.SSSS.SSSSSSSSS.SSSS.SSSS...........................................S...................................................................SSSSSSSSSSSSSSSSSS........................................SSSSSS.....................SSSS.....SSSS.S.......SSSSSSSSSSSS.SSS..SSS.............................................S....S........................................................................SSSSSSSS............SSS..SSSSSSS............................................S..............SSSSSSSSSS......SSSSSSSSS...........................S............SSSSSSSSSS.....SSSSSSSS.................SSSSSSSSSSSSSSSSSSSSSS
----------------------------------------------------------------------
Ran 1423 tests in 25820.194s

OK (SKIP=423)
```

**Comment by sthirugn** [comment]
`This PR is a combination of #2778, #2779, #2801, #2806, #2814 and #2817, squashed together and rebased to the current state of master branch (with conflicts resolution).`

I dont see a need for squashing all these commits together in one PR.  It would have been better to keep those as individual commits.  You dont need to change anything now though :)

**Comment by elyezer** [comment]
Have been reviewing the PRs to the other branch.

ACK, thanks for this massive and great improvement.

**Comment by sthirugn** [comment]
This is a great improvement to cli tests and reduced a lot of lines of redundant/boring code.

**Comment by sthirugn** [comment]
what @elyezer said, we have been reviewing these changes in the branch, so we decided to merge this PR and monitor jenkins results.

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
