### PR TITLE
update rh satellite repo with existing repo

### PR DESCRIPTION
**Pull request by vijaysawant**
### Problem Statement
Component audit - SAT-23377
As we do not have Satellite Tools repo any more we should use another repository 

### Solution
Update repo name and other details details, `RH Satellite Capsule` is another repo we can use instead of `RH Satellite Tools`

### Related Issues
No

### PRT test Cases example
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_package.py -k 'test_positive_rh_repo_search_and_check_file_list'
```

### CODE REVIEW

**Comment by vijaysawant** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_package.py -k 'test_positive_rh_repo_search_and_check_file_list'
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7790
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_package.py -k test_positive_rh_repo_search_and_check_file_list --external-logging
Test Result : =========== 4 deselected, 12 warnings, 1 error in 1046.76s (0:17:26) ===========
```

**Comment by vijaysawant** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_package.py -k 'test_positive_rh_repo_search_and_check_file_list'
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7792
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_package.py -k test_positive_rh_repo_search_and_check_file_list --external-logging
Test Result : =========== 1 passed, 4 deselected, 15 warnings in 822.61s (0:13:42) ===========
```

**Review by ColeHiggins2 — APPROVED** [review]
Looks good to me!

**Review by damoore044 — APPROVED** [review]

**Review by omkarkhatavkar — APPROVED** [review]

**Pull request merged**
