### PR TITLE
Adding coverage for Convert2Rhel Pre-conversion check

### PR DESCRIPTION
**Pull request by adarshdubey-star**
### Problem Statement
 We now have a pre_conversion check before converting the host from centos to role

### Solution

Adding support to an existing test case to cover this scenario before the actual conversion

### CODE REVIEW

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_convert2rhel.py -k test_convert2rhel_centos_with_pre_conversion_template_check

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_convert2rhel.py -k test_convert2rhel_centos_with_pre_conversion_template_check
env:
    ROBOTTELO_server__deploy_workflow: 'deploy-satellite'
    ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.15'

**Comment by adarshdubey-star** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_convert2rhel.py -k test_convert2rhel_centos_with_pre_conversion_template_check
env:
ROBOTTELO_server__deploy_workflow: 'deploy-satellite'
ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.15'
```

**Comment by adarshdubey-star** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_convert2rhel.py -k test_convert2rhel_centos_with_pre_conversion_template_check
env:
ROBOTTELO_server__deploy_workflow: 'deploy-satellite'
ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.15'
```

**Comment by adarshdubey-star** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_convert2rhel.py -k test_convert2rhel_centos_with_pre_conversion_template_check
env:
ROBOTTELO_server__deploy_workflow: 'deploy-satellite'
ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.15'
```

**Comment by lhellebr** [comment]
@adarshdubey-star Are you planning to continue work here or should we close it?

**Pull request closed without merging**
