### PR TITLE
Fix UI test failures

### PR DESCRIPTION
**Pull request by akhil-jha**
Test failures mostly due to location errors.
Adding some BZ.
Removing SatelliteToolsRepository() where not required.

### CODE REVIEW

**Comment by akhil-jha** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py

**Comment by akhil-jha** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py

**Comment by akhil-jha** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py

**Review by JacobCallahan — APPROVED** [review]

**Review by swadeley — APPROVED** [review]
ACK

**Review by mshriver — APPROVED** [review]

**Pull request merged**
