### PR TITLE
Packit testing for installed products report

### PR DESCRIPTION
**Pull request by ColeHiggins2**
Packit test for https://github.com/Katello/katello/pull/11182

### CODE REVIEW

**Comment by ColeHiggins2** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py -k test_positive_installed_products
Katello:
    katello: 11182

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8988
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_reporttemplates.py -k test_positive_installed_products --external-logging
Test Result : ========= 3 failed, 38 deselected, 148 warnings in 2671.16s (0:44:31) ==========
```

**Comment by ColeHiggins2** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py -k test_positive_installed_products
Katello:
katello: 11182

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8995
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_reporttemplates.py -k test_positive_installed_products --external-logging
Test Result : ========= 3 failed, 38 deselected, 140 warnings in 1056.82s (0:17:36) ==========
```

**Comment by ColeHiggins2** [comment]
Closing after testing

**Pull request closed without merging**
