### PR TITLE
[6.15.z] Quick fix- CI failure- for number of found CV publish tasks

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14890

### Problem Statement
`test_negative_publish_during_repo_sync`: Sometimes, more than one content-view publish task is present, 
so we should search that there are > 0, and get most recent task from search, [index 0].
- The reason seems to be because in this module, when the full session is run, an associated composite content-view still exists from another test, which will generate extra task(s).

### Related Issues
CI failure for stream, 6.15.z combined sessions, because occasionally we find 2 or 3 matching tasks, instead of exactly 1.

### PRT test Cases example
```
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync
```

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6778
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync --external-logging
Test Result : ================== 1 failed, 10 warnings in 699.40s (0:11:39) ==================
```

**Comment by Gauravtalreja1** [comment]
@damoore044 Could you resolve the conflicts and investigate the PRT failures?

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync

**Comment by damoore044** [comment]
@Gauravtalreja1 This test case was not brought into 6.15, mistakenly added the CP tag it seems.

**Pull request closed without merging**
