### PR TITLE
[6.16.z] Fix bind name

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16170

null

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_positive_create_with_https

**Comment by pondrejk** [comment]
uh, 
image
vs the comment above stating that build 8419 is successful. @omkarkhatavkar any idea why the split happens?

**Comment by devendra104** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_positive_create_with_https

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8422
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py::test_positive_create_with_https --external-logging
Test Result : ================= 2 passed, 219 warnings in 2760.47s (0:46:00) =================
```

**Review by pondrejk — APPROVED** [review]

**Pull request merged**
