### PR TITLE
Added synchronous false to avoid wait on delete

### PR DESCRIPTION
**Pull request by vijay8451**

### CODE REVIEW

**Comment by vijay8451** [comment]
Travis failure is not related to this PR.

**Comment by vijay8451** [comment]
> Can you elaborate a little why this is needed? You want to speed up test a little, or can it actually fail during deleting?
 One to speed up test a little , second not worth to wait for delete as already checking under  API tests .

**Comment by vijay8451** [comment]
@mirekdlugosz pls merge .

**Comment by mirekdlugosz** [comment]
@vijay8451 since Jameer is neither tier1 nor tier2 reviewer, unfortunately this needs to wait for another tier1/tier2 ACK.

I said many times this PR review process is not working, but I am going to follow it as long as it's there.

**Comment by vijay8451** [comment]
> @vijay8451 since Jameer is neither tier1 nor tier2 reviewer, unfortunately this needs to wait for another tier1/tier2 ACK.
> 
> I said many times this PR review process is not working, but I am going to follow it as long as it's there.

Thanks to remind , I was thinking he is tier1 :) ... let's get one more ack on it.

**Pull request merged**
