### PR TITLE
[6.15.z] The hostgroup Ansible job schedule along with host provisioning.

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15488

### Problem Statement
After provisioning a new host the assigned Ansible roles from hostgroups
are not executed on the new host

### Solution
The method below assigns a role to a hostgroup, then assigns the same hostgroup to a host, and provisions the host to verify that the role is correctly assigned.

Dependent PR: https://github.com/SatelliteQE/airgun/pull/1439

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_computeresource_vmware.py -k test_positive_provision_end_to_end
airgun: 1439

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_computeresource_vmware.py -k test_positive_provision_end_to_end
airgun: 1474

**Comment by amolpati30** [comment]
"trigger": "test-robottelo"
"pytest": "-k 'test_positive_provision_end_to_end' tests/foreman/ui/test_computeresource_vmware.py"
"airgun": "1474"

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7843
Build Status: SUCCESS
PRT Comment: pytest /opt/app-root/src/robottelo/tests/foreman -v -m build_sanity --external-logging
Test Result : ======= 11 passed, 5473 deselected, 5578 warnings in 2165.82s (0:36:05) ========
```

**Pull request merged**
