### PR TITLE
Fix TOTP generation. Fix what commit a5a5cd9e5e broke.

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by lhellebr** [comment]
These PRs are unrelated but this PR will only work with all of them (there were multiple issues in the test):
https://github.com/SatelliteQE/robottelo/pull/14645
https://github.com/SatelliteQE/airgun/pull/1312
https://github.com/SatelliteQE/robottelo/pull/14511
Internal commit updating TOTP secret.

**Review by pondrejk — APPROVED** [review]

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login
airgun: 1312

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6342
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 1 failed, 28 deselected, 4 warnings in 2531.65s (0:42:11) ===========
```

**Comment by lhellebr** [comment]
As per my previous comment, PRT will fail.

**Comment by lhellebr** [comment]
@SatelliteQE/robottelo-tier-2-reviewers

**Comment by lhellebr** [comment]
Merge?

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6729
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 1 failed, 28 deselected, 45 warnings in 2635.71s (0:43:55) ==========
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6736
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 1 failed, 28 deselected, 45 warnings in 2395.03s (0:39:55) ==========
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6740
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 1 failed, 28 deselected, 45 warnings in 2230.74s (0:37:10) ==========
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6744
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 1 failed, 28 deselected, 45 warnings in 2266.64s (0:37:46) ==========
```

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6770
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py -k test_totp_user_login --external-logging
Test Result : ========== 1 passed, 28 deselected, 45 warnings in 2279.61s (0:37:59) ==========
```

**Comment by lhellebr** [comment]
Dependencies have been merged, let's merge

**Comment by lhellebr** [comment]
It's been a month and there are no requests for changes. I'm gonna self-merge in a week from now unless somebody has objections.

**Pull request merged**
