### PR TITLE
Release AC and docker content counts testing

### PR DESCRIPTION
**Pull request by vsedmik**
### Problem Statement
BZ#2251019 blocked us from testing ansible collection content counts via CLI.

### Solution
The BZ has been resolved so we can test it now.

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_capsulecontent.py -k content_counts_for_mixed_cv

**Comment by vsedmik** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_capsulecontent.py -k content_counts_for_mixed_cv
env:
  ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.15.0'
  ROBOTTELO_server__deploy_arguments__deploy_snap_version: '8.0'
```

**Review by lhellebr — APPROVED** [review]

**Comment by vsedmik** [comment]
Ad PRT results:
- 5506 failed as it was obviously run against not-fixed-yet stream snap 45
- 5513 passed as it was run against fixed 6.15.0 snap 8.0

Stream snap 46 was released tonight so we can give it a go

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_capsulecontent.py -k content_counts_for_mixed_cv

**Review by ColeHiggins2 — APPROVED** [review]

**Review by synkd — APPROVED** [review]

**Pull request merged**
