### PR TITLE
upgrade test class parameter u2p

### PR DESCRIPTION
**Pull request by tstrych**
Unittest to pytest conversion.

@vsedmik in `tests/foreman/` these tests are under `Puppet` component, and you are the component owner. I did not change it as @lhellebr told me he will create separate PR, where he will change multiple component owners. 
 
 Let me know if you do not like some changes here :) 
 
 Test results 
 pre upgrades are okay
 
Screenshot from 2021-03-19 21-54-51
 
 but problem with post upgrades, so I keep it in draft

### CODE REVIEW

**Review by JacobCallahan — APPROVED** [review]

**Comment by tstrych** [comment]
pre-upgrade
Screenshot from 2021-03-22 23-19-33

post-upgrade
Screenshot from 2021-03-22 23-20-21

**Comment by JacobCallahan** [comment]
trigger: test-robottelo
pytest: -n 3 --collect-only tests/upgrades/test_classparameter.py

**Review by vsedmik — APPROVED** [review]
Hello @tstrych, I haven't spotted any changes I would not like, the code looks good to me. :+1: Thank you for taking this conversion!

**Comment by JacobCallahan** [comment]
trigger: test-robottelo
pytest: tests/foreman/ -n 3 --collect-only

**Comment by JacobCallahan** [comment]
test collection looks good

**Review by JacobCallahan — APPROVED** [review]

**Pull request merged**
