### PR TITLE
Renamed tests cli/tests_organization.py.

### PR DESCRIPTION
**Pull request by omaciel**
First of all, this PR renamed test_org.py to test_organization.py. Then, it updates
all test cases as per #3083.

### CODE REVIEW

**Comment by omaciel** [comment]
This required some massive refactoring which will still require further changes (to be addressed by #3139). Tests show 2 failures:

```bash
(robottelo)┌[omaciel☮Ogs-MacBook-Pro.local]-(~/hacking/robottelo)-[git://master ✗]-
└> py.test -v tests/foreman/cli/test_organization.py
=============================================================== test session starts ================================================================
platform darwin -- Python 2.7.10, pytest-2.8.3, py-1.4.31, pluggy-0.3.1 -- /Users/omaciel/.virtualenvs/robottelo/bin/python
cachedir: .cache
rootdir: /Users/omaciel/hacking/robottelo, inifile:
collected 53 items

tests/foreman/cli/test_organization.py::OrganizationTestCase::test_negative_create_name_blank PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_negative_create_name_long PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_negative_create_name_spaces PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_negative_create_same_name PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_negative_update_name PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_capsule_by_id <- robottelo/decorators.py SKIPPED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_capsule_by_name <- robottelo/decorators.py SKIPPED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_compresource_by_id PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_compresource_by_name <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_compresources_by_id PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_domain_by_id <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_domain_by_name <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_hostgroup_by_name <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_lce <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_medium_by_name <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_subnet_by_id <- robottelo/decorators.py SKIPPED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_subnet_by_name <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_template_by_id PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_template_by_name <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_templates_by_id PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_user_by_id PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_add_user_by_name PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_create_with_matching_name_label PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_create_with_name PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_create_with_name_description PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_create_with_name_label_description <- robottelo/decorators.py FAILED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_create_with_unmatched_name_label <- robottelo/decorators.py FAILED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_delete_by_id PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_delete_by_label PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_delete_by_name PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_info_by_label PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_info_by_name PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_list <- ../../.virtualenvs/robottelo/lib/python2.7/site-packages/unittest2/case.py SKIPPED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_admin_user_by_name <- ../../.virtualenvs/robottelo/lib/python2.7/site-packages/unittest2/case.py SKIPPED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_capsule_by_name <- robottelo/decorators.py SKIPPED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_compresource_by_id <- robottelo/decorators.py SKIPPED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_domain_by_id <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_domain_by_name <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_hostgroup_by_id <- robottelo/decorators.py SKIPPED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_hostgroup_by_name <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_lce <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_medium_id <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_subnet_by_id <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_subnet_by_name <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_template_by_name <- robottelo/decorators.py PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_user_by_id PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_remove_user_by_name <- ../../.virtualenvs/robottelo/lib/python2.7/site-packages/unittest2/case.py SKIPPED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_search_by_label PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_search_by_name PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_update_description PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_update_name PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_positive_update_name_description PASSED
tests/foreman/cli/test_organization.py::OrganizationTestCase::test_verify_bugzilla_1078866 PASSED

================================================ 2 failed, 42 passed, 9 skipped in 1205.68 seconds =================================================
```

Both `test_positive_create_with_name_label_description` and `test_positive_create_with_unmatched_name_label` are affected by [BZ 1142821](https://bugzilla.redhat.com/show_bug.cgi?id=1142821) which was verified `upstream` but somehow are being run by our `downstream` tests.

**Comment by sthirugn** [comment]
s/test_positive_remove_medium_id/test_positive_remove_medium_by_id

**Comment by sthirugn** [comment]
ACK pending minor comment

**Comment by sthirugn** [comment]
For future, may be we can rename tests in one PR and rename the module in another PR for viewing the changes easily.

**Pull request merged**
