### PR TITLE
Re-assign bz decorator to another issue

### PR DESCRIPTION
**Pull request by oshtaier**

### CODE REVIEW

**Comment by abalakh** [comment]
ACK

**Comment by rochacbruno** [comment]
@oshtaier can you please rebase to ensure there is no conflict with merged polarion changes.
Also please include the new required testimony tags to docsting.

ACK: pending rebase + new polarion tags

**Comment by elyezer** [comment]
Since this is not a new test, then the docstring should be already updated properly.

**Comment by oshtaier** [comment]
rebased

**Pull request merged**
