### PR TITLE
[6.13.z] Update HTTP Proxy e2e test cases

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14215

### Problem Statement
During the HTTP proxy component evaluation PX/SD/QE agreed to make several changes. This PR addresses those related to the E2E tests, in particular:
- extends `test_positive_end_to_end` to sync other content type repos via HTTP proxy
- decreases CaseImportance of some 

Some other changes improve docstings - remove redundant fields and adds more information.

### Related Issues
SAT-23276

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5933
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py --external-logging
Test Result : ===== 8 passed, 2 deselected, 321 warnings, 2 errors in 1786.91s (0:29:46) =====
```

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5943
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py --external-logging
Test Result : ===== 8 passed, 2 deselected, 332 warnings, 2 errors in 1862.17s (0:31:02) =====
```

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5947
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py --external-logging
Test Result : ========= 10 passed, 2 deselected, 535 warnings in 4387.70s (1:13:07) ==========
```

**Comment by vsedmik** [comment]
There is some flakiness in the last cli test not reproducible locally.
Since it is not caused by this PR and this PR is just a cherry-pick, we should merge and address the flakiness separately.

**Review by vsedmik — APPROVED** [review]

**Pull request merged**
