### PR TITLE
[6.11.z] Rhcloud plugin integration tests with capsule

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of commit: 6fbb365b6e635cc8137d3b09801a8fcde55a39f9

```
pytest tests/foreman/ui/test_rhcloud_insights.py -k test_insights_registration_with_capsule
=============================================================================================== test session starts ===============================================================================================
collected 11 items / 10 deselected / 1 selected                                                                                                                                                                   

tests/foreman/ui/test_rhcloud_insights.py .                                                                                                                                                                 [100%]
============================================================================ 1 passed, 10 deselected, 3 warnings in 2905.10s (0:48:25) ===========================================================================

```

Signed-off-by: Adarsh Dubey <addubey@redhat.com>

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_rhcloud_insights.py -k test_insights_registration_with_capsule

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_rhcloud_insights.py -k test_insights_registration_with_capsule

**Comment by Gauravtalreja1** [comment]
@adarshdubey-star Could you investigate PRT failures here?

**Comment by adarshdubey-star** [comment]
> @adarshdubey-star Could you investigate PRT failures here?

I am not sure about this failure had it in my local run, when the capsule is added to the org stating the taxonomy is already taken. Running on the newer sat resolved this. I don't see this as a blocker.

**Review by jyejare — APPROVED** [review]

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
