### PR TITLE
Ignore pytest-reportportal client errors

### PR DESCRIPTION
**Pull request by mshriver**
https://github.com/reportportal/agent-python-pytest#troubleshooting

Mitigates connectivity issues of the RP server during a test session.
Currently any exceptions from pytest-reportportal result in an
INTERNALERROR that kills the session.

### CODE REVIEW

**Comment by mshriver** [comment]
trigger: test-robottelo

**Review by JacobCallahan — APPROVED** [review]
APT

**Comment by mshriver** [comment]
trigger: test-robottelo

**Review by rplevka — APPROVED** [review]

**Comment by mshriver** [comment]
@rplevka also pointed out we should be using pytest-reportportal's option for REST retries.

**Pull request merged**
