### PR TITLE
ActivationKey with service level subscription (BZ1394357)

### PR DESCRIPTION
**Pull request by ldjebran**
cover BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1394357
depend on nailgun PR: https://github.com/SatelliteQE/nailgun/pull/441

```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ pytest tests/foreman/ui/test_activationkey.py -v -k "test_positive_service_level_subscription_with_custom_product"
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.20.0, services-1.2.1, mock-1.6.2, forked-0.2, cov-2.5.1
collected 39 items 
2017-09-14 13:43:12 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings


tests/foreman/ui/test_activationkey.py::ActivationKeyTestCase::test_positive_service_level_subscription_with_custom_product <- robottelo/decorators/__init__.py PASSED

================================================= 38 tests deselected ==================================================
====================================== 1 passed, 38 deselected in 558.04 seconds =======================================
```

### CODE REVIEW

**Comment by ldjebran** [comment]
from sauce test scennshots
screen

**Comment by ldjebran** [comment]
there is only one test test_hostunification.py test_negative_add_subs_to_unregistered_host
but this test is a negative one
```
            with self.assertRaises(UIError):
                self.contenthost.update(
                    hostname,
                    add_subscriptions=[DEFAULT_SUBSCRIPTION_NAME],
                )
```
it will pass anyway 
here is a screenshot getting the element by that xpath and click on it
ch_sub_select_locator

**Comment by oshtaier** [comment]
Shouldn't your custom subscription has word 'Premium' in the column?

**Comment by ldjebran** [comment]
@oshtaier the Premium service level is related to RH products and not to custom one, please also refer to to the screens how this bug has been verified for the 6.2, from where this bug has been cloned: https://bugzilla.redhat.com/show_bug.cgi?id=1370496

**Pull request merged**
