### PR TITLE
[6.10.z] GHA: Added support to handle auto-cherry-pick failure & create issue …

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
…(#10211)

* GHA: Added support to handle auto-cherry-pick failure & create issue

* added support for the google chat notification bot for AutocherryPick

Fixes https://github.com/SatelliteQE/robottelo/issues/10224

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_webhook.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_webhook.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_webhook.py

**Comment by omkarkhatavkar** [comment]
I was just testing with PRT. there is nothing need to test in this PR

**Comment by jyejare** [comment]
Even we dont needed to autocherrypick here since we are not actually autocherrypicking anything back to 6.9 from 6.10.

But still there is no harm in merging this so merging it !

**Review by jyejare — APPROVED** [review]

**Pull request merged**
