### PR TITLE
Drop unused code

### PR DESCRIPTION
**Pull request by Ichimonji10**
Before changes:

    $ git grep 'RepositoryPackagesException\|RepositoryErrataException\|get_packages\|get_errata'
    robottelo/api/utils.py:class RepositoryPackagesException(Exception):
    robottelo/api/utils.py:class RepositoryErrataException(Exception):
    robottelo/api/utils.py:def get_errata(repository_id):
    robottelo/api/utils.py:    :raises robottelo.api.utils.RepositoryErrataException: If an error occurs
    robottelo/api/utils.py:        raise RepositoryErrataException(
    robottelo/api/utils.py:def get_packages(repository_id):
    robottelo/api/utils.py:    :raises robottelo.api.utils.RepositoryPackagesException: If an error occurs
    robottelo/api/utils.py:        raise RepositoryPackagesException(
    tests/foreman/cli/test_contenthost.py:    def test_contenthost_get_errata_info(self):

After changes:

    $ git grep 'RepositoryPackagesException\|RepositoryErrataException\|get_packages\|get_errata'
    tests/foreman/cli/test_contenthost.py:    def test_contenthost_get_errata_info(self):

### CODE REVIEW

**Comment by JacobCallahan** [comment]
" 1 addition and 63 deletions" :) ACK

**Comment by sthirugn** [comment]
I don't recall why we created these functions earlier.  But @Ichimonji10 can you comment here on how to do these functionalities (get_errata, get_packages) using a Repository entity?

**Comment by Ichimonji10** [comment]
Yes, gan give example. Ask tomorrow. Comcast gave my router an IP of 192.168.0.10.

**Comment by sthirugn** [comment]
ok np and not a blocker for this PR.

ACK

**Comment by Ichimonji10** [comment]
ty @sthirugn <3

**Pull request merged**
