### PR TITLE
Comp Eval - Repo discovery via new and existing product

### PR DESCRIPTION
**Pull request by vijaysawant**
### Problem Statement
1. Merge repo discovery scenarios
`test_positive_discover_repo_via_new_product`
`test_positive_discover_repo_via_existing_product`

2. Remove upgrade scenarios from class `TestScenarioCustomRepoOverrideCheck`
`/tests/upgrades/test_repository.py -k test_pre_scenario_custom_repo_sca_toggle`
`/tests/upgrades/test_repository.py -k test_post_scenario_custom_repo_sca_toggle`

### Solution
1. new test name: `test_positive_discover_repo_via_new_and_existing_product`
2. remove class `TestScenarioCustomRepoOverrideCheck` from `/tests/upgrades/test_repository.py`

### Related Issues
1. https://issues.redhat.com/browse/SAT-25988
2. https://issues.redhat.com/browse/SAT-25999 and https://issues.redhat.com/browse/SAT-26000

### PRT test Cases example
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_repository.py -k 'test_positive_discover_repo_via_new_and_existing_product'
```

### CODE REVIEW

**Comment by vijaysawant** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_repository.py -k 'test_positive_discover_repo_via_new_and_existing_product'
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8290
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_repository.py -k test_positive_discover_repo_via_new_and_existing_product --external-logging
Test Result : ========== 1 failed, 28 deselected, 38 warnings in 1357.21s (0:22:37) ==========
```

**Comment by vijaysawant** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_repository.py -k 'test_positive_discover_repo_via_new_and_existing_product'
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8297
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_repository.py -k test_positive_discover_repo_via_new_and_existing_product --external-logging
Test Result : ========== 1 failed, 28 deselected, 38 warnings in 907.46s (0:15:07) ===========
```

**Comment by vijaysawant** [comment]
Local test execution result:
```
============================= test session starts ==============================
collecting ... 2024-08-27 15:00:22 - robottelo.collection - INFO - Processing test items to add testimony token markers
collected 30 items / 29 deselected / 1 selected

tests/foreman/ui/test_repository.py::test_positive_discover_repo_via_new_product 

========== 1 passed, 29 deselected, 100 warnings in 148.16s (0:02:28) ==========
```

**Comment by vijaysawant** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_repository.py -k 'test_positive_discover_repo_via_new_and_existing_product'
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8312
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_repository.py -k test_positive_discover_repo_via_new_and_existing_product --external-logging
Test Result : ========== 1 passed, 28 deselected, 46 warnings in 739.50s (0:12:19) ===========
```

**Review by damoore044 — APPROVED** [review]

**Review by shubhamsg199 — APPROVED** [review]

**Review by synkd — APPROVED** [review]

**Pull request merged**
