### PR TITLE
[6.16.z] Update kickstart repo sync test as per eval proposal

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16042

### Problem Statement
`test_positive_sync_kickstart_repo` test case needs update as per eval proposal - see the Related Issue.

### Solution
This PR.

### Related Issues
https://issues.redhat.com/browse/SAT-25998

### PRT test Cases example
trigger: test-robottelo
pytest: tests/foreman/api/test_repositories.py -k sync_kickstart_repo

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_repositories.py -k sync_kickstart_repo

**Comment by vsedmik** [comment]
PRT failed since we don't have 6.16 snap 1 yet. :smiley:

**Comment by vijaysawant** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_repositories.py -k sync_kickstart_repo
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8272
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_repositories.py -k sync_kickstart_repo --external-logging
Test Result : ========== 3 passed, 10 deselected, 94 warnings in 1029.92s (0:17:09) ==========
```

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
