### PR TITLE
[No Merge] Empty to run prt for Airgun changes only

### PR DESCRIPTION
**Pull request by damoore044**
### Problem Statement
Run tests as-is with minor change in [Airgun#1612](https://github.com/SatelliteQE/airgun/pull/1612)
Wait for the Packages tab to appear before entering/selecting

New Host UI > Installed Packages tab > read table :

tests/foreman/ui/test_errata.py:: test_positive_apply_for_all_hosts (upgrade)
tests/foreman/ui/test_host.py:: test_positive_update_delete_package (rhel8 only)  _Fails in setup_

### Related Issue (seen occasionally in 6.15, 6.16 el8/9)
```
Error Message
selenium.common.exceptions.NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator='.//div[contains(@class, "pf-c-tabs")]/ul/li[button[normalize-space(.)="Content"]]'); 

Stacktrace
tests/foreman/ui/test_errata.py:947: in test_positive_apply_for_all_hosts
    updated_pkg = session.host_new.get_packages(
../../lib64/python3.12/site-packages/airgun/entities/host_new.py:334: in get_packages
    view.content.packages.select()
../../lib64/python3.12/site-packages/widgetastic/widget/base.py:146: in __get__
    obj.child_widget_accessed(widget)
   
    ...
E   selenium.common.exceptions.NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator='.//div[contains(@class, "pf-c-tabs")]/ul/li[button[normalize-space(.)="Content"]]');
```
### PRT Case
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts
airgun: 1612
```
~trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py:: test_positive_update_delete_package~

### CODE REVIEW

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts
airgun: 1612

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts --count=10
airgun: 1612

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts --collect-only

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts
airgun: 1612

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 9182
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts --external-logging
Test Result : ================= 1 passed, 49 warnings in 1537.87s (0:25:37) ==================
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts
airgun: 1612

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 9189
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts --external-logging
Test Result : ================== 1 failed, 23 warnings in 832.53s (0:13:52) ==================
```

**Comment by damoore044** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py::test_positive_apply_for_all_hosts
airgun: 1612

**Pull request closed without merging**
