### PR TITLE
Depend on NailGun version 0.13.0

### PR DESCRIPTION
**Pull request by Ichimonji10**
NailGun version 0.13.0 has been released. Release notes are available on GitHub.
[1] Example test results against a downstream system:

    $ nosetests tests/foreman/api/test_multiple_paths.py
    ...S...S......S...............................................................S...S..........................................................................................................................................SSSS.SSSSSS..S.S.SSSSSS...SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
    ----------------------------------------------------------------------
    Ran 278 tests in 461.405s

    OK (SKIP=54)

[1] https://github.com/SatelliteQE/nailgun/releases/tag/0.13.0

### CODE REVIEW

**Comment by elyezer** [comment]
APT

**Comment by elyezer** [comment]
:tada:

**Comment by JacobCallahan** [comment]
APT

**Comment by elyezer** [comment]
Karma given

**Pull request merged**
