### PR TITLE
[6.12.z] Fix remotedb backup expected files

### LINKED ISSUE #12653: [Failed-AutoCherryPick] - Fix remotedb backup expected files
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/6237247032)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12645)

### PR DESCRIPTION
**Pull request by lpramuk**
Cherrypick of #12645 to `6.12.z` branch

(cherry picked from commit e075c5e4f7d91e1a7a6382b11b2fef03aa6e4258)

Fixes #12653

### CODE REVIEW

**Comment by lpramuk** [comment]
trigger: test-robottelo
pytest: tests/foreman/maintain/test_backup_restore.py -n 4

**Comment by lpramuk** [comment]
trigger: test-robottelo
pytest: tests/foreman/maintain/test_backup_restore.py -n 6

**Comment by lpramuk** [comment]
trigger: test-robottelo
pytest: tests/foreman/maintain/test_backup_restore.py -n 6

**Comment by lpramuk** [comment]
trigger: test-robottelo
pytest: tests/foreman/maintain/test_backup_restore.py -n 6

**Comment by lpramuk** [comment]
trigger: test-robottelo
pytest: tests/foreman/maintain/test_backup_restore.py -n 6

**Comment by lpramuk** [comment]
trigger: test-robottelo
pytest: tests/foreman/maintain/test_backup_restore.py -n 4

**Comment by Gauravtalreja1** [comment]
@lpramuk Can you check the failing PRT? are this new backup expected files valid for remotedb?

**Comment by lpramuk** [comment]
`Failed to establish a new connection: [Errno 111] Connection refused`  capsule error is not related.

Incremental restore is failing due to unreported? product bug

**Review by Griffin-Sullivan — APPROVED** [review]

**Pull request merged**
