### PR TITLE
[6.12.z] update Insights test to use new host page (#12582)

### PR DESCRIPTION
**Pull request by mstrlc**
Parent PR https://github.com/SatelliteQE/robottelo/pull/12582

* update Insights test to use new host page

* update whole test to use `host_new`

(cherry picked from commit b23414be98f81f55f4a2b9eed9d4c2367ac7840a)

### CODE REVIEW

**Comment by mstrlc** [comment]
Closes #12697

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_rhcloud_insights.py -k 'test_host_details_page[rhel9]'

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_rhcloud_insights.py -k 'test_host_details_page or test_insights_registration_with_capsule'

**Comment by mstrlc** [comment]
After looking into it, I found that the `new_host` entity is not fully supported in Airgun's 6.12 branch. Closing this PR.

**Pull request closed without merging**
