### PR TITLE
api paths updated for 6.13

### PR DESCRIPTION
**Pull request by pondrejk**
dev approval requested on satellite-dev list, draft state until then

### CODE REVIEW

**Review by synkd — APPROVED** [review]
Acking as dev approval has been given on the email list.

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_api_endtoend.py -k test_positive_get_links

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_api_endtoend.py -k test_positive_get_links

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_api_endtoend.py -k test_positive_get_links

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
