### PR TITLE
Skip API repository upload content tests due to open BZ

### PR DESCRIPTION
**Pull request by abalakh**
`entites.Repository().upload_content()` is broken as per [BZ1329292](https://bugzilla.redhat.com/show_bug.cgi?id=1329292), skipping all affected tests.

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK

**Comment by oshtaier** [comment]
Can you provide some results just to confirm that classes are skipped?

**Comment by abalakh** [comment]
```python
py.test tests/foreman/api/test_contentview.py -k 'ContentViewPublishPromoteTestCase'
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 51 items 

tests/foreman/api/test_contentview.py sssssssssssssssssss

============ 32 tests deselected by '-kContentViewPublishPromoteTestCase' ============
===================== 19 skipped, 32 deselected in 1.86 seconds ======================
py.test tests/foreman/api/test_puppetmodule.py -k 'ContentViewVersionSearchTestCase'
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 4 items 

tests/foreman/api/test_puppetmodule.py ss

============= 2 tests deselected by '-kContentViewVersionSearchTestCase' =============
====================== 2 skipped, 2 deselected in 1.82 seconds =======================
```

**Comment by oshtaier** [comment]
ACK

**Pull request merged**
