### PR TITLE
[6.2.z] Update Hammer options for new additions

### LINKED ISSUE #4164: Update HammerCommandsTestCase.test_positive_all_options
- [x] tests.foreman.cli.test_hammer.HammerCommandsTestCase.test_positive_all_options

following options seems to be added for 6.2.7:
```
E           AssertionError: 
E           hammer auth-source ldap create
E             Added options:
E               * organization-ids
E               * organizations
E               * location-ids
E               * locations
E           
E           hammer auth-source ldap list
E             Added options:
E               * organization
E               * location-id
E               * location
E               * organization-id
E           
E           hammer auth-source ldap update
E             Added options:
E               * organization-ids
E               * organizations
E               * location-ids
E               * locations
E           
E           hammer csv activation-keys
E             Added options:
E               * search
E           
E           hammer csv content-hosts
E             Added options:
E               * search
E               * columns
E           
E           hammer csv settings
E             Added options:
E               * search
E           
E           hammer csv subscriptions
E             Added options:
E               * search
```

### PR DESCRIPTION
**Pull request by lpramuk**
Fixes #4164

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK pending test results (yeah, I know that 1 test take a lot of time)

**Comment by lpramuk** [comment]
```$ nosetests -v test_hammer:HammerCommandsTestCase.test_positive_all_options
check all provided options for every hammer command ... FAIL

======================================================================
FAIL: check all provided options for every hammer command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lpramuk/git/SatelliteQE/robottelo/tests/foreman/cli/test_hammer.py", line 160, in test_positive_all_options
    '\n' + _format_commands_diff(self.differences)
AssertionError: 
hammer discovery_rule (new command)
  Added subcommands:
    * info
    * create
    * list
    * update
    * delete
  Added options:
    * help

hammer discovery_rule create (new command)
  Added options:
    * search
    * hostname
    * hostgroup-title
    * hostgroup-id
    * enabled
    * hostgroup
    * name
    * priority
    * hosts-limit
    * max-count
    * help

hammer discovery_rule delete (new command)
  Added options:
    * help
    * name
    * id

hammer discovery_rule info (new command)
  Added options:
    * help
    * name
    * id

hammer discovery_rule list (new command)
  Added options:
    * search
    * order
    * help
    * page
    * per-page

hammer discovery_rule update (new command)
  Added options:
    * search
    * hostname
    * hostgroup-title
    * hostgroup-id
    * enabled
    * hostgroup
    * name
    * priority
    * hosts-limit
    * max-count
    * id
    * new-name
    * help

```

**Comment by lpramuk** [comment]
it's failing since the unrelated bug https://bugzilla.redhat.com/show_bug.cgi?id=1219610 was CLOSED - WONTFIX

Going to create separate issue for this change.

**Comment by oshtaier** [comment]
ACK, `discovery_rule` issues will be resolved in scope of another PRs

**Pull request merged**
