### PR TITLE
Mark some skipped tests with run_in_one_thread decorator

### PR DESCRIPTION
**Pull request by abalakh**

### CODE REVIEW

**Comment by sthirugn** [comment]
what is the criteria to move these threads to single thread?

**Comment by abalakh** [comment]
@sthirugn latest automation run :) i've just looked through the failures and saw some tests failed because of race condition with importing subscriptions. It was hard to cover every single sequential candidate among 1800  tests from the first attempt, so another PR was expected.

**Comment by sthirugn** [comment]
I spoke to @abalakh and as per his comment - all the affected tests here are manifest related.

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
