### PR TITLE
[6.13.z] Add e2e tests for Global Registration

### LINKED ISSUE #10541: [Failed-AutoCherryPick] - Add e2e tests for Global Registration
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/3939757677)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10458)

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
Manual cherrypick of #10458
Fixes #10541

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
PRT failures are known issue and not related to the changes in this PR

**Review by adarshdubey-star — APPROVED** [review]

**Review by synkd — CHANGES_REQUESTED** [review]
I made the same request in the other cherry pick PR: can you please revert the changes to satellite_mixins.py? I explain the rationale for this request in https://github.com/SatelliteQE/robottelo/pull/10554.

**Review by synkd — APPROVED** [review]

**Comment by shweta83** [comment]
trigger: test-robottelo
nailgun: 865
pytest: tests/foreman/api/test_registration.py::test_host_registration_end_to_end tests/foreman/cli/test_registration.py::test_host_registration_end_to_end tests/foreman/destructive/test_remoteexecution.py::test_positive_use_alternate_directory tests/foreman/cli/test_remoteexecution.py::TestAsyncSSHProviderRex tests/foreman/cli/test_remoteexecution.py::TestPullProviderRex

**Review by pondrejk — APPROVED** [review]
Noticed several manifest-related issues in the prt run

**Review by pondrejk — COMMENTED** [review]
Noticed several manifest-related issues in the prt run

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_registration.py::test_host_registration_end_to_end tests/foreman/cli/test_registration.py::test_host_registration_end_to_end tests/foreman/destructive/test_remoteexecution.py::test_positive_use_alternate_directory tests/foreman/cli/test_remoteexecution.py::TestAsyncSSHProviderRex tests/foreman/cli/test_remoteexecution.py::TestPullProviderRex

**Comment by Gauravtalreja1** [comment]
@pondrejk those manifest issues were fixed by @synkd in PR #10594, now remaining failures are expected and are known issues

**Pull request merged**
