### PR TITLE
[6.13.z] Add test coverage for provisioning with fips_enabled

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
(cherry picked from commit b7ce955601e9b7bc5ffad9133ee0fdacb779fb5c)
Manual Cherrypick of https://github.com/SatelliteQE/robottelo/pull/12695

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py::test_rhel_pxe_provisioning_fips_enabled
provisioning: true

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py::test_rhel_pxe_provisioning_fips_enabled
provisioning: true

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py::test_rhel_pxe_provisioning_fips_enabled[rhel8-uefi]
provisioning: true

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioningtemplate.py::TestProvisioningTemplate::test_positive_template_check_fips_enabled

**Review by shubhamsg199 — APPROVED** [review]
ACK

**Pull request merged**
