### PR TITLE
Fix travis failures

### PR DESCRIPTION
**Pull request by abalakh**
flake8 was updated on travis and is catching more errors. sphynx was pointing to some old errors too. Fixing them to make travis happy

### CODE REVIEW

**Comment by abalakh** [comment]
Can't reproduce most of them locally, so will try to update this pr till failures are gone

**Comment by rochacbruno** [comment]
ACK

**Comment by sthirugn** [comment]
ACK

**Comment by elyezer** [comment]
@abalakh thank you very much!

**Pull request merged**
