### PR TITLE
[6.13.z] - remove the all nailgun imports from UI folder

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
#### Problem Statement

We are using the direct imports from the nailgun rather than directly using from target_sat

#### Solution

Direct Imports Removed: We've cleaned up our codebase by eliminating direct imports from the Nailgun package.

Using target_sat, module_target_sat, class_target_sat: Modified the API calls and using the target_sat.api. pattern for all API calls.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6100
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/ -m e2e --external-logging
Test Result : = 2 failed, 12 passed, 777 deselected, 908 warnings, 10 errors in 6101.76s (1:41:41) =
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6174
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/ --external-logging
Test Result : = 203 failed, 433 passed, 23 skipped, 57 deselected, 11995 warnings, 88 errors in 94713.20s (1 day, 2:18:33) =
```

**Comment by Gauravtalreja1** [comment]
@omkarkhatavkar Could you rebase and update this PR?

**Comment by omkarkhatavkar** [comment]
@Gauravtalreja1 @jyejare Rebase Done !

**Review by pondrejk — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
@omkarkhatavkar Could you rebase this PR again?

**Review by pnovotny — APPROVED** [review]
LGTM. Rebase & conflicts resolve needed.

**Comment by omkarkhatavkar** [comment]
@Gauravtalreja1 @Gauravtalreja1 @pondrejk can we merge this ?

**Comment by pnovotny** [comment]
ACK

**Review by JacobCallahan — APPROVED** [review]

**Pull request merged**
