### PR TITLE
ddt removal in smoke tests

### PR DESCRIPTION
**Pull request by sthirugn**
*Note*:
None of the tests are affected so no testing necessary.

### CODE REVIEW

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Comment by oshtaier** [comment]
ACK

**Comment by abalakh** [comment]
Double checked. So it appears that we imported ddt, but haven't ever used it in smoke tests. That's weird.
Anyway, ACK.

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
