### PR TITLE
Test fixes for errata

### PR DESCRIPTION
**Pull request by adarshdubey-star**
```
With better results run with https://github.com/SatelliteQE/airgun/pull/754/
Attempts to fix:
test_positive_view_cve
test_positive_get_count_for_host
test_positive_get_applicable_for_host
test_content_host_errata_page_pagination
test_end_to_end
test_positive_apply_for_all_hosts
```

### CODE REVIEW

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k  'test_end_to_end and test_positive_apply_for_all_hosts '
airgun: 754

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py 
airgun: 754

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py
airgun: 754

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

**Review by latran — APPROVED** [review]
PRT is still failing.  Can you recheck?  May need to update the airgun PR.

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py -k 'test_positive_get_count_for_host'

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py -k 'test_positive_view_cve'

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_positive_view_cve'

**Comment by adarshdubey-star** [comment]
The PR can be merged the failures are not related to changes!

**Review by Gauravtalreja1 — APPROVED** [review]

**Review by akhil-jha — APPROVED** [review]

**Review by ColeHiggins2 — APPROVED** [review]

**Review by jyejare — APPROVED** [review]

**Pull request merged**
