### PR TITLE
Update travis requirements

### PR DESCRIPTION
**Pull request by elyezer**
Update travis requirements to match current set of commands being
executed. Install robottelo itself to allow documentation generation
through sphinx autodoc. And install coveralls to allow coverage
reporting run for real.

### CODE REVIEW

**Comment by omaciel** [comment]
APT

**Comment by omaciel** [comment]
Merging

**Comment by elyezer** [comment]
Now it is building. Next step will be increase the coverage percentage :smile:

**Comment by omaciel** [comment]
Cool!

**Pull request merged**
