### PR TITLE
Fix test_positive_assign_http_proxy_to_products

### PR DESCRIPTION
**Pull request by jameerpathan111**
Fixes tests/foreman/api/test_product.py::ProductTestCase::test_positive_assign_http_proxy_to_products

### CODE REVIEW

**Comment by mirekdlugosz** [comment]
@jameerpathan111 flake8 in travis complains about imported but unused module.

Also, can you explain how it fixes the test? Did Satellite stop putting fqdn in log during sync? Was that expected change? Is there another log file we should maybe look into instead?

**Comment by jameerpathan111** [comment]
> Also, can you explain how it fixes the test? Did Satellite stop putting fqdn in log during sync? Was that expected change? Is there another log file we should maybe look into instead?

The thing is, the test passes locally and I can see the fqdn in log as well but on automation m/c it fails for unknown reason.
And I think checking log for fqdn is not that important and we can skip that part till we find root cause. we have other tests which use real proxy to sync content so this change shouldn't cause any problem.

@mirekdlugosz what do you think we should do?

**Comment by jameerpathan111** [comment]
@mirekdlugosz as per our discussion offline, I will try to check what's wrong with automation m/c and see if I can fix the issue.

**Comment by jyejare** [comment]
@jameerpathan111 Whats ur plan on this ? Is the test still failing ? if yes, would you like to continue on this PR ?

Else lets close it ?

**Comment by JacobCallahan** [comment]
@jameerpathan111 can you revisit this PR and see if the issue persists in latest automation? If so, can you update the PR? Thanks

**Comment by jameerpathan111** [comment]
@JacobCallahan I no longer see this issue in latest automation run.

**Comment by JacobCallahan** [comment]
> @JacobCallahan I no longer see this issue in latest automation run.

Perfect, thanks for closing!

**Pull request closed without merging**
