### PR TITLE
[6.14.z] Add --f-p-c-pulcpore-hide-guarded-distributions option

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11759

A [new option was added](https://github.com/theforeman/puppet-foreman_proxy_content/commit/fdc6a78dbc894f6c68e52d52f2d01632b04d70f4) to expose Pulpcore's `HIDE_GUARDED_DISTRIBUTIONS` option.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/installer/test_installer.py

**Comment by Griffin-Sullivan** [comment]
@ekohl are we going to get 3.7 in 6.14? If so I am tempted to just merge this and wait for the test to pass when it arrives in a snap.

**Comment by ekohl** [comment]
We should. This feature specifically requested to make into Satellite.

**Comment by ekohl** [comment]
It is in the latest snap so let's see if I can retrigger it:
trigger: test-robottelo
pytest: tests/foreman/installer/test_installer.py

**Comment by Griffin-Sullivan** [comment]
Was there a problem with getting that option into the snap? We got the same failure on snap 6

**Comment by ekohl** [comment]
Looks like that's a bug, because it still uses the RC for the installer and not the GA version. I'm also leaning to merging this so we will fail snaps until it's in.

**Review by Griffin-Sullivan — APPROVED** [review]
Fine with me!

**Review by Gauravtalreja1 — APPROVED** [review]
LGTM, but would wait for green PRT results to get this merged

**Comment by Gauravtalreja1** [comment]
Merging this, as installer seems to be fixed for GA version and contains a fix for mentioned flag

**Pull request merged**
