### PR TITLE
fix to use subscription entity

### PR DESCRIPTION
**Pull request by swadeley**
ref: nailgun issue#750

Hello this PR depends on https://github.com/SatelliteQE/nailgun/pull/754

### CODE REVIEW

**Comment by swadeley** [comment]
robottelo]$ pytest --show-capture=no tests/foreman/api/test_hostcollection.py -k test_positive_add_remove_subscription
================================= test session starts ===============================================
platform linux -- Python 3.7.9, pytest-4.6.3, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo_1/robottelo
plugins: xdist-2.0.0, services-1.3.1, mock-1.10.4, forked-1.3.0, cov-2.10.1
collecting ... 2020-09-23 14:23:17 - conftest - DEBUG - Collected 20 test cases
collected 20 items / 19 deselected / 1 selected                                                                  

tests/foreman/api/test_hostcollection.py .                                                                 [100%]


========================== 1 passed, 19 deselected, 2 warnings in 198.56 seconds ========================

**Review by mirekdlugosz — APPROVED** [review]
Great! Thank you for this change

**Review by jameerpathan111 — APPROVED** [review]
LGTM, once https://github.com/SatelliteQE/nailgun/pull/754 is merged then we can merge this PR.

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
