### PR TITLE
Add test for foreman tasks

### PR DESCRIPTION
**Pull request by Ichimonji10**
Test that it is possible to get a summary of information about foreman tasks.

Test results:

    $ nosetests tests/foreman/api/test_foremantask.py
    S.
    ----------------------------------------------------------------------
    Ran 2 tests in 1.037s

    OK (SKIP=1)

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Related to SatelliteQE/nailgun#207.

**Comment by Ichimonji10** [comment]
Ugh. [BZ 1244904](https://bugzilla.redhat.com/show_bug.cgi?id=1244904) specifies that `parent_task_id` should be used for the search term, not `parent_id`. Looks like I need to update the test. I'm going to split this PR so that the `summary()` test can be added right away.

**Comment by Ichimonji10** [comment]
Here's an example of the `summary()` method in action:

```python
>>> from nailgun import entities
>>> entities.ForemanTask().summary()
[
    {u'count': u'1', u'state': u'paused', u'result': u'pending'},
    {u'count': u'6', u'state': u'paused', u'result': u'error'},
    {u'count': u'1', u'state': u'running', u'result': u'pending'},
    {u'count': u'96', u'state': u'stopped', u'result': u'error'},
    {u'count': u'4184', u'state': u'stopped', u'result': u'success'},
    {u'count': u'2', u'state': u'stopped', u'result': u'warning'}
]
```

**Comment by Ichimonji10** [comment]
I've shrunk down this PR so it only tests the `summary()` method. A test for [BZ 1244904](https://bugzilla.redhat.com/show_bug.cgi?id=1244904) will come in a separate PR.

**Comment by omaciel** [comment]
ACK

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
