### PR TITLE
Do not pass release version for sat tools repo

### PR DESCRIPTION
**Pull request by sthirugn**

### CODE REVIEW

**Comment by sthirugn** [comment]
This change got lost in the massive code update in the last few days :)

**Comment by omaciel** [comment]
ACK and merge

**Comment by sthirugn** [comment]
Thank you :)

**Comment by abalakh** [comment]
Wait a sec. Did that fix really work? @sthirugn , have you tried testing it? I think you forgot to delete quotation marks, so instead of not sending the release version you are sending some 'None'.

**Comment by sthirugn** [comment]
@abalakh you are right, it is supposed to be None instead of 'None'. Fixed in https://github.com/SatelliteQE/robottelo/pull/2661. Thank you.

**Pull request merged**
