### PR TITLE
Optimize CLI tests for sync plans (#6812)

### PR DESCRIPTION
**Pull request by swadeley**
make CLI tests similar to API tests

This pull request for branch 6812-3.1 has the updates for the CLI tests to match changes in API tests in #6825

### CODE REVIEW

**Comment by swadeley** [comment]
robottelo]$ git status
On branch issue#6812-3.1
nothing to commit, working tree clean
robottelo]$ pytest --capture=no tests/foreman/cli/test_syncplan.py::SyncPlanTestCase
2019-04-04 17:47:58 - conftest - DEBUG - Registering custom pytest_namespace

======================== test session starts =====================================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.6.0, pluggy-0.8.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /Downloads/robottelo, inifile:
plugins: xdist-1.23.2, services-1.3.1, repeat-0.8.0, mock-1.10.0, forked-0.2, cov-2.6.0
collecting ... 2019-04-04 17:47:58 - conftest - DEBUG - BZ deselect is disabled in settings

collected 19 items                                         

=================== 19 passed, 4 warnings in 2945.58 seconds ===============

**Comment by swadeley** [comment]
> moved discussion to #6855

But why? This pull request is about CLI tests and that one is about UI tests.

**Comment by swadeley** [comment]
Hello

adding a line to make sync plans that are "custom cron" not generate a random cron expression but rather use the supplied expression (every 4 minutes) (reasons here https://github.com/SatelliteQE/robottelo/issues/6812#issuecomment-487080174)

robottelo]$ for i in {1..6}; do echo $i; pytest --dist=each --tx=3*popen --show-capture=no tests/foreman/cli/test_syncplan.py::SyncPlanTestCase::test_positive_synchronize_custom_product_future_sync_date; done
1
============================ test session starts ======================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.6.0, pluggy-0.8.1
shared_function enabled - OFF - scope: - storage: file
rootdir: /Downloads/robottelo, inifile:
plugins: xdist-1.23.2, services-1.3.1, repeat-0.8.0, mock-1.10.0, forked-0.2, cov-2.6.0
gw0 [1] / gw1 [1] / gw2 [1]
scheduling tests via EachScheduling
. [100%].. [100%] [100%]

=================== 3 passed, 6 warnings in 355.67 seconds ====================
2019-04-26 14:35:14 - conftest - DEBUG - Registering custom pytest_namespace

2

================ 3 passed, 6 warnings in 355.05 seconds ========================
2019-04-26 15:05:08 - conftest - DEBUG - Registering custom pytest_namespace

6
======================== test session starts =================================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.6.0, pluggy-0.8.1
shared_function enabled - OFF - scope: - storage: file
rootdir: /Downloads/robottelo, inifile:
plugins: xdist-1.23.2, services-1.3.1, repeat-0.8.0, mock-1.10.0, forked-0.2, cov-2.6.0
gw0 [1] / gw1 [1] / gw2 [1]
scheduling tests via EachScheduling
. [100%]. [100%]. [100%]
=============== 3 passed, 6 warnings in 370.80 seconds =============================
2019-04-26 15:11:04 - conftest - DEBUG - Registering custom pytest_namespace

**Comment by swadeley** [comment]
I have done a rebase and squashed the commits

**Comment by JacobCallahan** [comment]
@pondrejk mind a quick review on this? Thanks!

**Comment by swadeley** [comment]
Thank you @pondrejk

**Pull request merged**
