### PR TITLE
Add test for syncable export with restrictive permissions

### PR DESCRIPTION
**Pull request by vsedmik**
### Problem Statement
Coverage for [BZ#2233162](https://bugzilla.redhat.com/show_bug.cgi?id=2233162) is missing

### Solution
This PR.
`metadata.json` is the only exception where restrictive permissions are expected

### PRT test Cases example
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k permissions

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k permissions

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6970
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_satellitesync.py -k permissions --external-logging
Test Result : ========== 1 passed, 33 deselected, 42 warnings in 784.37s (0:13:04) ===========
```

**Review by pondrejk — APPROVED** [review]

**Review by rmynar — COMMENTED** [review]
Can we be sure that all involved components (services) use the modified umask settings? May it be useful to launch `satellite-maintain service restart` when changing umask?

**Comment by vsedmik** [comment]
> Can we be sure that all involved components (services) use the modified umask settings? May it be useful to launch `satellite-maintain service restart` when changing umask?

The issue was that the rights of the user executing the export command were used for the exported files. This way we set it globally for whatever user is used by `target_sat.execute()`, so IMHO no service restart is necessary.

**Comment by rmynar** [comment]
> > Can we be sure that all involved components (services) use the modified umask settings? May it be useful to launch `satellite-maintain service restart` when changing umask?
> 
> The issue was that the rights of the user executing the export command were used for the exported files. This way we set it globally for whatever user is used by `target_sat.execute()`, so IMHO no service restart is necessary.

Sounds good, ACK :)

**Review by rmynar — APPROVED** [review]

**Pull request merged**
