### PR TITLE
Removing Auto Release WF from non-master branch

### PR DESCRIPTION
**Pull request by jyejare**
Removing the WF for `Automatic Releases` from non-master branches as only master branch commits are considered in Github Releases!

This was been cherrypicked into 6.14.z during the Branching process which should have been removed !

### CODE REVIEW

**Review by ogajduse — APPROVED** [review]
as I mentioned in SatelliteQE/nailgun#995,
> If we have a documentation for branching, adding an extra step to remove the file from the newly branched .z branch would be a good idea.

**Comment by jyejare** [comment]
@ogajduse We will soon have auto branching where we will make sure to delete it !

**Review by Gauravtalreja1 — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
@jyejare As we need to remove it from all supported .z branches, shouldn't we cherrypick this commit onto those branches?

**Comment by jyejare** [comment]
@Gauravtalreja1 It's only in 6.14.z branch now as it's introduced in 6.14.z time only.

**Pull request merged**
