### PR TITLE
[6.15.z] Add workaround for BZ:2255264 and extend for OS version check

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
Manual Cherrypick of https://github.com/SatelliteQE/robottelo/pull/14094
### Problem Statement
Bootdisk provisioning passes for VMware 8, but installed status isn't updated, we've BZ:2255264 reported for it

### Solution
Handling BZ:2255264 in automation while this is open, and extending the test to check OS version when provisioning is completed for all methods including bootdisk

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_vmware.py -k test_positive_provision_end_to_end
provisioning: true

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5876
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_computeresource_vmware.py -k test_positive_provision_end_to_end --external-logging --include-onprem-provisioning
Test Result : = 11 failed, 13 passed, 2 deselected, 453 warnings, 1 error in 31332.87s (8:42:12) =
```

**Comment by lhellebr** [comment]
PRT doesn't look good

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_computeresource_vmware.py -k test_positive_provision_end_to_end
provisioning: true

**Pull request closed without merging**
