### PR TITLE
6.9.z pit markers

### PR DESCRIPTION
**Pull request by rplevka**
server scenario:
```
$ pytest -m pit_server --collect-only tests/foreman/
=== test session starts ===
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/rplevka/work/rplevka/robottelo, configfile: pyproject.toml
plugins: forked-1.3.0, services-2.2.1, reportportal-5.0.8, mock-3.6.1, ibutsu-1.16, xdist-2.4.0
collected 5561 items / 5545 deselected / 16 selected                                                                                                                                                                                          

<Package api>
  <Module test_contentview.py>
    <Class TestContentView>
        <Function test_negative_add_dupe_modules>
    <Class TestContentViewPublishPromote>
        <Function test_positive_publish_multiple_repos>
  <Module test_rhsm.py>
    <Function test_positive_path>
  <Module test_subscription.py>
    <Function test_positive_create>
    <Function test_sca_end_to_end>
<Package cli>
  <Module test_contentaccess.py>
    <Function test_positive_list_installable_updates>
    <Function test_positive_erratum_installable>
  <Module test_contentview.py>
    <Class TestContentView>
        <Function test_positive_publish_rh_and_custom_content>
  <Module test_host.py>
    <Function test_positive_erratum_applicability>
    <Function test_syspurpose_end_to_end>
  <Module test_remoteexecution.py>
    <Class TestRemoteExecution>
        <Function test_positive_run_default_job_template_by_ip[rhel7]>
        <Function test_positive_run_job_effective_user_by_ip[rhel7]>
    <Class TestAnsibleREX>
        <Function test_positive_run_effective_user_job[rhel7]>
        <Function test_positive_run_packages_and_services_job[rhel7]>
        <Function test_positive_run_packages_and_services_job[rhel7_fips]>
<Package ui>
  <Module test_user.py>
    <Function test_positive_end_to_end>

=== warnings summary ===
16/5561 tests collected (5545 deselected) in 19.41s ===
```

client scenario:
```
$ pytest -m pit_client --collect-only tests/foreman/
=== test session starts 
===
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/rplevka/work/rplevka/robottelo, configfile: pyproject.toml
plugins: forked-1.3.0, services-2.2.1, reportportal-5.0.8, mock-3.6.1, ibutsu-1.16, xdist-2.4.0
collected 5561 items / 5550 deselected / 11 selected                                                                                                                                                                                          

<Package api>
  <Module test_errata.py>
    <Function test_errata_installation_with_swidtags>
  <Module test_subscription.py>
    <Function test_sca_end_to_end>
<Package cli>
  <Module test_contentaccess.py>
    <Function test_positive_list_installable_updates>
    <Function test_positive_erratum_installable>
  <Module test_host.py>
    <Function test_positive_erratum_applicability>
    <Function test_syspurpose_end_to_end>
  <Module test_remoteexecution.py>
    <Class TestRemoteExecution>
        <Function test_positive_run_default_job_template_by_ip[rhel7]>
        <Function test_positive_run_job_effective_user_by_ip[rhel7]>
    <Class TestAnsibleREX>
        <Function test_positive_run_effective_user_job[rhel7]>
        <Function test_positive_run_packages_and_services_job[rhel7]>
        <Function test_positive_run_packages_and_services_job[rhel7_fips]>

===11/5561 tests collected (5550 deselected) in 19.20s ===
```

### CODE REVIEW

**Comment by rplevka** [comment]
trigger: test-robottelo
pytest: -m pit_client tests/foreman/api/test_subscription.py

**Comment by rplevka** [comment]
trigger: test-robottelo
pytest: -m pit_client tests/foreman/api/test_subscription.py

**Comment by rplevka** [comment]
trigger: test-robottelo
pytest: -m pit_client tests/foreman/api/test_subscription.py

**Comment by rplevka** [comment]
trigger: test-robottelo
pytest: -m pit_client tests/foreman

**Comment by rplevka** [comment]
trigger: test-robottelo
pytest: -m pit_server tests/foreman

**Comment by rplevka** [comment]
robottelo runner's failed tests are unrelated to the changes

**Review by ogajduse — APPROVED** [review]

**Review by pondrejk — APPROVED** [review]

**Pull request merged**
