### PR TITLE
New cv tests

### PR DESCRIPTION
**Pull request by latran**
Adding test cases for the new cv UI.  This will most likely be in draft to test out airgun PRs for the time being.

### CODE REVIEW

**Comment by latran** [comment]
trigger: test-robottelo
pytest: -v tests/foreman/ui/test_contentview_new.py
airgun: 749

**Comment by latran** [comment]
trigger: test-robottelo
pytest: -v tests/foreman/ui/test_contentview_new.py
airgun: 749

**Comment by latran** [comment]
trigger: test-robottelo
pytest: -v tests/foreman/ui/test_contentview_new.py
airgun: 749

**Comment by latran** [comment]
trigger: test-robottelo
pytest: -v tests/foreman/ui/test_contentview_new.py
airgun: 749

**Comment by latran** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview_new.py
airgun: 749

**Comment by Gauravtalreja1** [comment]
@jameerpathan111 As you own ContentViews now, would you like this PR assigned to you?

**Comment by omkarkhatavkar** [comment]
Can one of the admins verify this patch?

**Comment by jameerpathan111** [comment]
@Gauravtalreja1 I don't plan to work on this.

**Comment by Gauravtalreja1** [comment]
@jameerpathan111 Thanks for responding.
@vsedmik As Team Phoenix owns ContentViews, would you like this PR assigned to you/someone?

**Pull request closed without merging**
