### PR TITLE
Update robottelo to use fixtures.pulpproject.org

### PR DESCRIPTION
**Pull request by Griffin-Sullivan**
Changed the CUSTOM_FILE_REPO constant to use fixtures.pulpproject and skipped all tests affected by DRPM, SRPM, and FAKE_7_YUM_REPO. New DRPM, SRPM, and FAKE_7_YUM_REPO will need to be created manually and ran locally.

### CODE REVIEW

**Comment by Griffin-Sullivan** [comment]
Output for tests affected by CUSTOM_FILE_REPO:

==================================== test session starts =====================================
platform linux -- Python 3.8.3, pytest-4.6.9, py-1.8.0, pluggy-0.13.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/gsulliva/Programming/robottelo
plugins: mock-1.10.4, services-1.3.1, forked-1.1.3, xdist-1.32.0, cov-2.9.0
collecting ... 2020-06-22 20:54:47 - conftest - DEBUG - Collected 7 test cases
collected 7 items                                                                                                

test_repository.py .......                                                                                 [100%]

================================= 7 passed in 218.46 seconds ==================================

**Comment by Griffin-Sullivan** [comment]
Output for skipped tests:

============================= test session starts ==============================
platform linux -- Python 3.8.3, pytest-4.6.9, py-1.8.0, pluggy-0.13.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/gsulliva/Programming/robottelo
plugins: mock-1.10.4, services-1.3.1, forked-1.1.3, xdist-1.32.0, cov-2.9.0
collecting ... 2020-06-23 13:23:15 - conftest - DEBUG - Collected 13 test cases
collected 13 items                                                             

cli/test_repository.py ssssss                                          [ 46%]
api/test_repository.py ssssss                                        [ 92%]
api/test_contentmanagement.py s                                [100%]

========================== 13 skipped in 3.18 seconds ==========================

**Comment by daviddavis** [comment]
The drpm and srpm fixtures were deprecated and then removed. See https://github.com/pulp/pulp-fixtures/commit/3f5b11faca3110bb585eb0b651c8aa745be86d12.

You should be able to use https://fixtures.pulpproject.org/drpm-signed/ and https://fixtures.pulpproject.org/srpm-signed/ instead.

**Comment by swadeley** [comment]
Hello

File `tests/foreman/api/test_repository.py` is case component `Repositories` which is owned by @rochacbruno 
Se we should tag him for an ack.

**Comment by swadeley** [comment]
Hello

Bruno moved to other team and I am now component owner for Repositories, so we no longer need his ACK.

**Pull request merged**
