### PR TITLE
ddt removal in ui activation keys and ad user group tests

### PR DESCRIPTION
**Pull request by sthirugn**
This PR also introduces fixes to reuse browser object between subTests to improve the run time.

### CODE REVIEW

**Comment by sthirugn** [comment]
Tests are running currently, will paste the tests results when done.

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Comment by sthirugn** [comment]
Ran 34 tests of test_activationkey.py locally and they passed.

**Comment by oshtaier** [comment]
Please, provide results there

**Comment by elyezer** [comment]
ACK

**Comment by elyezer** [comment]
The results @oshtaier have asked is pasted. Will consider as an ACK.

ACK

**Comment by oshtaier** [comment]
@elyezer I am sorry, but where pasted?

**Comment by sthirugn** [comment]
Alex, I think you are asking for this:
```sh
# nosetests tests/foreman/ui/test_activationkey.py
.....S..S...S.....................
----------------------------------------------------------------------
Ran 34 tests in 4879.816s

OK
```

**Comment by oshtaier** [comment]
@sthirugn Yes. Thank you !!

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
