### PR TITLE
[6.15.z] Add OS Parameters to end to end test

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15412

Adding  OS Parameters to  OS end to end test

Dependent Nailgun PR: https://github.com/SatelliteQE/nailgun/pull/1191

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_operatingsystem.py -k test_positive_end_to_end_os

**Comment by Gauravtalreja1** [comment]
@shubhamsg199 Can you investigate the PRT failures and update the PR?

**Comment by Gauravtalreja1** [comment]
@shubhamsg199  Could you please update this PR?

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_operatingsystem.py -k test_positive_end_to_end_os

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 9089
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_operatingsystem.py -k test_positive_end_to_end_os --external-logging
Test Result : ========== 1 passed, 42 deselected, 51 warnings in 551.00s (0:09:10) ===========
```

**Pull request merged**
