### PR TITLE
Update of BZ1177570

### PR DESCRIPTION
**Pull request by ares**
See https://bugzilla.redhat.com/show_bug.cgi?id=1177570 for more details

### CODE REVIEW

**Comment by oshtaier** [comment]
According to `flake8 .` you removed single reference to `skip_if_bug_open` decorator from the code, so `from robottelo.common.decorators import skip_if_bug_open` is redundant. Please, remove it

**Comment by oshtaier** [comment]
Please, provide `nosetests` result for that test here

**Comment by oshtaier** [comment]
Why do we remove `u'mac': host.mac`? It seems that attribute is crucial for that particular test

**Comment by Ichimonji10** [comment]
Quoting from [comment 14](https://bugzilla.redhat.com/show_bug.cgi?id=1177570#c14):

> The issue is in how the hammer is called. [...] To create the interface an extra argument must be  specified, try adding following to the hammer command
>
>    --interface type=network

OK. Let's accept the premise that the issue lies with the user, and the user is using hammer inappropriately. Given this assumption, then yes, the solution in this pull request (change how hammer is used) is correct.

But I also think that the returned error message is horridly unhelpful:

> '[ERROR 2015-03-23 11:28:34 Exception] mac value is blank!\nCould not create the host:\n  mac value is blank!\n'

In [comment 9](https://bugzilla.redhat.com/show_bug.cgi?id=1177570#c9), Tom Caspy recognizes this and proposes fixing this error message:

> The error message is indeed wrong, it should be "you must specify either compute attributes or a compute profile", will changing the error message be the right approach for fixing this issue?

@ares Can we test both cases? That is, can we test that:

* When hammer is used incorrectly, an appropriate error message is returned.
* When hammer is used correctly, an appropriate action is taken.

**Comment by ares** [comment]
> But I also think that the returned error message is horridly unhelpful:

The error message is actually correct, since we don't add any interface, no MAC is specified. I agree it's very confusing. On the other hand, suggested error message about compute attributes or compute profile is misleading. I can try to change the message to following "could not fetch MAC address, you must specify attributes for at least one compute interface"

I tried to update the tests but apparently it's more complicated than I thought, so I'm leaving this up to you after the change is merged.  `<rant>too bad test are in different lang, devs have hard time to send small patches like this...</rant>`. Anyway I hope you got the idea, in case of libvirt, MAC is fetched from compute resource so specifying mac manually is useless. Feel free to close this PR.

**Comment by sthirugn** [comment]
@sat6qe, can somebody pick up this PR and complete please?

**Comment by elyezer** [comment]
Will merge this manually.

**Comment by sthirugn** [comment]
ty @elyezer

**Comment by elyezer** [comment]
Created #2777 in order to handle the changes, took care of maintaining the @ares authorship. Will close this in favor of that.

**Pull request closed without merging**
