### PR TITLE
[6.14.z] Fix RHSSO bugs.

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11546

1) Fix setting a redirect URL to the actual Satellite
2) Fix issues setting client access to public

Test results: satellite-jenkins MR#1033

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldapauthsource.py::test_rhsso_login_using_hammer

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldapauthsource.py::test_rhsso_login_using_hammer

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldapauthsource.py::test_rhsso_login_using_hammer

**Review by pondrejk — APPROVED** [review]

**Comment by pondrejk** [comment]
prt failing with:
```
 >           raise InvalidVersion(f"Invalid version: '****version}'")
 E           packaging.version.InvalidVersion: Invalid version: 'stream'
```
which looks fairly unrelated, we may need to get some other fix in to get prt passing

**Comment by lhellebr** [comment]
Yes, I've hit that, too. I think the version of package module used returns LegacyVersion instead of throwing an exception. I didn't alter it since I think it's unrelated.

**Review by Gauravtalreja1 — APPROVED** [review]
Ack, PRT failures look related to BZ#2213582 and seem unrelated

**Pull request merged**
