### PR TITLE
Cherry-pick to 6.4 Fixes the task timeout caused in Syncplan tests

### PR DESCRIPTION
**Pull request by san7ket**

### CODE REVIEW

**Comment by san7ket** [comment]
```
++ which py.test
+ /home/jenkins/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/py.test -v --junit-xml=foreman-results.xml -m 'not stubbed' tests/foreman/api/test_syncplan.py -k _synchronize_
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /home/jenkins/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/jenkins/workspace/satellite6-standalone-automation, inifile:
plugins: wait-for-1.0.9, xdist-1.22.2, services-1.2.1, mock-1.6.3, forked-0.2, env-0.6.2
collecting ... 2018-07-17 09:26:35 - conftest - DEBUG - Collected 32 test cases

2018-07-17 09:26:35 - conftest - DEBUG - Deselected test tests.foreman.api.test_syncplan.SyncPlanProductTestCase.test_positive_remove_product

2018-07-17 09:26:35 - conftest - DEBUG - Deselected test tests.foreman.api.test_syncplan.SyncPlanProductTestCase.test_positive_repeatedly_add_remove

collected 32 items / 24 deselected

tests/foreman/api/test_syncplan.py::SyncPlanSynchronizeTestCase::test_negative_synchronize_custom_product_past_sync_date PASSED [ 12%]
tests/foreman/api/test_syncplan.py::SyncPlanSynchronizeTestCase::test_positive_synchronize_custom_product_daily_recurrence PASSED [ 25%]
tests/foreman/api/test_syncplan.py::SyncPlanSynchronizeTestCase::test_positive_synchronize_custom_product_future_sync_date PASSED [ 37%]
tests/foreman/api/test_syncplan.py::SyncPlanSynchronizeTestCase::test_positive_synchronize_custom_product_past_sync_date PASSED [ 50%]
tests/foreman/api/test_syncplan.py::SyncPlanSynchronizeTestCase::test_positive_synchronize_custom_product_weekly_recurrence PASSED [ 62%]
tests/foreman/api/test_syncplan.py::SyncPlanSynchronizeTestCase::test_positive_synchronize_custom_products_future_sync_date PASSED [ 75%]
tests/foreman/api/test_syncplan.py::SyncPlanSynchronizeTestCase::test_positive_synchronize_rh_product_future_sync_date PASSED [ 87%]
tests/foreman/api/test_syncplan.py::SyncPlanSynchronizeTestCase::test_positive_synchronize_rh_product_past_sync_date PASSED [100%]

 generated xml file: /home/jenkins/workspace/satellite6-standalone-automation/foreman-results.xml 
================== 8 passed, 24 deselected in 2528.16 seconds ==================
```

**Comment by san7ket** [comment]
```
+ /home/jenkins/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/py.test -v --junit-xml=foreman-results.xml -m 'not stubbed' tests/foreman/cli/test_syncplan.py -k _synchronize_
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /home/jenkins/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/jenkins/workspace/satellite6-standalone-automation, inifile:
plugins: wait-for-1.0.9, xdist-1.22.2, services-1.2.1, mock-1.6.3, forked-0.2, env-0.6.2
collecting ... 2018-07-17 10:19:47 - conftest - DEBUG - Collected 18 test cases

collected 18 items / 10 deselected

tests/foreman/cli/test_syncplan.py::SyncPlanTestCase::test_negative_synchronize_custom_product_past_sync_date PASSED [ 12%]
tests/foreman/cli/test_syncplan.py::SyncPlanTestCase::test_positive_synchronize_custom_product_daily_recurrence PASSED [ 25%]
tests/foreman/cli/test_syncplan.py::SyncPlanTestCase::test_positive_synchronize_custom_product_future_sync_date PASSED [ 37%]
tests/foreman/cli/test_syncplan.py::SyncPlanTestCase::test_positive_synchronize_custom_product_past_sync_date PASSED [ 50%]
tests/foreman/cli/test_syncplan.py::SyncPlanTestCase::test_positive_synchronize_custom_product_weekly_recurrence PASSED [ 62%]
tests/foreman/cli/test_syncplan.py::SyncPlanTestCase::test_positive_synchronize_custom_products_future_sync_date PASSED [ 75%]
tests/foreman/cli/test_syncplan.py::SyncPlanTestCase::test_positive_synchronize_rh_product_future_sync_date PASSED [ 87%]
tests/foreman/cli/test_syncplan.py::SyncPlanTestCase::test_positive_synchronize_rh_product_past_sync_date PASSED [100%]

 generated xml file: /home/jenkins/workspace/satellite6-standalone-automation/foreman-results.xml 
================== 8 passed, 10 deselected in 2748.75 seconds ==================
```

**Comment by san7ket** [comment]
@rplevka @pondrejk Test results added

**Comment by rplevka** [comment]
ACK

**Pull request merged**
