### PR TITLE
Updated test case docstring for API tests

### PR DESCRIPTION
**Pull request by sthirugn**

### CODE REVIEW

**Comment by sthirugn** [comment]
This needs testimony updates

**Comment by sthirugn** [comment]
There is no testimony update needed.  Testimony currently does not accept `:` in test case name so I fixed very few test cases which had that issue. All is well.

**Comment by sthirugn** [comment]
Rebased.

**Comment by elyezer** [comment]
ACK

**Comment by JacobCallahan** [comment]
ACK

**Pull request merged**
