### PR TITLE
Debug and fix failing DHCPDNS tests

### PR DESCRIPTION
**Pull request by synkd**
The tests in destructive/test_infoblox.py are failing in CI, but I am unable to reproduce the failure locally. I am temporarily adding epdb and setting it to serve near the location of the error to facilitate investigating this issue.

### CODE REVIEW

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by synkd** [comment]
Looks like the Satellite deploy workflow failed during the `satellite-change-hostname` step. [1] Trying again.

[1] https://infra-ansible-tower-01.infra.sat.rdu2.redhat.com/#/jobs/playbook/6651/output

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by synkd** [comment]
Just learned that the internal engineering Satellite instance is down. I'm guessing this is behind the workflow failure.

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by omkarkhatavkar** [comment]
https://github.com/SatelliteQE/robottelo/pull/10142 this would fix that

**Comment by synkd** [comment]
https://github.com/SatelliteQE/robottelo/pull/10142 did resolve the initial error. However, the tests are still failing. Modifying the debugger location and re-running PRT.

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by synkd** [comment]
```
2022-10-07 13:08:41 [ERROR ] [configure] Execution of '/bin/dnf -d 0 -e 1 -y install dhcp-server' returned 1: Error: Unable to find a match: dhcp-server
2022-10-07 13:08:41 [ERROR ] [configure] /Stage[main]/Dhcp/Package[dhcp-server]/ensure: change from 'purged' to 'present' failed: Execution of '/bin/dnf -d 0 -e 1 -y install dhcp-server' returned 1: Error: Unable to find a match: dhcp-server
```
My suspicion is that these tests started failing when we stopped registering Satellites to the internal engineering Satellite instance and started just copying repofiles to provide access to compose packages. Adding a `register_to_cdn` step may resolve this error.

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by synkd** [comment]
I was getting some errors from one of the compose repos on Friday, but today the addition of `target_sat.register_to_cdn()` seems to be working as expected. Running PRT one more time to validate the fix.

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Review by mshriver — APPROVED** [review]

**Pull request merged**
