### PR TITLE
Added missed string indices for string format usages

### PR DESCRIPTION
**Pull request by sthirugn**

### CODE REVIEW

**Comment by sthirugn** [comment]
@omaciel @JacobCallahan

**Comment by JacobCallahan** [comment]
Awesome, thanks! ACK

**Comment by oshtaier** [comment]
Please, explain necessity of that change

**Comment by sthirugn** [comment]
@oshtaier https://github.com/SatelliteQE/robottelo/pull/2851#discussion_r40925602

As per @JacobCallahan and @omaciel, without specifying string indices breaks compatibility with python 2.6

**Comment by omaciel** [comment]
ACK (asking for a rebase)

**Comment by sthirugn** [comment]
Rebased

**Comment by elyezer** [comment]
We do support Python 2.6? Where it is important?

**Comment by sthirugn** [comment]
@omaciel @JacobCallahan please ^

**Comment by sthirugn** [comment]
Part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
