### PR TITLE
Update component name GPGKeys to ContentCredentials

### PR DESCRIPTION
**Pull request by lpramuk**
ReportPortal job is failing as mojo page is modified and `GPG Keys` row was removed

### CODE REVIEW

**Review by rplevka — APPROVED** [review]

**Comment by mirekdlugosz** [comment]
There's already #8019 for that.

Wouldn't it be better to fix report portal tooling, so it doesn't stop when test component is not present in owners map?

**Comment by swadeley** [comment]
Hello

which should we merge first? This or https://github.com/SatelliteQE/robottelo/pull/8019 ?

I can rebase if required, or just cherry pick this commit into that https://github.com/SatelliteQE/robottelo/pull/8019 branch?

Let me know

Thank you

**Review by swadeley — APPROVED** [review]

**Comment by mirekdlugosz** [comment]
@swadeley since your PR has additional dependency, let's merge this to unblock CI and rebase #8019 to account for testimony.yaml changes.

**Comment by swadeley** [comment]
ACK

**Comment by rplevka** [comment]
@mirekdlugosz 
> Wouldn't it be better to fix report portal tooling, so it doesn't stop when test component is not present in owners map?

The patch is already in.

**Pull request merged**
