### PR TITLE
fix 10141: release can be float but needs casting to string object

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
This will fix the https://github.com/SatelliteQE/robottelo/issues/10141

### CODE REVIEW

**Comment by synkd** [comment]
I believe this issue is also responsible for errors in the `destructive/test_infoblox.py` tests, which I was debugging today:
```
11:04:48          return (
11:04:48  >           f'{settings.repos.ohsnap_repo_host}/api/releases/'
11:04:48              f'{release}{"/" + snap if snap else ""}/el{self._v_major}/{product}/repo_file'
11:04:48          )
11:04:48  E       TypeError: can only concatenate str (not "float") to str
11:04:48  
11:04:48  robottelo/host_helpers/contenthost_mixins.py:63: TypeError
```
Running PRT against that module should be a good test of this change.

**Comment by synkd** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by omkarkhatavkar** [comment]
> I believe this issue is also responsible for errors in the `destructive/test_infoblox.py` tests, which I was debugging today:
> 
> ```
> 11:04:48          return (
> 11:04:48  >           f'{settings.repos.ohsnap_repo_host}/api/releases/'
> 11:04:48              f'{release}{"/" + snap if snap else ""}/el{self._v_major}/{product}/repo_file'
> 11:04:48          )
> 11:04:48  E       TypeError: can only concatenate str (not "float") to str
> 11:04:48  
> 11:04:48  robottelo/host_helpers/contenthost_mixins.py:63: TypeError
> ```
> 
> Running PRT against that module should be a good test of this change.

it even fails at the snap, which needs to be a string object. updated with this PR now.

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_infoblox.py

**Review by synkd — APPROVED** [review]
Looking at the most recent PRT run, the tests are failing but this change enabled them to proceed past the previous error. I will continue debugging those tests, but ACK to this PR.

**Comment by omkarkhatavkar** [comment]
> Looking at the most recent PRT run, the tests are failing but this change enabled them to proceed past the previous error. I will continue debugging those tests, but ACK to this PR.

I think `settings.server.version.get("snap")` was the culprit, somehow Jenkins passed the correct version in string format but it's loading the float value. adding an extra layer of formating solves it.

**Review by pondrejk — APPROVED** [review]

**Comment by omkarkhatavkar** [comment]
added here https://github.com/SatelliteQE/robottelo/pull/10152

**Comment by omkarkhatavkar** [comment]
> added here #10152

no need to cherry-pick as support is not required.

**Pull request merged**
