### PR TITLE
Revert "Add coverage for provisioning templates cloning functionality"

### PR DESCRIPTION
**Pull request by rochacbruno**
I made a mistake merging #3558 because nailgun changes were not implemented yet.

Reverts SatelliteQE/robottelo#3558

### CODE REVIEW

**Comment by elyezer** [comment]
It could be better to try getting NailGun PR merged soon instead of reverting this and sending it back again later on.

**Comment by rochacbruno** [comment]
@elyezer: @oshtaier asked me to revert because nailgun PR was not accepted, maybe it will get more time to get it in.

**Comment by oshtaier** [comment]
@elyezer @rochacbruno need to change the code, so we can revert that one PR and create a new one. Or should I create a new one PR overwriting the old one?

**Comment by elyezer** [comment]
@oshtaier you can go ahead and send a PR for the update. We can close this and leave the other one merged.

**Comment by oshtaier** [comment]
Ok

**Comment by elyezer** [comment]
Also when making a PR blocked is better to add a [DONOTMERGE] to the title, thank will reinforce the need to wait. Some times I just look over the code and the ACK and merge if needed.

**Pull request closed without merging**
