### PR TITLE
ddt removal in ui login tests

### PR DESCRIPTION
**Pull request by sthirugn**
Test results:
```sh
----------------------------------------------------------------------
Ran 2 tests in 34.811s

OK
```

### CODE REVIEW

**Comment by oshtaier** [comment]
Don't forget to put `nosetests` statement to see what tests were executed

**Comment by oshtaier** [comment]
ACK

**Comment by sthirugn** [comment]
@oshtaier I agree with your point about mentioning the nosetests.  But the problem is that I use different runners.  Sometimes I use a UI runner in which you right click the test and click Run. (This does not use nosetests in the background).  And all it provides is the output as I mentioned above with a bunch of `locator` debug statements if the debug is turned on.  Do you have any idea of what else can be done here?

**Comment by oshtaier** [comment]
I am also using different runners, but do final testing using nosetests all the time. I am just want to make sure that you do not confuse yourself as you have huge amount of branches, PRs, runs and etc

**Comment by sthirugn** [comment]
good point, thank you.

**Comment by abalakh** [comment]
ACK, pending a rebase.

**Comment by sthirugn** [comment]
Rebased

**Comment by sthirugn** [comment]
part of https://github.com/SatelliteQE/robottelo/issues/2769

**Pull request merged**
