### PR TITLE
Added missing /api/hosts/:id/enc path on end-to-end tests

### LINKED ISSUE #4146: Add u'/api/hosts/:id/enc' path to end to end tests

### PR DESCRIPTION
**Pull request by renzon**
close #4146

### CODE REVIEW

**Comment by rochacbruno** [comment]
@renzon is it valid only for 6.3 or should we CP to 6.2?

**Comment by renzon** [comment]
@rochacbruno in fact this change was made first on 6.2.7 (#4143) because was blocking its hands off to QE team.

**Comment by rochacbruno** [comment]
@renzon but it is also applicable to 6.3? shoud it be merged in both branches?

**Comment by rochacbruno** [comment]
@omaciel I added a review request for you as you are aware of this change. 
(and you mentioned it can fail 6.3 build until we get next snap, ok to merge now, or put it on hold?)

**Comment by lpramuk** [comment]
I checked upstream and it has ```"Get ENC values of host":"/api/hosts/:id/enc"```
Lets merge to be on par with upcoming 6.3 candidate (aka Downstream Nightly) in advance

**Pull request merged**
