### PR TITLE
Update nailgun requirement to use master branch

### PR DESCRIPTION
**Pull request by mshriver**
Update all direct git requirements to specify a branch explicitly

### CODE REVIEW

**Review by JacobCallahan — APPROVED** [review]
ACK

**Review by lpramuk — APPROVED** [review]

**Review by jameerpathan111 — APPROVED** [review]
ACK. 
@mshriver we should also update https://github.com/SatelliteQE/satellite6-upgrade/blob/master/requirements.txt#L5

**Review by jyejare — APPROVED** [review]

**Comment by mirekdlugosz** [comment]
@jyejare why did you merge it, when there is ongoing discussion on satqe list, with Mike stating explicitly:

> I'll leave discussion open for another day or two

?

If there are people opposing this change, you have just unilaterally taken away their opportunity to voice their dissent and state their arguments.

**Comment by jyejare** [comment]
@mshriver @mirekdlugosz Ohh I didnt see that conversion and I also didnt see the DNM label . any comment or drafted PR.

Sorry for not looking at Email thread, but my intention was not to take away anybody's opportunity to voice.

**Comment by mshriver** [comment]
@mirekdlugosz @jyejare No harm no foul, I should have marked it draft to prevent merge. If there is any reason raised why we should continue using stable-satellite, this will be an easy change to revert.

**Comment by jyejare** [comment]
@mshriver  I ACK to use master branches since the `stable-satellite` is no more being used from DEV team , which was the main intention behind creating that branch and there were lot of back and forth for having it implemented that time.

Since DEVs have moved to apiepe we should not worry abt changing that to master here.

**Pull request merged**
