### PR TITLE
Fix per_page field for api calls

### PR DESCRIPTION
**Pull request by tpapaioa**
This PR fixes usage of the `per_page` parameter in the search API. The parameter should be a string that can be converted an integer. Many of them were instead passed as an integer value. The Satellite API then tries to convert the value to an Integer in Rails, resulting in test failures with log messages like the following:

```
2021-01-06 16:36:10 - nailgun.client - DEBUG - Making HTTP GET request to https://satellite.example.com/api/v2/permissions with options {'data': '{"per_page": 350, "search": "resource_type=\\"Katello::Product\\""}', 'auth': ('
admin', 'XXXXX'), 'verify': False, 'headers': {'content-type': 'application/json'}}, no params and no data.
2021-01-06 16:36:10 - nailgun.client - WARNING - Received HTTP 500 response: {
  "error": {"message":"undefined method `empty?' for 350:Integer"}
}
```

Some tests showing the successful test results with this fix in place:

```
$ pytest tests/foreman/api/test_repository.py -k 'test_positive_remove_contents or test_positive_resynchronize_rpm_repo or test_positive_resynchronize_puppet_repo'
[...]
collected 229 items / 226 deselected / 3 selected

tests/foreman/api/test_repository.py ...                     [100%]
[...]
=== 3 passed, 226 deselected, 43 warnings in 140.57s (0:02:20) ===

$ pytest tests/foreman/api/test_classparameters.py -k test_positive_update_parameter_type
[...]
collected 29 items / 21 deselected / 8 selected

tests/foreman/api/test_classparameters.py ........      [100%]
[...]
=== 8 passed, 21 deselected, 67 warnings in 61.13s (0:01:01) ===

$ pytest tests/foreman/api/test_templatesync.py -k 'test_positive_import_filtered_templates_from_git or test_import_filtered_templates_from_git_with_negate'
[...]
collected 23 items / 21 deselected / 2 selected

tests/foreman/api/test_templatesync.py ..     [100%]
[...]
=== 2 passed, 21 deselected, 16 warnings in 21.89s ===


$ pytest tests/foreman/api/test_templatesync.py -k test_positive_import_and_associate
[...]
collected 23 items / 22 deselected / 1 selected

tests/foreman/api/test_templatesync.py .      [100%]
[...]
=== 1 passed, 22 deselected, 22 warnings in 28.57s ===

$ pytest tests/foreman/api/test_host.py::test_positive_get_per_page
[...]
collected 1 item

tests/foreman/api/test_host.py .            [100%]
[...]
=== 1 passed, 3 warnings in 0.61s ===
```

### CODE REVIEW

**Review by jameerpathan111 — COMMENTED** [review]
@tpapaioa there can be more tests failing because of this issue. Should we fix them as well? 
for ex. `test_positive_import_filtered_templates_from_git` is also failing because of this issue.

**Comment by tpapaioa** [comment]
Done. I've updated the description to reflect the additional changes.

**Review by jameerpathan111 — APPROVED** [review]
ACK

**Review by jyejare — APPROVED** [review]
ACK

**Comment by jyejare** [comment]
@tpapaioa Thanks much for taking care of this. This was a pain from long.

**Pull request merged**
