### PR TITLE
Testing Upstream PRT DO NOT MERGE

### PR DESCRIPTION
**Pull request by Griffin-Sullivan**

### CODE REVIEW

**Comment by Griffin-Sullivan** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/sys/test_fam.py::test_prt
theforeman:
    foreman: 10126
Katello:
    katello: 10960
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6502
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/sys/test_fam.py::test_prt --external-logging
Test Result : =================== 6 warnings, 1 error in 249.67s (0:04:09) ===================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6505
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/sys/test_fam.py::test_prt --external-logging
Test Result : =================== 6 warnings, 1 error in 222.79s (0:03:42) ===================
```

**Comment by Griffin-Sullivan** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/sys/test_fam.py::test_prt
theforeman:
    foreman: 10126
Katello:
    katello: 10960
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6507
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/sys/test_fam.py::test_prt --external-logging
Test Result : =================== 6 warnings, 1 error in 218.51s (0:03:38) ===================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6525
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/sys/test_fam.py::test_prt --external-logging
Test Result : =================== 6 warnings, 1 error in 245.43s (0:04:05) ===================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6529
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/sys/test_fam.py::test_prt --external-logging
Test Result : ================== 1 passed, 9 warnings in 1703.15s (0:28:23) ==================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6574
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/sys/test_fam.py::test_prt --external-logging
Test Result : ================== 1 passed, 9 warnings in 1596.77s (0:26:36) ==================
```

**Comment by Griffin-Sullivan** [comment]
I don't know why it didn't report the result but it passed

**Comment by Griffin-Sullivan** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/sys/test_fam.py::test_prt
theforeman:
    foreman: 10126
Katello:
    katello: 10960
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 115
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/sys/test_fam.py::test_prt --external-logging
Test Result : ================== 1 passed, 9 warnings in 1841.19s (0:30:41) ==================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6607
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/sys/test_fam.py::test_prt --external-logging
Test Result : ================== 1 passed, 9 warnings in 1855.45s (0:30:55) ==================
```

**Comment by ogajduse** [comment]
Shouldn't this be a draft?

**Comment by omkarkhatavkar** [comment]
@Griffin-Sullivan Good to close this one. As we are done with testing for the upstream PRT

**Comment by Griffin-Sullivan** [comment]
sorry had this open for a demo this morning. Closing now.

**Pull request closed without merging**
