### PR TITLE
[DO NOT MERGE] packit test

### PR DESCRIPTION
**Pull request by vsedmik**
Packit test for https://github.com/Katello/katello/pull/11050

### CODE REVIEW

**Comment by vsedmik** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k export_import_redhat_cv
env:
    ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '9'
Katello:
    katello: 11050
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7551
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_satellitesync.py -k export_import_redhat_cv --external-logging
Test Result : ========== 3 passed, 31 deselected, 85 warnings in 4807.71s (1:20:07) ==========
```

**Comment by Griffin-Sullivan** [comment]
FYI you can just run the job directly now if you run build with parameters. Although this is nice to be able to link to other PRs

**Comment by vsedmik** [comment]
Closing since the upstream PR has been merged.

**Pull request closed without merging**
