### PR TITLE
Enable the live logging, so that the progress can be tracked from jen…

### PR DESCRIPTION
**Pull request by kbidarkar**
…kins.

### CODE REVIEW

**Comment by sghai** [comment]
ACK

**Comment by oshtaier** [comment]
```
  -s, --nocapture       Don't capture stdout (any stdout output will be printed immediately) [NOSE_NOCAPTURE]
```
so we will get all results right away in the logs?

**Comment by kbidarkar** [comment]
Yeah it will print the results right away to the screen( when running locally)/console log(jenkins). Also,
a) This should help us know whether automation is running, just by
looking at the console-output.
b) robottelo-${ENDPOINT}.log would also work as usual.
c) Discussed this with suresh, Og and elyezer on wednesday, and we also merged another PR in robottelo-ci for the same.

**Comment by kbidarkar** [comment]
https://github.com/SatelliteQE/robottelo-ci/pull/77

**Comment by oshtaier** [comment]
You know what you are doing:) I am just curious why that change was not present before :)

**Comment by oshtaier** [comment]
ACK

**Comment by elyezer** [comment]
@oshtaier basically that will print out all logging messages to stdout. We let nose capture it and just print for failures to not drop a bunch of text when test passes since they are not relevant when analyzing test results. The problem is when the job get stuck (UI for upstream for example) and we can't see it from jenkins console, requiring to log into the slave machine.

**Pull request merged**
