### PR TITLE
Added sleep to load repoinfo

### LINKED ISSUE #6627: Fix AssertionError for docker RepositoryTestCase
- tests:  tests/foreman/cli/test_repository.py::RepositoryTestCase::test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags    tests/foreman/cli/test_repository.py::RepositoryTestCase::test_positive_synchronize_docker_repo_set_tags_later  tests/foreman/cli/test_repository.py::RepositoryTestCase::test_positive_synchronize_docker_repo_with_tags_whitelist

- Error:
self = <tests.foreman.cli.test_repository.RepositoryTestCase testMethod=test_positive_synchronize_docker_repo_set_tags_later>

    @run_only_on('sat')
    @tier2
    def test_positive_synchronize_docker_repo_set_tags_later(self):
        """Verify that adding tags whitelist and re-syncing after
        synchronizing full repository doesn't remove content that was
        already pulled in
    
        :id: 97f2087f-6041-4242-8b7c-be53c68f46ff
    
        :expectedresults: Non-whitelisted tags are not removed
        """
        tags = 'latest'
        repo = self._make_repository({
            'content-type': 'docker',
            'docker-upstream-name': 'hello-world',
            'url': DOCKER_REGISTRY_HUB,
        })
        Repository.synchronize({'id': repo['id']})
        repo = Repository.info({'id': repo['id']})
        # Field is displayed only if there is any content
        with self.assertRaises(KeyError):
            repo['container-image-tags-filter']
>       self.assertGreaterEqual(int(repo['content-counts']['container-image-tags']), 2)
E       AssertionError: 0 not greater than or equal to 2

self = <tests.foreman.cli.test_repository.RepositoryTestCase testMethod=test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags>

    @run_only_on('sat')
    @tier2
    def test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags(self):
        """Set tags whitelist to contain both valid and invalid (non-existing)
        tags. Check if only whitelisted tags are synchronized
    
        :id: 75668da8-cc94-4d39-ade1-d3ef91edc812
    
        :expectedresults: Only whitelisted tag is synchronized
        """
        tags = ['latest', gen_string('alpha')]
        repo = self._make_repository({
            'content-type': 'docker',
            'docker-upstream-name': 'alpine',
            'url': DOCKER_REGISTRY_HUB,
            'docker-tags-whitelist': ",".join(tags),
        })
        Repository.synchronize({'id': repo['id']})
        repo = Repository.info({'id': repo['id']})
        [self.assertIn(tag, repo['container-image-tags-filter']) for tag in tags]
>       self.assertEqual(int(repo['content-counts']['container-image-tags']), 1)
E       AssertionError: 0 != 1

tests/foreman/cli/test_repository.py:1070: AssertionError

self = <tests.foreman.cli.test_repository.RepositoryTestCase testMethod=test_positive_synchronize_docker_repo_with_tags_whitelist>

    @run_only_on('sat')
    @tier2
    @upgrade
    def test_positive_synchronize_docker_repo_with_tags_whitelist(self):
        """Check if only whitelisted tags are synchronized
    
        :id: aa820c65-2de1-4b32-8890-98bd8b4320dc
    
        :expectedresults: Only whitelisted tag is synchronized
        """
        tags = 'latest'
        repo = self._make_repository({
            'content-type': 'docker',
            'docker-upstream-name': 'alpine',
            'url': DOCKER_REGISTRY_HUB,
            'docker-tags-whitelist': tags,
        })
        Repository.synchronize({'id': repo['id']})
        repo = Repository.info({'id': repo['id']})
        self.assertIn(tags, repo['container-image-tags-filter'])
>       self.assertEqual(int(repo['content-counts']['container-image-tags']), 1)
E       AssertionError: 0 != 1

tests/foreman/cli/test_repository.py:1015: AssertionError

### PR DESCRIPTION
**Pull request by vijay8451**
**- Bugzilla raised:** https://bugzilla.redhat.com/show_bug.cgi?id=1664631
**- Fixed #6627** 
**- Test result:**
++++++++++++++++++++++++++++++++++++++
(py36test) [root@vijsingh robottelo]# pytest -v tests/foreman/cli/test_repository.py -k test_positive_synchronize_docker_repo_set_tags_later
============================================================================ test session starts ============================================================================
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/vijsingh/my_projects/py36test/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/vijsingh/my_projects/ROBO/master/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-01-09 18:16:50 - conftest - DEBUG - Collected 93 test cases

2019-01-09 18:16:50 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_negative_create_non_yum_with_download_policy

2019-01-09 18:16:50 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_negative_restricted_user_cv_add_repository

2019-01-09 18:16:50 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_positive_upload_content_srpm

2019-01-09 18:16:50 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.OstreeRepositoryTestCase.test_negative_create_ostree_repo_with_checksum

2019-01-09 18:16:50 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync

2019-01-09 18:16:50 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync_publish_cv

2019-01-09 18:16:50 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync_publish_promote_cv

2019-01-09 18:16:50 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync

2019-01-09 18:16:50 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync_publish_cv

2019-01-09 18:16:50 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync_publish_promote_cv

collected 93 items / 92 deselected                                                                                                                                          

**tests/foreman/cli/test_repository.py::RepositoryTestCase::test_positive_synchronize_docker_repo_set_tags_later PASSED                                                 [100%]**

(py36test) [root@vijsingh robottelo]# pytest -v tests/foreman/cli/test_repository.py -k test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags
============================================================================ test session starts ============================================================================
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/vijsingh/my_projects/py36test/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/vijsingh/my_projects/ROBO/master/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-01-09 18:52:03 - conftest - DEBUG - Collected 93 test cases

2019-01-09 18:52:03 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_negative_create_non_yum_with_download_policy

2019-01-09 18:52:03 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_negative_restricted_user_cv_add_repository

2019-01-09 18:52:03 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_positive_upload_content_srpm

2019-01-09 18:52:03 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.OstreeRepositoryTestCase.test_negative_create_ostree_repo_with_checksum

2019-01-09 18:52:03 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync

2019-01-09 18:52:03 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync_publish_cv

2019-01-09 18:52:03 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync_publish_promote_cv

2019-01-09 18:52:03 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync

2019-01-09 18:52:03 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync_publish_cv

2019-01-09 18:52:03 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync_publish_promote_cv

collected 93 items / 92 deselected                                                                                                                                          

**tests/foreman/cli/test_repository.py::RepositoryTestCase::test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags PASSED                                    [100%]**

(py36test) [root@vijsingh robottelo]# pytest -v tests/foreman/cli/test_repository.py -k test_positive_synchronize_docker_repo_with_tags_whitelist
============================================================================ test session starts ============================================================================
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/vijsingh/my_projects/py36test/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/vijsingh/my_projects/ROBO/master/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-01-09 18:54:27 - conftest - DEBUG - Collected 93 test cases

2019-01-09 18:54:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_negative_create_non_yum_with_download_policy

2019-01-09 18:54:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_negative_restricted_user_cv_add_repository

2019-01-09 18:54:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_positive_upload_content_srpm

2019-01-09 18:54:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.OstreeRepositoryTestCase.test_negative_create_ostree_repo_with_checksum

2019-01-09 18:54:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync

2019-01-09 18:54:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync_publish_cv

2019-01-09 18:54:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync_publish_promote_cv

2019-01-09 18:54:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync

2019-01-09 18:54:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync_publish_cv

2019-01-09 18:54:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync_publish_promote_cv

collected 93 items / 92 deselected                                                                                                                                          

**tests/foreman/cli/test_repository.py::RepositoryTestCase::test_positive_synchronize_docker_repo_with_tags_whitelist PASSED                                            [100%]**

++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### CODE REVIEW

**Comment by vijay8451** [comment]
@oshtaier got it , changes are inplace now.

**Test result:**
++++++++++++++++++++++++++++++++++++++++
robottelo]# pytest -v tests/foreman/cli/test_repository.py::RepositoryTestCase::test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags
============================================================================ test session starts ============================================================================
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/vijsingh/my_projects/py36test/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/vijsingh/my_projects/ROBO/master/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-01-10 19:14:00 - conftest - DEBUG - Collected 1 test cases

collected 1 item                                                                                                                                                            

tests/foreman/cli/test_repository.py::RepositoryTestCase::test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags PASSED                                    [100%]




robottelo]# pytest -v tests/foreman/cli/test_repository.py::RepositoryTestCase::test_positive_synchronize_docker_repo_with_tags_whitelist
============================================================================ test session starts ============================================================================
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/vijsingh/my_projects/py36test/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/vijsingh/my_projects/ROBO/master/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-01-10 19:19:45 - conftest - DEBUG - Collected 1 test cases

collected 1 item                                                                                                                                                            

tests/foreman/cli/test_repository.py::RepositoryTestCase::test_positive_synchronize_docker_repo_with_tags_whitelist PASSED                                            [100%]



robottelo]# pytest -v tests/foreman/cli/test_repository.py::RepositoryTestCase::test_positive_synchronize_docker_repo_set_tags_later
============================================================================ test session starts ============================================================================
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/vijsingh/my_projects/py36test/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/vijsingh/my_projects/ROBO/master/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-01-10 19:25:24 - conftest - DEBUG - Collected 1 test cases

collected 1 item                                                                                                                                                            

tests/foreman/cli/test_repository.py::RepositoryTestCase::test_positive_synchronize_docker_repo_set_tags_later PASSED                                                 [100%]

++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by oshtaier** [comment]
Here is idea for approach to be used there:
```
def get_image_tags_count()
    repo = Repository.info({'id': repo['id']})
    count = int(repo['content-counts']['container-image-tags'])
    return count


def validated_image_tags_count()
    if bz_bug_is_open(1664631):
        wait_for(
            lambda: get_image_tags_count > 0,
            timeout=30,
            delay=2,
            logger=self.logger
        )
    return get_image_tags_count()

def test...

    Repository.synchronize({'id': repo['id']})
    self.assertIn(tags, repo['container-image-tags-filter'])
    self.assertEqual(validated_image_tags_count1)
```

That is **not** tested, but you can make it as a working scenario

**Comment by vijay8451** [comment]
@oshtaier thanks , really make sense . Changes are made now with a small modification.

**Test result:**

++++++++++++++++++++++++++++
(py36test) [root@vijsingh robottelo]# pytest -v tests/foreman/cli/test_repository.py -k test_positive_synchronize_docker_repo_with_tags_whitelist
============================================================================ test session starts ============================================================================
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/vijsingh/my_projects/py36test/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/vijsingh/my_projects/ROBO/master/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-01-14 16:28:05 - conftest - DEBUG - Collected 93 test cases

2019-01-14 16:28:05 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_negative_create_non_yum_with_download_policy

2019-01-14 16:28:05 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_negative_restricted_user_cv_add_repository

2019-01-14 16:28:05 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_positive_upload_content_srpm

2019-01-14 16:28:05 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.OstreeRepositoryTestCase.test_negative_create_ostree_repo_with_checksum

2019-01-14 16:28:05 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync

2019-01-14 16:28:05 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync_publish_cv

2019-01-14 16:28:05 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync_publish_promote_cv

2019-01-14 16:28:05 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync

2019-01-14 16:28:05 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync_publish_cv

2019-01-14 16:28:05 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync_publish_promote_cv

collected 93 items / 92 deselected                                                                                                                                          

**tests/foreman/cli/test_repository.py::RepositoryTestCase::test_positive_synchronize_docker_repo_with_tags_whitelist PASSED                                            [100%]**







(py36test) [root@vijsingh robottelo]# pytest -v tests/foreman/cli/test_repository.py -k test_positive_synchronize_docker_repo_set_tags_later
============================================================================ test session starts ============================================================================
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/vijsingh/my_projects/py36test/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/vijsingh/my_projects/ROBO/master/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-01-14 16:32:51 - conftest - DEBUG - Collected 93 test cases

2019-01-14 16:32:51 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_negative_create_non_yum_with_download_policy

2019-01-14 16:32:51 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_negative_restricted_user_cv_add_repository

2019-01-14 16:32:51 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_positive_upload_content_srpm

2019-01-14 16:32:51 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.OstreeRepositoryTestCase.test_negative_create_ostree_repo_with_checksum

2019-01-14 16:32:51 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync

2019-01-14 16:32:51 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync_publish_cv

2019-01-14 16:32:51 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync_publish_promote_cv

2019-01-14 16:32:51 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync

2019-01-14 16:32:51 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync_publish_cv

2019-01-14 16:32:51 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync_publish_promote_cv

collected 93 items / 92 deselected                                                                                                                                          

**tests/foreman/cli/test_repository.py::RepositoryTestCase::test_positive_synchronize_docker_repo_set_tags_later PASSED                                                 [100%]**




(py36test) [root@vijsingh robottelo]# pytest -v tests/foreman/cli/test_repository.py -k test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags
============================================================================ test session starts ============================================================================
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/vijsingh/my_projects/py36test/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/vijsingh/my_projects/ROBO/master/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-01-14 16:37:27 - conftest - DEBUG - Collected 93 test cases

2019-01-14 16:37:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_negative_create_non_yum_with_download_policy

2019-01-14 16:37:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_negative_restricted_user_cv_add_repository

2019-01-14 16:37:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.RepositoryTestCase.test_positive_upload_content_srpm

2019-01-14 16:37:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.OstreeRepositoryTestCase.test_negative_create_ostree_repo_with_checksum

2019-01-14 16:37:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync

2019-01-14 16:37:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync_publish_cv

2019-01-14 16:37:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.SRPMRepositoryTestCase.test_positive_sync_publish_promote_cv

2019-01-14 16:37:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync

2019-01-14 16:37:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync_publish_cv

2019-01-14 16:37:27 - conftest - DEBUG - Deselected test tests.foreman.cli.test_repository.DRPMRepositoryTestCase.test_positive_sync_publish_promote_cv

collected 93 items / 92 deselected                                                                                                                                          

**tests/foreman/cli/test_repository.py::RepositoryTestCase::test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags PASSED                                    [100%]**




++++++++++++++++++++++++++++++++++

**Comment by vijay8451** [comment]
travis is green now :)

**Comment by oshtaier** [comment]
then we need second reviewer =)

**Pull request merged**
