### PR TITLE
Fixing flaky http proxy end to end test

### PR DESCRIPTION
**Pull request by ColeHiggins2**
test_positive_end_to_end has been a very flaky test. 

This is a test PR to check to see if the test needs to have functional manifests and not module

### CODE REVIEW

**Comment by vijaysawant** [comment]
looks good to me :+1:

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_end_to_end -n 3

**Review by vsedmik — APPROVED** [review]
ACK, PRT pending

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_end_to_end

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py -k test_positive_end_to_end

**Comment by ColeHiggins2** [comment]
Closing due to fix in https://github.com/SatelliteQE/robottelo/pull/13064

**Comment by ColeHiggins2** [comment]
Closing due to fix in https://github.com/SatelliteQE/robottelo/pull/13064

**Pull request closed without merging**
