### PR TITLE
Use sAMAccountName in AD LDAP, i.e. 'domain\username'

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_user.py::TestActiveDirectoryUser::test_positive_access_entities_from_ldap_org_admin

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_user.py::TestActiveDirectoryUser::test_positive_access_entities_from_ldap_org_admin

**Review by pondrejk — COMMENTED** [review]
ack for the changes, I just wonder if there aren't more occurrences to fix. I did a search for `ad_data['ldap_user_name']` and got some hits also in  tests/foreman/cli/test_ldapauthsource.py, tests/upgrades/test_usergroup.py, pytest_fixtures/component/satellite_auth.py, so something worth double checking

**Comment by lhellebr** [comment]
sAMACountName only should be used in some contexts. I'll go through other failures later, some of the instances you pointed out might be the same issue, some not. I'll make a separate PR for those if needed.

**Review by pondrejk — APPROVED** [review]

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
