### PR TITLE
Convert remaining tests to manifester

### PR DESCRIPTION
**Pull request by synkd**
This PR converts to manifester all tests using manifests to that are not contained in the API, CLI, or UI namespaces.

### CODE REVIEW

**Comment by synkd** [comment]
`endtoend.py::TestEndToEnd::test_positive_end_to_end` is failing both locally and in CI with the same error, but Manifester is working as expected.

**Comment by synkd** [comment]
`endtoend/test_cli_endtoend.py::test_positive_cli_end_to_end` is failing, but Manifester is working as expected. Error here:
```
        # BONUS: Create a content host and associate it with promoted
        # content view and last lifecycle where it exists
        content_host_name = gen_alphanumeric()
>       content_host = Host.with_user(user['login'], user['password']).subscription_register(
            {
                'content-view-id': content_view['id'],
                'lifecycle-environment-id': lifecycle_environment['id'],
                'name': content_host_name,
                'organization-id': org['id'],
            }
        )

tests/foreman/endtoend/test_cli_endtoend.py:270: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
robottelo/cli/host.py:374: in subscription_register
    result = cls.execute(cls._construct_command(options), output_format='csv')
robottelo/cli/base.py:259: in execute
    return cls._handle_response(response, ignore_stderr=ignore_stderr)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'robottelo.cli.base.Base.with_user.<locals>.Wrapper'>, response = stdout:

stderr:
Failed to register host:
  undefined method `each' for #<Katello::ContentViewEnvironment:0x00005638def47870>

status: 70, ignore_stderr = None

    @classmethod
    def _handle_response(cls, response, ignore_stderr=None):
        """Verify ``status`` of the CLI command.
    
        Check for a non-zero return code or any stderr contents.
    
        :param response: a result object, returned by :mod:`robottelo.utils.ssh.command`.
        :param ignore_stderr: indicates whether to throw a warning in logs if
            ``stderr`` is not empty.
        :returns: contents of ``stdout``.
        :raises robottelo.cli.base.CLIReturnCodeError: If return code is
            different from zero.
        """
        if isinstance(response.stderr, tuple):
            # the current contents of response.stderr is a tuple with the following properties
            # (<len(message)>,<message>).
            # This behavior could (and maybe should) change in the near future.
            # In the meantime, we don't need it here so we just use the message itself
            response.stderr = response.stderr[1]
        if isinstance(response.stderr, bytes):
            response.stderr = response.stderr.decode()
        if response.status != 0:
            full_msg = (
                f'Command "{cls.command_base} {cls.command_sub}" '
                f'finished with status {response.status}\n'
                f'stderr contains:\n{response.stderr}'
            )
            error_data = (response.status, response.stderr, full_msg)
            if cls._db_error_regex.search(full_msg):
                raise CLIDataBaseError(*error_data)
>           raise CLIReturnCodeError(*error_data)
E           robottelo.cli.base.CLIReturnCodeError: CLIReturnCodeError(status=70, stderr="Failed to register host:\n  undefined method `each' for #<Katello::ContentViewEnvironment:0x00005638def47870>\n", msg='Command "host subscription register" finished with status 70\nstderr contains:\nFailed to register host:\n  undefined method `each\' for #<Katello::ContentViewEnvironment:0x00005638def47870>\n'
```

**Review by pondrejk — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/endtoend/ -m e2e

**Review by Gauravtalreja1 — APPROVED** [review]
ACK, PRT results look unrelated to this change

**Pull request merged**
