### PR TITLE
Fix positive recommend repos test

### PR DESCRIPTION
**Pull request by swadeley**
Trim sat version to two digits
  Bump Ansible to 2.9
  Reverse change from fdrh8 to rhae2

### CODE REVIEW

**Comment by swadeley** [comment]
robottelo]$ pytest --show-capture=no tests/foreman/ui/test_repository.py -k test_positive_recommended_repos
================================== test session starts ===============================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo, configfile: pyproject.toml
plugins: xdist-2.3.0, mock-3.6.1, ibutsu-1.16, forked-1.3.0, services-2.2.1, cov-2.12.1, reportportal-5.0.8
collected 28 items / 27 deselected / 1 selected                                                                                                                                                   

tests/foreman/ui/test_repository.py .                                                                                                                                                       [100%]

======================= 1 passed, 27 deselected, 3 warnings in 655.79s (0:10:55) ===========================

**Review by JacobCallahan — APPROVED** [review]

**Review by mshriver — APPROVED** [review]

**Comment by mshriver** [comment]
@swadeley holding off on merging because of the use of the 6.9 label an target of `master` branch. Should this go into `master` which is now targeting 6.10 testing, or should we move it to `6.9.z` target branch?

**Comment by swadeley** [comment]
> @swadeley holding off on merging because of the use of the 6.9 label an target of `master` branch. Should this go into `master` which is now targeting 6.10 testing, or should we move it to `6.9.z` target branch?

Hello @mshriver , sorry for confusion over use of 6.9 tag, I wanted to indicate I would like this merged into in master before the 6.9 branch if possible. I have removed that tag.

Thank you

**Comment by swadeley** [comment]
Hello

I cannot test this against 6.10 at this time due to an airgun issue. I will make a new PR for 6.9 branch.

**Comment by swadeley** [comment]
[cherry-pick] Fix positive recommend repos test #8709 

for the 6.9 branch

**Comment by mshriver** [comment]
If you would like to re-open this, the pr-testing pipeline can handle running this PR + and airgun PR. That way we can validate both fixes/changes at the same time against 6.10.

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
