### PR TITLE
Cherry Pick - UI tests for download policy to 6.2.z

### PR DESCRIPTION
**Pull request by rochacbruno**
- UI improvements
- Logging improvements
- Download Policy test cases

### CODE REVIEW

**Comment by rochacbruno** [comment]
Currently tests failing on 6.2.z, I am going to fix and provide results here soon.

**Comment by rochacbruno** [comment]
Depends on https://github.com/SatelliteQE/nailgun/pull/325

**Comment by rochacbruno** [comment]
All good! take a look at standalone automation build 230.

All download policy tests passed

**Comment by oshtaier** [comment]
ACK

**Comment by lpramuk** [comment]
if we are cherrypicking can we have branch in brackets at start: 
[6.2.z] (cherrypick) we need this

**Pull request merged**
