### PR TITLE
[6.11.z] Fix RHSSO multi-group test

### PR DESCRIPTION
**Pull request by vsedmik**
Manual cherry-pick of #10136.

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_user_permissions_rhsso_user_multiple_group

**Review by pondrejk — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_user_permissions_rhsso_user_multiple_group

**Comment by Gauravtalreja1** [comment]
@vsedmik Can you please check the PRT results?

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_user_permissions_rhsso_user_multiple_group

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_user_permissions_rhsso_user_multiple_group

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_user_permissions_rhsso_user_multiple_group

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_user_permissions_rhsso_user_multiple_group

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_user_permissions_rhsso_user_multiple_group

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_user_permissions_rhsso_user_multiple_group

**Comment by vsedmik** [comment]
This PRT is cursed.
Locally it passes now in 6.11.z branch (I had to add some other changes).
```
$ pytest tests/foreman/destructive/test_ldap_authentication.py::test_user_permissions_rhsso_user_multiple_group
============================================== test session starts =============================================
collected 1 item                                                                                                                                                                                                                       

tests/foreman/destructive/test_ldap_authentication.py .                                                  [100%]

================================== 1 passed, 2 warnings in 1340.02s (0:22:20) ==================================
```

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
