### PR TITLE
[6.15.z] Component Audit - VMware api e2e provisioning test

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14969

Adding VMware e2e api provisioning test.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7582
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_computeresource_vmware.py -k test_computeresource_vmware.py --external-logging --include-onprem-provisioning
Test Result : ================== 13 warnings, 8 errors in 606.46s (0:10:06) ==================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7595
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_computeresource_vmware.py --external-logging --include-onprem-provisioning
Test Result : ================== 13 warnings, 8 errors in 602.97s (0:10:02) ==================
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_computeresource_vmware.py
provisioning: true
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_computeresource_vmware.py
provisioning: true
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7688
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_computeresource_vmware.py --external-logging --include-onprem-provisioning
Test Result : ================== 13 warnings, 8 errors in 638.00s (0:10:38) ==================
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/api/test_computeresource_vmware.py
provisioning: true
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7795
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_computeresource_vmware.py --external-logging --include-onprem-provisioning
Test Result : ================= 8 passed, 416 warnings in 6305.78s (1:45:05) =================
```

**Pull request merged**
