### PR TITLE
Update HTTP Proxy e2e test cases

### PR DESCRIPTION
**Pull request by vsedmik**
### Problem Statement
During the HTTP proxy component evaluation PX/SD/QE agreed to make several changes. This PR addresses those related to the E2E tests, in particular:
- extends `test_positive_end_to_end` to sync other content type repos via HTTP proxy
- decreases CaseImportance of some 

Some other changes improve docstings - remove redundant fields and adds more information.

### Related Issues
SAT-23276

### CODE REVIEW

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5892
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py --external-logging
Test Result : = 1 failed, 7 passed, 2 deselected, 216 warnings, 2 errors in 1152.83s (0:19:12) =
```

**Comment by vsedmik** [comment]
Need #14217 for pass.

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5900
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_http_proxy.py tests/foreman/cli/test_http_proxy.py --external-logging
Test Result : ========= 10 passed, 2 deselected, 363 warnings in 2742.23s (0:45:42) ==========
```

**Review by pondrejk — APPROVED** [review]

**Review by Griffin-Sullivan — APPROVED** [review]

**Pull request merged**
