### PR TITLE
[6.12.z] Add e2e tests for Global Registration

### PR DESCRIPTION
**Pull request by Gauravtalreja1**
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/10458 and https://github.com/SatelliteQE/robottelo/pull/10404
Fixes https://github.com/SatelliteQE/robottelo/issues/10543

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
nailgun: 865
pytest: tests/foreman/api/test_registration.py::test_host_registration_end_to_end tests/foreman/cli/test_registration.py::test_host_registration_end_to_end tests/foreman/destructive/test_remoteexecution.py::test_positive_use_alternate_directory tests/foreman/cli/test_remoteexecution.py::TestAsyncSSHProviderRex tests/foreman/cli/test_remoteexecution.py::TestPullProviderRex

**Comment by Gauravtalreja1** [comment]
PRT failures for el8 api registrations are known issue and REX failures not related to the changes in this PR

**Review by adarshdubey-star — APPROVED** [review]

**Review by synkd — CHANGES_REQUESTED** [review]
Looks good overall, but can you please revert the changes to satellite_mixins.py? I explain the rationale for this request in https://github.com/SatelliteQE/robottelo/pull/10554.

**Review by synkd — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_registration.py::test_host_registration_end_to_end tests/foreman/cli/test_registration.py::test_host_registration_end_to_end tests/foreman/destructive/test_remoteexecution.py::test_positive_use_alternate_directory tests/foreman/cli/test_remoteexecution.py::TestAsyncSSHProviderRex tests/foreman/cli/test_remoteexecution.py::TestPullProviderRex

**Comment by Gauravtalreja1** [comment]
PRT failures for el8 API registrations are known issues and REX failures are not related to the changes in this PR

**Pull request merged**
