### PR TITLE
SSH provider renamed to Script

### PR DESCRIPTION
**Pull request by pondrejk**
Adjusting to terminology change in 6.12, also shifting focus to rhel8 hosts

### CODE REVIEW

**Review by latran — APPROVED** [review]
Ack.  Can you paste a few test results from the changes once we branch?

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k  test_positive_run_default_job_template_by_ip

**Review by JacobCallahan — APPROVED** [review]
@pondrejk is this ready to merge?

**Comment by pondrejk** [comment]
@latran @JacobCallahan hello, yes ready to merge. Rpr run failed on host timeout, not sure about the reason, but locally I'm getting pass:

```
pytest  tests/foreman/cli/test_remoteexecution.py -k test_positive_run_default_job_template_by_ip

================================================ test session starts ================================================

tests/foreman/cli/test_remoteexecution.py .                                                                   [100%]
```

**Pull request merged**
