### PR TITLE
Convert test hostcollection to use REX

### PR DESCRIPTION
**Pull request by swadeley**
Hello

Convert test hostcollection to use REX
and  Move setup steps to before session start

### CODE REVIEW

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_hostcollection.py

**Comment by swadeley** [comment]
Hello

this PR depends on  [Add REX support to chost and errata tests #607](https://github.com/SatelliteQE/airgun/pull/607)

**Review by jaryn — APPROVED** [review]

**Comment by swadeley** [comment]
Rebased

**Comment by swadeley** [comment]
broken after rebase, there were some upstream changes that did not work, should be fixed now

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_hostcollection.py

**Comment by swadeley** [comment]
robottelo]$ date && pytest tests/foreman/ui/test_hostcollection.py 
Tue 31 Aug 13:38:30 BST 2021
============================== test session starts ==================================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /robot-test/robottelo, configfile: pyproject.toml
plugins: xdist-2.3.0, mock-3.6.1, ibutsu-1.16, forked-1.3.0, services-2.2.1, cov-2.12.1, reportportal-5.0.8
collected 14 items                                                                                                                                                                                

tests/foreman/ui/test_hostcollection.py ..............                                                                                                                                      [100%]


=========================== 14 passed, 204 warnings in 6033.04s (1:40:33) ================================

**Review by mshriver — APPROVED** [review]

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
