### PR TITLE
Drop DDT from API tests for discovery rules

### PR DESCRIPTION
**Pull request by Ichimonji10**
Do this as part of #2769.

Test results:

    $ nosetests tests/foreman/api/test_discoveryrule.py -x
    ..........
    ----------------------------------------------------------------------
    Ran 10 tests in 30.875s

    OK

### CODE REVIEW

**Comment by sthirugn** [comment]
ACK

**Comment by omaciel** [comment]
ACK

**Comment by Ichimonji10** [comment]
Rebased.

**Comment by sghai** [comment]
:+1:

**Pull request merged**
