### PR TITLE
Component audit - Modify/Delete UI OS tests 

### PR DESCRIPTION
**Pull request by shubhamsg199**
This PR aims to refactor Operating System UI tests. There were some OS tests which are combined into one end-to-end test.

- Removing tests which are covered already in e2e

### CODE REVIEW

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_operatingsystem.py -k test_positive_end_to_end

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_operatingsystem.py

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_operatingsystem.py

**Comment by Gauravtalreja1** [comment]
@shubhamsg199 Can you apply the suggestions from https://github.com/SatelliteQE/robottelo/pull/12046 into this PR then run PRT?

**Review by ogajduse — APPROVED** [review]

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_operatingsystem.py

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_operatingsystem.py

**Pull request merged**
