### PR TITLE
Update the `Repository` entity class

### PR DESCRIPTION
**Pull request by Ichimonji10**
If a repository is being created with a content_type of "docker", then mark the
"docker_upstream_name" field as required. Also, provide a default value for
field `Repository.docker_upstream_name`.

With the changes:

    >>> from robottelo import entities
    >>> entities.Repository(content_type='docker').create_json()['docker_upstream_name']
    u'busybox'
    >>> entities.Repository(content_type='docker', docker_upstream_name='foo').create_json()['docker_upstream_name']
    u'foo'

Without the changes:

    >>> entities.Repository(content_type='docker').create_raw().text
    u'{"displayMessage":"Validation failed: Docker upstream name cannot be blank. …

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Tested against a RHEL 6.6 nightly system.

**Comment by Ichimonji10** [comment]
I will submit a PR for Ichimonji10/robottelo@eb4b9a8720de54412285408298605b7e80ad3ab2 after this PR is merged.

**Comment by omaciel** [comment]
ACK

**Comment by sthirugn** [comment]
ACK

**Comment by elyezer** [comment]
Thank you

**Pull request merged**
