### PR TITLE
Rename & fix pylintrc

### PR DESCRIPTION
**Pull request by abalakh**
Pylint is looking for `pylintrc` config file in robottelo folder, not `.pylintrc`. Renaming the file to make config actually work.

Before:
```
pylint robottelo
No config file found, using default configuration
************* Module robottelo.constants
^C
KeyboardInterrupt
```
After:
```
pylint robottelo
************* Module robottelo.constants
W: 48,20: Access to a protected member _OPERATING_SYSTEMS of a client class (protected-access)
...
^C
KeyboardInterrupt
```

### CODE REVIEW

**Comment by abalakh** [comment]
According to [docs](http://docs.pylint.org/run.html#command-line-options):
```
Pylint searches for a configuration file in the following order and uses the first one it finds:
1. `pylintrc` in the current working directory
2. If the current working directory is in a Python module, Pylint searches up the hierarchy of Python modules until it finds a `pylintrc` file.
3. This allows you to specify coding standards on a module-by-module basis. Of course, a directory is judged to be a Python module if it contains an __init__.py file.
4. The file named by environment variable `PYLINTRC`
if you have a home directory which isn’t /root:
  1. `.pylintrc` in your home directory
  2. `.config/pylintrc` in your home directory
5. `/etc/pylintrc`
```

**Comment by sthirugn** [comment]
fyi .pylintrc works for me in fedora.

**Comment by abalakh** [comment]
@sthirugn that means you have file placed in one of folders mentioned in 3), 4) or 5). And btw I've checked on fedora too :)

**Comment by omaciel** [comment]
I also had problems and had to explicitly use the flag that let's you point to the pylintrc file

**Comment by omaciel** [comment]
ACK

**Comment by sthirugn** [comment]
@abalakh yeah need to double check all folders

**Comment by sthirugn** [comment]
This is what I did to verify in my Fedora box:
```sh
# I had .pylintrc in my robottelo root
$ pylint tests/foreman/api/test_foremantask.py
<worked>

$ rm .pylintrc
rm: remove regular file ‘.pylintrc’? y

$ pylint tests/foreman/api/test_foremantask.py 
No config file found, using default configuration

$ git checkout .pylintrc
$ pylint tests/foreman/api/test_foremantask.py 
<worked>

$ mv .pylintrc pylintrc
$ pylint tests/foreman/api/test_foremantask.py 
<worked>
```
I have no idea why it picks up my `.pylintrc` although I do not have any other configuration files.  Also as I shown above `pylintrc` config also works fine for me.  So I am okay with this PR.  But I will let somebody else review and provide second ACK.

**Comment by elyezer** [comment]
ACK

**Pull request merged**
