### PR TITLE
Edit stubbed tests for Inter Satellite Sync (ISS)

### PR DESCRIPTION
**Pull request by swadeley**
Hello

Stubbed tests for ISS

Thank you

### CODE REVIEW

**Comment by mshriver** [comment]
Needs to be rebased after #8662 was merged, converting to draft.

**Comment by swadeley** [comment]
Rebased and removed two redundant stubbed tests and edited two others.

**Review by mshriver — APPROVED** [review]

**Review by latran — APPROVED** [review]
ACK

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
