### PR TITLE
Revert "Add CLI test for activation-key delete"

### PR DESCRIPTION
**Pull request by oshtaier**
Already investigated mentioned issue. Will add more coverage and remove unnecessary code duplication

### CODE REVIEW

**Comment by oshtaier** [comment]
Not sure why that commit was performed as it is similar to "test_positive_delete_activation_key_1" method, but with less coverage.
Also there are few code duplication and one wrong verification. Also ```except CLIFactoryError as err``` should not work for ```ActivationKey.delete``` as it is not a factory

**Comment by JacobCallahan** [comment]
You are absolutely right about the delete method already being in the base. I've been away from our automation way too long! Since we are on the subject of test_positive_delete_activation_key_*, I think we should address how most of them are unnecessary or need to be modified. 
delete key 1 should be modified to delete the key by its name. delete key 2 is completely unnecessary. My test can be modified to be similar to delete key 1, but still delete the key by its ID. Thoughts?

**Comment by elyezer** [comment]
Instead of merging this PR I'm in favor of using the revert github feature on #2162 and close this.

**Comment by oshtaier** [comment]
Sure. Could @elyezer help me please with that?

**Comment by oshtaier** [comment]
```
nosetests tests/foreman/cli/test_activationkey.py -m test_delete_activation_key
..........
----------------------------------------------------------------------
Ran 10 tests in 219.062s

OK
```

**Comment by elyezer** [comment]
@oshtaier on the previous PR a "Revert" button should be visible on the merged log entry, feel free to revert it. Ping me if you need any other help.

**Comment by oshtaier** [comment]
@elyezer Actually, current PR(#2163) was created once I clicked "Revert" button for #2162 PR

**Comment by elyezer** [comment]
@oshtaier got it. I have not used that yet and thought that it does not opened a PR for that.

ACK

**Comment by Ichimonji10** [comment]
ACK

**Pull request merged**
