### PR TITLE
Update the capsule and tools repo urls in the robottelo.properties

### PR DESCRIPTION
**Pull request by kbidarkar**

### CODE REVIEW

**Comment by kbidarkar** [comment]
Related to robottelo-ci PR,  https://github.com/SatelliteQE/robottelo-ci/pull/56

**Comment by sthirugn** [comment]
ACK

**Comment by sthirugn** [comment]
@elyezer looks like you need to incorporate this change in your branch :)

**Comment by elyezer** [comment]
ACK

**Pull request merged**
