### PR TITLE
Update to RHBA-2020:1455 for rhst7

### PR DESCRIPTION
**Pull request by swadeley**
[ This is Satellite 6.7 Satellite Tools Release](https://access.redhat.com/errata/RHBA-2020:1455.html)

out of date errata causes this test to fail:

tests/foreman/api/test_errata.py::ErrataTestCase::test_positive_get_diff_for_cv_envs

### CODE REVIEW

**Comment by swadeley** [comment]
robottelo]$ pytest --show-capture=no tests/foreman/api/test_errata.py::ErrataTestCase::test_positive_get_diff_for_cv_envs
==================================== test session starts ===============================================
platform linux -- Python 3.7.9, pytest-4.6.3, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo_1/robottelo
plugins: xdist-2.0.0, services-1.3.1, mock-1.10.4, forked-1.3.0, cov-2.10.1
collecting ... 2020-09-18 14:55:19 - conftest - DEBUG - Collected 1 test cases
collected 1 item                                                                                                 

tests/foreman/api/test_errata.py .                                                                         [100%]

========================== 1 passed, 2 warnings in 414.84 seconds =================================

**Review by omkarkhatavkar — APPROVED** [review]
ACK

**Review by devendra104 — APPROVED** [review]
ACK

**Review by pondrejk — APPROVED** [review]

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
