### PR TITLE
Add logging statements to sat_factory

### PR DESCRIPTION
**Pull request by mshriver**

### CODE REVIEW

**Review by rplevka — APPROVED** [review]

**Review by JacobCallahan — APPROVED** [review]

**Comment by mshriver** [comment]
Though this is approved, I mostly opened it to help with debugging in CI.  I think #9397 is a much better approach that gets the data logged.

If anything I'd keep one of the log messages I've added here and the TODO line for dynaconf issue.

**Review by ColeHiggins2 — APPROVED** [review]
ACK

**Comment by jyejare** [comment]
@mshriver As per your comment, https://github.com/SatelliteQE/robottelo/pull/9396#issuecomment-1054315624 would you like to modify the PR to remove explicit logging of a broker deployment ? And just limit this PR for comment https://github.com/rochacbruno/dynaconf/issues/690 ?

OR we can close this one ?

**Comment by ColeHiggins2** [comment]
I think the more debugging we have the better, I am merging this

**Pull request merged**
