### PR TITLE
Fixing Discovery tests

### PR DESCRIPTION
**Pull request by adarshdubey-star**
Attempting to increase the timeout for the `wait_for` function to overcome `wait_for.TimedOutError`

### CODE REVIEW

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py -k test_positive_provision_pxe_host
provisioning: true

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py
provisioning: true

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py -k test_positive_provision_pxe_host
provisioning: true
pod_resources_size: extra_extra_large

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py
provisioning: true
pod_resources_size: extra_extra_large

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_discoveredhost.py
provisioning: true
pod_resources_size: extra_extra_large

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py
provisioning: true
pod_resources_size: extra_extra_large

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_discoveredhost.py
provisioning: true
pod_resources_size: extra_extra_large

**Review by Griffin-Sullivan — APPROVED** [review]

**Pull request merged**
