### PR TITLE
sca fixes for ui organization

### PR DESCRIPTION
**Pull request by pondrejk**
### Problem Statement
updating for SCA as a default (SAT-24364)

### CODE REVIEW

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_organization.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6573
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_organization.py --external-logging
Test Result : ======= 2 failed, 5 passed, 1 skipped, 83 warnings in 1333.83s (0:22:13) =======
```

**Review by vsedmik — APPROVED** [review]
PRT failure seems unrelated to this PR, `test_positive_delete_with_manifest_lces` and `test_positive_download_debug_cert_after_refresh` passed.

**Review by synkd — APPROVED** [review]
I agree with @vsedmik, the two failing tests are failing in CI with the same errors. Looks good to me.

**Pull request merged**
