### PR TITLE
Drop redundant status checks. Update a class reference.

### PR DESCRIPTION
**Pull request by Ichimonji10**
This pull request updates Robottelo to take full advantage of NailGun version [0.6.0](https://github.com/SatelliteQE/nailgun/releases/tag/0.6.0). For full details about what changes are included in this pull request, see the individual commit messages. Summary:

* NailGun version 0.6.0 changes function `nailgun.entity_mixins._poll_task` and
  makes it raise an exception if a task finishes with any result other than
  "success". As a result, much redundant error-checking code can be dropped from
  robottelo.
* Make robottelo reference `TaskTimedOutError`, not `TaskTimeout`.

### CODE REVIEW

**Comment by elyezer** [comment]
ACK, pending email about the need of updating nailgun.

**Comment by Ichimonji10** [comment]
I've fired off an email.

**Comment by omaciel** [comment]
It looks like we have a total of 10 places where we have ``if synchronous is True and response.status_code is httplib.ACCEPTED`` in the ``entities.py`` file but only 2 of them were updated to use ``if synchronous is True and response.status_code == httplib.ACCEPTED``. Sorry if I'm missing something :/

**Comment by Ichimonji10** [comment]
> It looks like we have a total of 10 places where we have ``if synchronous is True and response.status_code is httplib.ACCEPTED`` in the ``entities.py`` file but only 2 of them were updated to use ``if synchronous is True and response.status_code == httplib.ACCEPTED``. Sorry if I'm missing something :/

No, you're not missing something. I have more work to do.

**Comment by Ichimonji10** [comment]
I've changed all occurrences of `response.status_code is` to `response.status_code ==`. Thank you for catching that, @omaciel.

**Comment by omaciel** [comment]
ACK and thank you @Ichimonji10

**Pull request merged**
