### PR TITLE
Refactor UI search

### LINKED ISSUE #2913: Improve handling of entities name that longer than 30 symbols in WebUI
At that moment we have implementation of that functionality on the search level. For example, `environment` entity
```
    def search(self, name):
        """Searches existing env from UI"""
        Navigator(self.browser).go_to_environments()
        if len(name) <= 30:
            element = self.search_entity(name, locators['env.env_name'])
        else:
            element = self.search_entity(
                name, common_locators['select_filtered_entity'])
        return element
```

Such approach applied on next entities:

* [ ] `Config Groups`
* [ ] `Environment`
* [ ] `Hardware Model`
* [ ] `Medium`
* [ ] `Operating System`
* [ ] `Registry`

For other entities, we tried to use short strings (not more than 8 symbols)

We have to think on one solution that should be applied on higher level, so we can remove huge amount of redundant code and add proper support of long string for all entities in WebUI

### LINKED ISSUE #2930: Standardize search functionality
The most essential part of current search approach is navigation to necessary page (which is actually performed to get system to some known state). For example:
```
    def search(self, name):
        """Searches existing Organization from UI."""
        Navigator(self.browser).go_to_org()
        return self.search_entity(name, locators['org.org_name'])
```
or
```
    def search(self, name):
        """Searches existing architecture from UI"""
        Navigator(self.browser).go_to_architectures()
        return self.search_entity(name, locators['arch.arch_name'])
```

In case, we want to get rid of search methods from all modules and move to exclusive `search_entity` usage, we should move mentioned navigation to some other level which is obviously not so easy task.
There are few options:
1) Move to test level
Example:
```
with Session(self.browser) as session:
    make_arch(session, name=test_data['name'], os_names=[test_data['os_name']])
    self.assertIsNotNone(self.architecture.search(test_data['name']))
```
changed on:
```
with Session(self.browser) as session:
    make_arch(session, name=test_data['name'], os_names=[test_data['os_name']])
    session.nav.go_to_architectures()
    self.assertIsNotNone(self.search_entity(test_data['name']), locators['arch.arch_name'])
```
pros:
- That is definitely most friendly approach from architecture point of view as navigation logic is separated from search logic.
- Flexible
- Easy to implement
- Reliable and error-tolerant approach

cons:
- A lot of redundant code will be introduced into the system
- Huge amount of testing and re-testing will be needed as we will touch every piece of code in webui

2) Move to base framework level
a) Some kind of correspondance table
```
'Organization' => go_to_org()
'Architecture' => go_to_architectures()
```
```
def search_entity(...):
    Navigator(self.browser).(check our table for required method)
...
```
```
with Session(self.browser) as session:
    self.assertIsNotNone(self.search_entity('Architecture', test_data['name']), locators['arch.arch_name'])
```
pros:
- One phase of re-test will be enough as we do not change tests logic
- Amount of code will be even decreased, so redundancy will not be introduced

cons:
- Mentioned table will look pretty ugly
- Not so flexible solution and not so easy to understand from user perspective

b) Pass entity class name as a part of navigation method name:
```
architecture => go_to_(class_name)()
org => go_to_(class_name)()
```
pros are the same
cons:
- Even less flexible solution as a) as we have more navigation methods than entities in application

3) Don't remove at all, but get search() to one format/look
Let's say that:
```
    def search(self, name):
        """Searches existing Organization from UI."""
        Navigator(self.browser).go_to_org()
        return self.search_entity(name, locators['org.org_name'])
```
is a standard that we should follow, so things like:
```
    def search(self, element_name):
        """Uses the search box to locate an element from a list of elements"""
        element = None
        strategy, value = locators['contentviews.key_name']
        searchbox = self.wait_until_element(common_locators['kt_search'])
        if searchbox:
            searchbox.clear()
            searchbox.send_keys(escape_search(element_name))
            self.click(common_locators['kt_search_button'])
            element = self.wait_until_element((strategy, value % element_name))
        return element
```
should be re-factored to have similar look
pros:
- Changes impact very small area of the code, so no extra efforts for testing required
- Easy to implement

cons:
- We are only improving things, but not solving initial problem.

### PR DESCRIPTION
**Pull request by elyezer**
Closes #2930
Closes #2913

### CODE REVIEW

**Comment by sthirugn** [comment]
ACK

**Comment by sthirugn** [comment]
Please merge after 
* two more ACKs atleast
* test results
* 6.1.4 signoff

**Comment by elyezer** [comment]
ACK

**Comment by oshtaier** [comment]
@omaciel @jyejare @sghai @JacobCallahan @rplevka Please check that PR if you have time

**Comment by elyezer** [comment]
Rebased

**Comment by elyezer** [comment]
Incorporated #3025 and rebased.

**Comment by lpramuk** [comment]
This approach really optimized search() function which is now faster. alex++
As a side effect some asserts have started to fail:
```
                    make_org(session, org_name=org_name)
                    self.assertIsNotNone(self.org.search(org_name))
```
Back to master branch and I didn't experienced these asserts failing. Oops?

**Comment by oshtaier** [comment]
@lpramuk I have no idea what you are talking about. We re-run all UI tests, so far no new issues, even some issues fixed

**Comment by lpramuk** [comment]
If I am the only one who has these asserts failing, I'm OK to proceed further and merge with master.

**Comment by oshtaier** [comment]
@lpramuk Sorry, but did you try to run with latest fix? I mean that was applied 40 min ago

**Comment by abalakh** [comment]
**Activation Keys**:
```
nosetests tests/foreman/ui/test_activationkey.py 
.....S..S...S..............E......
======================================================================
ERROR: @Test: Update Content View in an Activation key
----------------------------------------------------------------------
Ran 34 tests in 6802.277s

FAILED (SKIP=3, errors=1)

nosetests tests/foreman/ui/test_activationkey.py -m test_positive_update_activation_key_with_cv
.
----------------------------------------------------------------------
Ran 1 test in 234.195s

OK
```

**Content Views**:
```
nosetests tests/foreman/ui/test_contentviews.py                          
...S...ESS.S.....SSS.S.S.SS..SSSSSSSSS........
======================================================================
ERROR: @test: attempt to associate components to a non-composite
----------------------------------------------------------------------
Ran 46 tests in 3374.600s

FAILED (SKIP=20, errors=1)

nosetests tests/foreman/ui/test_contentviews.py -m test_cv_associate_components_composite_negative
.
----------------------------------------------------------------------
Ran 1 test in 60.871s

OK
```

**Discovered Hosts**:
```
nosetests tests/foreman/ui/test_discoveredhosts.py
SSSSSSSSSSSESSSSESSSSSSS
======================================================================
ERROR: @Test: Delete the selected discovered host
======================================================================
ERROR: @Test: Discover a host via proxy by setting "proxy.type=proxy" in
----------------------------------------------------------------------
Ran 24 tests in 44.194s

FAILED (SKIP=22, errors=2)
```
Both tests are failing on Jenkins too.

**Content Views**:
```
nosetests tests/foreman/ui/test_contentviews.py                          
...S...ESS.S.....SSS.S.S.SS..SSSSSSSSS........
======================================================================
ERROR: @test: attempt to associate components to a non-composite
----------------------------------------------------------------------
Ran 46 tests in 3374.600s

FAILED (SKIP=20, errors=1)

nosetests tests/foreman/ui/test_contentviews.py -m test_cv_associate_components_composite_negative
.
----------------------------------------------------------------------
Ran 1 test in 60.871s

OK
```

**Discovery Rules**:
```
nosetests tests/foreman/ui/test_discoveryrule.py
.........
----------------------------------------------------------------------
Ran 9 tests in 706.872s

OK
```

**Domains**:
```
nosetests tests/foreman/ui/test_domain.py
..........S
----------------------------------------------------------------------
Ran 11 tests in 704.911s

OK (SKIP=1)
```

**Environments**:
```
nosetests tests/foreman/ui/test_environment.py
.....
----------------------------------------------------------------------
Ran 5 tests in 313.106s

OK
```

**Hosts**:
```
nosetests tests/foreman/ui/test_host.py
E
======================================================================
ERROR: test suite for <class 'tests.foreman.ui.test_host.Host'>
----------------------------------------------------------------------
Ran 0 tests in 18.897s

FAILED (errors=1)
```

**HW Model**:
```
nosetests tests/foreman/ui/test_hw_model.py
..SS
----------------------------------------------------------------------
Ran 4 tests in 249.874s

OK (SKIP=2)
```

**Operating systems**:
```
nosetests tests/foreman/ui/test_operatingsys.py
F...F.............
======================================================================
FAIL: @Test: Create a new OS using different string types as a name
======================================================================
FAIL: @Test: OS - Create a new OS with same name and version
----------------------------------------------------------------------
Ran 18 tests in 731.493s

FAILED (failures=2)

nosetests tests/foreman/ui/test_operatingsys.py -m test_create_os_with_different_names
.
----------------------------------------------------------------------
Ran 1 test in 149.750s

OK
```

**Puppet Classes**:
```
nosetests tests/foreman/ui/test_puppet_classes.py
..
----------------------------------------------------------------------
Ran 2 tests in 419.166s

OK
```

**Registries**:
```
nosetests tests/foreman/ui/test_docker.py:DockerRegistriesTestCase
......
----------------------------------------------------------------------
Ran 6 tests in 351.310s

OK
```

**Repositories**:
```
nosetests tests/foreman/ui/test_repository.py
..............
----------------------------------------------------------------------
Ran 14 tests in 2187.168s

OK
```

**Roles**:
```
nosetests tests/foreman/ui/test_role.py
......
----------------------------------------------------------------------
Ran 6 tests in 377.708s

OK
```

**Subscriptions**:
```
nosetests tests/foreman/ui/test_subscription.py
...
----------------------------------------------------------------------
Ran 3 tests in 234.303s

OK
```

**SyncPlans**:
```
nosetests tests/foreman/ui/test_syncplan.py
.....S......
----------------------------------------------------------------------
Ran 12 tests in 1289.959s

OK (SKIP=1)
```

**Templates**:
```
nosetests tests/foreman/ui/test_template.py
............
----------------------------------------------------------------------
Ran 11 tests in 385.431s

OK
```

**Trends**:
```
nosetests tests/foreman/ui/test_trend.py
...
----------------------------------------------------------------------
Ran 3 tests in 77.275s

OK
```

**Users**:
```
nosetests tests/foreman/ui/test_user.py
.SSSSSSSSSSSSSSSS.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSS.S.....S.....SSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSS..
----------------------------------------------------------------------
Ran 100 tests in 1463.301s

OK (SKIP=80)
```

**User Groups**:
```
nosetests tests/foreman/ui/test_usergroup.py
S.SSSS
----------------------------------------------------------------------
Ran 6 tests in 74.532s

OK (SKIP=5)
```

**Smoke UI**:
```
nosetests tests/foreman/smoke/test_ui_smoke.py 
E.E.E.
======================================================================
ERROR: @Test: Perform end to end smoke tests using RH repos.
======================================================================
ERROR: @Test: Check if :data:`robottelo.constants.DEFAULT_LOC` is present
======================================================================
ERROR: @Test: Perform puppet end to end smoke tests using RH repos.
----------------------------------------------------------------------
Ran 6 tests in 755.182s

FAILED (errors=3)

nosetests tests/foreman/smoke/test_ui_smoke.py -m test_find_default_location
.
----------------------------------------------------------------------
Ran 1 test in 14.551s

OK
```
(Two others are failing on Jenkins too)

**Comment by oshtaier** [comment]
**Architecture:**
```
nosetests tests/foreman/ui/test_architecture.py
..........................................
----------------------------------------------------------------------
Ran 42 tests in 1142.958s

OK
```

**Compute Resource/Compute Profile:**
```
nosetests tests/foreman/ui/test_computeresource.py
..........
----------------------------------------------------------------------
Ran 10 tests in 816.803s

OK
```

**Config Group:**
```
nosetests tests/foreman/ui/test_config_groups.py
....
----------------------------------------------------------------------
Ran 4 tests in 516.567s

OK
```

**Docker Container:**
```
nosetests tests/foreman/ui/test_docker.py
..SS...SS...SSS............................S
----------------------------------------------------------------------
Ran 44 tests in 4594.114s

OK (SKIP=8)
```

**LDAP Auth Source**
```
nosetests tests/foreman/ui/test_ldapauthsource.py
..
----------------------------------------------------------------------
Ran 2 tests in 312.507s

OK
```

**Lifecycle Environment**
```
nosetests tests/foreman/ui/test_contentenv.py
....
----------------------------------------------------------------------
Ran 4 tests in 205.469s

OK
```

**Location:**
```
nosetests tests/foreman/ui/test_location.py
.....E.................E...
======================================================================
ERROR: @test: Add medium by using the location name and medium name
----------------------------------------------------------------------
======================================================================
ERROR: @test: Add a hostgroup and remove it by using the location name and
----------------------------------------------------------------------
Ran 27 tests in 5329.835s

FAILED (errors=2)

nosetests tests/foreman/ui/test_location.py -m test_add_medium
.
----------------------------------------------------------------------
Ran 1 test in 277.118s

OK

nosetests tests/foreman/ui/test_location.py -m test_remove_hostgroup
.
----------------------------------------------------------------------
Ran 1 test in 417.314s

OK

```

**Medium**
```
nosetests tests/foreman/ui/test_medium.py
........
----------------------------------------------------------------------
Ran 8 tests in 309.519s

OK
```

**Organization:**
```
nosetests tests/foreman/ui/test_org.py
.E.....S.....F.SF..S.E........SEE
======================================================================
ERROR: @test: Add config template by using organization name and
----------------------------------------------------------------------
======================================================================
ERROR: @test: Remove subnet by using organization name and subnet name.
----------------------------------------------------------------------
======================================================================
ERROR: @test: Create admin users then add user and remove it
----------------------------------------------------------------------
======================================================================
FAIL: @test: Create organization with valid values, then create a new one
----------------------------------------------------------------------
======================================================================
FAIL: @test: Select both organization and location.
----------------------------------------------------------------------
======================================================================
ERROR: @test: Create organization with valid values then delete it.
----------------------------------------------------------------------

Ran 33 tests in 6071.737s

FAILED (SKIP=4, errors=4, failures=2)


nosetests tests/foreman/ui/test_org.py -m test_add_configtemplate
.
----------------------------------------------------------------------
Ran 1 test in 234.411s

OK

nosetests tests/foreman/ui/test_org.py -m test_remove_subnet
.
----------------------------------------------------------------------
Ran 1 test in 265.979s

OK

nosetests tests/foreman/ui/test_org.py -m test_remove_user
.
----------------------------------------------------------------------
Ran 1 test in 204.075s

OK

nosetests tests/foreman/ui/test_org.py -m test_negative_create_with_same_name
.
----------------------------------------------------------------------
Ran 1 test in 212.421s

OK

nosetests tests/foreman/ui/test_org.py -m test_positive_create_with_both_location_and_org
.
----------------------------------------------------------------------
Ran 1 test in 200.764s

OK

nosetests tests/foreman/ui/test_org.py -m test_positive_delete
.
----------------------------------------------------------------------
Ran 1 test in 134.398s

OK
```

**Partition Table:**
```
nosetests tests/foreman/ui/test_partitiontable.py
....SS
----------------------------------------------------------------------
Ran 6 tests in 285.965s

OK (SKIP=2)
```

**Products:**
```
nosetests tests/foreman/ui/test_products.py
........
----------------------------------------------------------------------
Ran 8 tests in 1342.492s

OK
```

**Settings**
```
nosetests tests/foreman/ui/test_settings.py
SSSSSS...........S..SS.......
----------------------------------------------------------------------
Ran 29 tests in 599.211s

OK (SKIP=9)
```

**Subnet:**
```
nosetests tests/foreman/ui/test_subnet.py
....S.....
----------------------------------------------------------------------
Ran 10 tests in 522.116s

OK (SKIP=1)
```

**Comment by lpramuk** [comment]
@oshtaier  once I fetched upstream and rebased tests are OK.
Good job, Alex

**Comment by oshtaier** [comment]
@lpramuk Thanks for checking out

**Comment by oshtaier** [comment]
@omaciel @elyezer @sthirugn We are done with testing. So far, we executed all UI tests and found 6 issues (4 in general suites and 2 in smoke). That means, that we decreased number of issues significantly (of course, there is always chance of random fails, but, in general, picture is improved)

**Comment by elyezer** [comment]
Awesome! Thank you all for this incredible teamwork!

Waiting for the green light to merge this.

**Comment by elyezer** [comment]
Rebased.

**Pull request merged**
