### PR TITLE
Add test create AK with syspurpose values

### PR DESCRIPTION
**Pull request by swadeley**
Add values to cli.factory to support system purpose

Test is not working yet:

Setting service level does not work (could be product bug, TBC.)

Setting purpose-addons to '' does not work:

     >       self.assertEqual(updated_ak['system-purpose']['purpose-addons'], '')
     E       TypeError: list indices must be integers or slices, not str

    tests/foreman/cli/test_activationkey.py:1186: TypeError

### CODE REVIEW

**Comment by mirekdlugosz** [comment]
It doesn't work because robottelo CLI `entity.update()` does not return updated object, but update message as object. So your `updated_ak` in line 1186 is something like:
```
[{'message': 'Activation key updated.', 'id': '1', 'name': 'ak1'}]
```

You need to add following between update and assertions:
```python
updated_ak = ActivationKey.info({'id': new_ak['id'], 'organization-id': self.org['id']})
```

**Comment by swadeley** [comment]
@mirekdlugosz 
Thank you very much. Changes made and pushed.

Bug raised for service level failure to set:
[BZ#1789028 – hammer activation-key create fails to set service level](https://bugzilla.redhat.com/show_bug.cgi?id=1789028)

Thank you

**Comment by swadeley** [comment]
robottelo]$ pytest --show-capture=no tests/foreman/cli/test_activationkey.py -k test_create_ak_with_syspurpose_set
============================================================================ test session starts ============================================================================
platform linux -- Python 3.7.5, pytest-4.6.3, py-1.8.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo
plugins: cov-2.8.1, services-1.3.1, xdist-1.30.0, mock-1.10.4, forked-1.1.3
collecting ... 2020-01-08 17:40:34 - conftest - DEBUG - Collected 54 test cases
2020-01-08 17:40:34 - robottelo.issue_handlers.bugzilla - DEBUG - Calling Bugzilla API for {'1789028'}
collected 54 items / 53 deselected / 1 selected                                                                                                                             

tests/foreman/cli/test_activationkey.py .                                                                                                                             [100%]

==================== 1 passed, 53 deselected in 60.21 seconds ========================

**Comment by mirekdlugosz** [comment]
@swadeley is it ok to remove "DO NOT MERGE" label and "[WIP]" from title?

**Comment by swadeley** [comment]
> @swadeley is it ok to remove "DO NOT MERGE" label and "[WIP]" from title?
.
@mirekdlugosz not yet, I want to add test to add vales to an existing key and then change them.

Sorry for confusion.

**Comment by swadeley** [comment]
Hello

Based on further testing for #7584 I found that setting system-level requires a manifest, so even when the bug[1] is resolved, that part of the test will not work as written. 

I will add the manifest install steps.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1789028

**Comment by swadeley** [comment]
========================= test session starts ====================================
platform linux -- Python 3.7.5, pytest-4.6.3, py-1.8.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo
plugins: cov-2.8.1, services-1.3.1, xdist-1.30.0, mock-1.10.4, forked-1.1.3
collecting ... 2020-01-13 20:38:44 - conftest - DEBUG - Collected 54 test cases
2020-01-13 20:38:44 - robottelo.issue_handlers.bugzilla - DEBUG - Calling Bugzilla API for {'1789028'}
2020-01-13 20:38:51 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7fdcd769f390
2020-01-13 20:38:51 - robottelo.ssh - INFO - Connected to [dell-r330-12.gsslab.brq.redhat.com]
2020-01-13 20:38:51 - robottelo.ssh - INFO - >>> rpm -q satellite
2020-01-13 20:38:53 - robottelo.ssh - INFO - <<< stdout
satellite-6.7.0-4.beta.el7sat.noarch

2020-01-13 20:38:53 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7fdcd769f390
2020-01-13 20:38:53 - robottelo.host_info - DEBUG - Host Satellite version: 6.7
2020-01-13 20:38:53 - robottelo.helpers - DEBUG - Generated file bz_cache.json with BZ collect data
collected 54 items / 53 deselected / 1 selected                                                                                                                             

tests/foreman/cli/test_activationkey.py .                                                                                                                             [100%]

==================== 1 passed, 53 deselected in 50.89 seconds ========================

**Comment by swadeley** [comment]
@mirekdlugosz 

I have changed the test to use the class org and added the fake manifest step to the class setup. That way other tests can use cls org if they need fake manifest (I will make a note to review the other tests in tests/foreman/cli/test_activationkey.py for this).

I decided to make separate git commits for ease of working on the two branches (for this pull request and  #7584).

**Comment by swadeley** [comment]
Thank you all

**Pull request merged**
