### PR TITLE
Update paths for API end to end tests

### PR DESCRIPTION
**Pull request by elyezer**
Depends on https://github.com/SatelliteQE/nailgun/pull/296 in order to pass 100% of the API end to end tests.

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK pending one test run

**Comment by elyezer** [comment]
``` 
$ py.test tests/foreman/endtoend/test_api_endtoend.py -k test_positive_get_links
========================== test session starts ===========================
platform linux -- Python 3.4.3, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/elyezer/code/robottelo, inifile: 
plugins: xdist-1.14, cov-2.2.1
collected 7 items 

tests/foreman/endtoend/test_api_endtoend.py .

=========== 6 tests deselected by '-ktest_positive_get_links' ============
================= 1 passed, 6 deselected in 3.47 seconds =================
```

**Comment by oshtaier** [comment]
ACK

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
