### PR TITLE
Add test demonstrating User → Role associations

### PR DESCRIPTION
**Pull request by Ichimonji10**
Users can be associated with roles via the API. Unfortunately, the API docs
don't make mention of this. BZ 1216239 outlines this shortcoming, and this PR
provides proof positive that users can be associated with roles via the API.
Test results against an upstream system:

    $ nosetests tests/foreman/api/test_user.py -m _with_role
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 4.558s

    OK

This test depends on the "role" field being added to the User entity. See
SatelliteQE/nailgun#57.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
I've marked this PR as [DO NOT MERGE] because the "role" field has not yet been added to the "User" entity class. The above test results demonstrates what will happen if you install SatelliteQE/nailgun@02ca8bdc8dadd8078f52af98ec089f02380a4342. I've submitted this PR anyway, because otherwise I may forget about it. This PR should be re-opened when NailGun 0.13.0 is released.

**Comment by jyejare** [comment]
APT.

**Comment by Ichimonji10** [comment]
Depends on #2219.

**Comment by elyezer** [comment]
#2219 is merged, ACK pending rebase.

**Comment by Ichimonji10** [comment]
Rebased.

**Pull request merged**
