### PR TITLE
Automation coverage for bz-2117760 & 1829266

### PR DESCRIPTION
**Pull request by latran**
Automation for incremental update coverage for https://bugzilla.redhat.com/show_bug.cgi?id=2117760 and https://bugzilla.redhat.com/show_bug.cgi?id=1829266

### CODE REVIEW

**Comment by latran** [comment]
@synkd Time can be gather by prepending the `time` command to the `incremental-update` command in `hammer`, but I have yet to figure out how to implement that yet.

As far as benchmark goes, there's no concrete answer so I'm going to get a benchmark for dev with a few sample rhel repos based on their suggestion for pulp3.

Finally this is quite a time consuming test case coverage so it's still a work in progress.  Thanks for bringing this up as it does contain considerations I haven't thought of and now I can move forward with some prelim testing :)

**Comment by Gauravtalreja1** [comment]
@jameerpathan111 As you own ContentViews now, would you like this PR assigned to you?

**Comment by omkarkhatavkar** [comment]
Can one of the admins verify this patch?

**Comment by jameerpathan111** [comment]
@Gauravtalreja1 I am not planning to work on this.

**Comment by Gauravtalreja1** [comment]
@jameerpathan111 Thanks for responding, 

@vsedmik As Team Phoenix owns ContentViews, would you like this PR assigned to you/someone?

**Review by jyejare — CHANGES_REQUESTED** [review]
Missing Branch labels in this PR to auto-cherrypick!

**Comment by JacobCallahan** [comment]
@damoore044 is this something that you can pick up?

**Comment by damoore044** [comment]
@JacobCallahan will take a look at this soon

**Pull request closed without merging**
