### PR TITLE
[6.14.z] global registration with nested hostgroup

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13617

### Problem Statement
Applying the component evaluation feedback to cover 1955421

### Solution
Adding a nested hostgroup to the global registration test to check the values are populated correctly

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_registration.py -k global_registration_form_populate
airgun: 1226

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5872
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py -k global_registration_form_populate --external-logging
Test Result : =========== 1 failed, 12 deselected, 2 warnings in 764.44s (0:12:44) ===========
```

**Comment by pondrejk** [comment]
this needs https://github.com/SatelliteQE/airgun/pull/1266 to be merged and cherry-picked

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_registration.py -k global_registration_form_populate

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5899
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py -k global_registration_form_populate --external-logging
Test Result : =========== 1 failed, 12 deselected, 3 warnings in 776.48s (0:12:56) ===========
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_registration.py -k global_registration_form_populate

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5937
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py -k global_registration_form_populate --external-logging
Test Result : =========== 1 failed, 12 deselected, 3 warnings in 778.68s (0:12:58) ===========
```

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_registration.py -k global_registration_form_populate

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5990
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py -k global_registration_form_populate --external-logging
Test Result : =========== 1 failed, 12 deselected, 3 warnings in 806.46s (0:13:26) ===========
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_registration.py -k global_registration_form_populate

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6126
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py -k global_registration_form_populate --external-logging
Test Result : =========== 1 failed, 12 deselected, 3 warnings in 866.55s (0:14:26) ===========
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_registration.py -k global_registration_form_populate
airgun: 1293

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6185
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py -k global_registration_form_populate --external-logging
Test Result : =========== 1 failed, 12 deselected, 2 warnings in 838.61s (0:13:58) ===========
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_registration.py -k global_registration_form_populate

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6816
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py -k global_registration_form_populate --external-logging
Test Result : ========== 1 failed, 12 deselected, 22 warnings in 761.91s (0:12:41) ===========
```

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_registration.py -k global_registration_form_populate

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6824
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py -k global_registration_form_populate --external-logging
Test Result : ========== 1 failed, 12 deselected, 22 warnings in 735.19s (0:12:15) ===========
```

**Pull request closed without merging**
