### PR TITLE
[6.15.z] added scap constant

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14921

### Problem Statement
with recent changes in oscap related fixtures, the lack of the rhel9 variant in constants causes key error

### Solution
added an item into constants

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap.py -k  test_postive_create_scap_policy_with_valid_name[cjk]

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6749
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_oscap.py -k  test_postive_create_scap_policy_with_valid_name[cjk] --external-logging
Test Result : =========== 70 deselected, 78 warnings, 1 error in 673.43s (0:11:13) ===========
```

**Comment by Gauravtalreja1** [comment]
@pondrejk PRT failing with other KeyError now, could you check and add that to constants as well?
```
        scap_profile_id = [
            profile['id']
            for profile in scap_info.scap_content_profiles
>           if OSCAP_PROFILE[settings.oscap.profile] in profile['title']
        ][0]
E       KeyError: 'security8'

pytest_fixtures/component/oscap.py:42: KeyError
```

**Comment by pondrejk** [comment]
hello, turns out https://github.com/SatelliteQE/robottelo/pull/14716 should have been cherrypicked, with that in, this should pass too, moving to draft meanwhile

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap.py -k test_postive_create_scap_policy_with_valid_name[cjk]

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_oscap.py -k test_postive_create_scap_policy_with_valid_name[cjk]

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6819
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_oscap.py -k test_postive_create_scap_policy_with_valid_name[cjk] --external-logging
Test Result : =========== 70 deselected, 78 warnings, 1 error in 784.11s (0:13:04) ===========
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6823
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_oscap.py -k test_postive_create_scap_policy_with_valid_name[cjk] --external-logging
Test Result : ========== 1 passed, 70 deselected, 79 warnings in 741.88s (0:12:21) ===========
```

**Pull request merged**
