### PR TITLE
[needs cherrypick to 6.2.2] updated hammer command tree

### PR DESCRIPTION
**Pull request by rplevka**
tested on `6.2.2`
```
+ /home/jenkins/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/py.test -v --junit-xml=foreman-results.xml -m 'not stubbed' tests/foreman/cli/test_hammer.py -k test_positive_all_options
============================= test session starts ==============================
platform linux2 -- Python 2.7.10, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /home/jenkins/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/python2.7
cachedir: .cache
rootdir: /home/jenkins/workspace/satellite6-standalone-automation, inifile: 
plugins: xdist-1.15.0
collecting ... collected 1 items

tests/foreman/cli/test_hammer.py::HammerCommandsTestCase::test_positive_all_options PASSED

 generated xml file: /home/jenkins/workspace/satellite6-standalone-automation/foreman-results.xml 
========================= 1 passed in 1341.64 seconds ==========================
+ exit 0
Deleting 2 temporary files
Recording test results

Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: SUCCESS

```

### CODE REVIEW

**Comment by rplevka** [comment]
this has the ambition to address the long-term failing test:
img

**Comment by omaciel** [comment]
ACK

**Comment by omaciel** [comment]
@rplevka can you link to the other PR that cherry-picks this into 6.2.z?

**Comment by JacobCallahan** [comment]
ACK

**Comment by rplevka** [comment]
https://github.com/SatelliteQE/robottelo/pull/3810

**Comment by lpramuk** [comment]
Anyway this is not cherrypicking. This is committing same stuff twice...

**Pull request merged**
