### PR TITLE
pytest conversion for auth cli tests

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
```
/home/okhatavk/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --path /home/okhatavk/okhatavk/Satellite/robottelo/tests/foreman/cli/test_auth.py
Launching py.test with arguments /home/okhatavk/okhatavk/Satellite/robottelo/tests/foreman/cli/test_auth.py in /home/okhatavk/Satellite/robottelo

============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/okhatavk/okhatavk/Satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, cov-2.10.1, xdist-2.2.1, reportportal-5.0.8, mock-3.5.1, forked-1.3.0, ibutsu-1.14.1, picked-0.4.6collected 9 items

../../okhatavk/Satellite/robottelo/tests/foreman/cli/test_auth.py  [ 66%]                                                                      [100%]

======================== 9 passed in 625.36s (0:10:25) =========================
```

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -k  tests/foreman/cli/test_auth.py

**Review by JacobCallahan — APPROVED** [review]

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -k tests/foreman/cli/test_auth.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_auth.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_auth.py

**Review by jameerpathan111 — APPROVED** [review]
LGTM

**Pull request merged**
