### PR TITLE
[6.15.z] Add test coverage for BZ:2238952 and BZ:2025523

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15205

### Problem Statement
Missing coverage for BZ:2238952 and BZ:2268544, where we verified Customize host button works to provision a discovered host with a few customizations.

### Solution
Add test coverage for BZ:2238952 and BZ:2268544, to verify functionality of discovery provisioning with Customize host button with a few customizations, and also covering BZ:2025523 where we've validated the assigned Ansible roles to a HostGroup gets auto executed when host is provisioned.
Also, verifying new test and modifying existing test to validate if provisioning is sucessfull on new host UI instead of old UI

### Related Issues
https://github.com/SatelliteQE/airgun/pull/1397

### CODE REVIEW

**Comment by Satellite-QE** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_discoveredhost.py -k test_positive_custom_provision_pxe_host
provisioning: true
deploy_rhel_version: '9'
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Gauravtalreja1** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_discoveredhost.py -k test_positive_custom_provision_pxe_host
provisioning: true
env:
     BROKER_SSH_BACKEND: hussh
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7446
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_discoveredhost.py -k test_positive_custom_provision_pxe_host --external-logging --include-onprem-provisioning
Test Result : ========== 2 failed, 7 deselected, 173 warnings in 4531.92s (1:15:31) ==========
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7453
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_discoveredhost.py -k test_positive_custom_provision_pxe_host --external-logging --include-onprem-provisioning
Test Result : ========== 2 failed, 7 deselected, 228 warnings in 5617.91s (1:33:37) ==========
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7456
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_discoveredhost.py -k test_positive_custom_provision_pxe_host --external-logging --include-onprem-provisioning
Test Result : ========== 2 failed, 7 deselected, 266 warnings in 6459.28s (1:47:39) ==========
```

**Comment by Gauravtalreja1** [comment]
PRT is expected to fail here due to hussh issue with discovery tests, we can merge this PR and handle the failure in separately with other discovery tests

**Review by shubhamsg199 — APPROVED** [review]
Ack

**Pull request merged**
