### PR TITLE
Add certs.yaml.template

### PR DESCRIPTION
**Pull request by swadeley**
From certs section of robottelo.properties file

### CODE REVIEW

**Comment by swadeley** [comment]
Hello

Test depends on this PR: https://github.com/SatelliteQE/robottelo/pull/8496

```
robottelo]$ pytest  --show-capture=no tests/foreman/sys/test_katello_certs_check.py 
============================== test session starts =================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo_1/robottelo, configfile: pyproject.toml
plugins: forked-1.3.0, services-2.2.1, cov-2.11.1, mock-3.5.1, ibutsu-1.14.1, reportportal-5.0.8, xdist-2.2.1
collected 14 items / 6 deselected / 8 selected                                                                                                                                                    

tests/foreman/sys/test_katello_certs_check.py ....F...                                                                                                                                      [100%]

====================================== FAILURES ===============================================
____________________________________________________________________ TestKatelloCertsCheck.test_positive_update_katello_certs _____________________________________________________________________

                )
E               robottelo.ssh.SSHCommandTimeoutError: ssh command: satellite-installer --scenario satellite --certs-reset 
E                did not respond in the predefined time (timeout=500)

robottelo/ssh.py:413: SSHCommandTimeoutError

```

timeout is not related to these changes.

https://github.com/SatelliteQE/robottelo/pull/8496#issuecomment-816500443

**Review by ColeHiggins2 — COMMENTED** [review]
Since this is a yaml file, Shouldnt we get rid of the equals sign and replace them with a colon? ex. ```CERT_FILE: ```

**Comment by swadeley** [comment]
@ColeHiggins2 I have fixed that now, thank you.

**Review by mshriver — APPROVED** [review]

**Comment by swadeley** [comment]
Thanks to all

**Pull request merged**
