### PR TITLE
[6.3] FIX CLI  test_lifecycleenvironment

### PR DESCRIPTION
**Pull request by ldjebran**
```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ pytest -v -n 8 tests/foreman/cli/test_lifecycleenvironment.py
==================================================================== test session starts =====================================================================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.20.0, services-1.2.1, mock-1.6.2, forked-0.2, cov-2.5.1
[gw0] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw1] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw2] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw3] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw4] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw5] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw6] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw7] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw0] Python 2.7.13 (default, Feb  1 2017, 15:29:46)  -- [GCC 4.8.4]
[gw5] Python 2.7.13 (default, Feb  1 2017, 15:29:46)  -- [GCC 4.8.4]
[gw7] Python 2.7.13 (default, Feb  1 2017, 15:29:46)  -- [GCC 4.8.4]
[gw6] Python 2.7.13 (default, Feb  1 2017, 15:29:46)  -- [GCC 4.8.4]  
[gw2] Python 2.7.13 (default, Feb  1 2017, 15:29:46)  -- [GCC 4.8.4]     
[gw4] Python 2.7.13 (default, Feb  1 2017, 15:29:46)  -- [GCC 4.8.4]      
[gw1] Python 2.7.13 (default, Feb  1 2017, 15:29:46)  -- [GCC 4.8.4]           
[gw3] Python 2.7.13 (default, Feb  1 2017, 15:29:46)  -- [GCC 4.8.4]              
gw0 [13] / gw1 [13] / gw2 [13] / gw3 [13] / gw4 [13] / gw5 [13] / gw6 [13] / gw7 [13]
scheduling tests via LoadScheduling

tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_create_with_name <- robottelo/decorators/__init__.py 
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_create_with_label <- robottelo/decorators/__init__.py 
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_update_description <- robottelo/decorators/__init__.py 
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_create_with_organization_name <- robottelo/decorators/__init__.py 
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_delete_by_id <- robottelo/decorators/__init__.py 
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_create_with_organization_label <- robottelo/decorators/__init__.py 
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_update_name <- robottelo/decorators/__init__.py 
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_create_with_description <- robottelo/decorators/__init__.py 
[gw2] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_create_with_organization_name <- robottelo/decorators/__init__.py 
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentPaginationTestCase::test_positive_list_with_pagination <- robottelo/decorators/__init__.py 
[gw3] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_create_with_organization_label <- robottelo/decorators/__init__.py 
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentPaginationTestCase::test_positive_list_all_with_per_page <- robottelo/decorators/__init__.py 
[gw5] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_create_with_label <- robottelo/decorators/__init__.py 
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_verify_bugzilla_1077333 <- robottelo/decorators/__init__.py 
[gw5] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_verify_bugzilla_1077333 <- robottelo/decorators/__init__.py 
[gw7] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_create_with_name <- robottelo/decorators/__init__.py 
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_verify_bugzilla_1077386 <- robottelo/decorators/__init__.py 
[gw1] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_create_with_description <- robottelo/decorators/__init__.py 
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positve_list_paths <- robottelo/decorators/__init__.py 
[gw4] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_update_name <- robottelo/decorators/__init__.py 
[gw0] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_update_description <- robottelo/decorators/__init__.py 
[gw7] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_verify_bugzilla_1077386 <- robottelo/decorators/__init__.py 
[gw1] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positve_list_paths <- robottelo/decorators/__init__.py 
[gw6] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_delete_by_id <- robottelo/decorators/__init__.py 
[gw3] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentPaginationTestCase::test_positive_list_all_with_per_page <- robottelo/decorators/__init__.py 
[gw2] PASSED tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentPaginationTestCase::test_positive_list_with_pagination <- robottelo/decorators/__init__.py 

================================================================ 13 passed in 307.57 seconds =================================================================
```

### CODE REVIEW

**Comment by abalakh** [comment]
Could you please describe what was the root cause of failures? Previous approach was definitely worse, but at the first glance *theoretically* it had to work in a similar manner.

**Comment by oshtaier** [comment]
And is it okay to have only one org instead having per each case? According to your test results - seems fine

**Comment by abalakh** [comment]
@oshtaier it wasn't one per test, but one per module, like in proposed solution. Frankly I'm not sure what's the difference, maybe it acts differently for multiple threads. Waiting for @ldjebran thoughts :)

**Comment by ldjebran** [comment]
@abalakh @oshtaier 
The tests failed with
```
AssertionError: u'eXtncg' != u'NtODu9' - eXtncg + NtODu9
```
seems when pytest spawn the processes the org was there, some confusion happened here with class and instance attributes after spawn:
so the fix consist of initiating the class parameters in class method and not in the instance one, 
so the org is initiated always with the setupClass.

For me also this is a bizare thing happened also, but we have not waist time investigating on what gone  wrong with a wrong code :).

**Comment by abalakh** [comment]
Still not sure whether the root cause was found and whether proposed solution will fix it, but previous approach was worse in any case, so let's update it and hope it will resolve the failure.

**Pull request merged**
