### PR TITLE
Added sauceclient so that pass/fail status is known to saucelabs

### PR DESCRIPTION
**Pull request by kbidarkar**
Fixes the issue #4957

### CODE REVIEW

**Comment by kbidarkar** [comment]
@rochacbruno , wondering if we should move `sauceclient` from `requirements-optional.txt` to `requirements.txt`. What do you think ?

**Comment by kbidarkar** [comment]
I mean to say, probably remove it from requirements-optional.txt file.

**Comment by abalakh** [comment]
I would rather nack such change. For local runs there's no need in `sauceclient` and most of us won't use it as we don't use saucelabs. If some lib is optional, not needed for tests execution and its absence introduces no issues for generic workflow - then it should be placed to `requirements-optional`. Our CI boxes should be updated to install `sauceclient` from `requirements-optional` instead.

**Comment by kbidarkar** [comment]
Ok, I agree, let me make this part of the `robottelo-ci` project then, will move `sauceclient` to `requirements-optional`, but would also ensure `sauceclient` would get installed separately after requriements.txt is installed. 

Let me file an issue in robottelo-ci

**Comment by kbidarkar** [comment]
Something like this,

```
pip install -r requirements.txt sauceclient
```

**Pull request merged**
