### PR TITLE
fixed tests and moved the ui steps to api steps

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
#### PR_Description:

Location create works okay, but the search has the issues over the UI. Hence moved that assertion on API level. Fixed some tests were using task.read_all() when there is no tasks. Instead that call moved to another UI call.  These steps are to not actual part of test but the supporting part that user logged in successful and able to access the entities.

I required to remove the OPEN_LDAP parameter as there underneath environment still not updated yet. I review that environment and then update the parameter. For now it is not required to have that and fail the test.

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: robottelo
pytest: -k ' test_positive_delete_external_roles or test_positive_update_external_user_roles or test_email_of_the_user_should_be_copied or test_verify_group_permissions' tests/foreman/api/test_syncplan.py tests/foreman/ui/test_ldap_authentication.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ldap_authentication.py -k  'test_positive_delete_external_roles or test_positive_update_external_user_roles or test_email_of_the_user_should_be_copied or test_verify_group_permissions'

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ldap_authentication.py -k 'test_positive_delete_external_roles or test_positive_update_external_user_roles or test_email_of_the_user_should_be_copied or test_verify_group_permissions'

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ldap_authentication.py -k 'test_positive_delete_external_roles or test_positive_update_external_user_roles or test_email_of_the_user_should_be_copied or test_verify_group_permissions'

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -m 'not destructive' tests/foreman/ui/test_ldap_authentication.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -m 'not destructive' tests/foreman/ui/test_ldap_authentication.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -m 'not destructive' tests/foreman/ui/test_ldap_authentication.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -m 'not destructive' tests/foreman/ui/test_ldap_authentication.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -m 'not destructive' tests/foreman/ui/test_ldap_authentication.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -k 'test_positive_login_user_no_roles' tests/foreman/ui/test_ldap_authentication.py
airgun: 617

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -m 'not destructive' tests/foreman/ui/test_ldap_authentication.py
airgun: 617

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -m 'not destructive' tests/foreman/ui/test_ldap_authentication.py
airgun: 617

**Comment by omkarkhatavkar** [comment]
Ignore the previous results, As I was able to fix most of them at PRT JOB 294.

**Review by mshriver — APPROVED** [review]

**Comment by mshriver** [comment]
trigger: test-robottelo
pytest: -m 'not destructive' tests/foreman/ui/test_ldap_authentication.py

**Comment by mshriver** [comment]
re-testing, we lost the OCP pod.

**Pull request merged**
