### PR TITLE
Add a new test for password reset to user-specified password

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/destructive/test_auth.py::test_positive_password_reset_chosen

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 5714
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_auth.py::test_positive_password_reset_chosen
Test Result : ================= 1 passed, 11 warnings in 1412.01s (0:23:32) ==================
```

**Comment by rmynar** [comment]
ACK.
I just see this is currently labeled to be cherrypicked only into 6.15.z. What about older versions?

**Review by rmynar — APPROVED** [review]

**Comment by lhellebr** [comment]
With 6.16 on its way, I just didn't think it's worth the hassle to backport it further

**Review by ogajduse — APPROVED** [review]

**Comment by ogajduse** [comment]
No need for T2 ACK. Merging.

**Pull request merged**
