### PR TITLE
Fix two host test cases

### PR DESCRIPTION
**Pull request by odovzhenko**
Particular fix for #5675 

test_positive_remove_parameter_non_admin_user is failing due to #5371
test_positive_check_permissions_affect_create_procedure is failing due to presence of `<div style="" class="select2-drop-mask" id="select2-drop-mask"></div>` element that present after second change of Host form and blocks working with elements related to dropdown.
```
(sat-6.3.0) odovz@bueno:~/projects/robottelo$ py.test -v tests/foreman/ui/test_host.py::HostTestCase::test_positive_remove_parameter_non_admin_user tests/foreman/ui/test_host.py::HostTestCase::test_positive_check_permissions_affect_create_procedure
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.12, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/odovz/venv/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/odovz/projects/robottelo, inifile:
plugins: xdist-1.20.1, services-1.2.1, mock-1.6.3, forked-0.2, cov-2.5.1
collected 2 items                                                                                                                                                                                           
2017-12-12 18:25:57 - conftest - DEBUG - BZ deselect is disabled in settings


tests/foreman/ui/test_host.py::HostTestCase::test_positive_remove_parameter_non_admin_user PASSED
tests/foreman/ui/test_host.py::HostTestCase::test_positive_check_permissions_affect_create_procedure PASSED

======================================================================================== 2 passed in 522.09 seconds ========================================================================================
```

### CODE REVIEW

**Comment by abalakh** [comment]
How does that `select2-drop-mask` element looks like (if it's visible)? Is it possible to hide it more natural way (clicking some 'X', closing dropdown, whatever)?

**Comment by odovzhenko** [comment]
select2-drop-mask

This div appears on second action with dropdown element and block tests from any action with drop-down related elements, like arrow to close it.
We can get rid of it by refresh, but in this case we lost data filled previously (host group), and in this case we can't assign correct value for lce and cv.

**Comment by ldjebran** [comment]
Create a function in ui/base

```python
from selenium.webdriver.common.keys import Keys

class Base(object):
    """Base class for UI"""

    def perform_action_send_escape_key(self):
        """Send escape key to browser"""
        ActionChains(self.browser).send_keys(Keys.ESCAPE).perform()
        self.wait_for_ajax()
```
in the test

```python
               ...
                with self.assertRaises(UINoSuchElementError):
                    session.hosts.assign_value(
                        entity['locator'], entity['unexpected_entity'].name)
                session.hosts.perform_action_send_escape_key()
                session.hosts.assign_value(
                    entity['locator'], entity['expected_entity'].name)

```
This should work for sure

**Comment by abalakh** [comment]
Well, if that div reacts on Esc key - that's definitely better option. @odovzhenko could you please investigate?

**Comment by odovzhenko** [comment]
This workaround works as well.
```
(sat-6.3.0) odovz@bueno:~/projects/robottelo$ py.test -v tests/foreman/ui/test_role.py::CannedRoleTestCases::test_positive_create_overridable_filter
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.12, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/odovz/venv/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/odovz/projects/robottelo, inifile:
plugins: xdist-1.20.1, services-1.2.1, mock-1.6.3, forked-0.2, cov-2.5.1
collected 1 item                                                                                                                                                                                            
2017-12-14 16:48:40 - conftest - DEBUG - BZ deselect is disabled in settings


tests/foreman/ui/test_role.py::CannedRoleTestCases::test_positive_create_overridable_filter PASSED

======================================================================================== 1 passed in 184.89 seconds ========================================================================================
```

**Pull request merged**
