### PR TITLE
[6.15.z] Cherrypick of FixesForEndeavour

### PR DESCRIPTION
**Pull request by LadislavVasina1**
Cherrypick of https://github.com/SatelliteQE/robottelo/pull/14512

### CODE REVIEW

**Comment by LadislavVasina1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_jobinvocation.py -k 'test_rex_through_host_details'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6195
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_jobinvocation.py -k test_rex_through_host_details --external-logging
Test Result : =========== 1 passed, 4 deselected, 4 warnings in 1093.68s (0:18:13) ===========
```

**Comment by LadislavVasina1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_remoteexecution.py -k 'test_positive_run_job_template_multiple_hosts_by_ip'

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6197
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_remoteexecution.py -k test_positive_run_job_template_multiple_hosts_by_ip --external-logging
Test Result : ========== 1 passed, 15 deselected, 5 warnings in 1143.68s (0:19:03) ===========
```

**Review by lhellebr — APPROVED** [review]

**Review by pondrejk — APPROVED** [review]

**Pull request merged**
