### PR TITLE
Fixeding repo sync

### PR DESCRIPTION
**Pull request by latran**
Report portal failure test case.  Removing unnecessary timeout check and just using regular repo sync

### CODE REVIEW

**Comment by latran** [comment]
Test Result:
```
$ pytest tests/foreman/ui/test_contentview.py::test_positive_delete_with_kickstart_repo_and_host_group
2019-10-02 20:13:01 - conftest - DEBUG - Registering custom pytest_configure

2019-10-02 20:13:01 - conftest - DEBUG - Fetching BZs to deselect...

2019-10-02 20:13:09 - conftest - DEBUG - Deselected tests reason: BZ resolution ['1156555', '1147100', '1217635', '1230902', '1310422', '1311113', '1199150', '1214312', '1278917', '1475443', '1610309', '1414821', '1226425', '1204686']

2019-10-02 20:13:09 - conftest - DEBUG - Deselected tests reason: missing version flag ['1156555', '1581628', '1147100', '1625783', '1489322', '1217635', '1682940', '1230902', '1310422', '1378442', '1311113', '1194476', '1199150', '1214312', '1278917', '1475443', '1610309', '1740790', '1436209', '1716429', '1226425', '1204686', '1701118', '1701132', '1321543', '1743271']

2019-10-02 20:13:09 - conftest - DEBUG - Deselected tests reason: sat-backlog ['1156555', '1581628', '1147100', '1625783', '1489322', '1217635', '1682940', '1230902', '1310422', '1311113', '1194476', '1199150', '1214312', '1278917', '1475443', '1610309', '1740790', '1436209', '1716429', '1226425', '1204686', '1701118', '1701132', '1321543', '1743271']

============== test session starts ======================
platform linux -- Python 3.6.6, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/ltran/Projects/robottelo
plugins: services-1.3.1, mock-1.10.4
collecting ... 2019-10-02 20:13:09 - conftest - DEBUG - Collected 1 test cases

collected 1 item                                                                                                                                                                                                                                                           

tests/foreman/ui/test_contentview.py .                                                                                                                                                                                                                               [100%]

================ warnings summary =======================
tests/foreman/ui/test_contentview.py::test_positive_delete_with_kickstart_repo_and_host_group
  /home/ltran/Projects/myvenv/lib64/python3.6/site-packages/anytree/resolver.py:209: DeprecationWarning: Flags not at the start of the expression 'tbody\\Z(?ms)'
    Resolver._match_cache[pat] = re_pat = re.compile(res)

tests/foreman/ui/test_contentview.py::test_positive_delete_with_kickstart_repo_and_host_group
  /home/ltran/Projects/myvenv/lib64/python3.6/site-packages/anytree/resolver.py:209: DeprecationWarning: Flags not at the start of the expression 'tr\\Z(?ms)'
    Resolver._match_cache[pat] = re_pat = re.compile(res)

tests/foreman/ui/test_contentview.py::test_positive_delete_with_kickstart_repo_and_host_group
  /home/ltran/Projects/myvenv/lib64/python3.6/site-packages/anytree/resolver.py:209: DeprecationWarning: Flags not at the start of the expression '.*\\Z(?ms)'
    Resolver._match_cache[pat] = re_pat = re.compile(res)

tests/foreman/ui/test_contentview.py::test_positive_delete_with_kickstart_repo_and_host_group
  /home/ltran/Projects/myvenv/lib64/python3.6/site-packages/anytree/resolver.py:209: DeprecationWarning: Flags not at the start of the expression 'tr.*\\Z(?ms)'
    Resolver._match_cache[pat] = re_pat = re.compile(res)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========= 1 passed, 4 warnings in 406.34 seconds ==============
```

**Comment by mirekdlugosz** [comment]
Out of curiosity - how does removing wrapper help here?
It basically calls the function with new value of `nailgun.entity_mixins.TASK_TIMEOUT`. This new value is set to 3600 seconds, which is way more than enough for test to complete. Sync should complete before new timeout value becomes a problem.

If this fails with wrapper, but succeeds without wrapper, I would say we need to take closer look at this wrapper, as it might cause some false-positives in our tests.

**Comment by latran** [comment]
@mirekdlugosz It fails with wrapper and passes without wrapper.  I'll take a closer look into this issue and report back on my findings.

**Comment by latran** [comment]
@mirekdlugosz Found the issue.  Check your email thread on the problem.  I will delete this branch or update this branch after getting a response.

**Comment by latran** [comment]
RHEL7 has latest version and should be used instead of RHEL6.

Result from Stand alone jenkins job run:
```
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-4.6.3, py-1.8.0, pluggy-0.13.0 -- /home/[*******]/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/[*******]/workspace/satellite6-standalone-automation
plugins: xdist-1.25.0, services-1.3.1, forked-1.0.2, mock-1.10.4, env-0.6.2
collecting ... 2019-10-08 14:12:43 - conftest - DEBUG - Collected 1 test cases

collected 1 item

tests/foreman/ui/test_contentview.py::test_positive_delete_with_kickstart_repo_and_host_group PASSED [100%]

- generated xml file: /home/[*******]/workspace/satellite6-standalone-automation/foreman-results.xml -
========================= 1 passed in 2004.71 seconds ==========================
```

**Comment by latran** [comment]
@rplevka If no one has any complaint, then it would be good to include in 6.5.z.

**Pull request merged**
