### PR TITLE
Remove use of SATELLITE_VERSION env var

### PR DESCRIPTION
**Pull request by mshriver**
Read settings.robottelo.satellite_version instead

### CODE REVIEW

**Comment by mshriver** [comment]
trigger: test-robottelo
pytest: -m build_sanity

**Comment by mshriver** [comment]
trigger: test-robottelo

**Comment by mshriver** [comment]
trigger: test-robottelo

**Review by JacobCallahan — APPROVED** [review]

**Review by lpramuk — APPROVED** [review]

**Comment by mshriver** [comment]
trigger: test-robottelo

**Pull request merged**
