### PR TITLE
[qe_test-coverage] - Install modular errata using katello-agent bugzilla 1713417

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
## PR Description

- Install modular errata using katello-agent
- Added as qe coverage for https://bugzilla.redhat.com/show_bug.cgi?id=1713417

## Test Result 
```
Testing started at 6:44 PM ...
/home/okhatavk/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_contenthost.py::test_install_modular_errata
Launching py.test with arguments test_contenthost.py::test_install_modular_errata in /home/okhatavk/Satellite/robottelo/tests/foreman/ui

============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-4.6.3, py-1.8.1, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/okhatavk/Satellite/robottelo
plugins: forked-1.1.3, xdist-1.31.0, cov-2.8.1, mock-1.10.4, services-1.3.12020-08-28 13:14:09 - conftest - DEBUG - Collected 1 test cases
collected 1 item

test_contenthost.py                                                     [100%]

=============================== warnings summary ===============================
```

## Dependant PR 
https://github.com/SatelliteQE/airgun/pull/510

### CODE REVIEW

**Review by mirekdlugosz — APPROVED** [review]
ACK

At this point, it might make sense to parametrize this test - have separate run for installing through dnf, separate for rex and separate for katello-agent. Obviously this is not something to do in this PR, just something to consider.

**Review by devendra104 — APPROVED** [review]
left one minor suggestion.

**Comment by mirekdlugosz** [comment]
@omkarkhatavkar with latest push, travis is broken (black reformats one place to be in single line). Please fix.

**Review by pondrejk — APPROVED** [review]
ack, but test result would be nice

**Comment by omkarkhatavkar** [comment]
> ack, but test result would be nice
Please take a look https://github.com/SatelliteQE/robottelo/pull/7947#issue-472501386 comment

**Comment by omkarkhatavkar** [comment]
@pondrejk, @mirekdlugosz and @devendra104 Please have look on the Airgun PR as this PR is dependent on that too.

**Comment by JacobCallahan** [comment]
@pondrejk @mirekdlugosz @devendra104 any update on @omkarkhatavkar's request?

**Pull request merged**
