### PR TITLE
RHEL_RELEASE works, RHEL_VERSION seems to be incorrect

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by mshriver** [comment]
https://github.com/SatelliteQE/robottelo/blob/master/robottelo/hosts.py#L69 

You've gotta up date the references if you're going to change these field names. I think it should be updated to be consistent.

**Comment by lhellebr** [comment]
I think I don't understand what you're saying. The template file says RHEL_VERSION but actually, RHEL_RELEASE is used, RHEL_VERSION is ignored and even our automation config contains RHEL_RELEASE: https://gitlab.sat.engineering.redhat.com/satelliteqe/satelliteqe-jenkins/-/blob/master/openshift/conf/server.yaml#L16

I thought this was just a mistake in the template file, is there more to it?

**Comment by mshriver** [comment]
@lhellebr have you verified this behavior on `master` or z-stream branches recently? 

https://github.com/SatelliteQE/robottelo/pull/9322/files
https://github.com/SatelliteQE/robottelo/pull/9321
https://github.com/SatelliteQE/robottelo/pull/9304

#9304 addressed this behavior, making it more consistent and updating the configs for CI.

**Comment by lhellebr** [comment]
Yes, that's why I think this slould be closed. The issue was resolved other way before this got merged.

**Pull request closed without merging**
