### PR TITLE
Fixed invalid test names in few cli tests

### PR DESCRIPTION
**Pull request by sthirugn**
```py
# nosetests tests/foreman/cli/test_capsule.py
SSSSSSSSS
----------------------------------------------------------------------
Ran 9 tests in 0.003s

OK (SKIP=9)

# nosetests tests/foreman/cli/test_capsule_installer.py
SSSSSSS
----------------------------------------------------------------------
Ran 7 tests in 0.003s

OK (SKIP=7)

# nosetests tests/foreman/ui/test_capsule.py
SSSS
----------------------------------------------------------------------
Ran 4 tests in 0.003s

OK (SKIP=4)
```

### CODE REVIEW

**Comment by sthirugn** [comment]
Note: Please merge after #3078

**Comment by oshtaier** [comment]
ACK

**Comment by elyezer** [comment]
ACK, merging since #3078 is merged.

**Comment by elyezer** [comment]
Karma given.

**Comment by omaciel** [comment]
@sthirugn thank you for taking care of this :)

**Pull request merged**
