### PR TITLE
Adding stubbed tests for RPM content

### PR DESCRIPTION
**Pull request by swadeley**
Hello

some stubbed tests related to Pulp3 RPM content

### CODE REVIEW

**Comment by swadeley** [comment]
rebased

**Review by mshriver — APPROVED** [review]

**Review by JacobCallahan — CHANGES_REQUESTED** [review]
All of these test names are very long. Can you shorten them up?

**Comment by swadeley** [comment]
> All of these test names are very long. Can you shorten them up?

@JacobCallahan I have shortened them.

**Review by JacobCallahan — APPROVED** [review]

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
