### PR TITLE
Quick Fix: joining 2 AKs for registeration

### PR DESCRIPTION
**Pull request by jyejare**
Fixing AK Tests for @ColeHiggins2 failing with error:
```
TypeError: join() takes exactly one argument (2 given)
```

### CODE REVIEW

**Comment by jyejare** [comment]
trigger: robottelo
pytest: tests/foreman/ui/test_activationkey.py -k test_positive_add_multiple_aks_to_system

**Comment by jyejare** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_activationkey.py -k test_positive_add_multiple_aks_to_system

**Comment by jyejare** [comment]
@ColeHiggins2 Please check if this is an actual product issue on 6.10 and 7.0 !

**Review by swadeley — APPROVED** [review]
ACK

**Comment by jyejare** [comment]
@ColeHiggins2 @swadeley Since th test is failing in PRT , I will late @ColeHiggins2 look into it before merge if thats real failure and fix in automation if needed! Making it a draft PR now !

**Comment by ColeHiggins2** [comment]
@jyejare Looks like I am getting an error on the last assertion on 6.10.2 and 7.0

assert ak['content_hosts']['table'][0]['Name'] == rhel6_contenthost.hostname  

'This activation key is not associated with any content hosts.'

**Comment by jyejare** [comment]
@ColeHiggins2  Is this the bug or the procedures to assign multiple AKs have changed ?

Try testing it manually !

**Comment by swadeley** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_activationkey.py -k test_positive_add_multiple_aks_to_system

**Pull request merged**
