### PR TITLE
bz1784254

### PR DESCRIPTION
**Pull request by lhellebr**
Close-loop bz1784254

### CODE REVIEW

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py::TestRemoteExecution::test_recurring_with_unreachable_host

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py::TestRemoteExecution::test_recurring_with_unreachable_host

**Comment by lhellebr** [comment]
Errors on teardown are unrelated: https://redhat-internal.slack.com/archives/C04NYN8MBGU/p1703161093990639

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py::TestRemoteExecution::test_recurring_with_unreachable_host

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py::TestRemoteExecution::test_recurring_with_unreachable_host

**Review by pondrejk — APPROVED** [review]

**Review by rplevka — APPROVED** [review]

**Review by ogajduse — APPROVED** [review]

**Pull request merged**
