### PR TITLE
Drop `robottelo.api.base`

### LINKED ISSUE #1789: Drop `robottelo.api.base`
Module `robottelo.api.base` is a wrapper around the `requests` library. However, the wrapper is a bit of a kludge, and it has been dropped in favor of `robottelo.api.client` (which is itself being dropped in favor of `nailgun.client`). This code does not appear to be used anywhere, and if any code is still using it, that code should be brought up to date.

### PR DESCRIPTION
**Pull request by Ichimonji10**
Fix #1789:

> Module `robottelo.api.base` is a wrapper around the `requests` library.
> However, the wrapper is a bit of a kludge, and it has been dropped in favor of
> `robottelo.api.client` (which is itself being dropped in favor of
> `nailgun.client`). This code does not appear to be used anywhere, and if any
> code is still using it, that code should be brought up to date.

This change appears to be sane. `make docs` produces no new warnings, `git grep
'import.*base'` returns no matches, and `git grep 'robottelo\.api'` returns no
relevant matches.

### CODE REVIEW

**Comment by JacobCallahan** [comment]
have you tried running any tests? not a blocker since I agree that it shouldn't impact anything. Just being cautious..

ACK

**Comment by Ichimonji10** [comment]
@JacobCallahan, here's the result of running some randomly chosen CLI tests:

    $ nosetests tests/foreman/cli/test_repository.py
    ......SS............................SSSSSS.............SSSS.....SS.
    ----------------------------------------------------------------------
    Ran 67 tests in 647.405s
    
    OK (SKIP=14)

I chose CLI tests b/c that hunk of code has been around for much longer than the API tests, and is therefore more likely to be affected by `robottelo.api.base`.

**Comment by JacobCallahan** [comment]
thanks!

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
