### PR TITLE
Made ssh.get_connection public

### LINKED ISSUE #3693: Make ssh._get_connection public
Once it can be used with the already public function execute_command, it should be public as well:

```console
with ssh._get_connection(..) as connection:
    ssh.execute_command('cp /orign /destiny', connection)
    ssh.execute_command('chmod 0777 /destiny', connection)
    ssh.execute_command("echo 'foo' > /destiny/bar")
```

### PR DESCRIPTION
**Pull request by renzon**
closes #3693

### CODE REVIEW

**Comment by oshtaier** [comment]
please resolve:
Warning, treated as error:
/home/travis/build/SatelliteQE/robottelo/robottelo/ssh.py:docstring of robottelo.ssh.get_connection:None: WARNING: py:obj reference target not found: paramiko.SSHClient

**Comment by renzon** [comment]
@oshtaier done. Interesting note that sphinks scan only public functions. I didn't change docstring on first PR.

**Comment by rochacbruno** [comment]
ACK

**Comment by sghai** [comment]
ACK.. Looks good.

**Pull request merged**
