### PR TITLE
Add log-related tasks to Makefile.

### PR DESCRIPTION
**Pull request by omaciel**
Backporting Makefile rules that gathers log files from automation.

### CODE REVIEW

**Comment by abalakh** [comment]
ACK pending travis fix

**Comment by oshtaier** [comment]
ACK pending travis

**Comment by omaciel** [comment]
Thanks @abalakh @oshtaier I just fixed the `flake8` issue and will wait for `Travis` but fixing `make docs` may require more time :/ I need to remember if this was caused by changes to `paramiko`.

**Comment by omaciel** [comment]
@abalakh thank you!!!

**Comment by abalakh** [comment]
thank *you* :)

**Comment by omaciel** [comment]
@abalakh @oshtaier if you're wondering why I needed this, see our Jenkins jobs:

* /view/Satellite6.1/job/automation-6.1-tier1-rhel6/
* /view/Satellite6.1/job/automation-6.1-tier1-rhel7/

Hopefully these will finish running successfully now :)

**Pull request merged**
