### PR TITLE
[DO NOT MERGE] Added @skip_if_bug_open decorators for org tests

### PR DESCRIPTION
**Pull request by tkolhar**
please review it
thanks 
Tests covered  : 
1. test_bugzilla_1079587_1___name_utf8
2. test_bugzilla_1076568_3
3. test_negative_create_3
4. test_positive_create_5_1
5. test_positive_delete_1
6. test_positive_delete_2_1
7. test_positive_delete_3_1
8. test_positive_update_1

### CODE REVIEW

**Comment by Ichimonji10** [comment]
I cannot verify [BZ 1184729](https://bugzilla.redhat.com/show_bug.cgi?id=1184729).

**Comment by Ichimonji10** [comment]
See [this comment](https://bugzilla.redhat.com/show_bug.cgi?id=1184729#c4) for more information.

**Comment by tkolhar** [comment]
added specimen test results :
https://gist.github.com/tkolhar/57d837e186bf0ab370a2

please review it 
thanks

**Comment by Ichimonji10** [comment]
@tkolhar, using the API in CLI tests is often good to do, as the API is typically faster. However, I think module `tests.foreman.cli.test_org` should stick to using CLI tools for creating organizations. As a result, this change doesn't make sense:

    - new_obj = make_org(test_data)
    + new_obj = entities.Organization().create()

I've looked over your gist, and I'm happy to see that the four tests you ran all passed. :smiley: However, a quick look at Jenkins shows that `test_positive_delete_2` is currently passing, so I'm not sure what is being proved here. :confused: Is that test failing when run from your local machine? It is true that four of the CLI tests for organizations are failing. However, they appear to be failing due to issues with our own code base, not due to any bugs on the server.

NACK

**Comment by Ichimonji10** [comment]
Please do ping me on IRC if you have any questions. I'll help out if I can.

**Pull request closed without merging**
