### PR TITLE
Fix e2e bulk update test failure

### PR DESCRIPTION
**Pull request by spusateri**
This PR fixes an error that would appear when asserting against the uri, due to the equals sign `=` not being encoded properly. To fix this, I parsed the uri components individually using `urlparse()` and used `urlencode()` to properly format the assertion rather than hard coding it and running into potential similar errors in the future

### CODE REVIEW

**Comment by spusateri** [comment]
trigger: robottelo
pytest: tests/foreman/ui/test_contenthost.py -k test_positive_end_to_end_bulk_update

**Comment by spusateri** [comment]
For some reason I accidentally applied some cherry picked commits when rebasing, will resolve that shortly

**Comment by spusateri** [comment]
I had to remove `urlencode` for the search query because the response returned by satellite is not fully encoded, which would cause the test to fail. I am open to suggestions on how to handle the partial encoding, but for now I think it would be sufficient just to hard code the `%3D` required to get the test to pass

**Comment by spusateri** [comment]
Although this leaves me wondering what change in Satellite would have caused this singular `=` sign to be encoded, while other `=` in the URI are not.

**Review by mshriver — APPROVED** [review]

**Pull request merged**
