### PR TITLE
Removing the direct Airgun imports from robottelo

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
### Problem Statement

- Remove the Airgun Imports from the Robottelo and Use `target_sat.ui_session` or `module_target_sat.ui`

### Solution

- UI tests are updated to use the modified "target_sat" or "module_target_sat" for efficient management of multiple browser sessions.
- The streamlined UI tests function correctly and manage browser sessions effectively.
- Remove the nailgun entities from the UI code considering the Airgun Imports (some more PR needs to be added remove this as not wanted to do everything in single PR)

### CODE REVIEW

**Review by JacobCallahan — APPROVED** [review]

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -n 2 tests/foreman/ui/test_settings.py
pod_resources_size: extra_large

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -n 2 tests/foreman/ui/test_settings.py
pod_resources_size: extra_large

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -n 2 tests/foreman/ui/test_settings.py
pod_resources_size: extra_large

**Comment by omkarkhatavkar** [comment]
```
PRT Result : 
4918/testReport/
```
Failures are not related to this PR.

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ldap_authentication.test_positive_update_external_roles
pod_resources_size: extra_large

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ldap_authentication -k test_positive_delete_external_roles
pod_resources_size: extra_large

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ldap_authentication.py -k test_positive_delete_external_roles
pod_resources_size: extra_large

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ldap_authentication.py -k test_positive_delete_external_roles
pod_resources_size: extra_large

**Comment by omkarkhatavkar** [comment]
@SatelliteQE/airgun-tier-1-reviewers, @SatelliteQE/airgun-tier-2-reviewers can we get the review to merge this soon?

**Review by sambible — APPROVED** [review]

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ldap_authentication.py -k test_positive_delete_external_roles
pod_resources_size: extra_large

**Pull request merged**
