### PR TITLE
Finish test module renaming

### LINKED ISSUE #3102: Naming convention for test modules and test case class names
Since we are coming up with a naming convention for tests on #3083, we should do the same for test modules and test case class names.

Initial proposal is:

For test modules, they should start with `test_`, followed by the entity name on singular and entity name words separated by `_`. It also should not abbreviate the entity name. Examples:

* test_architecture
* test_content_view
* test_content_view_version
* test_organization

For test case class names, they should end with the suffix `TestCase` and for classes named after the entity they should have the entity name on singular CamelCases. Entities names should not be abbreviated. Example:

* OrganizationTestCase
* ContentViewTestCase
* ContentViewVersionTestCase
* NonEntityRelatedTestCase

PS.: All test cases classes must inherit from `robottelo.test.TestCase` or one of its subclasses like `APITestCase`, `CLITestCase` and `UITestCase`.

### PR DESCRIPTION
**Pull request by elyezer**
Closes #3102

### CODE REVIEW

**Comment by sthirugn** [comment]
please update test_config_template.py in api/cli to test_template.py

**Comment by omaciel** [comment]
@sthirugn you want that other change to be included with this PR as well?

ACK here

**Comment by sthirugn** [comment]
@omaciel yes @elyezer wanted to do that change in this pr

**Comment by sthirugn** [comment]
APT

**Pull request merged**
