### PR TITLE
[6.11.z] UI Utils module depreciation and new ui_factory module

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12225

- Depreciating UI Utils module, removed UI utils file and package!
- Introduced new `ui_factory` attribute to satellite class, returns the UIFactory class object containing all the UI Factory methods.
So now this could be used as `target_sat.ui_factory.ui_method()`
-   Impacted test modules changed to use ui_factory methods.

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_reporttemplates.py -k test_positive_generate_registered_hosts_report

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_reporttemplates.py -k test_positive_generate_registered_hosts_report

**Comment by Gauravtalreja1** [comment]
@jyejare we're not supposed to cherrypick anything to this branch. PRT is failing with checks, so are you going to work on this PR?

**Comment by jyejare** [comment]
@Gauravtalreja1 Yeah! I mean we have cli and API factory changes made in 6.11 and I dont want to miss just ui factory changes. Will fix and update !

**Comment by devendra104** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py

**Comment by jyejare** [comment]
@Gauravtalreja1 The required changes are updated to fix the CI checks tests collection and PRT is ran. PRT failures are not related to the change made in this PR !

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
