### PR TITLE
os fixtures updated for rhel9

### PR DESCRIPTION
**Pull request by pondrejk**
### Problem Statement
default os was not found on rhel9 backend sat

### Solution
extended search

### CODE REVIEW

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: pytest tests/foreman/api/test_architecture.py -k  test_positive_CRUD

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_architecture.py -k test_positive_CRUD

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6675
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_architecture.py -k test_positive_CRUD --external-logging
Test Result : ========== 1 passed, 14 deselected, 23 warnings in 777.19s (0:12:57) ===========
```

**Comment by jameerpathan111** [comment]
@pondrejk, @Gauravtalreja1 has already raised https://github.com/SatelliteQE/robottelo/pull/14851 to fix this issue.

**Review by ColeHiggins2 — APPROVED** [review]

**Comment by ColeHiggins2** [comment]
Robottelo runner and code quality pass. ACK if not a duplicate

**Pull request closed without merging**
