### PR TITLE
[6.12.z] Add coverage for BZ#2173756

### PR DESCRIPTION
**Pull request by vsedmik**
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13202

Closes https://github.com/SatelliteQE/robottelo/issues/13838

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k consume

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/cli/test_satellitesync.py -k consume

**Comment by ogajduse** [comment]
PRT seems to be failing due to #11783 not being backported to 6.12.z.

**Comment by vsedmik** [comment]
Since no `6.12.z` release is planned it makes no sense to backport this test - it would never be run. Closing for that reason.

**Pull request closed without merging**
