### PR TITLE
[6.15.z] - remove the all nailgun imports from UI folder

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
Problem Statement

We are using the direct imports from the nailgun rather than directly using from target_sat
Solution

Direct Imports Removed: We've cleaned up our codebase by eliminating direct imports from the Nailgun package.

Using target_sat, module_target_sat, class_target_sat: Modified the API calls and using the target_sat.api. pattern for all API calls.

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/ -m e2e

**Comment by pondrejk** [comment]
@omkarkhatavkar since https://github.com/SatelliteQE/robottelo/pull/13809 got merged some time ago, I wonder if you could check the stream results for the modified tests so that we are sure it didn't break anything

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6102
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/ -m e2e --external-logging
Test Result : = 2 failed, 24 passed, 802 deselected, 1137 warnings, 16 errors in 8228.45s (2:17:08) =
```

**Comment by omkarkhatavkar** [comment]
@pondrejk PRT result looks good, just 2 failures not related to PR

**Comment by pondrejk** [comment]
> @pondrejk PRT result looks good, just 2 failures not related to PR

Yes, but most of the tests changed by this PR are not marked as e2e, right? So that PRT run doesn't fully cover the changes...

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/

**Review by lhellebr — APPROVED** [review]
Code-wise LGTM but I agree with Peter it would be nice to check whether this has broken something in stream automation.

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6206
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/ --external-logging
Test Result : = 223 failed, 450 passed, 23 skipped, 57 deselected, 13064 warnings, 96 errors in 93861.05s (1 day, 2:04:21) =
```

**Comment by omkarkhatavkar** [comment]
> Build Number: 6206
> Build Status: UNSTABLE
> PRT Comment: pytest tests/foreman/ui/ --external-logging
> Test Result : = 223 failed, 450 passed, 23 skipped, 57 deselected, 13064 warnings, 96 errors in 93861.05s (1 day, 2:04:21) =

image

@pondrejk @lhellebr what you say? 237 failures which more than what ever I run.

**Comment by Gauravtalreja1** [comment]
@omkarkhatavkar Could you rebase and update this PR?
I think new 4 failures introduced with this PR should also be part of master as original PR is merged, so we can get this cherrypicks merged now, and you/component-owner can fix those with cherrypick here?

**Comment by omkarkhatavkar** [comment]
@Gauravtalreja1 @jyejare Rebase Done !

**Comment by jyejare** [comment]
@omkarkhatavkar Does this now also includes the cherrypicks of those 14 failures ? if yes, @Gauravtalreja1 could you please verify those are present and provide Ack/NAack/Merge .

**Comment by omkarkhatavkar** [comment]
> @omkarkhatavkar Does this now also includes the cherrypicks of those 14 failures 

I don't know what are those 14 failures though. It is rebased to cherry-pick branched for sure.

**Comment by jyejare** [comment]
@omkarkhatavkar Cool. @Gauravtalreja1 please verify and we should merge all of these cherrypicks !

**Comment by pondrejk** [comment]
@omkarkhatavkar @Gauravtalreja1 @jyejare well 14 failures is not a small number + who knows what the errors are about. Finding out what these are is the tough work this cp brings about. So I'm not in favor of merging these without having the needed fixes ready. 

I suggest listing out the components that were affected by this refactor, then going to the RP history view for each of them and do the comparison between 6.15 and stream run. If the comparison shows some difference for ui tests in the component, review those and see if they are caused by https://github.com/SatelliteQE/robottelo/pull/13809. With that, we will have clarity on what we need to fix, if anything

**Comment by omkarkhatavkar** [comment]
@pondrejk, I've reviewed some of the tests, and it appears that these failures are not directly related to the changes introduced in PR #13809. It seems that several PRs in between have also encountered similar issues. Reviewing each failure individually and determining its relation to #13809 would be a time-consuming and challenging task for single person.

Given that the changes have already been merged into the master/stream branch, it would be more efficient to address them post-merge, particularly when backporting to 6.15.z. Holding back this merge solely for the purpose of refactoring in a cherry-pick branch seems unnecessary.

**Comment by pondrejk** [comment]
> @pondrejk, I've reviewed some of the tests, and it appears that these failures are not directly related to the changes introduced in PR #13809. It seems that several PRs in between have also encountered similar issues. Reviewing each failure individually and determining its relation to #13809 would be a time-consuming and challenging task for single person.
> 
> Given that the changes have already been merged into the master/stream branch, it would be more efficient to address them post-merge, particularly when backporting to 6.15.z. Holding back this merge solely for the purpose of refactoring in a cherry-pick branch seems unnecessary.

Hi there, "addressing changes post-merge" is exactly what I ask for with regards to master and https://github.com/SatelliteQE/robottelo/pull/13809. It all boils down to how confident you are about your changes not breaking anything. If you don't have a clear picture of your's PRs impact and investigation is too big of a task (which I can definitely relate to), then it is ok to ask POCs for help (I'm willing to), but the request should come from you as well as the coordination of the whole effort. Because if we just merge breaking changes downstream, then it will just pollute results and complicate stuff during already complicated release sign-offs.

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -n 2 tests/foreman/ui/

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 6681
Build Status: UNSTABLE
PRT Comment: pytest -n 2 tests/foreman/ui/ --external-logging
Test Result : = 190 failed, 420 passed, 18 skipped, 16269 warnings, 10 errors in 49528.26s (13:45:28) =
```

**Comment by pondrejk** [comment]
thanks for putting the time in to make sure there is no unexpected impact, much appreciated!

**Pull request merged**
