### PR TITLE
[6.14.z] Add automation for BZ 2168494

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15811

### Problem Statement
Automated BZ 2168494

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 7999
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 2122.12s (0:35:22) ==================
```

**Comment by shweta83** [comment]
The test is failing on selennium grid with some unrelated javascript error failing for all tests for jobinvocation. We need to fix that before merging this. So moving this back to draft.

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 8679
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_leapp_client.py -k test_leapp_preupgrade_report --external-logging
Test Result : ================= 1 failed, 14 warnings in 2177.96s (0:36:17) ==================
```

**Comment by shweta83** [comment]
The failure is unrelated to the change in the PR.

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
