### PR TITLE
Removing stubbed marker

### PR DESCRIPTION
**Pull request by adarshdubey-star**
### Problem Statement
Removing stubbed marker

### CODE REVIEW

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveryrule.py -k test_positive_multi_provision_with_rule_limit

**Comment by shweta83** [comment]
Don't we need to cherrypick to 6.12.z ?

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveryrule.py::test_positive_update_and_provision_with_rule_priority

**Review by Gauravtalreja1 — APPROVED** [review]

**Comment by Gauravtalreja1** [comment]
@shweta83 looking at the PR https://github.com/SatelliteQE/robottelo/pull/12962 adding this test, this test isn't cherrypicked for 6.12.z by @adarshdubey-star , so we're good with current labels for stubbed mark removal here

**Pull request merged**
