### PR TITLE
[DynaConf] Performance settings conversion

### PR DESCRIPTION
**Pull request by jyejare**
- Adding `performance.yaml`
- Updating/Removing some existing validators in performance settings since they are no longer been used anywhere in Robottelo.

### CODE REVIEW

**Review by swadeley — APPROVED** [review]
ACK

**Comment by jyejare** [comment]
@SatelliteQE/tier-2-reviewers Please review !

**Review by devendra104 — APPROVED** [review]
ACK

**Review by ColeHiggins2 — APPROVED** [review]
ACK

**Pull request merged**
