### PR TITLE
Modify provisioning test to check root password is set for provisioned VM

### PR DESCRIPTION
**Pull request by shubhamsg199**
Modifying the provisioning test to check if the root password is set on the provisioned VM.

### CODE REVIEW

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py
provisioning: true

**Comment by shubhamsg199** [comment]
2 rhel9 test failures are not related to this PR, which I'm debugging separately. Tests passes of other branches

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
