### PR TITLE
Fixed Hammer Options

### LINKED ISSUE #5744: tests.foreman.cli.test_hammer.HammerCommandsTestCase.test_positive_all_options
AssertionError:  hammer activation-key content-override   Added options:     * override-name  hammer compute-resource create   Added options:     * domain  hammer compute-resource update   Added options:     * domain  hammer host subscription content-override   Added options:     * override-name   Removed options:     * name  hammer job-invocation info   Removed options:     * name  hammer report delete   Removed options:     * name  hammer report info   Removed options:     * name
Stacktrace
self = <tests.foreman.cli.test_hammer.HammerCommandsTestCase testMethod=test_positive_all_options>

    @tier1
    @upgrade
    def test_positive_all_options(self):
        """check all provided options for every hammer command
    
            :id: 1203ab9f-896d-4039-a166-9e2d36925b5b
    
            :expectedresults: All expected options are present
    
            :CaseImportance: Critical
            """
        self.maxDiff = None
        self._traverse_command_tree()
        if self.differences:
            self.fail(
>               '\n' + _format_commands_diff(self.differences)
            )
E           AssertionError: 
E           hammer activation-key content-override
E             Added options:
E               * override-name
E           
E           hammer compute-resource create
E             Added options:
E               * domain
E           
E           hammer compute-resource update
E             Added options:
E               * domain
E           
E           hammer host subscription content-override
E             Added options:
E               * override-name
E             Removed options:
E               * name
E           
E           hammer job-invocation info
E             Removed options:
E               * name
E           
E           hammer report delete
E             Removed options:
E               * name
E           
E           hammer report info
E             Removed options:
E               * name

tests/foreman/cli/test_hammer.py:156: AssertionError

### PR DESCRIPTION
**Pull request by renzon**
close #5744

Test Result:

```console
=============================================== test session starts ===============================================
platform linux2 -- Python 2.7.14, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/renzo/PycharmProjects/robottelo, inifile:
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.3, cov-2.4.0
collected 1 item                                                                                                   
2018-01-03 14:35:56 - conftest - DEBUG - BZ deselect is disabled in settings


tests/foreman/cli/test_hammer.py .

============================================ 1 passed in 9.37 seconds =============================================
```

This PR can be reviewed but I am just confirmed the exclusion of import sub command with devs prior to  merge this.

### CODE REVIEW

**Comment by renzon** [comment]
@abalakh 

I got the msg from my test and also:

``` console
$ hammer |grep import
 csv                           import to or export from a running foreman server
```

But that is exactly the reason I've labeled this PR as DO NOT MERGE and sent email to dev to confirm what happened ;)

**Comment by abalakh** [comment]
I see DONOTMERGE label got removed, that's why i asked :)

**Comment by renzon** [comment]
@abalakh my bad, I've returned it back ;)

**Comment by ldjebran** [comment]
@abalakh @renzon import command has been removed and we have already removed all the tests related to that command, you can find a related PR https://github.com/SatelliteQE/robottelo/pull/5145 and BZ https://bugzilla.redhat.com/show_bug.cgi?id=1477992

**Comment by renzon** [comment]
Ty @ldjebran, I am removing DO NOT MERGE tag.

**Pull request merged**
